# VN30F1M — kết quả backtest

Notebook gửi payload khai báo trực tiếp bên dưới tới API hiện tại, rồi trình bày dữ liệu, cấu hình, kết quả và lịch sử sự kiện của cùng `run_id`. Chiến lược, cách khớp lệnh và tính tiền lấy nguyên từ payload; notebook chỉ trình bày kết quả backend.

Payload mặc định dùng nến 5 phút, LONG/SHORT, đóng từng phần và mô hình hợp đồng (`contract_v1`): tiền theo VND, số lượng theo hợp đồng. Không tự chuyển dữ liệu thành nến ngày hoặc tính lại tín hiệu/lãi lỗ.

Khởi động API từ thư mục gốc: `.venv/Scripts/python.exe -m uvicorn backtesting_api.main:app --reload`, rồi chạy các ô theo thứ tự bằng kernel `.venv`. Cần các thư viện trong nhóm `notebook` của `pyproject.toml`.

`BACKTEST_API_URL` mặc định là `http://127.0.0.1:8000`; `BACKTEST_REPORT_START` và `BACKTEST_REPORT_END` ghi đè kỳ báo cáo; nếu không đặt, giữ kỳ trong payload hoặc để API xác định từ dữ liệu. Đổi kỳ báo cáo có thể đổi kết quả.

Xem [đặc tả API](../docs/design/backtest-api-specification.md) và [hướng dẫn JSON](../docs/design/strategy-payload-guide.md).

In [2]:
import json
import os
from urllib.error import HTTPError
from urllib.request import Request, urlopen

import pandas as pd
from IPython.display import Markdown, display

API_URL = os.getenv("BACKTEST_API_URL", "http://127.0.0.1:8000").rstrip("/")

## Payload đầu vào

**Chỉ báo và khởi tạo**

- `warmup_bars = 150` nến.
- `sma20`: SMA 20 nến của `market_data.close`.
- `ema5`: EMA 5 nến của `trade_data.close`.
- `trade_sma20`: SMA 20 nến của `trade_data.close`.
- `bb`: Bollinger Bands 20 nến của `trade_data.close`, hệ số độ lệch chuẩn 2.
- `macd`: MACD của `trade_data.close`, chu kỳ nhanh/chậm/tín hiệu = 12/26/9, `histogram = "line"`.
- `mfi14`: MFI 14 nến từ OHLCV của `trade_data`.

**Vào lệnh — `entry`**

- Xét tại Close trong khung 09:05–11:20 hoặc 13:05–14:00; tài khoản đang trống và số lệnh chờ = 0.
- LONG khi **tất cả** điều kiện sau đúng:
  - `market_data.close > sma20`.
  - `ema5 > trade_sma20`.
  - `0 < trade_data.close − bb.upper ≤ 3` điểm.
  - `macd.line > 0` và `macd.line[t] > macd.line[t−1]`.
  - `mfi14 ≥ 55`.
- SHORT khi **tất cả** điều kiện sau đúng:
  - `market_data.close < sma20`.
  - `ema5 < trade_sma20`.
  - `0 < bb.lower − trade_data.close ≤ 3` điểm.
  - `macd.line < 0` và `macd.line[t] < macd.line[t−1]`.
  - `mfi14 ≤ 45`.
- LONG và SHORT cùng đúng → `SIGNAL_CONFLICT`.
- Vào lại: xét từ Close của nến kế tiếp sau nến thoát (`next_bar_close_after_exit`).
- Lệnh chờ hiệu lực tối đa 1 nến; hủy khi vượt nghỉ trưa, mốc ngừng khớp hoặc phiên (`cross_lunch/cross_cutoff/cross_session = false`).

**Thoát lệnh — `exit`**

- LONG: `TP1 = entry_price + 6`, `TP2 = entry_price + 12` điểm.
- SHORT: `TP1 = entry_price − 6`, `TP2 = entry_price − 12` điểm.
- `PROTECTIVE_STOP`: cách giá vào 6 điểm, đóng toàn bộ số hợp đồng còn lại.
- TP1: vị thế ban đầu 1 hợp đồng thì đóng hết; từ 2 hợp đồng thì đóng `floor(initial_quantity / 2)`.
- TP2: sau khi TP1 đã khớp, đóng toàn bộ phần còn lại.
- Trailing stop: kích hoạt sau TP1, cách 6 điểm, khởi tạo từ giá TP1; theo dõi cực trị từ nến sau TP1, cập nhật tại Close và áp dụng từ nến kế tiếp; chọn mức stop chặt nhất (`allow_widening = false`).
- Thoát trong nến: ưu tiên `PROTECTIVE_STOP → TP1 → TP2`.
- Thoát xét tại Close: `MARGIN_BREACH` khi `account.equity < account.required_margin`; `FORCED_EXIT` khi giờ ≥ 14:20; `TIME_STOP` khi `position.held_bars ≥ 18`.
- Thứ tự tại Close: `MARGIN_BREACH → FORCED_EXIT → TIME_STOP`; đóng phần còn lại tại Open kế tiếp.
- Đóng hết vị thế trước 14:30, chỉ giữ vị thế trong ngày (`flat_by = "14:30"`, `allow_overnight = false`).

**Quy mô vị thế — `sizing`**

- `type = "risk_and_margin"`: số hợp đồng theo giới hạn rủi ro và ký quỹ.
- `risk_fraction = 0.01`: ngân sách rủi ro 1%; `stop_points = 6`: khoảng dừng lỗ dùng để tính số hợp đồng.
- `margin_buffer = 1.1`: đệm ký quỹ 10%; `max_contracts = 5`: tối đa 5 hợp đồng; `pyramiding = false`.

**Giới hạn ngày — `daily_limits`**

- Dừng mở vị thế mới khi `day.net_pnl ≤ −2% × day.start_equity` **hoặc** `day.entry_fill_count ≥ 3` lần mở đã khớp trong ngày.

**Khớp lệnh — `execution`**

- `entry_fill_policy = "next_open"`: tín hiệu tại Close → khớp mở vị thế tại Open kế tiếp.
- `slippage_rate = "0"`: trượt giá 0%.

**Mô hình hợp đồng — `accounting`**

`model = "contract"`: giao dịch trên hợp đồng phái sinh, hỗ trợ LONG/SHORT và đóng từng phần. Giá tính theo điểm, tiền theo VND, số lượng theo hợp đồng.

- `contract_multiplier = "100000"`: hệ số 100.000 VND/điểm/hợp đồng.
- `margin_rate = "0.17"`: tỷ lệ ký quỹ 17%.
- `pit_rate = "0.001"`: thuế TNCN 0,1% trên cơ sở tính thuế `giá khớp × hệ số hợp đồng × số hợp đồng × tỷ lệ ký quỹ / 2`.
- `exchange_fee_per_contract = "2700"`: phí sàn 2.700 VND/hợp đồng/lượt khớp.
- `clearing_fee_per_contract = "2550"`: phí bù trừ 2.550 VND/hợp đồng/lượt khớp.
- `broker_fee_per_contract = "0"`: phí môi giới 0 VND/hợp đồng/lượt khớp.

**Vốn ban đầu**

- `initial_cash = "100000000"`: 100 triệu VND.

In [3]:
payload = json.loads(r"""
{
  "trade_data": {
    "symbol": "VN30F1M",
    "resolution": "5",
    "bars": {
      "t": [1773626400,1773626700,1773627000,1773627300,1773627600,1773627900,1773628200,1773628500,1773628800,1773629100,1773629400,1773629700,1773630000,1773630300,1773630600,1773630900,1773631200,1773631500,1773631800,1773632100,1773632400,1773632700,1773633000,1773633300,1773633600,1773633900,1773634200,1773634500,1773634800,1773635100,1773640800,1773641100,1773641400,1773641700,1773642000,1773642300,1773642600,1773642900,1773643200,1773643500,1773643800,1773644100,1773644400,1773644700,1773645000,1773645300,1773645600,1773645900,1773647100,1773712800,1773713100,1773713400,1773713700,1773714000,1773714300,1773714600,1773714900,1773715200,1773715500,1773715800,1773716100,1773716400,1773716700,1773717000,1773717300,1773717600,1773717900,1773718200,1773718500,1773718800,1773719100,1773719400,1773719700,1773720000,1773720300,1773720600,1773720900,1773721200,1773721500,1773727200,1773727500,1773727800,1773728100,1773728400,1773728700,1773729000,1773729300,1773729600,1773729900,1773730200,1773730500,1773730800,1773731100,1773731400,1773731700,1773732000,1773732300,1773733500,1773799200,1773799500,1773799800,1773800100,1773800400,1773800700,1773801000,1773801300,1773801600,1773801900,1773802200,1773802500,1773802800,1773803100,1773803400,1773803700,1773804000,1773804300,1773804600,1773804900,1773805200,1773805500,1773805800,1773806100,1773806400,1773806700,1773807000,1773807300,1773807600,1773807900,1773813600,1773813900,1773814200,1773814500,1773814800,1773815100,1773815400,1773815700,1773816000,1773816300,1773816600,1773816900,1773817200,1773817500,1773817800,1773818100,1773818400,1773818700,1773819900,1773885600,1773885900,1773886200,1773886500,1773886800,1773887100,1773887400,1773887700,1773888000,1773888300,1773888600,1773888900,1773889200,1773889500,1773889800,1773890100,1773890400,1773890700,1773891000,1773891300,1773891600,1773891900,1773892200,1773892500,1773892800,1773893100,1773893400,1773893700,1773894000,1773894300,1773900000,1773900300,1773900600,1773900900,1773901200,1773901500,1773901800,1773902100,1773902400,1773902700,1773903000,1773903300,1773903600,1773903900,1773904200,1773904500,1773904800,1773905100,1773906300,1773972000,1773972300,1773972600,1773972900,1773973200,1773973500,1773973800,1773974100,1773974400,1773974700,1773975000,1773975300,1773975600,1773975900,1773976200,1773976500,1773976800,1773977100,1773977400,1773977700,1773978000,1773978300,1773978600,1773978900,1773979200,1773979500,1773979800,1773980100,1773980400,1773980700,1773986400,1773986700,1773987000,1773987300,1773987600,1773987900,1773988200,1773988500,1773988800,1773989100,1773989400,1773989700,1773990000,1773990300,1773990600,1773990900,1773991200,1773991500,1773992700,1774231200,1774231500,1774231800,1774232100,1774232400,1774232700,1774233000,1774233300,1774233600,1774233900,1774234200,1774234500,1774234800,1774235100,1774235400,1774235700,1774236000,1774236300,1774236600,1774236900,1774237200,1774237500,1774237800,1774238100,1774238400,1774238700,1774239000,1774239300,1774239600,1774239900,1774245600,1774245900,1774246200,1774246500,1774246800,1774247100,1774247400,1774247700,1774248000,1774248300,1774248600,1774248900,1774249200,1774249500,1774249800,1774250100,1774250400,1774250700,1774251900,1774317600,1774317900,1774318200,1774318500,1774318800,1774319100,1774319400,1774319700,1774320000,1774320300,1774320600,1774320900,1774321200,1774321500,1774321800,1774322100,1774322400,1774322700,1774323000,1774323300,1774323600,1774323900,1774324200,1774324500,1774324800,1774325100,1774325400,1774325700,1774326000,1774326300,1774332000,1774332300,1774332600,1774332900,1774333200,1774333500,1774333800,1774334100,1774334400,1774334700,1774335000,1774335300,1774335600,1774335900,1774336200,1774336500,1774336800,1774337100,1774338300,1774404000,1774404300,1774404600,1774404900,1774405200,1774405500,1774405800,1774406100,1774406400,1774406700,1774407000,1774407300,1774407600,1774407900,1774408200,1774408500,1774408800,1774409100,1774409400,1774409700,1774410000,1774410300,1774410600,1774410900,1774411200,1774411500,1774411800,1774412100,1774412400,1774412700,1774418400,1774418700,1774419000,1774419300,1774419600,1774419900,1774420200,1774420500,1774420800,1774421100,1774421400,1774421700,1774422000,1774422300,1774422600,1774422900,1774423200,1774423500,1774424700,1774490400,1774490700,1774491000,1774491300,1774491600,1774491900,1774492200,1774492500,1774492800,1774493100,1774493400,1774493700,1774494000,1774494300,1774494600,1774494900,1774495200,1774495500,1774495800,1774496100,1774496400,1774496700,1774497000,1774497300,1774497600,1774497900,1774498200,1774498500,1774498800,1774499100,1774504800,1774505100,1774505400,1774505700,1774506000,1774506300,1774506600,1774506900,1774507200,1774507500,1774507800,1774508100,1774508400,1774508700,1774509000,1774509300,1774509600,1774509900,1774511100,1774576800,1774577100,1774577400,1774577700,1774578000,1774578300,1774578600,1774578900,1774579200,1774579500,1774579800,1774580100,1774580400,1774580700,1774581000,1774581300,1774581600,1774581900,1774582200,1774582500,1774582800,1774583100,1774583400,1774583700,1774584000,1774584300,1774584600,1774584900,1774585200,1774585500,1774591200,1774591500,1774591800,1774592100,1774592400,1774592700,1774593000,1774593300,1774593600,1774593900,1774594200,1774594500,1774594800,1774595100,1774595400,1774595700,1774596000,1774596300,1774597500,1774836000,1774836300,1774836600,1774836900,1774837200,1774837500,1774837800,1774838100,1774838400,1774838700,1774839000,1774839300,1774839600,1774839900,1774840200,1774840500,1774840800,1774841100,1774841400,1774841700,1774842000,1774842300,1774842600,1774842900,1774843200,1774843500,1774843800,1774844100,1774844400,1774844700,1774850400,1774850700,1774851000,1774851300,1774851600,1774851900,1774852200,1774852500,1774852800,1774853100,1774853400,1774853700,1774854000,1774854300,1774854600,1774854900,1774855200,1774855500,1774856700,1774922400,1774922700,1774923000,1774923300,1774923600,1774923900,1774924200,1774924500,1774924800,1774925100,1774925400,1774925700,1774926000,1774926300,1774926600,1774926900,1774927200,1774927500,1774927800,1774928100,1774928400,1774928700,1774929000,1774929300,1774929600,1774929900,1774930200,1774930500,1774930800,1774931100,1774936800,1774937100,1774937400,1774937700,1774938000,1774938300,1774938600,1774938900,1774939200,1774939500,1774939800,1774940100,1774940400,1774940700,1774941000,1774941300,1774941600,1774941900,1774943100,1775008800,1775009100,1775009400,1775009700,1775010000,1775010300,1775010600,1775010900,1775011200,1775011500,1775011800,1775012100,1775012400,1775012700,1775013000,1775013300,1775013600,1775013900,1775014200,1775014500,1775014800,1775015100,1775015400,1775015700,1775016000,1775016300,1775016600,1775016900,1775017200,1775017500,1775023200,1775023500,1775023800,1775024100,1775024400,1775024700,1775025000,1775025300,1775025600,1775025900,1775026200,1775026500,1775026800,1775027100,1775027400,1775027700,1775028000,1775028300,1775029500,1775095200,1775095500,1775095800,1775096100,1775096400,1775096700,1775097000,1775097300,1775097600,1775097900,1775098200,1775098500,1775098800,1775099100,1775099400,1775099700,1775100000,1775100300,1775100600,1775100900,1775101200,1775101500,1775101800,1775102100,1775102400,1775102700,1775103000,1775103300,1775103600,1775103900,1775109600,1775109900,1775110200,1775110500,1775110800,1775111100,1775111400,1775111700,1775112000,1775112300,1775112600,1775112900,1775113200,1775113500,1775113800,1775114100,1775114400,1775114700,1775115900,1775181600,1775181900,1775182200,1775182500,1775182800,1775183100,1775183400,1775183700,1775184000,1775184300,1775184600,1775184900,1775185200,1775185500,1775185800,1775186100,1775186400,1775186700,1775187000,1775187300,1775187600,1775187900,1775188200,1775188500,1775188800,1775189100,1775189400,1775189700,1775190000,1775190300,1775196000,1775196300,1775196600,1775196900,1775197200,1775197500,1775197800,1775198100,1775198400,1775198700,1775199000,1775199300,1775199600,1775199900,1775200200,1775200500,1775200800,1775201100,1775202300,1775440800,1775441100,1775441400,1775441700,1775442000,1775442300,1775442600,1775442900,1775443200,1775443500,1775443800,1775444100,1775444400,1775444700,1775445000,1775445300,1775445600,1775445900,1775446200,1775446500,1775446800,1775447100,1775447400,1775447700,1775448000,1775448300,1775448600,1775448900,1775449200,1775449500,1775455200,1775455500,1775455800,1775456100,1775456400,1775456700,1775457000,1775457300,1775457600,1775457900,1775458200,1775458500,1775458800,1775459100,1775459400,1775459700,1775460000,1775460300,1775461500,1775527200,1775527500,1775527800,1775528100,1775528400,1775528700,1775529000,1775529300,1775529600,1775529900,1775530200,1775530500,1775530800,1775531100,1775531400,1775531700,1775532000,1775532300,1775532600,1775532900,1775533200,1775533500,1775533800,1775534100,1775534400,1775534700,1775535000,1775535300,1775535600,1775535900,1775541600,1775541900,1775542200,1775542500,1775542800,1775543100,1775543400,1775543700,1775544000,1775544300,1775544600,1775544900,1775545200,1775545500,1775545800,1775546100,1775546400,1775546700,1775547900,1775613600,1775613900,1775614200,1775614500,1775614800,1775615100,1775615400,1775615700,1775616000,1775616300,1775616600,1775616900,1775617200,1775617500,1775617800,1775618100,1775618400,1775618700,1775619000,1775619300,1775619600,1775619900,1775620200,1775620500,1775620800,1775621100,1775621400,1775621700,1775622000,1775622300,1775628000,1775628300,1775628600,1775628900,1775629200,1775629500,1775629800,1775630100,1775630400,1775630700,1775631000,1775631300,1775631600,1775631900,1775632200,1775632500,1775632800,1775633100,1775634300,1775700000,1775700300,1775700600,1775700900,1775701200,1775701500,1775701800,1775702100,1775702400,1775702700,1775703000,1775703300,1775703600,1775703900,1775704200,1775704500,1775704800,1775705100,1775705400,1775705700,1775706000,1775706300,1775706600,1775706900,1775707200,1775707500,1775707800,1775708100,1775708400,1775708700,1775714400,1775714700,1775715000,1775715300,1775715600,1775715900,1775716200,1775716500,1775716800,1775717100,1775717400,1775717700,1775718000,1775718300,1775718600,1775718900,1775719200,1775719500,1775720700,1775786400,1775786700,1775787000,1775787300,1775787600,1775787900,1775788200,1775788500,1775788800,1775789100,1775789400,1775789700,1775790000,1775790300,1775790600,1775790900,1775791200,1775791500,1775791800,1775792100,1775792400,1775792700,1775793000,1775793300,1775793600,1775793900,1775794200,1775794500,1775794800,1775795100,1775800800,1775801100,1775801400,1775801700,1775802000,1775802300,1775802600,1775802900,1775803200,1775803500,1775803800,1775804100,1775804400,1775804700,1775805000,1775805300,1775805600,1775805900,1775807100,1776045600,1776045900,1776046200,1776046500,1776046800,1776047100,1776047400,1776047700,1776048000,1776048300,1776048600,1776048900,1776049200,1776049500,1776049800,1776050100,1776050400,1776050700,1776051000,1776051300,1776051600,1776051900,1776052200,1776052500,1776052800,1776053100,1776053400,1776053700,1776054000,1776054300,1776060000,1776060300,1776060600,1776060900,1776061200,1776061500,1776061800,1776062100,1776062400,1776062700,1776063000,1776063300,1776063600,1776063900,1776064200,1776064500,1776064800,1776065100,1776066300,1776132000,1776132300,1776132600,1776132900,1776133200,1776133500,1776133800,1776134100,1776134400,1776134700,1776135000,1776135300,1776135600,1776135900,1776136200,1776136500,1776136800,1776137100,1776137400,1776137700,1776138000,1776138300,1776138600,1776138900,1776139200,1776139500,1776139800,1776140100,1776140400,1776140700,1776146400,1776146700,1776147000,1776147300,1776147600,1776147900,1776148200,1776148500,1776148800,1776149100,1776149400,1776149700,1776150000,1776150300,1776150600,1776150900,1776151200,1776151500,1776152700,1776218400,1776218700,1776219000,1776219300,1776219600,1776219900,1776220200,1776220500,1776220800,1776221100,1776221400,1776221700,1776222000,1776222300,1776222600,1776222900,1776223200,1776223500,1776223800,1776224100,1776224400,1776224700,1776225000,1776225300,1776225600,1776225900,1776226200,1776226500,1776226800,1776227100,1776232800,1776233100,1776233400,1776233700,1776234000,1776234300,1776234600,1776234900,1776235200,1776235500,1776235800,1776236100,1776236400,1776236700,1776237000,1776237300,1776237600,1776237900,1776239100,1776304800,1776305100,1776305400,1776305700,1776306000,1776306300,1776306600,1776306900,1776307200,1776307500,1776307800,1776308100,1776308400,1776308700,1776309000,1776309300,1776309600,1776309900,1776310200,1776310500,1776310800,1776311100,1776311400,1776311700,1776312000,1776312300,1776312600,1776312900,1776313200,1776313500,1776319200,1776319500,1776319800,1776320100,1776320400,1776320700,1776321000,1776321300,1776321600,1776321900,1776322200,1776322500,1776322800,1776323100,1776323400,1776323700,1776324000,1776324300,1776325500,1776391200,1776391500,1776391800,1776392100,1776392400,1776392700,1776393000,1776393300,1776393600,1776393900,1776394200,1776394500,1776394800,1776395100,1776395400,1776395700,1776396000,1776396300,1776396600,1776396900,1776397200,1776397500,1776397800,1776398100,1776398400,1776398700,1776399000,1776399300,1776399600,1776399900,1776405600,1776405900,1776406200,1776406500,1776406800,1776407100,1776407400,1776407700,1776408000,1776408300,1776408600,1776408900,1776409200,1776409500,1776409800,1776410100,1776410400,1776410700,1776411900,1776650400,1776650700,1776651000,1776651300,1776651600,1776651900,1776652200,1776652500,1776652800,1776653100,1776653400,1776653700,1776654000,1776654300,1776654600,1776654900,1776655200,1776655500,1776655800,1776656100,1776656400,1776656700,1776657000,1776657300,1776657600,1776657900,1776658200,1776658500,1776658800,1776659100,1776664800,1776665100,1776665400,1776665700,1776666000,1776666300,1776666600,1776666900,1776667200,1776667500,1776667800,1776668100,1776668400,1776668700,1776669000,1776669300,1776669600,1776669900,1776671100,1776736800,1776737100,1776737400,1776737700,1776738000,1776738300,1776738600,1776738900,1776739200,1776739500,1776739800,1776740100,1776740400,1776740700,1776741000,1776741300,1776741600,1776741900,1776742200,1776742500,1776742800,1776743100,1776743400,1776743700,1776744000,1776744300,1776744600,1776744900,1776745200,1776745500,1776751200,1776751500,1776751800,1776752100,1776752400,1776752700,1776753000,1776753300,1776753600,1776753900,1776754200,1776754500,1776754800,1776755100,1776755400,1776755700,1776756000,1776756300,1776757500,1776823200,1776823500,1776823800,1776824100,1776824400,1776824700,1776825000,1776825300,1776825600,1776825900,1776826200,1776826500,1776826800,1776827100,1776827400,1776827700,1776828000,1776828300,1776828600,1776828900,1776829200,1776829500,1776829800,1776830100,1776830400,1776830700,1776831000,1776831300,1776831600,1776831900,1776837600,1776837900,1776838200,1776838500,1776838800,1776839100,1776839400,1776839700,1776840000,1776840300,1776840600,1776840900,1776841200,1776841500,1776841800,1776842100,1776842400,1776842700,1776843900,1776909600,1776909900,1776910200,1776910500,1776910800,1776911100,1776911400,1776911700,1776912000,1776912300,1776912600,1776912900,1776913200,1776913500,1776913800,1776914100,1776914400,1776914700,1776915000,1776915300,1776915600,1776915900,1776916200,1776916500,1776916800,1776917100,1776917400,1776917700,1776918000,1776918300,1776924000,1776924300,1776924600,1776924900,1776925200,1776925500,1776925800,1776926100,1776926400,1776926700,1776927000,1776927300,1776927600,1776927900,1776928200,1776928500,1776928800,1776929100,1776930300,1776996000,1776996300,1776996600,1776996900,1776997200,1776997500,1776997800,1776998100,1776998400,1776998700,1776999000,1776999300,1776999600,1776999900,1777000200,1777000500,1777000800,1777001100,1777001400,1777001700,1777002000,1777002300,1777002600,1777002900,1777003200,1777003500,1777003800,1777004100,1777004400,1777004700,1777010400,1777010700,1777011000,1777011300,1777011600,1777011900,1777012200,1777012500,1777012800,1777013100,1777013400,1777013700,1777014000,1777014300,1777014600,1777014900,1777015200,1777015500,1777016700,1777341600,1777341900,1777342200,1777342500,1777342800,1777343100,1777343400,1777343700,1777344000,1777344300,1777344600,1777344900,1777345200,1777345500,1777345800,1777346100,1777346400,1777346700,1777347000,1777347300,1777347600,1777347900,1777348200,1777348500,1777348800,1777349100,1777349400,1777349700,1777350000,1777350300,1777356000,1777356300,1777356600,1777356900,1777357200,1777357500,1777357800,1777358100,1777358400,1777358700,1777359000,1777359300,1777359600,1777359900,1777360200,1777360500,1777360800,1777361100,1777362300,1777428000,1777428300,1777428600,1777428900,1777429200,1777429500,1777429800,1777430100,1777430400,1777430700,1777431000,1777431300,1777431600,1777431900,1777432200,1777432500,1777432800,1777433100,1777433400,1777433700,1777434000,1777434300,1777434600,1777434900,1777435200,1777435500,1777435800,1777436100,1777436400,1777436700,1777442400,1777442700,1777443000,1777443300,1777443600,1777443900,1777444200,1777444500,1777444800,1777445100,1777445400,1777445700,1777446000,1777446300,1777446600,1777446900,1777447200,1777447500,1777448700,1777860000,1777860300,1777860600,1777860900,1777861200,1777861500,1777861800,1777862100,1777862400,1777862700,1777863000,1777863300,1777863600,1777863900,1777864200,1777864500,1777864800,1777865100,1777865400,1777865700,1777866000,1777866300,1777866600,1777866900,1777867200,1777867500,1777867800,1777868100,1777868400,1777868700,1777874400,1777874700,1777875000,1777875300,1777875600,1777875900,1777876200,1777876500,1777876800,1777877100,1777877400,1777877700,1777878000,1777878300,1777878600,1777878900,1777879200,1777879500,1777880700,1777946400,1777946700,1777947000,1777947300,1777947600,1777947900,1777948200,1777948500,1777948800,1777949100,1777949400,1777949700,1777950000,1777950300,1777950600,1777950900,1777951200,1777951500,1777951800,1777952100,1777952400,1777952700,1777953000,1777953300,1777953600,1777953900,1777954200,1777954500,1777954800,1777955100,1777960800,1777961100,1777961400,1777961700,1777962000,1777962300,1777962600,1777962900,1777963200,1777963500,1777963800,1777964100,1777964400,1777964700,1777965000,1777965300,1777965600,1777965900,1777967100,1778032800,1778033100,1778033400,1778033700,1778034000,1778034300,1778034600,1778034900,1778035200,1778035500,1778035800,1778036100,1778036400,1778036700,1778037000,1778037300,1778037600,1778037900,1778038200,1778038500,1778038800,1778039100,1778039400,1778039700,1778040000,1778040300,1778040600,1778040900,1778041200,1778041500,1778047200,1778047500,1778047800,1778048100,1778048400,1778048700,1778049000,1778049300,1778049600,1778049900,1778050200,1778050500,1778050800,1778051100,1778051400,1778051700,1778052000,1778052300,1778053500,1778119200,1778119500,1778119800,1778120100,1778120400,1778120700,1778121000,1778121300,1778121600,1778121900,1778122200,1778122500,1778122800,1778123100,1778123400,1778123700,1778124000,1778124300,1778124600,1778124900,1778125200,1778125500,1778125800,1778126100,1778126400,1778126700,1778127000,1778127300,1778127600,1778127900,1778133600,1778133900,1778134200,1778134500,1778134800,1778135100,1778135400,1778135700,1778136000,1778136300,1778136600,1778136900,1778137200,1778137500,1778137800,1778138100,1778138400,1778138700,1778139900,1778205600,1778205900,1778206200,1778206500,1778206800,1778207100,1778207400,1778207700,1778208000,1778208300,1778208600,1778208900,1778209200,1778209500,1778209800,1778210100,1778210400,1778210700,1778211000,1778211300,1778211600,1778211900,1778212200,1778212500,1778212800,1778213100,1778213400,1778213700,1778214000,1778214300,1778220000,1778220300,1778220600,1778220900,1778221200,1778221500,1778221800,1778222100,1778222400,1778222700,1778223000,1778223300,1778223600,1778223900,1778224200,1778224500,1778224800,1778225100,1778226300,1778464800,1778465100,1778465400,1778465700,1778466000,1778466300,1778466600,1778466900,1778467200,1778467500,1778467800,1778468100,1778468400,1778468700,1778469000,1778469300,1778469600,1778469900,1778470200,1778470500,1778470800,1778471100,1778471400,1778471700,1778472000,1778472300,1778472600,1778472900,1778473200,1778473500,1778479200,1778479500,1778479800,1778480100,1778480400,1778480700,1778481000,1778481300,1778481600,1778481900,1778482200,1778482500,1778482800,1778483100,1778483400,1778483700,1778484000,1778484300,1778485500,1778551200,1778551500,1778551800,1778552100,1778552400,1778552700,1778553000,1778553300,1778553600,1778553900,1778554200,1778554500,1778554800,1778555100,1778555400,1778555700,1778556000,1778556300,1778556600,1778556900,1778557200,1778557500,1778557800,1778558100,1778558400,1778558700,1778559000,1778559300,1778559600,1778559900,1778565600,1778565900,1778566200,1778566500,1778566800,1778567100,1778567400,1778567700,1778568000,1778568300,1778568600,1778568900,1778569200,1778569500,1778569800,1778570100,1778570400,1778570700,1778571900,1778637600,1778637900,1778638200,1778638500,1778638800,1778639100,1778639400,1778639700,1778640000,1778640300,1778640600,1778640900,1778641200,1778641500,1778641800,1778642100,1778642400,1778642700,1778643000,1778643300,1778643600,1778643900,1778644200,1778644500,1778644800,1778645100,1778645400,1778645700,1778646000,1778646300,1778652000,1778652300,1778652600,1778652900,1778653200,1778653500,1778653800,1778654100,1778654400,1778654700,1778655000,1778655300,1778655600,1778655900,1778656200,1778656500,1778656800,1778657100,1778658300,1778724000,1778724300,1778724600,1778724900,1778725200,1778725500,1778725800,1778726100,1778726400,1778726700,1778727000,1778727300,1778727600,1778727900,1778728200,1778728500,1778728800,1778729100,1778729400,1778729700,1778730000,1778730300,1778730600,1778730900,1778731200,1778731500,1778731800,1778732100,1778732400,1778732700,1778738400,1778738700,1778739000,1778739300,1778739600,1778739900,1778740200,1778740500,1778740800,1778741100,1778741400,1778741700,1778742000,1778742300,1778742600,1778742900,1778743200,1778743500,1778744700,1778810400,1778810700,1778811000,1778811300,1778811600,1778811900,1778812200,1778812500,1778812800,1778813100,1778813400,1778813700,1778814000,1778814300,1778814600,1778814900,1778815200,1778815500,1778815800,1778816100,1778816400,1778816700,1778817000,1778817300,1778817600,1778817900,1778818200,1778818500,1778818800,1778819100,1778824800,1778825100,1778825400,1778825700,1778826000,1778826300,1778826600,1778826900,1778827200,1778827500,1778827800,1778828100,1778828400,1778828700,1778829000,1778829300,1778829600,1778829900,1778831100,1779069600,1779069900,1779070200,1779070500,1779070800,1779071100,1779071400,1779071700,1779072000,1779072300,1779072600,1779072900,1779073200,1779073500,1779073800,1779074100,1779074400,1779074700,1779075000,1779075300,1779075600,1779075900,1779076200,1779076500,1779076800,1779077100,1779077400,1779077700,1779078000,1779078300,1779084000,1779084300,1779084600,1779084900,1779085200,1779085500,1779085800,1779086100,1779086400,1779086700,1779087000,1779087300,1779087600,1779087900,1779088200,1779088500,1779088800,1779089100,1779090300,1779156000,1779156300,1779156600,1779156900,1779157200,1779157500,1779157800,1779158100,1779158400,1779158700,1779159000,1779159300,1779159600,1779159900,1779160200,1779160500,1779160800,1779161100,1779161400,1779161700,1779162000,1779162300,1779162600,1779162900,1779163200,1779163500,1779163800,1779164100,1779164400,1779164700,1779170400,1779170700,1779171000,1779171300,1779171600,1779171900,1779172200,1779172500,1779172800,1779173100,1779173400,1779173700,1779174000,1779174300,1779174600,1779174900,1779175200,1779175500,1779176700,1779242400,1779242700,1779243000,1779243300,1779243600,1779243900,1779244200,1779244500,1779244800,1779245100,1779245400,1779245700,1779246000,1779246300,1779246600,1779246900,1779247200,1779247500,1779247800,1779248100,1779248400,1779248700,1779249000,1779249300,1779249600,1779249900,1779250200,1779250500,1779250800,1779251100,1779256800,1779257100,1779257400,1779257700,1779258000,1779258300,1779258600,1779258900,1779259200,1779259500,1779259800,1779260100,1779260400,1779260700,1779261000,1779261300,1779261600,1779261900,1779263100,1779328800,1779329100,1779329400,1779329700,1779330000,1779330300,1779330600,1779330900,1779331200,1779331500,1779331800,1779332100,1779332400,1779332700,1779333000,1779333300,1779333600,1779333900,1779334200,1779334500,1779334800,1779335100,1779335400,1779335700,1779336000,1779336300,1779336600,1779336900,1779337200,1779337500,1779343200,1779343500,1779343800,1779344100,1779344400,1779344700,1779345000,1779345300,1779345600,1779345900,1779346200,1779346500,1779346800,1779347100,1779347400,1779347700,1779348000,1779348300,1779349500,1779415200,1779415500,1779415800,1779416100,1779416400,1779416700,1779417000,1779417300,1779417600,1779417900,1779418200,1779418500,1779418800,1779419100,1779419400,1779419700,1779420000,1779420300,1779420600,1779420900,1779421200,1779421500,1779421800,1779422100,1779422400,1779422700,1779423000,1779423300,1779423600,1779423900,1779429600,1779429900,1779430200,1779430500,1779430800,1779431100,1779431400,1779431700,1779432000,1779432300,1779432600,1779432900,1779433200,1779433500,1779433800,1779434100,1779434400,1779434700,1779435900,1779674400,1779674700,1779675000,1779675300,1779675600,1779675900,1779676200,1779676500,1779676800,1779677100,1779677400,1779677700,1779678000,1779678300,1779678600,1779678900,1779679200,1779679500,1779679800,1779680100,1779680400,1779680700,1779681000,1779681300,1779681600,1779681900,1779682200,1779682500,1779682800,1779683100,1779688800,1779689100,1779689400,1779689700,1779690000,1779690300,1779690600,1779690900,1779691200,1779691500,1779691800,1779692100,1779692400,1779692700,1779693000,1779693300,1779693600,1779693900,1779695100,1779760800,1779761100,1779761400,1779761700,1779762000,1779762300,1779762600,1779762900,1779763200,1779763500,1779763800,1779764100,1779764400,1779764700,1779765000,1779765300,1779765600,1779765900,1779766200,1779766500,1779766800,1779767100,1779767400,1779767700,1779768000,1779768300,1779768600,1779768900,1779769200,1779769500,1779775200,1779775500,1779775800,1779776100,1779776400,1779776700,1779777000,1779777300,1779777600,1779777900,1779778200,1779778500,1779778800,1779779100,1779779400,1779779700,1779780000,1779780300,1779781500,1779847200,1779847500,1779847800,1779848100,1779848400,1779848700,1779849000,1779849300,1779849600,1779849900,1779850200,1779850500,1779850800,1779851100,1779851400,1779851700,1779852000,1779852300,1779852600,1779852900,1779853200,1779853500,1779853800,1779854100,1779854400,1779854700,1779855000,1779855300,1779855600,1779855900,1779861600,1779861900,1779862200,1779862500,1779862800,1779863100,1779863400,1779863700,1779864000,1779864300,1779864600,1779864900,1779865200,1779865500,1779865800,1779866100,1779866400,1779866700,1779867900,1779933600,1779933900,1779934200,1779934500,1779934800,1779935100,1779935400,1779935700,1779936000,1779936300,1779936600,1779936900,1779937200,1779937500,1779937800,1779938100,1779938400,1779938700,1779939000,1779939300,1779939600,1779939900,1779940200,1779940500,1779940800,1779941100,1779941400,1779941700,1779942000,1779942300,1779948000,1779948300,1779948600,1779948900,1779949200,1779949500,1779949800,1779950100,1779950400,1779950700,1779951000,1779951300,1779951600,1779951900,1779952200,1779952500,1779952800,1779953100,1779954300,1780020000,1780020300,1780020600,1780020900,1780021200,1780021500,1780021800,1780022100,1780022400,1780022700,1780023000,1780023300,1780023600,1780023900,1780024200,1780024500,1780024800,1780025100,1780025400,1780025700,1780026000,1780026300,1780026600,1780026900,1780027200,1780027500,1780027800,1780028100,1780028400,1780028700,1780034400,1780034700,1780035000,1780035300,1780035600,1780035900,1780036200,1780036500,1780036800,1780037100,1780037400,1780037700,1780038000,1780038300,1780038600,1780038900,1780039200,1780039500,1780040700,1780279200,1780279500,1780279800,1780280100,1780280400,1780280700,1780281000,1780281300,1780281600,1780281900,1780282200,1780282500,1780282800,1780283100,1780283400,1780283700,1780284000,1780284300,1780284600,1780284900,1780285200,1780285500,1780285800,1780286100,1780286400,1780286700,1780287000,1780287300,1780287600,1780287900,1780293600,1780293900,1780294200,1780294500,1780294800,1780295100,1780295400,1780295700,1780296000,1780296300,1780296600,1780296900,1780297200,1780297500,1780297800,1780298100,1780298400,1780298700,1780299900,1780365600,1780365900,1780366200,1780366500,1780366800,1780367100,1780367400,1780367700,1780368000,1780368300,1780368600,1780368900,1780369200,1780369500,1780369800,1780370100,1780370400,1780370700,1780371000,1780371300,1780371600,1780371900,1780372200,1780372500,1780372800,1780373100,1780373400,1780373700,1780374000,1780374300,1780380000,1780380300,1780380600,1780380900,1780381200,1780381500,1780381800,1780382100,1780382400,1780382700,1780383000,1780383300,1780383600,1780383900,1780384200,1780384500,1780384800,1780385100,1780386300,1780452000,1780452300,1780452600,1780452900,1780453200,1780453500,1780453800,1780454100,1780454400,1780454700,1780455000,1780455300,1780455600,1780455900,1780456200,1780456500,1780456800,1780457100,1780457400,1780457700,1780458000,1780458300,1780458600,1780458900,1780459200,1780459500,1780459800,1780460100,1780460400,1780460700,1780466400,1780466700,1780467000,1780467300,1780467600,1780467900,1780468200,1780468500,1780468800,1780469100,1780469400,1780469700,1780470000,1780470300,1780470600,1780470900,1780471200,1780471500,1780472700,1780538400,1780538700,1780539000,1780539300,1780539600,1780539900,1780540200,1780540500,1780540800,1780541100,1780541400,1780541700,1780542000,1780542300,1780542600,1780542900,1780543200,1780543500,1780543800,1780544100,1780544400,1780544700,1780545000,1780545300,1780545600,1780545900,1780546200,1780546500,1780546800,1780547100,1780552800,1780553100,1780553400,1780553700,1780554000,1780554300,1780554600,1780554900,1780555200,1780555500,1780555800,1780556100,1780556400,1780556700,1780557000,1780557300,1780557600,1780557900,1780559100,1780624800,1780625100,1780625400,1780625700,1780626000,1780626300,1780626600,1780626900,1780627200,1780627500,1780627800,1780628100,1780628400,1780628700,1780629000,1780629300,1780629600,1780629900,1780630200,1780630500,1780630800,1780631100,1780631400,1780631700,1780632000,1780632300,1780632600,1780632900,1780633200,1780633500,1780639200,1780639500,1780639800,1780640100,1780640400,1780640700,1780641000,1780641300,1780641600,1780641900,1780642200,1780642500,1780642800,1780643100,1780643400,1780643700,1780644000,1780644300,1780645500,1780884000,1780884300,1780884600,1780884900,1780885200,1780885500,1780885800,1780886100,1780886400,1780886700,1780887000,1780887300,1780887600,1780887900,1780888200,1780888500,1780888800,1780889100,1780889400,1780889700,1780890000,1780890300,1780890600,1780890900,1780891200,1780891500,1780891800,1780892100,1780892400,1780892700,1780898400,1780898700,1780899000,1780899300,1780899600,1780899900,1780900200,1780900500,1780900800,1780901100,1780901400,1780901700,1780902000,1780902300,1780902600,1780902900,1780903200,1780903500,1780904700,1780970400,1780970700,1780971000,1780971300,1780971600,1780971900,1780972200,1780972500,1780972800,1780973100,1780973400,1780973700,1780974000,1780974300,1780974600,1780974900,1780975200,1780975500,1780975800,1780976100,1780976400,1780976700,1780977000,1780977300,1780977600,1780977900,1780978200,1780978500,1780978800,1780979100,1780984800,1780985100,1780985400,1780985700,1780986000,1780986300,1780986600,1780986900,1780987200,1780987500,1780987800,1780988100,1780988400,1780988700,1780989000,1780989300,1780989600,1780989900,1780991100,1781056800,1781057100,1781057400,1781057700,1781058000,1781058300,1781058600,1781058900,1781059200,1781059500,1781059800,1781060100,1781060400,1781060700,1781061000,1781061300,1781061600,1781061900,1781062200,1781062500,1781062800,1781063100,1781063400,1781063700,1781064000,1781064300,1781064600,1781064900,1781065200,1781065500,1781071200,1781071500,1781071800,1781072100,1781072400,1781072700,1781073000,1781073300,1781073600,1781073900,1781074200,1781074500,1781074800,1781075100,1781075400,1781075700,1781076000,1781076300,1781077500,1781143200,1781143500,1781143800,1781144100,1781144400,1781144700,1781145000,1781145300,1781145600,1781145900,1781146200,1781146500,1781146800,1781147100,1781147400,1781147700,1781148000,1781148300,1781148600,1781148900,1781149200,1781149500,1781149800,1781150100,1781150400,1781150700,1781151000,1781151300,1781151600,1781151900,1781157600,1781157900,1781158200,1781158500,1781158800,1781159100,1781159400,1781159700,1781160000,1781160300,1781160600,1781160900,1781161200,1781161500,1781161800,1781162100,1781162400,1781162700,1781163900,1781229600,1781229900,1781230200,1781230500,1781230800,1781231100,1781231400,1781231700,1781232000,1781232300,1781232600,1781232900,1781233200,1781233500,1781233800,1781234100,1781234400,1781234700,1781235000,1781235300,1781235600,1781235900,1781236200,1781236500,1781236800,1781237100,1781237400,1781237700,1781238000,1781238300,1781244000,1781244300,1781244600,1781244900,1781245200,1781245500,1781245800,1781246100,1781246400,1781246700,1781247000,1781247300,1781247600,1781247900,1781248200,1781248500,1781248800,1781249100,1781250300,1781488800,1781489100,1781489400,1781489700,1781490000,1781490300,1781490600,1781490900,1781491200,1781491500,1781491800,1781492100,1781492400,1781492700,1781493000,1781493300,1781493600,1781493900,1781494200,1781494500,1781494800,1781495100,1781495400,1781495700,1781496000,1781496300,1781496600,1781496900,1781497200,1781497500,1781503200,1781503500,1781503800,1781504100,1781504400,1781504700,1781505000,1781505300,1781505600,1781505900,1781506200,1781506500,1781506800,1781507100,1781507400,1781507700,1781508000,1781508300,1781509500,1781575200,1781575500,1781575800,1781576100,1781576400,1781576700,1781577000,1781577300,1781577600,1781577900,1781578200,1781578500,1781578800,1781579100,1781579400,1781579700,1781580000,1781580300,1781580600,1781580900,1781581200,1781581500,1781581800,1781582100,1781582400,1781582700,1781583000,1781583300,1781583600,1781583900,1781589600,1781589900,1781590200,1781590500,1781590800,1781591100,1781591400,1781591700,1781592000,1781592300,1781592600,1781592900,1781593200,1781593500,1781593800,1781594100,1781594400,1781594700,1781595900,1781661600,1781661900,1781662200,1781662500,1781662800,1781663100,1781663400,1781663700,1781664000,1781664300,1781664600,1781664900,1781665200,1781665500,1781665800,1781666100,1781666400,1781666700,1781667000,1781667300,1781667600,1781667900,1781668200,1781668500,1781668800,1781669100,1781669400,1781669700,1781670000,1781670300,1781676000,1781676300,1781676600,1781676900,1781677200,1781677500,1781677800,1781678100,1781678400,1781678700,1781679000,1781679300,1781679600,1781679900,1781680200,1781680500,1781680800,1781681100,1781682300,1781748000,1781748300,1781748600,1781748900,1781749200,1781749500,1781749800,1781750100,1781750400,1781750700,1781751000,1781751300,1781751600,1781751900,1781752200,1781752500,1781752800,1781753100,1781753400,1781753700,1781754000,1781754300,1781754600,1781754900,1781755200,1781755500,1781755800,1781756100,1781756400,1781756700,1781762400,1781762700,1781763000,1781763300,1781763600,1781763900,1781764200,1781764500,1781764800,1781765100,1781765400,1781765700,1781766000,1781766300,1781766600,1781766900,1781767200,1781767500,1781768700,1781834400,1781834700,1781835000,1781835300,1781835600,1781835900,1781836200,1781836500,1781836800,1781837100,1781837400,1781837700,1781838000,1781838300,1781838600,1781838900,1781839200,1781839500,1781839800,1781840100,1781840400,1781840700,1781841000,1781841300,1781841600,1781841900,1781842200,1781842500,1781842800,1781843100,1781848800,1781849100,1781849400,1781849700,1781850000,1781850300,1781850600,1781850900,1781851200,1781851500,1781851800,1781852100,1781852400,1781852700,1781853000,1781853300,1781853600,1781853900,1781855100,1782093600,1782093900,1782094200,1782094500,1782094800,1782095100,1782095400,1782095700,1782096000,1782096300,1782096600,1782096900,1782097200,1782097500,1782097800,1782098100,1782098400,1782098700,1782099000,1782099300,1782099600,1782099900,1782100200,1782100500,1782100800,1782101100,1782101400,1782101700,1782102000,1782102300,1782108000,1782108300,1782108600,1782108900,1782109200,1782109500,1782109800,1782110100,1782110400,1782110700,1782111000,1782111300,1782111600,1782111900,1782112200,1782112500,1782112800,1782113100,1782114300,1782180000,1782180300,1782180600,1782180900,1782181200,1782181500,1782181800,1782182100,1782182400,1782182700,1782183000,1782183300,1782183600,1782183900,1782184200,1782184500,1782184800,1782185100,1782185400,1782185700,1782186000,1782186300,1782186600,1782186900,1782187200,1782187500,1782187800,1782188100,1782188400,1782188700,1782194400,1782194700,1782195000,1782195300,1782195600,1782195900,1782196200,1782196500,1782196800,1782197100,1782197400,1782197700,1782198000,1782198300,1782198600,1782198900,1782199200,1782199500,1782200700,1782266400,1782266700,1782267000,1782267300,1782267600,1782267900,1782268200,1782268500,1782268800,1782269100,1782269400,1782269700,1782270000,1782270300,1782270600,1782270900,1782271200,1782271500,1782271800,1782272100,1782272400,1782272700,1782273000,1782273300,1782273600,1782273900,1782274200,1782274500,1782274800,1782275100,1782280800,1782281100,1782281400,1782281700,1782282000,1782282300,1782282600,1782282900,1782283200,1782283500,1782283800,1782284100,1782284400,1782284700,1782285000,1782285300,1782285600,1782285900,1782287100,1782352800,1782353100,1782353400,1782353700,1782354000,1782354300,1782354600,1782354900,1782355200,1782355500,1782355800,1782356100,1782356400,1782356700,1782357000,1782357300,1782357600,1782357900,1782358200,1782358500,1782358800,1782359100,1782359400,1782359700,1782360000,1782360300,1782360600,1782360900,1782361200,1782361500,1782367200,1782367500,1782367800,1782368100,1782368400,1782368700,1782369000,1782369300,1782369600,1782369900,1782370200,1782370500,1782370800,1782371100,1782371400,1782371700,1782372000,1782372300,1782373500,1782439200,1782439500,1782439800,1782440100,1782440400,1782440700,1782441000,1782441300,1782441600,1782441900,1782442200,1782442500,1782442800,1782443100,1782443400,1782443700,1782444000,1782444300,1782444600,1782444900,1782445200,1782445500,1782445800,1782446100,1782446400,1782446700,1782447000,1782447300,1782447600,1782447900,1782453600,1782453900,1782454200,1782454500,1782454800,1782455100,1782455400,1782455700,1782456000,1782456300,1782456600,1782456900,1782457200,1782457500,1782457800,1782458100,1782458400,1782458700,1782459900,1782698400,1782698700,1782699000,1782699300,1782699600,1782699900,1782700200,1782700500,1782700800,1782701100,1782701400,1782701700,1782702000,1782702300,1782702600,1782702900,1782703200,1782703500,1782703800,1782704100,1782704400,1782704700,1782705000,1782705300,1782705600,1782705900,1782706200,1782706500,1782706800,1782707100,1782712800,1782713100,1782713400,1782713700,1782714000,1782714300,1782714600,1782714900,1782715200,1782715500,1782715800,1782716100,1782716400,1782716700,1782717000,1782717300,1782717600,1782717900,1782719100,1782784800,1782785100,1782785400,1782785700,1782786000,1782786300,1782786600,1782786900,1782787200,1782787500,1782787800,1782788100,1782788400,1782788700,1782789000,1782789300,1782789600,1782789900,1782790200,1782790500,1782790800,1782791100,1782791400,1782791700,1782792000,1782792300,1782792600,1782792900,1782793200,1782793500,1782799200,1782799500,1782799800,1782800100,1782800400,1782800700,1782801000,1782801300,1782801600,1782801900,1782802200,1782802500,1782802800,1782803100,1782803400,1782803700,1782804000,1782804300,1782805500,1782871200,1782871500,1782871800,1782872100,1782872400,1782872700,1782873000,1782873300,1782873600,1782873900,1782874200,1782874500,1782874800,1782875100,1782875400,1782875700,1782876000,1782876300,1782876600,1782876900,1782877200,1782877500,1782877800,1782878100,1782878400,1782878700,1782879000,1782879300,1782879600,1782879900,1782885600,1782885900,1782886200,1782886500,1782886800,1782887100,1782887400,1782887700,1782888000,1782888300,1782888600,1782888900,1782889200,1782889500,1782889800,1782890100,1782890400,1782890700,1782891900,1782957600,1782957900,1782958200,1782958500,1782958800,1782959100,1782959400,1782959700,1782960000,1782960300,1782960600,1782960900,1782961200,1782961500,1782961800,1782962100,1782962400,1782962700,1782963000,1782963300,1782963600,1782963900,1782964200,1782964500,1782964800,1782965100,1782965400,1782965700,1782966000,1782966300,1782972000,1782972300,1782972600,1782972900,1782973200,1782973500,1782973800,1782974100,1782974400,1782974700,1782975000,1782975300,1782975600,1782975900,1782976200,1782976500,1782976800,1782977100,1782978300,1783044000,1783044300,1783044600,1783044900,1783045200,1783045500,1783045800,1783046100,1783046400,1783046700,1783047000,1783047300,1783047600,1783047900,1783048200,1783048500,1783048800,1783049100,1783049400,1783049700,1783050000,1783050300,1783050600,1783050900,1783051200,1783051500,1783051800,1783052100,1783052400,1783052700,1783058400,1783058700,1783059000,1783059300,1783059600,1783059900,1783060200,1783060500,1783060800,1783061100,1783061400,1783061700,1783062000,1783062300,1783062600,1783062900,1783063200,1783063500,1783064700,1783303200,1783303500,1783303800,1783304100,1783304400,1783304700,1783305000,1783305300,1783305600,1783305900,1783306200,1783306500,1783306800,1783307100,1783307400,1783307700,1783308000,1783308300,1783308600,1783308900,1783309200,1783309500,1783309800,1783310100,1783310400,1783310700,1783311000,1783311300,1783311600,1783311900,1783317600,1783317900,1783318200,1783318500,1783318800,1783319100,1783319400,1783319700,1783320000,1783320300,1783320600,1783320900,1783321200,1783321500,1783321800,1783322100,1783322400,1783322700,1783323900,1783389600,1783389900,1783390200,1783390500,1783390800,1783391100,1783391400,1783391700,1783392000,1783392300,1783392600,1783392900,1783393200,1783393500,1783393800,1783394100,1783394400,1783394700,1783395000,1783395300,1783395600,1783395900,1783396200,1783396500,1783396800,1783397100,1783397400,1783397700,1783398000,1783398300,1783404000,1783404300,1783404600,1783404900,1783405200,1783405500,1783405800,1783406100,1783406400,1783406700,1783407000,1783407300,1783407600,1783407900,1783408200,1783408500,1783408800,1783409100,1783410300,1783476000,1783476300,1783476600,1783476900,1783477200,1783477500,1783477800,1783478100,1783478400,1783478700,1783479000,1783479300,1783479600,1783479900,1783480200,1783480500,1783480800,1783481100,1783481400,1783481700,1783482000,1783482300,1783482600,1783482900,1783483200,1783483500,1783483800,1783484100,1783484400,1783484700,1783490400,1783490700,1783491000,1783491300,1783491600,1783491900,1783492200,1783492500,1783492800,1783493100,1783493400,1783493700,1783494000,1783494300,1783494600,1783494900,1783495200,1783495500,1783496700,1783562400,1783562700,1783563000,1783563300,1783563600,1783563900,1783564200,1783564500,1783564800,1783565100,1783565400,1783565700,1783566000,1783566300,1783566600,1783566900,1783567200,1783567500,1783567800,1783568100,1783568400,1783568700,1783569000,1783569300,1783569600,1783569900,1783570200,1783570500,1783570800,1783571100,1783576800,1783577100,1783577400,1783577700,1783578000,1783578300,1783578600,1783578900,1783579200,1783579500,1783579800,1783580100,1783580400,1783580700,1783581000,1783581300,1783581600,1783581900,1783583100,1783648800,1783649100,1783649400,1783649700,1783650000,1783650300,1783650600,1783650900,1783651200,1783651500,1783651800,1783652100,1783652400,1783652700,1783653000,1783653300,1783653600,1783653900,1783654200,1783654500,1783654800,1783655100,1783655400,1783655700,1783656000,1783656300,1783656600,1783656900,1783657200,1783657500,1783663200,1783663500,1783663800,1783664100,1783664400,1783664700,1783665000,1783665300,1783665600,1783665900,1783666200,1783666500,1783666800,1783667100,1783667400,1783667700,1783668000,1783668300,1783669500,1783908000,1783908300,1783908600,1783908900,1783909200,1783909500,1783909800,1783910100,1783910400,1783910700,1783911000,1783911300,1783911600,1783911900,1783912200,1783912500,1783912800,1783913100,1783913400,1783913700,1783914000,1783914300,1783914600,1783914900,1783915200,1783915500,1783915800,1783916100,1783916400,1783916700,1783922400,1783922700,1783923000,1783923300,1783923600,1783923900,1783924200,1783924500,1783924800,1783925100,1783925400,1783925700,1783926000,1783926300,1783926600,1783926900,1783927200,1783927500,1783928700,1783994400,1783994700,1783995000,1783995300,1783995600,1783995900,1783996200,1783996500,1783996800,1783997100,1783997400,1783997700,1783998000,1783998300,1783998600,1783998900,1783999200,1783999500,1783999800,1784000100,1784000400,1784000700,1784001000,1784001300,1784001600,1784001900,1784002200,1784002500,1784002800,1784003100,1784008800,1784009100,1784009400,1784009700,1784010000,1784010300,1784010600,1784010900,1784011200,1784011500,1784011800,1784012100,1784012400,1784012700,1784013000,1784013300,1784013600,1784013900,1784015100,1784080800,1784081100,1784081400,1784081700,1784082000,1784082300,1784082600,1784082900,1784083200,1784083500,1784083800,1784084100,1784084400,1784084700,1784085000,1784085300,1784085600,1784085900,1784086200,1784086500,1784086800,1784087100,1784087400,1784087700,1784088000,1784088300,1784088600,1784088900,1784089200,1784089500,1784095200,1784095500,1784095800,1784096100,1784096400,1784096700,1784097000,1784097300,1784097600,1784097900,1784098200,1784098500,1784098800,1784099100,1784099400,1784099700,1784100000,1784100300,1784101500,1784167200,1784167500,1784167800,1784168100,1784168400,1784168700,1784169000,1784169300,1784169600,1784169900,1784170200,1784170500,1784170800,1784171100,1784171400,1784171700,1784172000,1784172300,1784172600,1784172900,1784173200,1784173500,1784173800,1784174100,1784174400,1784174700,1784175000,1784175300,1784175600,1784175900,1784181600,1784181900,1784182200,1784182500,1784182800,1784183100,1784183400,1784183700,1784184000,1784184300,1784184600,1784184900,1784185200,1784185500,1784185800,1784186100,1784186400,1784186700,1784187900,1784253600,1784253900,1784254200,1784254500,1784254800,1784255100,1784255400,1784255700,1784256000,1784256300,1784256600,1784256900,1784257200,1784257500,1784257800,1784258100,1784258400,1784258700,1784259000,1784259300,1784259600,1784259900,1784260200,1784260500,1784260800,1784261100,1784261400,1784261700,1784262000,1784262300,1784268000,1784268300,1784268600,1784268900,1784269200,1784269500,1784269800,1784270100,1784270400,1784270700,1784271000,1784271300,1784271600,1784271900,1784272200,1784272500,1784272800,1784273100,1784274300,1784512800,1784513100,1784513400,1784513700,1784514000,1784514300,1784514600,1784514900,1784515200,1784515500,1784515800,1784516100,1784516400,1784516700,1784517000,1784517300,1784517600,1784517900,1784518200,1784518500,1784518800,1784519100,1784519400,1784519700,1784520000,1784520300,1784520600,1784520900,1784521200,1784521500,1784527200,1784527500,1784527800,1784528100,1784528400,1784528700,1784529000,1784529300,1784529600,1784529900,1784530200,1784530500,1784530800,1784531100,1784531400,1784531700,1784532000,1784532300,1784533500,1784599200,1784599500,1784599800,1784600100,1784600400,1784600700,1784601000,1784601300,1784601600,1784601900,1784602200,1784602500,1784602800,1784603100,1784603400,1784603700,1784604000,1784604300,1784604600,1784604900,1784605200,1784605500,1784605800,1784606100,1784606400,1784606700,1784607000,1784607300,1784607600,1784607900,1784613600,1784613900,1784614200,1784614500,1784614800,1784615100,1784615400,1784615700,1784616000,1784616300,1784616600,1784616900,1784617200,1784617500,1784617800,1784618100,1784618400,1784618700,1784619900,1784685600,1784685900,1784686200,1784686500,1784686800,1784687100,1784687400,1784687700,1784688000,1784688300,1784688600,1784688900,1784689200,1784689500,1784689800,1784690100,1784690400,1784690700,1784691000,1784691300,1784691600,1784691900,1784692200,1784692500,1784692800,1784693100,1784693400,1784693700,1784694000,1784694300,1784700000,1784700300,1784700600,1784700900,1784701200,1784701500,1784701800,1784702100,1784702400,1784702700,1784703000,1784703300,1784703600,1784703900,1784704200,1784704500,1784704800,1784705100,1784706300,1784772000,1784772300,1784772600,1784772900,1784773200,1784773500,1784773800,1784774100,1784774400,1784774700,1784775000,1784775300,1784775600,1784775900,1784776200,1784776500,1784776800,1784777100,1784777400,1784777700,1784778000,1784778300,1784778600,1784778900,1784779200,1784779500,1784779800,1784780100,1784780400,1784780700,1784786400,1784786700,1784787000,1784787300,1784787600,1784787900,1784788200,1784788500,1784788800,1784789100,1784789400,1784789700,1784790000,1784790300,1784790600,1784790900,1784791200,1784791500,1784792700,1784858400,1784858700,1784859000,1784859300,1784859600,1784859900,1784860200,1784860500,1784860800,1784861100,1784861400,1784861700,1784862000,1784862300,1784862600,1784862900,1784863200,1784863500,1784863800,1784864100,1784864400,1784864700,1784865000,1784865300,1784865600,1784865900,1784866200,1784866500,1784866800,1784867100,1784872800,1784873100,1784873400,1784873700,1784874000,1784874300,1784874600,1784874900,1784875200,1784875500,1784875800,1784876100,1784876400,1784876700,1784877000,1784877300,1784877600,1784877900,1784879100,1785117600,1785117900,1785118200,1785118500,1785118800,1785119100,1785119400,1785119700,1785120000,1785120300,1785120600,1785120900,1785121200,1785121500,1785121800,1785122100,1785122400,1785122700,1785123000,1785123300,1785123600,1785123900,1785124200,1785124500,1785124800,1785125100,1785125400,1785125700,1785126000,1785126300,1785132000,1785132300,1785132600,1785132900,1785133200,1785133500,1785133800,1785134100,1785134400,1785134700,1785135000,1785135300,1785135600,1785135900,1785136200,1785136500,1785136800,1785137100,1785138300,1785204000,1785204300,1785204600,1785204900,1785205200,1785205500,1785205800,1785206100,1785206400,1785206700,1785207000,1785207300,1785207600,1785207900,1785208200,1785208500,1785208800,1785209100,1785209400,1785209700,1785210000,1785210300,1785210600,1785210900,1785211200,1785211500,1785211800,1785212100,1785212400,1785212700,1785218400,1785218700,1785219000,1785219300,1785219600,1785219900,1785220200,1785220500,1785220800,1785221100,1785221400,1785221700,1785222000,1785222300,1785222600,1785222900,1785223200,1785223500,1785224700,1785290400,1785290700,1785291000,1785291300,1785291600,1785291900,1785292200,1785292500,1785292800,1785293100,1785293400,1785293700,1785294000,1785294300,1785294600,1785294900,1785295200,1785295500,1785295800,1785296100,1785296400,1785296700,1785297000,1785297300,1785297600,1785297900,1785298200,1785298500,1785298800,1785299100,1785304800,1785305100,1785305400,1785305700,1785306000,1785306300,1785306600,1785306900,1785307200,1785307500,1785307800,1785308100,1785308400,1785308700,1785309000,1785309300,1785309600,1785309900,1785311100,1785376800,1785377100,1785377400,1785377700,1785378000,1785378300,1785378600,1785378900,1785379200,1785379500,1785379800,1785380100,1785380400,1785380700,1785381000,1785381300,1785381600,1785381900,1785382200,1785382500,1785382800,1785383100,1785383400,1785383700,1785384000,1785384300,1785384600,1785384900,1785385200,1785385500,1785391200,1785391500,1785391800,1785392100,1785392400,1785392700,1785393000,1785393300,1785393600,1785393900,1785394200,1785394500,1785394800,1785395100,1785395400,1785395700,1785396000,1785396300,1785397500,1785463200,1785463500,1785463800,1785464100,1785464400,1785464700,1785465000,1785465300,1785465600,1785465900,1785466200,1785466500,1785466800,1785467100,1785467400,1785467700,1785468000,1785468300,1785468600,1785468900,1785469200,1785469500,1785469800,1785470100,1785470400,1785470700,1785471000,1785471300,1785471600,1785471900,1785477600,1785477900,1785478200,1785478500,1785478800,1785479100,1785479400,1785479700,1785480000,1785480300,1785480600,1785480900,1785481200,1785481500,1785481800,1785482100,1785482400,1785482700,1785483900,1785722400,1785722700,1785723000,1785723300,1785723600,1785723900,1785724200,1785724500,1785724800,1785725100,1785725400,1785725700,1785726000,1785726300,1785726600,1785726900,1785727200,1785727500,1785727800,1785728100,1785728400,1785728700,1785729000,1785729300,1785729600,1785729900,1785730200,1785730500,1785730800,1785731100,1785736800,1785737100,1785737400,1785737700,1785738000,1785738300,1785738600,1785738900,1785739200,1785739500,1785739800,1785740100,1785740400,1785740700,1785741000,1785741300,1785741600,1785741900,1785743100,1785808800,1785809100,1785809400,1785809700,1785810000,1785810300,1785810600,1785810900,1785811200,1785811500,1785811800,1785812100,1785812400,1785812700,1785813000,1785813300,1785813600,1785813900,1785814200,1785814500,1785814800,1785815100,1785815400,1785815700,1785816000,1785816300,1785816600,1785816900,1785817200,1785817500,1785823200,1785823500,1785823800,1785824100,1785824400,1785824700,1785825000,1785825300,1785825600,1785825900,1785826200,1785826500,1785826800,1785827100,1785827400,1785827700,1785828000,1785828300,1785829500,1785895200,1785895500,1785895800,1785896100,1785896400,1785896700,1785897000,1785897300,1785897600,1785897900,1785898200,1785898500,1785898800,1785899100,1785899400,1785899700,1785900000,1785900300,1785900600,1785900900,1785901200,1785901500,1785901800,1785902100,1785902400,1785902700,1785903000,1785903300,1785903600,1785903900,1785909600,1785909900,1785910200,1785910500,1785910800,1785911100,1785911400,1785911700,1785912000,1785912300,1785912600,1785912900,1785913200,1785913500,1785913800,1785914100,1785914400,1785914700,1785915900,1785981600,1785981900,1785982200,1785982500,1785982800,1785983100,1785983400,1785983700,1785984000,1785984300,1785984600,1785984900,1785985200,1785985500,1785985800,1785986100,1785986400,1785986700,1785987000,1785987300,1785987600,1785987900,1785988200,1785988500,1785988800,1785989100,1785989400,1785989700,1785990000,1785990300,1785996000,1785996300,1785996600,1785996900,1785997200,1785997500,1785997800,1785998100,1785998400,1785998700,1785999000,1785999300,1785999600,1785999900,1786000200,1786000500,1786000800,1786001100,1786002300,1786068000,1786068300,1786068600,1786068900,1786069200,1786069500,1786069800,1786070100,1786070400,1786070700,1786071000,1786071300,1786071600,1786071900,1786072200,1786072500,1786072800,1786073100,1786073400,1786073700,1786074000,1786074300,1786074600,1786074900,1786075200,1786075500,1786075800,1786076100,1786076400,1786076700,1786082400,1786082700,1786083000,1786083300,1786083600,1786083900,1786084200,1786084500,1786084800,1786085100,1786085400,1786085700,1786086000,1786086300,1786086600,1786086900,1786087200,1786087500,1786088700,1786327200,1786327500,1786327800,1786328100,1786328400,1786328700,1786329000,1786329300,1786329600,1786329900,1786330200,1786330500,1786330800,1786331100,1786331400,1786331700,1786332000,1786332300,1786332600,1786332900,1786333200,1786333500,1786333800,1786334100,1786334400,1786334700,1786335000,1786335300,1786335600,1786335900,1786341600,1786341900,1786342200,1786342500,1786342800,1786343100,1786343400,1786343700,1786344000,1786344300,1786344600,1786344900,1786345200,1786345500,1786345800,1786346100,1786346400,1786346700,1786347900,1786413600,1786413900,1786414200,1786414500,1786414800,1786415100,1786415400,1786415700,1786416000,1786416300,1786416600,1786416900,1786417200,1786417500,1786417800,1786418100,1786418400,1786418700,1786419000,1786419300,1786419600,1786419900,1786420200,1786420500,1786420800,1786421100,1786421400,1786421700,1786422000,1786422300,1786428000,1786428300,1786428600,1786428900,1786429200,1786429500,1786429800,1786430100,1786430400,1786430700,1786431000,1786431300,1786431600,1786431900,1786432200,1786432500,1786432800,1786433100,1786434300,1786500000,1786500300,1786500600,1786500900,1786501200,1786501500,1786501800,1786502100,1786502400,1786502700,1786503000,1786503300,1786503600,1786503900,1786504200,1786504500,1786504800,1786505100,1786505400,1786505700,1786506000,1786506300,1786506600,1786506900,1786507200,1786507500,1786507800,1786508100,1786508400,1786508700,1786514400,1786514700,1786515000,1786515300,1786515600,1786515900,1786516200,1786516500,1786516800,1786517100,1786517400,1786517700,1786518000,1786518300,1786518600,1786518900,1786519200,1786519500,1786520700,1786586400,1786586700,1786587000,1786587300,1786587600,1786587900,1786588200,1786588500,1786588800,1786589100,1786589400,1786589700,1786590000,1786590300,1786590600,1786590900,1786591200,1786591500,1786591800,1786592100,1786592400,1786592700,1786593000,1786593300,1786593600,1786593900,1786594200,1786594500,1786594800,1786595100,1786600800,1786601100,1786601400,1786601700,1786602000,1786602300,1786602600,1786602900,1786603200,1786603500,1786603800,1786604100,1786604400,1786604700,1786605000,1786605300,1786605600,1786605900,1786607100,1786672800,1786673100,1786673400,1786673700,1786674000,1786674300,1786674600,1786674900,1786675200,1786675500,1786675800,1786676100,1786676400,1786676700,1786677000,1786677300,1786677600,1786677900,1786678200,1786678500,1786678800,1786679100,1786679400,1786679700,1786680000,1786680300,1786680600,1786680900,1786681200,1786681500,1786687200,1786687500,1786687800,1786688100,1786688400,1786688700,1786689000,1786689300,1786689600,1786689900,1786690200,1786690500,1786690800,1786691100,1786691400,1786691700,1786692000,1786692300,1786693500,1786932000,1786932300,1786932600,1786932900,1786933200,1786933500,1786933800,1786934100,1786934400,1786934700,1786935000,1786935300,1786935600,1786935900,1786936200,1786936500,1786936800,1786937100,1786937400,1786937700,1786938000,1786938300,1786938600,1786938900,1786939200,1786939500,1786939800,1786940100,1786940400,1786940700,1786946400,1786946700,1786947000,1786947300,1786947600,1786947900,1786948200,1786948500,1786948800,1786949100,1786949400,1786949700,1786950000,1786950300,1786950600,1786950900,1786951200,1786951500,1786952700,1787018400,1787018700,1787019000,1787019300,1787019600,1787019900,1787020200,1787020500,1787020800,1787021100,1787021400,1787021700,1787022000,1787022300,1787022600,1787022900,1787023200,1787023500,1787023800,1787024100,1787024400,1787024700,1787025000,1787025300,1787025600,1787025900,1787026200,1787026500,1787026800,1787027100,1787032800,1787033100,1787033400,1787033700,1787034000,1787034300,1787034600,1787034900,1787035200,1787035500,1787035800,1787036100,1787036400,1787036700,1787037000,1787037300,1787037600,1787037900,1787039100,1787104800,1787105100,1787105400,1787105700,1787106000,1787106300,1787106600,1787106900,1787107200,1787107500,1787107800,1787108100,1787108400,1787108700,1787109000,1787109300,1787109600,1787109900,1787110200,1787110500,1787110800,1787111100,1787111400,1787111700,1787112000,1787112300,1787112600,1787112900,1787113200,1787113500,1787119200,1787119500,1787119800,1787120100,1787120400,1787120700,1787121000,1787121300,1787121600,1787121900,1787122200,1787122500,1787122800,1787123100,1787123400,1787123700,1787124000,1787124300,1787125500,1787191200,1787191500,1787191800,1787192100,1787192400,1787192700,1787193000,1787193300,1787193600,1787193900,1787194200,1787194500,1787194800,1787195100,1787195400,1787195700,1787196000,1787196300,1787196600,1787196900,1787197200,1787197500,1787197800,1787198100,1787198400,1787198700,1787199000,1787199300,1787199600,1787199900,1787205600,1787205900,1787206200,1787206500,1787206800,1787207100,1787207400,1787207700,1787208000,1787208300,1787208600,1787208900,1787209200,1787209500,1787209800,1787210100,1787210400,1787210700,1787211900,1787277600,1787277900,1787278200,1787278500,1787278800,1787279100,1787279400,1787279700,1787280000,1787280300,1787280600,1787280900,1787281200,1787281500,1787281800,1787282100,1787282400,1787282700,1787283000,1787283300,1787283600,1787283900,1787284200,1787284500,1787284800,1787285100,1787285400,1787285700,1787286000,1787286300,1787292000,1787292300,1787292600,1787292900,1787293200,1787293500,1787293800,1787294100,1787294400,1787294700,1787295000,1787295300,1787295600,1787295900,1787296200,1787296500,1787296800,1787297100,1787298300,1787536800,1787537100,1787537400,1787537700,1787538000,1787538300,1787538600,1787538900,1787539200,1787539500,1787539800,1787540100,1787540400,1787540700,1787541000,1787541300,1787541600,1787541900,1787542200,1787542500,1787542800,1787543100,1787543400,1787543700,1787544000,1787544300,1787544600,1787544900,1787545200,1787545500,1787551200,1787551500,1787551800,1787552100,1787552400,1787552700,1787553000,1787553300,1787553600,1787553900,1787554200,1787554500,1787554800,1787555100,1787555400,1787555700,1787556000,1787556300,1787557500,1787623200,1787623500,1787623800,1787624100,1787624400,1787624700,1787625000,1787625300,1787625600,1787625900,1787626200,1787626500,1787626800,1787627100,1787627400,1787627700,1787628000,1787628300,1787628600,1787628900,1787629200,1787629500,1787629800,1787630100,1787630400,1787630700,1787631000,1787631300,1787631600,1787631900,1787637600,1787637900,1787638200,1787638500,1787638800,1787639100,1787639400,1787639700,1787640000,1787640300,1787640600,1787640900,1787641200,1787641500,1787641800,1787642100,1787642400,1787642700,1787643900,1787709600,1787709900,1787710200,1787710500,1787710800,1787711100,1787711400,1787711700,1787712000,1787712300,1787712600,1787712900,1787713200,1787713500,1787713800,1787714100,1787714400,1787714700,1787715000,1787715300,1787715600,1787715900,1787716200,1787716500,1787716800,1787717100,1787717400,1787717700,1787718000,1787718300,1787724000,1787724300,1787724600,1787724900,1787725200,1787725500,1787725800,1787726100,1787726400,1787726700,1787727000,1787727300,1787727600,1787727900,1787728200,1787728500,1787728800,1787729100,1787730300,1787796000,1787796300,1787796600,1787796900,1787797200,1787797500,1787797800,1787798100,1787798400,1787798700,1787799000,1787799300,1787799600,1787799900,1787800200,1787800500,1787800800,1787801100,1787801400,1787801700,1787802000,1787802300,1787802600,1787802900,1787803200,1787803500,1787803800,1787804100,1787804400,1787804700,1787810400,1787810700,1787811000,1787811300,1787811600,1787811900,1787812200,1787812500,1787812800,1787813100,1787813400,1787813700,1787814000,1787814300,1787814600,1787814900,1787815200,1787815500,1787816700,1787882400,1787882700,1787883000,1787883300,1787883600,1787883900,1787884200,1787884500,1787884800,1787885100,1787885400,1787885700,1787886000,1787886300,1787886600,1787886900,1787887200,1787887500,1787887800,1787888100,1787888400,1787888700,1787889000,1787889300,1787889600,1787889900,1787890200,1787890500,1787890800,1787891100,1787896800,1787897100,1787897400,1787897700,1787898000,1787898300,1787898600,1787898900,1787899200,1787899500,1787899800,1787900100,1787900400,1787900700,1787901000,1787901300,1787901600,1787901900,1787903100,1788400800,1788401100,1788401400,1788401700,1788402000,1788402300,1788402600,1788402900,1788403200,1788403500,1788403800,1788404100,1788404400,1788404700,1788405000,1788405300,1788405600,1788405900,1788406200,1788406500,1788406800,1788407100,1788407400,1788407700,1788408000,1788408300,1788408600,1788408900,1788409200,1788409500,1788415200,1788415500,1788415800,1788416100,1788416400,1788416700,1788417000,1788417300,1788417600,1788417900,1788418200,1788418500,1788418800,1788419100,1788419400,1788419700,1788420000,1788420300,1788421500,1788487200,1788487500,1788487800,1788488100,1788488400,1788488700,1788489000,1788489300,1788489600,1788489900,1788490200,1788490500,1788490800,1788491100,1788491400,1788491700,1788492000,1788492300,1788492600,1788492900,1788493200,1788493500,1788493800,1788494100,1788494400,1788494700,1788495000,1788495300,1788495600,1788495900,1788501600,1788501900,1788502200,1788502500,1788502800,1788503100,1788503400,1788503700,1788504000,1788504300,1788504600,1788504900,1788505200,1788505500,1788505800,1788506100,1788506400,1788506700,1788507900,1788746400,1788746700,1788747000,1788747300,1788747600,1788747900,1788748200,1788748500,1788748800,1788749100,1788749400,1788749700,1788750000,1788750300,1788750600,1788750900,1788751200,1788751500,1788751800,1788752100,1788752400,1788752700,1788753000,1788753300,1788753600,1788753900,1788754200,1788754500,1788754800,1788755100,1788760800,1788761100,1788761400,1788761700,1788762000,1788762300,1788762600,1788762900,1788763200,1788763500,1788763800,1788764100,1788764400,1788764700,1788765000,1788765300,1788765600,1788765900,1788767100,1788832800,1788833100,1788833400,1788833700,1788834000,1788834300,1788834600,1788834900,1788835200,1788835500,1788835800,1788836100,1788836400,1788836700,1788837000,1788837300,1788837600,1788837900,1788838200,1788838500,1788838800,1788839100,1788839400,1788839700,1788840000,1788840300,1788840600,1788840900,1788841200,1788841500,1788847200,1788847500,1788847800,1788848100,1788848400,1788848700,1788849000,1788849300,1788849600,1788849900,1788850200,1788850500,1788850800,1788851100,1788851400,1788851700,1788852000,1788852300,1788853500,1788919200,1788919500,1788919800,1788920100,1788920400,1788920700,1788921000,1788921300,1788921600,1788921900,1788922200,1788922500,1788922800,1788923100,1788923400,1788923700,1788924000,1788924300,1788924600,1788924900,1788925200,1788925500,1788925800,1788926100,1788926400,1788926700,1788927000,1788927300,1788927600,1788927900,1788933600,1788933900,1788934200,1788934500,1788934800,1788935100,1788935400,1788935700,1788936000,1788936300,1788936600,1788936900,1788937200,1788937500,1788937800,1788938100,1788938400,1788938700,1788939900,1789005600,1789005900,1789006200,1789006500,1789006800,1789007100,1789007400,1789007700,1789008000,1789008300,1789008600,1789008900,1789009200,1789009500,1789009800,1789010100,1789010400,1789010700,1789011000,1789011300,1789011600,1789011900,1789012200,1789012500,1789012800,1789013100,1789013400,1789013700,1789014000,1789014300,1789020000,1789020300,1789020600,1789020900,1789021200,1789021500,1789021800,1789022100,1789022400,1789022700,1789023000,1789023300,1789023600,1789023900,1789024200,1789024500,1789024800,1789025100,1789026300,1789092000,1789092300,1789092600,1789092900,1789093200,1789093500,1789093800,1789094100,1789094400,1789094700,1789095000,1789095300,1789095600,1789095900,1789096200,1789096500,1789096800,1789097100,1789097400,1789097700,1789098000,1789098300,1789098600,1789098900,1789099200,1789099500,1789099800,1789100100,1789100400,1789100700,1789106400,1789106700,1789107000,1789107300,1789107600,1789107900,1789108200,1789108500,1789108800,1789109100,1789109400,1789109700,1789110000,1789110300,1789110600,1789110900,1789111200,1789111500,1789112700,1789351200,1789351500,1789351800,1789352100,1789352400,1789352700,1789353000,1789353300,1789353600,1789353900,1789354200,1789354500,1789354800,1789355100,1789355400,1789355700,1789356000,1789356300,1789356600,1789356900,1789357200,1789357500,1789357800,1789358100,1789358400,1789358700,1789359000,1789359300,1789359600,1789359900,1789365600,1789365900,1789366200,1789366500,1789366800,1789367100,1789367400,1789367700,1789368000,1789368300,1789368600,1789368900,1789369200,1789369500,1789369800,1789370100,1789370400,1789370700,1789371900,1789437600,1789437900,1789438200,1789438500,1789438800,1789439100,1789439400,1789439700,1789440000,1789440300,1789440600,1789440900,1789441200,1789441500,1789441800,1789442100,1789442400,1789442700,1789443000,1789443300,1789443600,1789443900,1789444200,1789444500,1789444800,1789445100,1789445400,1789445700,1789446000,1789446300,1789452000,1789452300,1789452600,1789452900,1789453200,1789453500,1789453800,1789454100,1789454400,1789454700,1789455000,1789455300,1789455600,1789455900,1789456200,1789456500,1789456800,1789457100,1789458300],
      "c": [1847.5,1845,1847.7,1844.2,1845.6,1841.2,1841.4,1843,1844,1844.4,1842.9,1844.4,1853.5,1857.3,1853.9,1854,1855,1852.9,1856.3,1855.3,1853.2,1854.1,1849.5,1848,1845.6,1847,1847,1851.1,1851.4,1851.7,1852.4,1849.5,1851.2,1853.4,1850.9,1845.8,1843,1844.5,1843.1,1845.5,1843,1843,1844.3,1838.7,1841.6,1851.4,1852,1850.3,1851.3,1870.5,1870.8,1874.4,1872.6,1896.6,1892.7,1892.5,1903.5,1897.1,1897,1894.5,1895.4,1893.8,1894.4,1895.9,1894.3,1894.7,1895.1,1897,1895,1893.5,1894.4,1895.4,1895.5,1894.3,1894.1,1894.7,1896.5,1896.1,1899.4,1883.9,1882.7,1881,1882.7,1882.4,1884.4,1883.3,1882.5,1880,1878.5,1877.7,1876.1,1882.4,1882.5,1875.3,1876.5,1881,1880.3,1877,1892.5,1889,1889,1890.5,1893,1902,1904,1906.5,1904.4,1903.6,1904.6,1902,1903.4,1905.6,1904,1901.9,1896.7,1896.4,1896.8,1894.4,1895.8,1893.9,1894.5,1896.1,1895.2,1893.6,1891,1890.8,1882.8,1879,1880.8,1883.5,1884.6,1885.1,1888.1,1889.8,1896.5,1900.5,1899.6,1892,1893.8,1889.5,1893.1,1886.5,1888.2,1885.1,1888.5,1891.4,1881.9,1857.2,1854.4,1856,1853.4,1863.2,1860.4,1858.3,1853.7,1855.9,1856.3,1858.5,1857.4,1855.9,1854.5,1852.7,1855.1,1854.5,1855.5,1858.8,1860.5,1858.7,1858.3,1863,1862,1861.5,1857.6,1856.9,1858.7,1859.4,1857.5,1859.3,1858.4,1858.6,1858.2,1857.6,1858.1,1859.2,1855.3,1855.4,1855.8,1857.3,1858.7,1861.9,1864.1,1868,1863.1,1859.7,1858.8,1858.2,1830.4,1829,1827.1,1824,1821.3,1819.5,1820.8,1817.6,1818.6,1821.5,1820.8,1819.8,1823.7,1816.8,1812,1812,1812.2,1815,1813.2,1814.5,1814.1,1815.2,1812.3,1813,1812.5,1812.4,1814.5,1813,1814.3,1814,1818.7,1814.3,1812.5,1811,1811.7,1816.5,1817.9,1815.3,1813.7,1812.3,1813.3,1806.7,1809.6,1802.5,1805.2,1800.9,1798,1794.6,1802,1778.8,1778.2,1777.4,1780.5,1772.8,1776.3,1775.3,1769.2,1763.6,1765.5,1760.7,1755.3,1757,1761.1,1757.7,1756.7,1759.6,1761.1,1764.6,1764.4,1761.5,1761.2,1757,1754.6,1755.5,1760.1,1763.3,1773.5,1770.5,1771.8,1769.3,1766.9,1763.5,1760,1757.3,1761,1760.8,1757.1,1751.5,1750.4,1752.8,1749.2,1750.9,1753,1752.1,1743.3,1743.5,1743,1740,1774.7,1771.9,1769,1768.3,1766.1,1768,1765.6,1766.8,1768.4,1770.8,1764.8,1761.8,1763.9,1760.8,1766.6,1769,1772.1,1769,1767.8,1770.9,1774.4,1776.5,1775.8,1775.6,1775,1775.7,1773.9,1770.2,1770.6,1771.6,1770.9,1775,1774,1771,1766.8,1767.2,1767.8,1768,1763.7,1763.3,1766.8,1770.2,1773,1769.9,1767,1763,1765.9,1767.8,1773.9,1803.6,1803.1,1801.1,1803.5,1802.8,1808.2,1803.6,1803.1,1802.3,1801.8,1801.9,1802,1798.5,1797.9,1798,1798.1,1801.5,1799.9,1800.1,1800.5,1800.4,1798.9,1799,1799.1,1795.9,1795,1793.3,1794.2,1795.1,1795.8,1794.2,1795.4,1798.3,1795.8,1799,1800,1800.2,1800.6,1797.9,1797.6,1797.5,1798.7,1798.9,1797.5,1803.7,1805,1806.5,1809.5,1814,1805,1804.7,1803.5,1801,1801.1,1799,1797.7,1797.8,1798.6,1796.4,1795.1,1793,1789.9,1789.2,1793.3,1796,1794.2,1796.5,1797.8,1794.2,1794.6,1796.7,1794.9,1794.8,1794,1796.5,1792.1,1792,1791.3,1792.5,1785.5,1786,1786.1,1786.7,1785.2,1789.2,1787.5,1787.2,1787.1,1793,1792.8,1790.5,1793.9,1788.2,1792.3,1792,1789.4,1790.8,1793,1786.9,1789.1,1789.5,1787.1,1791,1791,1791,1790.4,1794.8,1794.5,1795.2,1807.5,1806.9,1805,1805,1805.9,1803.3,1803.4,1802.3,1803.9,1804.9,1804,1803.6,1802.8,1804.9,1806,1805.5,1804,1804.2,1806.8,1806.2,1805.7,1808.1,1807.8,1813.9,1811.5,1812.5,1816.6,1817.8,1818.8,1817,1818.6,1822.8,1826.5,1822.4,1825,1829,1825,1821.1,1771.1,1775.1,1775.9,1782.6,1779.8,1780.4,1781.6,1781.4,1779.6,1783.2,1782.7,1781,1780.3,1783.8,1788.5,1792,1793.1,1800.6,1798.8,1799,1800.6,1797.5,1797.1,1797.1,1794.5,1797,1791.4,1792.5,1794,1795.9,1796,1800.8,1799.3,1805.3,1806.5,1807,1809.3,1817.2,1818,1821.7,1824.8,1827.3,1820.2,1821.7,1823.3,1817.7,1813,1800.5,1808.4,1825,1829.4,1830.1,1825.5,1823.8,1825.9,1822.1,1823,1821.4,1824.6,1826.9,1828,1824.3,1835.5,1836.3,1834.8,1836.4,1840.8,1838.4,1836.2,1835,1835.1,1837,1831,1829.8,1828.9,1829.8,1829.9,1834,1832.9,1838.5,1835.2,1826.7,1825.2,1826.8,1822.5,1824.2,1826.5,1821.5,1823.8,1823.8,1828.8,1827.7,1829.4,1826,1823.8,1822.9,1822.1,1823.9,1866.9,1867.9,1874.2,1873.4,1870.5,1871.8,1869.3,1870.5,1871.9,1871.4,1869,1871.8,1872.5,1870,1870.7,1871,1870.2,1869.2,1872,1866.9,1867.2,1867,1868.5,1869.3,1867.3,1867.6,1869.3,1869.8,1868.6,1870.8,1871.4,1868.7,1871.9,1870.4,1873.7,1873.3,1871.4,1874,1878.8,1879,1878.1,1879.1,1878.4,1874.1,1874.1,1876,1876,1877.8,1875.8,1854.7,1854,1851.6,1850,1852.5,1846.4,1846,1845.5,1846.8,1849,1847.4,1850.5,1848.1,1846.2,1845.4,1845.6,1848.5,1848.2,1849,1846.8,1847,1848.8,1847.9,1845.2,1846.1,1846,1845.8,1846,1847.3,1845.8,1842.6,1842.2,1843.3,1843.9,1843,1845.4,1842,1842,1841.7,1842.1,1842,1843,1843.4,1844.8,1844.2,1849.9,1844.7,1847.7,1853.2,1867.7,1865.6,1863.8,1864,1865,1865,1864.6,1860.9,1862,1862.7,1861,1863.9,1862.8,1862.2,1862.8,1863.4,1861.5,1859.3,1857.3,1856.3,1857.2,1857.2,1857.8,1857.4,1855.8,1857.9,1858,1858.5,1857.9,1857.8,1856.4,1853.8,1849.6,1850,1848,1846,1840,1842.7,1842.1,1837.4,1837.7,1836.4,1835.1,1832.7,1831.2,1832.9,1834.7,1835.8,1835.4,1840,1835,1834.4,1834.4,1838.6,1841.6,1842.6,1851,1853.5,1848,1848.2,1848,1844.5,1841.4,1837.6,1835.1,1833.8,1835.3,1835.8,1834.9,1835.1,1836,1835.8,1837.5,1837.6,1839.8,1837.1,1835.1,1835.7,1836,1837.5,1838.9,1840.3,1845.4,1843.9,1848.6,1847.4,1846.4,1846.6,1843.1,1844.3,1843.5,1840.1,1838.5,1837,1838.5,1836,1838.9,1845.3,1840.8,1839.4,1837.9,1840.6,1838.1,1838.4,1837.3,1838.7,1840.6,1845.3,1843.7,1849.9,1853.5,1855.8,1853.5,1851.3,1853.7,1855.5,1852.5,1851.8,1851.2,1850.5,1850.5,1850.6,1851.1,1847.5,1846.6,1843.2,1842.5,1843.8,1845.1,1848.2,1845.4,1844.1,1843.9,1846.6,1845.1,1844.8,1846.5,1838.5,1839.2,1838.3,1839.5,1838.8,1840.6,1846.8,1847.5,1855,1848.2,1918,1913,1908.4,1906.7,1902.6,1900.9,1894.4,1896,1895.4,1897,1895.4,1899.1,1900.9,1903.5,1904.9,1904.5,1910.2,1909.9,1912.9,1914.3,1913,1915.2,1912.8,1911.6,1912.1,1912.6,1914.5,1915.4,1913.8,1914.8,1918.7,1923.9,1923.7,1923.7,1926.9,1933,1932.5,1932,1930.6,1934,1939.7,1939.6,1938.5,1938.5,1937.1,1939.5,1938.2,1940.2,1942,1929.7,1927.4,1926,1927.9,1927.4,1927.4,1926.1,1927.3,1927.2,1929.7,1932.5,1933.8,1932.9,1929.5,1928.6,1928.9,1930.6,1931.4,1930.8,1932,1932,1929.6,1930.4,1929.5,1931,1930.6,1929,1930.1,1928.7,1925,1931.3,1932.9,1934.6,1933.9,1932.6,1934.7,1937.6,1938.1,1936,1935.1,1937.2,1938.3,1938,1941.1,1936.8,1933.8,1931,1925.7,1921.7,1944.7,1945.6,1948,1947.5,1946.1,1949,1948.4,1953.3,1954.2,1951.3,1948.5,1948.8,1951.3,1949.7,1949.4,1949.9,1950.7,1950,1947.6,1949.5,1948.5,1949.4,1948.5,1951.7,1950.6,1948.8,1948.4,1947.4,1948,1948.5,1950,1951,1944.6,1945.6,1946.7,1948.8,1947.5,1946.4,1946.9,1946.3,1946,1945.4,1942.8,1939.6,1939.1,1940.1,1935.4,1937,1931,1916.1,1915.8,1912.5,1915.6,1918.6,1915.2,1915.3,1916.4,1918.9,1920.7,1919.7,1922.6,1921.9,1922,1918,1919.4,1919.3,1920.7,1919.2,1917.4,1916,1915.1,1915.9,1915.9,1915.7,1916,1916.6,1914.3,1916.1,1918.5,1920.8,1926.6,1928.9,1927.5,1931.7,1925.6,1925.4,1926.9,1927.2,1928.4,1929,1931.5,1931.8,1933,1931.1,1933.8,1931.6,1932,1932.2,1957.7,1958.9,1959.5,1958,1958,1960.4,1958.7,1958.9,1957.7,1954.5,1954.5,1955.2,1950.7,1948.2,1949.8,1949.1,1948.9,1945.8,1945,1947.3,1948,1947.9,1950.4,1949.7,1947,1943.8,1942.3,1940.7,1941.6,1941.6,1945.5,1949,1948.5,1943.3,1941.7,1943.8,1942.9,1945.2,1945.3,1943,1945,1946.8,1944,1946.1,1945.3,1943.2,1944,1944.9,1946.3,1964.8,1962.6,1962.5,1959.8,1957.2,1958.3,1960.4,1955.5,1957.7,1958.5,1958,1957.9,1959,1958.2,1957.7,1958.4,1958.4,1959.2,1961.6,1962.4,1960,1959.5,1957.7,1957.8,1957.7,1959,1957.2,1957.5,1958.8,1960.9,1958.4,1958.7,1958.7,1959.4,1959,1963.5,1961.1,1958.5,1958.6,1958.3,1958,1957.7,1961.2,1959.3,1961.9,1959.5,1962,1961,1961,1969.8,1968.6,1970.4,1969,1970.1,1970.8,1969.6,1969.4,1969.4,1969,1966.9,1966.8,1967.7,1967.2,1967.3,1968.5,1967.8,1969.4,1970.3,1970.9,1975.8,1973.6,1973.9,1975.5,1974.5,1975.1,1974.5,1974.9,1974.8,1975,1976.9,1976.3,1976.5,1980,1978.7,1982.2,1983.3,1983.3,1982,1980.5,1978,1977.4,1975.2,1973.4,1976,1980.7,1980.6,1980.3,1980.5,1969.1,1974.8,1978.3,1981.8,1982.5,1989.9,1987,1985.3,1982.4,1983.9,1977.7,1980.6,1985.2,1988.1,1989,1991.2,1994.2,1989.5,1988.9,1988.3,1987.6,1986.6,1988.7,1989.5,1989.7,1989.1,1991.3,1989.4,1990.9,1991.6,1989.7,1990.4,1991.5,1991.5,1993.4,1995.2,1993.3,1993.9,1992.2,1992.2,1992.4,1989.5,1988.8,1986.8,1984.3,1984.9,1986.9,1986,1987.9,1994,1993.3,1994,1989.1,1990.8,1992.7,1990.5,1989.6,1988.8,1987.5,1988.8,1989.5,1989.4,1990.2,1992.1,1992.1,1994.2,1999.8,1994.7,1993.3,1994.3,1994.4,1996.1,1993.8,1998.3,1993.1,1990.1,1989.4,1989.1,1988.4,1989.9,1992.8,1993.2,1988.9,1989.9,1988.1,1990.7,1991.2,1990.7,1993,1991.8,1992.3,1992.2,1992,1994.7,1994.3,1996.7,1995,1997.9,2008.9,2012.8,2015.4,2015,2014.2,2013.9,2013.3,2014.5,2013.8,2015.3,2017.1,2018.3,2016.6,2016.3,2019.8,2022.7,2024,2022.3,2022.8,2022.9,2019.5,2019.4,2019.9,2021.7,2015.9,2016,2017.2,2018,2018.9,2021.3,2019.6,2019,2019,2017.4,2018.8,2017.3,2016.7,2017.2,2017.3,2017.2,2018,2016.5,2013.9,2012.5,2012.2,2010.9,2009.7,2002.9,1998,2000.7,2001.6,2002.5,2000.3,1998.4,1998.6,1995.4,1995.3,1997.7,1996.8,1996,1996.2,1995.7,1994.9,1996,1994.2,1994.4,1994.5,1996.7,1996.6,1989.1,1990,1988,1987.2,1986.4,1986.4,1987.9,1983.6,1983.6,1986.3,1988,1988.5,1994,1994.2,1996,2002.5,2005.3,2008.8,2013.5,2011,2016.7,2017.7,2024.1,2025.2,2024.8,2031.4,2033.4,2039.7,2040.6,2047.3,2039.5,2036,2035.6,2037.4,2038.5,2043.4,2039.7,2036.8,2040.2,2037.5,2038.4,2037,2044.2,2043.7,2038.8,2037.5,2038.5,2028.6,2028.6,2026.8,2027.9,2026.5,2027.4,2027.7,2028.2,2029.8,2027.7,2028.6,2026.8,2030.1,2024.3,2023.4,2018.8,2007.3,2013.9,2009.5,2002.7,2006.8,2009.6,2008.2,2004.2,1998,2003.4,2009.8,2019.3,2020.7,2023.9,2019.2,2013.2,2013,2010.6,2006.5,2008.5,2006.6,2008.5,2013.8,2011.1,2010.7,2010.6,2015,2012,2011.5,2009.7,2007.9,2008.8,2009,2006.3,2006.7,2006.4,2008.1,2008.3,2007.7,2007.8,2010.6,2012,2014,2014.5,2013.8,2014.1,2008,2010.4,2012.4,2009.1,2008,2004,2007.3,2011.1,2008.1,2014.4,2014,2016.3,2012,2007.9,2012,2012.9,2013,2015,2019.4,2016.8,2017.9,2021.1,2020.9,2021.8,2020,2019.4,2021,2018.7,2018.2,2018.3,2018.4,2020.5,2023,2022.8,2022,2022,2021,2025.6,2028.6,2033.6,2037.6,2041.6,2043.5,2041.9,2038.9,2040.5,2039.7,2040.4,2032,2031.5,2031,2028,2027.9,2027.3,2032.5,2032.9,2033.8,2034,2035.1,2034,2029.4,2029.3,2031.8,2034.3,2033.1,2027.3,2028,2035.6,2036.4,2034.4,2036,2035.3,2036,2033.4,2034.1,2029.6,2031.2,2030.9,2030.8,2029.5,2029.3,2030.5,2028.6,2029.1,2030,2027.9,2027.9,2028.8,2030.1,2029.8,2027.6,2028.4,2029,2027.8,2028.5,2028.6,2029,2031.1,2032.1,2028.6,2028,2029.6,2029.2,2031.1,2028.1,2031,2032,2030.1,2028,2028.7,2029.6,2029.5,2028.1,2023.9,2024.1,2028,2050,2050,2047.1,2044,2043.6,2040.9,2039.8,2043,2042.3,2040.9,2036,2035.9,2034.6,2034.9,2036.5,2035.9,2032,2030.9,2028.8,2027.7,2029.1,2028.5,2026,2022.7,2018.8,2023.7,2023.8,2025.6,2024.6,2024.9,2020.9,2017.9,2017.4,2019.2,2016.1,2015.4,2019.4,2019.8,2015,2012.4,2013.6,2012.4,2015.5,2015.5,2018.6,2022.6,2020.1,2016.7,2017.9,2005.1,2010.3,2008.2,2009.8,2005.7,2006,2009.8,2010.4,2014,2012.1,2010.2,2009.9,2009.1,2007.1,2009,2006.6,2008.6,2007.7,2005,2009.6,2012.7,2012.7,2015,2012.7,2013,2015.9,2016.4,2014.5,2013.5,2013.9,2015,2014,2013.4,2013.4,2014.5,2015.7,2012.5,2014.3,2019.6,2022.3,2024,2029.9,2035.7,2033.2,2035.8,2034.7,2034.4,2035.3,2038.8,2047,2046.7,2047.5,2047.6,2046.4,2046.5,2047.2,2046.3,2041,2042.6,2044.2,2042,2040.7,2038.5,2038.4,2040.6,2039.6,2038.8,2038.6,2038,2036.5,2036.5,2038.5,2038.7,2037.4,2036.5,2037.4,2040.4,2039,2039.9,2038.5,2043.7,2044.5,2043,2047.2,2046.7,2047.9,2047.9,2047.6,2049.1,2051.8,2057.8,2061.5,2063,2060,2059.7,2061.6,2062.8,2060,2068.7,2066.9,2068.3,2069.2,2073.3,2069,2071.7,2071.4,2068.9,2068.3,2068.9,2068.9,2066.9,2063.6,2064,2064.8,2064.5,2067.7,2070,2074.1,2078.8,2076.9,2078.5,2077.5,2075.4,2074.9,2073.1,2075.8,2076.5,2075.9,2078.4,2088.4,2091.5,2088.9,2086.4,2083.5,2085.4,2083.5,2086.3,2083.9,2085,2085.2,2075.8,2077.9,2076.8,2080.5,2082.5,2081.5,2080,2069.3,2070.9,2070.2,2069.6,2071.5,2070.6,2070.7,2068.2,2071.1,2069,2070.7,2071.1,2070.7,2069.9,2071.5,2071.3,2072.8,2072.6,2072.5,2073.1,2071.8,2070.4,2071.3,2070.5,2069.8,2072.5,2072,2072.3,2072.4,2072.2,2072.5,2077.6,2078.3,2079.8,2079.8,2079.4,2078.5,2083.1,2083.3,2080.6,2077.9,2079.2,2076.8,2068,2070.4,2070.9,2070.7,2074.5,2073.4,2070.1,2070.5,2070.3,2072.7,2069.8,2069.7,2066.7,2067.4,2064.8,2062.1,2065.3,2063.5,2065.5,2066.9,2066.1,2064.5,2067.1,2066.5,2065.7,2066.5,2067.2,2068.6,2069.1,2068.1,2066,2065.4,2065.1,2067.3,2065.5,2066.1,2066.5,2066,2071.5,2070.9,2070.5,2064.4,2063,2057.5,2055.5,2056,2056.9,2057.2,2053.7,2053,2051.3,2048.9,2043.7,2044.3,2039,2039.1,2039.4,2038.5,2039.7,2036.5,2038.4,2038.8,2039,2040.2,2038.5,2037.7,2038.3,2039,2037.9,2038,2039.8,2039,2038,2039.4,2039.2,2038,2037.6,2038.1,2037.8,2037,2036.5,2033.7,2030.9,2028.8,2027.8,2029.2,2031.3,2029.2,2030.7,2030.8,2030.9,2031.2,2037.7,2039.4,2047.5,2049,2044.9,2047.5,2043,2041.4,2047.3,2045.9,2044.1,2049,2053.7,2054.4,2052.4,2048.6,2046.8,2047.7,2042.7,2041.3,2039.7,2040.9,2038.9,2037.8,2042,2040.5,2041.6,2043.2,2042.6,2039,2040.8,2044.4,2044.5,2040,2041.2,2039.8,2037.3,2035.5,2040.5,2039.6,2039.1,2041.7,2040.3,2039.3,2039.5,2039.3,2040.5,2033.1,2034.1,2033.5,2030.8,2032.1,2031.4,2027.5,2031.2,2023.1,2028.1,2031.7,2032.4,2032,2039.9,2037.5,2036.8,2038,2036.2,2035.8,2037.7,2046.9,2050.4,2050.7,2051.4,2051.1,2052.5,2050.1,2047.7,2049.8,2050.7,2050,2053.3,2056.9,2056.2,2055.9,2058.1,2060.6,2062.8,2058.1,2057,2056.9,2058.4,2054.7,2055,2057.9,2062,2058.5,2055.8,2055.6,2052,2053.5,2052.7,2052.4,2056.7,2057.8,2056,2056.7,2054.5,2055.5,2060.3,2059.4,2063,2065.1,2061,2060.9,2061.4,2060.3,2062.4,2060,2058.3,2058.9,2055.5,2057.8,2058,2057.2,2058.5,2055.5,2056.2,2055.4,2056.2,2055.8,2057.5,2057.7,2058.5,2058.5,2057.1,2057.5,2057.7,2059.3,2058.9,2060.4,2059.9,2060.2,2047,2046.6,2046.6,2046.2,2047.3,2048,2048.6,2047,2050.1,2047.8,2046.8,2048.3,2051.8,2051,2053,2052.4,2050.5,2053.6,2053.9,2037.7,2033.4,2034.7,2036.6,2037,2035.4,2036.1,2041.1,2037.4,2036.3,2036,2037.4,2036.9,2036.2,2035.1,2034.4,2037.3,2036.7,2031.3,2032.7,2032,2031.9,2033.4,2033.6,2033,2032.1,2035,2036,2035.2,2036.4,2035.1,2035.6,2035.3,2036.2,2034,2036.6,2038.8,2037.4,2037.9,2043.4,2042.5,2043.7,2047.6,2045.5,2046.3,2049.7,2053.8,2055,2047.5,2045.7,2045.5,2044.1,2042.8,2042.4,2037.1,2037.1,2038.2,2039.8,2038.6,2041.5,2038.7,2037.8,2040,2038.8,2037.4,2037.8,2038.6,2036.1,2036.9,2035.2,2035.5,2035.5,2039.4,2037.3,2037.4,2037.6,2038.2,2037.5,2028.9,2030.3,2028,2030.5,2031,2031.5,2029.2,2029.5,2034.3,2038.2,2035.8,2041.6,2038.8,2039.3,2040.4,2039.3,2029.8,2031.3,2033,2030.1,2021.8,2023,2026.3,2025.2,2030.7,2030.1,2030.7,2030,2029.6,2027.1,2027,2026.5,2025.8,2027,2028.2,2027.4,2029.7,2028.6,2028.2,2027.2,2023.5,2022.6,2023.2,2022.9,2020.1,2017,2017.3,2014.5,2013.4,2006.9,2004,2012,2013,2016.7,2016.7,2018.9,2020.5,2021.7,2020.3,2019.5,2020.5,2026.4,2021.9,2021.2,2023.8,2025.1,2029.6,2031.1,2040,2045.2,2043.8,2045.7,2041.5,2039.5,2037.8,2040,2039.1,2036.2,2037.5,2037.7,2040.4,2041,2039.5,2038.6,2038,2041.6,2041.8,2040.9,2039.7,2037.3,2038.1,2033.9,2033.9,2036.6,2034.9,2036.5,2038,2039.2,2040,2035.5,2034.1,2033.7,2034.8,2036,2034,2036.5,2037.4,2038.9,2037.3,2038.5,2038.6,2037.6,2038.7,2038.6,2033,2030.9,2031.9,2031.5,2011.6,2011.5,2012,2006.8,2007.1,2007.4,2002.8,2003.7,2004.5,2004.2,2004.7,2004.9,2006.5,2005.5,2002.9,2001.5,2003.4,2007,2005.3,2004,2003,2002.1,2000.9,1998.5,1996.1,1997.5,1997.1,1998.3,2006.6,2008.4,2013.5,2014,2013.8,2017,2011,2009.4,2010.6,2012,2011.8,2014.5,2013.5,2014.8,2010.1,2010.5,2007.6,2010.9,2010.7,2011.9,2010,2017.3,2016.4,2020,2022.9,2018.8,2019.8,2022,2022.9,2023.5,2021,2021.8,2020.6,2019.7,2020.7,2027.8,2024.9,2024.6,2025.6,2025.6,2025,2025.1,2021.7,2021,2020.8,2020.3,2021,2020.6,2018.1,2018.9,2019.3,2022,2024.6,2026.5,2026.4,2028.3,2027.6,2029.5,2028.9,2028,2027.8,2025.2,2023.6,2025,2023,2022.4,2020,2019.6,2019.4,2022.4,2019.9,2020.9,2021.7,2021.9,2023.8,2023.6,2024,2022.2,2024,2025.9,2024.7,2025.4,2026.5,2027,2027.2,2026.6,2024.8,2023.9,2024.3,2022.7,2022.8,2024.2,2024,2024.2,2025.3,2022.9,2023,2022.5,2022.7,2022.5,2021.6,2022,2020.9,2022.3,2021.5,2024.6,2024.1,2024.2,2025.7,2021,2020.7,2022,2025.4,2027.4,2025.1,2026.6,2030.1,2033,2033,2032.8,2034,2034.8,2031.9,2030.5,2029.4,2029.7,2029.8,2028.8,2028.9,2025,2023,2022.7,2019.6,2022.2,2022.9,2024.9,2024,2022.7,2023.4,2023,2024,2023.4,2022.2,2022.6,2021.7,2021.8,2020.7,2019,2016.6,2019.5,2021.1,2021.8,2019.6,2024.9,2024.5,2020.8,2018,2020.1,2025.8,2022.8,2024,2024.5,2025.9,2024.1,2020.8,2019.5,2020.7,2024.8,2022.6,2022.8,2023.1,2023.1,2024.8,2027.5,2027,2025.1,2022.9,2023.7,2022.8,2021.3,2022,2019.7,2020,2020.6,2021.4,2020.1,2019,2015.9,2012.2,2013.4,2012.2,2013,2011.3,2008.3,2008.8,2009.9,2010.1,2009.8,2013,2010.6,2012.7,2010.5,2011.4,2013.5,2012.7,2016.6,2014.1,2018.9,2013.8,2013.8,2017.7,2017.9,2017.8,2016.1,2012.4,2008.6,1990.1,1993.6,1995.1,1996,1996.1,1994.7,1995.3,1995,1994.2,1995,1997,1999.5,2001.4,2000.1,1999.2,1999.3,1999.9,2001.5,1999,1996.1,1996.3,1996.9,1999.2,2001.3,1997,1998,2001.2,2000.1,1999.5,2003.2,2007.8,2007.5,2005.6,2007,2005.9,2010.7,2012.9,2011.8,2014.5,2013,2011.4,2010.7,2009.9,2007,2008.7,2009.8,2011.8,2009.1,2003.9,2005,2003.2,2003.7,2005.2,2004,2003.7,2005.3,2004.3,2005.8,2006.2,2006.3,2005,2005.2,2003.2,2002.5,2002.9,2002.9,2001.6,2000.7,2001.7,2000.7,1997.4,1997,1996.6,1997.6,1997,1998.1,1997.6,1996.7,1999.9,1996.5,1997,1998.2,1996.9,1997.4,1996.9,1996.8,1995.6,1997,1997,1995.7,1994.4,1997.4,1996.9,1996.9,1996.6,1990.7,1985.7,1988,1991,1986.5,1987.8,1988.8,1988,1989.1,1992,1992.5,1994.1,1996.7,1996.7,1995,1995.9,1994.9,1994.1,1994.1,1993.8,1991.4,1992,1991.7,1991.4,1990.5,1990.9,1991.4,1989.7,1992,1992,1990.8,1990,1989.8,1985.6,1986.3,1987.2,1988.9,1989.1,1987.6,1986.9,1988,1988.2,1987.6,1986.1,1983.8,1983,1983.7,1984,1981.2,1978.6,1975.4,1973.1,1972.1,1975.7,1977.3,1975.8,1976.3,1975.5,1974,1973.3,1972.7,1973.4,1973.6,1973,1974.5,1974.1,1975.1,1975.9,1977,1975.4,1973.5,1974.3,1973.6,1973.4,1972.8,1972.8,1974.6,1974.6,1975.8,1977,1976,1975.1,1975.6,1976.7,1976,1976,1976.3,1983,1985.5,1990.6,1993.2,1992.4,1992.8,1991.6,1990.9,1993,1988.7,1986.7,1982,1979.5,1966,1972.4,1969.9,1971,1970.6,1967.8,1973,1973,1973,1971.6,1972.7,1972.8,1972.2,1971.3,1972,1971.7,1971.9,1969.1,1969.1,1969.2,1968.9,1968.6,1971.9,1971.2,1969.4,1969.3,1968.8,1971.3,1968,1971.8,1971.8,1971.9,1971.9,1978.6,1980.6,1978.6,1976.8,1976.1,1978,1983,1979.7,1977.6,1978.7,1979.5,1980.9,1977.6,1980.2,1985.1,1986,1983.4,1982.4,1982.2,1984.4,1983.7,1984.1,1982.9,1983.2,1984.7,1984.1,1984.3,1983.5,1984.1,1982.9,1983.4,1982.3,1981.6,1982.7,1984.3,1983.9,1982.4,1984.6,1983.6,1983.6,1983.1,1982.7,1983.9,1983.1,1984.3,1986.5,1985.1,1984.9,1984.4,1981.1,1981,1979.5,1979.5,1980.7,1979.7,1979.6,1978,1979.3,1979.4,1978.4,1976.3,1977.7,1974.1,1975.7,1980.1,1979.1,1982,1969.1,1968.2,1966.5,1967.6,1967.5,1964.7,1961.3,1960.7,1962.2,1963.7,1963.1,1962.7,1962,1956.7,1955.4,1955,1954.1,1955.6,1956.1,1956.2,1956.7,1957.7,1954.5,1955.1,1954.7,1953.9,1953.3,1951.7,1950.3,1951,1950.9,1952,1952.1,1950.5,1948.3,1953.7,1953.4,1952.4,1952.4,1952,1950.7,1949.5,1948,1943,1943.8,1943.7,1938.2,1939,1937,1941,1942.1,1942.5,1942.6,1941.6,1943,1943.8,1943.3,1944.2,1943.6,1942.5,1942.4,1941.5,1940,1939.3,1939.8,1939.2,1940.8,1941.5,1943.3,1943.5,1945,1946.7,1951,1950.9,1949.5,1949.5,1950.8,1949.5,1950.3,1953.2,1949.9,1950,1951.1,1953.3,1950.7,1948.5,1948.6,1947.9,1951,1951.6,1954,1954.4,1952.8,1950.2,1949.4,1952.8,1950.1,1950.5,1945.6,1945.6,1946.9,1945.7,1946.6,1946.7,1947.5,1948.6,1947,1946.7,1946.5,1945.4,1945.2,1945.3,1945.5,1946.7,1947.8,1952.7,1955.3,1956,1955,1957.9,1958.7,1957.7,1958.7,1958.3,1957,1957,1957.3,1957.6,1958.6,1959,1959.8,1957.6,1957.5,1957.6,1955.2,1956.6,1957.7,1958.6,1956.4,1957.8,1960.6,1956.3,1957.6,1960.4,1964.2,1958.5,1961.5,1952.8,1950.6,1947.5,1949.1,1949.2,1948.2,1946.5,1946.3,1946.2,1947.5,1947.6,1946.8,1948.5,1948.7,1948.5,1948,1947.5,1947.6,1950.8,1949.2,1951.6,1951.3,1953.2,1952.5,1951.7,1951.5,1950,1950.8,1951.3,1951,1950.5,1950.3,1951.3,1951.6,1952.5,1954.2,1953.2,1953.2,1954.4,1952.8,1953.2,1951.1,1952.6,1953.4,1953.5,1952.8,1953.6,1951,1952.8,1964,1967.3,1967.2,1965.8,1965.5,1963.9,1965,1965.2,1964.5,1965.4,1964.8,1964.4,1965.7,1966,1973,1972.1,1971.3,1970,1965,1966.3,1965.8,1965.1,1966.2,1965.9,1965.2,1965.5,1966.1,1965.6,1966.1,1966.5,1965.9,1966.8,1965.9,1966.6,1967.5,1967.3,1968.2,1969.3,1967.7,1964.4,1965.2,1964.4,1958.4,1958.5,1953,1950.2,1946.4,1937,1939,1963.1,1961.8,1961.6,1961.4,1962.5,1960.8,1962.7,1960.6,1958.7,1960.5,1957.9,1954.8,1956.5,1951.7,1953.2,1953.5,1952.9,1953.4,1953.7,1955.7,1956.4,1957.8,1957,1955.8,1961.2,1959.8,1957.1,1958.7,1959.7,1960,1959.4,1960,1966,1966.3,1967.4,1968.8,1967.4,1965.5,1961.6,1964.5,1962.5,1964.4,1965.3,1961.7,1961.7,1961.5,1962.8,1963.8,1965.2,1969.2,1968.3,1967.8,1970,1967.4,1966.1,1967,1970.9,1967.5,1968.3,1967,1966.8,1967.4,1964.6,1964.5,1965.4,1964.7,1964.5,1965.6,1965.7,1965.1,1965.3,1964.9,1965.3,1964.2,1964.6,1964.3,1965,1964.8,1965,1965.7,1966.3,1965.4,1965.2,1966.5,1966.5,1963.9,1964.4,1964.6,1965.9,1964.1,1964.5,1961.3,1961.5,1960.9,1961.7,1962.1,1963.5,1964,1958.1,1956.6,1956,1956.1,1958.1,1957.7,1957.9,1958.5,1959.4,1959.2,1962.1,1961,1960.6,1960.2,1958.8,1957.8,1957.3,1956.2,1957,1957.1,1957.1,1956.5,1956,1954.4,1952.5,1952.7,1953.4,1952.3,1952.7,1950.2,1951.6,1953.1,1955.4,1955.1,1954.5,1956.6,1958.4,1959.9,1957.5,1960.5,1959.7,1960,1963,1962.7,1964.5,1962.2,1962.4,1963.7,1959.9,1969,1966.4,1965.5,1965,1966.8,1965.5,1967.7,1968.1,1969.2,1971.2,1968.5,1968.1,1970.2,1968.8,1969.6,1970.5,1970.7,1970.3,1969.2,1970.6,1970.7,1969.9,1971.2,1971.2,1971,1971.3,1971.8,1971.4,1973.5,1974.2,1974.7,1974.2,1974.9,1976.1,1975.6,1976.4,1974.5,1973.7,1971.5,1972.2,1972.3,1971.6,1972.3,1972.4,1972.5,1971.3,1971.2,1971.3,1971.4,1973,1973.9,1971.7,1968.3,1966.2,1960.3,1963.5,1964.5,1963.8,1964.2,1963.9,1963.1,1963.9,1962.9,1962.6,1961.3,1962.1,1963,1963.5,1963.3,1962.3,1964.5,1964.5,1966.8,1965.6,1964.9,1964.8,1964.5,1961.9,1961.1,1963.4,1961.2,1962.5,1962.9,1963.7,1964.2,1964.9,1965.3,1963.5,1964.7,1963,1963.7,1964.6,1961.6,1964.2,1962.5,1958.5,1964.4,1964,1968,1968.2,1967.9,1966.2,1967,1968.2,1969.7,1968.2,1968.8,1967.3,1967.2,1967.7,1967,1968.1,1969.3,1969.6,1971,1974,1973.8,1974.7,1975.4,1975.6,1975.3,1976.5,1974.8,1976.4,1978.6,1977.9,1979.4,1979.3,1980.1,1980,1980.8,1982.5,1983.4,1983,1981.7,1980.7,1982,1981.1,1981.1,1977.7,1980.3,1981.2,1982,1984,1986.9,1986.1,1984.8,1985,1985.2,1984.9,1988.9,1988.7,1987.8,1987.9,1988.6,1989.2,1987.4,1986.1,1985.3,1983.9,1983,1983.8,1983.9,1983.5,1983,1983.6,1983.4,1983.9,1983.3,1984,1985.2,1984.9,1984.7,1985.6,1987.2,1990,1999.8,2005,2005.7,2009.1,2010.4,2009.4,2006.7,2004.8,2004.8,2004.6,2003.7,2002.6,2000.1,1999.6,1996.2,1996.7,1993.4,1991.2,1990.8,1991.4,1998.5,1998.8,1999.1,2000,2003.1,2002.9,2006.9,2002.9,2004,2006,2001,2000.5,1999.5,1998.4,1997.6,1999.6,1998.7,1999.3,2000.6,1996.4,1997,1997.2,1997.5,1996.9,1996.4,1997.7,1995.9,1997,1997.3,1998.4,2000.4,2002.7,2002.9,2005.5,2005.3,2002.8,2004.5,2002.5,2002.8,2001.9,2002,2001.1,2005.1,2005,2004.1,2006.7,2006.3,2008.2,2009,2010.1,2010,2009.1,2006.9,2005.2,2003.7,2004.7,2004.1,2003.6,2004.6,2005.7,2005.4,2005.4,2004,2004.9,2005.1,2005.2,2005.5,2004.8,2005.4,2004.8,2004.1,2004.8,2004.5,2003.5,2005.5,2005.8,2007.3,2005.1,2005.3,2006.3,2005.6,2007,2010.8,2009.5,2008.9,2009.6,2007.8,2007.5,2007.1,2008.6,2007.7,2007.8,2004.8,2003.6,2005.8,2008.1,2006.4,2006.4,1998.7,1999.3,1998.7,1999.7,2002.4,2000.6,2005.8,2003.5,2003.1,2001.9,2001,2001.2,1998.7,1998.5,1996.4,1997.1,1999.2,1998.5,1997.6,1994.1,1994.1,1995,1994.7,1994.5,1995,1993.4,1994.4,1993.6,1993.5,1993.5,1997.6,1997.3,1998,1998,2001.5,2001.9,2002,2000.6,2002.6,2004.5,2004.5,2004.8,2005.5,2004.2,2004.7,2006,2009.1,2007,2012,2013,2012.1,2011.1,2012.8,2011.2,2009.5,2010.3,2011.6,2012.3,2012.8,2010.9,2010.6,2010.8,2010.2,2011.5,2013,2012,2011.9,2011.6,2010.4,2010.5,2011.8,2011.9,2011.8,2012,2011.5,2010.5,2010.5,2011.2,2011,2011.2,2012.3,2010.6,2011,2012.2,2012.8,2012.3,2013.8,2014,2013,2011.4,2010.8,2010.4,2010,2009,2009,2003.4,2008.8,2010,2008.8,2008.5,2006.2,2007,2007.6,2009,2008.8,2007.4,2006.2,2005.1,2004.7,2004.6,2004.5,2005,2005.8,2006.8,2007,2008.9,2007.5,2007.2,2008,2007.4,2007.6,2007.1,2007.5,2006.9,2006.8,2007.1,2007.8,2007.9,2008.9,2009.6,2008.3,2007.3,2007.7,2007.4,2007.5,2007.2,2006.6,2006.7,2007,2006.5,2005.5,2003.6,2003.5,2000,1998.3,1998.2,1997.6,2001,1999.4,2000,1999.9,2003.4,2008.6,2008,2007,2008,2008.8,2009.8,2009,2008.4,2008.7,2008.8,2010,2011.9,2012.7,2012.8,2015.1,2014,2013.8,2013.3,2012.9,2013.6,2013.5,2013.3,2013.4,2013.9,2015,2015.9,2015.3,2015.8,2015.9,2016,2013.6,2013.5,2012.7,2012.1,2012.7,2013.2,2012.4,2013.2,2013.7,2014.7,2015.5,2014,2014.8,2014,2015.6,2017.3,2018.1,2018.5,2022.5,2020.6,2020,2016.8,2016.1,2015.5,2015.2,2016.5,2017.3,2015.4,2016.3,2015.5,2016,2015.7,2013.2,2013.7,2013.1,2014.7,2016.5,2018.3,2017.1,2017.3,2017.4,2016.7,2017.2,2017.4,2014.1,2013.7,2014.4,2014.2,2014,2012.6,2013.6,2013.5,2013,2013.8,2008.5,2007.8,2008.1,2007.3,2004.8,2008.5,2012.2,2012.1,2009.8,2013.5,2013.4,2013.4,2012.8,2011.9,2010.2,2010.6,2011.1,2013,2011.8,2007.8,2007.7,2006.2,2005.5,2007.8,2007,2007.7,2006.8,2008.5,2006.4,2006.1,2005.7,2006,2006.1,2006.2,2006.6,2006.8,2006.2,2005.9,2005.7,2006.9,2002,2002.3,2005.1,2006.2,2007,2006.6,2007.3,2011.4,2011,2012,2010.9,2010.6,2011.8,2010.2,2008.5,2009,2008.8,2009,2012.9,2012.5,2012.7,2011.7,2012,2010.5,2011.3,2012,2011.6,2008.9,2006.7,2004.1,2004.1,2005.5,2007,2006.3,2007.2,2005.7,2005.5,2007,2006.3,2006,2005.7,2005.5,2005.6,2006.7,2006.4,2007,2006.7,2006.8,2007.4,2005.5,2006,2005.1,2005.7,2004,2005,2004.5,2003.6,2005,2002.7,1998.4,1996.7,1995,1996,1982.9,1985,1986.4,1995,1992.2,1991.8,1991.2,1993.6,1991.8,1989.2,1988.9,1992,1991.8,1992,1992,1991.4,1992.2,1990.5,1992,1990.5,1990.7,1990.5,1989.7,1989.2,1988,1987,1986.1,1984.8,1986.4,1985.5,1984.6,1983.3,1985.5,1985.9,1989.8,1989.7,1987.9,1990.3,1990.1,1993,1991.2,1991.3,1991.2,1990.4,1992.3,1994.6,1991.6,1992,1994.4,1995,1996.8,1998.3,1999,1996.2,1994.7,1995.3,1995.4,1994.5,1995.7,1994.1,1991.9,1991.8,1991,1989.4,1984.8,1986.9,1988.7,1988.1,1990.9,1991.9,1994.4,1997.5,1996.3,1997,2003.7,2004.1,2001.8,2000.5,1999.9,2000,1999.1,1998.6,1998.9,1995.4,1994.4,1994.8,1996,1995.8,1996.5,1996.5,1998,1998.5,1999.3,1997.8,1996.5,1998.1,1995.8,1996.6,1998.5,1999.7,1999,1999.5,1993.1,1993.5,1993.8,1993.3,1995.8,1996.4,1997.1,1996.6,1996.3,1994.4,1992.8,1993.1,1993.2,1991.8,1990.6,1991.7,1992.9,1993.7,1993.7,1993.8,1993.9,1995.3,1995.1,1996.4,1995.4,1994.4,1993.8,1993.7,1994.5,1994,1995.5,1993.7,1994,1995.1,1995,1996.5,1996.7,1995.2,1994.8,1993.4,1994.3,1996.3,1994.7,1993.2,1994.1,1992,1993.9,1993.9,1994.3,1992.5,1993,1993,1995.6,1993.9,1992.9,1990.3,1989,1988.6,1988.8,1989.9,1989,1989,1989.2,1988.8,1988.6,1989.4,1988.4,1988.6,1987.4,1988,1988.5,1987.6,1987.2,1988.7,1988.2,1987,1987.6,1987,1986.9,1986.4,1985.7,1988,1987,1987.2,1989.3,1988.7,1987.6,1987,1987.4,1986.1,1981.4,1980.6,1981.2,1979.8,1977.9,1978.7,1977.7,1976.5,1966.9,1968.4,1969,1965.4,1966.6,1966.2,1966.2,1964.7,1962.7,1963.1,1962.7,1964.7,1963.9,1963.3,1959.9,1959.4,1958.7,1959.5,1959.1,1960,1961.5,1961.3,1961.5,1960.6,1959.6,1957.3,1955.8,1956.2,1953.6,1954.5,1954.9,1955,1955.2,1954.8,1954.2,1953.5,1954.3,1951,1946.7,1939.5,1940.4,1940,1932.6,1939,1939.8,1929.7,1936.2,1936.3,1941.5,1937.8,1937.9,1935.3,1936.8,1938.3,1936.8,1935.7,1932.4,1934.7,1933.1,1930.5,1928.7,1926.8,1924,1920.9,1918.6,1919.3,1922.8,1921.8,1921.4,1924.6,1925,1928.8,1926.5,1924.1,1922.7,1922.3,1924.3,1925,1926,1930.6,1934.3,1939.2,1939.4,1937.2,1938.9,1942,1942.1,1941,1937.9,1939.7,1938.9,1941.5,1938.9,1941.1,1943.9,1942.6,1944,1943.5,1940.4,1939.1,1939.8,1935.4,1936.5,1934,1935.2,1934.1,1931.1,1926.9,1926.7,1924.9,1928.4,1926.9,1925.5,1927,1927.6,1919.9,1925.2,1926.8,1925.4,1928,1927.3,1927.7,1924.8,1926.1,1926.5,1927.1,1931.7,1931.1,1929.9,1929.1,1925.6,1925.2,1924.1,1924.3,1922,1926.6,1921.8,1923.3,1925.3,1923.5,1925.1,1928.8,1924.2,1919.7,1919.1,1920,1919.1,1914.9,1913.8,1912.8,1918.9,1918.1,1919.4,1918.9,1925.1,1925.4,1924.5,1919.7,1922.5,1920.6,1918.8,1919.8,1916.8,1915.8,1916.4,1916.1,1914.9,1914,1913.7,1908.6,1910.8,1909.1,1908,1904.5,1909.7,1911,1910.4,1911.4,1910.3,1908.8,1906.6,1906.8,1909,1911,1914.5,1916,1924.9,1925.8,1928.8,1927,1928.2,1929.4,1937.4,1935.8,1936.4,1936.3,1933.5,1933.2,1930.4,1932.1,1932.1,1927.9,1928.5,1927.8,1930.8,1928.6,1927.6,1928.2,1927.8,1927.1,1929.8,1928.6,1931.1,1931.9,1929.6,1929.2,1930.4,1930.8,1929.3,1929.7,1930.2,1930.9,1931.6,1932,1933.5,1933.9,1929.1,1928,1930,1929.9,1931,1930.4,1931.5,1930.1,1932.7,1929.7,1931.5,1929.6,1930.9,1931,1928.9,1929.9,1930.6,1931,1930,1924.9,1927,1927.4,1926.2,1923.1,1921.8,1923.5,1922.8,1923.5,1922.8,1923.6,1922.6,1921.5,1915,1913.5,1913.7,1914.6,1915.2,1914.9,1914.8,1912,1911.8,1913.3,1910.7,1908.1,1909.8,1906.7,1906.5,1905.2,1906.1,1906.6,1909,1905.1,1904.1,1901.4,1896,1896.9,1896,1897.4,1902.1,1907.5,1903.1,1900.2,1895.6,1889,1881.2,1882.1,1889,1893,1887.8,1885.8,1887.8,1891.6,1888.7,1894.2,1897.7,1898.5,1898.8,1899,1897,1897,1895.6,1907,1903.9,1898.7,1898.1,1896.1,1896.1,1894.2,1892.3,1891.2,1894.4,1891.2,1894.4,1891.4,1894.5,1891.5,1892.4,1893.5,1893.1,1895.8,1896.2,1894,1893.1,1892.6,1892.8,1892,1893.3,1888.8,1885.6,1889.3,1885.5,1884.4,1885.6,1885.9,1882.8,1887.1,1884.5,1889.2,1888.1,1889.3,1893.1,1892,1893.5,1897,1892.5,1887.6,1887.1,1883,1882,1874.4,1874.3,1873.3,1874.6,1873,1872,1870.6,1873.3,1874,1871.9,1871.9,1871.5,1870,1871.6,1869.5,1862.6,1864.9,1863,1853.6,1854.4,1852.4,1848.2,1850,1851.9,1859.6,1857.5,1855.2,1856.8,1851.2,1855,1857.8,1847.5,1848,1840,1843,1839.6,1837.6,1838.7,1839,1839.6,1843,1842,1839.4,1835,1837,1835.5,1832.7,1828.9,1829,1838.2,1837.6,1837.5,1834.8,1839.2,1837.7,1835.6,1833.9,1834,1832.4,1829,1829,1825,1823.8,1822.4,1823.1,1822.2,1822.5,1834.6,1838,1843.2,1842.6,1844,1846.5,1851.8,1856,1850.3,1849.5,1848.2,1852.6,1855.6,1856,1857,1852.6,1846.7,1845,1842.7,1837,1833.8,1832.5,1830.5,1828.1,1826,1827.5,1829.8,1827,1827,1822.6,1824.1,1829,1829.5,1827.3,1825.2,1824.9,1825.3,1828.8,1834.5,1833.8,1836.5,1833.2,1833.3,1835,1836.3,1837,1835.5,1834.4,1836.9,1835.5,1832,1831.8,1830.5,1832.9,1829.4,1829.2,1827.5,1832.2,1831.4,1830.7,1832,1835,1832.7,1834.7,1836.7,1835.7,1833,1835,1841.5,1842.4,1845,1844.9,1847.2,1853.9,1853.9,1854,1857.2,1852.5,1852.1,1850,1848.3,1847.2,1847,1847.7,1848.1,1844.7,1844.7,1842.2,1842,1839.8,1836.6,1836.4,1836.8,1838.3,1838.4,1837.5,1837.3,1839.1,1842.6,1843.8,1842,1838,1833.1,1833.3,1832.4,1832.7,1833.3,1835.8,1833.5,1835.4,1837.8,1835.5,1833,1828.3,1827.3,1813.9,1811.1,1803.6,1801.7,1801,1804.9,1811.7,1811.3,1814.2,1816.8,1812,1812.3,1813.1,1808.9,1807.6,1808,1810.7,1810,1814.5,1812.1,1813.1,1811.4,1811.3,1819.1,1817.7,1823.4,1821.7,1823,1822.6,1818.6,1819.5,1822.2,1824.4,1828.9,1829,1832,1826.8,1827.6,1826.8,1825.2,1828.5,1833.8,1826.8,1831.4,1828.7,1827.4,1828.6,1823.8,1822.6,1821.5,1824,1823.1,1823,1822.8,1819.6,1823,1824.4,1823.5,1823,1824.7,1822.9,1823,1823.9,1821.2,1822.5,1823.1,1824.3,1823.6,1825.1,1824,1822.6,1822.8,1823.2,1820.9,1821.6,1819.8,1816.5,1817.5,1816.6,1819.1,1823.3,1834.9,1841.4,1838.9,1838.1,1837.8,1838.5,1838.7,1839.3,1840.3,1837.2,1847,1845.8,1848.8,1846.1,1847.1,1848.4,1849.2,1850.6,1851,1850.7,1850.4,1848.7,1851.3,1849,1849.5,1851.2,1852.9,1853.8,1857.5,1857.9,1856,1855.7,1859,1855.7,1854,1854.3,1855.3,1861.2,1861.5,1863.4,1865.6,1862.6,1864.5,1867.1,1866.1,1869.6,1869.3,1872.4,1875.3,1878.9,1881.2,1882.9,1879.5,1880.2,1879.6,1881,1880.8,1880.4,1881.4,1884,1889.5,1887,1889.5,1889.8,1894.3,1891.4,1890,1884.8,1893.9,1892.5,1891.2,1887.6,1884.4,1883.9,1881.9,1885.6,1884.2,1885,1883.1,1883.4,1884.7,1887.4,1888.4,1884.4,1884.8,1885.4,1885.5,1885.4,1885,1882.7,1883.4,1883.5,1883.8,1884.9,1884.8,1885.5,1884.2,1884,1881.8,1883,1878.8,1879.7,1877.5,1878.7,1876.3,1874.5,1876,1875.4,1876.3,1873.2,1867.7,1870.1,1869.6,1870.9,1869.8,1871.4,1875,1888.4,1886.9,1889.8,1891.1,1890.5,1886.7,1885.6,1890.4,1894.2,1900.1,1903.9,1899.7,1901.5,1898.5,1897,1896.7,1899.4,1901,1899.1,1901.3,1901.3,1902.1,1898.6,1899,1901.6,1901.2,1903.1,1903.8,1904.8,1904.7,1907.9,1912.6,1911.6,1916.6,1915.1,1920.5,1919.1,1919.5,1919.1,1920.1,1922.6,1923.7,1922.3,1920.4,1918.6,1922.1,1920.1,1916,1914,1920.4,1920.5,1918,1916.5,1918.1,1924,1919.5,1915,1914.3,1914.8,1914.5,1916.9,1916.5,1915.9,1918.6,1920.6,1923.8,1924.1,1921,1922.7,1921.7,1920.1,1918.1,1915.5,1917.7,1917.8,1917.6,1918.4,1919.9,1917.7,1917.9,1920.1,1918.5,1920.4,1922.2,1924,1919.9,1920.6,1921.4,1923,1922.2,1922.1,1922.8,1923.8,1918.1,1920.8,1922.1,1922.9,1925,1937.1,1936.7,1936.9,1936.7,1933.5,1934.8,1931,1926.8,1922,1920.4,1922.6,1925,1924.1,1927.3,1929.5,1928.6,1927.4,1930,1928.7,1928.6,1927.9,1928.3,1928.4,1928.8,1929,1930.3,1928.8,1926.6,1928.3,1928.7,1928.6,1927.3,1926.3,1924,1920.5,1921.6,1923.5,1920.5,1919.1,1918.3,1918.5,1918.2,1912.5,1912.4,1912.9,1908.6,1910.9,1913.8,1913.8,1916,1915.2,1915.5,1916.1,1915.7,1908.3,1907.1,1907.5,1907.8,1905.8,1907.4,1911.5,1914.5,1914.4,1916.7,1920,1918.7,1915.9,1917.9,1916.1,1912.1,1909.8,1911.2,1909.3,1908.2,1907.3,1909.1,1909.5,1909.2,1908.4,1908.4,1912.5,1912.8,1912.7,1907.7,1904.5,1905.1,1904.6,1906.6,1906.2,1905.1,1907.5,1904,1900.3,1897.8,1896.6,1901.3,1901.7,1896,1896,1896.4,1896.3,1894.5,1892.9,1891.2,1892.1,1892.6,1891.9,1888.9,1891.5,1891.9,1893.4,1895.7,1902.3,1906.4,1908,1911,1909.8,1908.8,1909.1,1908.5,1910.5,1906.3,1904.8,1903.8,1904,1905.2,1905.5,1905,1909,1906.3,1905.5,1911.3,1911,1911.7,1910.2,1909.7,1906.7,1908.6,1906.7,1907.7,1908.7,1908.3,1907.1,1906.3,1897,1895.8,1890.1,1899.9,1898.3,1900.5,1896.8,1892.6,1892.4,1894.6,1893.7,1900.6,1904.3,1912,1911,1916.3,1914,1914.9,1915.4,1914.8,1912.2,1913.2,1917.5,1917.5,1915.5,1917.5,1919.3,1923.2,1927.1,1926.3,1927.6,1926.7,1928.8,1929.2,1926.8,1928.8,1927.6,1927.4,1928.8,1929,1928.6,1932,1932,1934.5,1933.5,1930.9,1929.5,1931,1930.9,1929.3,1931.8,1928.6,1933.1,1932.1,1932,1940.3,1936.5,1927.4,1928,1925.9,1928.8,1928.5,1929.7,1926.8,1933.8,1931.6,1932.3,1929,1928.8,1928.8,1934,1931.1,1930.5,1932,1931.9,1931.3,1928.7,1929.7,1927.3,1928,1929.1,1929.4,1927,1928.6,1929.1,1928,1931.6,1936,1934.4,1930.4,1924.6,1923.2,1921.4,1921.6,1922.1,1922.5,1923.6,1921.3,1921.8,1922.2,1924,1923.8,1925.2,1925.5,1923.3,1923.8,1924.8,1922.6,1924.4,1931.4,1941.2,1941.7,1947.1,1947.2,1943.3,1943.5,1943.2,1938.7,1939.7,1943.1,1941.9,1940,1939.8,1940.7,1943,1942.9,1942.6,1944,1945.3,1946.8,1946.1,1940.7,1942.5,1941.7,1944.5,1943.9,1942.2,1942.1,1941.6,1937.4,1937.6,1938.9,1938.5,1937.3,1935,1933,1935,1937,1937,1940,1945.5,1945.5,1943.4,1944.7,1946.7,1939.9,1937.1,1937.5,1938.4,1939.5,1937.3,1936.8,1939.2,1939,1937.9,1938.5,1940.1,1938.9,1940.2,1941,1940,1939,1940.4,1939.9,1939.7,1940.8,1942,1941.8,1942.8,1944.3,1941.6,1941.4,1939.4,1938,1935,1935.5,1934.5,1927.9,1924.7,1924.3,1925.3,1924.1,1918.8,1914.2,1914.5,1913,1912.5,1910,1901.1,1905,1905,1903,1903,1903.4,1904,1904.5,1904,1903.4,1895.9,1894.9,1909.7,1908.1,1903,1905.1,1905.4,1908,1905,1905.5,1906.9,1906,1907.9,1905.7,1902.8,1897.7,1897.6,1896.1,1889.3,1890.8,1892.4,1893,1894.6,1894,1892.2,1892.9,1890.2,1891.9,1889.8,1885.9,1883,1883.4,1886.6,1879.3,1876.9,1877,1872.8,1872.5,1876.9,1878.8,1880.2,1879.7,1881.7,1883.8,1882.8,1878.9,1878.5,1883.2,1881.4,1883,1882.7,1882.6,1882.1,1882.9,1880.2,1875.8,1877.3,1875.6,1877.4,1875.3,1874.9,1874.8,1876,1874.2,1877,1877.6,1877.4,1876.2,1875.7,1876.4,1877.8,1878.9,1877.6,1876.1,1878.7,1885.4,1883.6,1884.5,1882.9,1883.1,1884.1,1884.3,1884.1,1884.9,1875.2,1873.9,1877.3,1875.2,1880,1881.9,1880.5,1880.8,1881,1880.5,1879.6,1880.1,1882.1,1886.5,1889.7,1889.4,1888.9,1894.5,1893.6,1894.2,1894.7,1894.1,1889,1888.6,1889.4,1883.5,1884.7,1885.2,1884.3,1884.5,1884,1884,1883,1880,1880.8,1874.8,1874.5,1874.5,1874.9,1876.7,1876.4,1875.5,1875.2,1873.6,1870.3,1870.7,1869,1867.3,1867.3,1869.9,1871.2,1869.7,1872.6,1874,1879.8,1879.4,1877.3,1878.8,1877.1,1873.4,1874.4,1871.6,1873.8,1874.5,1874.8,1874.8,1875.5,1875.6,1878.5,1877.5,1877.2,1870.2,1871.1,1871.8,1870.1,1870.4,1871,1870.3,1868.8,1868.2,1868.8,1872.3,1871.7,1875.8,1874,1872.5,1873.8,1875.8,1876.1,1872,1872.7,1871.2,1872.5,1872,1871.3,1870.2,1872.6,1874.4,1873.9,1875.7,1876.4,1878.9,1880.9,1889.7,1888.6,1891.2,1890.2,1889,1894.5,1897.4,1896.7,1896.2,1893.8,1896.1,1892.5,1893,1893.4,1891.8,1890.3,1890.4,1890.8,1890.6,1893.6,1891.5,1891.2,1891.2,1892.9,1893.4,1893.2,1891.8,1892.2,1890.8,1891.2,1889.8,1891.6,1891.9,1891.9,1890.6,1892,1892.9,1892.6,1893.5,1894.5,1896.1,1901.4,1903.3,1900.8,1898,1893.7,1891.9,1891.2,1891.1,1884.9,1884.1,1879.9,1879,1881.2,1873.2,1874.7,1874.3,1876.1,1877,1876,1875.5,1877.4,1877.9,1875.7,1877.3,1877.8,1877.2,1877,1879,1879.6,1880.6,1881.7,1883.5,1882.9,1885,1887.4,1887.2,1889.9,1894,1903.7,1912.9,1909.5,1908.5,1916.6,1918.4,1918.7,1916.4,1920.2,1921.8,1922.7,1922.3,1921.7,1917.6,1920.5,1926.3,1929.1,1931.5,1934.2,1945.9,1946.4,1950,1947.4,1941.9,1939.2,1935.1,1938.7,1942,1938.5,1940.9,1942.5,1942.2,1946.4,1947.7,1947.9,1948,1948.5,1947.2,1945.4,1940.5,1940.2,1940.7,1936.4,1938.8,1942.1,1942.5,1945,1942,1941.2,1943.8,1945.1,1941.8,1942.4,1941.9,1942.2,1941.7,1940.5,1942,1941.9,1939.7,1938.2,1943.4,1945.9,1944.1,1942.8,1942.2,1942.1,1943,1948.8,1948.1,1948,1947.3,1950.8,1953,1951.8,1957,1957,1954.3,1950.4,1950.1,1951.5,1952,1952.4,1951.3,1954.2,1952.5,1955,1954.2,1954.5,1952.3,1952.9,1955,1954,1953.2,1953.3,1953.4,1952.4,1953.9,1952.9,1950.8,1944.7,1941.9,1940.5,1942.7,1943.7,1944.3,1942.1,1943.4,1943.3,1931.9,1936.5,1942.2,1944.1,1940.8,1943,1941.5,1939.9,1941.9,1941.5,1940.2,1944.8,1943.2,1940.5,1943.1,1948,1947.9,1948.3,1946,1945.1,1943.9,1943,1942.5,1942.1,1938.8,1937.9,1943.7,1937.2,1938.7,1937,1939.6,1937,1936.6,1938,1941.5,1941.4,1939.6,1942,1939.5,1941,1942.5,1945.9,1946.5,1945.6,1947.1,1953,1956.9,1963.8,1962.5,1964.4,1960.4,1961.5,1961.2,1969,1970,1974.1,1976.5,1975.4,1974.5,1973.7,1981.2,1977.3,1975,1979.4,1976.4,1975.1,1973.4,1972.2,1974.4,1975.1,1972.2,1971.6,1972.4,1972,1968.5,1966.8,1969.1,1971.7,1970.4,1972.5,1973.1,1971.5,1970.8,1972,1971.6,1973.6,1972.5,1974,1968.6,1970,1969,1967.1,1969.9,1972.7,1972.1,1973,1972.3,1971.5,1971.5,1973.2,1974.6,1972.4,1976,1976.6,1977.3,1980.8,1975.8,1979.2,1976.4,1975.4,1976.2,1974.8,1976.6,1973.2,1973.7,1972.8,1973.6,1974.4,1975.1,1978.3,1975.7,1974.8,1976.4,1975.4,1977.5,1976.8,1977.9,1978.3,1978.4,1980,1979.2,1978,1977.6,1978,1976.3,1975.7,1976.8,1976,1978.2,1980.1,1989,1991.8,1991.7,1991,1991.2,1991.9,1992.8,1991.7,1991,1990,1992.2,1981.7,1985.7,1982.5,1981.5,1974.6,1972.1,1969.8,1969,1969.7,1969.1,1967.5,1964,1958.7,1959.2,1960.5,1958.6,1957.1,1955,1950,1952.5,1954.3,1954.1,1954.7,1955.1,1958.7,1959.7,1958.9,1957.8,1961.2,1956.3,1957.5,1959,1959.2,1957.9,1960.3,1964,1962.8,1959.9,1953.4,1953.4,1954.4,1951,1954,1956.8,1960.8,1962.3,1961.4,1957.6,1956.8,1956.5,1959.5,1959,1955.5,1962.9,1962.1,1963,1969,1970,1976.1,1979.3,1978,1977.3,1977.2,1974.3,1974.6,1974.2,1973.9,1977,1976.8,1977.1,1975.4,1975.4,1975,1975.3,1975.2,1977.2,1978,1977.1,1976.1,1976.6,1977.4,1978.7,1979,1983,1981.9,1979.6,1975,1975.3,1971.1,1972.1,1973.9,1975.5,1978,1979.1,1979.4,1975.3,1977.1,1979.5,1989,1990.3,1991,1985.6,1986.3,1987.3,1989.2,1990.6,1989.6,1986.4,1987,1989.5,1989.5,1988.5,1987.7,1989.2,1989.8,1991.2,1990,1990,1990,1988.5,1987.5,1986.1,1986.5,1988.1,1987.4,1982.9,1983.4,1984,1983.6,1985,1982.5,1981,1981,1985.4,1985.8,1986.3,1987,1986.2,1988.1,1987.5,1985.8,1984.6,1980.1,1972.6,1970,1970.9,1967.3,1966.6,1969.8,1967.9,1964,1965.9,1964.7,1967,1966.5,1963.4,1961.2,1960,1963.7,1965.2,1963.5,1963.4,1962.5,1960.6,1964.3,1961.1,1963.2,1963.7,1963.2,1964.9,1964.3,1965.5,1967,1965.8,1963.3,1963.4,1963.6,1962.9,1964.6,1963.8,1964,1962.7,1964.2,1963.6,1962.4,1965.8,1963.6,1965.7,1966.3,1966,1963.6,1962.4,1964,1963,1963.4,1962.3,1959.1,1962.6,1963.2,1961,1962.9,1965,1966.4,1964.2,1964.8,1964.5,1967.3,1973.5,1975.1,1977,1975,1975.5,1976.5,1977.3,1978.7,1978.1,1976.2,1976.6,1975.3,1975.7,1974.1,1974.6,1974.4,1974.6,1976.7,1976.9,1972.3,1970.2,1972.3,1972.1,1972.9,1972.2,1972.4,1970.8,1972.7,1971.2,1973.1,1972.6,1971.5,1971.4,1971.2,1970.6,1970.5,1961.7,1962,1962.8,1962.8,1963.5,1966,1963,1962.9,1961.9,1961.7,1962.2,1964.6,1963.4,1965.1,1965.5,1962,1962.7,1963.2,1965.1,1963.8,1963.8,1963.9,1962.9,1962.9,1963.6,1961.6,1960.4,1960.2,1959.7,1959.2,1959,1962.3,1963,1963.9,1963.9,1974.5,1977.4,1972.1,1972.2,1972.6,1971.5,1973.5,1974.8,1975.1,1974.5,1977.6,1974.1,1976.9,1982.3,1982.5,1982.4,1983.2,1980.8,1982.5,1975.5,1960.9,1961.4,1959.8,1960.8,1961.1,1959,1961,1961.6,1960.4,1958.9,1953.2,1952.3,1951.2,1948.5,1949,1948.7,1950,1951.2,1952.8,1950.6,1950.3,1949.9,1952,1951.4,1952.5,1952.4,1950.4,1950.2,1948.6,1949,1951.2,1953.6,1952,1954.5,1955.4,1953.8,1953.7,1952.8,1954.5,1956,1957,1950.7,1951.5,1945.6,1945,1946.9,1944.3,1942,1940,1937.8,1939.2,1939.8,1940.1,1940.6,1942.7,1941.8,1939.1,1939.6,1937.1,1938.7,1936.4,1936.7,1933.2,1932.3,1931.7,1936.4,1937,1935,1935.4,1938,1939.5,1937.7,1936.3,1937.6,1936,1938.1,1938.7,1936.4,1936.8,1939,1937,1935.4,1933.2,1936.4,1934.1,1931,1928.2,1925.4,1923.9,1924.3,1925.2,1927.4,1919,1917.6,1920.6,1924.1,1926.9,1930.9,1936,1936.6,1938.1,1938.5,1940.4,1939.8,1940.6,1937.8,1937.7,1938.1,1937.5,1939.1,1938.5,1943.6,1947,1946.6,1946,1944.7,1944.9,1945.2,1944.4,1943,1941.3,1939.5,1940.8,1941,1941,1941.2,1941.1,1941.8,1943.1,1944,1944.5,1945.2,1943.7,1943.3,1943.1,1944,1943.1,1948,1947.8,1945.6,1945.8,1948.7,1951.1,1952,1946.5,1947.1,1948.1],
      "o": [1847,1847.5,1845.1,1847.7,1844.1,1845.8,1841.2,1841.5,1842.6,1844,1844.3,1842.7,1844.3,1854,1857.5,1853.8,1854,1855,1852.8,1856.3,1855.3,1853.3,1854.5,1849.6,1847.9,1845.6,1847.2,1847.2,1851.8,1851.5,1851.5,1852.8,1849.4,1851.2,1853,1851,1846.2,1843.1,1844.5,1843.1,1845.5,1843,1842.8,1844.3,1838.3,1841.6,1851.5,1852,1851.3,1868,1870.3,1870.8,1874.4,1872.6,1896.7,1892.8,1892.4,1903.7,1897.1,1896.9,1894.6,1895.4,1893.8,1894.4,1895.9,1894.4,1894.8,1895.1,1897,1895,1893.5,1894.5,1895.5,1895.5,1894.3,1894.1,1894.7,1896.5,1896.3,1899,1883.5,1883,1881,1882.5,1882.4,1884.2,1883,1882.3,1879.9,1878.5,1877.5,1876.1,1882.4,1882.6,1875.3,1876.5,1881.4,1877,1896.9,1892.8,1889,1889,1890.5,1893,1901.6,1904,1905.9,1904,1903.6,1904.6,1902.1,1903.4,1905.7,1904,1901.9,1897,1896.5,1896.4,1894.2,1895.8,1893.9,1894.7,1896.3,1895.4,1893.5,1890.8,1890.8,1882.8,1879.1,1880.8,1883.5,1884.5,1885,1888.1,1889.6,1897,1901.1,1899.7,1892,1893.7,1889.5,1893.1,1886.5,1888.2,1885.3,1888.6,1881.9,1844.9,1857.1,1854.5,1856.3,1853.6,1863.3,1860.6,1858.3,1853.7,1855.6,1856.7,1858.3,1857.5,1856,1854.5,1852.6,1855.1,1854.5,1855.5,1858.8,1860.5,1858.7,1858.3,1863,1862,1861.5,1857.5,1856.5,1858.5,1859.1,1857,1859.3,1858.4,1858.5,1858.2,1857.6,1858.1,1859.2,1855.3,1855.3,1855.7,1857.5,1858.7,1861.9,1864.1,1868.5,1863.1,1859.6,1858.2,1841,1830.3,1829.1,1827.1,1824,1821.4,1819.8,1820.5,1817.3,1818.4,1821.8,1820.9,1819.8,1823.7,1816.2,1811.9,1812.2,1812.2,1815,1813.3,1814.5,1814.1,1815.3,1812.3,1812.9,1812.8,1812.4,1814.4,1813.2,1814.2,1814,1819,1814.4,1812.7,1811,1811.7,1816.5,1817.5,1815.1,1813.6,1812.7,1813.3,1806.7,1810,1802.6,1805.2,1800.9,1797.6,1802,1775.1,1778.8,1778.1,1777.6,1780.2,1772.3,1776.1,1775.2,1769.2,1764,1765.5,1760.7,1755.4,1757.2,1760.8,1757.5,1756.7,1759.8,1761,1764.6,1764.5,1761.5,1761,1757,1754.6,1755.3,1759.9,1763.3,1774.8,1770.4,1771.3,1769.6,1766.9,1763.5,1759.9,1757.3,1761,1760.7,1757.1,1751.7,1750.5,1752.8,1749.4,1750.8,1753.2,1752,1743,1743.5,1740,1766,1774.8,1771.9,1769,1767.6,1766,1768,1765.6,1767,1768.4,1770.7,1764.8,1761.9,1763.9,1760.6,1766.9,1768.9,1772.1,1768.6,1767.8,1770.7,1774,1776.4,1775.8,1775.8,1774.9,1775.6,1773.9,1770.2,1770.6,1772,1770.9,1775,1774.1,1771.3,1766.8,1767.2,1767.6,1768,1763.8,1763.3,1766.9,1769.9,1773,1770,1767.7,1763.6,1765.6,1773.9,1809.9,1803.6,1803.1,1801.3,1803.2,1802.8,1808.3,1803.7,1803.1,1802.3,1801.9,1801.8,1802,1798.5,1797.9,1798,1798.2,1801.5,1799.9,1800.1,1800.5,1800.4,1798.7,1799,1799.4,1796,1795,1793.4,1794.2,1795.2,1795.6,1794.2,1795.5,1798.2,1795.8,1799,1800,1800.1,1800.5,1797.8,1797.6,1797.5,1798.7,1798.6,1797.5,1803.8,1804.5,1806,1814,1808,1805.1,1804.4,1803.7,1801,1801.1,1799,1797.9,1797.7,1798.6,1796.4,1795.1,1793,1789.6,1789.2,1793.3,1795.9,1794.2,1796.5,1797.9,1794,1794.6,1796.7,1794.9,1794.8,1794.1,1796.3,1791.9,1792,1791.5,1792.6,1785.5,1786,1786,1786.7,1785.4,1789,1787.5,1787.5,1787.3,1793,1792.8,1790.6,1793.5,1788.1,1792.4,1792,1789.4,1793,1784,1786.7,1789.6,1789.5,1787.4,1790.8,1791,1791.1,1790.5,1795,1795,1795.2,1807.4,1806.9,1805,1805,1805.8,1803.1,1803.3,1802.4,1803.8,1804.8,1804,1803.6,1802.8,1804.8,1806,1805.5,1803.8,1804.3,1808,1806.1,1805.3,1808.3,1808,1814,1811.7,1812.6,1816.7,1817.9,1818.8,1817.1,1819,1822.8,1826.6,1822.7,1825,1828.9,1821.1,1779,1771.4,1774.9,1775.9,1782.5,1780.2,1780.7,1781.3,1781.4,1779.6,1782.9,1782.9,1780.9,1780.3,1783.5,1788.3,1792.1,1793.5,1800.6,1798.8,1798.9,1800.9,1797.4,1797.1,1797.1,1794.2,1797.4,1791.3,1792.2,1794,1796,1795.9,1800.8,1799.4,1805,1806.2,1807.2,1809,1817.2,1818,1821.7,1824.8,1827.1,1820.5,1821.7,1823.3,1818,1813,1808.4,1820.7,1825,1829.4,1829.4,1825.5,1823.4,1825.7,1822.4,1823.2,1821.4,1824.8,1826.9,1828,1824.3,1835.5,1836.2,1834.8,1836.1,1840.7,1838.3,1836.2,1835,1835.1,1837,1831.2,1829.7,1828.5,1829.8,1829.9,1834.4,1835.2,1838.5,1835.2,1826.1,1825.1,1826.8,1822.1,1824.2,1826.7,1821.3,1823.8,1823.8,1829,1827.7,1829,1826,1823.7,1823.2,1823.9,1865,1866.4,1867.8,1874.2,1873.6,1870.8,1871.9,1869.3,1870.3,1872,1871.4,1869.1,1873,1872.4,1870.2,1870.7,1870.8,1870.5,1868.8,1872,1867.2,1867.3,1867,1868.4,1869.3,1867.3,1868,1869.4,1869.8,1868.6,1872,1871,1868.7,1871.7,1870.4,1873.5,1873.5,1871.6,1873.7,1879,1879,1878,1879.4,1878.2,1874.1,1874.1,1876.9,1876.4,1875.8,1856.6,1855.1,1854,1851.6,1850.2,1852.5,1846.5,1846.1,1845.5,1846.8,1848.7,1847.4,1850.4,1848.1,1846.3,1845.4,1845.6,1848.3,1848.4,1848.6,1847,1846.8,1848.8,1847.6,1845.4,1846.2,1846,1845.8,1846,1847.4,1845.8,1842.6,1842,1843.3,1843.9,1843.1,1845.4,1841.9,1841.8,1842,1842.1,1842,1843.3,1843,1845,1844.2,1848.5,1844,1853.2,1868,1867.5,1865.7,1863.8,1864.1,1864.8,1865.2,1864.8,1860.7,1861.9,1862.7,1861.3,1864,1862.8,1862.2,1862.8,1863.3,1861.9,1859.2,1857.2,1856.3,1857,1857.2,1857.8,1857.1,1856,1857.9,1858.2,1858.5,1857.9,1857.8,1856.3,1853.8,1850,1850,1848,1845.8,1840,1842.4,1842.1,1837.4,1837.8,1836.4,1835.5,1832.7,1831,1832.9,1834.8,1835.4,1830,1839.6,1834.9,1834.4,1834.4,1838.9,1841.7,1842.8,1851.8,1853.6,1848,1848.5,1847.8,1844.6,1841.4,1837.6,1835.2,1833.8,1835.4,1835.6,1835,1835.1,1836.2,1835.3,1837.8,1837.6,1840.1,1837.1,1835.5,1835.7,1836,1837.9,1838.8,1840.5,1845,1843.9,1848.6,1847.4,1846.4,1846.6,1843.2,1844.3,1843.7,1840.1,1838.5,1837,1838.8,1835.8,1845.3,1840.5,1840.1,1839.4,1837.9,1840.8,1838.1,1838.7,1837.2,1838.8,1840.2,1845.2,1843.6,1849.9,1853.5,1855.9,1853.6,1851.3,1853.9,1855.3,1852.4,1851.9,1851.3,1850.5,1850.5,1850.6,1851.1,1847.7,1846.6,1843.2,1842.5,1843.3,1845.2,1848.2,1845.4,1844.1,1843.9,1846.4,1845.2,1844.9,1846,1838.4,1839.3,1838.2,1839.5,1838.7,1840.4,1846.8,1847.4,1848.2,1920,1918,1912.9,1908.4,1906.7,1902.6,1900.8,1894.4,1895.7,1895.4,1897.1,1895.3,1899.1,1900.7,1903.5,1904.5,1904.5,1909.5,1909.7,1913,1914.2,1914,1915.3,1912.8,1911.4,1912.1,1912.6,1914.1,1915.2,1914,1915.7,1918.6,1924.1,1923.4,1923.7,1926.9,1932.9,1932.5,1931.8,1930.7,1934,1939.7,1939.6,1938.5,1938.5,1937.1,1939.7,1938.1,1942,1935,1929.7,1927.4,1925.8,1928,1927,1927.3,1926.2,1927.3,1927,1929.8,1932.7,1934,1932.9,1929.6,1928.6,1928.9,1931,1931.4,1931,1932,1932,1929.5,1930.2,1929.9,1930.8,1930.6,1928.8,1930,1928.7,1925,1931.3,1933,1934.7,1933.5,1932.7,1934.9,1937.2,1938.1,1936.3,1935.1,1936.9,1938.3,1937.9,1941.5,1936.8,1933.8,1931.2,1921.7,1936.1,1944.7,1945.5,1947.9,1947.8,1946.1,1949,1948.5,1953.5,1954.2,1951.3,1948.5,1948.8,1951.1,1949.7,1949.7,1949.8,1950.7,1950,1947.6,1949.6,1948.9,1949.4,1948.6,1952,1950.6,1948.8,1948.4,1947.4,1948,1948.5,1950,1950.1,1944.6,1945.8,1946.7,1948.4,1947.5,1946.2,1946.6,1946.1,1946,1945.3,1942.8,1939.4,1939,1939.9,1935.3,1931,1914.1,1916,1915.8,1912.7,1915.9,1918.7,1915.3,1915.2,1916.2,1918.9,1920.7,1920.1,1922.5,1921.7,1922,1918.2,1919.4,1919.2,1920.7,1919.2,1917,1916.3,1915.1,1915.8,1915.8,1915.5,1916,1916.6,1914.2,1916.3,1919,1920.9,1927,1928.9,1927.4,1931.2,1925.6,1925.4,1926.9,1927,1928.3,1928.6,1931.5,1931.6,1932.7,1931.1,1933.9,1931.7,1932.2,1955,1957.6,1958.8,1959.5,1958,1958,1960.4,1958.4,1958.9,1957.8,1954.5,1954.4,1955.1,1950.5,1948.2,1949.8,1948.9,1949,1945.9,1945,1947.3,1948,1947.8,1950.6,1949.7,1946.9,1943.8,1942.2,1941,1941.8,1941.5,1945.5,1949.2,1948.6,1943.3,1941.7,1943.2,1942.6,1945.2,1945.3,1942.8,1944.8,1946.3,1943.8,1946.2,1945.3,1943,1944.3,1946.3,1959,1964.6,1962.8,1962.1,1959.7,1957.2,1958.1,1960.4,1955.8,1957.2,1958.5,1958.1,1957.9,1958.8,1958.2,1957.8,1958.1,1958.5,1959.1,1961.6,1962.2,1959.8,1959.2,1958,1957.9,1957.7,1959,1957.2,1957.5,1958.8,1961,1958.2,1958.8,1958.8,1959.4,1959,1963.6,1961.3,1958.5,1958.5,1958.5,1958,1957.5,1961.1,1959.1,1961.8,1959.5,1961.9,1961,1968,1969.8,1968.5,1970.4,1969,1970.4,1970.9,1969.8,1969.1,1969.7,1968.8,1966.9,1966.7,1967.9,1967.5,1967,1968.4,1967.6,1969.4,1970.3,1970.9,1975.9,1973.7,1973.9,1975.5,1974.9,1975.1,1974.5,1975,1974.7,1974.9,1976.6,1976.4,1976.6,1980,1978.6,1982.2,1983.2,1983.4,1982,1980.5,1978,1977.3,1975.1,1973.4,1976,1981.1,1980.7,1980.5,1967,1969.4,1974.9,1978.3,1981.6,1982.5,1990,1987.2,1985,1982.5,1983.8,1977.7,1980.6,1985.2,1988.1,1989.1,1991.4,1994.3,1989.5,1988.7,1988.3,1987.5,1986.6,1988.5,1989.4,1989.9,1989.2,1991.2,1989.5,1991.3,1991.9,1989.7,1990.4,1991.5,1991.4,1993,1995.2,1993.3,1993.8,1992.2,1992.2,1992.4,1989.4,1988.8,1986.7,1984.3,1985,1986.9,1987.9,1994.9,1994,1993,1994,1989.2,1990.8,1992.7,1990.5,1989.7,1988.7,1987.5,1988.8,1989.4,1989.3,1990.2,1992,1992.1,1994.2,1999.5,1994.7,1993.3,1994.1,1994.4,1996.2,1993.9,1998.6,1993.1,1990.1,1989.4,1989.1,1988.4,1989.9,1993,1993.2,1988.6,1989.9,1988.2,1990.7,1991.2,1990.7,1993.3,1991.9,1992.2,1992.6,1991.9,1995,1994.3,1996.9,1997.9,2006.2,2008.9,2013,2015.4,2015.6,2014.5,2013.9,2013.3,2014.4,2013.8,2015.2,2017.1,2018.1,2016.5,2016.3,2019.8,2022.8,2023.8,2022.3,2022.8,2022.5,2019.2,2019.2,2019.8,2021.8,2015.9,2016.1,2017.2,2018,2018.7,2021.9,2019.6,2019.1,2019,2017.5,2018.5,2017.3,2016.7,2017.3,2017.7,2017.2,2018,2016.5,2013.7,2012.5,2012,2010.9,2009.7,1998,1994.6,2000.6,2001.6,2002.7,2000.4,1998.7,1998.6,1995.7,1995.3,1997.6,1997,1996,1996.6,1995.7,1994.9,1996,1994.2,1994.3,1994.5,1996.7,1996.4,1989.1,1990.1,1988.3,1987.2,1986.4,1986.5,1987.5,1984,1983.6,1986.1,1988,1988.9,1994.8,1994.7,1995.9,2002.7,2005.3,2008.9,2013.5,2011.4,2016.8,2017.8,2024,2025,2024.8,2032,2033.2,2040.6,2045,2047.3,2039.4,2035.8,2035.7,2037.2,2038.4,2043.5,2039.7,2036.8,2040.3,2037.6,2038.3,2037,2044.6,2043.4,2038.9,2037.4,2038.5,2028.4,2028.7,2026.8,2027.7,2026.3,2027.4,2027.9,2028.4,2029.8,2027.6,2028.5,2026.8,2030.4,2024.7,2023.2,2018.8,2007.3,2013.9,2009.2,2002.8,2006.8,2009.6,2008.1,2004,1998.6,2003.1,2010.3,2019,2020.2,2019.2,2011.2,2013.2,2013,2010.7,2006.4,2008.5,2006.6,2008.1,2013.8,2011.2,2010.3,2010.4,2015,2011.6,2011.5,2009.7,2007.9,2008.8,2009.1,2006.3,2006.8,2006.4,2008.1,2008.2,2008,2007.8,2011,2012.1,2014,2014.6,2013.8,2014.1,2008.2,2010.4,2012.3,2009.2,2008,2004,2007.4,2011.1,2008.4,2014.4,2013.6,2016.6,2012.6,2007.9,2012,2012.5,2015,2022.8,2019.4,2016.8,2017.6,2021.1,2020.8,2021.7,2020,2019.4,2021.2,2018.5,2018.2,2018.1,2018.4,2020.1,2023,2023,2022.1,2021.9,2021,2025.9,2029,2033.5,2038,2042.5,2043.6,2042,2038.9,2040.5,2039.7,2040,2031.6,2031,2030.9,2027.9,2027.9,2027.3,2032.2,2032.9,2033.8,2034,2035.1,2034,2029.3,2029.1,2031.8,2034.4,2033.1,2028,2031.7,2035.6,2036.7,2034.6,2036,2035.2,2036,2033.4,2033.8,2029.6,2031.3,2030.9,2030.8,2029.2,2029.3,2030.5,2028.6,2029.2,2029.7,2027.7,2027.9,2028.7,2030.4,2029.8,2027.6,2028.3,2029.1,2028,2028.5,2028.7,2028.3,2031.1,2031.6,2028.8,2028,2029.5,2029.5,2031.1,2028,2031,2032,2030.2,2028,2028.5,2029.6,2029.6,2028.2,2023.8,2028,2040,2050,2050,2047.2,2044,2043.5,2040.9,2039.6,2042.8,2042.3,2040.9,2036.4,2036,2034.6,2034.9,2036.5,2035.9,2032,2030.9,2028.9,2027.6,2029.4,2028.8,2026,2022.5,2018.8,2023.6,2023.8,2025.9,2024.7,2024.9,2020.9,2017.1,2017.4,2019.2,2016.2,2015.3,2019.6,2019.9,2015,2012.1,2013.6,2012.4,2015.7,2015.5,2018.6,2022.7,2020.1,2017.9,2004,2005.4,2010.3,2008.2,2009.7,2005.6,2006.1,2010,2010.8,2014.2,2012.1,2010.5,2009.7,2009.1,2007.3,2008.9,2006.6,2008.4,2007.7,2005.1,2009.8,2012.8,2012.9,2015,2012.7,2013.1,2016,2016.4,2014.5,2013.5,2014.1,2015,2014,2013.3,2013.4,2014.6,2015.7,2012.5,2014.3,2019.7,2022.5,2024.2,2029.9,2035.7,2033.9,2035.8,2035.4,2034.3,2038.8,2053.4,2047,2046.7,2047.7,2047.6,2046.5,2046.3,2047,2046.3,2041,2042.6,2044.2,2042,2040.7,2038.6,2038.4,2040.6,2039.6,2038.8,2038.6,2038,2036.6,2036.6,2038.5,2038.8,2037.6,2036.6,2037.5,2040.4,2039.1,2039,2038.5,2043.7,2044.6,2042.9,2047.4,2046.8,2047.8,2047.9,2047.6,2049.2,2051.7,2057.3,2061.5,2062.7,2060,2059.7,2061.8,2060,2070,2068.7,2066.8,2068.7,2069.3,2073.3,2068.8,2071.4,2071.5,2068.8,2068.3,2068.6,2068.9,2066.9,2063.8,2064.4,2064.8,2064.5,2067.7,2070,2074,2078.9,2077,2078.5,2077.5,2075.1,2074.8,2073.2,2075.8,2076.5,2075.9,2078,2088.6,2091.5,2088.9,2086.7,2083.6,2085.3,2083.5,2086.5,2083.9,2084.9,2085.2,2075.6,2078,2077,2080.9,2082.6,2080,2073,2070,2070.9,2070.2,2069.7,2071.8,2070.6,2070.7,2068.2,2071,2069,2070.7,2071.1,2070.6,2069.9,2071.5,2071.1,2072.5,2072.8,2072.5,2073.2,2071.7,2070.4,2071.6,2070.9,2070,2072.4,2072,2072.6,2072.8,2072.6,2072.2,2077.7,2078.3,2079.7,2079.8,2079.4,2078.5,2083.1,2083.3,2080.6,2077.9,2079.2,2076.9,2068.3,2070.7,2070.7,2070.9,2073.4,2070.5,2070.2,2070.7,2070.4,2072.7,2069.9,2069.3,2066.7,2067.3,2064.8,2062.1,2065.4,2063.5,2065.7,2066.9,2066.1,2064.5,2067.2,2066.7,2065.7,2066.6,2067.2,2068.7,2069.1,2068.2,2066,2065.4,2065.1,2067,2065.5,2066.1,2066.5,2065.9,2071.5,2070.9,2070.5,2064.7,2062.8,2057.5,2055.5,2056.2,2056.9,2057.2,2053.8,2052.9,2051.4,2048.9,2043.4,2039,2038.8,2039,2039.3,2038.7,2039.8,2036.5,2038.4,2038.8,2038.9,2040.1,2038.5,2037.7,2038,2039,2037.6,2037.9,2040,2039,2038,2039.5,2039.2,2038,2037.6,2038.2,2037.8,2037,2036.5,2033.7,2030.9,2028.5,2027.8,2029.2,2031.2,2029.1,2030.7,2031,2030.9,2031.2,2037.8,2039.4,2047.5,2049,2045,2047.5,2043.4,2041.4,2047.3,2046,2049,2052,2053.8,2054.3,2052.5,2048.5,2046.9,2047.7,2042.7,2041.3,2039.6,2040.9,2038.7,2037.6,2041.8,2040.5,2041.9,2043.1,2042.6,2039,2040.8,2044.3,2044.4,2040,2041,2040,2037.3,2035.7,2040.5,2039.2,2039.1,2041.7,2040.3,2039.3,2039.6,2039.3,2040.5,2033.1,2034,2033.6,2030.5,2032.4,2031.4,2027.1,2031.2,2022.7,2027.9,2031.8,2032.2,2039.9,2042,2037.3,2036.8,2038,2036.1,2035.8,2037.7,2046.9,2050.4,2050.7,2051.3,2051.1,2052.5,2050,2047.9,2049.6,2050.7,2050.3,2053.5,2056.9,2056.2,2055.7,2058.1,2060.5,2062.4,2058,2057.3,2056.8,2058.4,2054.6,2055,2058.2,2062,2058.3,2055.8,2055.9,2052,2053.5,2052.9,2052.3,2056.7,2057.8,2056,2056.6,2054.5,2055.5,2060.4,2059.3,2065.1,2061,2061,2060.7,2061.3,2060.5,2062,2060,2058.3,2058.5,2055.4,2057.8,2058,2057.2,2058.4,2055.5,2056.3,2055.2,2056.2,2055.9,2057.9,2057.7,2058.3,2058.5,2057.2,2057.3,2057.7,2059.1,2058.9,2060.5,2060,2060,2047,2046.4,2046.6,2046.2,2047.3,2048,2048.7,2047.1,2050.2,2047.8,2046.9,2048.4,2051.4,2051,2053.4,2052.3,2050.4,2053.9,2039,2037.7,2033.4,2034.6,2036.5,2037,2035.4,2036.1,2040.9,2037.5,2036.3,2035.8,2037.7,2036.9,2036.4,2035.1,2034.4,2037.1,2036.7,2031.5,2032.5,2032,2031.9,2033.4,2033.3,2033,2032.5,2035.1,2036,2035.4,2036.4,2034.7,2035.5,2035.3,2036.2,2034,2036.6,2039,2037.4,2037.9,2043.7,2042.6,2043.7,2047.8,2045.5,2046.4,2049.8,2053.6,2047.5,2050,2045.9,2045.6,2044,2042.8,2042.4,2036.9,2037.1,2038.2,2039.7,2038.6,2041.5,2038,2038,2039.9,2038.8,2037,2037.9,2038.5,2036.5,2037,2035.1,2035.5,2035.5,2039.4,2037.3,2037.5,2037.6,2038.1,2037.8,2029,2030.3,2028,2030.1,2031,2031.5,2029,2029.5,2034.1,2038.2,2035.8,2041.7,2039,2039.3,2040.4,2039.3,2029.8,2031.3,2030.1,2024.5,2021.8,2023,2026,2025.4,2030.5,2030.2,2030.7,2030,2029.5,2027.3,2027,2026.5,2025.8,2026.8,2028.1,2027.2,2029.7,2028.6,2028.1,2027.2,2023.8,2022.6,2023.6,2023.3,2020.1,2016.8,2017,2014.5,2013.4,2006,2004,2011.9,2013,2016.6,2016.7,2019,2020.7,2021.6,2020.3,2019.5,2020.7,2026.9,2021.7,2021.2,2023.6,2025.8,2029.8,2040,2050.9,2045.2,2044,2045.7,2041.5,2039.2,2037.8,2040,2039.1,2036,2037.5,2037.6,2040.3,2041.4,2039.4,2038.6,2038,2041.3,2041.6,2040.9,2039.6,2037.4,2038.1,2033.7,2033.9,2036.6,2034.6,2036,2037.7,2039.7,2039.8,2035.5,2034.3,2033.7,2035,2035.9,2034.1,2036.6,2037.4,2038.9,2037.3,2038.5,2038.7,2037.6,2038.7,2038.6,2032.9,2030.9,2031.5,2016,2011.6,2011.4,2011.8,2006.9,2006.8,2007.2,2002.8,2003.7,2004.6,2004.4,2004.7,2004.6,2006.6,2005.4,2002.9,2001.7,2003.2,2007.2,2005.2,2004.1,2003.1,2002.3,2000.8,1998,1996.1,1997.5,1997.2,1998.3,2006.6,2008.5,2013.7,2014,2013.8,2017,2011,2009,2010.5,2012.3,2012,2014.7,2013.1,2015.2,2010.1,2010.7,2007.7,2010.7,2010.7,2010,2022,2017.4,2016.3,2020,2022.7,2019,2019.8,2022,2022.7,2023.2,2021,2021.8,2020.5,2019.9,2020.7,2027.7,2024.9,2024.5,2025.6,2025.6,2025.3,2025.1,2021.7,2020.9,2020.9,2020.3,2021,2020.5,2018.1,2018.8,2019.3,2022,2024.5,2026.8,2026.4,2028.3,2027.6,2029.5,2028.9,2027.7,2027.5,2025.2,2023.9,2025.3,2022.9,2022.1,2019.9,2019.8,2022.4,2018.6,2019.9,2020.9,2021.7,2021.9,2023.6,2023.5,2024,2022.2,2024,2026,2024.9,2025.9,2026.5,2027.3,2027.2,2026.7,2024.9,2023.9,2024.3,2022.6,2022.9,2024.2,2023.8,2024,2025.2,2023,2023,2022.2,2023,2022.7,2021.6,2021.8,2020.7,2022.2,2021.7,2024.5,2024.2,2024.2,2025.7,2021.3,2020.7,2022,2025.3,2027.6,2025.1,2026.1,2030.1,2033,2032.9,2033,2033.9,2034.8,2032,2030.5,2029.1,2030,2029.9,2028.9,2028.8,2024.3,2022.6,2022.7,2019.6,2022.2,2022.9,2024.5,2024,2022.7,2023.4,2023,2024,2023.7,2021.8,2022.6,2021.6,2021.8,2020.7,2019,2016.6,2019.5,2021.5,2021.8,2019.6,2025,2024.3,2020.5,2018,2020,2025.8,2023.2,2024.3,2024.4,2026,2024.2,2020.8,2019.2,2024.8,2020,2022.6,2022.9,2023.1,2023.3,2024.5,2027.5,2027,2025,2023,2023.7,2022.7,2021.4,2022,2019.8,2020,2020.6,2021.6,2020.4,2019,2015.3,2012.1,2013.4,2012.2,2012.9,2011.3,2008.5,2008.7,2009.9,2010.1,2012,2013,2010.7,2012.7,2010.5,2011.4,2013.6,2012.9,2016.7,2014.1,2018.9,2013.9,2013.9,2017.7,2017.8,2017.8,2016.1,2012.7,1990.1,1998,1993.6,1995.3,1996.2,1996.3,1994.7,1995.3,1995,1994.5,1995,1996.8,1999.5,2001.6,2000.4,1999.2,1999.7,1999.9,2001.5,1999,1996.2,1996.3,1996.9,1999.1,2001.3,1997,1998,2001,2000.1,1999.2,2003.6,2007.7,2007.5,2005.7,2007,2005.9,2010.7,2013,2011.8,2014.6,2013.1,2011.4,2010.6,2009.8,2007,2008.7,2009.8,2012.2,2009,2005,2007.5,2003.4,2003.7,2005.3,2004,2003.7,2005.2,2004.3,2005.8,2006.2,2006.3,2004.8,2004.8,2003.2,2002.5,2002.9,2002.9,2001.5,2000.7,2001.7,2000.7,1997.2,1997,1996.7,1997.8,1996.9,1998.1,1997.6,1996.7,2000,1996.5,1997,1998.4,1997,1997.3,1996.6,1996.8,1995.6,1996.9,1997.3,1995.5,1994.5,1997.3,1996.7,1996.9,1996.6,1991,1985.4,1991,1985.3,1985.7,1987.8,1988.4,1988.1,1989.1,1991.9,1992.4,1994.6,1997,1996.7,1995,1995.8,1994.7,1994.1,1994.1,1993.8,1991.4,1991.8,1991.6,1991.5,1990.5,1990.9,1991.4,1989.5,1992.1,1992,1990.8,1990,1989.7,1986.1,1986.7,1987.2,1988.7,1989.3,1987.6,1986.7,1988.1,1988.2,1987.6,1985.9,1983.5,1982.9,1983.7,1984,1981.4,1978.5,1975.3,1972.1,1977,1975.7,1977.2,1976.2,1976.4,1975.5,1974,1973.3,1972.8,1973.4,1973.7,1973,1974.4,1974.1,1975.1,1976,1977,1975.4,1973.5,1974.3,1973.6,1973.5,1972.8,1972.5,1974.6,1974.6,1975.8,1977,1976,1975.5,1975.7,1976.9,1976,1975.9,1976.3,1983.6,1985.5,1990.6,1992.8,1992.7,1992.8,1991.7,1990.8,1993,1988.7,1986.6,1981.8,1980.1,1972.4,1969.4,1969.5,1971,1970.4,1968,1973.7,1973,1973.1,1971.5,1972.8,1972.8,1972.2,1971.3,1972,1972,1971.6,1969.1,1969.1,1969.6,1968.9,1968.6,1971.9,1971.2,1969.2,1969.5,1968.7,1971.3,1968,1971.8,1972,1972,1971.9,1978.6,1980.9,1978.9,1976.7,1976.1,1978.1,1982.9,1979.7,1977.7,1978.7,1979.7,1980.9,1977.6,1980.1,1985,1986.1,1982.4,1981.7,1982.2,1984.3,1983.6,1984.3,1983,1983.3,1984.7,1984.1,1984.3,1983.4,1984.1,1983,1983.5,1982.3,1981.6,1982.7,1984.3,1984.2,1982.3,1984.6,1983.6,1983.6,1983.3,1982.7,1984,1983,1984.4,1986.5,1985.4,1984.9,1984.2,1980.9,1981,1979.5,1979.4,1980.6,1979.7,1979.6,1978,1979,1979.4,1978.4,1976.3,1977.3,1973.9,1975.9,1980.2,1982,1967.5,1969,1968.2,1966.5,1967.6,1967.3,1963.2,1961,1960.7,1962,1963.5,1963.1,1962.1,1962,1956.5,1955.1,1954.8,1954.1,1955.6,1956.1,1956.3,1956.7,1957.7,1954.2,1955.1,1954.7,1953.7,1953.5,1951.7,1950.3,1950.1,1950.9,1952,1952.1,1950.6,1948.5,1953.7,1953.4,1952.5,1952.4,1951.8,1950.7,1949.4,1948,1943.1,1943.8,1943.7,1938.2,1937,1941,1941.1,1942,1942.5,1942.6,1941.8,1943,1943.8,1943.3,1944.2,1943.6,1942.5,1941.7,1941.2,1940,1939.3,1940,1939.3,1940.8,1941.5,1943.4,1943.5,1945,1946.4,1951.1,1950.9,1949.5,1949.7,1950.6,1949.5,1950.3,1953.1,1949.6,1950,1951.3,1953.4,1950.8,1948.1,1948.6,1948,1951,1951.6,1953.7,1954,1952.7,1950.2,1949.4,1952.4,1950.5,1944.4,1945.5,1945.6,1947,1945.6,1946.8,1946.7,1947.5,1948.7,1947,1946.7,1946.4,1945.2,1945.2,1945.5,1945.6,1946.7,1947.8,1952.9,1955.3,1955.9,1955,1957.9,1958.7,1958.4,1958.9,1958.3,1957,1957.3,1957.3,1957.7,1958.6,1959.2,1959.8,1957.7,1957.6,1957.6,1955.2,1956.6,1957.6,1958.3,1956.4,1957.8,1960.6,1956.3,1958,1960.4,1964,1961.5,1954.9,1952.8,1950.7,1947.5,1949,1949.2,1948.2,1946.4,1946.3,1946.3,1947.5,1947.5,1946.8,1948.6,1948.7,1948.4,1947.8,1947.4,1947.3,1950.9,1949.2,1951.6,1951.3,1953.1,1952.5,1951.8,1951.5,1950.3,1950.7,1951.3,1951,1950.8,1950.3,1951.3,1951.6,1952.6,1954,1953.2,1953.2,1954.1,1953,1953.2,1951.1,1952.5,1953.4,1953.5,1952.8,1953.2,1952.8,1968,1964.2,1967.3,1967.2,1965.8,1965.4,1963.9,1964.9,1965,1964.6,1965.4,1964.8,1964.3,1965.7,1966,1972.9,1972,1971.3,1970,1965,1966.2,1965.7,1965.1,1966.1,1966.9,1965.1,1965.5,1966.1,1966,1966.2,1966.5,1965.9,1966.8,1965.9,1966.6,1967.6,1967.1,1968.2,1969.1,1967.7,1964.4,1965.2,1964.3,1958.5,1958.3,1953,1950.9,1946.5,1939,1959,1963.1,1961.8,1961.5,1961.5,1962.5,1960.8,1962.7,1960.9,1958.8,1960.5,1957.9,1954.8,1956.5,1951.6,1953.2,1953.5,1952.8,1953.4,1953.7,1955.8,1956.4,1957.8,1957,1957.4,1961.2,1959.6,1957.1,1958.6,1959.7,1960.3,1959.3,1960,1966.3,1966.4,1967.5,1968.8,1967.4,1965.5,1961.6,1964.1,1962.8,1964.4,1965.3,1962.1,1961.7,1961.4,1962.8,1965.2,1968,1969.2,1968.4,1967.7,1970,1967.5,1966,1967.3,1970.7,1967.6,1968.3,1967,1967,1967.2,1964.6,1964.5,1965.1,1964.6,1964.4,1965.6,1965.7,1965.6,1965.3,1964.5,1965.3,1964.2,1964.6,1964.2,1965.2,1965,1965.3,1965.7,1966.3,1965.4,1965.2,1966.6,1966.5,1963.8,1964.4,1964.6,1965.6,1964.1,1964.6,1961.1,1961.5,1961,1961.2,1962.4,1964,1960,1957.9,1956.8,1956,1956,1958.2,1957.7,1957.8,1958.5,1959.6,1959.4,1962.2,1961.1,1960.5,1960.2,1958.8,1957.8,1957.3,1956.2,1957,1957.2,1957.1,1956.5,1956.2,1954.5,1952.3,1952.7,1953,1952,1952.5,1950.6,1951.6,1953.2,1955.5,1955,1954.6,1956.7,1958.3,1959.9,1957.4,1960.5,1959.9,1960,1963,1962.7,1964.5,1961.9,1962.4,1959.9,1966.8,1968.9,1966.2,1965.5,1965.1,1966.8,1965.5,1967.6,1968.1,1969.5,1971.2,1968.5,1969.5,1970.2,1969,1969.5,1970.5,1970.7,1970.3,1969.1,1970.5,1970.7,1970,1971.2,1971.2,1971.2,1971.4,1971.8,1971.4,1973.1,1974.2,1975,1974.3,1974.8,1976.1,1975.6,1976.1,1974.5,1973.7,1971.5,1972.2,1972,1971.7,1972.4,1972.5,1972.5,1971.3,1971.3,1971.4,1975.8,1973,1973.8,1971.9,1968.3,1966,1960.4,1963.7,1964.4,1963.8,1964.7,1964,1963.1,1964,1962.7,1962.5,1961.3,1962.1,1963.3,1963.5,1963.3,1962.3,1964.3,1964.5,1967.2,1965.8,1964.9,1964.8,1964.7,1961.9,1961,1963.1,1961.2,1962.6,1963,1963.7,1964.5,1965,1965.5,1963.5,1964.7,1963,1963.7,1964.3,1961.6,1964.3,1962.5,1958.5,1964,1966.9,1968,1968.2,1968,1966,1967.2,1968.5,1969.5,1968.2,1968.9,1967.1,1967.3,1967.5,1967,1968.1,1969.3,1969.6,1971,1973.9,1973.8,1974.6,1975.4,1975.4,1975.5,1976.4,1974.8,1976.3,1978.7,1977.9,1979.5,1979.6,1980.2,1979.9,1980.8,1982.5,1983,1983,1981.7,1980.7,1982,1981.1,1981.3,1977.3,1980.3,1981.2,1982,1983.9,1986.9,1984.8,1984.7,1985,1985.2,1984.9,1989,1988.8,1987.8,1987.9,1988.8,1989.2,1987.2,1986.1,1985.1,1983.7,1983,1983.6,1983.9,1983.5,1983,1983.5,1983.4,1983.9,1983.4,1984,1985.5,1985,1984.7,1985.9,1987.7,1990,1999.2,2004.9,2005.5,2009.2,2010.1,2009.5,2006.8,2004.9,2004.8,2004.7,2003.6,2002.7,2000.1,1999.6,1996.2,1996.6,1993.4,1991.3,1991.4,1995.1,1998.5,1998.8,1999.1,1999.9,2003.2,2002.9,2006.9,2002.9,2004.2,2006.2,2000.9,2000.4,1999.5,1998.4,1997.6,1999.7,1998.8,1999.4,2000.9,1996.5,1996.9,1997.1,1997.3,1996.9,1996.4,1997.5,1995.9,1997.1,1997.4,1998.4,2000.4,2002.7,2002.9,2005.5,2005.2,2003.2,2004.5,2002.7,2002.9,2001.9,2002,2001.1,2005.2,2004.8,2004.1,2006.8,2006.5,2009,2008.8,2010.1,2010,2009.1,2006.9,2005.2,2003.7,2004.8,2004.1,2003.9,2004.5,2006,2005.2,2005.4,2004,2004.9,2005,2005.2,2005.5,2004.7,2005.3,2005,2004.1,2004.9,2004.5,2003.5,2005.5,2005.8,2007.4,2005.2,2005.2,2006.5,2005.9,2007,2010.9,2009.7,2009,2009.7,2007.8,2007.4,2007.1,2008.5,2007.7,2007.8,2004.9,2003.6,2005.8,2008.5,2006.4,2003.8,1998.7,1999.3,1998.7,1999.7,2002.5,2000.8,2005.8,2003.5,2003.4,2001.7,2001,2001.2,1998.6,1998.5,1996.5,1997.1,1999.2,1998.5,1997.3,1994.2,1994.1,1995,1994.7,1994.6,1995.1,1993.3,1994.4,1993.6,1993.6,1992.7,1997.5,1997.3,1998,1998,2001.5,2001.6,2001.9,2000.4,2002.8,2004.7,2004.7,2004.9,2005.5,2004.2,2004.7,2006.1,2009.5,2012,2016,2013.3,2012,2011.1,2012.5,2011.2,2009.5,2010.5,2011.8,2012.3,2013,2010.9,2010.6,2010.8,2010.3,2011.6,2013,2012.2,2011.9,2011.6,2010.4,2010.5,2011.9,2011.8,2011.8,2012,2011.4,2010.5,2010.5,2011.3,2011.6,2011.5,2012.2,2010.7,2011.2,2012.2,2012.7,2012.3,2013.8,2014.2,2012.9,2011.1,2010.6,2010.3,2010.1,2009.1,2008.9,2003.3,2010,2009.8,2008.9,2008.5,2006.1,2006.9,2007.8,2009,2008.8,2007.7,2006.1,2005.1,2004.4,2004.6,2004.5,2005,2005.8,2006.8,2007.3,2009,2007.8,2007.3,2008,2007.7,2007.6,2007.6,2007.4,2006.8,2007,2007.3,2007.8,2007.9,2008.6,2009.6,2008.1,2007.3,2007.9,2007.4,2007.5,2007.2,2006.6,2006.8,2007,2006.5,2005.5,2003.6,2003.2,2000.1,1998.2,1997.6,1997.9,2001.1,1999.3,2000,2000,2003.4,2008.9,2008,2007,2007.9,2008.8,2009.8,2009.2,2008.6,2008.7,2008.8,2010.2,2011.8,2012.7,2013,2015.3,2014,2013.8,2013.2,2012.9,2013.7,2013.5,2013.7,2013.4,2013.9,2015.4,2015.9,2015.5,2015.8,2015.9,2015.9,2013.6,2013.5,2012.8,2012.1,2012.6,2013.4,2012.4,2013.3,2013.7,2014.8,2015.5,2014,2014,2016.3,2015.6,2017.3,2018.2,2018.5,2022.5,2020.7,2020,2016.8,2016.1,2015.2,2015.2,2016.5,2017,2015.4,2016.4,2015.7,2015.9,2015.7,2013.2,2013.7,2013.1,2014.8,2016.5,2018.4,2017.4,2017.3,2017.4,2016.8,2017.2,2017.4,2013.7,2013.7,2014.4,2014,2014.1,2012.6,2013.5,2013.5,2013.1,2013.6,2008.6,2007.8,2008.1,2007.3,2004.7,2008.5,2012.4,2009.8,2013.6,2013.3,2013.5,2013.4,2012.7,2011.7,2010.1,2010.6,2011.1,2013,2011.8,2007.8,2007.6,2006.2,2005.7,2007.5,2007,2007.7,2006.9,2008.8,2006.3,2005.9,2005.8,2006,2006,2006.5,2006.6,2006.6,2006.2,2005.8,2004.6,2006.9,2002,2002.3,2005.1,2006.1,2007.4,2006.7,2007.3,2011.8,2011,2011.9,2010.8,2010.5,2011.8,2010.2,2008.6,2009,2009,2012.7,2012.9,2012.5,2012.6,2011.6,2011.9,2010.5,2011.4,2011.7,2011.6,2008.8,2006.6,2004.1,2004.1,2005.1,2007,2006.6,2007.1,2005.7,2005.5,2007,2006.3,2006,2005.7,2005.6,2005.8,2006.7,2006.3,2007,2006.7,2006.8,2007.7,2005.8,2006,2005.2,2005.7,2003.7,2004.8,2004.5,2003.6,2005,2002.6,1998,1996.4,1995.1,1995.7,1982.1,1984.9,1995,1994.8,1992.2,1991.7,1991.2,1993.7,1991.8,1989.2,1988.6,1992,1991.8,1992,1991.8,1991.4,1992.1,1990.3,1992,1990.9,1990.6,1990.6,1989.7,1989.2,1988,1987,1986.1,1985.6,1986.4,1985.5,1985,1983.3,1985.4,1986.4,1990.2,1989.7,1987.9,1990.4,1990.1,1993.8,1991.3,1991.3,1991.2,1990.4,1992.3,1994.7,1991.6,1992,1994.4,1995.2,1996.8,1999,1995.5,1996.1,1994.7,1995.2,1995.4,1994.6,1995.4,1994.3,1991.9,1991.8,1991,1989.4,1984.8,1986.9,1988.7,1988.1,1990.9,1991.9,1994.2,1997.2,1996.3,1997,2003.8,2004,2004,2000.5,1999.9,2000,1999.3,1998.6,1999,1995.2,1994.4,1994.7,1996.1,1995.8,1996.6,1996.5,1998,1998.6,1999.5,1998.1,1996.5,1998.2,1995.9,1996.8,1998.4,1999.6,1999.5,1996,1993,1993.5,1993.9,1993.6,1995.8,1996.1,1997.1,1996.6,1996.3,1994.4,1992.8,1993.1,1993.2,1992.1,1990.6,1991.6,1992.9,1993.7,1993.7,1993.6,1993.8,1995.1,1995.1,1996.8,1995.3,1994.3,1994,1993.6,1994.4,1993.9,1995.5,1993.7,1994,1995.2,1995.1,1996.5,1996.4,1995.1,1995,1993.4,1994.5,1996,1994.8,1993.1,1994.1,1991.6,1994.1,1994.3,1995.6,1992.5,1993,1993,1995.6,1993.9,1992.9,1990.4,1989,1988.7,1988.8,1989.9,1988.1,1989.1,1989.1,1988.8,1989,1989.4,1988.5,1988.5,1987.1,1988,1988.5,1987.6,1986.8,1988.7,1988.2,1987,1987.6,1986.9,1986.2,1986.4,1986,1988,1986.8,1987.3,1989.2,1988.7,1987.6,1987.2,1987.2,1986.1,1981.6,1980.6,1980.9,1979.7,1978,1978.6,1976.5,1967,1966.6,1968.4,1968.9,1965.4,1966.5,1966.2,1966.2,1964.8,1962.8,1963.1,1962.6,1964.8,1963.8,1963.3,1959.4,1959.4,1958.7,1959.5,1959.1,1960,1961.5,1961.3,1961.5,1960.6,1959.6,1957.3,1956,1956.3,1953.6,1954.5,1954.9,1954.9,1955.2,1954.5,1954,1953.5,1954.2,1950.8,1946.7,1939.6,1940.4,1940,1932.6,1938.8,1939.7,1929.9,1936.2,1941.5,1938.9,1937.7,1937.9,1935.3,1936.9,1938.3,1936.8,1935.7,1932.5,1934.8,1933.2,1930.5,1928.8,1926.8,1924,1920.9,1918.5,1919.3,1922.6,1921.8,1921.4,1924.7,1925,1928.8,1926.5,1924.4,1922.7,1922.3,1924.3,1925,1927,1930.7,1934.2,1939.2,1939.1,1937.2,1939,1942,1942.2,1940.8,1937.6,1939.7,1938.9,1941.1,1938.8,1941.4,1943.9,1942.6,1943.5,1943.5,1940.5,1939.1,1939.8,1935.4,1936.4,1933.9,1935.1,1933.9,1931.1,1925.7,1926.5,1924.8,1928.4,1926.6,1925.6,1927,1927.6,1919.9,1925.2,1927,1925.1,1928,1927.3,1927.7,1924.6,1926.1,1926.4,1927.1,1931.7,1931.3,1929.6,1929.1,1925.6,1925.2,1924.3,1924.3,1922,1926.7,1921.5,1923.3,1925.4,1923.5,1925.3,1929,1923.7,1920.4,1918.9,1919.1,1915,1914.7,1913.7,1913.1,1918.8,1918.1,1919.8,1918.8,1925.1,1925.4,1924.5,1919.7,1922.7,1920.7,1918.7,1920.2,1916.6,1915.8,1916.3,1916,1914.9,1913.9,1913.7,1908.6,1910.7,1909.1,1908,1904.4,1909.7,1911.1,1910,1911.4,1910.3,1909,1906.6,1906.7,1909,1910.9,1914.6,1916.2,1924.9,1926.1,1929.8,1927.1,1928.2,1929.4,1937.8,1936,1936.3,1926.8,1933.1,1933.2,1930,1932.1,1932.1,1928,1928.5,1927.8,1931,1928.6,1927.9,1928.2,1927.7,1927,1930.1,1928.6,1931.1,1932.2,1929.5,1929.2,1930.2,1930.8,1929.3,1929.8,1930.2,1931.3,1931.4,1931.9,1933.7,1933.9,1929.2,1927.8,1930,1929.8,1931,1930.4,1931.5,1930.1,1933,1929.7,1931.3,1929.8,1930.9,1931,1928.6,1929.9,1930.7,1930,1923.9,1925,1927.2,1927.3,1926,1923.1,1921.8,1923.5,1922.7,1923.7,1922.8,1923.5,1922.8,1921.5,1915.3,1913.5,1913.6,1914.6,1915.1,1914.9,1914.8,1912,1911.6,1913.5,1910.5,1908.3,1909.8,1906.5,1906.6,1905.3,1906.1,1906.6,1909,1905.1,1904,1901.4,1896,1896.9,1896.2,1897.4,1902.2,1907.5,1903.1,1900.2,1895.7,1888.8,1881.1,1882.1,1893,1891.7,1887.7,1885.7,1887.3,1891.7,1888.4,1894,1897.7,1898.5,1898.8,1899,1896.9,1897,1895.6,1907,1904,1898.7,1898.1,1896.2,1896,1894.2,1892.2,1891.1,1894.4,1891,1894,1891.4,1894.5,1891.5,1892.4,1893.7,1893.1,1895.8,1896.2,1894,1893,1892.6,1893.1,1892.1,1893.6,1889,1885.8,1889.2,1885.5,1884.4,1885.6,1885.6,1882.8,1884.5,1889,1889.1,1888.3,1889.3,1892.8,1891.9,1893.5,1897,1892.6,1887.2,1887.1,1883,1882.1,1874.3,1874.2,1873.4,1874.9,1873.2,1871.9,1870.2,1873.3,1873.7,1871.5,1871.8,1871.5,1870.2,1871.9,1869.3,1862.6,1865,1863.5,1853.1,1854.3,1852.1,1848.2,1850,1851.8,1859.5,1857.5,1855,1856.9,1851.3,1855,1857.9,1847.9,1848,1840,1843,1837.6,1835.5,1838.6,1839,1839.6,1843,1842,1839.5,1834.6,1837,1835.6,1832.7,1828.6,1828.9,1838.4,1837.6,1837.5,1835.6,1838.9,1837.7,1835.2,1833.6,1834,1832.4,1829.4,1829,1824.9,1823.5,1822.1,1823.1,1822.4,1823.3,1835,1838.3,1842.8,1842.6,1844,1846.5,1851.9,1856.1,1850.2,1849.5,1848,1853.4,1855.5,1856.1,1856.7,1852.6,1846.4,1842.7,1834.3,1836.9,1833.8,1832.5,1830.5,1828.1,1825.6,1827.5,1829.6,1827.1,1827,1822.6,1824.1,1828.9,1829.8,1827.3,1825.2,1824.8,1825.3,1828.8,1834.6,1833.8,1836.5,1833.5,1833.7,1834.8,1836.4,1836.7,1835.5,1834.4,1837,1835.5,1832,1831.8,1830.9,1832.9,1829.5,1828,1827.7,1832.1,1831.7,1830.6,1831.9,1835,1832.6,1835,1836.7,1835.8,1835,1840,1841.5,1842.3,1845,1844.9,1848,1853.9,1853.9,1854.3,1857.2,1852.2,1852.2,1850,1848.3,1847.2,1847,1847.7,1848.1,1845.1,1844.3,1842.2,1842,1839.6,1836.7,1836.2,1836.8,1838.3,1838.4,1837.5,1837,1839.1,1842.8,1843.8,1842,1837.9,1833.1,1833.6,1832.2,1832.7,1833.3,1836,1833.5,1835.5,1838,1835.6,1833.1,1827.9,1827.3,1811.1,1807.8,1803.7,1801.7,1801,1804.5,1811.7,1811.1,1814.4,1816.8,1812.9,1812.3,1813.1,1808.8,1807.6,1808,1810.7,1809.9,1814.8,1812,1813.2,1811.2,1811.3,1819.3,1817.7,1823.4,1821.7,1823,1823.1,1818.4,1819.3,1823.5,1824.4,1828.7,1829.1,1832,1826.4,1827.4,1826.8,1825.3,1828.7,1833.8,1826.7,1831.4,1828.7,1827.3,1828.6,1823.5,1822.7,1824,1822,1823.1,1822.9,1822.8,1819.8,1823,1824.3,1823.3,1823,1824.7,1822.9,1823,1823.7,1821.2,1822.6,1823.1,1824.2,1823.9,1825.3,1824,1822.6,1822.8,1823.5,1821.2,1821.6,1819.8,1816.3,1817.7,1816.1,1819.2,1825.1,1835,1842,1839,1838.2,1837.8,1838.5,1838.7,1839.5,1840.4,1837.4,1846.9,1846.8,1848.7,1846.4,1847.1,1848.4,1848.4,1851,1846.5,1850.3,1850.4,1848.7,1851.3,1848.9,1849.5,1851.4,1853.2,1853.8,1857.6,1857.7,1855.9,1855.9,1858.5,1855.8,1853.6,1854.3,1855.3,1861.3,1861.6,1863.7,1865.6,1862.6,1864.5,1867.1,1866,1869.7,1869.3,1872.4,1875.3,1878.8,1881.2,1883,1879.5,1880.2,1879.7,1881.1,1880.4,1880.3,1881.3,1884,1889.5,1887,1889.6,1889.8,1894.5,1891.4,1884.8,1893,1893.9,1892.5,1891.4,1887.4,1884.4,1883.8,1881.9,1885.6,1884.2,1885.1,1883.1,1883.5,1884.6,1887.8,1888.3,1884.4,1884.8,1885.2,1885.5,1885.6,1884.9,1882.8,1883.8,1883.5,1884,1884.8,1884.8,1885.5,1884.1,1884.5,1881.8,1882.9,1878.7,1879.7,1877.5,1878.7,1876.3,1874.5,1875.8,1875.4,1876.3,1873.4,1867.7,1870.1,1869.7,1871,1869.9,1875,1883,1888.4,1886.9,1890,1891.1,1890.4,1886.6,1885.6,1890.8,1894,1900.5,1903.9,1899.7,1901.5,1898.5,1897,1896.8,1899.4,1900.9,1899.1,1901.3,1901.3,1902.1,1899.3,1899,1901.6,1901.3,1903.1,1903.5,1904.8,1904.7,1907.9,1912.6,1911.4,1916.3,1915,1920.5,1919.1,1919.3,1919.3,1920,1922.6,1924,1922.4,1920.4,1918.9,1922,1919.7,1914,1918,1920.5,1920.5,1917.7,1916.9,1918.1,1924,1919.5,1915.4,1914,1914.8,1914.4,1916.6,1916.4,1915.9,1918.8,1920.3,1923.8,1924.1,1921,1922.7,1921.9,1920.2,1918,1915.4,1917.6,1918,1917.6,1918.4,1919.9,1917.6,1918,1920,1918.5,1920.4,1922.1,1923.6,1919.9,1920.7,1921.3,1922.7,1922.2,1922,1922.9,1923.8,1918.1,1921,1922.3,1925,1934,1937,1936.7,1936.8,1936.7,1933.5,1934.8,1931.3,1926.9,1922,1920.1,1922.6,1924.8,1924.1,1927.3,1929.5,1928.8,1927.4,1930,1928.7,1928.6,1928,1928.3,1928.1,1928.8,1929.1,1930.3,1928.6,1926.7,1928.6,1929.1,1928.6,1927.3,1926.2,1924,1920.5,1921.1,1923.5,1920.3,1919.1,1918.5,1918.5,1918.3,1912.5,1912.3,1912.9,1908.6,1911,1913.8,1913.8,1916.1,1915.2,1915.5,1916.1,1915.7,1908.5,1907.2,1907.5,1908,1905.6,1907.2,1911.4,1914.5,1914.4,1916.7,1920.4,1918.5,1915.9,1917.8,1916.2,1912.4,1909.8,1911.2,1909.4,1908.6,1907.4,1909.1,1909.6,1909.2,1908.4,1908.4,1912.5,1912.8,1912.7,1907.7,1904.4,1905.1,1904.9,1906.6,1906.2,1905.1,1907.2,1904.1,1900.3,1897.7,1896.9,1901.4,1896,1896.3,1896,1896.2,1896.6,1894.6,1892.4,1891,1892.2,1892.8,1891.8,1888.8,1891.5,1892.2,1893.4,1895.7,1902.3,1907.1,1908.3,1911.1,1909.9,1908.8,1909.3,1908.9,1910.5,1906.3,1904.6,1903.9,1904,1904.9,1905.5,1905,1909,1906.6,1905.5,1911.4,1910.9,1912,1910.2,1910,1906.2,1908.3,1906.8,1907.7,1908.7,1908.6,1907,1906.6,1896.5,1890.1,1897.6,1899.9,1898.1,1900.4,1896.8,1892.5,1892.3,1894.5,1894,1900.6,1904.3,1913.1,1911,1915.9,1914.3,1915,1915.4,1914.8,1912.2,1913.2,1917.5,1917.5,1915.4,1917.4,1918.8,1923.3,1927,1926.4,1927.6,1926.7,1929.2,1929.2,1926.8,1928.7,1927.6,1927.4,1929.1,1929,1928.5,1931.7,1931.8,1935.1,1933.6,1931.2,1929.7,1931,1931,1929.3,1928.6,1932,1933.2,1932.1,1931.9,1940.4,1936.6,1927.1,1928.1,1925.9,1928.8,1928.3,1929.7,1926.8,1933.8,1931.8,1932.3,1929,1928.8,1928.9,1934.1,1931.3,1930.5,1932,1932,1931.4,1928.7,1929.7,1927.3,1928.1,1929.1,1930,1927.1,1928.9,1929.1,1928,1931.5,1936.4,1934.8,1930.4,1924.7,1923.1,1921.7,1921.5,1922.4,1922.5,1923.6,1920.6,1921.8,1924,1922,1923.6,1925.2,1925.2,1923,1923.8,1924.8,1922.6,1924.4,1931.7,1941.3,1941.9,1947.9,1947.2,1943.3,1943.8,1943.2,1938.5,1939.7,1943.1,1941.8,1939.8,1939.8,1940.4,1942.7,1942.9,1942.6,1943.9,1945.1,1946.7,1945.9,1940.4,1942.8,1941.7,1944.6,1944,1942.2,1942.1,1941.6,1937.4,1937.2,1938.7,1938.5,1937.3,1935.2,1933.2,1934.9,1937,1940,1944,1945.5,1945.3,1943.4,1945,1946.7,1939,1937.4,1937.4,1938.3,1939.7,1937.1,1936.8,1939.2,1939,1937.9,1938.5,1940.1,1938.8,1940.2,1941,1940,1939,1940.4,1939.7,1939.8,1940.5,1941.9,1941.8,1942.4,1944.9,1941.6,1941.4,1939.2,1937.9,1935,1935.2,1934.5,1927.8,1924.8,1924,1925.3,1923.8,1919,1913.7,1914.5,1912.9,1912.4,1901.1,1900.5,1905,1905.1,1902.8,1902.8,1903.4,1904,1904.5,1904,1903.3,1895.9,1894.9,1909.9,1908.1,1903.2,1905,1905.4,1908,1905,1905.4,1906.9,1906.1,1907.9,1905.7,1902.6,1897.5,1897.6,1895.9,1889.5,1891,1892.4,1893,1894.6,1893.8,1892.2,1892.9,1890.1,1891.9,1889.8,1886,1883,1883.4,1887,1879.2,1877.3,1877,1872.8,1873.1,1878.8,1881.8,1880.2,1879.8,1881.6,1884,1882.7,1878.9,1878.5,1883.6,1881.5,1883.2,1882.7,1882.5,1882.2,1882.9,1881.2,1875.8,1877.3,1875.8,1877.4,1875.3,1875.1,1874.7,1875.9,1874.1,1877,1877.8,1877.4,1876.2,1875.6,1876.7,1877.8,1878.8,1877.6,1876.1,1878.7,1885.6,1883.7,1884.8,1882.7,1883.1,1884.1,1884.3,1884.1,1884.9,1875,1873.9,1877.6,1880,1879,1881.9,1880.6,1880.5,1881,1880.7,1879.8,1880.3,1882.5,1886.5,1889.7,1889.4,1890.9,1894.5,1893.6,1894.3,1894.5,1894.4,1889.3,1888.6,1889.4,1883.2,1884.7,1885.2,1884.1,1884.2,1884,1883.7,1883.1,1879.8,1880.7,1874.6,1874.4,1874.5,1875.1,1876.6,1876.2,1875.5,1875.2,1873.6,1870.6,1871.1,1868,1867,1867.2,1869.7,1871.2,1869.7,1874,1878,1879.6,1879.4,1877.1,1878.8,1877,1873,1874.3,1871.6,1873.8,1874.5,1874.8,1874.5,1875.6,1876.2,1878.8,1877.5,1877.3,1870,1871.2,1871.8,1870.5,1870.4,1871,1870.2,1868.7,1868.2,1868.8,1872.3,1871.7,1876,1873.7,1872.8,1874,1875.9,1876.1,1872,1872.7,1870.9,1872.5,1872,1871.1,1870.5,1872.6,1874.3,1874.2,1876,1876.4,1880.9,1888,1889.7,1888.8,1891.1,1890.3,1889,1894.9,1897.6,1896.7,1896.3,1893.8,1896.1,1892.6,1893,1893.3,1891.9,1890.3,1890.4,1890.8,1890.5,1893.8,1891.3,1891.2,1891.2,1892.9,1893.4,1893.2,1891.8,1892.2,1890.7,1891,1889.8,1891.6,1891.9,1891.9,1890.6,1891.8,1892.9,1892.6,1893.5,1894.5,1896.1,1901.4,1903.3,1900.8,1898.3,1893.6,1891.8,1891.1,1884.5,1884.8,1884.1,1879.2,1879.2,1881.2,1873.2,1874.8,1874.5,1876.1,1876.8,1875.8,1875.5,1877.3,1877.9,1875.7,1877.4,1877.8,1877.2,1877,1879.2,1879.6,1880.9,1881.7,1883.6,1883.5,1884.8,1887.4,1887.3,1889.9,1894,1903.5,1912.9,1909.5,1908.6,1916.6,1918.4,1918.6,1916.3,1920.5,1921.8,1923,1922.4,1921.5,1917.6,1920.5,1926.6,1929.1,1934.2,1944.9,1946,1946.4,1950.1,1947.5,1941.9,1938.9,1935.3,1938.6,1942.2,1938.5,1940.8,1942.5,1942.2,1946.4,1947.7,1947.8,1948.1,1948,1947.3,1945.4,1940.4,1940,1940.7,1937,1938.5,1942,1942.6,1945,1942,1941.2,1944,1945.1,1941.8,1942.4,1941.9,1942.4,1941.6,1940.5,1942.1,1941.9,1939.7,1938.2,1943.1,1946,1944.1,1942.6,1942.1,1943,1944.1,1948.8,1948.1,1947.9,1947.4,1950.8,1953.3,1951.8,1957.7,1957,1954.4,1950.3,1950.1,1951.5,1951.9,1952.5,1951.3,1954.2,1952.5,1955,1954.4,1954.5,1952.4,1953,1955,1954,1953.2,1953.3,1953.4,1952.4,1954.8,1952.9,1950.8,1944.7,1941.5,1941.5,1942.5,1943.6,1944.3,1942.2,1943.4,1943.3,1931.5,1936.6,1942.2,1944.1,1940.8,1942.9,1939.9,1942.6,1941.8,1941.4,1940.1,1944.9,1943.2,1940.5,1943.1,1948.4,1947.9,1948.3,1946,1945.1,1943.7,1943,1942.4,1942.1,1938.8,1937.9,1943.4,1937.4,1938.7,1937.1,1939.6,1936.5,1936.7,1938,1941.5,1941.4,1939.6,1941.8,1939.5,1941,1942.5,1946,1946.5,1945.6,1947.3,1952.1,1957.2,1963.5,1962.5,1964.5,1960.2,1961.7,1961.2,1969.1,1970,1976.5,1974,1975.2,1974.5,1973.7,1981.2,1977.3,1975.2,1979.3,1976.6,1975.1,1973.5,1972.2,1974.3,1975.1,1972,1971.6,1972.4,1972,1968,1966.8,1969,1971.7,1970.4,1972.4,1973.2,1971.6,1971,1972,1971.6,1973.6,1972.8,1974,1968.6,1970,1969,1967.1,1969.9,1972.7,1972.1,1973.1,1972.1,1971.6,1971.5,1973.1,1974.8,1972.1,1975.9,1976.7,1980.8,1977.9,1975.8,1979,1976.4,1975.3,1976.2,1975,1976.7,1972.6,1973.7,1972.6,1973.9,1974.4,1975.1,1978.3,1975.6,1974.8,1976.3,1975.4,1977.2,1976.8,1977.9,1978.3,1978.4,1980.3,1979,1977.9,1977.6,1978,1976.5,1975.7,1976.8,1976,1978.2,1980.1,1989,1991.8,1991.7,1990.9,1991.2,1991.9,1993,1992.1,1991,1990.4,1992.2,1981.7,1985.7,1981.5,1976.3,1974.6,1972.1,1969.8,1968.8,1969.8,1969.1,1967.2,1964,1958.7,1959.4,1960.5,1957.9,1957.1,1955,1950,1952.4,1954.2,1954.1,1954.7,1955.1,1958.7,1959.3,1958.9,1957.7,1961.2,1956.7,1957.5,1959.4,1959.2,1957.7,1960.3,1963.8,1962.8,1959.9,1953.2,1953.4,1954.4,1951.1,1954.3,1956.9,1960.7,1962.7,1961.6,1957.5,1956.9,1956.5,1959.4,1955.5,1962,1962.2,1962.1,1963.1,1969.1,1969.9,1976.7,1979.3,1978.4,1977.4,1977.2,1974.3,1974.9,1974.2,1973.9,1976.9,1976.8,1977.1,1975.4,1975.4,1975.3,1975.1,1975.2,1977,1978,1977.2,1976.1,1976.7,1977.4,1978.8,1979,1983,1982,1979.6,1975,1975.3,1971,1972.1,1973.9,1975.5,1978,1979,1979.3,1975.3,1977.1,1979.6,1988.9,1990.1,1985.6,1985,1986,1987.3,1989.3,1990.5,1989.5,1986,1987.1,1989.5,1989.5,1988.4,1987.7,1989.1,1989.8,1991.2,1990.6,1990,1990,1988.5,1987.6,1986.1,1986.6,1988.1,1987.2,1982.9,1983.5,1984.4,1983.6,1985,1982.5,1981,1981,1985.2,1985.8,1986.3,1987,1986.2,1988.2,1987.6,1985.7,1984.5,1980,1972,1970,1970.9,1967.2,1966.4,1969.9,1964,1965,1965.8,1964.9,1967,1966.5,1963.2,1961.2,1960,1963.7,1965.4,1963.6,1963.4,1962.4,1960.9,1964.2,1961.1,1963.4,1963.9,1963.2,1964.9,1964.4,1965.5,1966.9,1965.8,1963.1,1963.4,1963.6,1962.7,1964.5,1963.8,1963.9,1962.5,1964.1,1963.9,1962.4,1965.4,1964,1965.9,1966.2,1966,1963.8,1962.3,1964,1962.9,1963.4,1962.3,1958.9,1962.6,1961,1961.9,1963,1965,1966.2,1964.4,1964.8,1964.5,1966.9,1973.3,1975.1,1977,1975,1975.5,1976.5,1977.2,1978.7,1978.1,1976.2,1976.6,1975.3,1975.5,1974.1,1974.2,1974.2,1974.8,1977,1977,1972.6,1970.2,1972.5,1972,1972.9,1972.2,1972.4,1970.8,1972.4,1971.3,1972.7,1972.6,1971.6,1971.4,1971.2,1970.6,1970.4,1961.5,1962,1962.8,1962.9,1966,1962,1963,1962.6,1961.9,1961.7,1962.2,1964.5,1963.4,1965.1,1965.5,1961.9,1962.7,1963.2,1965.1,1963.8,1963.7,1964,1962.7,1962.7,1963.8,1961.5,1960.2,1960.2,1959.3,1959.2,1959,1962.3,1963.1,1963.8,1963.7,1975.5,1977.3,1972.4,1972.2,1972.6,1971.3,1973.5,1974.8,1975,1974.5,1977.5,1974.2,1977.7,1982.3,1982.5,1982.4,1983.2,1980.7,1975.5,1964.8,1960.9,1961.5,1959.8,1960.8,1961.1,1959,1961.3,1961.5,1960.2,1959,1953.4,1952.1,1951,1948.5,1949.1,1949,1950,1951.3,1952.6,1950.6,1950.3,1949.9,1952,1951.3,1952.1,1952.2,1950.3,1950.3,1948.8,1949.5,1951.2,1953.5,1952,1954.6,1955.9,1953.7,1953.6,1952.8,1954.5,1955.9,1957,1950.7,1951.5,1945.3,1945,1947.1,1944.1,1940,1936,1937.5,1939.4,1939.7,1940,1940.6,1942.7,1941.7,1939.3,1939.3,1937.1,1938.6,1936.4,1936.8,1933.2,1932.3,1931.7,1936.3,1937.2,1934.6,1935.7,1938,1939.2,1937.6,1936.3,1937.6,1936,1938.2,1938.6,1936.5,1936.3,1938.9,1936.9,1935.3,1933.1,1936.4,1934.1,1931,1928.2,1925.3,1923.8,1924.2,1925.4,1927.4,1919.1,1917.9,1921,1924.2,1930.9,1933,1936,1936.6,1938.1,1938.6,1940.4,1939.6,1940.6,1937.8,1937.6,1938.1,1937.6,1939,1938.5,1943.3,1947,1946.7,1946,1944.7,1944.6,1945.2,1944.5,1942.9,1941.2,1939.5,1940.6,1941,1941.2,1941.2,1941.1,1941.8,1943.3,1944.1,1944.3,1945.3,1943.9,1943.3,1943.1,1944,1943.1,1948.2,1947.8,1945.8,1945.9,1948.8,1951.1,1952,1946.3,1948.1],
      "h": [1848.3,1848.1,1848.8,1849.5,1846,1846,1843.8,1843.5,1844,1846,1847,1844.4,1854.5,1858.6,1857.9,1854.8,1855,1855.2,1856.4,1858.5,1855.5,1855.1,1854.5,1850.4,1848,1847.8,1848.7,1851.8,1855.5,1852.7,1854.7,1852.9,1851.4,1853.5,1854.6,1851.4,1846.6,1845.9,1844.7,1845.6,1845.6,1844.8,1844.5,1848,1843.8,1851.8,1855,1854,1851.3,1874.3,1872.2,1874.9,1875.8,1920,1897.6,1898,1905.9,1907.4,1899.9,1899,1896.9,1898,1896.5,1897.8,1896.2,1895.9,1896.5,1898.6,1897.5,1895.1,1896.5,1897.9,1897.4,1895.5,1895.9,1894.9,1897.6,1897.3,1900.1,1899.6,1885.6,1885,1883.7,1885,1884.8,1884.5,1883.4,1884.8,1880.6,1879.5,1878.8,1883.3,1883.9,1883.3,1877,1883.5,1886.2,1877,1898,1893.7,1890.5,1893.3,1893,1904.8,1909,1909,1908.1,1906.9,1905.6,1904.6,1903.6,1906.3,1908.8,1905.4,1902.3,1898,1897.3,1896.9,1896.5,1895.8,1895.8,1896.9,1898.8,1896.1,1895,1891.7,1891.4,1883.8,1884.8,1884.8,1885.8,1885.9,1888.8,1890.5,1897,1903,1902.9,1900.4,1894.8,1894.8,1894.4,1893.5,1890,1889.8,1894,1893,1881.9,1858.9,1858.5,1856.3,1858,1864.2,1866.9,1861.7,1858.6,1857,1857.7,1861.9,1861.8,1858,1856.8,1855.7,1855.7,1856.8,1859.8,1859.8,1862,1863,1860.7,1865,1866,1864,1861.9,1857.9,1859,1860.7,1860.2,1859.4,1859.8,1861.9,1860.7,1859.7,1859,1859.9,1860.5,1856.9,1857.9,1859.8,1859.5,1863.8,1865,1869,1869,1863.9,1859.9,1858.2,1841.9,1832.5,1831.2,1831.5,1824,1823.8,1822.6,1820.9,1820.8,1822.7,1822.7,1822.8,1825.8,1823.9,1817.2,1814.8,1813.6,1815.4,1815.2,1815.7,1818.4,1816,1817.7,1813.5,1815.4,1815.5,1817,1815,1815,1815.3,1819.9,1819.8,1814.8,1814.3,1813.7,1816.5,1818.6,1817.9,1815.4,1814.5,1814.1,1813.5,1811.3,1810.3,1805.5,1807,1804.3,1799.9,1802,1784.8,1780,1779.5,1782,1781.3,1776.7,1776.7,1775.4,1769.3,1766.8,1765.9,1760.7,1758.6,1762.7,1762.4,1758.8,1762.5,1763,1766.8,1765.3,1764.7,1762.9,1761.8,1758.3,1757.7,1762.4,1764.8,1774,1776.8,1772,1772,1769.7,1768.2,1763.7,1760.4,1761.7,1764.9,1761.4,1761.2,1753.2,1754.5,1753.8,1753,1757.8,1755.5,1753.6,1746.8,1745.2,1740,1779.8,1775.5,1772.1,1770,1767.8,1769.8,1770.5,1768,1770.4,1771.9,1770.8,1766,1763.9,1763.9,1766.7,1769.9,1773.9,1772.1,1771,1770.9,1776.3,1777,1780.8,1777.5,1777.8,1776.6,1778,1774.9,1772.2,1772,1772.9,1775,1776.7,1774.9,1771.4,1769,1768.5,1768,1768.3,1765.6,1768.6,1771.1,1773.7,1773.7,1771.9,1769.8,1769,1767.8,1773.9,1811,1804.8,1805,1804.3,1804.9,1808.9,1808.5,1804.6,1803.8,1802.9,1803.5,1803,1802.6,1799,1799.6,1798.2,1803.6,1802.8,1803.7,1801.2,1801.1,1801.6,1800,1801.1,1799.6,1796.2,1796.2,1795,1795.8,1795.9,1797.7,1795.5,1798.5,1799.2,1799.4,1800.7,1800.7,1802.5,1801.6,1798.7,1798.4,1798.8,1800.9,1799.2,1804,1806.1,1807.5,1810.5,1814,1809.5,1805.9,1805.6,1804.5,1803.1,1802.3,1799.8,1798.7,1799.2,1798.8,1796.4,1795.5,1793.8,1791.8,1793.3,1797,1796.3,1796.5,1798.6,1798.8,1796,1797,1796.7,1795.5,1795,1798.2,1797.8,1793.7,1792.5,1793.5,1792.6,1786.4,1786.4,1787.4,1786.7,1789.8,1791,1788.1,1788.5,1793,1795,1793.5,1793.9,1794.5,1792.9,1793.3,1792.8,1792.5,1793,1787.8,1791.8,1790,1790.3,1792,1793.6,1792,1792.2,1794.8,1797.3,1797,1807.5,1810.1,1807,1807.2,1807.9,1806,1803.7,1806,1804.4,1804.9,1805.8,1804,1803.7,1805,1806.8,1806.7,1805.8,1804.6,1808,1810.3,1806.8,1808.7,1813,1813.9,1814.9,1815,1817,1819,1819.5,1819.9,1822,1824,1827.5,1827.1,1826.7,1830.9,1830,1821.1,1779,1777,1776.2,1784,1782.9,1781,1781.9,1784,1781.9,1783.3,1786.1,1782.9,1782,1784,1789.5,1795.2,1793.8,1804.5,1801.5,1800,1802.8,1802,1798.9,1799,1797.5,1797.5,1797.5,1793.3,1795.8,1799.6,1799.5,1802,1802.7,1806.6,1808.5,1808.5,1809.8,1817.8,1820.2,1822,1824.8,1830,1827.6,1825,1825,1824.5,1821.1,1814.7,1808.4,1825.9,1833,1831.9,1831.8,1826.9,1826.9,1826.2,1823.2,1824.4,1824.8,1827.7,1829.9,1828,1835.5,1837.9,1838.7,1836.7,1840.9,1841,1838.5,1837,1836.6,1838,1837,1832.1,1831.2,1831.4,1832.8,1834.9,1836,1839.3,1838.5,1836.6,1828.5,1826.9,1828,1824.9,1826.8,1827.2,1824.4,1825.8,1832,1829.9,1830.4,1829.4,1827,1823.7,1826.5,1823.9,1869.2,1869,1875,1875,1876,1872.6,1872.5,1871,1872.9,1873.5,1872.9,1874.5,1873.8,1872.4,1871.7,1871.7,1871.1,1870.5,1872,1872,1868,1868.7,1869,1869.6,1870,1868.5,1871.9,1871.2,1869.9,1871.2,1872.4,1871.4,1873,1872,1874,1874.2,1873.8,1874.2,1878.9,1879.9,1881.2,1879.8,1879.8,1878.7,1875.7,1876,1879.3,1877.9,1875.8,1859.9,1856.7,1855.7,1852.2,1852.5,1853.2,1848,1847.8,1847.4,1849.5,1850.8,1850.8,1850.8,1848.5,1847.7,1847.3,1848.9,1849.1,1849,1849.4,1848.9,1849.7,1849.5,1847.9,1847.7,1847,1847,1846.7,1847.3,1847.5,1846,1843.7,1844,1844.5,1844.7,1846.4,1845.6,1842.5,1843.4,1843.2,1842.8,1844.6,1845.8,1847,1845.1,1851,1849.9,1848,1853.2,1872,1868.8,1866.6,1865.5,1865.5,1866.1,1866.2,1865,1862.5,1864,1862.7,1863.9,1864.4,1863.8,1863,1864.6,1863.4,1862.5,1859.5,1858.6,1857.4,1857.2,1858.1,1858.5,1857.3,1858,1859,1859,1859,1858.7,1858.4,1856.4,1854.3,1850.9,1850.7,1848.2,1846,1842.9,1842.7,1842.7,1839.4,1840.8,1836.9,1836.6,1833.4,1835.7,1838.9,1837.8,1835.4,1842,1840.5,1836.1,1837.3,1839.4,1844.8,1843,1851.9,1853.6,1854.5,1848.5,1849,1847.9,1845,1842.2,1838.4,1835.3,1837.3,1836.8,1836.6,1836,1838.8,1836.5,1837.9,1837.9,1841.8,1840.8,1837.5,1835.8,1836.5,1839.9,1841.8,1841.3,1845.4,1845.8,1849,1849.9,1850,1849.8,1848.3,1846.7,1846.1,1844.7,1840.8,1840.8,1842,1839.7,1840.6,1845.3,1842.5,1840.8,1840.3,1843,1841,1841.4,1838.7,1839.1,1841,1845.6,1845.3,1849.9,1855,1856.3,1857.6,1854.3,1854.5,1855.8,1855.9,1852.5,1853.7,1852.5,1852,1852.8,1852.3,1851.4,1847.7,1846.9,1844.3,1845.4,1846.6,1848.4,1848.5,1846.5,1845.1,1847.6,1846.8,1845.6,1846.5,1847,1840.3,1841.8,1841.8,1841.5,1841.5,1848.2,1850.4,1855.5,1848.2,1926.5,1918.8,1913.8,1910.5,1907.3,1904.8,1900.8,1899.3,1897.7,1898.6,1898,1900.7,1901.9,1904.5,1905,1905,1911,1913.1,1915,1914.3,1914.4,1917.9,1915.6,1913.5,1914,1914.7,1914.5,1915.9,1917.5,1916.3,1919.9,1924.4,1924.2,1925,1927.9,1935,1933.5,1935,1933.9,1935,1939.9,1940,1941,1939.8,1939.2,1942,1942,1941,1942,1936,1929.8,1929,1928,1931.9,1927.5,1928,1928.3,1928.4,1930.7,1933.6,1936.9,1935.3,1933.9,1930,1929.9,1932.4,1933.2,1933.3,1933.3,1932.2,1934,1931.4,1931.8,1931.9,1932,1931,1930.3,1930,1928.8,1931.4,1933,1935,1935.7,1934.3,1935.8,1938,1938.8,1938.8,1937.5,1937.9,1939.6,1941.4,1942,1942,1937.5,1936,1932.2,1921.7,1945,1946,1949.9,1950,1949.8,1949.2,1949.9,1953.7,1954.9,1955.8,1952.3,1949.6,1951.4,1951.8,1951.2,1951.2,1951.5,1951.3,1950,1949.6,1949.6,1950.9,1950.3,1952.8,1952.5,1951.4,1949.6,1948.6,1948.4,1950,1951.2,1951.5,1951,1946.1,1947.4,1948.8,1949.7,1948.9,1947.7,1948.3,1946.7,1947.2,1946.2,1943.6,1941.9,1941,1940.5,1937.5,1931,1919.7,1917.5,1917.4,1916,1918.9,1918.8,1916,1917.5,1920,1921.9,1921.2,1922.6,1924,1922,1922.9,1920,1919.6,1921.3,1921.2,1920,1917.6,1917,1917.1,1916.5,1917.3,1916.5,1917.4,1916.9,1916.6,1918.6,1922.3,1927,1930.6,1929.9,1932,1932,1926.5,1927.7,1929.4,1928.5,1930.8,1933,1933,1936,1933.5,1935.5,1934.6,1935,1932.2,1960,1959,1960.4,1961.8,1958.7,1960.5,1960.5,1958.9,1959.2,1957.8,1955.5,1955.4,1955.2,1951.5,1950.1,1949.8,1949.7,1949.5,1946.5,1947.7,1948.5,1949,1950.7,1950.6,1949.7,1947.7,1943.8,1942.5,1942,1943.1,1945.8,1949.5,1949.7,1948.8,1946.9,1943.9,1945.8,1945.5,1947.8,1946.6,1946,1948,1947.6,1946.8,1947,1947,1946,1946,1946.3,1964.8,1964.9,1963.7,1963,1959.8,1958.5,1960.5,1960.4,1957.8,1959,1958.8,1958.3,1959.9,1959.6,1959,1959,1958.8,1960.9,1961.6,1963.5,1962.9,1960,1959.5,1958.1,1958,1959.4,1959.7,1957.9,1959.4,1961,1961.9,1959,1959.8,1960.9,1960.9,1963.8,1963.6,1961.8,1959.9,1959.5,1959.5,1958.8,1961.9,1961.8,1962.5,1962.7,1962,1962.5,1961,1971.9,1970,1970.4,1971,1970.5,1972.5,1970.9,1970.5,1970,1970.8,1969,1967.5,1968,1968,1967.5,1968.5,1968.5,1970.3,1970.3,1970.9,1977.8,1977,1974.3,1976,1976,1976.4,1976.3,1975.2,1976,1975.9,1977.5,1977.4,1977.4,1982.1,1980.8,1983.1,1983.8,1985,1983.8,1983.2,1980.9,1979.8,1977.3,1976.9,1976,1981.8,1981.8,1980.8,1980.5,1973,1976.6,1978.6,1984.9,1983.3,1990.8,1991.6,1987.8,1986.9,1985,1984.5,1982.5,1985.6,1988.5,1989.6,1994,1995.8,1995.4,1990.7,1989.7,1988.9,1990,1991.5,1990,1991,1990.6,1991.7,1991.9,1991.3,1992.1,1993.3,1990.9,1993.9,1993.6,1993.5,1995.5,1996.9,1994.1,1997.9,1992.8,1994.3,1993.5,1990.4,1989,1987.8,1987.2,1988.8,1988.5,1987.9,1997,1995,1994,1994.4,1990.8,1993.9,1993.1,1993.5,1990.6,1988.8,1988.8,1989.8,1991,1991.5,1992.8,1993.2,1994.8,1999.9,2001.8,1995.4,1994.8,1995,1997.3,1996.7,1999.5,1998.7,1993.9,1991.4,1990.4,1991.2,1991.5,1993.6,1993.3,1993.5,1990.6,1991.5,1990.8,1991.7,1991.9,1993.5,1993.6,1992.7,1993.7,1992.8,1994.9,1995.9,1997.6,1997.3,1997.9,2008.9,2013.3,2017.6,2016.5,2016.9,2015,2014.3,2014.5,2014.6,2016.3,2019.5,2021.6,2018.9,2017,2021.4,2023.4,2025,2024,2023.9,2024,2022.9,2020,2020.8,2021.9,2021.9,2017.4,2017.3,2018.2,2019.4,2021.8,2023.6,2020.7,2020.7,2019.4,2019,2018.7,2017.9,2018.6,2019.6,2019,2018.6,2018.8,2018.5,2015,2014,2013.6,2011,2009.8,1998,2001.9,2004.4,2002.8,2003.4,2000.9,2000.5,1999.7,1996.4,1998,2000.9,1997.8,1997.6,1997.9,1996.7,1997,1996.8,1995.8,1995.4,1996.7,1997.5,1996.8,1991.2,1990.2,1989,1988.7,1987.3,1987.9,1987.9,1984,1986.5,1989.7,1988.9,1994.9,1995.5,1996.9,2003,2005.6,2013,2014.7,2014.5,2016.9,2019.8,2027.9,2025.9,2025.5,2031.6,2035,2044.8,2040.6,2048.7,2047.5,2042,2038,2037.6,2039.2,2043.8,2043.7,2039.7,2040.8,2041.4,2038.7,2038.7,2046,2047.7,2044.3,2039.3,2038.8,2038.9,2031.4,2029.7,2028.2,2029.7,2029.3,2028,2030.9,2030.5,2030.5,2029,2028.6,2033.3,2030.5,2025,2023.8,2019.4,2014.8,2016.9,2011.1,2009.4,2012.5,2013.3,2016.9,2008,2005.7,2011.7,2022,2022.9,2026.9,2019.2,2015.9,2015.7,2013.8,2013.4,2008.7,2009.7,2009.4,2013.8,2016.8,2012.3,2012.7,2015,2016.8,2013.6,2011.7,2010.5,2010.7,2009.5,2010.7,2008.2,2009.5,2009.4,2009.9,2010.8,2008,2011.9,2013.5,2014.4,2015.5,2014.9,2015.7,2014.5,2011.7,2012.5,2012.4,2009.2,2008.9,2008,2011.7,2012.5,2015,2019,2017.6,2018,2014.9,2013.9,2015,2015.5,2015,2026,2019.5,2018.7,2021.5,2022.4,2022.5,2022.6,2020.9,2021.5,2021.9,2018.7,2018.7,2018.7,2020.9,2023.2,2023.9,2024.5,2024,2022,2026.9,2029.5,2035,2039.6,2042.8,2044.5,2043.6,2042.5,2041,2043.3,2041,2041,2032.4,2031.6,2031.9,2028.9,2029.9,2033.5,2034.8,2035.5,2034.9,2037.6,2036,2034,2031.9,2032.4,2037.9,2036.3,2033.3,2028,2036,2040,2038,2036.3,2037.7,2036.3,2036.7,2035.5,2033.8,2031.3,2032.5,2031.7,2031.9,2029.7,2030.7,2030.6,2030,2031.9,2030.1,2029.9,2029.2,2031,2031.5,2030.6,2029,2029.3,2029.9,2028.6,2029.5,2029.7,2031.7,2033.5,2031.9,2029.5,2030.2,2030,2031.3,2031.5,2031,2033.5,2033.2,2030.8,2030.2,2031.8,2031.5,2030.4,2029.9,2025,2028,2053.6,2050.6,2050.8,2049.7,2044.5,2043.6,2042,2043.3,2043.3,2042.5,2042.8,2037.9,2036.5,2035.6,2036.8,2036.8,2036.7,2032.8,2031.6,2029.9,2030.7,2030.2,2028.8,2027,2023.5,2024.6,2025.8,2026.5,2026.8,2025.2,2026.3,2022.9,2018.5,2020.6,2021.1,2017.5,2020.9,2024.6,2020,2017,2014.5,2015.4,2017.2,2019.6,2018.8,2025.4,2024,2020.8,2017.9,2006.9,2010.8,2011.6,2011.4,2010,2007.8,2010.3,2013.4,2015,2015,2013,2011,2010.6,2009.2,2010.7,2009,2008.8,2008.5,2008.8,2009.8,2012.7,2014,2016.5,2015.7,2013.7,2015.9,2017.7,2016.7,2015,2014.5,2015.5,2015.5,2014.8,2015,2014.5,2016.9,2016.2,2014.5,2020.8,2022.5,2024.8,2031.8,2037.5,2037.8,2036.1,2038.6,2036.2,2037.6,2038.8,2054.9,2048,2048.7,2049.9,2048.7,2048.3,2047.8,2048.5,2046.9,2043,2044.2,2044.2,2042.3,2041.5,2040.7,2040.8,2041.5,2039.6,2039.5,2039.3,2038.8,2037.5,2039,2039.2,2039.2,2038.4,2038.4,2041.9,2040.5,2040.4,2040.4,2043.9,2046.5,2045,2047.8,2048.5,2048.5,2048.5,2049,2049.8,2052.8,2057.9,2063.8,2065,2064.3,2061.3,2062.9,2066,2060,2070,2072,2069.1,2069.2,2076,2073.7,2072.7,2074.5,2073,2070.9,2069.3,2069.2,2070.4,2067.8,2065,2065.3,2066,2067.8,2070.6,2074.8,2079.6,2079.5,2078.7,2079.4,2077.5,2075.3,2075,2076.8,2076.7,2076.8,2079,2089.8,2093.3,2094.2,2089.9,2087.5,2085.5,2088.5,2088.2,2086.5,2086.5,2086.7,2085.7,2079.8,2079.2,2083,2083.8,2085.5,2080,2074.5,2071.2,2072.2,2070.8,2073.7,2075,2071.6,2070.9,2071.3,2071.8,2071.7,2072.8,2072,2072,2071.5,2072.6,2073,2073.9,2073.7,2073.3,2073.3,2072.2,2071.8,2072.7,2071,2072.6,2073.6,2072.8,2073,2072.8,2073.3,2078.7,2079,2081.4,2082,2080,2081,2083.8,2084.7,2084.5,2081.8,2079.4,2080.9,2076.9,2070.9,2071.9,2072.8,2077.3,2073.4,2071,2070.8,2071.9,2073.3,2072.9,2070.8,2072.6,2067.9,2067.4,2064.8,2065.7,2066.9,2065.7,2067.3,2067.3,2066.4,2067.9,2068.3,2066.8,2066.7,2067.8,2069.8,2069.5,2070,2069.3,2066.5,2065.9,2067.3,2067.9,2066.5,2067.4,2068.9,2071.8,2072,2073.3,2070.9,2065.8,2063.9,2059.9,2058,2057.8,2058.6,2058.6,2054,2055,2052.2,2050.5,2048.5,2039,2043.9,2039.9,2039.9,2040,2041,2038.7,2040.9,2041.1,2042.6,2040.6,2038.7,2039.3,2039.5,2039,2038.5,2040,2040.9,2039.4,2039.8,2039.7,2041,2038.2,2039.6,2038.7,2038.2,2038.9,2037.6,2033.8,2032.3,2029.6,2030.8,2031.3,2031.3,2031,2031.6,2031.7,2031.9,2038.7,2041,2047.8,2050.6,2049.9,2049.5,2048,2044,2047.8,2049.7,2046.4,2049,2054.8,2054.5,2054.4,2053,2049.5,2048.9,2048.8,2043.7,2042.5,2041.9,2041.1,2039.8,2042.8,2042.5,2042,2044.5,2043.8,2043.2,2041.8,2046.9,2046,2045.1,2041.5,2041.7,2040.1,2038.5,2040.8,2041.6,2041.3,2042.9,2043.7,2040.8,2041.4,2041,2040.7,2042.8,2034.5,2036.8,2034.8,2033.7,2033.6,2032,2031.6,2031.8,2029,2033,2035.6,2034.6,2039.9,2042,2037.7,2038.3,2038.8,2037.4,2037.8,2048,2051.7,2051.3,2051.5,2053.5,2054.5,2052.7,2050.4,2050.6,2051.6,2052.5,2053.9,2058.8,2058.2,2058.5,2058.4,2063,2063.5,2063.6,2059,2058.4,2058.5,2059.5,2055.5,2058.4,2062.9,2065.5,2058.9,2057.2,2059.5,2053.9,2055.5,2054.8,2056.9,2058.5,2058.6,2058.3,2056.9,2057.8,2061.6,2061.2,2064.5,2065.1,2063,2061.5,2062.5,2062,2064,2062.4,2062.1,2059.6,2058.8,2058.4,2058.5,2058.1,2058.8,2059.4,2057,2056.9,2056.2,2056.6,2058,2057.9,2059.4,2059.4,2058.9,2059,2058,2059.8,2059.9,2061.8,2061,2060.8,2060.3,2047.2,2047.9,2047.2,2048.8,2048.9,2049.7,2049,2050.6,2050.2,2048,2049.5,2053.2,2052.9,2055.8,2053.9,2052.9,2053.6,2053.9,2039.5,2037.9,2035.5,2038.2,2037.2,2038.4,2036.2,2041.9,2041.2,2038.8,2037.1,2038.3,2038.4,2037.2,2037.5,2035.1,2037.4,2037.4,2036.7,2032.8,2033,2033.3,2033.5,2034.9,2033.9,2033.6,2036,2036.5,2036.1,2038.8,2038.5,2036.4,2037.1,2036.4,2036.6,2038,2040,2039.4,2039.7,2043.6,2045.9,2046.6,2048,2048.8,2047.3,2050.1,2054.7,2056.6,2047.5,2050.1,2046.4,2046,2044.5,2043.7,2042.7,2038.8,2038.4,2039.8,2040.3,2042.3,2042,2038.7,2041.8,2040,2039.5,2038.3,2039.3,2039.3,2038.4,2037.8,2036,2036.1,2040.5,2040,2037.9,2037.7,2038.5,2039.2,2037.8,2030.7,2030.4,2031.6,2031.3,2032.5,2032.3,2031.9,2034.9,2039.7,2038.8,2042.1,2043.5,2040.8,2041.5,2040.8,2040.6,2033.4,2034.5,2030.1,2024.5,2023.3,2026.6,2026.2,2030.8,2032,2030.8,2031.9,2030.8,2029.8,2027.5,2027.1,2027.3,2027.6,2028.3,2028.5,2030.6,2030,2029.7,2028.4,2027.5,2025,2024.2,2023.6,2024.7,2020.4,2017.9,2018.6,2014.7,2013.7,2009.3,2012,2013.9,2018,2019,2018.9,2023,2024,2024.5,2021.7,2021.8,2028,2028.8,2023.4,2025,2025.5,2032,2032.9,2040,2051.9,2045.8,2046.8,2046.9,2042.5,2040.5,2040,2041.4,2039.5,2037.9,2037.7,2040.5,2043,2041.5,2040.3,2039.5,2041.8,2043,2042.8,2041.5,2039.9,2039,2038.7,2035,2037.7,2039.5,2037,2038.6,2039.5,2041.7,2040.4,2036.2,2037.3,2035.4,2036.9,2036.8,2036.7,2038.5,2039.5,2040.5,2039,2040.2,2039.7,2040.3,2040,2038.9,2033.2,2032.5,2031.5,2019.4,2012.7,2012.4,2012.2,2009.8,2008.5,2007.4,2004,2006,2005.8,2004.9,2005.7,2007.7,2007.5,2005.5,2004.3,2003.4,2007.4,2008.5,2005.7,2005.9,2003.9,2003.6,2002.8,1998.7,1998.4,1999.9,1999,2007.8,2008.9,2013.9,2015.9,2015.5,2018,2017.9,2012,2011,2012.3,2016.7,2015.6,2016.7,2016.5,2015.2,2012.7,2012.5,2012.8,2013.5,2015.2,2010,2023.1,2017.5,2020,2024.6,2022.9,2019.9,2022.9,2023.1,2026,2024.9,2022.2,2021.9,2020.7,2021.5,2028,2028,2025.5,2026.3,2026.8,2025.9,2026.3,2025.4,2022.5,2021.3,2021,2022.1,2021.5,2021.9,2019.5,2020.8,2023.6,2025.5,2027,2029,2030,2029.2,2029.6,2030.8,2029.9,2029.7,2028.1,2025.9,2026.4,2025.5,2024.7,2024.4,2021.7,2022.7,2022.4,2021.4,2021.2,2022.5,2023.3,2023.9,2023.8,2024.8,2024.6,2024.5,2028,2026.8,2025.9,2026.5,2027.9,2027.4,2027.5,2027.5,2024.9,2024.8,2024.3,2023.6,2025,2025.2,2024.2,2025.3,2025.3,2024.4,2023,2023.5,2023.6,2023.3,2022.7,2022.1,2022.8,2022.5,2024.7,2024.7,2025.8,2027.5,2025.9,2022.3,2023.5,2025.7,2027.5,2028.8,2027,2031.6,2034.5,2033,2035,2034.5,2035.8,2035.7,2032.3,2030.5,2030.3,2030.3,2030.2,2029.5,2028.8,2025.5,2023.3,2023.2,2022.9,2023,2025.8,2026.1,2024.4,2023.8,2024,2024,2024.9,2024,2023,2023.3,2023.1,2022,2021.3,2020,2020.8,2022,2021.9,2022.5,2025,2025,2024.7,2021.4,2020.8,2026,2027,2024.9,2024.7,2026.8,2028,2024.4,2022.2,2022.2,2024.8,2023.4,2023.3,2023.1,2023.4,2024.9,2028,2028,2027.4,2025.3,2024.1,2024.1,2022.7,2022.8,2022.3,2020.6,2021.6,2021.6,2021.6,2020.7,2019.5,2015.9,2013.7,2013.5,2013.4,2013,2011.7,2010.5,2010.8,2011.4,2010.8,2014.6,2013,2012.8,2012.8,2011.8,2014,2016.7,2016.9,2016.9,2019.8,2019.7,2015.4,2018.8,2019.3,2019.3,2018.5,2017.4,2012.9,1990.1,1998,1996,1996.4,1996.9,1996.4,1995.6,1995.7,1995.4,1995.5,1997.4,2001,2001.4,2002.5,2000.5,2000.6,2000.7,2002,2001.8,1999.4,1997.4,1997.8,1999.7,2001.5,2001.5,1999.7,2001.3,2001.5,2000.4,2004.8,2008.7,2009.5,2007.7,2008,2007.7,2011,2014.5,2013.2,2014.8,2016,2013.3,2012.1,2011.2,2012.1,2009.4,2010.6,2013.4,2012.5,2009.1,2005,2007.6,2003.8,2005.3,2005.7,2005,2007.4,2005.2,2006.8,2007.5,2007.3,2006.4,2005.5,2006.3,2004.1,2003.2,2003,2003,2001.9,2002.9,2002,2000.7,1998,1998.8,1998.5,1998,1999.6,1998.5,1997.8,2001,2001.3,1998.7,1998.3,1998.5,1998,1997.7,1997.4,1997.1,1999.2,1998.8,1997.4,1995.8,1997.5,1998,1997.8,1998.3,1996.8,1992.8,1991.8,1991,1989.9,1987.8,1988.8,1990,1990.8,1992.8,1992.5,1995,1998.6,1998,1997,1996,1996.5,1995.3,1994.9,1994.3,1993.8,1992.7,1992.7,1992.2,1991.5,1991.9,1991.5,1991.4,1992.9,1992.8,1992.8,1991.6,1990.6,1989.8,1989.8,1987.9,1989.2,1990.8,1989.5,1988,1988.9,1988.5,1990,1987.6,1986.9,1984.9,1984.4,1985.9,1985.6,1982.5,1979.6,1978.9,1972.1,1979.3,1977.8,1977.5,1977.8,1976.9,1975.6,1975.5,1975.5,1974.4,1974.5,1974.3,1974.8,1976.3,1975.7,1976,1977.3,1977.9,1975.5,1975.7,1974.7,1974.3,1974.3,1973.9,1974.8,1975.4,1976.7,1977.4,1977.5,1976.8,1976,1978.9,1977.6,1976.2,1977.1,1984.7,1985.5,1992,1994.4,1994.2,1994.3,1995.8,1991.7,1993,1993.2,1989.9,1987.6,1982.7,1980.8,1972.4,1971.5,1971,1971.2,1970.9,1973.8,1973.9,1974,1974.4,1974.5,1973.8,1973.2,1974,1972.7,1972.2,1972.6,1971.8,1969.7,1970.3,1969.7,1969.7,1972,1973.9,1971.2,1969.5,1969.7,1971.5,1971.6,1972,1972.8,1972.2,1973.5,1978.9,1980.8,1981.6,1978.9,1976.7,1978.8,1983,1983.5,1980.4,1980.6,1979.9,1983.4,1981,1983,1986.4,1987,1986.6,1982.4,1982.7,1984.5,1984.7,1984.5,1985.5,1984.9,1984.7,1985.4,1984.7,1985.4,1984.5,1985,1984.5,1983.6,1982.6,1982.9,1984.5,1984.9,1984.3,1984.9,1984.9,1983.8,1983.6,1983.6,1984.3,1984,1985,1986.8,1986.8,1985.6,1985.6,1984.3,1981.7,1981.4,1979.5,1981.3,1981,1980.6,1981.3,1979.4,1982.5,1979.9,1980.4,1978.7,1978.5,1976.4,1981.5,1981.5,1982,1969.7,1969.3,1968.2,1967.8,1969.4,1967.3,1964.7,1962.2,1962.5,1964.5,1963.7,1964.7,1963.4,1962.7,1956.7,1956.2,1955.5,1956.3,1957.3,1957.1,1956.9,1958,1959.6,1956.1,1956.8,1955.3,1954.6,1953.9,1953,1951.9,1952.9,1952.2,1952.2,1953.7,1951.5,1954.9,1954.2,1953.5,1952.7,1953.5,1953,1951.4,1951.8,1949.4,1945.4,1946.2,1945.9,1940,1937,1941.5,1942.6,1942.8,1944.9,1942.9,1943.3,1944.5,1944,1944.2,1944.9,1943.9,1942.8,1942.5,1941.4,1940.5,1940.4,1940,1940.8,1942,1943.3,1943.8,1945,1947.6,1952,1952.8,1950.9,1950.2,1951,1951,1950.3,1955.6,1953.4,1950.7,1951.3,1953.5,1953.5,1951.1,1951.2,1950.2,1951,1952,1954.9,1956.9,1954.9,1952.7,1950.9,1952.9,1952.8,1950.5,1946.7,1946.4,1947.4,1947.1,1947.2,1947.4,1947.5,1948.7,1949.2,1947.9,1947,1946.4,1945.4,1946.1,1946.6,1946.7,1948.4,1953.6,1955.4,1956.5,1956.3,1958.2,1958.9,1958.9,1960.8,1959.4,1959,1957.6,1957.6,1957.7,1959.8,1960,1960.4,1960,1958.5,1957.9,1958.2,1957,1959,1959,1959.4,1958.3,1962.4,1961.3,1958.3,1960.5,1966.7,1964.9,1961.5,1954.9,1952.8,1951,1949.1,1950.3,1949.3,1948.6,1946.8,1946.4,1947.7,1948.4,1949,1949.7,1949.4,1949.4,1948.8,1948.8,1948.1,1950.8,1951.2,1952,1952.4,1953.7,1953.2,1953.3,1952.5,1951.7,1950.9,1951.7,1951.6,1952.6,1951.3,1952.4,1952.5,1952.7,1954.3,1956,1953.9,1954.5,1955.5,1954.4,1954.2,1952.7,1955,1954.4,1955.2,1954.8,1954,1952.8,1968.5,1968,1967.9,1967.9,1966.5,1965.6,1965.7,1965.5,1965.7,1966.4,1966.2,1965,1965.7,1966,1974,1974.7,1972.6,1971.5,1970,1966.8,1967.2,1966.3,1966.8,1966.6,1967.7,1965.7,1966.9,1966.8,1966.4,1966.5,1966.8,1967.9,1966.8,1966.9,1967.6,1968.8,1968.5,1969.3,1969.4,1968,1965.8,1965.5,1965.2,1959.5,1958.5,1954.5,1950.9,1947,1939,1964.7,1963.4,1962,1963,1963.1,1963.4,1962.7,1963,1961,1960.7,1960.6,1958.2,1956.9,1956.8,1954.9,1954,1955.3,1955.3,1954,1957.8,1956.6,1957.9,1958.8,1957.9,1961.6,1962.2,1959.6,1959.2,1960,1961.5,1961.9,1960,1966.6,1966.6,1969.8,1970.4,1969.6,1968,1966.1,1965.6,1966.3,1966.5,1966.4,1965.7,1963.8,1962.6,1964.7,1964.7,1965.2,1969.6,1969.8,1968.6,1970,1972,1967.5,1967.4,1971.5,1970.9,1968.3,1968.7,1968.4,1968,1967.2,1964.9,1965.5,1965.4,1965.4,1966.3,1966.5,1966.2,1965.6,1968,1965.7,1965.6,1965.3,1965.1,1965.3,1965.9,1965.7,1966,1967.2,1966.6,1965.6,1966.5,1966.7,1967.5,1964.8,1965.2,1966,1966.6,1965.5,1965.5,1962,1962.5,1964.6,1962.6,1964.4,1964,1960.4,1958.4,1957,1956.6,1958.5,1958.3,1958.2,1958.8,1959.8,1960.4,1964,1962.5,1961.5,1960.6,1960.2,1959.3,1958.3,1958,1957.4,1957.3,1958,1957.3,1956.9,1956.2,1954.5,1954.2,1954.1,1953.3,1952.8,1953.2,1952.9,1953.5,1956.2,1955.8,1955.6,1956.6,1958.6,1961.5,1960.8,1960.5,1962,1961.4,1963.8,1965.9,1964.5,1964.9,1963.8,1964.6,1959.9,1971.2,1969.4,1966.6,1965.8,1967.2,1967.3,1967.9,1968.7,1970.5,1971.9,1971.5,1969.8,1970.4,1970.3,1970,1970.7,1971,1971.5,1971.3,1971.5,1971.2,1971.1,1972,1971.7,1971.8,1971.8,1972,1972.4,1974.5,1977.9,1975.2,1976.7,1974.9,1976.9,1977.6,1977.1,1976.3,1975,1974.4,1973,1972.5,1973.8,1972.9,1973.5,1973.3,1972.8,1971.5,1971.4,1971.4,1976,1974.7,1973.9,1972.5,1968.3,1966.4,1965,1965.1,1965.3,1965.7,1965,1964,1964.9,1964.2,1964.1,1962.8,1962.2,1963.3,1963.9,1963.6,1963.4,1964.5,1964.9,1967.5,1968,1965.9,1965.9,1965,1964.8,1962.8,1964.4,1963.4,1963,1963.2,1964.5,1966,1965.6,1965.5,1966.8,1965.5,1964.9,1964.5,1966,1964.9,1965.4,1965.5,1962.6,1965,1964,1972,1968.5,1968.2,1969.1,1967.9,1968.6,1969.7,1969.9,1969.4,1969.6,1967.8,1967.7,1967.9,1968.7,1970,1969.8,1971.8,1974.4,1974.6,1975,1976.7,1975.9,1975.9,1976.5,1976.8,1976.6,1978.9,1979.3,1979.6,1979.6,1982,1981.8,1981.4,1983,1983.9,1984,1983.8,1982.2,1982.2,1983.4,1982.1,1981.5,1980.8,1981.7,1982.5,1984.9,1987.9,1987.1,1984.8,1987.1,1985.8,1985.4,1989.9,1992,1988.8,1988.5,1990.4,1989.8,1990.1,1987.9,1986.3,1985.6,1984.6,1983.9,1983.9,1984.5,1983.9,1983.7,1984.5,1984.5,1984.6,1984.3,1985.9,1985.6,1985,1986.2,1987.7,1990.7,1999.8,2005.2,2006,2012.4,2011.7,2010.5,2010.3,2007.8,2006.9,2005.5,2004.7,2003.7,2002.8,2001.8,2000.3,1998,1996.7,1994.7,1991.8,1991.4,1998.8,2000.5,1999.5,2000,2005.7,2004,2007.7,2007.2,2004.6,2006.9,2006.3,2002,2001.6,2000,1998.9,2000.6,2000,1999.3,2001.5,2001.5,1998.5,1998.3,1998.2,1997.9,1997.5,1998.2,1998.5,1997.2,1998,1998.5,2000.5,2003.6,2004.1,2005.8,2006,2005.8,2004.6,2005.7,2004,2002.9,2002.4,2002.7,2005.9,2010,2006.8,2008.9,2008.6,2011.7,2009,2011.6,2011.2,2010.5,2010,2007.5,2005.5,2004.8,2006,2005,2004.8,2006.4,2006,2005.5,2005.5,2004.9,2007,2005.5,2006.4,2006.2,2006,2005.5,2005,2005.2,2005.3,2006,2006.3,2005.9,2007.9,2007.9,2005.9,2007,2006.5,2007.9,2010.9,2011.5,2010,2010.7,2009.8,2008.1,2008.5,2009,2009.5,2008.4,2008.3,2006,2007.5,2008.5,2008.8,2006.4,2003.8,1999.4,1999.6,2001,2002.7,2002.5,2006.8,2005.8,2004.1,2003.8,2002,2001.5,2001.3,1999.2,1998.6,1998.2,1999.8,1999.9,1998.8,1997.3,1994.8,1995.4,1996,1995.6,1995.5,1996.5,1995.2,1994.9,1994.3,1994,1998,1998.6,1998.5,1999.8,2001.9,2003.4,2002.6,2002,2003.5,2005,2005.5,2005.7,2008.6,2005.8,2005,2006.8,2009.7,2009.7,2012,2018.5,2013.8,2013,2013.4,2013,2011.7,2011.6,2012.2,2013.3,2013.3,2013.3,2011.2,2011.3,2011.2,2011.6,2013.6,2013.6,2012.7,2012.4,2012.2,2011.2,2012.2,2012,2012.7,2012.3,2012.2,2011.5,2011.4,2011.9,2011.4,2012.2,2013.5,2012.4,2012.2,2012.4,2013.2,2013,2014.5,2014.9,2014.6,2013.2,2011.7,2010.7,2011.8,2010.6,2010.1,2009.9,2009.5,2010,2011.3,2010,2008.8,2007.3,2007.8,2009.4,2009.6,2008.9,2007.8,2006.9,2005.4,2005.3,2004.8,2005.3,2006.6,2006.9,2007.9,2009.4,2009.1,2008.5,2008.4,2008.4,2009.1,2008.4,2008.5,2007.8,2007.9,2007.5,2007.8,2008.5,2009.2,2010.1,2009.9,2008.4,2008.8,2007.9,2007.6,2008,2008,2007.4,2007.8,2007.5,2006.9,2005.8,2004.8,2003.5,2000.3,1999.3,1997.6,2001.9,2001.2,2000.3,2001.6,2003.7,2009.6,2009.5,2008.9,2008,2010,2010.5,2009.8,2010,2009,2009.5,2010.3,2012.4,2013,2013.2,2015.5,2015.9,2015.3,2014,2013.8,2013.8,2014.9,2014.4,2014,2014.3,2015.4,2017.4,2016.5,2016.2,2016.8,2016.2,2016.4,2014.2,2014.1,2012.9,2013.5,2013.4,2013.8,2013.5,2013.7,2015.5,2016.5,2016.2,2015.7,2014,2017.2,2018.3,2018.7,2019.3,2023.5,2022.9,2021.3,2020,2017.1,2016.6,2016,2016.9,2017.4,2017.4,2017.3,2016.9,2016.3,2016.4,2016.4,2014.3,2014,2015,2016.5,2018.9,2018.8,2017.7,2017.5,2017.5,2017.3,2017.5,2017.4,2014.6,2014.9,2014.7,2014.6,2014.9,2014.4,2014.4,2014,2014.2,2013.7,2009.9,2009.1,2008.8,2007.7,2008.9,2013.8,2013.8,2009.8,2015.8,2013.8,2013.6,2013.5,2013.2,2012.4,2011.7,2011.3,2013.2,2013.3,2011.8,2008.7,2008.7,2007,2008,2007.7,2007.8,2007.9,2008.5,2009,2006.9,2006.4,2006.2,2006.5,2007.8,2006.9,2007.4,2007.3,2006.5,2005.9,2007,2006.9,2003,2006.1,2006.8,2007,2007.7,2007.6,2013,2012.9,2012,2012.9,2011.9,2012.9,2012,2011.5,2010.9,2010.9,2009,2014.8,2013.3,2013.8,2014.4,2013.8,2012,2011.5,2012,2012.4,2012,2009,2007.3,2005.3,2005.5,2007.5,2007.3,2008,2007.3,2005.9,2007.4,2007.5,2007.2,2006.2,2005.9,2007.2,2007,2006.8,2007.3,2007.4,2007.3,2008.8,2007.7,2006.1,2007,2006.9,2006.3,2005.3,2005.5,2005,2005.4,2006.5,2003,2000.6,1997.7,1997.3,1996.8,1986.8,1987.8,1995,1994.8,1992.4,1992.9,1993.8,1994.5,1992.3,1989.3,1992.5,1992.8,1993.8,1993.5,1992.5,1992.5,1992.4,1992.4,1992.2,1991.5,1990.9,1991.4,1990.7,1989.8,1988.4,1988.2,1986.5,1987.8,1986.9,1985.9,1985,1986.6,1986.3,1992,1990.4,1989.8,1991.5,1991,1993.6,1994,1992.6,1992.3,1993.6,1992.8,1995.7,1995.3,1993.5,1994.9,1997,1999.4,1998.7,1999,1996.9,1996.1,1995.4,1996.1,1996.3,1995.9,1996.2,1994.3,1992.5,1992.1,1991,1989.4,1987.4,1988.8,1989.1,1992,1992,1994.8,1999,1997.5,1997.6,2004.7,2004.2,2004.1,2004.1,2000.9,2001,2000.4,1999.3,1999,1999.4,1995.6,1995.3,1997.4,1996.8,1997.3,1998.8,1998.8,2000.4,1999.6,2000,1998.9,1998.5,2001.6,1997.5,1999.8,2000,2000.7,1999.5,1996.4,1993.7,1994.5,1994.4,1996,1998,1998.8,1997.1,1996.9,1996.5,1994.4,1993.7,1993.3,1993.8,1992.2,1992.4,1993.6,1994.1,1994,1994.4,1993.9,1995.5,1996,1996.5,1997.3,1995.7,1994.6,1994.3,1995.2,1994.5,1997.6,1995.9,1994,1996.3,1996.3,1997,1997.4,1996.7,1995.4,1995.3,1994.8,1996.5,1996.9,1995.2,1994.4,1995.8,1994.5,1995.5,1994.3,1995.6,1993.4,1993.6,1996,1996,1994.2,1993.5,1991.1,1989,1989.6,1990.6,1990,1989.2,1990,1990.4,1989.5,1989.5,1989.7,1989.5,1988.9,1988.8,1988.7,1988.5,1988.7,1988.8,1989.3,1988.4,1988.4,1988,1987.5,1988.1,1987,1988.3,1988,1987.3,1989.3,1991,1989.3,1987.9,1987.5,1987.8,1986.1,1982,1981.3,1981.7,1982.8,1978.8,1980.5,1976.5,1971.9,1968.5,1969.7,1969.2,1966.9,1967.9,1966.6,1966.7,1964.9,1965,1964.2,1964.9,1964.9,1964.3,1963.4,1960.5,1959.7,1959.7,1960,1960.1,1961.9,1961.8,1961.5,1961.5,1961,1959.8,1957.7,1957,1956.5,1955.9,1956.1,1956.1,1955.6,1955.5,1955.8,1955.1,1954.6,1954.5,1951.9,1946.8,1941.6,1941.9,1940.1,1939.8,1944.6,1940,1938.7,1937.5,1941.5,1939.3,1938.3,1938.7,1937.3,1938.9,1939.7,1937.4,1936,1935.2,1936.4,1933.6,1931.4,1930,1927.7,1925,1920.9,1921.5,1923.4,1924.9,1922.5,1925.1,1928,1929.1,1928.9,1926.8,1926,1924,1925.3,1926,1926.6,1932,1935,1939.9,1940.9,1939.8,1938.9,1944.8,1944.9,1943.2,1941.6,1942.5,1943.6,1944.4,1942.7,1942.3,1946,1946.5,1945.6,1943.5,1945.7,1940.5,1940.4,1939.9,1937.2,1936.9,1935.8,1935.2,1933.9,1931.2,1927.8,1927.4,1928.4,1929.3,1927,1928.8,1928.6,1927.8,1926.8,1928.2,1927.4,1928,1928.3,1928.9,1927.8,1926.6,1926.9,1927.5,1933.5,1932.6,1931.8,1930.7,1930.4,1926.1,1925.8,1925.9,1924.5,1927.5,1927.2,1924.7,1926,1926,1926.9,1929.9,1929.1,1925,1921.1,1924.5,1919.1,1917.4,1915.5,1914.4,1918.9,1920,1922.4,1920.5,1925.6,1926.4,1927.2,1924.8,1922.8,1922.7,1921,1920.5,1921.2,1917.8,1917.7,1917.8,1917.4,1916.3,1914.4,1915,1910.9,1911.9,1910.5,1908.4,1910.7,1911,1911.2,1914.8,1911.4,1911,1909.6,1907,1910.7,1911.7,1915,1918.5,1925,1927.4,1929.5,1931.7,1930.8,1932.4,1938.8,1939,1937,1936.3,1934.7,1933.7,1933.2,1933.1,1935,1932.1,1929.5,1930.7,1931.6,1931.4,1929.5,1929.5,1928.7,1928.4,1930.5,1931,1932.9,1932.3,1932.5,1930.8,1930.6,1931.9,1931.1,1931.5,1930.6,1932.4,1931.8,1932.9,1934,1934.2,1934,1929.5,1930,1931,1931.6,1931.7,1931.9,1932.5,1932.7,1933.3,1931.9,1932,1931.5,1932,1931.1,1930.6,1931.8,1931.7,1930,1925.8,1928,1928,1927.7,1926.5,1923.5,1924.1,1923.7,1924.3,1923.8,1923.6,1924.4,1922.8,1921.9,1916.5,1914.7,1915.8,1915.9,1915.8,1915.5,1915.1,1913.5,1914.2,1914.3,1910.8,1910.8,1909.8,1909,1906.9,1907.5,1907,1910,1909.1,1905.5,1905,1903,1900,1898.8,1897.9,1904.5,1908.7,1910.5,1903.9,1900.6,1898.6,1891,1886.9,1890.5,1893,1891.9,1890,1888,1894.9,1892.7,1895.5,1897.8,1898.8,1899.7,1901.1,1899.7,1897.4,1898.1,1907,1907.9,1905.2,1899.8,1899.3,1897,1896.7,1896,1892.9,1895.7,1894.4,1894.6,1894.4,1894.5,1896,1893.9,1893.7,1896.9,1896.7,1898,1896.5,1894.8,1895,1893.7,1894.9,1897.8,1893.6,1889.4,1891.5,1889.5,1887.9,1888.9,1888.7,1888,1888.5,1884.5,1890.5,1889.4,1889.4,1894.5,1893.7,1893.9,1898.2,1897.7,1893.4,1887.6,1887.4,1885,1882.8,1877,1874.8,1876,1877.7,1874.5,1874.7,1873.5,1874,1875.5,1874.5,1873.2,1872,1873,1872,1869.9,1865.6,1866,1864.7,1856.5,1854.7,1853.7,1850.2,1852.5,1860.8,1862.8,1857.6,1859,1856.9,1855,1865.7,1858.2,1851.9,1851.7,1845,1844,1837.6,1843,1840.4,1841.4,1844.8,1843.5,1842.8,1839.9,1838.2,1838.5,1835.6,1832.7,1833.8,1838.5,1843,1840,1838.7,1840.5,1839.7,1838.2,1835.5,1835.3,1834.2,1833.5,1832.1,1829.2,1827,1823.7,1828.8,1824.9,1825,1837,1838.9,1844,1846.1,1846.4,1847.6,1852.5,1857.7,1858.7,1854.2,1852.5,1853,1855.6,1863,1857.6,1859,1854,1848.7,1842.7,1839.8,1836.9,1834.9,1834.4,1831.8,1829.9,1828.3,1831,1829.7,1829.4,1827.5,1824.8,1829.4,1831.8,1830.7,1828,1826.5,1827.9,1828.9,1838,1837.4,1838.7,1837,1834.4,1836,1837.9,1840.9,1837.7,1836.3,1837.6,1837.7,1836.6,1833.5,1832.6,1833.6,1835.5,1830.7,1831.7,1833.8,1833.2,1833.4,1832,1838,1841.7,1836.9,1838.9,1839,1835.9,1835,1842.8,1843.8,1845,1846.5,1847.8,1856.4,1855.1,1855.6,1859.9,1857.5,1853.9,1852.7,1850.9,1848.9,1848.6,1848.4,1850.5,1848.1,1845.5,1846.3,1843,1842.5,1839.7,1838.8,1837.9,1838.7,1841,1838.5,1837.6,1840.2,1844.9,1844.2,1844.7,1842.8,1838,1835.9,1834,1835.7,1834,1837.3,1837,1836.8,1839.8,1839,1835.9,1833.4,1830.8,1827.7,1811.1,1807.8,1804,1803.8,1805.6,1818,1813.6,1814.4,1816.8,1817.5,1813.7,1813.9,1813.9,1810.7,1809.4,1812,1811.5,1816,1816.5,1814.7,1816,1814.7,1820.6,1821.7,1824,1823.8,1824.9,1825.6,1823.1,1821.2,1823.3,1824.7,1829.7,1830,1832.7,1833,1828.4,1829.5,1828,1829.2,1834.9,1834.9,1831.9,1831.4,1829.5,1830.6,1830.9,1824.7,1824.6,1824,1823.3,1825,1824.5,1823.1,1823.5,1826,1827.9,1823.9,1824.8,1824.9,1824.7,1824.8,1823.7,1822.8,1824.3,1824.7,1824.4,1825.8,1825.3,1824,1823.2,1824,1823.5,1822.3,1822,1820,1818.6,1818.5,1819.7,1825,1836.6,1842,1842,1840,1841,1839,1839.8,1843.6,1840.9,1840.7,1849,1847.4,1851,1850.3,1848.3,1852,1850.9,1851.5,1851,1852.5,1851,1851.8,1851.5,1854,1850.3,1852,1854.5,1855.9,1857.8,1858.3,1858.4,1857,1859.5,1859.2,1856.2,1854.8,1855.5,1862,1864.7,1864.5,1866.6,1866.3,1864.6,1868,1867.5,1871,1871.4,1873.8,1875.8,1881,1882,1883.8,1884.9,1882.4,1882,1881.8,1881.6,1880.8,1883,1888.5,1892,1889.8,1890.8,1889.8,1895.6,1895.9,1892.1,1884.8,1897.7,1894,1892.9,1892.4,1888,1885.8,1883.9,1887.3,1886,1886.7,1885.7,1884.7,1885.4,1888,1890,1888.9,1885.4,1885.9,1885.7,1885.6,1885.6,1885.2,1885,1884.3,1884.8,1886.5,1885.5,1885.5,1885.5,1885,1884.9,1883,1886.5,1880.5,1880,1879.7,1879.6,1877.7,1877.8,1877,1877.5,1877,1873.9,1871.3,1873.6,1872.6,1873,1871.6,1875,1889.3,1889,1891.9,1892.5,1892.5,1891,1887.5,1891.3,1894.3,1903.5,1904.5,1904.8,1902.8,1901.7,1898.5,1899.3,1899.7,1901,1901.5,1902.5,1904.6,1902.8,1902.3,1899.7,1901.9,1903.6,1906.7,1904.5,1906.3,1906,1908.8,1913.5,1913,1917,1918.2,1922.5,1922.2,1921.6,1923.9,1922.4,1923,1925,1924.5,1922.4,1920.4,1923.9,1923.8,1920.2,1914,1921.2,1920.8,1922,1919.3,1918.5,1926,1924.8,1919.7,1916,1914.9,1916.8,1917,1917.9,1918.3,1919.3,1920.6,1924,1925.6,1924.7,1923.5,1923.7,1922.4,1920.8,1918.1,1918,1919,1919.2,1920.3,1920.5,1920,1921.4,1920.5,1920.5,1920.5,1923,1924,1925,1922,1923.4,1924.5,1924.5,1923.8,1923.6,1924.9,1924.4,1921.7,1923.8,1924.7,1925,1942,1937.5,1937,1938.4,1936.9,1934.8,1934.9,1931.3,1927.4,1923.8,1923.2,1925.6,1926,1928,1930,1931.5,1930.4,1930.4,1930.9,1930.5,1928.8,1928.5,1928.6,1929.9,1930.5,1931.4,1930.7,1929.3,1928.8,1930.7,1929.2,1928.9,1929,1926.7,1924.9,1922.4,1923.5,1923.5,1921.8,1919.5,1919.9,1919,1918.5,1914,1913.5,1916.2,1913,1915,1913.8,1917.8,1917,1916.5,1917.6,1917.5,1915.9,1909.6,1908.5,1908.3,1909.6,1908,1912,1915,1915.5,1916.8,1921.8,1922,1918.9,1918.6,1918.2,1916.2,1913,1911.5,1911.5,1909.4,1910,1911.1,1909.6,1910.8,1909.8,1908.9,1914,1914,1913.4,1912.7,1909.8,1905.9,1907.5,1908.8,1909.8,1907.5,1907.5,1907.5,1904.5,1902.2,1899.4,1901.8,1902.6,1896,1897.6,1897,1896.9,1897.3,1895.3,1895.7,1892.8,1892.8,1892.8,1892.4,1893.5,1893,1894.8,1896.3,1902.8,1908.1,1908.2,1912.2,1913.9,1911.1,1910.2,1909.3,1911.8,1910.9,1907.8,1907.9,1905.3,1906,1906.7,1905.6,1909.7,1910.4,1906.6,1912.5,1912.8,1912,1912,1910.4,1910.3,1909.7,1908.6,1907.9,1909.9,1911,1911.3,1909,1907.4,1897.3,1890.1,1901.7,1900,1901,1902.5,1897.8,1894,1896.7,1895.8,1901.8,1905,1915,1915.5,1919.8,1916.8,1915.7,1917,1915.7,1914.9,1914.7,1917.9,1921,1918,1917.5,1919.3,1925.2,1927.6,1927.6,1930,1928.2,1929.9,1934.8,1930.4,1928.9,1929.7,1929.5,1929.9,1932.3,1929.8,1932.8,1934.9,1936.8,1936.5,1936.5,1932.7,1931.8,1932.5,1932.2,1931.8,1928.6,1936.8,1933.9,1932.7,1941.8,1942.8,1936.7,1928.1,1928.2,1929.8,1930.8,1931.1,1931,1934.9,1934.9,1933,1933.5,1930.5,1930.1,1934,1934.4,1933.4,1932.7,1932.7,1933,1932,1930.4,1929.7,1929.4,1929.8,1930.4,1930.3,1929.4,1929.3,1929.9,1932,1938.7,1937,1935.3,1930.5,1924.8,1923.6,1925.8,1923.5,1923.5,1924.8,1924.8,1922.9,1922.6,1924,1924.6,1925.8,1927.5,1926.8,1924.5,1925.7,1924.8,1924.5,1932,1942,1944.8,1947.8,1952.8,1947.5,1944.9,1943.9,1943.5,1941.9,1946.8,1943.3,1941.9,1941.3,1943.7,1943.5,1943.5,1944.5,1944.1,1946.1,1946.8,1948,1948,1943.3,1943.4,1946.6,1946,1945.5,1944.4,1943.8,1942.4,1939.7,1939.7,1939.7,1938.7,1938.4,1935.7,1938,1937.3,1937.9,1940,1946.5,1946.3,1947.5,1945.5,1949.3,1947,1939.5,1938.5,1940.4,1939.8,1939.7,1937.9,1941.3,1940,1939.4,1939.7,1942.8,1941.6,1941.3,1941.5,1941.9,1940.3,1941.2,1942.6,1940.7,1941.1,1942.1,1943.9,1943.7,1944.9,1946,1942.6,1941.7,1939.2,1938.2,1936,1935.5,1934.7,1930.8,1927.2,1928.2,1926,1923.8,1920.3,1917.3,1916,1913.7,1914,1901.1,1905.4,1906.5,1905.4,1906,1904.5,1906,1905,1904.9,1905.4,1903.7,1898,1915,1912,1908.7,1906,1909,1908.9,1908.6,1906.2,1908,1907,1907.9,1908,1906,1902.8,1898.2,1897.8,1896.1,1891.7,1893.4,1894.5,1900,1895.3,1894.4,1893.6,1893.4,1893.2,1892.6,1892,1886.7,1883.9,1891.6,1887.4,1882,1880,1883,1875.5,1880,1878.8,1883.4,1881.3,1882.9,1886.6,1885.7,1882.9,1880.3,1884.7,1884,1884.6,1883.3,1886,1883.5,1884,1883.4,1881.4,1877.5,1877.8,1878.3,1877.5,1876,1875.9,1881,1875.9,1877.8,1879.2,1878.6,1877.6,1877.2,1877.4,1882.8,1880.4,1879,1877.7,1879.7,1888,1887,1885.7,1887,1887.8,1886.4,1885.3,1885.5,1885.4,1887,1876,1878.5,1878.1,1880,1883.7,1883.1,1881.9,1882.5,1883.5,1881.6,1881.3,1882.8,1886.6,1890.9,1892,1889.8,1895.7,1896,1895.7,1897.6,1895,1894.4,1890.9,1890.4,1889.9,1884.8,1886.2,1885.9,1886.3,1885.3,1884.5,1884.1,1883.5,1882.9,1881.4,1877.4,1876.3,1876.4,1877.1,1877.3,1878.5,1875.9,1876.3,1873.9,1871.9,1873.8,1870.4,1868.8,1871.8,1872.3,1873.6,1873,1874,1880,1883,1879.5,1880,1879.2,1877,1874.4,1875.2,1873.8,1878.4,1876.6,1876.5,1876.9,1876.5,1879.9,1880.5,1878,1877.8,1872,1871.9,1873.4,1872,1871.7,1871.3,1870.3,1870.2,1870,1872.6,1872.5,1875.9,1877,1874,1875.1,1876.9,1879,1876.8,1873.7,1873.2,1874,1873.3,1872.2,1872.3,1877,1874.6,1876,1877.9,1877,1879.5,1880.9,1892,1890.8,1891.5,1892.6,1890.8,1895,1898.8,1898.8,1897.2,1898.4,1896.6,1896.5,1893.9,1893.5,1894.6,1891.9,1890.7,1891.8,1891.7,1893.9,1893.8,1892.1,1892,1893.1,1893.7,1894.9,1893.3,1893.1,1892.5,1892,1891.6,1893,1892,1892.6,1892.7,1892.5,1893.6,1893,1894.4,1894.9,1896.5,1903,1903.5,1903.5,1901.6,1898.5,1894,1891.9,1891.1,1887,1885.5,1884.4,1880.8,1882,1881.4,1874.9,1876.4,1878,1877.3,1878,1876,1879.7,1878.3,1879.2,1877.7,1878.5,1878.7,1878.1,1880,1880.5,1882.5,1884,1883.5,1884.3,1885,1887.8,1888.6,1889.9,1895,1907.5,1913.2,1913.4,1910.5,1918.8,1919,1922.9,1918.9,1921,1922.8,1924,1924,1925.7,1923,1922,1929.9,1930.9,1931.9,1934.2,1948.3,1948,1951.9,1953.8,1948.9,1943,1938.9,1941,1945,1942.9,1941,1943.3,1944.9,1947.9,1950.3,1948,1949.2,1949.5,1948.9,1947.3,1945.6,1941.3,1941.4,1941,1939,1943.5,1944.9,1946.9,1946.2,1942.6,1945.8,1947.8,1947.7,1944.8,1942.9,1943.7,1943.7,1942.2,1942.2,1943,1946.8,1941.1,1944,1946,1949.5,1945,1944.4,1943.7,1943,1949.4,1951.5,1949,1950.6,1953,1955.1,1954,1958.5,1957.9,1957.2,1954.6,1951.2,1951.7,1952.8,1953.3,1953.9,1954.8,1957.4,1956.6,1955.8,1955.5,1954.9,1953.4,1956.2,1955.6,1954.3,1953.8,1953.6,1953.9,1954.4,1954.9,1952.9,1951.2,1945,1941.7,1943.9,1945.4,1945.2,1945.3,1944,1943.9,1944.8,1937.9,1945,1946,1944.5,1944.6,1944.3,1939.9,1943.8,1941.8,1941.5,1944.8,1945.9,1943.2,1943.6,1948.8,1948.5,1950.5,1948.5,1947.9,1946.3,1944,1943.2,1943.6,1943.4,1940,1944.8,1943.8,1938.9,1939,1939.9,1942.2,1937.5,1938.8,1942.5,1942.7,1941.6,1942,1943.9,1941.7,1943,1945.9,1949.8,1947.5,1949,1953,1959.8,1963.8,1966.6,1964.8,1966.6,1962.9,1962.9,1970,1972,1976,1976.5,1976.1,1976.7,1976,1982,1983.5,1978.9,1980.3,1979.5,1977.3,1975.7,1974,1975.5,1975.8,1975.5,1973,1973.3,1973.4,1972.2,1969.4,1970.5,1972.2,1974.5,1973,1974.7,1973.6,1973,1972.8,1972.6,1974.5,1974.9,1975,1974.4,1971.7,1971.6,1969.6,1970.7,1973.9,1974.5,1973.9,1974,1973,1973.4,1973.5,1978,1975,1977.4,1978.8,1978.8,1980.8,1978.2,1979.4,1979.2,1977.9,1976.5,1977,1977.5,1977.1,1975.5,1974.5,1974,1974.4,1976.5,1979.6,1979.6,1975.8,1977.8,1977,1977.6,1977.5,1977.9,1978.5,1978.7,1980.6,1980.7,1980,1978.7,1978.1,1978,1976.8,1977.8,1978.3,1978.2,1980.8,1990,1993,1993.5,1993.3,1992,1992.8,1994.9,1993.3,1992.6,1991,1993.9,1992.4,1989,1986.8,1981.5,1977.9,1974.6,1973.3,1970.1,1972,1971.4,1969.3,1967.5,1964.4,1960.9,1962.4,1960.8,1958.5,1957.1,1955,1952.5,1954.8,1954.8,1955.8,1955.5,1959.3,1960.5,1962,1960.7,1961.5,1962,1958.9,1960.7,1961,1959.6,1960.5,1965,1964,1963.8,1959.9,1955,1956.2,1955,1954.5,1958,1961.7,1965,1964.4,1962.5,1961.5,1959.9,1959.7,1960.8,1955.5,1963.8,1962.8,1964.2,1970,1971.8,1976.1,1981,1979.6,1978.7,1978.5,1979.5,1976.3,1975.5,1975.2,1978.5,1977.5,1978.9,1977.3,1977.3,1976.8,1976.1,1976,1978.2,1979.5,1978.8,1977.5,1977.7,1978.5,1979.5,1980.5,1985,1983.5,1982.3,1979.6,1976.1,1976.7,1973.5,1974.7,1976.4,1978,1981.6,1980,1980.7,1977.8,1982.7,1989,1992,1991.7,1985.6,1987.4,1988,1989.8,1995.6,1991,1989.6,1988.9,1990.7,1992,1990.9,1988.6,1990,1991.9,1992.4,1991.6,1991.5,1990.7,1990.2,1988.5,1987.7,1989,1988.7,1990.3,1987.4,1985.7,1984.7,1984.7,1986.4,1985.5,1982.6,1981.5,1985.9,1988,1986.9,1988.9,1987,1990.4,1988.6,1988.5,1986.9,1985.1,1980.4,1973.3,1974.9,1972,1969.2,1971.6,1971,1964,1967.1,1967.7,1967,1968.9,1967.4,1964.8,1962,1964.8,1968.4,1966,1965.4,1965,1963,1965,1964.9,1963.7,1964.8,1963.9,1965.5,1966.5,1965.7,1967.4,1967.5,1966.3,1964.7,1964.4,1965,1964.9,1964.6,1964.9,1964,1964.8,1965,1963.9,1966,1965.8,1966.4,1967.2,1967.9,1966.5,1964.5,1964.1,1964.2,1964,1963.8,1963.9,1963.2,1963.6,1961,1963.9,1965.8,1966.6,1966.4,1966.6,1966.3,1968.6,1974.7,1975.8,1978,1978,1975.6,1977.5,1979.8,1980.8,1978.8,1978.9,1977,1976.7,1976,1976.1,1975.3,1975.7,1977.5,1978,1977.8,1977,1973.4,1972.5,1972.8,1973.4,1973.3,1972.9,1973.9,1973.9,1973.4,1973.1,1975,1974,1973.1,1971.9,1971.8,1970.8,1970.6,1965.3,1965.5,1964.8,1963.8,1966,1963.3,1963.4,1963.5,1962.5,1963.5,1965.8,1964.8,1965.4,1965.6,1965.8,1963,1963.8,1966.9,1965.3,1964.6,1964.9,1964.1,1963.6,1963.9,1963.9,1961.5,1960.9,1960.6,1960.3,1960,1962.3,1963.9,1965,1964.5,1975.7,1978.9,1978,1973.9,1973.8,1972.6,1973.7,1975,1976.3,1977,1978.7,1977.7,1977.5,1988.5,1983.7,1983.2,1985.9,1984.8,1983.6,1975.5,1965.4,1962.3,1961.7,1961.8,1962.5,1962.4,1961.3,1962,1961.5,1960.8,1959.1,1954.4,1952.3,1951.1,1950.5,1950.3,1950,1951.5,1953.7,1952.8,1951.7,1950.5,1953.3,1952.5,1952.5,1953,1952.7,1951.1,1950.4,1951.7,1952.8,1954.8,1954.8,1954.5,1956.8,1956.5,1954.7,1954.5,1955.5,1957.9,1957.9,1957,1952,1951.6,1947.8,1949.5,1948,1945.7,1940,1938.6,1939.4,1940,1940.9,1942,1943,1944.7,1942.2,1940.8,1939.6,1940,1939.5,1938.7,1936.8,1935.2,1933.2,1937.1,1939.4,1937.6,1936.6,1938,1940,1939.8,1937.7,1937.6,1937.6,1939.5,1939.8,1939,1937.5,1939.5,1939.3,1938,1936.3,1938.1,1937,1934.8,1931.5,1929.5,1926.5,1927,1927.7,1928.5,1928,1920.7,1922.8,1924.3,1928,1930.9,1936.9,1937.7,1938.2,1939.8,1942.6,1940.6,1941.5,1941.9,1939.2,1938.9,1939.9,1939.3,1939.5,1944.6,1947,1948,1947.4,1946.2,1945.3,1947.6,1946.1,1944.8,1943.2,1941.5,1941,1942.3,1941.9,1941.5,1941.9,1942.8,1943.9,1945.6,1945.3,1946.5,1946.2,1947,1943.6,1945,1946.9,1949.3,1949.8,1948.9,1947.5,1949.6,1951.8,1953,1953.9,1948.3,1948.1],
      "l": [1845.5,1842.2,1845,1843,1842.6,1840.7,1840.5,1840.6,1840.6,1843.1,1842.3,1841.1,1843.3,1852.1,1853,1852.7,1852,1850.5,1852.6,1855.3,1853.2,1850.6,1849,1846.5,1845.4,1845.2,1846.5,1846.8,1850.4,1848.7,1851.5,1848.5,1849.3,1851,1850.6,1844,1842.2,1842.5,1840.6,1841.3,1841.1,1842.1,1841.1,1837.3,1836.7,1840.8,1848.3,1848.7,1851.3,1867.3,1869.9,1870.8,1872.4,1872.6,1890,1892,1892.4,1896.6,1895.3,1894,1893.5,1893.5,1891.5,1894,1893.2,1893.1,1893.8,1894.5,1894.6,1892.3,1893.5,1894.2,1894.5,1893,1893.6,1893.5,1894,1895.2,1895.6,1883,1880.1,1880,1880.1,1881.6,1882,1881,1881.6,1878.9,1877.7,1876,1873.6,1875.5,1879,1872.8,1870.8,1870.7,1877.1,1877,1891.5,1889,1887.2,1888,1888.5,1892.6,1901.6,1903.9,1904.1,1903.4,1903.1,1901,1898.6,1902.6,1903.1,1900.5,1892.2,1895.5,1894.2,1892.1,1894,1893.6,1893,1894.5,1895.2,1893.1,1890,1889.5,1882,1876.2,1877.4,1880.6,1882.5,1882,1883.7,1887,1886.8,1893.3,1896.6,1891.3,1889,1887,1887.8,1886,1886.1,1883.5,1883,1887.3,1881.9,1843,1854.3,1852,1850,1851.7,1860,1858,1851.2,1850.1,1855,1856,1855.6,1853.4,1853.6,1852.5,1852.6,1854.1,1854.3,1853.8,1857.8,1857.8,1857.1,1857.7,1860.8,1861,1857.4,1855.3,1856.2,1857.6,1857.3,1855,1856.8,1858,1857.6,1857.1,1856.5,1855.4,1854,1854.6,1854.7,1855.4,1857,1856,1859.5,1861.8,1861,1859.6,1858.3,1858.2,1826,1827,1827,1823.1,1817.2,1819.1,1818.7,1814.1,1814.2,1818.1,1819.6,1819.3,1819.6,1816.2,1809.3,1809.2,1811.5,1810.1,1812.4,1812.8,1812.5,1813.2,1811,1810,1811.6,1812.1,1811.3,1812.2,1812.2,1812.8,1812.6,1814.3,1812.4,1810.5,1810.8,1811.6,1814.7,1814.8,1811.8,1811.3,1812,1805.2,1805.2,1801.8,1801.2,1798.7,1797.7,1791.4,1802,1774.6,1776.5,1777.4,1776,1771,1772,1774,1768,1763.2,1763.6,1758.8,1755,1753.6,1754.8,1757.2,1755.1,1756.4,1758.8,1759.5,1763,1760.1,1760.2,1756.6,1754.5,1754,1755.3,1759.8,1763.1,1769.1,1767.5,1767.6,1765.5,1762.6,1758,1756.6,1756.5,1759.2,1756.2,1751.5,1748.8,1750.2,1748.4,1745.5,1749.1,1749.5,1742,1741,1742.1,1740,1765.4,1771.3,1768,1766,1762,1764.7,1764.4,1764.3,1766.3,1767,1763.5,1761,1760.8,1760.1,1759.5,1766.2,1766.8,1768.6,1766,1766.8,1769.1,1773.6,1775.1,1775,1774,1774.5,1773.6,1770,1769.2,1769.4,1768.3,1770.2,1772.8,1770.6,1766.7,1766,1766.3,1763.6,1763.6,1762,1762.6,1765.6,1767.1,1769.5,1766.5,1763,1761.6,1765.1,1773.9,1801.2,1802,1801,1800.8,1801.6,1802.7,1803.2,1802.6,1801.4,1801.6,1801.5,1801.6,1797.5,1796.3,1797.7,1796.8,1798,1799,1799.5,1799,1799.5,1798.6,1797.9,1798.9,1794.1,1793.2,1793,1792.2,1794,1795,1793.5,1794.2,1795.2,1795.1,1795.6,1797,1798,1799.2,1797.1,1796.5,1795.5,1796,1797.1,1796,1797.5,1801,1803.7,1806,1814,1804.5,1803,1803.5,1800.8,1800.5,1798.5,1796.7,1796.6,1796.8,1795,1794.6,1792.9,1788,1789.2,1789.2,1793.1,1794.2,1794,1795.1,1794.2,1793.7,1793.8,1794.1,1794.1,1793.1,1793.9,1791.2,1790.9,1791,1791.3,1783,1784.2,1784.7,1784.6,1784.8,1785.3,1787.5,1785.8,1786.5,1786.6,1792.2,1789.3,1789.2,1785.7,1786.6,1788.4,1787.4,1789,1793,1783.2,1785.3,1787.8,1786.4,1786.7,1790.8,1789.3,1790.4,1790,1794.4,1794,1795.1,1805.5,1804.6,1804.5,1804.1,1803,1801.5,1802.1,1802.1,1802.4,1803.4,1802.7,1802.7,1801.3,1803.9,1805,1802.6,1803,1803.7,1805.5,1804.1,1804.8,1807,1807,1810.6,1810.6,1812,1815.1,1815.2,1816.6,1816.1,1816.6,1821,1822,1822,1824.8,1825,1821.1,1769,1769.6,1774,1774.7,1777.6,1776.9,1779.3,1780,1778.3,1779.1,1782,1779.7,1780.2,1778.8,1783.5,1788.2,1790.4,1792.7,1797.1,1798.2,1798.8,1795.4,1796.1,1795.6,1793.6,1793.8,1791.3,1791.2,1792.2,1793.2,1795.2,1795.6,1798.1,1799.4,1804.7,1805.1,1805.1,1809,1815.4,1816.6,1820.1,1821.8,1819.2,1819.4,1819.8,1816.5,1812.1,1796.6,1808.4,1820.4,1824.2,1828.4,1825.3,1823.4,1823.3,1821.7,1820.7,1821.2,1821.2,1823.9,1826.1,1824.2,1824,1834,1834,1833.5,1835.9,1836,1834.2,1835,1834.8,1834.6,1829.1,1828,1827.5,1828.4,1827.5,1829,1832.6,1832.7,1835,1825.7,1824.3,1825,1821.3,1821,1822.4,1818.6,1821,1822.1,1822.3,1826.3,1825,1823,1823.3,1818.6,1821,1823.9,1860.7,1865.3,1866.5,1870.5,1869.5,1869,1867.1,1867.2,1869.7,1869.5,1868.5,1868.3,1871.5,1869.3,1869.7,1869.7,1869,1868.4,1868.4,1866.3,1865.2,1866.4,1866.5,1868.3,1867.1,1866.7,1867.6,1868.3,1868.3,1868.3,1870.5,1868.5,1867,1869.8,1870.3,1871.5,1870,1870.2,1873.5,1877,1877.5,1876.1,1877.3,1874,1872,1872.5,1873.8,1875.3,1875.8,1852,1853.6,1850.7,1845.1,1849.5,1846.1,1843.2,1844.7,1845,1846,1847.3,1846.8,1847.7,1845,1845.3,1844.1,1843.6,1847.2,1847.2,1846.5,1846.3,1845.9,1847.4,1845,1844.6,1845.3,1844.1,1844.8,1845,1845.1,1840.1,1841.3,1841.1,1842.5,1842.6,1842.5,1841.6,1838.9,1840,1841.6,1841,1838.3,1842.5,1842.1,1842.2,1842.5,1842.2,1843.4,1853.2,1866.1,1865.2,1862.5,1862.8,1863.7,1864.3,1864,1860.7,1860.3,1861,1860.1,1860.5,1862.5,1861.5,1861.6,1862.1,1861,1858.2,1856.7,1855.6,1856.1,1855.6,1856.2,1857.1,1855.3,1855.8,1857.5,1857.7,1857.6,1857.5,1855.8,1853.2,1849.2,1848.8,1847.6,1843.6,1840,1839.3,1841,1835.1,1836.6,1836.1,1833.5,1831.1,1829.2,1830.7,1830.2,1834.4,1835.4,1830,1834.5,1834,1834.3,1831.4,1838.6,1840.3,1842.5,1849.3,1846.7,1845,1846.3,1844.1,1841.1,1837.3,1834.5,1832.8,1832.8,1833.7,1833.8,1833,1834.8,1833.9,1835,1836.6,1837.1,1837.1,1835,1834,1835.2,1834.2,1837,1837.4,1840.2,1842.7,1842.9,1844.8,1844.3,1845,1841.2,1840.6,1842.7,1839.3,1836.7,1835.1,1836.6,1835.8,1833.6,1845.3,1839.1,1839.1,1837,1837.1,1837.8,1838,1835.2,1836,1838.3,1839.5,1842.6,1842.1,1848.4,1851.1,1852.8,1850.6,1851,1852.5,1851.4,1849.7,1850,1849.8,1849.2,1850.1,1849.5,1847.5,1845.3,1842.4,1842,1842.2,1842.2,1844.4,1845.4,1843,1842.5,1842,1844.1,1843.3,1843.5,1838,1838,1838,1837.3,1838.2,1836.1,1839.9,1845.6,1847,1848.2,1915,1912,1908,1906.7,1902.2,1900.5,1893.3,1893.5,1894.5,1895.1,1894.5,1895.3,1899.1,1900.7,1900.7,1902.8,1904.2,1909.4,1908.4,1910.5,1911.6,1912.6,1912.3,1911.2,1911,1912,1911.2,1913.2,1913.5,1912.3,1914.8,1918.3,1920.5,1920.3,1923.4,1926.5,1929.1,1931.1,1929.7,1929.8,1934,1936,1936.5,1936.1,1936.3,1935,1937.3,1937.9,1942,1929.4,1927.3,1924.2,1923.8,1926.7,1925.7,1923,1924.3,1925.5,1926.9,1928.6,1931.3,1932.5,1928.7,1927.5,1928.1,1925.8,1930.7,1930.5,1930.5,1929.5,1929,1928.5,1928.8,1927.2,1930.1,1928.5,1928.8,1928.7,1923.9,1924.8,1930.1,1931,1932.4,1931.5,1932.6,1934,1936,1935.1,1934.2,1934.7,1936.8,1936.1,1935.3,1935.3,1932.4,1930,1924,1921.7,1935.5,1943,1945.1,1945.5,1946,1945.1,1945.6,1947,1951.2,1951.3,1948.4,1946.5,1947.8,1948.4,1948.7,1949.3,1948.2,1949.5,1946.6,1947.2,1947.5,1948.5,1948.2,1948.1,1950.1,1948.5,1946.2,1947.2,1947.3,1947.7,1947.6,1948.7,1943.1,1942.6,1944.5,1946.1,1947.4,1945.2,1944.6,1945.3,1945,1944.7,1940.8,1938.6,1937,1938.3,1934.1,1932.3,1931,1913.2,1915,1912.2,1911.5,1915.6,1914.8,1913.9,1914.9,1915.7,1917.5,1918,1918.2,1920.2,1920.5,1917.2,1917.8,1918.4,1919.2,1919.1,1916.2,1915.5,1914.3,1914.9,1915.4,1914.9,1915.5,1915.5,1914,1914.1,1916,1918.5,1920.2,1926.6,1926.7,1927.3,1924.2,1924.4,1925.1,1925.1,1925.1,1926.5,1927.9,1928.2,1930.2,1930.5,1931.1,1928.7,1929.6,1932.2,1952.2,1956.8,1957.5,1957.6,1957.2,1957.8,1957.5,1957.6,1957.7,1953,1954.1,1954.3,1950,1947.2,1948.1,1948.5,1948.6,1945.7,1945,1944.1,1946.6,1946.8,1946.8,1948.8,1945.8,1942.1,1940.3,1940.7,1940.6,1941.5,1940.4,1944.5,1947.4,1943.1,1941.2,1938.5,1942.1,1941.6,1944.4,1940.7,1942.5,1942.5,1942.8,1941.2,1944.8,1941.5,1942.4,1943.6,1946.3,1958.1,1961.2,1961,1959.2,1955.2,1956,1957,1955.5,1955.4,1956.7,1957,1957,1957.9,1958,1957.7,1957.7,1958,1958.4,1959.1,1960.5,1959.5,1958.3,1957.3,1956.6,1957,1957.3,1956.5,1957,1957.5,1958.5,1957.5,1957.1,1957.5,1957.2,1958.9,1959,1960.4,1957.4,1957.3,1956.6,1957.7,1955.5,1957.2,1959.3,1958.5,1958.5,1959.3,1960,1961,1967.3,1968.1,1968.5,1969,1968.6,1970.1,1969.5,1968.4,1968.3,1968.6,1966.3,1965.3,1966,1966.8,1966.1,1967,1967.3,1967.2,1969,1969.4,1970.8,1973.2,1972.5,1973.8,1974,1974.5,1973.7,1974.1,1974.6,1974.6,1974,1975.7,1975.8,1976.2,1978.3,1978.6,1982,1981.6,1981.5,1980.2,1977.3,1976.3,1975,1971.5,1972.3,1975.9,1978.6,1979.7,1980.5,1964,1969.1,1972.6,1975.5,1980.1,1982.4,1985.6,1983.7,1982,1982.3,1976.5,1976.5,1980.2,1984.2,1987.1,1989.1,1991.4,1989.1,1988,1987,1986.5,1986.3,1985.1,1988,1989.1,1988.3,1989.1,1989.1,1989.3,1990.5,1989.2,1989.3,1990.4,1990.6,1991.4,1992.1,1992.5,1992.2,1991.2,1991.1,1991.5,1989.5,1987,1986.2,1984,1982,1983.3,1985,1987.9,1992.1,1992.3,1992.2,1989,1988.8,1990.6,1989.5,1989.1,1988.3,1986,1987,1988.3,1988.5,1989.2,1990.2,1991.4,1991.8,1993.5,1993.2,1992.2,1992.7,1993.6,1992.6,1993.2,1993.8,1992.2,1990.1,1988,1988.1,1988,1988,1989.8,1991.2,1988.5,1988.5,1988.1,1988.1,1989.1,1989.5,1990.7,1990.3,1990.4,1991.5,1990.8,1991.1,1991.7,1994.1,1993.1,1997.9,2005.4,2008.5,2011.6,2013.1,2013.5,2012.7,2012.6,2012.5,2013.3,2013,2014.8,2016.6,2015.7,2016,2016.2,2019.4,2022.7,2022.3,2022.3,2022.3,2019.1,2018.1,2019,2019.5,2015.1,2015.5,2015.7,2017,2017.3,2018.1,2019.5,2018.8,2018.2,2015.9,2017,2017.3,2015.5,2016.2,2016.8,2016.2,2016,2016.5,2013.5,2011.7,2011.8,2010.1,2007.5,2001.3,1998,1993.1,2000,1999.6,2000.3,1997.3,1998,1994.1,1992.3,1994.5,1996.8,1996,1995.5,1995.7,1994.4,1994.6,1994,1994,1993.3,1994.5,1996.2,1989.1,1988,1988,1986.2,1985,1985,1983.8,1982.3,1980.4,1983.6,1986.1,1986.1,1988.3,1991.4,1993.3,1995.5,2002.4,2004.5,2006.1,2009.5,2011.1,2016.6,2017,2020.6,2023.4,2023.4,2031.1,2032.4,2040.6,2043.1,2037.7,2035,2034.5,2033.5,2036.1,2038.1,2039.7,2034.7,2036.1,2036,2037,2035.8,2036,2043.3,2037.5,2036.5,2037,2028,2028.3,2026.2,2024.5,2026.1,2026,2026.2,2027.7,2027.8,2027.4,2027.3,2026.2,2026.2,2021,2022.7,2018.3,2006,2007,2008.6,2002.1,2001.3,2004.9,2008,2003.2,1997.8,1998,2002.4,2006.2,2013.1,2018.1,2019.2,2011.2,2012.5,2008.5,2006.3,2005.3,2006.6,2006.3,2008,2010.3,2008.5,2009.9,2009.6,2011.1,2009.2,2009.5,2006.5,2007.5,2007.3,2004.5,2006.3,2006.3,2006.1,2008,2007.1,2005.1,2007.5,2010.6,2011,2012.9,2010.8,2013.2,2008,2007,2009.4,2009.1,2007,2001,2003.1,2005.2,2008,2008.3,2011.3,2012.2,2012,2005.5,2006,2010.3,2010,2015,2019,2016.3,2015,2016.3,2018.7,2019.3,2017.5,2018,2018.8,2018.5,2017.5,2017,2017.4,2017.2,2020,2021.1,2021.8,2021.2,2020.2,2020.6,2025.9,2028.1,2033.2,2037.7,2040.3,2039.5,2037.1,2038.1,2039.6,2039,2032,2029.3,2029.3,2027.6,2025.4,2027.3,2026.8,2030.3,2031.2,2030.2,2033,2031.4,2028.5,2027.8,2028.5,2029.2,2030.5,2026.6,2028,2030.5,2035.4,2034.4,2033.3,2034.3,2033.8,2033.3,2033,2029.2,2028.4,2030.1,2027.5,2029,2025.4,2028.7,2028.3,2028.5,2029.1,2027,2026.7,2027.9,2028.3,2029.5,2027.6,2026.8,2027.5,2027.7,2027.5,2028,2028.2,2028.1,2029.1,2028.2,2027.4,2027.5,2028.2,2028.3,2025.5,2027.3,2030.7,2030,2027.5,2027.6,2027.5,2027.5,2027.1,2021.1,2023,2028,2039,2048.2,2046.4,2043.4,2042.6,2038.6,2039.1,2037.9,2042,2039.5,2035.2,2035.2,2034.3,2032.6,2033.6,2035.3,2030.2,2030.5,2028.7,2026.1,2027.2,2028.1,2025,2022.6,2017.4,2017.3,2023.4,2023.1,2024.5,2023.6,2020.5,2013.4,2015.5,2015.5,2016.1,2013.5,2013.6,2019.2,2014.2,2005,2011.2,2008.1,2009.1,2013.7,2014.7,2015.7,2016.7,2014.1,2017.9,2001.3,2004.2,2007.9,2006.5,2004.5,2003.3,2004,2009.7,2010.5,2011.2,2009.3,2008.7,2009.1,2005.6,2006.5,2006.1,2006.6,2006.2,2004.1,2004.2,2009.2,2011.3,2012.4,2012,2011.6,2012.7,2014.3,2014.3,2013.1,2012.7,2012.2,2012.7,2012.6,2013,2011.8,2014.2,2011.1,2010.2,2014,2018.1,2020.7,2024,2029.9,2032.4,2033.2,2031,2032.9,2033.6,2038.8,2046.3,2045.3,2046.2,2047,2046.4,2045.5,2045.6,2046.3,2040.2,2040.6,2042,2041.3,2040.1,2038.2,2037.5,2037.7,2039.4,2038.4,2036,2037.3,2035.3,2035.7,2036.5,2037.7,2037,2036.2,2036.2,2037.4,2038.6,2038.6,2038.4,2038,2042.5,2042.5,2042.3,2046,2044.2,2045.7,2044.5,2046.8,2048.4,2051.6,2057.2,2059.4,2059.6,2057.2,2059.7,2061,2060,2066,2066.6,2065.5,2066.8,2069,2068.2,2068.8,2071.2,2068.6,2068.2,2068,2067,2066.5,2062,2061,2063.6,2062.5,2064.5,2067.5,2069.6,2073.6,2075.1,2076.4,2077.1,2073.5,2073.1,2073,2072.6,2075.3,2074.3,2074.2,2077.3,2086.1,2088.2,2086,2081.1,2083,2083,2082,2082.4,2082.2,2083.9,2073.3,2074.3,2075.1,2076.6,2079.2,2080.2,2080,2066.8,2068.6,2069.6,2068.2,2069.6,2070.3,2069.4,2067.6,2068,2069,2068.8,2069.6,2070.5,2069.7,2069.5,2070.3,2070.7,2072.3,2072,2071.7,2071.3,2069.5,2070.4,2070.1,2069.3,2069.5,2072,2071.4,2071.8,2071.6,2070.5,2072.2,2077.2,2078,2079.1,2076.1,2078,2078.4,2080.4,2080.3,2077.1,2075.7,2075.6,2066.9,2063.1,2066.3,2068.3,2070.7,2073.4,2068,2069.2,2070.2,2069.3,2069.1,2068.9,2066.7,2065.7,2063.3,2061.3,2061.8,2063.4,2063.2,2065.4,2065.6,2064.1,2064.3,2066.1,2064.1,2064.1,2066.4,2066.7,2067.5,2067.5,2064.8,2064,2064.4,2064.5,2065.2,2065.3,2064.6,2065.2,2064.5,2070.5,2069.3,2062,2062.5,2056.1,2055.1,2054.3,2052.3,2055.2,2053,2050.9,2048.7,2046,2040.3,2040,2039,2037.6,2038.5,2037.7,2036.4,2036.1,2035.3,2038.3,2038.7,2038.6,2038.1,2037.1,2037.1,2037.6,2036.5,2036.9,2037.9,2038.8,2037.3,2037.8,2038.4,2037.4,2037,2036.7,2036.8,2036.7,2035.9,2031,2030.7,2028.1,2026.5,2025.6,2028.7,2028.1,2028.2,2029.1,2030.1,2030.4,2029.6,2037.1,2037.8,2045.5,2044,2044.6,2042.2,2040.3,2041.2,2045,2041.6,2049,2051.3,2053.1,2049.7,2047.3,2045.6,2045.2,2042.5,2040,2038.3,2039.1,2036.5,2037.6,2037.5,2040.4,2039.4,2040.8,2041.6,2038.1,2038.4,2040.3,2043.7,2039.1,2038.5,2038.6,2035.5,2035.5,2035.2,2038.2,2037,2038.5,2039.3,2037.2,2037.5,2036.6,2037.6,2032.2,2031,2033.2,2030.2,2028.6,2029.5,2025.4,2023.7,2021.5,2022.4,2026.4,2030.1,2031,2039.9,2034.8,2036.2,2036.5,2035.7,2035.2,2035,2037.4,2046.5,2048.5,2048.1,2050,2049.2,2048.5,2047.3,2046.7,2048.6,2049.8,2049.7,2052.6,2055.8,2055.3,2055.6,2056.8,2060.5,2057.3,2056,2056.6,2056.7,2054.1,2052.7,2054.3,2057.7,2057.1,2055.3,2054.8,2051.6,2050.1,2051.8,2051.3,2051.9,2054,2055.5,2056,2052.9,2052.5,2051,2056.5,2058.9,2065.1,2059,2060.5,2060.3,2059.1,2060.4,2059.3,2058.1,2056.5,2055.5,2054.3,2056,2056.9,2057,2055,2053.5,2054.5,2054.8,2055,2054,2056.2,2056.5,2058.3,2056.5,2056.9,2056.6,2057.6,2058.3,2058.9,2057.3,2059.3,2045,2042.1,2044.7,2043.5,2044.6,2046.2,2046.5,2047,2045.9,2047.4,2045.8,2046.4,2047.2,2049.4,2050.8,2050,2048.5,2050.1,2053.9,2036.5,2033,2033.1,2034.1,2035,2034.6,2034.9,2036,2037,2035.5,2035.1,2035,2035.7,2035.5,2034.1,2033.3,2033.6,2035.1,2030.5,2028.3,2031.5,2031.5,2031.1,2032.5,2031.4,2032,2031.4,2033.8,2034.6,2035.3,2034.6,2033.3,2035.3,2033.3,2032.6,2033.8,2036,2036.2,2037,2037.3,2041.5,2041.1,2043,2045,2044.6,2046.3,2049.4,2052.6,2047.5,2045.7,2044.5,2044,2041.3,2041.7,2036.8,2035.2,2036,2037.3,2037.8,2037.9,2038.1,2036.5,2037.5,2038,2037,2036.5,2037.4,2033.5,2035.9,2034.6,2034.3,2035,2035.5,2036.4,2036.1,2036.5,2037.1,2037,2028,2026.5,2023.2,2028,2029.2,2029.6,2028.3,2028.1,2026.2,2033,2035.8,2035.6,2037.1,2037.5,2036.1,2036.3,2028.5,2028,2030.2,2030.1,2020.5,2021.6,2022.3,2024.2,2025.1,2029.5,2029.3,2028.4,2028.6,2026.5,2025.6,2025.4,2025.3,2025.8,2026.8,2027,2025.5,2027.6,2027.5,2027.2,2023.1,2022.5,2022.4,2021.1,2018.5,2017,2015.5,2014.3,2011.3,2006.8,2001.1,2003.7,2008.7,2010.8,2015.4,2013.5,2017.6,2019.6,2018.8,2018.5,2018.3,2020.1,2018.7,2019,2019.1,2022.2,2024.8,2029.6,2040,2042.8,2043.1,2043.8,2041,2038.1,2037.8,2037,2039.1,2034.2,2035.2,2036,2037.1,2039.4,2038.8,2038.6,2037.5,2037.8,2040.8,2040.9,2039.2,2036.7,2036.6,2033.3,2033.2,2032.7,2034.3,2033.8,2036,2037.2,2039.2,2033.4,2034,2032.8,2031.1,2034.8,2033.6,2033.2,2035.2,2035.1,2037,2036.3,2037.2,2036.6,2037.6,2037.6,2032,2029.5,2030.5,2031.5,2010.5,2010.2,2011,2005.7,2006.5,2005.4,2000.2,2001.6,2002.5,2003.2,2003.1,2003.6,2003,2005.2,2002.5,2001.5,2001,2003.2,2005,2002.7,2003,2000.5,1998,1998.5,1995.6,1994.3,1995.5,1995.2,1998.3,2005.5,2006.7,2012.4,2012.3,2012.2,2010,2008.1,2007.5,2009.7,2011.2,2011.1,2012.7,2012,2008.1,2008.1,2006.6,2006.7,2008.4,2009.5,2010,2016.3,2014.6,2016.3,2019.8,2018.2,2018.2,2019.6,2021,2022.5,2020.6,2020.8,2019.2,2019.1,2019.5,2020.3,2024.9,2023.8,2024,2025,2024.4,2025,2021.1,2020.9,2020.1,2020.3,2020.1,2020,2018,2017,2018.5,2018.6,2020.7,2023.3,2025.4,2026.1,2026.4,2027,2027.8,2026.5,2026.9,2024.1,2023.5,2021.3,2022.7,2021.5,2019,2018.6,2018.5,2022.4,2018.3,2019.3,2020.8,2020.2,2021,2022.4,2023.1,2021.8,2021,2024,2024.7,2024,2025,2026,2025.5,2025,2023.5,2023,2023.6,2022.5,2022.4,2022.7,2023.1,2023.2,2023.5,2022.9,2021.6,2021.6,2022.2,2022.1,2021.3,2021.6,2020,2019.5,2020.6,2021.2,2023.5,2023,2024.2,2021,2019.5,2020.2,2020.9,2024.6,2024.2,2024.5,2025.2,2030.1,2033,2031.7,2032.3,2033.8,2031.5,2028.5,2028.6,2028.7,2029,2028.8,2028.1,2022,2022.6,2020.9,2019.4,2019,2021.5,2022.4,2023.6,2022.7,2021.5,2022.5,2022.5,2023.2,2021.6,2021,2021,2021,2020.7,2017.3,2016.6,2016.5,2019.5,2020.5,2019.5,2018.7,2022.9,2020,2018,2016.5,2019.8,2022.2,2022.5,2022.1,2022.5,2020.1,2020.5,2018.8,2018.8,2024.8,2019.9,2022.5,2021.2,2019.5,2022.8,2024.2,2026.4,2025.1,2022.2,2022.4,2022.5,2020.2,2020.5,2019.7,2018.4,2019.6,2019.5,2020.1,2018.8,2015.9,2011,2011.5,2011.5,2010,2011.1,2007.3,2008,2007,2008.7,2009.6,2010.3,2010.1,2010.5,2010.5,2010,2011.4,2011.6,2012.7,2013.5,2014.1,2013.1,2013.1,2013.6,2014.7,2017,2015.1,2011.6,2008,1990.1,1993.1,1993.4,1994.6,1995.3,1994.4,1992.6,1994.3,1994.1,1993.6,1995,1996.8,1998.8,2000,1999.1,1999.1,1999.3,1999.5,1998.9,1995.8,1995.8,1995.8,1996.3,1998.5,1996.6,1996.5,1997.8,1999.5,1998.5,1998.8,2003.3,2006.6,2005.5,2005.1,2005,2005.9,2010,2010.8,2011.2,2012.1,2010.8,2009.8,2008,2006.3,2005.5,2006.7,2009.2,2007.1,2003.5,2005,2001.9,2000.2,2002.2,2002.5,2002.6,2003.5,2003.5,2004.2,2005.5,2004.3,2004.6,2004.3,2002.7,2002.5,2001.9,2002.2,2001.1,2000.5,1998.9,2000,1996.2,1996.5,1995.2,1996,1996,1996.6,1996.1,1996.5,1995.5,1996.3,1996,1995.2,1995.8,1996.2,1995.6,1995.2,1995.2,1993.3,1995.5,1994.7,1993.8,1992.8,1995.6,1994.5,1996,1990.6,1985.5,1984,1991,1984.9,1985.7,1986.3,1986.3,1987.7,1988.6,1990.8,1992.1,1994,1996.1,1994.7,1994.1,1993.5,1993.6,1993.5,1993.5,1991.4,1991.2,1991.6,1990.4,1989.2,1989.7,1990.1,1989,1989,1991.4,1990.4,1989.5,1989.2,1983.9,1984.5,1985.2,1987,1987.7,1987.1,1985.8,1986.7,1987.1,1987.3,1985,1983.8,1981.8,1980,1983.5,1976.7,1978,1974,1973.1,1972.1,1975.3,1974.8,1975.8,1975.4,1974.1,1973.7,1972.9,1972.5,1972.1,1972.1,1972.7,1972.7,1974.1,1974,1974.8,1975.2,1975.2,1972.5,1970.9,1973.1,1971.1,1972.8,1972.2,1972.2,1973.6,1974.5,1974.3,1975.8,1975,1974.6,1975,1974.7,1975,1975.2,1975.7,1982.5,1985.1,1989.7,1991.1,1991.8,1991.2,1989,1990.7,1988.3,1986.1,1981.6,1978.5,1965.2,1972.4,1968.8,1969.5,1969.3,1967.7,1967.8,1971.8,1972.5,1971.5,1971.2,1972.5,1971.6,1971,1971.2,1971.3,1971.5,1968.4,1968.4,1968.6,1968.5,1968.6,1968.1,1970.8,1969,1968.2,1968.5,1968.6,1968,1966.8,1971.3,1970.3,1971.5,1971.8,1977.4,1978.6,1976,1974.1,1976,1977.9,1979.2,1977.2,1977.2,1977.8,1977.5,1975.3,1977.6,1979.5,1982.7,1982.1,1982.4,1979.3,1982,1982.9,1982.5,1982.6,1982.4,1983.3,1983.7,1983.8,1983.1,1983.4,1982.6,1982.9,1982.1,1981.5,1981.2,1982,1983.2,1981.5,1982.3,1983.4,1982.9,1982.8,1982.7,1982.6,1982.5,1983,1983.2,1984.9,1984.3,1983.5,1980.4,1979.3,1979.5,1977,1979,1979.5,1977.6,1978,1978,1978.3,1978.3,1975.5,1975.2,1973.9,1972.9,1975,1978.4,1982,1967.3,1967.9,1966,1965.8,1967.2,1964.2,1960.7,1958.3,1959.8,1961.7,1962.1,1962.3,1960.1,1955.1,1952.8,1954.6,1953,1954,1955.6,1954.6,1956.2,1956.7,1954,1953.8,1954,1953.5,1951,1951.7,1950.1,1949.5,1948,1949.5,1950,1950.1,1947.5,1948.2,1951.8,1951.7,1950.6,1950.8,1949,1948.5,1946.7,1942.8,1941.5,1943.1,1936.8,1937,1937,1939.2,1941,1941.4,1941.5,1941.6,1940.2,1942.7,1942.8,1942.7,1943.4,1942.1,1941.4,1941.2,1939.4,1938.9,1938.7,1938.1,1939.1,1940.6,1941.3,1942.5,1943,1944.9,1946.2,1950.1,1949,1948.8,1948,1949,1948.7,1950,1948.6,1948.5,1948.8,1951.2,1950.3,1947.4,1946.5,1946.7,1947.9,1948.6,1949.1,1952.1,1951.6,1949.5,1949.1,1949.1,1948.1,1950.5,1943.6,1945.2,1944.8,1944,1945.4,1946.5,1945.5,1947.1,1946.6,1946.7,1946,1944.7,1944.8,1945.1,1945,1945,1946.5,1947.7,1952.5,1954.3,1954.5,1954.5,1957.1,1956.1,1957.5,1958,1956.7,1956.2,1956.9,1956.5,1955.3,1957.5,1957.6,1956.8,1956.9,1956.8,1954.4,1954.5,1955.1,1957.4,1955.5,1956.1,1957.1,1954.7,1955.4,1957.6,1960.1,1956.6,1961.5,1951.7,1950.4,1947,1946.8,1948.2,1948,1946.4,1945.2,1944.3,1945.8,1947.2,1946.8,1946.7,1948.1,1947.8,1947.4,1947.2,1947.1,1947.3,1948.1,1949.1,1950.1,1950.6,1951.5,1951.1,1951.4,1949.4,1949.5,1950,1950.3,1949.9,1948.2,1950,1951.3,1951.1,1951.7,1953,1952.3,1952.8,1952.2,1951,1951,1950.5,1952.2,1952.8,1952,1951.5,1950.5,1952.8,1963.2,1964.2,1965.9,1965.1,1965.3,1963.6,1963.7,1963.9,1964.1,1964.1,1964.4,1964.2,1964.3,1965,1965.7,1971.4,1971,1969.6,1964.7,1964.2,1965,1964.5,1965,1964.6,1965.1,1964.8,1965.2,1965,1964.9,1965.8,1965.1,1965.9,1965.1,1965.5,1966.2,1966.7,1966.6,1967.4,1967.7,1963.6,1963.6,1963.4,1956.8,1956.8,1953,1947.5,1940,1935,1939,1957.4,1961.6,1960.4,1960.4,1960.5,1960.6,1959.3,1960.3,1958.5,1958.7,1957.4,1954.1,1954.2,1950.5,1951,1950.2,1952.7,1952.8,1952.1,1953.2,1954.6,1955.1,1956.5,1955.4,1955.8,1959.4,1956.8,1956.8,1958,1958.2,1959.2,1957.7,1959.9,1963.1,1964.5,1966.6,1966.8,1965.1,1961.3,1960.7,1962,1962.5,1962.5,1961.6,1960.7,1957.8,1960.7,1960.8,1965.2,1966.4,1968.2,1967.5,1967.2,1966.8,1965.8,1965.5,1967,1967.5,1966.8,1967,1966.8,1966.7,1963,1963.7,1964,1964.1,1964.2,1964.4,1965.4,1965,1963.9,1964.2,1964.5,1963.1,1964,1964.1,1964,1964.6,1964.8,1964.3,1964.3,1964.8,1964,1964.8,1966.1,1963.5,1963.3,1964.2,1964.5,1963.8,1964,1960.1,1959.5,1960.9,1960.8,1960.2,1961.2,1964,1957.5,1956.2,1954.2,1955,1955.8,1957.5,1956.6,1957.1,1958.2,1959.2,1959.1,1960.4,1959.6,1959.7,1958.8,1957.7,1956.7,1956.2,1956,1956.6,1956.9,1956.3,1955.9,1954.4,1952,1951.9,1952.7,1951.3,1951.6,1950.1,1950,1951.6,1952.9,1954.3,1954.5,1954.5,1956,1958,1957,1957.2,1959.2,1958.5,1959.6,1961,1961.5,1961,1961.3,1961.5,1959.9,1965.9,1965.4,1963.6,1963.2,1964.7,1965.5,1964.6,1966.3,1968.1,1969.2,1968.3,1967.6,1968.1,1967.6,1968.5,1969,1969.4,1969.7,1968.6,1968.8,1969.5,1969.7,1969.8,1970,1970.7,1970.8,1971.3,1970.7,1971,1973.1,1974,1974.2,1973.1,1974.8,1975.5,1975.6,1974.1,1972.8,1971,1971.1,1971.8,1971.6,1971.5,1972.3,1972.2,1970.5,1970,1970.8,1971.4,1972.4,1973,1971.6,1967.3,1964.5,1960.1,1959.3,1963.5,1963.7,1963,1963.8,1962.8,1962.4,1962.5,1962.5,1960.8,1961,1962.1,1962.5,1962.3,1962.2,1962.1,1963.6,1964,1965.5,1964.7,1964.8,1962.8,1961.1,1961.1,1960.8,1960,1961,1962.1,1962.3,1963.1,1964.1,1963.6,1963.2,1963.5,1962.4,1962.7,1963.4,1960,1961.4,1961.7,1956.3,1957.8,1964,1966.2,1966.9,1967.2,1965.1,1965.8,1967,1967.6,1968.2,1968.1,1967,1966.5,1965.9,1966.5,1967,1967.9,1968.8,1969,1970.6,1972.8,1972.3,1974.6,1974.3,1974.5,1975.2,1974.6,1974.5,1976.3,1977.3,1977.4,1978.2,1979,1979.9,1979.7,1980.3,1982.2,1982.1,1981.4,1980.4,1980.5,1980.8,1980.1,1977.3,1976.2,1979.6,1981.2,1981.9,1983.7,1984.6,1984.8,1984.2,1984.5,1984.6,1984.5,1988.2,1986.3,1986.9,1987.3,1988.1,1987.1,1985.3,1984.8,1983,1981.5,1982,1982.7,1983.5,1982.5,1982.9,1982.9,1983.3,1983,1983,1983.5,1984.5,1983.4,1984.6,1985.5,1987.2,1989.8,1998,2004.2,2005.5,2008.6,2008.8,2006.2,2004.5,2003.5,2004,2003.7,2000.9,2000,1998.6,1995.2,1993.7,1992,1991.2,1987.5,1991.4,1995,1996.1,1998.6,1997,1999.5,2000.3,2002.6,2002.5,2002.2,2002.1,1998.6,1999,1998.7,1997.6,1996.9,1997.5,1997.6,1997.5,1998.8,1995.7,1996,1996.4,1996.2,1996.5,1996.4,1996.2,1995.9,1995.1,1996.8,1997,1998.1,1999.7,2002.7,2002.9,2003.9,2002.5,2002.5,2000.4,2002.4,2000.2,2001,2000.6,1999.1,2004.1,2003.1,2004.1,2004.3,2006.2,2009,2008.5,2009.4,2008.8,2006.5,2005,2003.2,2002.3,2003.8,2003.6,2003.2,2004.2,2005.2,2004.8,2003.3,2003.5,2003.5,2003.5,2004.7,2004.7,2004.6,2004.6,2003.8,2003.7,2004,2003.5,2002.5,2004.6,2005.7,2005.1,2004,2005,2005.2,2005.4,2006.6,2008.6,2008.6,2008.6,2007.3,2006.5,2006.5,2007,2006.5,2007,2004.6,2003.5,2002.6,2005.4,2005,2006.4,1995.8,1998.4,1997.9,1998.3,1999.7,2000.3,2000.8,2002.6,2002.6,2001.7,2000.5,2000.6,1998.5,1997,1996.3,1995.9,1996.8,1998.1,1996.7,1993.1,1993.4,1994,1994,1993.6,1994.3,1992.5,1993.3,1993.3,1991.6,1992.2,1992.4,1996.3,1996.6,1997.2,1997.5,2000.9,2001.1,1999.6,1999.5,2001.5,2003,2003.6,2004.5,2003.1,2002.5,2004,2004.4,2007,2012,2011.3,2011.5,2011.1,2010.2,2009.1,2009.4,2009.2,2009.6,2011.5,2011.8,2010.9,2009.6,2009.8,2009.2,2010,2011.6,2010.9,2011.4,2011.1,2010.2,2010,2009.8,2011.4,2011,2011,2010.5,2009.9,2010.1,2009.9,2010.4,2010.8,2010.3,2010,2009.5,2010.8,2011.5,2011.9,2012,2013.3,2012.4,2010.5,2009.9,2005.7,2009.3,2008.3,2008,2002.3,2003,2010,2008.2,2008.5,2005.8,2005.1,2005.6,2007.1,2008.6,2006.4,2006,2004.4,2003.6,2003.5,2003.8,2002.7,2004.8,2005.8,2006.5,2007,2007.3,2007.2,2007.1,2007.1,2006.7,2005.2,2006.3,2006.2,2006.5,2006.4,2006.7,2007.5,2007.1,2008.5,2007.5,2007.2,2007.3,2006.2,2006.2,2006.8,2006.5,2006.2,2006.8,2004.3,2005.4,2003.1,2002.3,1999.5,1995.6,1996.3,1997.6,1997.8,1999.3,1998.8,1999.6,1999.9,2003.2,2007.3,2006.6,2006.9,2007.9,2008.8,2008.8,2007.9,2007.6,2008.2,2008.4,2010,2011,2012.1,2012.6,2013.8,2013.7,2012.6,2012.8,2012.5,2013.2,2013.3,2013.1,2013.3,2013.6,2015,2015.1,2015.1,2015.6,2015.6,2013.5,2012.1,2012.4,2011.1,2011.5,2011.2,2012.2,2012.4,2012.6,2013.3,2014.3,2013.3,2013.7,2014,2014,2015.6,2017.3,2018,2018.5,2020.4,2019.6,2016.6,2014.6,2014.6,2015.2,2015,2016.4,2015.1,2015.2,2015.3,2015.5,2015.6,2012,2012.1,2012.8,2012.9,2014.6,2016,2017.1,2016.6,2017,2016.2,2016.4,2016.8,2013.2,2012.8,2013.3,2013.1,2013.8,2012.6,2012.4,2013.1,2013,2013,2008,2007.8,2006.2,2006.5,2004.5,2004.5,2008,2010.1,2009.8,2012.2,2012.8,2012.5,2011.3,2011.5,2010.1,2009.5,2009.5,2010,2011.5,2007.3,2005.1,2006.1,2005.3,2005.4,2005.5,2006.5,2006.6,2006.8,2006.2,2005.6,2005.5,2004.2,2005.2,2004.2,2005.6,2006.1,2005.8,2005.2,2005.1,2004.6,2001.7,2000.7,2002,2005,2005.4,2005.9,2006.3,2007.3,2009.9,2010.6,2009.8,2010.1,2010.5,2009.1,2008.3,2008,2008.3,2009,2011,2011.7,2012.3,2010.3,2011,2010.3,2010.3,2010.7,2010.7,2008.1,2005.4,2004,2002,2003.5,2004.9,2005.7,2006.2,2005.2,2004.5,2005.2,2006.1,2005.8,2005,2005,2005.4,2005.5,2005.8,2005.9,2006.2,2006.2,2006.1,2004.3,2004.8,2004.9,2004.6,2003.4,2003.5,2004,2003.1,2002.6,2001,1998.2,1996.3,1993.8,1993.5,1981.6,1978.5,1983.3,1995,1990.5,1991.2,1990.7,1989.8,1991.5,1988.1,1986.3,1988.3,1991.1,1991.6,1991.8,1990.5,1989.9,1989.4,1989.1,1990.1,1990.5,1989.4,1989.5,1988.5,1987.5,1986.6,1985.6,1983.1,1985,1985.5,1983.9,1982.6,1982.9,1984.9,1985,1988.7,1986.7,1987.4,1987.7,1989.6,1991.2,1988.2,1989.9,1990.1,1989.7,1991.3,1991.1,1991.5,1992,1993.6,1994.5,1996.2,1999,1995.3,1994.5,1994.2,1993.7,1993.8,1993.9,1994,1991.2,1990.4,1990,1989,1984.1,1983.5,1986.9,1987.5,1987.7,1990.6,1991.6,1992.7,1995.6,1996.1,1996.8,2002.5,2001.2,2000.1,1999.5,1999.1,1999.1,1998.4,1998.1,1995,1992.3,1993.5,1993.5,1994.6,1995.2,1996,1996.4,1998,1997.2,1997.2,1996.1,1996.2,1994.1,1994.1,1996.6,1998.2,1998,1999.5,1990.1,1992.1,1992.7,1992.5,1992.7,1995.6,1996,1996.3,1996.3,1993.2,1992.8,1992.1,1991.5,1991.6,1990.3,1990.2,1991.2,1992.4,1993.1,1992.5,1993,1993.2,1995,1994.9,1995.1,1993.7,1993.7,1993,1993.6,1993.5,1993.6,1993.1,1992.2,1993.8,1994.7,1994.5,1995.5,1994.5,1993.9,1992.6,1992.8,1993.7,1993.5,1992.3,1992.8,1990.3,1991.2,1993.7,1994.3,1992.3,1992,1992.5,1992.5,1993.4,1992.4,1990.3,1985.7,1987.6,1987.6,1988.3,1988.5,1987.5,1988.6,1988.6,1988.4,1988.7,1988.2,1988.5,1986.5,1987.1,1987.6,1986.7,1986.1,1986.5,1988.2,1986.3,1986.8,1986.5,1986.2,1986.1,1984.5,1985.6,1986,1985.5,1986.5,1988.5,1987,1986.8,1985.9,1985.9,1980.8,1979.5,1979.6,1976.1,1977.5,1975.5,1976.8,1976.5,1965.3,1966.1,1967.5,1963.2,1963.6,1966.2,1965.1,1964,1962.7,1962.3,1962.2,1961.8,1963.5,1963,1958.1,1958.5,1958.7,1958.3,1958.2,1959,1959.9,1961,1960.4,1960.6,1959,1956.3,1955.4,1955.6,1952.2,1953.3,1953.8,1954.2,1954.8,1952.1,1953.5,1953,1953,1950.7,1945.7,1939,1935.4,1939.1,1927.5,1932.3,1938.7,1928.1,1927.3,1935.1,1941.5,1936.5,1936.6,1934.2,1935.2,1936.6,1936.6,1935.3,1931.7,1932.2,1933,1930.4,1928.7,1926.1,1922.4,1919.4,1915.7,1917.2,1918.6,1921.5,1919.5,1920.9,1924.4,1924.6,1925.8,1923.5,1922.3,1921.3,1921.6,1922.8,1924.1,1925.5,1930.6,1933.9,1936.7,1935.8,1936.2,1937.6,1941.3,1940.3,1937.4,1936.2,1937.4,1937.2,1937.7,1938.2,1941.1,1942.1,1941.7,1943.5,1939.2,1938.2,1938.8,1935.1,1933.4,1933.5,1932.6,1933.5,1930.2,1925,1923.1,1924.5,1924.4,1926.5,1925.1,1924.5,1926.3,1918.6,1919.4,1923.5,1923.6,1925,1926.5,1926.8,1922.5,1924.2,1925.2,1924,1927.1,1929.5,1928.1,1928.1,1925.2,1923.4,1923.2,1921.6,1921.1,1921.7,1920.7,1918.4,1922.5,1921.3,1922.5,1924.5,1923.3,1919,1915.7,1918.6,1919.1,1911.5,1913.1,1912.5,1912.5,1915.8,1918,1918.1,1918.8,1924.1,1924.1,1919.3,1919.6,1920.5,1918.5,1917.6,1916.6,1915.2,1913.5,1914.8,1914.4,1912.8,1912,1907.8,1906.7,1908.9,1906.9,1904,1903.8,1908.1,1909,1909.6,1909.1,1908.7,1905,1904.6,1906.3,1906.8,1910.6,1914.5,1915.9,1922.3,1923.1,1925,1926.4,1927.5,1928.8,1935.5,1935.7,1936.3,1926.8,1932.1,1929.1,1929.3,1930.6,1927.5,1925,1926.3,1927.5,1927.7,1927.5,1927.5,1927.7,1926.6,1926.5,1928.5,1928.3,1930.2,1928.8,1929,1929.2,1930.1,1928.8,1929.3,1929.1,1929.2,1929.6,1931,1931.8,1931.2,1928.5,1926.5,1927.3,1928.5,1928.1,1929.2,1929.2,1929.3,1929.8,1929.3,1929.5,1929.2,1928.4,1930.5,1927.2,1927.8,1928.9,1930,1930,1920,1924.6,1926.3,1925,1922.9,1920.2,1921.5,1920.8,1922,1922.2,1922,1922.2,1921.1,1915,1913.3,1912.9,1912.6,1914.4,1914.7,1914.7,1912,1910.6,1911.2,1910.4,1907.8,1906.6,1906.5,1905.4,1904.5,1904.5,1901.3,1905.3,1904.6,1902.3,1899.1,1895.4,1894.5,1896,1892.3,1896.4,1902.2,1901.7,1897,1895,1888.2,1879,1875.1,1882,1893,1886.2,1885.6,1885.6,1887.3,1887.3,1888.2,1893,1896.1,1898,1898.3,1895.8,1895.1,1894,1895.6,1903.7,1898.2,1897.2,1895.7,1895.1,1894.1,1890.4,1889.9,1891.1,1891,1890.6,1891.2,1888.8,1890.9,1891,1890.2,1893,1891.6,1895.1,1892.2,1891.5,1892.1,1891.8,1890.8,1890.5,1888.4,1885,1883.8,1883.1,1884,1882,1885,1882,1882.7,1884.5,1886.4,1887.6,1887.5,1889.1,1891.1,1890.8,1893.4,1892.3,1884.5,1884.6,1882.6,1880.5,1872.5,1873.2,1867.2,1871.4,1872.1,1870,1869,1869.8,1872.5,1870.7,1871.1,1869.9,1868.8,1866.2,1868.5,1861.6,1861.2,1861.8,1850.9,1850,1851.5,1845.8,1845.5,1846.1,1850.3,1857,1853.4,1851.9,1849.5,1848.3,1852.6,1847,1844,1839.5,1837,1837.1,1837.6,1835.5,1838.3,1836.4,1838.6,1840.2,1838.3,1832.2,1833.2,1835.5,1832.5,1828,1828.5,1828.2,1837.1,1835.6,1833,1835.3,1836.1,1834.6,1833,1831.2,1831.5,1829,1826.1,1824.9,1822.9,1821.8,1820.2,1820.8,1821.6,1822.3,1833.3,1837.2,1840.7,1841.2,1842.6,1843.3,1850,1850.2,1848.1,1847.5,1847.6,1849.1,1854,1850,1852,1845.6,1844,1842.7,1833.8,1831.1,1830.2,1826.1,1827.9,1825.5,1824.7,1825.5,1826.1,1826.4,1822.4,1822.3,1824.1,1827.5,1826.5,1824.3,1824.2,1824.4,1825,1828.3,1832.2,1833.6,1832.5,1831.2,1831.8,1834.1,1836.4,1833.7,1834,1834,1834.2,1831.4,1830,1830,1830.5,1829.2,1826.7,1827.1,1827.3,1830.6,1829.4,1828,1831.4,1832.3,1832,1835,1835.2,1832,1835,1837.2,1841.5,1842.2,1843.3,1843,1847.2,1852.5,1852.8,1853.3,1851.5,1851.5,1849.2,1848.2,1846.5,1846.7,1846.6,1847.5,1844.3,1843.9,1841.7,1840.6,1838.8,1835.9,1835.6,1835,1834.6,1837.2,1836.2,1836,1836.7,1838.2,1841.5,1841.6,1837.3,1830.8,1832,1831.6,1831.1,1831.7,1833,1831.3,1832.3,1831.3,1833.4,1832,1827.8,1825.1,1811.1,1811.1,1802,1799.7,1796.3,1796.3,1804,1808.2,1809.3,1813.2,1811.2,1809.7,1808.2,1808.8,1805,1803.8,1806.5,1808.7,1808.6,1811.5,1811.1,1810.3,1811.1,1811.1,1817,1816.6,1820.3,1820.9,1821.5,1818.1,1817.3,1819.1,1821.3,1822.3,1828.1,1829.1,1826.5,1826.1,1826.3,1824.2,1823.5,1827.1,1825.5,1825.6,1827.5,1826.3,1827,1823.4,1820.5,1821.2,1824,1815,1822.1,1822,1819.6,1819.1,1823,1822.7,1821.3,1822.7,1822.3,1822.5,1821.6,1820.5,1820.9,1822.1,1821.7,1822.7,1823.8,1823.6,1822.1,1822.1,1822.5,1820.3,1820.6,1819.2,1814.2,1815.4,1816,1816,1819,1823.6,1834.4,1837.7,1838,1837,1836.5,1837,1838.2,1838.9,1835.5,1837.2,1843.9,1844.1,1845.1,1845.1,1847.1,1845.6,1847,1851,1846.3,1849.6,1848.5,1846.4,1847.7,1847.9,1848.8,1851.2,1853,1853.5,1856.4,1855,1855.7,1855.1,1855,1852.5,1853.2,1853.7,1854.3,1860.6,1861.6,1862.2,1862.1,1862.5,1864.4,1864.6,1865.2,1868.7,1869.3,1872.2,1875,1878.4,1879,1878.6,1878.6,1878.1,1879.2,1878.8,1879.2,1879.8,1880.9,1883.7,1885.4,1886.5,1886.5,1888.5,1891.4,1887.9,1884.8,1891.2,1890.9,1890.6,1887.6,1882.2,1883.5,1880.7,1881.4,1883.7,1883.7,1882.2,1882.6,1882.6,1884.5,1887.3,1883,1883.3,1884.5,1884.4,1884.6,1884.2,1882.7,1881.9,1883,1882,1883.7,1884,1883.9,1883.7,1882.5,1880.3,1880.5,1877.3,1877.9,1876,1877,1873.6,1873.5,1874.5,1874.6,1873.1,1871.7,1866.8,1867.3,1869.2,1866,1869.3,1869.5,1875,1881.9,1886.8,1886.8,1889.2,1889.3,1885.9,1885,1885.4,1890.8,1894,1899.5,1898.7,1897.1,1897.2,1896.5,1896.5,1895.7,1896.6,1897.2,1899.1,1901.1,1901.2,1896.5,1897.7,1899,1900.1,1901.1,1902.2,1903,1903.5,1904.7,1907.8,1909.1,1911.2,1914,1915,1917.7,1918.5,1918.8,1918.5,1919.7,1919.3,1919.2,1916.5,1917.4,1918.2,1919.3,1914.8,1914,1916.1,1919.4,1917.7,1916,1916,1917.6,1919.2,1913.2,1912.4,1911,1914.3,1913.3,1915.6,1915.2,1915.6,1917.8,1919.6,1923,1921,1921,1921.2,1920.1,1917,1915.3,1915.2,1916.6,1916,1917.3,1918.3,1917,1916.3,1917.7,1918,1918.1,1920.2,1921.4,1919.1,1919.1,1920.6,1920.9,1921.1,1921.5,1920.2,1922.1,1917.4,1918,1920.4,1921.8,1925,1933.1,1935.3,1934.7,1935.2,1932.3,1932.4,1931,1926.7,1922,1918.8,1920,1921.2,1922.6,1924.1,1926.3,1927.3,1926.5,1925.8,1928,1927.7,1926.8,1927,1927.1,1927.8,1928.5,1927.5,1928.3,1925.5,1926.5,1927.9,1927.1,1927,1926.2,1923.1,1920.3,1919.6,1920.8,1920.5,1918,1915.8,1915.9,1917,1910.1,1910.1,1911.6,1908,1907.4,1911,1913.8,1913.3,1914.5,1914.8,1915.1,1915.6,1908.2,1903.3,1905.4,1906.8,1905.8,1905,1907.2,1910.9,1911.5,1911.8,1916.5,1918.2,1915.9,1915.7,1916,1911.5,1908.4,1907,1908.5,1907.5,1905.5,1905.6,1906,1908.6,1908,1906.3,1906,1911.3,1911.6,1907.1,1903.5,1903.1,1904.6,1904.8,1905.5,1904,1904,1901.3,1899.2,1897.3,1894.8,1895.6,1899,1896,1893.5,1895,1894.6,1894.4,1890.8,1891,1889.1,1890,1889.9,1888.2,1888.2,1891,1891.8,1893.4,1895.6,1902.3,1904.6,1908.2,1909.2,1908.7,1907.6,1908,1908.3,1906.1,1903,1903.2,1903.4,1903.6,1904.3,1904.4,1904,1906.2,1903.5,1905.5,1908.4,1908.4,1906.1,1908.1,1905.3,1904.2,1906,1905.2,1906.8,1906.9,1906.8,1905.2,1896,1893.2,1890.1,1895.2,1896,1897.5,1896.6,1891.3,1891,1891.2,1893.1,1892.8,1898.1,1904.2,1910.5,1910.7,1912.6,1912.7,1913,1912.5,1911.3,1910.5,1913,1916.1,1914.5,1915.4,1916.5,1917.4,1921.1,1923.1,1925.5,1925,1925.7,1928.8,1926.3,1926.7,1926.7,1926.2,1927,1928.4,1927.8,1927.5,1929.5,1929.7,1932.2,1930.9,1929.5,1929.5,1929.5,1928.1,1928.3,1928.6,1932,1930.8,1930.3,1930.6,1936.1,1925.2,1924.1,1925.9,1925.1,1927.4,1928,1926.2,1925.7,1931.3,1931.5,1928.2,1928,1928.1,1928.5,1930.5,1929.5,1929.5,1931,1928.3,1928.6,1928.3,1925.5,1927.3,1928,1928.8,1926.9,1927,1927.7,1927.3,1927.9,1931.1,1933.3,1928,1924.3,1920.6,1921.4,1920.5,1919.1,1921.4,1919.2,1921,1918,1920.7,1924,1921.6,1922.5,1925.1,1923,1923,1923.4,1922.6,1920.1,1924.1,1931.4,1938.5,1940,1945.3,1942.3,1942.2,1942.4,1937.9,1938.3,1939.7,1941,1937.1,1937.9,1939,1940,1941,1942.3,1941.3,1942.1,1944,1944.2,1940.3,1940.2,1941,1940.3,1942.7,1942.1,1941.1,1941.5,1936.5,1936.7,1937.2,1938,1936.1,1933.3,1932.6,1932.1,1934.1,1936.2,1940,1941.3,1943.1,1943.1,1943.2,1944.8,1938.5,1936.5,1936.5,1937.1,1937.7,1935.2,1936,1936.7,1938.2,1937.5,1937.6,1938.4,1938.5,1938.8,1939.3,1940,1938.2,1938.9,1939.1,1939.6,1939,1939.9,1940.3,1941.7,1942.3,1940.8,1941.1,1938.2,1937.3,1933.2,1933,1933.5,1927.8,1923.3,1924,1923.6,1923.3,1918.8,1913.2,1912.5,1912.2,1910.2,1907.9,1901.1,1900.5,1904.5,1902.5,1900.9,1902.2,1902.3,1902.6,1903.1,1903.1,1895.5,1894.1,1894.3,1907.3,1901.1,1901.8,1903.5,1903.2,1904.2,1903.6,1905.3,1905.4,1906,1904.5,1902.1,1895,1896,1895.8,1889.3,1887.4,1890.8,1891.2,1891.6,1891.5,1891.4,1889.2,1887.5,1886.4,1888.5,1885.1,1881,1880.6,1883.3,1875.8,1875,1875.5,1870.6,1868,1871.7,1878.8,1879.3,1879.1,1879.7,1881.6,1882.7,1877.9,1876.7,1877,1881.4,1881.3,1880.6,1881,1881,1881.3,1879.3,1875.2,1875.8,1875.5,1874.6,1874.5,1874.5,1873.3,1874.2,1872.2,1872.5,1874.3,1875.5,1874.6,1875.2,1874.3,1875.5,1876.6,1876.6,1875.2,1876.1,1878.5,1883.5,1883.3,1881,1882.3,1883.1,1882.7,1882.6,1883.7,1875,1870.9,1872.3,1875,1880,1878.5,1880.2,1880,1879.5,1879.1,1879.2,1878.3,1880,1881.7,1885.7,1888.3,1887.5,1888.9,1892.6,1893.6,1894.1,1893,1888.6,1888.1,1888.4,1883.1,1882.3,1884.1,1883.8,1884.1,1883.1,1883,1882.6,1880,1879.4,1874.6,1873.8,1874,1872.2,1874.5,1875.1,1875.5,1874,1873.2,1868.2,1869.7,1866.3,1866.9,1864,1867,1869.1,1868.6,1869.1,1874,1875.5,1878,1876.6,1877.1,1876,1872.5,1872.3,1871.3,1871.4,1873.5,1873.9,1874.5,1874.5,1874.8,1875.6,1877.1,1876.2,1868.3,1869,1870.5,1870.1,1869.8,1870.1,1868.5,1867.6,1868,1867.5,1868.5,1870.9,1870.6,1873.1,1871,1871.7,1873.9,1875.4,1871.2,1871.3,1870.1,1870.6,1871.2,1871,1869.5,1869,1872.6,1872.6,1873.6,1875.3,1876,1880.9,1887,1888.1,1887.9,1890.1,1887.6,1888.2,1893.8,1895.6,1894.7,1893.6,1893.8,1891.6,1891.1,1891.8,1891.6,1888.6,1888.7,1889.5,1889.8,1890.4,1890.6,1889.4,1890.6,1890.8,1892,1892.9,1891.6,1891.5,1890,1888.8,1889.7,1889.7,1890,1891.1,1890.5,1890.6,1891,1891.9,1892.2,1893.2,1893.7,1895.8,1899.1,1900.2,1898,1893,1891.8,1890.9,1891.1,1882.1,1884,1879.3,1877.7,1878.8,1872.3,1872,1873.5,1874.3,1874.5,1875.5,1874.6,1873.2,1877,1874.6,1874.1,1875.9,1876.2,1876.4,1877,1876.4,1878.9,1880.6,1880.7,1882.1,1881.7,1884,1886,1885.6,1889,1894,1903.3,1908.1,1908.2,1908.5,1915.4,1918.4,1915.8,1916.3,1918.2,1920.5,1920.5,1920.6,1916,1917.2,1919.5,1926.1,1928.1,1934.2,1943,1944.6,1945.5,1947,1941,1938,1932.3,1934.6,1937.5,1938.1,1938.4,1940.5,1941.5,1940.1,1946,1943.5,1946.3,1947.2,1945.3,1945.1,1937.6,1938.7,1938.5,1935.5,1936.2,1938.3,1941.7,1942.5,1941.2,1940.3,1938.8,1943.8,1941.2,1941.4,1939.1,1941.4,1940.6,1939.2,1939.2,1939.8,1938.2,1936.3,1937.3,1942,1942.2,1941.7,1940,1941.3,1943,1943.5,1947,1947,1946.4,1946.8,1950.7,1950.5,1951.2,1955.8,1954.1,1950,1949.1,1948.7,1951.2,1951.7,1951.3,1951.1,1951.5,1951.6,1952.9,1953.1,1952,1951.5,1953,1953.1,1952.6,1952.3,1952,1952.4,1952.3,1952.7,1950.5,1944.2,1941.5,1936,1940.5,1942.1,1942.5,1941.5,1940.1,1941.2,1931.4,1929.8,1935.5,1941.2,1940.4,1939.8,1941.5,1939.9,1940.5,1939.8,1937.9,1938.5,1942.1,1939,1940.1,1943,1946.1,1946.9,1944.8,1944.1,1943.7,1942.1,1940.6,1941.5,1937.1,1937.6,1937.4,1935.7,1936.3,1936.7,1937.1,1937,1933.3,1936.1,1937.7,1935.5,1938.3,1939.5,1938.9,1938.6,1940.3,1942.3,1945.6,1944.4,1945.6,1946.4,1951.7,1956.7,1960.2,1962,1957.5,1959.7,1960.5,1960.4,1968.8,1969.5,1976.5,1972,1973.5,1973.5,1972.6,1976.1,1974.2,1975,1974.2,1975.1,1972.7,1970.6,1972.1,1974,1972,1971.3,1971,1971.8,1968.2,1965.6,1966.6,1968.8,1970.2,1970.3,1971,1970.5,1970.6,1970.7,1971.2,1971.6,1972.2,1971.5,1967.6,1967.9,1966.5,1966.5,1967,1969.3,1971.4,1970,1972,1970.5,1969.7,1971.3,1972.4,1970,1972.1,1975,1976.6,1980.8,1975.4,1975.6,1976.4,1973.2,1974.6,1973.5,1974,1972.3,1972,1971.2,1971,1972.9,1973.7,1974.9,1975.2,1974,1974.2,1975.4,1974.9,1976.2,1976.5,1977.3,1976.3,1978.3,1978.5,1977.6,1976.6,1977,1976.2,1974.1,1975.4,1975.6,1975.9,1978,1980,1986.6,1989.6,1989.3,1988.2,1989.5,1991.2,1989.2,1989,1989.6,1990.1,1975.1,1980.8,1982.1,1981.5,1973.5,1971.1,1968,1965.3,1966.5,1967,1966.4,1963.9,1958.3,1958,1958.3,1958.2,1955.5,1953.2,1949,1948,1951.5,1952.1,1953.5,1953.2,1954.6,1958,1958.3,1956.1,1955.4,1956.3,1956.3,1957.1,1958.2,1957.1,1956.8,1959.1,1961.4,1959.1,1952.1,1952.8,1952,1950.3,1950.3,1952.7,1955,1960.2,1960.5,1955.1,1956.1,1952,1954.3,1955.1,1955.5,1960.6,1960,1961.1,1963,1967.2,1968,1975.5,1976.5,1975.7,1975.7,1972.2,1972.2,1973.4,1973.6,1973,1974.7,1975.4,1974.5,1975.1,1974.5,1974.8,1975,1974.7,1976.1,1976.9,1975.3,1975.7,1976.5,1977,1977.5,1978.6,1981.5,1979.2,1973.4,1973.5,1969.8,1970.5,1972,1973.5,1974.5,1976.6,1977.3,1974.4,1975,1977.1,1979,1985.3,1988.1,1985.6,1984.6,1985.7,1987.2,1989.3,1988,1983.8,1985,1986.7,1988.4,1987.3,1987.2,1985.4,1988.1,1989.8,1989.2,1988.7,1989.1,1987.6,1986.2,1985.5,1984.8,1986.5,1986.7,1981,1980.8,1983.2,1982.7,1982.5,1981.6,1980.2,1978.2,1980.8,1983.9,1984.2,1985.7,1983.3,1985.6,1986.5,1984.1,1984.3,1978.3,1972.1,1968.8,1965.5,1963.6,1964.1,1965.1,1966.2,1964,1964.3,1964.5,1963,1965.6,1961.6,1960.2,1958.6,1960,1963.3,1963.5,1962.7,1962.2,1960.3,1960.5,1961,1956.6,1962.6,1960.7,1962.4,1963.9,1962.7,1965.1,1965,1963,1962.9,1963,1962.1,1962.7,1961.6,1962.7,1958.6,1961.5,1962.7,1961.8,1962.1,1962.6,1963.6,1964.1,1965,1963.1,1960.7,1962,1962.2,1961.9,1961,1958,1958,1961,1961,1961,1962.6,1964.9,1964.2,1963.5,1963.9,1964.2,1966.9,1971.7,1974.2,1974.1,1973.3,1975.4,1976.4,1977.1,1976.8,1976.1,1975.3,1975,1974.2,1974,1973.6,1972.6,1974.1,1974.6,1976.2,1972.3,1970.2,1968.9,1971.6,1971.2,1971.5,1971.6,1970.8,1970.7,1970,1970.5,1972.2,1971.5,1970.5,1969,1970.3,1967.3,1961.5,1961.1,1960.1,1961.9,1961.6,1966,1960.9,1962.3,1961.4,1958.2,1961,1962.1,1962.9,1962.9,1963.8,1961.2,1961.3,1962.5,1962.5,1963.8,1963.6,1963.7,1962.5,1962.5,1962.6,1961.5,1959.6,1958.8,1959.1,1958.3,1957,1958.5,1961.6,1962.4,1963.2,1963.7,1974.1,1971.2,1971.6,1971.8,1970.6,1971,1973,1974.2,1974.3,1973.3,1973.5,1974.1,1976.9,1981.2,1981.7,1982,1977.6,1979.2,1975.5,1959,1960.4,1959.5,1958.2,1958.8,1959,1958.5,1959.8,1959.5,1958.9,1951,1952,1950,1946.1,1947.6,1948.3,1948.4,1947.3,1950,1950.6,1949.1,1949.5,1949.1,1950.3,1951.1,1951.5,1947.6,1948.6,1948,1948.6,1948.9,1951.1,1951.6,1950.9,1952.6,1952.5,1952.1,1952.5,1952.1,1954.3,1955.1,1950.2,1947.7,1944.1,1944.3,1943.5,1942,1941.5,1940,1935.9,1937.5,1936.8,1938.2,1939.1,1939.6,1941.3,1939.1,1938.6,1937,1936.8,1936.4,1934.6,1932.7,1931.9,1931.2,1931.6,1935.4,1934.3,1933.9,1935,1937.3,1937.1,1935.6,1935.8,1935.6,1935.5,1938,1935.9,1935.1,1935.1,1936.8,1932.6,1932.6,1932.1,1934.1,1930.7,1927.3,1925.1,1921.5,1922.1,1923.6,1924.1,1918.5,1916.1,1916.1,1919,1924.2,1930.9,1932.5,1935,1935.7,1937.6,1938.3,1938,1939.1,1937.1,1936.6,1936.8,1937.4,1937.3,1936.5,1938.5,1943.3,1945.7,1944.5,1944.5,1942.5,1943.6,1943.8,1942.6,1939.6,1938.5,1939,1940.4,1940.5,1940,1940.7,1941,1941.1,1942.1,1943.3,1943.8,1942.6,1942.5,1940.5,1942.2,1942.7,1942.8,1946.2,1945.1,1945.3,1945.8,1948,1950.2,1944.7,1945.5,1948.1],
      "v": [8494,4042,3823,6524,4191,5486,3491,2638,3511,3882,3257,2972,10478,8922,5216,3335,3109,5109,3691,5472,2678,3306,5486,5402,3907,2628,2661,3915,6785,3413,5020,4193,3060,3562,4250,9031,6726,4483,6472,4276,3366,2777,3898,11539,8832,10204,14248,7392,4562,12729,3350,4897,5385,17924,12111,8029,11361,8635,4478,4132,3079,4988,4578,3479,1923,2336,2321,4119,2084,3797,2357,2200,2311,2349,1243,1006,2591,1476,4629,17836,10412,6349,4512,3978,3077,3660,1936,5628,6605,5384,5297,10201,6272,10338,8812,12867,10286,4962,9389,3671,3083,5601,3326,12101,10149,4973,4735,3864,2554,4448,5067,5276,5855,4290,10515,3824,1978,4096,2164,1563,2410,2052,5320,2874,6323,3122,8999,11598,7706,4649,5248,4741,8659,7102,9884,10630,10437,9186,7922,6441,5889,7309,4986,6969,11153,6877,4864,15468,4633,4704,7892,8333,8007,4967,6893,5443,3188,4355,4585,3463,2062,2967,2284,1653,3109,4154,6903,5815,3018,6248,6838,3509,4957,4893,2595,3154,3117,4901,2873,4550,2868,2621,2815,3560,7177,2947,3954,4196,2462,10375,6390,9440,11371,8203,5716,4331,15303,6301,4656,9264,11240,6845,3551,6421,4841,5707,2917,4073,7490,7323,11803,7429,2741,4142,2685,2645,5071,2516,5444,5633,3047,3735,4954,3266,2636,2668,7244,4031,4379,5328,4470,5112,7810,4673,5065,3714,2957,11403,10550,9929,8706,8625,10349,13672,6232,11553,2529,2709,7828,8302,3823,2668,7341,8184,4064,6493,5597,8740,7672,4301,3803,4769,3353,9690,3550,3461,1695,5004,5643,3979,4594,4704,11012,10007,4862,5774,4469,4480,7230,5462,5321,5601,5926,8403,10400,4824,8316,7634,9505,5757,11589,10962,5115,5462,21818,6279,6850,8375,8255,4642,5428,2394,2978,4759,5272,5968,3636,3488,6477,6943,8030,5262,4635,2984,9351,7060,11729,3804,3739,2521,3584,6562,4283,2269,4102,5045,4489,2808,7175,5247,2983,6300,4430,7076,5849,7299,8915,8460,6581,6188,8620,5285,5892,17874,3344,4671,5691,3978,9150,4877,2339,3282,2195,3091,2052,6784,4778,3548,2636,7620,4730,4829,2562,1619,2817,2471,1777,7784,3825,3229,3239,2107,1546,4046,2266,4916,5938,4244,6420,3266,6359,6053,2793,3797,2343,4103,4135,8954,10499,9669,11600,8121,10376,3781,2402,7038,3836,4361,6090,2910,2641,4674,2615,3731,8840,3542,3298,7445,3871,2843,5798,4926,3370,2486,1814,1216,2288,5017,6281,3862,2450,2119,12112,3538,2056,3259,1621,5560,4726,3443,1928,5865,8026,4453,3714,8881,5374,5605,6621,5848,5503,8625,5366,2491,4727,5163,6727,3125,1909,3643,7376,3578,13537,10902,4825,3423,3275,3587,4188,3512,2185,2703,2463,1139,998,4510,2857,2456,2871,1602,4439,8413,3479,3253,8220,4959,8808,6480,7271,6590,6214,5069,7282,7517,7160,7075,4639,10921,7584,6581,19364,6665,3297,10191,5958,3569,2693,3229,2843,3294,5632,3982,1705,5067,8776,10284,3514,11592,4534,1829,3547,4817,2881,2430,3147,2753,4287,1906,2151,4287,3716,5057,3592,5520,8468,5006,6857,12553,8869,8600,8430,10723,8846,6484,5266,6699,10129,16066,4790,8955,8457,4277,8217,5247,3790,4021,4131,4101,3627,4760,4461,3445,9900,7853,6403,3259,7466,5855,4634,1729,2473,2574,7170,5103,3219,3160,4818,4739,4394,7633,3231,9685,10216,3927,7621,6403,3633,8410,2918,4109,11276,5293,4659,6669,4112,10904,8306,4788,15919,3926,8206,8195,6150,4406,3892,2953,3816,4222,2637,5235,1507,2456,1029,936,1668,1779,2081,3830,3753,2009,1840,1470,2150,1180,3127,2021,1105,1869,3872,2122,8151,2066,3478,3109,2975,3452,8896,5459,8274,4853,2411,6269,5826,4795,6773,4891,6057,16548,4163,4780,10916,5449,7791,6066,3233,1808,3695,3247,2928,1933,4039,2203,2303,4186,2419,2292,2449,2401,2210,1477,2907,2367,988,2230,1042,1750,1552,7892,3203,2661,2020,3004,4494,3313,5356,3154,1836,1666,6919,5477,6079,4315,9218,8895,6506,6840,11222,3444,5333,4151,1869,2310,2616,5222,3473,3019,3315,1950,2733,1505,930,2723,1895,4160,5116,3973,2061,2493,2428,1713,2793,2157,2795,1260,1283,992,3065,5394,6335,6033,4608,6796,7290,5697,3492,9518,4457,5113,8780,7953,7748,8641,10822,7039,7062,13524,5294,2599,3074,8000,9763,4722,10281,9347,8025,5832,2646,3534,5824,4775,7012,4804,6045,3373,2051,2117,4449,2266,1919,1797,6292,3162,2641,2574,1334,5397,4875,3143,8787,4975,8656,6427,6017,6539,6860,6136,3035,7432,7257,7143,5339,6147,8909,5976,7047,3170,4029,7166,4082,3962,5704,3683,3998,7955,4215,7766,12530,8142,6450,5250,4764,3861,4130,3630,3551,2092,2345,2590,2618,3928,5451,6307,5117,4827,3620,3528,4080,3405,2838,4789,2155,1948,3093,9599,3995,4187,5653,3095,5738,14419,9783,11988,7361,23109,6789,7111,6493,6600,6405,10300,7782,3167,2756,2828,5760,4015,4273,3793,2326,8529,9344,7637,3929,3400,7240,4384,3820,2861,2064,2514,2585,3858,2847,5683,9000,5264,6474,6764,12080,6090,5440,4452,5031,8551,5420,5718,4215,4079,8459,6458,6656,6753,14260,4706,5680,8860,10512,4077,5796,3987,2512,4825,6783,7534,4081,5352,3969,2574,6592,3190,2653,1846,2010,6135,2187,1975,4398,2147,1838,1452,1190,7381,7901,5347,5048,4628,2729,3661,7434,4615,5203,3753,3721,4549,7228,7327,7988,9844,11754,12969,4785,13525,6183,7676,5910,4167,4410,3683,7802,6110,6164,5150,4215,3953,2785,2154,1728,2655,1085,4157,1820,1492,2260,1588,3632,2833,2573,4575,1159,829,3189,4356,2920,7777,5652,2556,2666,3147,3082,3673,2895,2465,2600,9937,7871,10287,5276,10141,9756,5996,11435,2563,4934,5789,3569,3324,2433,3032,7801,4554,4352,3102,5586,1465,4291,1886,1258,1743,1233,3682,3226,3703,2295,875,1485,575,1089,2432,1407,3332,6959,8636,10506,3992,7248,8193,4077,3481,6457,3692,5455,6474,6929,10694,6228,6747,8452,5850,5496,16527,2803,3701,5299,2138,2783,2435,1228,1222,6955,1640,1502,7434,5350,2966,1853,2190,3693,3803,4339,3017,2863,3757,2208,3352,7318,6591,2423,1458,3136,5587,6233,4254,6115,5611,7592,5096,3194,6124,8193,4684,5740,5310,6587,3407,7288,5208,5076,4550,12828,3547,2581,5373,6136,2751,3726,4659,2340,1848,1646,1839,2706,1455,1989,1243,797,2943,2045,5518,3672,2693,3157,3236,1330,1937,2518,1008,2046,2557,3458,2122,1670,3388,2294,5727,4751,5633,2460,3585,2349,4564,6357,4942,5091,5336,4568,4215,4547,8135,2280,1749,3414,1860,4246,1518,2617,1511,1394,3698,4208,1906,1076,1041,1487,973,2698,1540,1702,10792,4809,3135,2252,1855,2197,2047,832,1070,1326,2682,1254,1582,7843,3337,3470,4003,4751,2389,3532,5092,4724,5375,8004,4226,6740,5323,3661,3186,10962,6472,6249,13866,6187,11640,6426,4401,6216,3359,10073,6895,4760,7897,4732,8287,5909,5511,3244,3757,2658,5204,5557,1457,1781,1464,1561,1891,827,1879,4707,1840,3416,1907,1178,4969,5731,2308,6385,3457,3313,3247,8315,4108,7011,10551,7538,4083,5052,12005,4057,2871,6506,4738,5049,3286,3799,2182,5185,1888,1645,2390,1685,2623,2618,3970,7991,11126,4478,2007,1794,5130,4202,6232,6116,6518,7478,3972,3882,3090,3739,2407,3567,2570,2115,1986,1959,1732,3679,3145,2628,2484,2240,3577,5968,6805,5306,5399,9512,5738,7342,6056,3838,3601,2093,2103,1434,4375,7554,6295,5446,1303,5577,6805,4463,2262,1274,1603,4138,3558,1583,1668,7856,2845,1496,1292,1869,3957,4539,2793,2460,5537,3905,1592,3587,2913,3010,2119,2615,2500,8665,8442,5013,6704,8123,10154,6046,11328,5230,3837,4204,5943,3928,7189,7210,5699,8137,3595,2551,1753,2528,1232,2284,2222,2376,2199,2338,8424,6714,2559,4336,4336,2601,3463,4445,6862,5038,6219,4118,11313,8980,6517,14198,10943,16508,9846,7901,11730,10722,14688,9217,5277,11581,11823,10597,5778,11613,7848,7071,4884,5627,3719,6948,4110,6395,3481,4800,2194,3359,9794,7247,8624,6241,2954,12926,6064,6059,6729,3560,1795,2483,3854,1743,2283,1274,1880,6849,9092,4424,8798,16669,11655,9260,10562,9575,8884,6461,13887,13661,8513,10011,14153,11541,11655,5066,8639,2564,7128,9522,5325,2768,2931,6261,7247,4200,1897,4210,7273,4487,3330,4371,2596,2266,6021,1759,2684,2202,1824,2795,3633,5092,4028,3630,4421,5214,4698,6037,6317,2832,2956,4993,11166,8391,7269,6757,9361,11281,5454,5619,9903,7811,6261,6384,5467,11557,4824,3682,6265,4024,3227,4812,1813,2050,2201,2229,1582,1100,2301,5411,4500,3484,2661,2956,7740,8267,11583,9328,7553,6489,6318,5618,3368,3674,1792,8146,8263,3494,5604,5487,4114,5812,4982,4694,4825,5923,4376,5705,5731,4801,9792,6748,7289,4165,7051,8367,3735,4957,3453,2571,2310,3187,5948,4504,2900,4766,2819,6988,3077,1841,1942,3343,3159,1790,768,1551,1870,1961,2219,1599,1592,1055,1060,1212,3875,6025,3122,2588,2552,1317,3063,6285,4417,7198,3263,3970,2753,5252,4200,5524,11865,5302,4542,15618,2624,3629,7156,3723,5789,3375,5346,2296,2107,4647,3294,3128,3951,2122,1149,6271,2540,3851,4587,3734,1272,3730,4241,8257,5999,3703,2728,2940,1595,4454,9007,3918,4911,4455,5951,5232,8780,6574,10250,4069,6095,5580,6348,4266,11922,8645,7220,4334,8129,5454,4971,5060,5105,4585,4758,7425,4381,4616,3633,2717,2547,5067,3615,2716,1475,1845,4886,4998,5469,4937,6644,4548,2243,4142,5551,2641,2650,2178,3827,1531,1838,1505,2144,3136,4257,5833,11656,7495,8402,12599,11612,8005,5537,10082,6188,5607,6817,12127,3899,2990,5555,2104,3602,1814,1691,7810,3175,2653,2271,2718,4781,4709,3275,2397,1633,4151,2153,3539,1930,2551,1865,1634,1392,1173,4923,1866,1567,1589,6367,7200,3527,4616,5431,5518,2946,5570,4750,6456,9744,11690,7146,6397,6436,5906,8819,4063,7202,4285,2991,3472,9417,5509,3191,4202,4283,3049,2362,2418,3351,7781,4310,2642,3865,2492,5116,7168,9993,6599,2080,2800,5963,2843,1939,2725,1434,2054,3454,14133,8118,9673,5462,9475,4729,6364,6277,4492,4290,2802,16162,7761,3934,7346,7811,10193,4680,8454,2907,3036,4531,3987,4031,2322,2869,3815,2098,2071,2658,1298,1198,1016,1858,1615,3282,1149,1031,1234,3109,1118,1705,2132,2872,2189,1382,1147,986,2898,8469,6507,8683,5234,5285,3650,8125,5966,4710,5025,4515,5133,15185,11047,6987,6914,11027,5567,4600,1517,1798,3770,3066,2694,5745,3125,4817,4618,3165,3294,1535,3352,1724,1668,1791,1751,2006,1300,1778,3464,1818,2347,3454,2780,1551,1876,1775,719,2870,2796,6079,5462,6022,11615,5233,10264,6269,4644,7834,4823,5345,5864,6340,7855,11911,10853,6518,7233,1732,2761,4421,4620,4390,3328,2598,2937,2279,1732,2194,1283,1923,969,1727,2204,1548,1145,710,2535,2048,2140,1347,1395,2506,5107,6215,5685,5416,6178,3201,2613,3287,2935,2300,2503,10682,8552,13424,12785,9110,9294,8858,8634,7351,8911,6233,4186,7898,1513,5223,6525,4084,3024,6151,7091,4752,3358,4200,2290,4755,2244,1910,3481,2470,3199,2487,7278,2472,5333,2430,2113,5536,2588,4318,2946,2785,3439,5059,2859,3867,4184,3596,7777,11300,5277,5091,9579,6011,10771,10503,9991,6336,9727,10629,5755,7896,7567,1456,1215,3549,2316,3514,11210,10425,5390,6098,6077,5653,4425,3556,4240,3097,2852,3781,8654,3449,3580,2996,7664,4654,6284,3342,1615,1893,3698,4617,3473,6103,11582,5780,4057,7043,8661,4036,3573,4474,4541,3190,2486,5272,4706,11033,6913,10840,6427,7292,1719,1835,3308,5861,2780,3135,4953,4075,4525,3562,1360,2566,4338,6148,2054,939,1623,3654,1462,2624,1735,1466,1451,1132,2026,1309,3486,2135,1610,15573,9447,5033,3516,3813,3413,5454,2317,5500,2587,3194,2261,5682,4194,7937,5092,8063,7492,5228,8951,4469,3029,4001,2508,2941,1335,7747,3476,2716,1619,2821,2527,1117,2687,2651,2082,1804,6601,5933,1861,2183,1828,2321,1936,687,3545,2420,2132,6801,4114,2929,1777,2941,2898,3547,5047,3407,3208,8068,6968,7366,7200,6857,3586,8812,10527,8387,5909,5815,3678,2556,7045,3484,8240,6543,3260,3365,3514,3884,3656,3696,3483,2218,2116,1732,1175,7006,2526,2567,1996,1236,6091,3142,1733,1513,1130,1694,10366,6666,5940,4181,2443,5033,4164,3025,9668,15950,5551,7775,8849,4553,5779,3736,12048,8997,5646,4645,8270,2153,4099,2702,6128,6934,3781,3768,1994,3899,2343,1489,2574,2260,2102,1785,5416,1779,1062,1119,5181,3374,2294,4104,6706,6527,5616,6469,7046,8138,12868,10818,6884,8026,8396,7941,11155,6420,7112,5178,4139,9119,12199,5229,5554,6109,12408,6626,6407,13497,2585,2330,4704,4495,2886,2592,2156,4349,1953,1070,2143,3316,1580,1116,1593,2734,3040,1940,2008,2509,1763,4218,4173,4546,3411,2699,2340,2187,3578,5590,2461,5439,5187,2715,2078,3114,4513,3807,3733,2231,3109,3828,3654,2780,7994,8724,6368,3407,10911,4825,2225,7197,3489,3223,8521,2994,3225,2198,1466,2260,3985,2137,3332,1553,2695,4358,3699,2609,1678,4385,5534,2650,5589,3813,3540,3068,11774,6037,9901,9740,3895,6951,8338,7211,3835,3949,6423,4580,4968,3890,7509,4893,5961,7324,6745,6697,5244,8702,4407,3788,6699,4738,1661,2842,2197,4503,2501,1284,3177,1708,1006,7241,2485,1362,1462,1619,1340,819,3612,1696,1942,822,1318,1077,2864,2725,1413,4496,3647,4872,5696,5597,3379,3174,3823,3358,1958,4005,3588,4628,2257,4335,6979,6465,5711,5136,5081,1738,2567,4089,2590,1703,2484,2633,3368,8105,1989,1567,1966,3396,2182,1634,3533,2108,1425,1527,1912,2734,1311,535,1122,1762,2322,1352,1000,1379,1954,1543,3415,3661,1650,3920,2042,2638,6901,4755,6420,3677,4921,7019,8276,3719,10969,8813,4894,6958,1750,2521,4731,6624,2927,1870,1886,1310,2399,9511,4503,4455,5197,3992,1731,5252,3148,2046,2197,917,1063,1385,1707,2138,1015,1270,1467,5784,4775,4852,4546,2246,3347,6772,3665,4291,5186,5814,11261,6168,3309,3285,4682,8007,4709,6681,5695,5596,4059,911,1560,4389,5045,6440,4137,3090,4938,2996,1311,3451,1465,2230,3543,1948,1484,971,1807,5293,9238,3563,2219,5581,1661,3807,2893,3832,2230,1482,6986,2691,1676,1684,1998,3440,7849,6052,4539,9162,7113,2958,6571,5740,4235,5341,7799,8532,8883,9758,2735,2161,3899,2850,3046,1836,1406,1728,2665,7726,3355,4442,1957,1743,1673,2409,2661,5171,1779,2046,2054,4516,4810,3029,2769,2411,1692,6563,10234,6572,2784,2396,2694,5315,9125,3881,4440,5090,4359,3600,5016,6806,7776,4186,7963,6387,8747,6330,7436,3710,2354,3393,2586,3296,1273,1775,2552,2841,1530,1143,2824,1507,1951,764,1807,2076,6199,1575,5287,2655,3950,2649,1281,2862,1524,1030,3313,4743,3326,3303,1202,1647,1721,2504,1197,7297,2631,2275,3490,5779,2765,2942,2706,7070,11490,10576,5582,7196,1273,1423,3051,2806,4360,3268,5181,8007,4312,4192,2749,2575,1429,1376,1586,3527,1959,1024,2075,2989,1425,926,1871,3191,1610,1325,1373,1460,8145,5612,4203,3324,2787,1738,2317,1864,997,2576,4837,3960,7605,7381,4487,11997,7361,9172,7832,4140,5619,2244,1354,2935,2350,2044,3459,3229,2979,2811,1440,2679,3991,2096,1688,3148,3595,3148,5768,1289,3409,1342,1288,1804,2556,2971,3025,2341,1459,1659,4702,2148,1192,2189,9362,7108,13839,8644,5712,3899,5173,5385,3738,5525,6541,11421,10395,19613,5781,4384,1199,1456,3759,4742,3203,2476,2756,2673,1820,1670,2263,1988,997,898,3232,1290,1524,1697,1451,3556,3816,2301,1959,1265,1548,1732,4994,3097,2051,2885,7962,6588,5122,5555,4586,4807,8680,4335,4045,3112,1523,6236,6887,5959,9748,6952,5664,5428,5100,2311,1812,2687,3195,1934,1130,2934,862,1581,826,1555,1253,1850,2072,1551,1691,1807,2035,1919,1010,788,488,726,1106,715,1603,3069,2331,1082,1840,5076,5047,1941,5907,2817,1749,2571,2507,1577,4059,1583,5269,5735,5237,5427,7555,5510,6817,7004,2091,3674,3640,2855,4485,6089,7440,3385,4348,2603,5593,4838,7022,6312,2226,1799,2222,2386,1424,1274,2646,5825,2127,1883,1676,3096,1366,2990,3857,4997,2214,1861,3939,4151,5670,3221,1563,1683,1618,2518,2485,5969,9585,7032,7469,12107,8064,5263,6423,2531,1773,4404,2034,3419,2573,944,1286,2342,1721,1877,1399,3391,2134,2580,2218,1865,2486,2418,2588,2826,6703,10181,9080,3767,2334,2509,1693,1479,7616,4786,2580,2501,4074,2600,5124,5769,3515,3590,3647,5702,10373,4505,4812,4507,5551,7187,4642,6494,1007,2122,3288,1940,1584,1877,3533,2293,1069,1331,2439,1616,1642,1601,1405,3986,8765,8670,4954,4137,4205,4890,2251,7473,1279,2410,2640,1240,1201,4720,2180,2880,3762,1955,1064,5090,3888,3612,2598,3751,1837,8925,10707,3275,5249,14240,10062,4163,10708,3917,6459,4726,3051,1996,3681,4380,4270,2935,1971,2388,2970,1495,1442,1140,921,1098,3926,3641,3988,3574,3733,2467,2554,1477,3115,1160,1331,746,2388,3589,1958,1426,2000,4061,6760,2029,2405,3971,3808,2575,3481,4568,2543,5637,5954,6826,4990,13717,3678,2308,3074,1263,3316,2250,1652,1515,1929,1225,798,1076,1293,11895,4496,1726,3244,8405,4494,2561,1573,1794,1504,2533,1403,1343,1359,1549,1279,1927,2362,2431,1426,1511,2041,1549,2308,1931,5114,4532,2411,13025,5808,10441,11315,14830,11844,6733,14136,2720,2259,2862,2778,2459,3027,2847,3142,2293,2317,6249,1979,5638,3710,3921,2402,1928,1925,4217,1604,2007,2568,2229,5065,4064,2738,1725,907,2289,2030,2369,8289,7083,7670,7100,4588,4507,6743,4407,4483,2738,2834,3481,3884,9285,5078,4263,4847,4729,1676,2001,3315,4791,2792,2915,4311,3504,1632,1339,1256,1104,6347,1967,1538,1116,907,1645,1372,1213,1606,3492,715,2334,726,417,885,925,617,1295,2712,2387,1724,2391,2162,5715,2719,973,2087,3284,1515,4902,7683,2556,4765,4476,4542,4391,6814,3777,4175,1975,2761,1594,1656,1147,2384,2958,6687,2827,2019,1088,1413,2150,2111,2437,1780,1136,1804,1475,1765,4141,7514,2229,1143,2264,1061,3287,3074,3001,4220,3170,2113,3597,4725,7743,3977,3505,5059,3340,5811,6955,3778,4615,4005,3788,4783,7785,5366,3337,4401,3389,3467,3031,1860,4840,5660,3668,2801,1974,1623,999,1344,2036,2476,3626,1981,1575,1060,1963,1166,1003,1259,861,1561,4492,6630,1743,2041,1780,2942,1894,1563,2553,3247,4783,2827,940,2773,1381,1345,1475,4946,5124,5505,4418,6222,2089,2648,8020,7095,8029,6192,2115,2110,2126,790,1126,1133,801,1337,2583,1245,1465,1217,829,688,1436,1673,3511,4814,1718,1072,2735,3016,2405,3040,3066,2052,1411,2672,3407,1692,2324,4065,1653,2585,1011,2779,5720,4444,5144,9881,8009,5126,8455,1924,523,3696,2114,1398,2397,1955,1410,2135,1083,2001,1105,1221,2560,1988,4989,5406,4833,3715,5902,2263,1272,2384,2628,2108,5481,2952,2129,2571,4923,2146,1989,3612,2419,2266,2353,2483,1993,2176,2039,5689,7305,2560,3541,6705,7807,4614,5274,5888,1773,1028,7047,4590,3324,1341,2993,1377,2630,2829,3303,4629,4884,1816,1244,1989,1803,868,1222,1226,1438,794,1980,1158,1509,1912,3851,7370,13211,10457,7131,10964,5418,2132,4339,4550,5071,2551,2577,6538,4505,6216,8446,6765,6751,5275,9226,4416,6264,4389,1752,3865,9156,5485,5584,4440,2246,5287,6174,4008,2477,4079,3172,3246,1440,1263,2578,4793,2635,1609,2141,1308,1482,1419,3422,3503,1991,1396,4350,6206,3467,4600,4810,5017,3479,5897,2611,6246,1936,2417,8816,9977,3665,6744,4946,8676,5386,6456,2285,1569,5041,3437,4418,3760,2914,1873,1309,1441,731,695,1805,702,2682,1589,1194,647,606,619,1403,1018,700,2003,3864,1236,3117,2235,2264,1862,788,1795,6011,4822,2132,1821,3178,2518,2693,1532,3072,1337,6535,3681,6608,5314,4037,3790,9121,1198,1828,2826,3463,2386,6573,3314,1697,1519,1756,940,2916,3998,2067,3198,2995,1703,1778,6183,1914,1371,1611,1865,1480,4966,2087,2398,2294,2046,5602,4064,2425,4279,4178,7451,3218,2453,4476,4752,3379,3092,7993,4385,3775,4097,8621,6770,6517,7956,2314,1268,2974,2641,1997,1610,1784,2332,1413,1400,2009,1045,1574,1055,2556,1899,373,625,1027,1420,1662,424,1056,676,580,1489,696,1141,719,1688,2586,2456,3030,1190,1435,1348,2812,2991,2177,2929,3511,8789,3394,2517,2950,7937,6282,3745,4759,1418,3090,3186,1768,3804,1814,2457,1587,2794,2469,2012,1414,3533,3109,1992,2482,4003,1522,1339,1308,708,1393,2203,1555,716,802,696,1102,1372,2659,2720,1675,1350,1009,2188,1165,836,1022,639,1147,3899,2064,4530,3323,8168,8023,4623,5080,5183,1538,1117,1913,4556,10487,4126,2967,1816,3209,2791,989,2037,2101,1191,1236,5076,2305,2088,4347,3028,1590,2531,687,1481,1646,862,736,1208,2181,3163,1526,1035,1820,807,2367,4940,1715,3312,1693,1979,1500,1178,1130,3899,5835,4603,3947,4997,5423,2582,1581,3062,6497,3444,3130,4184,6209,2815,1340,1599,1753,1806,1326,719,341,433,4605,2942,1342,1564,2158,4703,2001,885,497,944,444,694,5969,2442,1243,1240,957,2398,1769,847,888,1167,10881,3494,4551,2960,6598,5410,10446,5433,3657,7281,1736,1314,2292,1471,2470,3110,1842,3472,2454,4908,4828,2979,2245,1939,1568,769,852,790,1854,1304,991,2462,1607,3278,709,1199,802,935,1219,2761,5103,6175,4067,2707,2352,3076,2237,14945,4835,2370,3820,2436,3561,3402,4656,5534,3992,4869,7568,2209,1301,3782,2013,1789,1342,967,1278,3215,6042,3771,4546,1237,2309,1261,1571,926,1249,1063,719,818,826,420,732,391,276,587,969,735,2210,2611,1401,1660,1354,2145,1049,1099,2019,2113,5911,6213,6695,5623,5760,13568,13435,6036,6268,6158,1078,1731,3234,2491,3741,3858,3268,2323,2007,1635,1469,2389,1727,2005,791,331,1217,798,1606,2086,2155,2505,4754,3100,883,1685,2103,2648,1627,7710,1928,2988,3272,2499,4572,4307,4099,2820,4168,2614,5784,3478,1961,3242,6784,8154,4195,3309,3733,2528,952,3352,2286,1103,1350,4260,3328,2690,2866,6815,4202,2481,2195,3566,3264,5084,10287,3803,2658,10099,4819,3977,4946,2589,2127,1333,1755,1072,4579,7621,3118,4096,1449,1620,2862,2020,3372,2026,1756,2452,2339,7816,3833,4158,3391,3244,4208,7552,1972,1353,1632,3253,3919,3227,1283,772,3403,2147,2343,2954,2294,2864,2016,1733,1429,822,1215,662,2128,2373,1535,2269,1636,935,1140,801,783,4860,2269,2501,2689,1652,3070,2490,2047,2024,3203,1385,2351,2885,2315,1353,6503,4063,3915,3493,5050,2015,598,3168,2803,2442,4085,8397,1958,1729,1911,1381,1711,786,808,753,354,704,973,2625,913,825,1386,2279,1870,1495,2091,1089,866,1378,1904,3814,2070,1329,1361,2017,5493,2480,1202,1790,1430,9433,7705,2908,9468,5751,8420,5901,4356,8800,2066,2233,6127,4292,1773,1808,1286,2405,3114,1719,2155,2524,1554,5713,3074,1738,1273,1891,1302,2250,1388,1156,823,2096,4750,2871,1613,4781,2463,2873,2374,731,2895,3020,1545,1692,3619,9084,8820,9325,3562,14873,7038,10521,10482,9836,5898,5249,5207,2007,3173,2937,3197,3709,2567,4086,2541,2846,3777,4010,5432,5414,5792,6940,5434,4260,4182,2881,2859,5268,4844,2913,2913,2649,2751,2724,1803,1423,8217,4807,8826,7201,4944,3828,11229,5950,4032,6084,5633,5445,7417,4108,3544,7212,6122,5208,5286,7563,4504,2095,6264,5071,3056,2992,2045,5221,8398,6076,4282,3604,4054,2538,3408,1677,7529,5649,6012,2880,2281,2183,2002,4617,2132,1136,2248,7613,2921,3450,2003,4165,4533,3134,3689,3480,4488,4217,6919,4247,4337,3824,7036,6742,9113,11489,9032,5398,6032,1887,1580,5383,4887,6151,2042,6354,4265,5083,6382,2414,1907,2999,2820,3388,3523,4603,3045,2314,3567,3301,6812,5326,3091,3769,5013,4425,2921,2283,5805,2506,2727,4246,3489,4164,3197,6214,8923,10103,9815,5690,7385,4574,5093,9824,4108,4843,3737,8892,1146,3160,3754,4012,4964,5595,3937,2460,2371,1885,1134,1210,1643,2697,2586,3506,2024,2683,1364,730,1443,1805,1174,834,2132,1273,1930,2721,2766,5724,4722,2698,2199,2557,2091,2137,2563,2033,3432,1431,1804,2956,1791,3697,3440,4254,3350,4607,6669,3138,1768,2533,3205,4595,2243,2467,1515,860,531,1340,1712,5708,5506,3345,2753,1652,1064,765,2258,3155,2295,3083,4765,5204,3064,3785,3146,2340,6206,4669,3211,4945,6317,7374,6510,3198,5862,7929,8937,9030,6544,5150,12734,13319,10020,8465,6496,7528,4106,2166,9858,4862,6756,5975,5827,3826,4877,4831,2748,5062,9440,5545,6260,3567,2722,2427,2408,6525,4564,4486,2912,3249,1774,4625,3337,1612,2088,4266,3132,4206,3401,3514,2593,1739,3892,6686,8178,8677,9749,8084,4513,8821,5471,6879,5844,5226,5368,1839,1536,7011,4072,2427,7903,4986,10175,5723,5927,8361,9306,6268,8983,6864,4478,4776,4943,3243,2357,4259,2794,2081,3203,5759,2887,6924,4358,3134,10717,8918,3402,9249,4537,6374,11246,7923,5202,4671,6136,5712,12788,9733,9567,10440,8215,8306,5722,6873,2870,3824,7744,3904,4480,6619,4996,2606,3647,7682,5769,8313,8519,3134,5375,4880,2913,2708,3108,3234,2433,5338,5875,5431,5735,4440,5057,2953,3218,14890,6370,10899,9373,6090,5327,8896,12354,9804,7356,7489,5137,7598,15311,9444,6792,10286,6799,6360,7527,6262,4129,8118,3272,4010,3857,3816,2320,1786,4549,3154,5040,3532,2999,3843,2091,2265,2783,11111,4914,5081,4326,2487,3467,3742,6234,4354,1707,2615,2435,4216,5327,2439,1841,4576,6450,3248,4476,2075,2929,4125,8052,11597,4897,4528,5257,5810,5242,5745,3620,3737,5087,3888,11925,3685,3533,6978,5397,3034,4677,4048,4268,2542,2507,3641,5068,2602,3333,4474,4475,6023,3477,3772,3754,3618,1666,1303,3365,8687,3679,4000,5609,10554,3964,4036,4542,1749,4863,6002,3400,8368,5143,4254,11634,9161,13346,5070,9306,5126,4954,7632,14480,5046,5289,6662,6259,3968,5489,2453,5197,5956,3117,2439,5960,5265,3548,4334,2889,9102,6386,7692,5558,4160,3571,5662,2900,2713,3267,6422,4870,6021,6800,3874,3801,5111,4263,7475,7934,4999,3347,3254,3615,8837,9733,5438,4813,7780,3088,1912,5279,4528,4914,6133,2785,2215,1415,1577,2533,3153,2132,1872,3584,1221,2913,1669,2348,1376,906,3078,2036,2841,10719,4311,2175,3229,5449,16938,11697,6560,3340,5879,2704,3835,7405,3510,6115,13058,5224,7409,6192,3449,9202,6790,5687,5587,6972,1550,3088,5945,6803,2334,4002,6123,6409,5775,3939,3856,2562,4356,2971,5145,1641,1389,7667,6476,3247,4757,4136,1807,5119,2701,5401,3884,4005,4813,7630,4294,4656,6106,3946,2694,2540,3651,3483,4353,8019,7839,6217,4178,4007,9412,6002,7282,8084,9197,3314,2590,5846,8798,4313,5460,5874,3499,2318,2693,1644,2660,4127,7238,4691,2992,1575,1472,777,1372,1554,3505,1437,2188,2969,913,993,705,2938,4655,3136,9137,4864,6081,2676,5948,3797,3008,2149,3637,4955,6323,5996,5367,9224,4605,3910,6546,9900,4424,6426,4636,4180,4253,3068,3898,4784,11069,4225,4356,3493,1692,1664,1692,3045,1929,3420,2825,3581,1561,4224,1159,2080,2776,6444,1756,2575,1814,3917,5732,4275,6783,4251,8422,4556,2435,4136,2689,2564,5973,4336,5678,3693,6028,4517,6902,5724,7475,2558,3973,4213,3726,8901,5560,9559,5496,5206,3226,3769,3784,2978,2676,3017,5785,4491,3636,2100,2125,2434,4338,3734,3107,2107,1963,1727,1288,2074,4279,1353,2180,1987,4167,4456,6842,3123,3036,2881,2989,1530,2938,4448,8175,4342,5107,4806,4968,11914,2852,2634,4063,5699,3291,3869,9281,8451,10765,3710,5220,3868,4442,4570,6599,2879,3817,1957,1735,1667,794,1037,1362,1420,2360,905,3472,1790,2590,2780,1113,2305,5688,6421,5911,3217,1782,6114,7396,5456,1808,12213,4655,3608,11570,6623,5359,4968,7227,2182,2432,4409,2180,8734,8126,3990,1592,3812,3232,5221,6244,4094,4386,10911,6539,4188,2872,1598,5955,4520,6077,2197,2794,3570,3376,2629,2121,1709,2865,5868,4587,2310,5522,5511,5163,2886,2550,3127,3234,2738,7151,6844,7981,8655,6676,5489,4860,6702,2195,2574,3477,6492,4351,4219,2688,2223,3814,3926,2203,3853,4335,10005,12538,7081,8785,6885,3343,3679,2153,2482,3550,6438,3677,2111,1513,1518,1390,4753,4467,4022,7394,4262,2679,4464,1953,3708,6214,2211,2744,3598,4330,4405,5946,12975,11851,7354,8531,3344,2348,4655,6210,4359,5680,3397,8283,8642,15899,9517,9250,4429,2476,3710,2168,3212,4281,3684,7087,2766,1238,1937,7183,6497,3989,6676,2648,2353,9285,4025,2499,2598,3326,2384,4408,1908,4701,6154,5677,4767,5667,4278,3369,5748,6618,5868,7458,6806,3941,3306,10399,8217,14239,8131,3625,5118,4859,3085,4112,10296,3888,2291,3655,2812,1369,3744,2106,2046,1438,956,3403,2006,1839,5337,1728,1279,1214,3036,1923,1189,2201,1918,13593,5977,7632,9605,9566,3897,7568,5749,2972,5609,4599,8650,3042,4681,4755,2893,3033,3433,1709,2108,1889,6133,12907,16028,9894,7742,9426,4735,3724,1631,6566,3573,5930,2351,6064,2669,3755,2140,1687,2010,1558,3192,3247,4442,5498,3375,2096,4986,3727,3556,3239,2220,9466,3435,2592,2352,4362,6500,5648,7490,5228,4273,5871,6212,2565,3672,2288,5132,10371,6384,3398,4471,2459,4301,1517,4838,1512,1831,1608,6027,1946,1840,1327,1492,2393,1662,2848,985,1227,1655,3944,1826,2606,6177,2122,4705,4747,7464,5883,2420,10943,9767,5203,6453,3794,10536,10835,7710,6389,7858,6626,6311,6466,2281,2001,6369,1938,3228,2893,1737,2831,8891,5557,17888,7584,6281,3695,5807,4948,2734,2424,2145,980,1480,2245,3626,11986,2515,1943,9905,7285,3837,5003,9602,3188,2217,4634,5266,6072,3325,5436,10551,5013,10591,11825,8628,5031,12199,12036,6800,6050,5816,2322,2975,7750,3792,5346,4833,6245,2497,2221,2169,4367,1974,1192,2586,7462,1617,2415,3189,2161,1694,2390,6485,3968,3116,4106,2662,1670,1060,1730,7444,2479,1718,3116,2573,11568,5813,2548,4979,5766,2920,3180,3918,2189,13272,11992,4613,4379,4210,7172,2083,2372,3949,4732,2107,2858,3932,6003,13011,6616,3096,10885,4599,2394,4863,3463,5783,4576,2441,9155,4625,3658,2078,2078,2120,1971,1777,5065,3692,7450,4806,3250,4761,2646,3162,3176,4267,2872,10838,3804,10464,4244,6990,6630,7451,6820,4499,4966,5874,6825,2982,3486,3392,6465,3095,3468,3328,6655,2027,2028,2162,1284,5059,4664,2210,11278,4093,1603,2890,1758,1286,3777,3382,2648,2368,3891,2638,5277,6741,3445,2869,3997,4774,7739,3421,3911,2969,2243,2079,4441,9131,3072,4675,7775,5077,8252,5955,11927,2482,3368,5120,4127,5047,12035,5146,2978,5116,2798,3466,4202,1952,2162,6254,1968,1984,2391,2976,2240,2329,1155,1890,2405,3082,2090,1340,4522,3765,2312,2501,1801,1502,1945,1183,2757,1259,2920,2864,5071,10518,8101,6829,6501,12891,7933,9295,4134,6796,1985,5640,5556,3227,8913,5007,3174,4176,3008,2630,1591,7064,1580,3693,2568,2051,2449,1276,3081,3634,5980,5155,2436,3246,3701,8024,5147,5384,9775,18056,10338,8226,4073,14287,6162,9848,5223,5659,5202,6254,4174,8707,8403,5402,11743,8300,5039,7796,8151,3559,4920,6715,5523,6895,8195,5584,4985,2621,1618,2246,2843,4263,6582,3661,2683,2283,2655,1203,7618,2593,2106,3565,2192,3635,2983,3142,2315,2351,4173,4833,4563,2835,3884,2272,2049,2607,2251,2437,7188,6126,4842,4698,7350,3910,6384,3124,4215,8857,6407,2124,4807,8475,8640,5018,7927,4567,3479,7081,3684,3288,3439,2437,2289,3704,7357,3760,2390,1907,2563,2620,5510,2479,1457,2011,2155,1336,2180,3120,4885,16073,8488,11629,6411,4303,3445,4168,4622,3638,13907,14434,13270,9092,7166,7036,4047,4239,5322,2020,3980,6367,5076,4900,3718,9237,4223,4748,2913,2861,4114,4135,4965,3106,7251,3752,5594,7363,2219,1499,2204,4490,7148,2111,5140,5489,2090,2451,5025,2261,2610,6796,9488,3089,4740,5747,14578,10768,9292,3642,8704,3612,2570,8002,8908,6815,5724,6184,2679,2259,8495,7270,3997,3981,5028,2410,4832,5671,3394,2613,2717,2182,2903,1628,5887,9177,2738,4200,5000,2593,2609,2191,1513,1018,879,3068,2131,2566,6524,4345,4426,3259,3265,5408,4247,2784,2340,2317,2597,1710,9321,6614,7406,6853,5391,4856,4997,3205,2470,6466,3499,3920,3572,3937,4332,3999,3708,2159,3858,5169,3908,2681,3465,1199,1572,1018,1139,1521,2401,4607,2142,1418,2107,901,1428,3148,3136,2471,1239,5819,14660,7430,6897,4979,4386,3611,4738,4355,4272,1904,3164,20967,7718,5509,6818,8656,4229,4450,6578,4315,4390,2968,4980,7903,4459,3815,2441,5354,4474,5910,5029,3332,2836,2813,1680,5517,5233,4561,2467,3785,3451,1179,2291,2105,1782,3517,6737,2862,2989,10004,2967,3991,4469,3214,5189,7420,9401,7113,6884,3436,7003,6016,5606,4134,6289,2383,2040,9348,4812,8894,10456,4505,3497,2481,6316,4294,2307,1724,3455,2342,2755,1724,1204,1695,624,450,2236,2816,1645,2093,887,954,1729,2658,8563,3432,3758,9613,3354,8160,3617,3324,4247,4057,7132,2912,6126,3718,5926,11900,8567,4545,5568,4667,2315,2721,11082,3733,5861,3546,3670,4317,2911,1277,2956,3150,2448,1732,2078,1268,1436,2767,2432,4374,2050,3266,9881,4775,2033,1789,2409,3257,3433,6182,5480,6495,2687,3838,4588,6342,2365,3803,1883,7673,12088,11447,10544,9262,8442,6521,3973,5834,5712,3340,3321,4776,5348,4825,5354,5021,6636,3312,2422,2070,3881,4575,3331,7924,2872,2472,3294,5125,2504,3581,2260,2132,1718,1293,1734,1572,2983,1976,7569,3617,2908,2776,4278,2855,2964,5455,4328,4654,5843,3054,2830,3148,5624,9449,7668,3931,5134,6444,3418,3609,4985,4316,2879,5346,12348,6597,8019,5592,4566,3323,4398,5576,2583,1631,2714,1239,2699,1542,1712,3062,2788,2286,1792,4612,7178,5958,2187,2356,1286,1113,2816,2379,3079,2064,5138,2867,3708,4296,1811,7651,9448,10818,7499,4224,4288,6176,6419,1134,2109,6552,3449,4476,2626,1853,2445,4229,2756,1535,6026,1398,602,673,1729,1096,1082,2065,5063,4535,2194,3234,5507,4828,4757,5236,2658,13934,12332,9591,3369,2958,3934,4119,3865,4727,5569,7625,5131,3193,17133,4631,3143,7736,9264,4466,6690,13386,2410,3628,4921,4993,3291,2772,2407,2042,1508,12186,4450,5909,7346,4090,1871,1853,3740,5116,2792,2288,1221,3023,1418,1137,1012,3757,1990,1644,2544,2681,5448,3587,3924,6956,5593,3681,2040,2786,7016,4028,8575,10875,7079,6707,8082,6962,6449,7236,5749,1823,3514,4105,3404,4171,6411,3673,2815,3769,3443,4003,5088,6936,3385,4492,5407,8029,4088,3029,2076,6310,2428,2004,907,1151,2733,1857,2039,1618,2457,1330,4405,3801,6283,2355,6395,7978,7060,9720,7925,4897,4667,10737,7443,7618,6673,9405,6670,7527,4004,3077,6116,6353,4865,2956,4154,3414,2776,2469,1514,2855,8135,8139,5486,3727,1457,2856,3307,1738,2542,6971,4264,1736,2365,1396,1705,1196,2439,3355,4112,2484,2825,3323,5225,4997,2658,4870,7414,5495,3916,2465,3710,6687,9913,13064,5442,4367],
      "s": "ok"
    },
    "contract_map": [
      {
        "contract_code": "VN30F2601",
        "expiry_date": "2026-01-15",
        "expiry_unix": 1768410000
      },
      {
        "contract_code": "VN30F2602",
        "expiry_date": "2026-02-13",
        "expiry_unix": 1770915600
      },
      {
        "contract_code": "VN30F2603",
        "expiry_date": "2026-03-19",
        "expiry_unix": 1773853200
      },
      {
        "contract_code": "VN30F2604",
        "expiry_date": "2026-04-16",
        "expiry_unix": 1776272400
      },
      {
        "contract_code": "VN30F2605",
        "expiry_date": "2026-05-21",
        "expiry_unix": 1779296400
      },
      {
        "contract_code": "VN30F2606",
        "expiry_date": "2026-06-18",
        "expiry_unix": 1781715600
      },
      {
        "contract_code": "VN30F2607",
        "expiry_date": "2026-07-16",
        "expiry_unix": 1784134800
      },
      {
        "contract_code": "VN30F2608",
        "expiry_date": "2026-08-20",
        "expiry_unix": 1787158800
      },
      {
        "contract_code": "VN30F2609",
        "expiry_date": "2026-09-17",
        "expiry_unix": 1789578000
      },
      {
        "contract_code": "VN30F2610",
        "expiry_date": "2026-10-15",
        "expiry_unix": 1791997200
      },
      {
        "contract_code": "VN30F2611",
        "expiry_date": "2026-11-19",
        "expiry_unix": 1795021200
      },
      {
        "contract_code": "VN30F2612",
        "expiry_date": "2026-12-17",
        "expiry_unix": 1797440400
      }
    ]
  },
  "market_data": {
    "resolution": "5",
    "bars": {
      "t": [1773800100,1773800400,1773800700,1773801000,1773801300,1773801600,1773801900,1773802200,1773802500,1773802800,1773803100,1773803400,1773803700,1773804000,1773804300,1773804600,1773804900,1773805200,1773805500,1773805800,1773806100,1773806400,1773806700,1773807000,1773807300,1773807600,1773807900,1773808200,1773813600,1773813900,1773814200,1773814500,1773814800,1773815100,1773815400,1773815700,1773816000,1773816300,1773816600,1773816900,1773817200,1773817500,1773817800,1773818100,1773818400,1773818700,1773819000,1773819900,1773886500,1773886800,1773887100,1773887400,1773887700,1773888000,1773888300,1773888600,1773888900,1773889200,1773889500,1773889800,1773890100,1773890400,1773890700,1773891000,1773891300,1773891600,1773891900,1773892200,1773892500,1773892800,1773893100,1773893400,1773893700,1773894000,1773894300,1773894600,1773900000,1773900300,1773900600,1773900900,1773901200,1773901500,1773901800,1773902100,1773902400,1773902700,1773903000,1773903300,1773903600,1773903900,1773904200,1773904500,1773904800,1773905100,1773905400,1773906300,1773972900,1773973200,1773973500,1773973800,1773974100,1773974400,1773974700,1773975000,1773975300,1773975600,1773975900,1773976200,1773976500,1773976800,1773977100,1773977400,1773977700,1773978000,1773978300,1773978600,1773978900,1773979200,1773979500,1773979800,1773980100,1773980400,1773980700,1773981000,1773986400,1773986700,1773987000,1773987300,1773987600,1773987900,1773988200,1773988500,1773988800,1773989100,1773989400,1773989700,1773990000,1773990300,1773990600,1773990900,1773991200,1773991500,1773991800,1773992700,1774232100,1774232400,1774232700,1774233000,1774233300,1774233600,1774233900,1774234200,1774234500,1774234800,1774235100,1774235400,1774235700,1774236000,1774236300,1774236600,1774236900,1774237200,1774237500,1774237800,1774238100,1774238400,1774238700,1774239000,1774239300,1774239600,1774239900,1774240200,1774245600,1774245900,1774246200,1774246500,1774246800,1774247100,1774247400,1774247700,1774248000,1774248300,1774248600,1774248900,1774249200,1774249500,1774249800,1774250100,1774250400,1774250700,1774251000,1774251900,1774318500,1774318800,1774319100,1774319400,1774319700,1774320000,1774320300,1774320600,1774320900,1774321200,1774321500,1774321800,1774322100,1774322400,1774322700,1774323000,1774323300,1774323600,1774323900,1774324200,1774324500,1774324800,1774325100,1774325400,1774325700,1774326000,1774326300,1774326600,1774332000,1774332300,1774332600,1774332900,1774333200,1774333500,1774333800,1774334100,1774334400,1774334700,1774335000,1774335300,1774335600,1774335900,1774336200,1774336500,1774336800,1774337100,1774337400,1774338300,1774404900,1774405200,1774405500,1774405800,1774406100,1774406400,1774406700,1774407000,1774407300,1774407600,1774407900,1774408200,1774408500,1774408800,1774409100,1774409400,1774409700,1774410000,1774410300,1774410600,1774410900,1774411200,1774411500,1774411800,1774412100,1774412400,1774412700,1774413000,1774418400,1774418700,1774419000,1774419300,1774419600,1774419900,1774420200,1774420500,1774420800,1774421100,1774421400,1774421700,1774422000,1774422300,1774422600,1774422900,1774423200,1774423500,1774423800,1774424700,1774491300,1774491600,1774491900,1774492200,1774492500,1774492800,1774493100,1774493400,1774493700,1774494000,1774494300,1774494600,1774494900,1774495200,1774495500,1774495800,1774496100,1774496400,1774496700,1774497000,1774497300,1774497600,1774497900,1774498200,1774498500,1774498800,1774499100,1774499400,1774504800,1774505100,1774505400,1774505700,1774506000,1774506300,1774506600,1774506900,1774507200,1774507500,1774507800,1774508100,1774508400,1774508700,1774509000,1774509300,1774509600,1774509900,1774510200,1774511100,1774577700,1774578000,1774578300,1774578600,1774578900,1774579200,1774579500,1774579800,1774580100,1774580400,1774580700,1774581000,1774581300,1774581600,1774581900,1774582200,1774582500,1774582800,1774583100,1774583400,1774583700,1774584000,1774584300,1774584600,1774584900,1774585200,1774585500,1774585800,1774591200,1774591500,1774591800,1774592100,1774592400,1774592700,1774593000,1774593300,1774593600,1774593900,1774594200,1774594500,1774594800,1774595100,1774595400,1774595700,1774596000,1774596300,1774596600,1774597500,1774836900,1774837200,1774837500,1774837800,1774838100,1774838400,1774838700,1774839000,1774839300,1774839600,1774839900,1774840200,1774840500,1774840800,1774841100,1774841400,1774841700,1774842000,1774842300,1774842600,1774842900,1774843200,1774843500,1774843800,1774844100,1774844400,1774844700,1774845000,1774850400,1774850700,1774851000,1774851300,1774851600,1774851900,1774852200,1774852500,1774852800,1774853100,1774853400,1774853700,1774854000,1774854300,1774854600,1774854900,1774855200,1774855500,1774855800,1774856700,1774923300,1774923600,1774923900,1774924200,1774924500,1774924800,1774925100,1774925400,1774925700,1774926000,1774926300,1774926600,1774926900,1774927200,1774927500,1774927800,1774928100,1774928400,1774928700,1774929000,1774929300,1774929600,1774929900,1774930200,1774930500,1774930800,1774931100,1774931400,1774936800,1774937100,1774937400,1774937700,1774938000,1774938300,1774938600,1774938900,1774939200,1774939500,1774939800,1774940100,1774940400,1774940700,1774941000,1774941300,1774941600,1774941900,1774942200,1774943100,1775009700,1775010000,1775010300,1775010600,1775010900,1775011200,1775011500,1775011800,1775012100,1775012400,1775012700,1775013000,1775013300,1775013600,1775013900,1775014200,1775014500,1775014800,1775015100,1775015400,1775015700,1775016000,1775016300,1775016600,1775016900,1775017200,1775017500,1775017800,1775023200,1775023500,1775023800,1775024100,1775024400,1775024700,1775025000,1775025300,1775025600,1775025900,1775026200,1775026500,1775026800,1775027100,1775027400,1775027700,1775028000,1775028300,1775028600,1775029500,1775096100,1775096400,1775096700,1775097000,1775097300,1775097600,1775097900,1775098200,1775098500,1775098800,1775099100,1775099400,1775099700,1775100000,1775100300,1775100600,1775100900,1775101200,1775101500,1775101800,1775102100,1775102400,1775102700,1775103000,1775103300,1775103600,1775103900,1775104200,1775109600,1775109900,1775110200,1775110500,1775110800,1775111100,1775111400,1775111700,1775112000,1775112300,1775112600,1775112900,1775113200,1775113500,1775113800,1775114100,1775114400,1775114700,1775115000,1775115900,1775182500,1775182800,1775183100,1775183400,1775183700,1775184000,1775184300,1775184600,1775184900,1775185200,1775185500,1775185800,1775186100,1775186400,1775186700,1775187000,1775187300,1775187600,1775187900,1775188200,1775188500,1775188800,1775189100,1775189400,1775189700,1775190000,1775190300,1775190600,1775196000,1775196300,1775196600,1775196900,1775197200,1775197500,1775197800,1775198100,1775198400,1775198700,1775199000,1775199300,1775199600,1775199900,1775200200,1775200500,1775200800,1775201100,1775201400,1775202300,1775441700,1775442000,1775442300,1775442600,1775442900,1775443200,1775443500,1775443800,1775444100,1775444400,1775444700,1775445000,1775445300,1775445600,1775445900,1775446200,1775446500,1775446800,1775447100,1775447400,1775447700,1775448000,1775448300,1775448600,1775448900,1775449200,1775449500,1775449800,1775455200,1775455500,1775455800,1775456100,1775456400,1775456700,1775457000,1775457300,1775457600,1775457900,1775458200,1775458500,1775458800,1775459100,1775459400,1775459700,1775460000,1775460300,1775460600,1775461500,1775528100,1775528400,1775528700,1775529000,1775529300,1775529600,1775529900,1775530200,1775530500,1775530800,1775531100,1775531400,1775531700,1775532000,1775532300,1775532600,1775532900,1775533200,1775533500,1775533800,1775534100,1775534400,1775534700,1775535000,1775535300,1775535600,1775535900,1775536200,1775541600,1775541900,1775542200,1775542500,1775542800,1775543100,1775543400,1775543700,1775544000,1775544300,1775544600,1775544900,1775545200,1775545500,1775545800,1775546100,1775546400,1775546700,1775547000,1775547900,1775614500,1775614800,1775615100,1775615400,1775615700,1775616000,1775616300,1775616600,1775616900,1775617200,1775617500,1775617800,1775618100,1775618400,1775618700,1775619000,1775619300,1775619600,1775619900,1775620200,1775620500,1775620800,1775621100,1775621400,1775621700,1775622000,1775622300,1775622600,1775628000,1775628300,1775628600,1775628900,1775629200,1775629500,1775629800,1775630100,1775630400,1775630700,1775631000,1775631300,1775631600,1775631900,1775632200,1775632500,1775632800,1775633100,1775633400,1775634300,1775700900,1775701200,1775701500,1775701800,1775702100,1775702400,1775702700,1775703000,1775703300,1775703600,1775703900,1775704200,1775704500,1775704800,1775705100,1775705400,1775705700,1775706000,1775706300,1775706600,1775706900,1775707200,1775707500,1775707800,1775708100,1775708400,1775708700,1775709000,1775714400,1775714700,1775715000,1775715300,1775715600,1775715900,1775716200,1775716500,1775716800,1775717100,1775717400,1775717700,1775718000,1775718300,1775718600,1775718900,1775719200,1775719500,1775719800,1775720700,1775787300,1775787600,1775787900,1775788200,1775788500,1775788800,1775789100,1775789400,1775789700,1775790000,1775790300,1775790600,1775790900,1775791200,1775791500,1775791800,1775792100,1775792400,1775792700,1775793000,1775793300,1775793600,1775793900,1775794200,1775794500,1775794800,1775795100,1775795400,1775800800,1775801100,1775801400,1775801700,1775802000,1775802300,1775802600,1775802900,1775803200,1775803500,1775803800,1775804100,1775804400,1775804700,1775805000,1775805300,1775805600,1775805900,1775806200,1775807100,1776046500,1776046800,1776047100,1776047400,1776047700,1776048000,1776048300,1776048600,1776048900,1776049200,1776049500,1776049800,1776050100,1776050400,1776050700,1776051000,1776051300,1776051600,1776051900,1776052200,1776052500,1776052800,1776053100,1776053400,1776053700,1776054000,1776054300,1776054600,1776060000,1776060300,1776060600,1776060900,1776061200,1776061500,1776061800,1776062100,1776062400,1776062700,1776063000,1776063300,1776063600,1776063900,1776064200,1776064500,1776064800,1776065100,1776065400,1776066300,1776132900,1776133200,1776133500,1776133800,1776134100,1776134400,1776134700,1776135000,1776135300,1776135600,1776135900,1776136200,1776136500,1776136800,1776137100,1776137400,1776137700,1776138000,1776138300,1776138600,1776138900,1776139200,1776139500,1776139800,1776140100,1776140400,1776140700,1776141000,1776146400,1776146700,1776147000,1776147300,1776147600,1776147900,1776148200,1776148500,1776148800,1776149100,1776149400,1776149700,1776150000,1776150300,1776150600,1776150900,1776151200,1776151500,1776151800,1776152700,1776219300,1776219600,1776219900,1776220200,1776220500,1776220800,1776221100,1776221400,1776221700,1776222000,1776222300,1776222600,1776222900,1776223200,1776223500,1776223800,1776224100,1776224400,1776224700,1776225000,1776225300,1776225600,1776225900,1776226200,1776226500,1776226800,1776227100,1776227400,1776232800,1776233100,1776233400,1776233700,1776234000,1776234300,1776234600,1776234900,1776235200,1776235500,1776235800,1776236100,1776236400,1776236700,1776237000,1776237300,1776237600,1776237900,1776238200,1776239100,1776305700,1776306000,1776306300,1776306600,1776306900,1776307200,1776307500,1776307800,1776308100,1776308400,1776308700,1776309000,1776309300,1776309600,1776309900,1776310200,1776310500,1776310800,1776311100,1776311400,1776311700,1776312000,1776312300,1776312600,1776312900,1776313200,1776313500,1776313800,1776319200,1776319500,1776319800,1776320100,1776320400,1776320700,1776321000,1776321300,1776321600,1776321900,1776322200,1776322500,1776322800,1776323100,1776323400,1776323700,1776324000,1776324300,1776324600,1776325500,1776392100,1776392400,1776392700,1776393000,1776393300,1776393600,1776393900,1776394200,1776394500,1776394800,1776395100,1776395400,1776395700,1776396000,1776396300,1776396600,1776396900,1776397200,1776397500,1776397800,1776398100,1776398400,1776398700,1776399000,1776399300,1776399600,1776399900,1776400200,1776405600,1776405900,1776406200,1776406500,1776406800,1776407100,1776407400,1776407700,1776408000,1776408300,1776408600,1776408900,1776409200,1776409500,1776409800,1776410100,1776410400,1776410700,1776411000,1776411900,1776651300,1776651600,1776651900,1776652200,1776652500,1776652800,1776653100,1776653400,1776653700,1776654000,1776654300,1776654600,1776654900,1776655200,1776655500,1776655800,1776656100,1776656400,1776656700,1776657000,1776657300,1776657600,1776657900,1776658200,1776658500,1776658800,1776659100,1776659400,1776664800,1776665100,1776665400,1776665700,1776666000,1776666300,1776666600,1776666900,1776667200,1776667500,1776667800,1776668100,1776668400,1776668700,1776669000,1776669300,1776669600,1776669900,1776670200,1776671100,1776737700,1776738000,1776738300,1776738600,1776738900,1776739200,1776739500,1776739800,1776740100,1776740400,1776740700,1776741000,1776741300,1776741600,1776741900,1776742200,1776742500,1776742800,1776743100,1776743400,1776743700,1776744000,1776744300,1776744600,1776744900,1776745200,1776745500,1776745800,1776751200,1776751500,1776751800,1776752100,1776752400,1776752700,1776753000,1776753300,1776753600,1776753900,1776754200,1776754500,1776754800,1776755100,1776755400,1776755700,1776756000,1776756300,1776756600,1776757500,1776824100,1776824400,1776824700,1776825000,1776825300,1776825600,1776825900,1776826200,1776826500,1776826800,1776827100,1776827400,1776827700,1776828000,1776828300,1776828600,1776828900,1776829200,1776829500,1776829800,1776830100,1776830400,1776830700,1776831000,1776831300,1776831600,1776831900,1776832200,1776837600,1776837900,1776838200,1776838500,1776838800,1776839100,1776839400,1776839700,1776840000,1776840300,1776840600,1776840900,1776841200,1776841500,1776841800,1776842100,1776842400,1776842700,1776843000,1776843900,1776910500,1776910800,1776911100,1776911400,1776911700,1776912000,1776912300,1776912600,1776912900,1776913200,1776913500,1776913800,1776914100,1776914400,1776914700,1776915000,1776915300,1776915600,1776915900,1776916200,1776916500,1776916800,1776917100,1776917400,1776917700,1776918000,1776918300,1776918600,1776924000,1776924300,1776924600,1776924900,1776925200,1776925500,1776925800,1776926100,1776926400,1776926700,1776927000,1776927300,1776927600,1776927900,1776928200,1776928500,1776928800,1776929100,1776929400,1776930300,1776996900,1776997200,1776997500,1776997800,1776998100,1776998400,1776998700,1776999000,1776999300,1776999600,1776999900,1777000200,1777000500,1777000800,1777001100,1777001400,1777001700,1777002000,1777002300,1777002600,1777002900,1777003200,1777003500,1777003800,1777004100,1777004400,1777004700,1777005000,1777010400,1777010700,1777011000,1777011300,1777011600,1777011900,1777012200,1777012500,1777012800,1777013100,1777013400,1777013700,1777014000,1777014300,1777014600,1777014900,1777015200,1777015500,1777015800,1777016700,1777342500,1777342800,1777343100,1777343400,1777343700,1777344000,1777344300,1777344600,1777344900,1777345200,1777345500,1777345800,1777346100,1777346400,1777346700,1777347000,1777347300,1777347600,1777347900,1777348200,1777348500,1777348800,1777349100,1777349400,1777349700,1777350000,1777350300,1777350600,1777356000,1777356300,1777356600,1777356900,1777357200,1777357500,1777357800,1777358100,1777358400,1777358700,1777359000,1777359300,1777359600,1777359900,1777360200,1777360500,1777360800,1777361100,1777361400,1777362300,1777428900,1777429200,1777429500,1777429800,1777430100,1777430400,1777430700,1777431000,1777431300,1777431600,1777431900,1777432200,1777432500,1777432800,1777433100,1777433400,1777433700,1777434000,1777434300,1777434600,1777434900,1777435200,1777435500,1777435800,1777436100,1777436400,1777436700,1777437000,1777442400,1777442700,1777443000,1777443300,1777443600,1777443900,1777444200,1777444500,1777444800,1777445100,1777445400,1777445700,1777446000,1777446300,1777446600,1777446900,1777447200,1777447500,1777447800,1777448700,1777860900,1777861200,1777861500,1777861800,1777862100,1777862400,1777862700,1777863000,1777863300,1777863600,1777863900,1777864200,1777864500,1777864800,1777865100,1777865400,1777865700,1777866000,1777866300,1777866600,1777866900,1777867200,1777867500,1777867800,1777868100,1777868400,1777868700,1777869000,1777874400,1777874700,1777875000,1777875300,1777875600,1777875900,1777876200,1777876500,1777876800,1777877100,1777877400,1777877700,1777878000,1777878300,1777878600,1777878900,1777879200,1777879500,1777879800,1777880700,1777947300,1777947600,1777947900,1777948200,1777948500,1777948800,1777949100,1777949400,1777949700,1777950000,1777950300,1777950600,1777950900,1777951200,1777951500,1777951800,1777952100,1777952400,1777952700,1777953000,1777953300,1777953600,1777953900,1777954200,1777954500,1777954800,1777955100,1777955400,1777960800,1777961100,1777961400,1777961700,1777962000,1777962300,1777962600,1777962900,1777963200,1777963500,1777963800,1777964100,1777964400,1777964700,1777965000,1777965300,1777965600,1777965900,1777966200,1777967100,1778033700,1778034000,1778034300,1778034600,1778034900,1778035200,1778035500,1778035800,1778036100,1778036400,1778036700,1778037000,1778037300,1778037600,1778037900,1778038200,1778038500,1778038800,1778039100,1778039400,1778039700,1778040000,1778040300,1778040600,1778040900,1778041200,1778041500,1778041800,1778047200,1778047500,1778047800,1778048100,1778048400,1778048700,1778049000,1778049300,1778049600,1778049900,1778050200,1778050500,1778050800,1778051100,1778051400,1778051700,1778052000,1778052300,1778052600,1778053500,1778120100,1778120400,1778120700,1778121000,1778121300,1778121600,1778121900,1778122200,1778122500,1778122800,1778123100,1778123400,1778123700,1778124000,1778124300,1778124600,1778124900,1778125200,1778125500,1778125800,1778126100,1778126400,1778126700,1778127000,1778127300,1778127600,1778127900,1778128200,1778133600,1778133900,1778134200,1778134500,1778134800,1778135100,1778135400,1778135700,1778136000,1778136300,1778136600,1778136900,1778137200,1778137500,1778137800,1778138100,1778138400,1778138700,1778139000,1778139900,1778206500,1778206800,1778207100,1778207400,1778207700,1778208000,1778208300,1778208600,1778208900,1778209200,1778209500,1778209800,1778210100,1778210400,1778210700,1778211000,1778211300,1778211600,1778211900,1778212200,1778212500,1778212800,1778213100,1778213400,1778213700,1778214000,1778214300,1778214600,1778220000,1778220300,1778220600,1778220900,1778221200,1778221500,1778221800,1778222100,1778222400,1778222700,1778223000,1778223300,1778223600,1778223900,1778224200,1778224500,1778224800,1778225100,1778225400,1778226300,1778465700,1778466000,1778466300,1778466600,1778466900,1778467200,1778467500,1778467800,1778468100,1778468400,1778468700,1778469000,1778469300,1778469600,1778469900,1778470200,1778470500,1778470800,1778471100,1778471400,1778471700,1778472000,1778472300,1778472600,1778472900,1778473200,1778473500,1778473800,1778479200,1778479500,1778479800,1778480100,1778480400,1778480700,1778481000,1778481300,1778481600,1778481900,1778482200,1778482500,1778482800,1778483100,1778483400,1778483700,1778484000,1778484300,1778484600,1778485500,1778552100,1778552400,1778552700,1778553000,1778553300,1778553600,1778553900,1778554200,1778554500,1778554800,1778555100,1778555400,1778555700,1778556000,1778556300,1778556600,1778556900,1778557200,1778557500,1778557800,1778558100,1778558400,1778558700,1778559000,1778559300,1778559600,1778559900,1778560200,1778565600,1778565900,1778566200,1778566500,1778566800,1778567100,1778567400,1778567700,1778568000,1778568300,1778568600,1778568900,1778569200,1778569500,1778569800,1778570100,1778570400,1778570700,1778571000,1778571900,1778638500,1778638800,1778639100,1778639400,1778639700,1778640000,1778640300,1778640600,1778640900,1778641200,1778641500,1778641800,1778642100,1778642400,1778642700,1778643000,1778643300,1778643600,1778643900,1778644200,1778644500,1778644800,1778645100,1778645400,1778645700,1778646000,1778646300,1778646600,1778652000,1778652300,1778652600,1778652900,1778653200,1778653500,1778653800,1778654100,1778654400,1778654700,1778655000,1778655300,1778655600,1778655900,1778656200,1778656500,1778656800,1778657100,1778657400,1778658300,1778724900,1778725200,1778725500,1778725800,1778726100,1778726400,1778726700,1778727000,1778727300,1778727600,1778727900,1778728200,1778728500,1778728800,1778729100,1778729400,1778729700,1778730000,1778730300,1778730600,1778730900,1778731200,1778731500,1778731800,1778732100,1778732400,1778732700,1778733000,1778738400,1778738700,1778739000,1778739300,1778739600,1778739900,1778740200,1778740500,1778740800,1778741100,1778741400,1778741700,1778742000,1778742300,1778742600,1778742900,1778743200,1778743500,1778743800,1778744700,1778811300,1778811600,1778811900,1778812200,1778812500,1778812800,1778813100,1778813400,1778813700,1778814000,1778814300,1778814600,1778814900,1778815200,1778815500,1778815800,1778816100,1778816400,1778816700,1778817000,1778817300,1778817600,1778817900,1778818200,1778818500,1778818800,1778819100,1778819400,1778824800,1778825100,1778825400,1778825700,1778826000,1778826300,1778826600,1778826900,1778827200,1778827500,1778827800,1778828100,1778828400,1778828700,1778829000,1778829300,1778829600,1778829900,1778830200,1778831100,1779070500,1779070800,1779071100,1779071400,1779071700,1779072000,1779072300,1779072600,1779072900,1779073200,1779073500,1779073800,1779074100,1779074400,1779074700,1779075000,1779075300,1779075600,1779075900,1779076200,1779076500,1779076800,1779077100,1779077400,1779077700,1779078000,1779078300,1779078600,1779084000,1779084300,1779084600,1779084900,1779085200,1779085500,1779085800,1779086100,1779086400,1779086700,1779087000,1779087300,1779087600,1779087900,1779088200,1779088500,1779088800,1779089100,1779089400,1779090300,1779156900,1779157200,1779157500,1779157800,1779158100,1779158400,1779158700,1779159000,1779159300,1779159600,1779159900,1779160200,1779160500,1779160800,1779161100,1779161400,1779161700,1779162000,1779162300,1779162600,1779162900,1779163200,1779163500,1779163800,1779164100,1779164400,1779164700,1779165000,1779170400,1779170700,1779171000,1779171300,1779171600,1779171900,1779172200,1779172500,1779172800,1779173100,1779173400,1779173700,1779174000,1779174300,1779174600,1779174900,1779175200,1779175500,1779175800,1779176700,1779243300,1779243600,1779243900,1779244200,1779244500,1779244800,1779245100,1779245400,1779245700,1779246000,1779246300,1779246600,1779246900,1779247200,1779247500,1779247800,1779248100,1779248400,1779248700,1779249000,1779249300,1779249600,1779249900,1779250200,1779250500,1779250800,1779251100,1779251400,1779256800,1779257100,1779257400,1779257700,1779258000,1779258300,1779258600,1779258900,1779259200,1779259500,1779259800,1779260100,1779260400,1779260700,1779261000,1779261300,1779261600,1779261900,1779262200,1779263100,1779329700,1779330000,1779330300,1779330600,1779330900,1779331200,1779331500,1779331800,1779332100,1779332400,1779332700,1779333000,1779333300,1779333600,1779333900,1779334200,1779334500,1779334800,1779335100,1779335400,1779335700,1779336000,1779336300,1779336600,1779336900,1779337200,1779337500,1779337800,1779343200,1779343500,1779343800,1779344100,1779344400,1779344700,1779345000,1779345300,1779345600,1779345900,1779346200,1779346500,1779346800,1779347100,1779347400,1779347700,1779348000,1779348300,1779348600,1779349500,1779416100,1779416400,1779416700,1779417000,1779417300,1779417600,1779417900,1779418200,1779418500,1779418800,1779419100,1779419400,1779419700,1779420000,1779420300,1779420600,1779420900,1779421200,1779421500,1779421800,1779422100,1779422400,1779422700,1779423000,1779423300,1779423600,1779423900,1779424200,1779429600,1779429900,1779430200,1779430500,1779430800,1779431100,1779431400,1779431700,1779432000,1779432300,1779432600,1779432900,1779433200,1779433500,1779433800,1779434100,1779434400,1779434700,1779435000,1779435900,1779675300,1779675600,1779675900,1779676200,1779676500,1779676800,1779677100,1779677400,1779677700,1779678000,1779678300,1779678600,1779678900,1779679200,1779679500,1779679800,1779680100,1779680400,1779680700,1779681000,1779681300,1779681600,1779681900,1779682200,1779682500,1779682800,1779683100,1779683400,1779688800,1779689100,1779689400,1779689700,1779690000,1779690300,1779690600,1779690900,1779691200,1779691500,1779691800,1779692100,1779692400,1779692700,1779693000,1779693300,1779693600,1779693900,1779694200,1779695100,1779761700,1779762000,1779762300,1779762600,1779762900,1779763200,1779763500,1779763800,1779764100,1779764400,1779764700,1779765000,1779765300,1779765600,1779765900,1779766200,1779766500,1779766800,1779767100,1779767400,1779767700,1779768000,1779768300,1779768600,1779768900,1779769200,1779769500,1779769800,1779775200,1779775500,1779775800,1779776100,1779776400,1779776700,1779777000,1779777300,1779777600,1779777900,1779778200,1779778500,1779778800,1779779100,1779779400,1779779700,1779780000,1779780300,1779780600,1779781500,1779848100,1779848400,1779848700,1779849000,1779849300,1779849600,1779849900,1779850200,1779850500,1779850800,1779851100,1779851400,1779851700,1779852000,1779852300,1779852600,1779852900,1779853200,1779853500,1779853800,1779854100,1779854400,1779854700,1779855000,1779855300,1779855600,1779855900,1779856200,1779861600,1779861900,1779862200,1779862500,1779862800,1779863100,1779863400,1779863700,1779864000,1779864300,1779864600,1779864900,1779865200,1779865500,1779865800,1779866100,1779866400,1779866700,1779867000,1779867900,1779934500,1779934800,1779935100,1779935400,1779935700,1779936000,1779936300,1779936600,1779936900,1779937200,1779937500,1779937800,1779938100,1779938400,1779938700,1779939000,1779939300,1779939600,1779939900,1779940200,1779940500,1779940800,1779941100,1779941400,1779941700,1779942000,1779942300,1779942600,1779948000,1779948300,1779948600,1779948900,1779949200,1779949500,1779949800,1779950100,1779950400,1779950700,1779951000,1779951300,1779951600,1779951900,1779952200,1779952500,1779952800,1779953100,1779953400,1779954300,1780020900,1780021200,1780021500,1780021800,1780022100,1780022400,1780022700,1780023000,1780023300,1780023600,1780023900,1780024200,1780024500,1780024800,1780025100,1780025400,1780025700,1780026000,1780026300,1780026600,1780026900,1780027200,1780027500,1780027800,1780028100,1780028400,1780028700,1780029000,1780034400,1780034700,1780035000,1780035300,1780035600,1780035900,1780036200,1780036500,1780036800,1780037100,1780037400,1780037700,1780038000,1780038300,1780038600,1780038900,1780039200,1780039500,1780039800,1780040700,1780280100,1780280400,1780280700,1780281000,1780281300,1780281600,1780281900,1780282200,1780282500,1780282800,1780283100,1780283400,1780283700,1780284000,1780284300,1780284600,1780284900,1780285200,1780285500,1780285800,1780286100,1780286400,1780286700,1780287000,1780287300,1780287600,1780287900,1780288200,1780293600,1780293900,1780294200,1780294500,1780294800,1780295100,1780295400,1780295700,1780296000,1780296300,1780296600,1780296900,1780297200,1780297500,1780297800,1780298100,1780298400,1780298700,1780299000,1780299900,1780366500,1780366800,1780367100,1780367400,1780367700,1780368000,1780368300,1780368600,1780368900,1780369200,1780369500,1780369800,1780370100,1780370400,1780370700,1780371000,1780371300,1780371600,1780371900,1780372200,1780372500,1780372800,1780373100,1780373400,1780373700,1780374000,1780374300,1780374600,1780380000,1780380300,1780380600,1780380900,1780381200,1780381500,1780381800,1780382100,1780382400,1780382700,1780383000,1780383300,1780383600,1780383900,1780384200,1780384500,1780384800,1780385100,1780385400,1780386300,1780452900,1780453200,1780453500,1780453800,1780454100,1780454400,1780454700,1780455000,1780455300,1780455600,1780455900,1780456200,1780456500,1780456800,1780457100,1780457400,1780457700,1780458000,1780458300,1780458600,1780458900,1780459200,1780459500,1780459800,1780460100,1780460400,1780460700,1780461000,1780466400,1780466700,1780467000,1780467300,1780467600,1780467900,1780468200,1780468500,1780468800,1780469100,1780469400,1780469700,1780470000,1780470300,1780470600,1780470900,1780471200,1780471500,1780471800,1780472700,1780539300,1780539600,1780539900,1780540200,1780540500,1780540800,1780541100,1780541400,1780541700,1780542000,1780542300,1780542600,1780542900,1780543200,1780543500,1780543800,1780544100,1780544400,1780544700,1780545000,1780545300,1780545600,1780545900,1780546200,1780546500,1780546800,1780547100,1780547400,1780552800,1780553100,1780553400,1780553700,1780554000,1780554300,1780554600,1780554900,1780555200,1780555500,1780555800,1780556100,1780556400,1780556700,1780557000,1780557300,1780557600,1780557900,1780558200,1780559100,1780625700,1780626000,1780626300,1780626600,1780626900,1780627200,1780627500,1780627800,1780628100,1780628400,1780628700,1780629000,1780629300,1780629600,1780629900,1780630200,1780630500,1780630800,1780631100,1780631400,1780631700,1780632000,1780632300,1780632600,1780632900,1780633200,1780633500,1780633800,1780639200,1780639500,1780639800,1780640100,1780640400,1780640700,1780641000,1780641300,1780641600,1780641900,1780642200,1780642500,1780642800,1780643100,1780643400,1780643700,1780644000,1780644300,1780644600,1780645500,1780884900,1780885200,1780885500,1780885800,1780886100,1780886400,1780886700,1780887000,1780887300,1780887600,1780887900,1780888200,1780888500,1780888800,1780889100,1780889400,1780889700,1780890000,1780890300,1780890600,1780890900,1780891200,1780891500,1780891800,1780892100,1780892400,1780892700,1780893000,1780898400,1780898700,1780899000,1780899300,1780899600,1780899900,1780900200,1780900500,1780900800,1780901100,1780901400,1780901700,1780902000,1780902300,1780902600,1780902900,1780903200,1780903500,1780903800,1780904700,1780971300,1780971600,1780971900,1780972200,1780972500,1780972800,1780973100,1780973400,1780973700,1780974000,1780974300,1780974600,1780974900,1780975200,1780975500,1780975800,1780976100,1780976400,1780976700,1780977000,1780977300,1780977600,1780977900,1780978200,1780978500,1780978800,1780979100,1780979400,1780984800,1780985100,1780985400,1780985700,1780986000,1780986300,1780986600,1780986900,1780987200,1780987500,1780987800,1780988100,1780988400,1780988700,1780989000,1780989300,1780989600,1780989900,1780990200,1780991100,1781057700,1781058000,1781058300,1781058600,1781058900,1781059200,1781059500,1781059800,1781060100,1781060400,1781060700,1781061000,1781061300,1781061600,1781061900,1781062200,1781062500,1781062800,1781063100,1781063400,1781063700,1781064000,1781064300,1781064600,1781064900,1781065200,1781065500,1781065800,1781071200,1781071500,1781071800,1781072100,1781072400,1781072700,1781073000,1781073300,1781073600,1781073900,1781074200,1781074500,1781074800,1781075100,1781075400,1781075700,1781076000,1781076300,1781076600,1781077500,1781144100,1781144400,1781144700,1781145000,1781145300,1781145600,1781145900,1781146200,1781146500,1781146800,1781147100,1781147400,1781147700,1781148000,1781148300,1781148600,1781148900,1781149200,1781149500,1781149800,1781150100,1781150400,1781150700,1781151000,1781151300,1781151600,1781151900,1781152200,1781157600,1781157900,1781158200,1781158500,1781158800,1781159100,1781159400,1781159700,1781160000,1781160300,1781160600,1781160900,1781161200,1781161500,1781161800,1781162100,1781162400,1781162700,1781163000,1781163900,1781230500,1781230800,1781231100,1781231400,1781231700,1781232000,1781232300,1781232600,1781232900,1781233200,1781233500,1781233800,1781234100,1781234400,1781234700,1781235000,1781235300,1781235600,1781235900,1781236200,1781236500,1781236800,1781237100,1781237400,1781237700,1781238000,1781238300,1781238600,1781244000,1781244300,1781244600,1781244900,1781245200,1781245500,1781245800,1781246100,1781246400,1781246700,1781247000,1781247300,1781247600,1781247900,1781248200,1781248500,1781248800,1781249100,1781249400,1781250300,1781489700,1781490000,1781490300,1781490600,1781490900,1781491200,1781491500,1781491800,1781492100,1781492400,1781492700,1781493000,1781493300,1781493600,1781493900,1781494200,1781494500,1781494800,1781495100,1781495400,1781495700,1781496000,1781496300,1781496600,1781496900,1781497200,1781497500,1781497800,1781503200,1781503500,1781503800,1781504100,1781504400,1781504700,1781505000,1781505300,1781505600,1781505900,1781506200,1781506500,1781506800,1781507100,1781507400,1781507700,1781508000,1781508300,1781508600,1781509500,1781575200,1781575500,1781575800,1781576100,1781576400,1781576700,1781577000,1781577300,1781577600,1781577900,1781578200,1781578500,1781578800,1781579100,1781579400,1781579700,1781580000,1781580300,1781580600,1781580900,1781581200,1781581500,1781581800,1781582100,1781582400,1781582700,1781583000,1781583300,1781583600,1781583900,1781584200,1781589600,1781589900,1781590200,1781590500,1781590800,1781591100,1781591400,1781591700,1781592000,1781592300,1781592600,1781592900,1781593200,1781593500,1781593800,1781594100,1781594400,1781594700,1781595000,1781595300,1781595900,1781597100,1781661600,1781661900,1781662500,1781662800,1781663100,1781663400,1781663700,1781664000,1781664300,1781664600,1781664900,1781665200,1781665500,1781665800,1781666100,1781666400,1781666700,1781667000,1781667300,1781667600,1781667900,1781668200,1781668500,1781668800,1781669100,1781669400,1781669700,1781670000,1781670300,1781670600,1781676000,1781676300,1781676600,1781676900,1781677200,1781677500,1781677800,1781678100,1781678400,1781678700,1781679000,1781679300,1781679600,1781679900,1781680200,1781680500,1781680800,1781681100,1781681400,1781681700,1781682000,1781682300,1781683500,1781748000,1781748900,1781749200,1781749500,1781749800,1781750100,1781750400,1781750700,1781751000,1781751300,1781751600,1781751900,1781752200,1781752500,1781752800,1781753100,1781753400,1781753700,1781754000,1781754300,1781754600,1781754900,1781755200,1781755500,1781755800,1781756100,1781756400,1781756700,1781757000,1781762400,1781762700,1781763000,1781763300,1781763600,1781763900,1781764200,1781764500,1781764800,1781765100,1781765400,1781765700,1781766000,1781766300,1781766600,1781766900,1781767200,1781767500,1781767800,1781768100,1781768400,1781768700,1781769900,1781834400,1781835300,1781835600,1781835900,1781836200,1781836500,1781836800,1781837100,1781837400,1781837700,1781838000,1781838300,1781838600,1781838900,1781839200,1781839500,1781839800,1781840100,1781840400,1781840700,1781841000,1781841300,1781841600,1781841900,1781842200,1781842500,1781842800,1781843100,1781843400,1781848800,1781849100,1781849400,1781849700,1781850000,1781850300,1781850600,1781850900,1781851200,1781851500,1781851800,1781852100,1781852400,1781852700,1781853000,1781853300,1781853600,1781853900,1781854200,1781854500,1781855100,1781856300,1782093600,1782093900,1782094200,1782094500,1782094800,1782095100,1782095400,1782095700,1782096000,1782096300,1782096600,1782096900,1782097200,1782097500,1782097800,1782098100,1782098400,1782098700,1782099000,1782099300,1782099600,1782099900,1782100200,1782100500,1782100800,1782101100,1782101400,1782101700,1782102000,1782102300,1782102600,1782108000,1782108300,1782108600,1782108900,1782109200,1782109500,1782109800,1782110100,1782110400,1782110700,1782111000,1782111300,1782111600,1782111900,1782112200,1782112500,1782112800,1782113100,1782113400,1782113700,1782114300,1782115500,1782180000,1782180300,1782180900,1782181200,1782181500,1782181800,1782182100,1782182400,1782182700,1782183000,1782183300,1782183600,1782183900,1782184200,1782184500,1782184800,1782185100,1782185400,1782185700,1782186000,1782186300,1782186600,1782186900,1782187200,1782187500,1782187800,1782188100,1782188400,1782188700,1782189000,1782194400,1782194700,1782195000,1782195300,1782195600,1782195900,1782196200,1782196500,1782196800,1782197100,1782197400,1782197700,1782198000,1782198300,1782198600,1782198900,1782199200,1782199500,1782199800,1782200700,1782201900,1782266400,1782267000,1782267300,1782267600,1782267900,1782268200,1782268500,1782268800,1782269100,1782269400,1782269700,1782270000,1782270300,1782270600,1782270900,1782271200,1782271500,1782271800,1782272100,1782272400,1782272700,1782273000,1782273300,1782273600,1782273900,1782274200,1782274500,1782274800,1782275100,1782275400,1782280800,1782281100,1782281400,1782281700,1782282000,1782282300,1782282600,1782282900,1782283200,1782283500,1782283800,1782284100,1782284400,1782284700,1782285000,1782285300,1782285600,1782285900,1782286200,1782286500,1782286800,1782287100,1782288300,1782352800,1782353400,1782353700,1782354000,1782354300,1782354600,1782354900,1782355200,1782355500,1782355800,1782356100,1782356400,1782356700,1782357000,1782357300,1782357600,1782357900,1782358200,1782358500,1782358800,1782359100,1782359400,1782359700,1782360000,1782360300,1782360600,1782360900,1782361200,1782361500,1782361800,1782367200,1782367500,1782367800,1782368100,1782368400,1782368700,1782369000,1782369300,1782369600,1782369900,1782370200,1782370500,1782370800,1782371100,1782371400,1782371700,1782372000,1782372300,1782372600,1782372900,1782373200,1782373500,1782374700,1782439200,1782439500,1782440100,1782440400,1782440700,1782441000,1782441300,1782441600,1782441900,1782442200,1782442500,1782442800,1782443100,1782443400,1782443700,1782444000,1782444300,1782444600,1782444900,1782445200,1782445500,1782445800,1782446100,1782446400,1782446700,1782447000,1782447300,1782447600,1782447900,1782448200,1782453600,1782453900,1782454200,1782454500,1782454800,1782455100,1782455400,1782455700,1782456000,1782456300,1782456600,1782456900,1782457200,1782457500,1782457800,1782458100,1782458400,1782458700,1782459000,1782459300,1782459600,1782459900,1782461100,1782698400,1782699300,1782699600,1782699900,1782700200,1782700500,1782700800,1782701100,1782701400,1782701700,1782702000,1782702300,1782702600,1782702900,1782703200,1782703500,1782703800,1782704100,1782704400,1782704700,1782705000,1782705300,1782705600,1782705900,1782706200,1782706500,1782706800,1782707100,1782707400,1782712800,1782713100,1782713400,1782713700,1782714000,1782714300,1782714600,1782714900,1782715200,1782715500,1782715800,1782716100,1782716400,1782716700,1782717000,1782717300,1782717600,1782717900,1782718200,1782718500,1782718800,1782719100,1782720300,1782785400,1782785700,1782786000,1782786300,1782786600,1782786900,1782787200,1782787500,1782787800,1782788100,1782788400,1782788700,1782789000,1782789300,1782789600,1782789900,1782790200,1782790500,1782790800,1782791100,1782791400,1782791700,1782792000,1782792300,1782792600,1782792900,1782793200,1782793500,1782793800,1782799200,1782799500,1782799800,1782800100,1782800400,1782800700,1782801000,1782801300,1782801600,1782801900,1782802200,1782802500,1782802800,1782803100,1782803400,1782803700,1782804000,1782804300,1782804600,1782804900,1782805200,1782805500,1782806700,1782871200,1782871800,1782872100,1782872400,1782872700,1782873000,1782873300,1782873600,1782873900,1782874200,1782874500,1782874800,1782875100,1782875400,1782875700,1782876000,1782876300,1782876600,1782876900,1782877200,1782877500,1782877800,1782878100,1782878400,1782878700,1782879000,1782879300,1782879600,1782879900,1782880200,1782885600,1782885900,1782886200,1782886500,1782886800,1782887100,1782887400,1782887700,1782888000,1782888300,1782888600,1782888900,1782889200,1782889500,1782889800,1782890100,1782890400,1782890700,1782891000,1782891300,1782891600,1782891900,1782893100,1782957600,1782958200,1782958500,1782958800,1782959100,1782959400,1782959700,1782960000,1782960300,1782960600,1782960900,1782961200,1782961500,1782961800,1782962100,1782962400,1782962700,1782963000,1782963300,1782963600,1782963900,1782964200,1782964500,1782964800,1782965100,1782965400,1782965700,1782966000,1782966300,1782966600,1782972000,1782972300,1782972600,1782972900,1782973200,1782973500,1782973800,1782974100,1782974400,1782974700,1782975000,1782975300,1782975600,1782975900,1782976200,1782976500,1782976800,1782977100,1782977400,1782978000,1782978300,1782979500,1783044000,1783044600,1783044900,1783045200,1783045500,1783045800,1783046100,1783046400,1783046700,1783047000,1783047300,1783047600,1783047900,1783048200,1783048500,1783048800,1783049100,1783049400,1783049700,1783050000,1783050300,1783050600,1783050900,1783051200,1783051500,1783051800,1783052100,1783052400,1783052700,1783053000,1783058400,1783058700,1783059000,1783059300,1783059600,1783059900,1783060200,1783060500,1783060800,1783061100,1783061400,1783061700,1783062000,1783062300,1783062600,1783062900,1783063200,1783063500,1783063800,1783064100,1783064400,1783064700,1783065900,1783303200,1783304100,1783304400,1783304700,1783305000,1783305300,1783305600,1783305900,1783306200,1783306500,1783306800,1783307100,1783307400,1783307700,1783308000,1783308300,1783308600,1783308900,1783309200,1783309500,1783309800,1783310100,1783310400,1783310700,1783311000,1783311300,1783311600,1783311900,1783312200,1783317600,1783317900,1783318200,1783318500,1783318800,1783319100,1783319400,1783319700,1783320000,1783320300,1783320600,1783320900,1783321200,1783321500,1783321800,1783322100,1783322400,1783322700,1783323000,1783323600,1783323900,1783325100,1783389600,1783390500,1783390800,1783391100,1783391400,1783391700,1783392000,1783392300,1783392600,1783392900,1783393200,1783393500,1783393800,1783394100,1783394400,1783394700,1783395000,1783395300,1783395600,1783395900,1783396200,1783396500,1783396800,1783397100,1783397400,1783397700,1783398000,1783398300,1783398600,1783404000,1783404300,1783404600,1783404900,1783405200,1783405500,1783405800,1783406100,1783406400,1783406700,1783407000,1783407300,1783407600,1783407900,1783408200,1783408500,1783408800,1783409100,1783409400,1783409700,1783410000,1783410300,1783411500,1783476600,1783476900,1783477200,1783477500,1783477800,1783478100,1783478400,1783478700,1783479000,1783479300,1783479600,1783479900,1783480200,1783480500,1783480800,1783481100,1783481400,1783481700,1783482000,1783482300,1783482600,1783482900,1783483200,1783483500,1783483800,1783484100,1783484400,1783484700,1783485000,1783490400,1783490700,1783491000,1783491300,1783491600,1783491900,1783492200,1783492500,1783492800,1783493100,1783493400,1783493700,1783494000,1783494300,1783494600,1783494900,1783495200,1783495500,1783495800,1783496700,1783497900,1783562400,1783563300,1783563600,1783563900,1783564200,1783564500,1783564800,1783565100,1783565400,1783565700,1783566000,1783566300,1783566600,1783566900,1783567200,1783567500,1783567800,1783568100,1783568400,1783568700,1783569000,1783569300,1783569600,1783569900,1783570200,1783570500,1783570800,1783571100,1783571400,1783576800,1783577100,1783577400,1783577700,1783578000,1783578300,1783578600,1783578900,1783579200,1783579500,1783579800,1783580100,1783580400,1783580700,1783581000,1783581300,1783581600,1783581900,1783582200,1783582500,1783582800,1783583100,1783584300,1783649400,1783649700,1783650000,1783650300,1783650600,1783650900,1783651200,1783651500,1783651800,1783652100,1783652400,1783652700,1783653000,1783653300,1783653600,1783653900,1783654200,1783654500,1783654800,1783655100,1783655400,1783655700,1783656000,1783656300,1783656600,1783656900,1783657200,1783657500,1783657800,1783663200,1783663500,1783663800,1783664100,1783664400,1783664700,1783665000,1783665300,1783665600,1783665900,1783666200,1783666500,1783666800,1783667100,1783667400,1783667700,1783668000,1783668300,1783668600,1783668900,1783669200,1783669500,1783670700,1783908300,1783908900,1783909200,1783909500,1783909800,1783910100,1783910400,1783910700,1783911000,1783911300,1783911600,1783911900,1783912200,1783912500,1783912800,1783913100,1783913400,1783913700,1783914000,1783914300,1783914600,1783914900,1783915200,1783915500,1783915800,1783916100,1783916400,1783916700,1783917000,1783922400,1783922700,1783923000,1783923300,1783923600,1783923900,1783924200,1783924500,1783924800,1783925100,1783925400,1783925700,1783926000,1783926300,1783926600,1783926900,1783927200,1783927500,1783927800,1783928100,1783928400,1783928700,1783929900,1783994400,1783995000,1783995300,1783995600,1783995900,1783996200,1783996500,1783996800,1783997100,1783997400,1783997700,1783998000,1783998300,1783998600,1783998900,1783999200,1783999500,1783999800,1784000100,1784000400,1784000700,1784001000,1784001300,1784001600,1784001900,1784002200,1784002500,1784002800,1784003100,1784003400,1784008800,1784009100,1784009400,1784009700,1784010000,1784010300,1784010600,1784010900,1784011200,1784011500,1784011800,1784012100,1784012400,1784012700,1784013000,1784013300,1784013600,1784013900,1784014200,1784014500,1784015100,1784016300,1784081400,1784081700,1784082000,1784082300,1784082600,1784082900,1784083200,1784083500,1784083800,1784084100,1784084400,1784084700,1784085000,1784085300,1784085600,1784085900,1784086200,1784086500,1784086800,1784087100,1784087400,1784087700,1784088000,1784088300,1784088600,1784088900,1784089200,1784089500,1784089800,1784095200,1784095500,1784095800,1784096100,1784096400,1784096700,1784097000,1784097300,1784097600,1784097900,1784098200,1784098500,1784098800,1784099100,1784099400,1784099700,1784100000,1784100300,1784100600,1784100900,1784101200,1784101500,1784102700,1784167200,1784168100,1784168400,1784168700,1784169000,1784169300,1784169600,1784169900,1784170200,1784170500,1784170800,1784171100,1784171400,1784171700,1784172000,1784172300,1784172600,1784172900,1784173200,1784173500,1784173800,1784174100,1784174400,1784174700,1784175000,1784175300,1784175600,1784175900,1784176200,1784181600,1784181900,1784182200,1784182500,1784182800,1784183100,1784183400,1784183700,1784184000,1784184300,1784184600,1784184900,1784185200,1784185500,1784185800,1784186100,1784186400,1784186700,1784187000,1784187300,1784187600,1784187900,1784189100,1784254500,1784254800,1784255100,1784255400,1784255700,1784256000,1784256300,1784256600,1784256900,1784257200,1784257500,1784257800,1784258100,1784258400,1784258700,1784259000,1784259300,1784259600,1784259900,1784260200,1784260500,1784260800,1784261100,1784261400,1784261700,1784262000,1784262300,1784262600,1784268000,1784268300,1784268600,1784268900,1784269200,1784269500,1784269800,1784270100,1784270400,1784270700,1784271000,1784271300,1784271600,1784271900,1784272200,1784272500,1784272800,1784273100,1784273400,1784273700,1784274300,1784275500,1784512800,1784513700,1784514000,1784514300,1784514600,1784514900,1784515200,1784515500,1784515800,1784516100,1784516400,1784516700,1784517000,1784517300,1784517600,1784517900,1784518200,1784518500,1784518800,1784519100,1784519400,1784519700,1784520000,1784520300,1784520600,1784520900,1784521200,1784521500,1784521800,1784527200,1784527500,1784527800,1784528100,1784528400,1784528700,1784529000,1784529300,1784529600,1784529900,1784530200,1784530500,1784530800,1784531100,1784531400,1784531700,1784532000,1784532300,1784532600,1784532900,1784533200,1784533500,1784534700,1784599200,1784600100,1784600400,1784600700,1784601000,1784601300,1784601600,1784601900,1784602200,1784602500,1784602800,1784603100,1784603400,1784603700,1784604000,1784604300,1784604600,1784604900,1784605200,1784605500,1784605800,1784606100,1784606400,1784606700,1784607000,1784607300,1784607600,1784607900,1784608200,1784613600,1784613900,1784614200,1784614500,1784614800,1784615100,1784615400,1784615700,1784616000,1784616300,1784616600,1784616900,1784617200,1784617500,1784617800,1784618100,1784618400,1784618700,1784619000,1784619300,1784619600,1784619900,1784621100,1784685600,1784686500,1784686800,1784687100,1784687400,1784687700,1784688000,1784688300,1784688600,1784688900,1784689200,1784689500,1784689800,1784690100,1784690400,1784690700,1784691000,1784691300,1784691600,1784691900,1784692200,1784692500,1784692800,1784693100,1784693400,1784693700,1784694000,1784694300,1784694600,1784700000,1784700300,1784700600,1784700900,1784701200,1784701500,1784701800,1784702100,1784702400,1784702700,1784703000,1784703300,1784703600,1784703900,1784704200,1784704500,1784704800,1784705100,1784705400,1784705700,1784706000,1784706300,1784707500,1784772000,1784772600,1784772900,1784773200,1784773500,1784773800,1784774100,1784774400,1784774700,1784775000,1784775300,1784775600,1784775900,1784776200,1784776500,1784776800,1784777100,1784777400,1784777700,1784778000,1784778300,1784778600,1784778900,1784779200,1784779500,1784779800,1784780100,1784780400,1784780700,1784781000,1784786400,1784786700,1784787000,1784787300,1784787600,1784787900,1784788200,1784788500,1784788800,1784789100,1784789400,1784789700,1784790000,1784790300,1784790600,1784790900,1784791200,1784791500,1784791800,1784792100,1784792400,1784792700,1784793900,1784858400,1784859000,1784859300,1784859600,1784859900,1784860200,1784860500,1784860800,1784861100,1784861400,1784861700,1784862000,1784862300,1784862600,1784862900,1784863200,1784863500,1784863800,1784864100,1784864400,1784864700,1784865000,1784865300,1784865600,1784865900,1784866200,1784866500,1784866800,1784867100,1784867400,1784872800,1784873100,1784873400,1784873700,1784874000,1784874300,1784874600,1784874900,1784875200,1784875500,1784875800,1784876100,1784876400,1784876700,1784877000,1784877300,1784877600,1784877900,1784878200,1784878800,1784879100,1784880300,1785117600,1785118500,1785118800,1785119100,1785119400,1785119700,1785120000,1785120300,1785120600,1785120900,1785121200,1785121500,1785121800,1785122100,1785122400,1785122700,1785123000,1785123300,1785123600,1785123900,1785124200,1785124500,1785124800,1785125100,1785125400,1785125700,1785126000,1785126300,1785126600,1785132000,1785132300,1785132600,1785132900,1785133200,1785133500,1785133800,1785134100,1785134400,1785134700,1785135000,1785135300,1785135600,1785135900,1785136200,1785136500,1785136800,1785137100,1785137400,1785137700,1785138000,1785138300,1785139500,1785204000,1785204300,1785204600,1785204900,1785205200,1785205500,1785205800,1785206100,1785206400,1785206700,1785207000,1785207300,1785207600,1785207900,1785208200,1785208500,1785208800,1785209100,1785209400,1785209700,1785210000,1785210300,1785210600,1785210900,1785211200,1785211500,1785211800,1785212100,1785212400,1785212700,1785213000,1785218400,1785218700,1785219000,1785219300,1785219600,1785219900,1785220200,1785220500,1785220800,1785221100,1785221400,1785221700,1785222000,1785222300,1785222600,1785222900,1785223200,1785223500,1785223800,1785224100,1785224400,1785224700,1785225900,1785290400,1785290700,1785291300,1785291600,1785291900,1785292200,1785292500,1785292800,1785293100,1785293400,1785293700,1785294000,1785294300,1785294600,1785294900,1785295200,1785295500,1785295800,1785296100,1785296400,1785296700,1785297000,1785297300,1785297600,1785297900,1785298200,1785298500,1785298800,1785299100,1785299400,1785304800,1785305100,1785305400,1785305700,1785306000,1785306300,1785306600,1785306900,1785307200,1785307500,1785307800,1785308100,1785308400,1785308700,1785309000,1785309300,1785309600,1785309900,1785310200,1785310800,1785311100,1785312300,1785376800,1785377700,1785378000,1785378300,1785378600,1785378900,1785379200,1785379500,1785379800,1785380100,1785380400,1785380700,1785381000,1785381300,1785381600,1785381900,1785382200,1785382500,1785382800,1785383100,1785383400,1785383700,1785384000,1785384300,1785384600,1785384900,1785385200,1785385500,1785385800,1785391200,1785391500,1785391800,1785392100,1785392400,1785392700,1785393000,1785393300,1785393600,1785393900,1785394200,1785394500,1785394800,1785395100,1785395400,1785395700,1785396000,1785396300,1785396600,1785396900,1785397200,1785397500,1785398700,1785463200,1785463800,1785464100,1785464400,1785464700,1785465000,1785465300,1785465600,1785465900,1785466200,1785466500,1785466800,1785467100,1785467400,1785467700,1785468000,1785468300,1785468600,1785468900,1785469200,1785469500,1785469800,1785470100,1785470400,1785470700,1785471000,1785471300,1785471600,1785471900,1785472200,1785477600,1785477900,1785478200,1785478500,1785478800,1785479100,1785479400,1785479700,1785480000,1785480300,1785480600,1785480900,1785481200,1785481500,1785481800,1785482100,1785482400,1785482700,1785483000,1785483300,1785483600,1785483900,1785485100,1785722400,1785723300,1785723600,1785723900,1785724200,1785724500,1785724800,1785725100,1785725400,1785725700,1785726000,1785726300,1785726600,1785726900,1785727200,1785727500,1785727800,1785728100,1785728400,1785728700,1785729000,1785729300,1785729600,1785729900,1785730200,1785730500,1785730800,1785731100,1785731400,1785736800,1785737100,1785737400,1785737700,1785738000,1785738300,1785738600,1785738900,1785739200,1785739500,1785739800,1785740100,1785740400,1785740700,1785741000,1785741300,1785741600,1785741900,1785742200,1785742500,1785742800,1785743100,1785744300,1785808800,1785809400,1785809700,1785810000,1785810300,1785810600,1785810900,1785811200,1785811500,1785811800,1785812100,1785812400,1785812700,1785813000,1785813300,1785813600,1785813900,1785814200,1785814500,1785814800,1785815100,1785815400,1785815700,1785816000,1785816300,1785816600,1785816900,1785817200,1785817500,1785817800,1785823200,1785823500,1785823800,1785824100,1785824400,1785824700,1785825000,1785825300,1785825600,1785825900,1785826200,1785826500,1785826800,1785827100,1785827400,1785827700,1785828000,1785828300,1785828600,1785828900,1785829200,1785829500,1785830700,1785895200,1785895500,1785896100,1785896400,1785896700,1785897000,1785897300,1785897600,1785897900,1785898200,1785898500,1785898800,1785899100,1785899400,1785899700,1785900000,1785900300,1785900600,1785900900,1785901200,1785901500,1785901800,1785902100,1785902400,1785902700,1785903000,1785903300,1785903600,1785903900,1785904200,1785909600,1785909900,1785910200,1785910500,1785910800,1785911100,1785911400,1785911700,1785912000,1785912300,1785912600,1785912900,1785913200,1785913500,1785913800,1785914100,1785914400,1785914700,1785915000,1785915300,1785915600,1785915900,1785917100,1785981600,1785982500,1785982800,1785983100,1785983400,1785983700,1785984000,1785984300,1785984600,1785984900,1785985200,1785985500,1785985800,1785986100,1785986400,1785986700,1785987000,1785987300,1785987600,1785987900,1785988200,1785988500,1785988800,1785989100,1785989400,1785989700,1785990000,1785990300,1785990600,1785996000,1785996300,1785996600,1785996900,1785997200,1785997500,1785997800,1785998100,1785998400,1785998700,1785999000,1785999300,1785999600,1785999900,1786000200,1786000500,1786000800,1786001100,1786001400,1786001700,1786002000,1786002300,1786003500,1786068000,1786068300,1786068900,1786069200,1786069500,1786069800,1786070100,1786070400,1786070700,1786071000,1786071300,1786071600,1786071900,1786072200,1786072500,1786072800,1786073100,1786073400,1786073700,1786074000,1786074300,1786074600,1786074900,1786075200,1786075500,1786075800,1786076100,1786076400,1786076700,1786077000,1786082400,1786082700,1786083000,1786083300,1786083600,1786083900,1786084200,1786084500,1786084800,1786085100,1786085400,1786085700,1786086000,1786086300,1786086600,1786086900,1786087200,1786087500,1786087800,1786088100,1786088400,1786088700,1786089900,1786327200,1786327800,1786328100,1786328400,1786328700,1786329000,1786329300,1786329600,1786329900,1786330200,1786330500,1786330800,1786331100,1786331400,1786331700,1786332000,1786332300,1786332600,1786332900,1786333200,1786333500,1786333800,1786334100,1786334400,1786334700,1786335000,1786335300,1786335600,1786335900,1786336200,1786341600,1786341900,1786342200,1786342500,1786342800,1786343100,1786343400,1786343700,1786344000,1786344300,1786344600,1786344900,1786345200,1786345500,1786345800,1786346100,1786346400,1786346700,1786347000,1786347300,1786347600,1786347900,1786349100,1786413900,1786414500,1786414800,1786415100,1786415400,1786415700,1786416000,1786416300,1786416600,1786416900,1786417200,1786417500,1786417800,1786418100,1786418400,1786418700,1786419000,1786419300,1786419600,1786419900,1786420200,1786420500,1786420800,1786421100,1786421400,1786421700,1786422000,1786422300,1786422600,1786428000,1786428300,1786428600,1786428900,1786429200,1786429500,1786429800,1786430100,1786430400,1786430700,1786431000,1786431300,1786431600,1786431900,1786432200,1786432500,1786432800,1786433100,1786433400,1786434300,1786435500,1786500000,1786500300,1786500600,1786500900,1786501200,1786501500,1786501800,1786502100,1786502400,1786502700,1786503000,1786503300,1786503600,1786503900,1786504200,1786504500,1786504800,1786505100,1786505400,1786505700,1786506000,1786506300,1786506600,1786506900,1786507200,1786507500,1786507800,1786508100,1786508400,1786508700,1786509000,1786514400,1786514700,1786515000,1786515300,1786515600,1786515900,1786516200,1786516500,1786516800,1786517100,1786517400,1786517700,1786518000,1786518300,1786518600,1786518900,1786519200,1786519500,1786519800,1786520100,1786520400,1786520700,1786521900,1786586400,1786587300,1786587600,1786587900,1786588200,1786588500,1786588800,1786589100,1786589400,1786589700,1786590000,1786590300,1786590600,1786590900,1786591200,1786591500,1786591800,1786592100,1786592400,1786592700,1786593000,1786593300,1786593600,1786593900,1786594200,1786594500,1786594800,1786595100,1786595400,1786600800,1786601100,1786601400,1786601700,1786602000,1786602300,1786602600,1786602900,1786603200,1786603500,1786603800,1786604100,1786604400,1786604700,1786605000,1786605300,1786605600,1786605900,1786606200,1786606500,1786606800,1786607100,1786608300,1786672800,1786673100,1786673700,1786674000,1786674300,1786674600,1786674900,1786675200,1786675500,1786675800,1786676100,1786676400,1786676700,1786677000,1786677300,1786677600,1786677900,1786678200,1786678500,1786678800,1786679100,1786679400,1786679700,1786680000,1786680300,1786680600,1786680900,1786681200,1786681500,1786681800,1786687200,1786687500,1786687800,1786688100,1786688400,1786688700,1786689000,1786689300,1786689600,1786689900,1786690200,1786690500,1786690800,1786691100,1786691400,1786691700,1786692000,1786692300,1786692600,1786692900,1786693200,1786693500,1786694700,1786932000,1786932900,1786933200,1786933500,1786933800,1786934100,1786934400,1786934700,1786935000,1786935300,1786935600,1786935900,1786936200,1786936500,1786936800,1786937100,1786937400,1786937700,1786938000,1786938300,1786938600,1786938900,1786939200,1786939500,1786939800,1786940100,1786940400,1786940700,1786941000,1786946400,1786946700,1786947000,1786947300,1786947600,1786947900,1786948200,1786948500,1786948800,1786949100,1786949400,1786949700,1786950000,1786950300,1786950600,1786950900,1786951200,1786951500,1786951800,1786952100,1786952400,1786952700,1786953900,1787018400,1787019300,1787019600,1787019900,1787020200,1787020500,1787020800,1787021100,1787021400,1787021700,1787022000,1787022300,1787022600,1787022900,1787023200,1787023500,1787023800,1787024100,1787024400,1787024700,1787025000,1787025300,1787025600,1787025900,1787026200,1787026500,1787026800,1787027100,1787027400,1787032800,1787033100,1787033400,1787033700,1787034000,1787034300,1787034600,1787034900,1787035200,1787035500,1787035800,1787036100,1787036400,1787036700,1787037000,1787037300,1787037600,1787037900,1787038200,1787038800,1787039100,1787040300,1787104800,1787105400,1787105700,1787106000,1787106300,1787106600,1787106900,1787107200,1787107500,1787107800,1787108100,1787108400,1787108700,1787109000,1787109300,1787109600,1787109900,1787110200,1787110500,1787110800,1787111100,1787111400,1787111700,1787112000,1787112300,1787112600,1787112900,1787113200,1787113500,1787113800,1787119200,1787119500,1787119800,1787120100,1787120400,1787120700,1787121000,1787121300,1787121600,1787121900,1787122200,1787122500,1787122800,1787123100,1787123400,1787123700,1787124000,1787124300,1787124600,1787124900,1787125200,1787125500,1787126700,1787191200,1787191500,1787192100,1787192400,1787192700,1787193000,1787193300,1787193600,1787193900,1787194200,1787194500,1787194800,1787195100,1787195400,1787195700,1787196000,1787196300,1787196600,1787196900,1787197200,1787197500,1787197800,1787198100,1787198400,1787198700,1787199000,1787199300,1787199600,1787199900,1787200200,1787205600,1787205900,1787206200,1787206500,1787206800,1787207100,1787207400,1787207700,1787208000,1787208300,1787208600,1787208900,1787209200,1787209500,1787209800,1787210100,1787210400,1787210700,1787211000,1787211300,1787211600,1787211900,1787213100,1787277900,1787278500,1787278800,1787279100,1787279400,1787279700,1787280000,1787280300,1787280600,1787280900,1787281200,1787281500,1787281800,1787282100,1787282400,1787282700,1787283000,1787283300,1787283600,1787283900,1787284200,1787284500,1787284800,1787285100,1787285400,1787285700,1787286000,1787286300,1787286600,1787292000,1787292300,1787292600,1787292900,1787293200,1787293500,1787293800,1787294100,1787294400,1787294700,1787295000,1787295300,1787295600,1787295900,1787296200,1787296500,1787296800,1787297100,1787297400,1787297700,1787298000,1787298300,1787299500,1787536800,1787537400,1787537700,1787538000,1787538300,1787538600,1787538900,1787539200,1787539500,1787539800,1787540100,1787540400,1787540700,1787541000,1787541300,1787541600,1787541900,1787542200,1787542500,1787542800,1787543100,1787543400,1787543700,1787544000,1787544300,1787544600,1787544900,1787545200,1787545500,1787545800,1787551200,1787551500,1787551800,1787552100,1787552400,1787552700,1787553000,1787553300,1787553600,1787553900,1787554200,1787554500,1787554800,1787555100,1787555400,1787555700,1787556000,1787556300,1787556600,1787556900,1787557200,1787557500,1787558700,1787623200,1787623500,1787623800,1787624100,1787624400,1787624700,1787625000,1787625300,1787625600,1787625900,1787626200,1787626500,1787626800,1787627100,1787627400,1787627700,1787628000,1787628300,1787628600,1787628900,1787629200,1787629500,1787629800,1787630100,1787630400,1787630700,1787631000,1787631300,1787631600,1787631900,1787632200,1787637600,1787637900,1787638200,1787638500,1787638800,1787639100,1787639400,1787639700,1787640000,1787640300,1787640600,1787640900,1787641200,1787641500,1787641800,1787642100,1787642400,1787642700,1787643000,1787643300,1787643600,1787643900,1787645100,1787709600,1787710500,1787710800,1787711100,1787711400,1787711700,1787712000,1787712300,1787712600,1787712900,1787713200,1787713500,1787713800,1787714100,1787714400,1787714700,1787715000,1787715300,1787715600,1787715900,1787716200,1787716500,1787716800,1787717100,1787717400,1787717700,1787718000,1787718300,1787718600,1787724000,1787724300,1787724600,1787724900,1787725200,1787725500,1787725800,1787726100,1787726400,1787726700,1787727000,1787727300,1787727600,1787727900,1787728200,1787728500,1787728800,1787729100,1787729400,1787729700,1787730000,1787730300,1787731500,1787796000,1787796300,1787796600,1787796900,1787797200,1787797500,1787797800,1787798100,1787798400,1787798700,1787799000,1787799300,1787799600,1787799900,1787800200,1787800500,1787800800,1787801100,1787801400,1787801700,1787802000,1787802300,1787802600,1787802900,1787803200,1787803500,1787803800,1787804100,1787804400,1787804700,1787805000,1787810400,1787810700,1787811000,1787811300,1787811600,1787811900,1787812200,1787812500,1787812800,1787813100,1787813400,1787813700,1787814000,1787814300,1787814600,1787814900,1787815200,1787815500,1787815800,1787816100,1787816400,1787816700,1787817900,1787882400,1787883300,1787883600,1787883900,1787884200,1787884500,1787884800,1787885100,1787885400,1787885700,1787886000,1787886300,1787886600,1787886900,1787887200,1787887500,1787887800,1787888100,1787888400,1787888700,1787889000,1787889300,1787889600,1787889900,1787890200,1787890500,1787890800,1787891100,1787891400,1787896800,1787897100,1787897400,1787897700,1787898000,1787898300,1787898600,1787898900,1787899200,1787899500,1787899800,1787900100,1787900400,1787900700,1787901000,1787901300,1787901600,1787901900,1787902200,1787902500,1787902800,1787903100,1787904300,1788400800,1788401400,1788401700,1788402000,1788402300,1788402600,1788402900,1788403200,1788403500,1788403800,1788404100,1788404400,1788404700,1788405000,1788405300,1788405600,1788405900,1788406200,1788406500,1788406800,1788407100,1788407400,1788407700,1788408000,1788408300,1788408600,1788408900,1788409200,1788409500,1788409800,1788415200,1788415500,1788415800,1788416100,1788416400,1788416700,1788417000,1788417300,1788417600,1788417900,1788418200,1788418500,1788418800,1788419100,1788419400,1788419700,1788420000,1788420300,1788420600,1788420900,1788421200,1788421500,1788422700,1788487800,1788488100,1788488400,1788488700,1788489000,1788489300,1788489600,1788489900,1788490200,1788490500,1788490800,1788491100,1788491400,1788491700,1788492000,1788492300,1788492600,1788492900,1788493200,1788493500,1788493800,1788494100,1788494400,1788494700,1788495000,1788495300,1788495600,1788495900,1788496200,1788501600,1788501900,1788502200,1788502500,1788502800,1788503100,1788503400,1788503700,1788504000,1788504300,1788504600,1788504900,1788505200,1788505500,1788505800,1788506100,1788506400,1788506700,1788507000,1788507300,1788507600,1788507900,1788509100,1788746700,1788747300,1788747600,1788747900,1788748200,1788748500,1788748800,1788749100,1788749400,1788749700,1788750000,1788750300,1788750600,1788750900,1788751200,1788751500,1788751800,1788752100,1788752400,1788752700,1788753000,1788753300,1788753600,1788753900,1788754200,1788754500,1788754800,1788755100,1788755400,1788760800,1788761100,1788761400,1788761700,1788762000,1788762300,1788762600,1788762900,1788763200,1788763500,1788763800,1788764100,1788764400,1788764700,1788765000,1788765300,1788765600,1788765900,1788766200,1788766500,1788767100,1788768300,1788833100,1788833400,1788833700,1788834000,1788834300,1788834600,1788834900,1788835200,1788835500,1788835800,1788836100,1788836400,1788836700,1788837000,1788837300,1788837600,1788837900,1788838200,1788838500,1788838800,1788839100,1788839400,1788839700,1788840000,1788840300,1788840600,1788840900,1788841200,1788841500,1788841800,1788847200,1788847500,1788847800,1788848100,1788848400,1788848700,1788849000,1788849300,1788849600,1788849900,1788850200,1788850500,1788850800,1788851100,1788851400,1788851700,1788852000,1788852300,1788852600,1788852900,1788853200,1788853500,1788854700,1788919500,1788920100,1788920400,1788920700,1788921000,1788921300,1788921600,1788921900,1788922200,1788922500,1788922800,1788923100,1788923400,1788923700,1788924000,1788924300,1788924600,1788924900,1788925200,1788925500,1788925800,1788926100,1788926400,1788926700,1788927000,1788927300,1788927600,1788927900,1788928200,1788933600,1788933900,1788934200,1788934500,1788934800,1788935100,1788935400,1788935700,1788936000,1788936300,1788936600,1788936900,1788937200,1788937500,1788937800,1788938100,1788938400,1788938700,1788939000,1788939300,1788939600,1788939900,1788941100,1789005600,1789005900,1789006200,1789006500,1789006800,1789007100,1789007400,1789007700,1789008000,1789008300,1789008600,1789008900,1789009200,1789009500,1789009800,1789010100,1789010400,1789010700,1789011000,1789011300,1789011600,1789011900,1789012200,1789012500,1789012800,1789013100,1789013400,1789013700,1789014000,1789014300,1789014600,1789020000,1789020300,1789020600,1789020900,1789021200,1789021500,1789021800,1789022100,1789022400,1789022700,1789023000,1789023300,1789023600,1789023900,1789024200,1789024500,1789024800,1789025100,1789025400,1789025700,1789026000,1789026300,1789027500,1789092000,1789092300,1789092600,1789092900,1789093200,1789093500,1789093800,1789094100,1789094400,1789094700,1789095000,1789095300,1789095600,1789095900,1789096200,1789096500,1789096800,1789097100,1789097400,1789097700,1789098000,1789098300,1789098600,1789098900,1789099200,1789099500,1789099800,1789100100,1789100400,1789100700,1789101000,1789106400,1789106700,1789107000,1789107300,1789107600,1789107900,1789108200,1789108500,1789108800,1789109100,1789109400,1789109700,1789110000,1789110300,1789110600,1789110900,1789111200,1789111500,1789111800,1789112100,1789112400,1789112700,1789113900,1789351200,1789351800,1789352100,1789352400,1789352700,1789353000,1789353300,1789353600,1789353900,1789354200,1789354500,1789354800,1789355100,1789355400,1789355700,1789356000,1789356300,1789356600,1789356900,1789357200,1789357500,1789357800,1789358100,1789358400,1789358700,1789359000,1789359300,1789359600,1789359900,1789360200,1789365600,1789365900,1789366200,1789366500,1789366800,1789367100,1789367400,1789367700,1789368000,1789368300,1789368600,1789368900,1789369200,1789369500,1789369800,1789370100,1789370400,1789370700,1789371000,1789371300,1789371600,1789371900,1789373100,1789437600,1789437900,1789438500,1789438800,1789439100,1789439400,1789439700,1789440000,1789440300,1789440600,1789440900,1789441200,1789441500,1789441800,1789442100,1789442400,1789442700,1789443000,1789443300,1789443600,1789443900,1789444200,1789444500,1789444800,1789445100,1789445400,1789445700,1789446000,1789446300,1789446600,1789452000,1789452300,1789452600,1789452900,1789453200,1789453500,1789453800,1789454100,1789454400,1789454700,1789455000,1789455300,1789455600,1789455900,1789456200,1789456500,1789456800,1789457100,1789457400,1789457700,1789458000,1789458300,1789459500],
      "c": [1724.72,1728.37,1732.93,1739.21,1742.29,1736.3,1736.05,1734.81,1733.85,1734.99,1739.34,1741.3,1738.92,1734.67,1734.2,1732.89,1731.82,1732.85,1730.6,1729.02,1730.54,1729.79,1728.9,1727.78,1723.77,1719.54,1713.28,1713.14,1709.87,1716.3,1715.76,1714.68,1717.35,1717.46,1721.33,1724.44,1726.24,1722.01,1719.95,1722.14,1725.17,1723.47,1725.88,1725.24,1728.69,1730.95,1713.13,1713.83,1697.61,1705.85,1703.01,1702.25,1696.27,1700.4,1702.71,1704.14,1703.3,1701.08,1700.47,1697.65,1695.9,1695.87,1696.54,1697.68,1700.13,1698.03,1698.7,1699.95,1702.22,1703.43,1700.15,1698.33,1697.67,1696.21,1698.25,1698.48,1693.09,1691.32,1693.82,1691.78,1690.5,1689.84,1692.31,1690.88,1689.36,1687.13,1686.71,1688.19,1693.27,1697.66,1708,1708.19,1703.95,1699.7,1677.09,1699.13,1690.92,1680.29,1683.78,1684.27,1680.1,1678.63,1680.88,1681.38,1681.22,1681.98,1678.15,1677.11,1675.81,1676.81,1677.55,1677.73,1679.68,1679.3,1680.58,1680.82,1678.29,1678.17,1677.18,1677.02,1676.19,1675.87,1676.19,1676,1671.33,1671.67,1670.62,1664.51,1666.29,1669.05,1671.75,1670.94,1669.04,1666.79,1667.42,1664.02,1663.39,1660.26,1661.21,1661.2,1658.43,1655.22,1642.65,1647.81,1635.49,1627.47,1626.38,1627.47,1619.12,1612.38,1616.24,1611.75,1605.78,1597.06,1610.17,1606.76,1605.1,1607.41,1609.12,1615.27,1613.12,1611.69,1608.64,1604.58,1602.87,1599.27,1605.22,1609.44,1615.21,1614.92,1613.56,1613.57,1611.84,1610.17,1607.99,1604.23,1602.28,1603.9,1607.99,1604.16,1599.72,1596.02,1599.17,1596.21,1598.24,1601.29,1599,1589.11,1591.03,1596.43,1592.79,1591.17,1621.71,1613.65,1616.31,1616.21,1613.32,1614.79,1614.17,1613.58,1610.73,1612.49,1613.07,1614.39,1618.97,1621.49,1619.08,1619.67,1621.07,1625.14,1629,1629.06,1627.04,1625.23,1623.31,1623.37,1622.64,1622.45,1622.6,1622.69,1618.79,1619.87,1620.98,1620.07,1612.98,1614.95,1614.06,1612.87,1609.63,1604.61,1607.46,1609.27,1611.21,1609.13,1609.26,1604.6,1606.12,1608.58,1606.13,1614.77,1643.1,1643.3,1652.28,1649.9,1648.66,1645.52,1642.52,1644.19,1644.87,1644.52,1644.86,1645.41,1646.31,1650.43,1651.68,1651.03,1650.48,1648.32,1648.06,1647.23,1648.93,1648.05,1647.5,1646.75,1645.44,1645.93,1645.83,1645.76,1643.55,1644.7,1647.43,1646.51,1646.34,1647.09,1648.69,1650.75,1650.53,1649.29,1648.71,1647.43,1648.9,1644.6,1646.3,1649.81,1652.64,1654.78,1654.13,1658.19,1653.81,1652.2,1649.37,1644.01,1642.26,1642.79,1642.53,1641.38,1637.91,1637.85,1639.51,1643.83,1648.35,1644.64,1643.97,1646.1,1643.94,1642.72,1644.12,1643.58,1642.92,1642.08,1643.25,1641.31,1641.61,1640.94,1640.61,1640.38,1635.76,1635.3,1636.57,1636.69,1636.45,1638.78,1639.13,1637.4,1637.41,1641.48,1644.84,1643.19,1645.05,1644.83,1643.58,1645.17,1643.43,1643.7,1641.41,1644.63,1641.59,1644.29,1645.48,1642.52,1642.19,1642.88,1643.6,1643.8,1652.57,1656.77,1652.47,1651.21,1652.07,1650.44,1650.47,1650.65,1650.36,1650.85,1650.14,1649.98,1649.22,1648.96,1650.97,1652.43,1651.84,1651.54,1652.56,1652.89,1652,1651.06,1653.02,1654.4,1656.91,1659,1657.37,1660.3,1662.09,1663.45,1662.97,1663.3,1665.44,1668.6,1669.49,1670.69,1671.89,1671.52,1669.84,1672.8,1646.83,1644.7,1642.52,1644.77,1646.38,1644,1643.63,1643.96,1642.22,1641,1638,1641.3,1646.95,1647.1,1652.5,1651.12,1649.64,1652.57,1653.53,1652.56,1651.21,1649.94,1649.96,1649.21,1648.67,1649.31,1650.21,1650.15,1648.98,1650.91,1651.41,1654.37,1657.73,1656.71,1658.13,1662.12,1664.9,1663.53,1667.49,1671.6,1663.93,1665.17,1666.76,1667.3,1665.76,1658.19,1657.68,1662.54,1670.32,1667.15,1667.37,1667.32,1666.84,1666.78,1667.22,1669.4,1670.52,1669.73,1672.73,1676.49,1675.71,1675.85,1677.39,1676.44,1676.44,1676.72,1675.9,1675.48,1674.86,1672.98,1673.31,1673.16,1673.44,1673.94,1673.72,1673.64,1675.21,1674.07,1672.52,1669.35,1669.85,1669.15,1668.79,1668.25,1665.08,1665.35,1666.73,1669.47,1669.26,1668.24,1667.63,1667.17,1666.18,1669.28,1663.05,1674.49,1713.94,1710.98,1709.53,1707.45,1706.95,1708.32,1709.69,1710.4,1711.2,1711.97,1708.96,1709.34,1709.53,1708.41,1706.4,1706.64,1705.09,1704.79,1703.29,1703.65,1705.18,1704.8,1704.65,1704.06,1704.14,1703.31,1704.89,1704.9,1704.12,1702.27,1701.29,1700.26,1703.88,1704.5,1705.27,1706.18,1709.15,1712.58,1711.04,1710.42,1710.92,1707.89,1706.91,1706.2,1707.23,1706.5,1704.73,1702.93,1695.84,1701.84,1698.69,1695.2,1695.75,1693.84,1696.13,1696.67,1697.93,1697.59,1695.99,1695.63,1694.94,1692.98,1692.32,1693.45,1695.4,1695.92,1697.69,1698.98,1696.1,1697.43,1696.98,1696.44,1695.38,1695.93,1694.92,1694.77,1691.32,1691.56,1693.27,1693.7,1693.02,1692.52,1688.9,1686.9,1688.23,1688.15,1687.24,1685.81,1689.56,1691.99,1692.06,1692.61,1693.96,1694.91,1691.17,1694.82,1703.82,1705.8,1707.21,1710.93,1707.03,1711.66,1712.33,1708.33,1709.28,1708.97,1708.54,1708,1706.82,1706.51,1704.85,1701.74,1699.93,1698.29,1698.21,1698.56,1700.55,1698.81,1699.21,1699.81,1700.91,1699.73,1699.36,1699.34,1694.77,1694.35,1690.55,1690.68,1690.42,1688.74,1684.41,1687.41,1685.67,1684.19,1685.36,1685.36,1684.03,1682.57,1680.12,1684.15,1683.27,1684.58,1684.62,1684.04,1679.03,1679.78,1685.23,1684.4,1691.36,1691.39,1688.9,1687.76,1687.06,1684.65,1683.59,1680.86,1677.45,1673.83,1676.44,1678.58,1676.17,1676.06,1675.73,1675.9,1675.53,1676.69,1678.72,1678.05,1677.66,1676.94,1676.45,1676.09,1676.54,1676.59,1676.7,1679.89,1680.22,1682.28,1682.27,1682.44,1680.27,1678.67,1677.92,1678.22,1677.18,1674.07,1674.76,1674.78,1671.51,1671.1,1673.71,1674.99,1679.34,1677.67,1674.04,1670.34,1672.74,1677.25,1682.43,1678.97,1681.66,1684.14,1689.65,1687.08,1684.41,1685.21,1684.3,1684.01,1683.06,1681.96,1680.24,1678.63,1679.5,1678.86,1675.88,1675.06,1673.6,1671.89,1672.6,1672.93,1672.1,1675.05,1673.83,1673.18,1671.66,1672.32,1672.23,1671.98,1671.44,1668.58,1669.11,1667.58,1666.57,1666.08,1666.13,1674.28,1676.73,1679.9,1677.2,1677.54,1725.19,1723.63,1719.68,1713.86,1713.68,1713.28,1715.11,1714.95,1717.35,1718.16,1720.64,1721.79,1723.75,1731.35,1731.48,1732.44,1734.93,1736.53,1739.07,1735.37,1733.3,1734.08,1733.49,1734.73,1735.64,1737.57,1735.98,1736.2,1736.45,1740.04,1740.6,1741.74,1744.38,1747.86,1748.41,1748.23,1749.07,1750.09,1752.11,1753.77,1754.54,1754.49,1754.34,1754.83,1753.78,1753.87,1754.2,1756.55,1743.39,1753.47,1750.32,1746.98,1747.48,1748.33,1750.47,1754.53,1753.72,1752.56,1749.93,1746.56,1746.86,1746.77,1747.21,1747.09,1746.27,1745.1,1744.52,1743.54,1741.07,1741.65,1742.47,1742.77,1741.79,1740.75,1738.93,1738.93,1740.29,1741.64,1743.46,1745.58,1745.35,1744.82,1746.36,1746.55,1745.8,1744.66,1745.35,1746.88,1748.49,1750.08,1747.64,1746.97,1742.53,1739.85,1738.81,1736.68,1756.32,1756.24,1756.53,1754.99,1757.39,1760.47,1761.02,1758.55,1753.84,1754.28,1755.92,1756.77,1756.86,1756.77,1756.5,1755.33,1755.07,1755.6,1756.27,1755.65,1758.33,1757.68,1756.29,1756.27,1755.08,1754.73,1754.23,1754.25,1754.38,1755.41,1755.64,1754.69,1756.14,1757.23,1758.71,1758.39,1757.24,1756.82,1756.87,1757,1755.6,1755.24,1753.71,1753.41,1751.98,1749.77,1747.75,1750,1733.98,1739.42,1739.83,1737.82,1740.83,1747.83,1744.6,1743.65,1745.92,1745.95,1747.43,1745.53,1745.25,1744.78,1745.41,1745.92,1744.33,1742.97,1741.78,1741.74,1740.55,1740.68,1740.88,1741.12,1739.76,1740.25,1741.85,1741.94,1742.7,1746.35,1750.19,1746.93,1750.15,1748.85,1747.86,1750.81,1753.89,1754.05,1756.37,1759.62,1759.25,1764.76,1762.15,1762.14,1757.71,1757.69,1755.93,1758.96,1781.79,1779.54,1782.32,1780.78,1781.24,1779.83,1776.58,1778.05,1778.92,1775.25,1776.68,1776.42,1775.89,1774.49,1772.7,1772.43,1772.47,1773.5,1773.47,1773.6,1774.11,1772.63,1770.58,1770.12,1769.95,1769.8,1768.62,1769.65,1768.62,1771.17,1772.02,1768.43,1767.21,1768.45,1768.77,1769.67,1771.75,1770.31,1770.54,1772.01,1771.17,1770.92,1772.4,1771.22,1771.37,1772.88,1770.89,1775.65,1792.93,1787.94,1789.37,1795.74,1789.93,1791.79,1793.4,1791.2,1791.57,1789.9,1789.38,1788.85,1788.33,1789.09,1790.16,1790.88,1793.45,1792.47,1792.46,1791.72,1790.46,1789.66,1789.71,1790.32,1790.59,1791.28,1791.52,1791.66,1788.71,1790.04,1791.09,1791.77,1793.1,1795.2,1794.29,1792.73,1793.33,1794.55,1795.09,1793.4,1797.1,1799.23,1800.79,1799.63,1799.87,1801.1,1799.07,1800.65,1809.27,1812.64,1813.21,1811.2,1806.36,1807.51,1807.35,1802.3,1803.42,1806.28,1805.13,1804.31,1806.46,1805.39,1806.17,1809.26,1813.4,1818.38,1816.03,1816.38,1819.36,1819.87,1823.32,1820.49,1820.62,1819.72,1818.72,1818.74,1817.38,1818.9,1818.33,1820.14,1820.77,1822.06,1822.09,1822.25,1821.6,1820.19,1815,1817.41,1815.64,1816.55,1817.88,1818.6,1818.98,1820,1817.22,1819.83,1844.74,1835.51,1837.39,1837.98,1835.42,1822.27,1826.07,1814.47,1827.65,1828.22,1829.67,1831.35,1832.66,1833.43,1831.93,1829.82,1825.19,1823.98,1821.75,1823.95,1826,1827.17,1827.77,1827.38,1827.06,1827.23,1825.73,1825.72,1821.27,1822.47,1828.08,1826.81,1826.75,1832.44,1833.72,1831.33,1830.16,1827.63,1829.61,1827.6,1826.84,1825.89,1824.27,1824.75,1824.69,1821.61,1818.12,1817.17,1806.04,1809,1814.5,1814.51,1810.28,1807.71,1805.19,1805.54,1806.77,1808.41,1808.67,1809.96,1812.52,1820.75,1829.2,1822.3,1818.52,1822.12,1825.81,1830.11,1829.41,1833.85,1830.55,1829.02,1827.39,1825.4,1825.85,1826.33,1822.72,1827.06,1829.63,1827.82,1827.15,1826.03,1824.85,1827.4,1827.84,1833.02,1830.25,1828.06,1828.7,1826.78,1829.18,1830.89,1833.59,1832.01,1838.01,1837.11,1858.67,1859.97,1852.55,1850.97,1851.32,1852.59,1858.44,1864.13,1864.7,1859.42,1858.68,1860.86,1863.79,1865.1,1864.04,1863.06,1862.03,1859.56,1857.6,1857.8,1858.05,1856.57,1856.23,1856.77,1856.67,1857.28,1857.76,1858,1852.62,1852.44,1849.59,1844.25,1849.78,1847.09,1846.8,1848.08,1848.5,1847.11,1847,1847.79,1846.22,1843.75,1843.49,1842.36,1840.61,1836.78,1833.62,1833.48,1834.7,1830.87,1833.24,1832.93,1832.31,1838.43,1837.2,1835.84,1835.29,1833.84,1831.71,1831.16,1829.72,1829.69,1828.48,1830.1,1831.52,1828.82,1827.29,1826.86,1825.78,1825.18,1824.7,1824.38,1821,1822.56,1824.78,1825.08,1828.12,1828.58,1834.73,1831.32,1830.09,1837.56,1840.76,1845.95,1855.36,1857.35,1857.23,1858.9,1858.39,1857.71,1857.35,1859.38,1859.68,1861.34,1855.34,1857.3,1871.74,1868.86,1871.95,1878.93,1879.24,1872.76,1877.93,1876.67,1880.21,1879.81,1886.98,1886.39,1881.51,1882,1885.03,1878.33,1877.98,1877.2,1874.81,1875.1,1876.14,1877.56,1879.47,1879.04,1876.98,1876.63,1874.61,1874.63,1872.94,1870.76,1868.66,1867.67,1861.21,1866.36,1866.09,1860.9,1859.76,1864.65,1865.53,1862.58,1855.58,1859.02,1863.98,1870.39,1874.98,1874.76,1868.58,1870.36,1866.43,1867.82,1868.61,1869.14,1871.89,1873.75,1874.64,1872.71,1876.96,1880.6,1877.1,1872.69,1871.05,1870.49,1868.72,1867.04,1865.11,1863.28,1863.67,1865.08,1862.68,1859.81,1862.99,1864.13,1863.74,1862.97,1862.51,1862.41,1859.17,1853.39,1857.48,1855.67,1856.14,1854.83,1849.06,1853.97,1856.66,1855.99,1857.22,1857.66,1858.24,1859.24,1853.38,1855.58,1854.85,1853.73,1848.08,1853.29,1858.73,1862.4,1865.99,1867,1868.68,1871.75,1867.65,1868.42,1868.69,1868.48,1870.54,1878.09,1879.27,1878.88,1876.99,1876.01,1882.16,1883.59,1883.68,1884.93,1886.72,1887.14,1887.29,1885.58,1886.54,1886.73,1885.87,1886.05,1876.58,1874.09,1874.91,1872.67,1871.11,1869.3,1872.87,1874.22,1878,1876.82,1878.56,1879.5,1874.76,1875.48,1877.26,1880.14,1879.74,1875.78,1875.1,1875.84,1876.49,1877.26,1875.4,1873.73,1873.38,1866.75,1868.96,1868.83,1868.25,1864.9,1863.16,1863.72,1861.06,1859.66,1861.92,1861.09,1860.13,1859.71,1861.63,1862.67,1861.59,1860.24,1859.03,1858.4,1858.66,1858.98,1859.28,1858.98,1860.68,1857.32,1857.83,1854.87,1855.79,1856.25,1857.37,1856.14,1857.16,1859.39,1857.65,1854.26,1853.56,1855.71,1858.2,1856.85,1854.31,1853.3,1841.3,1854.1,1873.76,1872.3,1870.89,1871.6,1874.99,1876.26,1872.97,1870.89,1868.59,1867.24,1865.37,1867.09,1868.72,1859.06,1859.66,1858.05,1856.29,1857.3,1857.17,1855.37,1854.62,1850.34,1852.31,1855.41,1856.08,1856.76,1855.41,1855.66,1847.66,1841.52,1847.6,1846.88,1846.08,1846.58,1853.83,1853.97,1850.77,1848.77,1852.89,1851.09,1854.64,1859.17,1858.86,1859.06,1856.7,1852.3,1849.7,1854.06,1856.49,1851.07,1849.5,1854.33,1860.11,1862.26,1860.38,1855.39,1853.49,1853.24,1854.34,1856.92,1855.33,1855.94,1855.77,1854.51,1858.37,1861.81,1864.36,1871.04,1868.39,1867.81,1871.7,1875.09,1872.92,1868.82,1869.18,1869.02,1863.03,1863,1864.11,1863.95,1864.79,1866.77,1864.35,1864.19,1865.67,1866.71,1866.77,1870.98,1873.84,1874.22,1873.66,1873.89,1872.93,1872.9,1872.69,1874.85,1882.84,1883.12,1882.18,1882.01,1880.98,1877.16,1879.62,1880.35,1878.7,1875.68,1873.18,1871.06,1873.26,1873.22,1873.26,1872.61,1872.14,1869.97,1869.91,1871.08,1872.79,1871.72,1871.24,1871.62,1871.62,1872.06,1872.03,1872.19,1869.23,1872.97,1874.94,1874.65,1877.71,1880.05,1878.52,1878.17,1878.39,1879.59,1883.29,1885.65,1887.55,1888.75,1888.29,1886.91,1887.46,1890.7,1888.01,1891.2,1900.09,1901.92,1897,1901.64,1906.19,1902.45,1904.06,1902.49,1901.99,1904.24,1900.76,1900.5,1901.21,1901.06,1902.17,1902.32,1904.93,1912.03,1908.18,1908.22,1909,1906.73,1905.99,1905.7,1905.92,1907.29,1906.31,1906.4,1904.18,1912.75,1917.05,1919.32,1917.1,1917.2,1917.08,1916.26,1919.12,1913.61,1913.31,1914.57,1904.57,1908.04,1907.14,1909.12,1910.23,1912.69,1907.47,1909.01,1903.66,1905.66,1903.95,1904.15,1898.72,1900.77,1900.61,1902.88,1903.08,1903.18,1901.97,1902.03,1903.12,1903.52,1903.85,1903.49,1904.23,1902.86,1901.28,1902.15,1901.5,1898.05,1900.29,1900.24,1900.97,1900.48,1899.92,1899.74,1899.32,1903.58,1908.24,1912.31,1917.01,1912.21,1914.6,1919.9,1921.53,1917.75,1914.84,1913.21,1913.04,1905.83,1905.25,1907.52,1907.88,1912.88,1907.3,1915.37,1924.69,1924.74,1925.03,1922.98,1923.05,1920.4,1918.11,1919.48,1919.51,1920.37,1921.23,1922.41,1920.79,1922.56,1923.34,1921.07,1920.62,1921.14,1922.69,1923.69,1923.79,1922.3,1921.17,1920.1,1921.62,1920.48,1920.81,1921.29,1918.2,1919.03,1920.04,1920.77,1920.13,1917.31,1915.68,1911.14,1911.71,1911.45,1910.18,1911.45,1909.89,1907.91,1907.26,1905.08,1895.96,1902.61,1895.44,1895.5,1892.11,1889.63,1893.04,1896.37,1897.24,1897.87,1895.08,1892.31,1891.89,1891.92,1891.73,1892.09,1893,1894.65,1893.22,1893.32,1891.3,1891.18,1889.1,1889.02,1889.79,1888.77,1888.05,1885.53,1883.19,1880.87,1879.13,1879.82,1878.57,1881.95,1881.2,1879.98,1880.87,1882.39,1882.69,1885.74,1889.14,1892.57,1899.9,1899.15,1906.35,1902.24,1899.89,1901.92,1900.75,1899.38,1882.58,1901.1,1900.2,1899.05,1901.35,1897.73,1895.74,1892.07,1893.32,1891.66,1892.07,1894.63,1894.51,1895.03,1896.91,1897.28,1895.7,1894.28,1894.46,1895.72,1892.84,1893.53,1892.33,1891.52,1890.81,1891.88,1891.47,1892.03,1892.56,1892.75,1889.97,1889.95,1891.38,1891.59,1892.28,1888.97,1882.16,1882.59,1876.84,1873.38,1872.59,1867,1869.31,1868.07,1876.04,1884.85,1887.71,1890.54,1887.34,1898.37,1890.95,1887.94,1889.27,1896.92,1901.52,1899.71,1898.82,1899,1897.14,1895.76,1894.89,1896.33,1899.88,1901.4,1902.95,1906.66,1907.69,1907.49,1909.24,1913.14,1919.66,1916.91,1915.53,1915.1,1917.11,1916.26,1918.48,1918.51,1916.2,1920.39,1919.54,1920.39,1918.24,1917.72,1917.08,1918.74,1917.08,1919.43,1921.04,1920.63,1919.88,1917.02,1916.91,1918.46,1917.73,1922.83,1925.05,1925.46,1925.91,1929.78,1926.65,1924.27,1922.73,1918.07,1918.19,1916.46,1915.87,1918.27,1917.54,1917.63,1916.53,1915.65,1915.42,1917.2,1916.09,1919.29,1918.17,1918.81,1918.45,1918.14,1919.19,1918.56,1919.5,1920.91,1921.6,1921.98,1913.25,1912.83,1912.3,1911.41,1911.57,1914,1916.36,1914.26,1914.26,1915.91,1915.42,1916.36,1918.79,1919.16,1922.63,1921.14,1918.39,1922.35,1910.14,1921.6,1912.39,1914.86,1915.19,1915.84,1922.07,1917.42,1915.66,1915.19,1915.12,1914.8,1912.34,1910.04,1909.95,1911.64,1913.75,1912.49,1912.83,1912.55,1912.82,1913.21,1913.94,1913.82,1913.75,1914.66,1916.81,1920.77,1920.63,1920.76,1918.54,1917.26,1915.66,1914.4,1915.55,1917.66,1921.99,1920.32,1920.7,1924.05,1925.43,1923.86,1925.43,1924.9,1923.65,1926.19,1925.9,1931.92,1924.64,1927.94,1929.21,1926.58,1926.42,1922.74,1919.68,1925.03,1924.74,1925.76,1924.72,1924.86,1923.84,1924.77,1923.21,1921.83,1922.3,1921.44,1921.28,1920.69,1920.92,1920.59,1924.18,1923.06,1924.39,1924.08,1925.14,1925.95,1922.59,1922.7,1918.35,1919.48,1920.71,1919.66,1916.33,1914.46,1910.92,1909.39,1915.48,1914.51,1916.83,1919.49,1917.24,1916.53,1913.08,1908.38,1911.41,1916.38,1905.14,1912.93,1910.02,1916.47,1914.58,1918.25,1918.34,1918.98,1914.97,1914.2,1913.35,1912.16,1911.75,1914.82,1915.56,1917.96,1915.7,1915.61,1914.51,1910.89,1908.68,1905.51,1905.19,1902.41,1898.62,1897.21,1898.4,1894.36,1882.13,1881.87,1860.13,1879.22,1882.02,1886,1892.72,1888.3,1897.37,1902.14,1899.94,1895.86,1896.95,1900.48,1901.8,1898.41,1901.35,1904.8,1908.72,1911.07,1903.12,1913.23,1915.4,1909.02,1903.5,1902.82,1906,1902.87,1902.45,1902.48,1903.3,1906.19,1905.07,1903.95,1902.11,1902.77,1904.98,1905.79,1902.54,1898.1,1896.75,1892.56,1887.32,1888.39,1888.96,1892.55,1894.41,1896.6,1898.46,1898.51,1891.87,1892.61,1890.75,1892.21,1892.03,1891.51,1892.98,1896.97,1898.51,1896.34,1896.48,1898.12,1899.81,1903.16,1904.75,1896.81,1896.5,1907.81,1894.38,1896.89,1882.82,1882.78,1880.48,1872.8,1873.46,1880.64,1881.37,1882.29,1883.02,1885.82,1882.36,1878.94,1877.35,1873.66,1874.1,1874.32,1872.31,1870.68,1869.59,1867.92,1866.96,1864.28,1861.63,1859.07,1856.09,1864.16,1864.75,1864.97,1863.92,1870.91,1870.43,1869.84,1869.08,1868.37,1867.33,1869.17,1872.21,1875.41,1874.51,1873.49,1871.18,1868.05,1869.99,1873,1872.99,1876.91,1872.86,1877.13,1885.51,1879.41,1880.03,1884.93,1886.92,1888.5,1885.7,1884.83,1886.48,1884.72,1883.07,1886.93,1885.33,1884.97,1885.28,1886.08,1887.22,1887.58,1886.93,1884.79,1883.54,1883.06,1882.07,1880.84,1880.25,1879.67,1879.31,1879.14,1880.66,1883.13,1886.65,1887.48,1890.16,1886.88,1887.37,1886.87,1885.66,1885.55,1884.02,1882.02,1883.24,1882.4,1880.08,1879.18,1878.54,1885.75,1879.11,1886.03,1886.41,1885.95,1886.4,1886.95,1884.45,1881.09,1884.04,1885.44,1884.55,1885.55,1887.22,1886.29,1885.48,1884.45,1883.47,1882.36,1881.3,1882.57,1882.81,1883.14,1882.89,1883.5,1882.4,1882.45,1882.21,1881.84,1880.88,1880.89,1877.99,1878.57,1877.38,1877.08,1877.12,1879.02,1880,1880.85,1882.15,1879.86,1879.74,1879.69,1880.78,1883.21,1882.79,1883.29,1884.84,1885.67,1884.57,1884.18,1878.47,1879.73,1879.07,1879.4,1879.12,1879.52,1877.89,1876.1,1870.84,1869.89,1866.01,1869.43,1872.07,1877.01,1874.02,1872.16,1871.73,1872.22,1873.48,1874.16,1873.29,1873.36,1872.75,1871.98,1869.35,1869.13,1868.44,1868.43,1865.99,1868.56,1867.58,1866.01,1867.98,1868.06,1867.76,1865.21,1865.4,1873.51,1872.35,1870.37,1872.1,1873.2,1873.9,1870.94,1870.06,1870.14,1865.83,1874.43,1870.31,1873.84,1877.06,1879.34,1878.46,1873.02,1874.94,1874.15,1871.38,1871.57,1869.21,1868.07,1868.74,1869.97,1870.31,1869.01,1865.17,1862.55,1861.87,1860.84,1858.96,1859.39,1858.08,1858.44,1859.41,1859.68,1858.94,1859,1860.07,1858.96,1859.97,1858.88,1859.56,1862.36,1865.58,1873.68,1867.35,1876.23,1871.3,1870.97,1880.16,1878.1,1879.46,1877.65,1874.63,1872.03,1867.81,1863.67,1864.66,1862.33,1863.7,1862.49,1861,1860.62,1861.93,1864.39,1863.76,1864.3,1862.8,1862.99,1862.66,1863.01,1860.88,1859.36,1857.83,1857.27,1858.3,1860.29,1858.53,1858.17,1858.23,1856.94,1856.33,1859.15,1863.51,1863.23,1863.62,1861.24,1862.62,1862.71,1865.3,1870.12,1867.6,1870.07,1873.17,1870.79,1868.47,1866.11,1866.26,1865.65,1868.04,1868.56,1866.44,1862.19,1861.38,1863.49,1868.04,1867.63,1867.66,1867.22,1867.71,1867.95,1869.07,1867.46,1866.18,1863.27,1862.69,1862.4,1862.28,1860.47,1858.42,1859.1,1858.02,1856.59,1854.5,1853.62,1853.78,1851.12,1853.76,1852.63,1851.55,1854.08,1853.05,1853.04,1850.7,1850.11,1849.9,1849.6,1849.29,1848.75,1847.44,1849.35,1848.62,1847.32,1844.15,1847,1848.57,1849.04,1848.53,1846.15,1841.58,1846.93,1841.32,1844.54,1841.58,1843.88,1846.33,1845.63,1850.5,1855.92,1854.49,1850.95,1851.75,1852.12,1850.42,1850.72,1848,1844.7,1846.04,1845.86,1843.89,1842.84,1842.77,1842.65,1840.04,1840.7,1841.49,1838.89,1836.66,1837.24,1836.09,1836.1,1832.86,1833,1834.94,1838.33,1835.36,1832.64,1834.52,1834.48,1833.62,1829.88,1827.94,1824.93,1828.22,1830.81,1827.81,1828.46,1824.94,1827.48,1822.4,1826.47,1825.68,1823.22,1820.06,1815.96,1816.47,1810.62,1812,1807.68,1810.83,1809.29,1810.12,1811.9,1812.45,1809.92,1803.97,1803.89,1801.83,1800.28,1801.56,1801.67,1803.48,1804.91,1805.7,1810.35,1809.7,1810.51,1809.31,1809.26,1808.62,1809.86,1808.45,1809.42,1814.79,1814.68,1824.34,1828.74,1826.16,1829.32,1828.95,1825.76,1828.04,1825.64,1826.8,1822.62,1820.87,1817.03,1812.08,1819.01,1812.8,1816.96,1819.88,1823.47,1824.91,1823.27,1822.97,1822.57,1818.87,1820.4,1821.31,1820.89,1818.65,1817.18,1818.75,1818.08,1817.8,1822.05,1821.24,1819.2,1819.04,1817.71,1818.39,1817.76,1818,1818.47,1818.61,1818.66,1818.06,1821.32,1824.87,1824.11,1821.59,1822.68,1825.64,1828.17,1827.82,1826.84,1826.77,1827.85,1829.84,1827.46,1828.97,1829.56,1830.27,1829.26,1826.91,1831.55,1838.23,1837.95,1838.88,1842.24,1841.57,1842,1841.35,1840.77,1841.05,1840.32,1839.66,1838.54,1838.04,1839.5,1840.99,1841.13,1843.83,1842.54,1842.32,1842.15,1841.47,1842.45,1842.32,1844.58,1846,1845.48,1843.33,1843.09,1840.57,1838.92,1841.1,1839.95,1838.88,1842.51,1841.53,1840.27,1840.13,1839.57,1841.21,1840.08,1840.05,1839.8,1837.33,1836.5,1842.08,1840.72,1830.4,1838.9,1820.14,1820.43,1816.62,1810.99,1809.53,1810.05,1815.48,1819.66,1820.03,1820.34,1812.82,1810.37,1809.87,1808.98,1809.65,1811.88,1810.66,1810.44,1810.06,1809.5,1808.62,1806.03,1804.6,1803.39,1802.6,1800.96,1799.24,1799.22,1798.15,1798.88,1800.46,1802.68,1800.55,1800.12,1799.75,1800.92,1800.01,1799.89,1799.59,1796.64,1794.87,1790.56,1793.37,1798.84,1793.88,1794.59,1790.16,1790.53,1799.12,1796.9,1795.65,1796.22,1797.59,1798.49,1797.5,1795.65,1793.68,1791.47,1788.42,1787.06,1785.04,1781.7,1783.3,1784.53,1785.86,1788.08,1788.63,1789.1,1794.88,1794.11,1793.66,1793.5,1794.09,1792.53,1790.73,1792.6,1794.47,1789.84,1789.5,1789.15,1792.09,1790.33,1786.76,1787.41,1786.62,1787.66,1787.77,1790.44,1793.72,1793.68,1792.2,1791.56,1792.54,1792.31,1790.35,1793.05,1789.95,1790.74,1793.42,1794.95,1796.98,1795.67,1794.56,1793.3,1790.9,1791.78,1792.36,1791.02,1790.46,1792.54,1794.82,1797.64,1799.89,1798.05,1797.99,1799.77,1799.86,1801.79,1802.26,1801.19,1801.67,1801.27,1801.2,1801.26,1798.72,1798.23,1798.82,1797.68,1796.95,1797.44,1795.51,1797.12,1796.83,1798.43,1797.78,1797.68,1802.32,1800.1,1801.51,1804.14,1804.15,1803.81,1799.33,1803.71,1790.47,1793.9,1792.45,1791.34,1789.43,1789.87,1790.18,1792.37,1792.62,1792.57,1793.14,1794.01,1793.43,1793.13,1792.24,1792.11,1792.46,1794.87,1794.21,1796.29,1797.37,1798.36,1797.43,1795.46,1795.4,1796.34,1797.1,1796.99,1794.88,1794.35,1796.06,1797.53,1797.24,1800.43,1799.47,1799.7,1798.06,1797.61,1797.86,1796.08,1798.12,1800.96,1800.85,1800.6,1799.81,1797.43,1795.35,1798.61,1810.13,1808.9,1804.54,1805.41,1807.45,1805.61,1804.9,1804.45,1803.18,1804.15,1804.05,1807.48,1807.65,1806.18,1805.16,1804.12,1804.25,1803.29,1802.66,1803.52,1803.43,1802.4,1802.15,1802.67,1802.26,1802.87,1803.02,1803.19,1801.19,1803.61,1802.03,1802.99,1803.12,1803.06,1804.92,1806.5,1805.6,1805.03,1804.18,1803.8,1800.59,1802.47,1797.9,1794.5,1794.05,1790.98,1788.96,1791.65,1806.12,1808.4,1809.25,1806.34,1804.29,1797.73,1797.21,1796.63,1793.04,1793.87,1783,1781.91,1780.85,1777.72,1778.08,1779.04,1786.93,1789.76,1792.26,1792.67,1791.97,1795.94,1792.55,1790.33,1794.17,1794.1,1794.37,1794.58,1791.82,1792.79,1797.24,1798.41,1801.06,1800.58,1799.88,1798.41,1795.47,1794.43,1793.35,1795.41,1797.01,1796.35,1795.32,1795.02,1795.29,1797.45,1796.67,1799.31,1803.87,1806.29,1806.09,1808.14,1806.37,1801.22,1804.26,1810.62,1805.61,1806.59,1807.97,1807.73,1806.2,1806.61,1805.7,1806.68,1803.9,1803.6,1805.12,1804.65,1804.46,1803.84,1804.12,1804.19,1804.03,1804.08,1803.19,1803.68,1804.62,1806.05,1805.96,1804.11,1804.88,1804.75,1804.09,1805.99,1807.05,1806.07,1805.43,1806.13,1805.55,1805.37,1806.04,1805.33,1805.71,1804.39,1805.55,1805.98,1805.92,1806.26,1806.75,1807.94,1807.94,1806.44,1805.58,1797.93,1801.76,1801.66,1800.78,1801.38,1803.49,1804.43,1808.19,1807.04,1805.66,1804.07,1802.9,1800.98,1798.89,1795.92,1796.56,1796.98,1796.28,1795.17,1794.54,1794.1,1793.31,1792.45,1792.67,1791.25,1790.63,1790.2,1790.11,1788.61,1789.5,1795.04,1795.92,1793.89,1796.89,1800.15,1800.5,1800.21,1802.64,1804.55,1804.84,1805.84,1807.15,1807.24,1805.82,1805.64,1807.77,1804.15,1804.84,1806.15,1806.2,1806.2,1836.95,1822.65,1828.58,1825.81,1825.86,1828.17,1831.72,1836.27,1832.02,1832.95,1834.46,1833.35,1834.84,1835.07,1835.68,1835.72,1834.39,1834.35,1834.53,1834.81,1835.48,1834.77,1834.36,1834.79,1834.1,1835.38,1834.66,1835.42,1835.42,1834.38,1834.57,1834.89,1834.52,1834.25,1834.75,1834.15,1834.5,1834.14,1833.16,1832.76,1832.37,1832.08,1832.26,1832.94,1831.99,1832.25,1833.31,1825.75,1826.47,1830.36,1830.47,1830.47,1839.29,1834.89,1833.65,1827.13,1831.66,1831.4,1832.52,1832.56,1833.3,1830.83,1830.48,1830.08,1827.54,1826.32,1826.42,1825.77,1827.66,1827.32,1826.92,1826.86,1828.03,1829.72,1829.01,1828.58,1827.99,1828.75,1827.54,1827.4,1827.41,1826.06,1824.72,1824.77,1824.98,1827.12,1827.67,1827.29,1827.25,1826.65,1827.87,1826.31,1826.19,1827.21,1826.26,1826.51,1824.8,1823.32,1825.96,1815.28,1813.02,1824.53,1824.53,1829.39,1829.45,1829.55,1823.46,1827.68,1829.31,1834.55,1835.67,1833.12,1829.95,1828.61,1827.77,1828.37,1831.42,1832.32,1832,1838.44,1842.31,1842.87,1847.72,1849.69,1850.15,1850.34,1851.34,1851.11,1852.27,1855.06,1855.43,1855.92,1856.73,1856.81,1855.7,1855.86,1857.16,1857.4,1858.35,1859.02,1857.66,1857.2,1857.41,1857.03,1856.28,1856.33,1857.6,1857.11,1857.97,1858.88,1859.41,1859.52,1855.5,1855.27,1857.91,1857.91,1875.73,1872.73,1882.35,1879.13,1878.83,1877.02,1878.49,1880.35,1876.83,1873.92,1872.87,1870.74,1869.51,1869.06,1869.19,1869.31,1868.72,1868.63,1868.46,1868.9,1867.9,1867.72,1871.27,1872.02,1872.09,1872.44,1872.62,1874.95,1878.49,1878.14,1882.26,1882.88,1886.24,1885.82,1885.44,1883.86,1880.45,1880.42,1879.3,1879.44,1876.58,1874.75,1873.92,1872.93,1872.43,1869.4,1866.95,1865.78,1868.1,1869.04,1869.04,1871.18,1872.93,1873.1,1881.5,1880.67,1884.92,1883.75,1886.11,1893.63,1886.61,1882.67,1882.12,1880.28,1877.9,1879.48,1878.57,1879.03,1878.58,1876.1,1873.05,1872.3,1870.73,1869.91,1867.49,1865.27,1862.68,1865.64,1866.3,1865.68,1865.69,1864.59,1867.75,1871.54,1872.93,1873.55,1871.43,1872.18,1872.99,1875.07,1875.4,1875.95,1875.69,1878.15,1880.68,1882.56,1884.1,1881.89,1882.78,1878.52,1879.01,1879.07,1878.02,1878.02,1886.15,1879.88,1871.81,1872.46,1867.98,1872.17,1870.8,1869.52,1869.38,1869.87,1869.42,1868.78,1867.17,1867.37,1866.41,1865.51,1866.13,1864.22,1864.17,1863.65,1862,1860.93,1859.59,1858.99,1858.4,1861.46,1863.71,1861.62,1861.86,1861.84,1861.35,1862.22,1862.07,1869.34,1868.51,1866.09,1866.16,1864.5,1862.71,1862.51,1863.17,1862.81,1862.45,1860.49,1857.34,1857.92,1864.05,1863.08,1857.25,1853.1,1862.41,1863.07,1863.07,1851.12,1857.9,1860.27,1865.53,1865.83,1873.23,1867.42,1868.69,1867,1865.67,1865.21,1862.93,1860.78,1858.37,1861.09,1865.79,1864.64,1862.15,1861.48,1860.4,1860.44,1859.05,1858.99,1858.57,1859.14,1858.05,1857.19,1856.46,1856.22,1855.99,1858,1858.69,1859.48,1859.98,1862.23,1862.25,1860.63,1859.81,1861.25,1864.48,1866.01,1865.87,1866.14,1863.78,1862.48,1863.4,1866.27,1868.32,1865.2,1863.69,1865.97,1871.91,1871.91,1870.42,1867.46,1866.21,1860.76,1863.15,1861.76,1863.27,1864.42,1862.12,1860.92,1861.09,1861.65,1862.07,1862.8,1862.24,1861.48,1860.97,1859.48,1858.42,1859.49,1859.31,1860.29,1859.72,1858.36,1857.55,1857.53,1857.19,1856.86,1856.74,1856.65,1856.71,1854.61,1854.56,1857.82,1859.56,1859.68,1860.8,1860.19,1859.99,1857.97,1856.53,1858.86,1857.77,1856.32,1856.65,1854.05,1858.04,1850.86,1850.84,1856.39,1854.97,1854.97,1853.87,1850.17,1854.06,1857.96,1853.56,1852.35,1850.56,1849.62,1848.83,1849.59,1849.15,1851.12,1854.32,1854.74,1854.68,1858.11,1856.78,1855.27,1857.58,1857.69,1857.17,1857.01,1858.14,1857.45,1857.31,1857.58,1857.41,1858.45,1858.52,1859.35,1862.2,1859.42,1859.01,1860.61,1860.72,1860.04,1860.6,1860.12,1860.25,1861.18,1860.45,1860.44,1859.41,1858.42,1858.52,1857.99,1858.58,1853.73,1854.01,1857.78,1860.01,1860.01,1860.9,1860.88,1860.27,1862.74,1865.47,1863.74,1864.98,1865.11,1865,1865.55,1864.27,1864.8,1865.95,1865.45,1866.02,1867.92,1867.47,1868.68,1870.92,1870.35,1867.87,1866.96,1866.38,1865.87,1865.47,1865.34,1864.82,1864.73,1869.27,1869.34,1870.27,1869.49,1870.61,1870.79,1869.75,1868.9,1867.69,1866.61,1866.07,1865.45,1865.42,1866.14,1865.94,1867.32,1867.36,1868.55,1866.78,1868.13,1863.99,1863.94,1864,1867.21,1867.21,1868.85,1868.33,1870.14,1872.8,1871.15,1870.86,1868.78,1866.34,1866.29,1866.48,1868.59,1868.35,1867.11,1866.68,1866.05,1866.57,1866.02,1864.93,1864.46,1864.19,1865.96,1867.84,1871.23,1869.79,1870,1869.89,1870.52,1869.85,1869.62,1869.42,1868.28,1867.86,1868.18,1867.83,1867.61,1867.57,1867.56,1867.74,1867.88,1868.24,1865.59,1865.59,1865.16,1865.3,1863.91,1866.21,1869.77,1869.97,1868.86,1863.32,1866.35,1866.35,1868.44,1867.08,1867.63,1866.56,1866.53,1868.01,1867.23,1870.48,1870.24,1868.22,1867.46,1865.41,1864.57,1863.98,1864.24,1864.53,1863.73,1863.28,1863.53,1862.7,1861.46,1860.99,1859.86,1860.93,1860.25,1860.14,1860.68,1859.06,1858.99,1859.09,1859.13,1858.4,1858.14,1858.88,1859.49,1859.69,1859.84,1860.46,1862.41,1863.77,1864.37,1864.15,1864.47,1863.92,1863.71,1863.21,1862.73,1862.46,1859.91,1859.52,1859.6,1862.08,1862.08,1879.13,1869.8,1870.52,1868.3,1868.4,1869.41,1869.33,1865.63,1863.45,1860.16,1858.62,1857.48,1861.92,1862.07,1863.15,1861.3,1860.32,1860.27,1860.61,1860.21,1859.74,1860.15,1860.22,1860.14,1861.2,1861.3,1860.56,1860.15,1860.16,1859.38,1859.59,1859.93,1859.86,1860.48,1858.7,1858.72,1857.03,1857.22,1857.43,1856.54,1854.16,1848.45,1847.9,1848.45,1837.4,1839.69,1842.02,1838.39,1839.44,1843.5,1843.5,1840.56,1843.67,1844.99,1842.62,1840.73,1843.23,1842.6,1841.78,1841.13,1838.54,1836.91,1833.56,1837.02,1835.72,1835.52,1835.21,1834.15,1834.36,1833.3,1831.9,1831.12,1829.96,1830.52,1829.82,1828.59,1826.84,1826.71,1827.87,1827.82,1832.74,1833.13,1834.47,1837.61,1837.99,1838.62,1839.03,1838.04,1836.36,1839.37,1840.33,1840.56,1839.67,1840.5,1841.08,1842.85,1845.25,1846.6,1844.29,1844.68,1848.57,1848.25,1848.25,1844.23,1848.93,1848.42,1850.02,1848.7,1846.97,1846.31,1845.8,1845.39,1843.07,1844.79,1844.88,1845.35,1848.39,1850.46,1851.29,1851.07,1849.98,1850.32,1854.8,1855.23,1854.77,1853.18,1852.53,1852.44,1852.07,1851.84,1851.21,1851.68,1850.26,1850.35,1850.69,1850.36,1851.46,1852.05,1852.27,1853.38,1853.7,1853.89,1853.81,1852.63,1853.48,1851.81,1851.21,1852.31,1852.81,1853.42,1850.62,1853.7,1853.7,1842.59,1847.42,1849.25,1849.1,1849.95,1849.07,1848.48,1847.46,1845.82,1844.98,1845.15,1844.03,1842.12,1841.99,1843.11,1843.98,1844.26,1843.93,1844.55,1844.85,1845.54,1845.74,1845.79,1845.63,1845.22,1844.66,1844.69,1844.67,1844.75,1844.09,1843.81,1843.79,1844.6,1844.69,1844.97,1846.48,1844.79,1844.25,1842.96,1842.29,1843.98,1843.8,1842.16,1842.75,1841.71,1842.34,1843.31,1839.45,1838.5,1839.09,1840.7,1840.7,1840.13,1843.93,1844.65,1841.58,1839.39,1838.58,1837.47,1837.65,1838.67,1838.45,1838.22,1838.23,1837.89,1837.55,1837.2,1837.3,1836.6,1836.39,1836.61,1835.55,1834.45,1834.66,1835.32,1834.35,1834.49,1834.01,1834.23,1833.23,1833.18,1832.98,1833.16,1834.65,1833.74,1834.3,1839.65,1839.71,1839.16,1838.75,1838.98,1838.57,1836.87,1835.39,1836.04,1834.99,1834.6,1831.47,1830.41,1825.04,1825.99,1827.39,1828.34,1828.34,1831.39,1818.71,1822.49,1821.23,1819.92,1818.21,1816.04,1815.87,1815.39,1816.19,1815.78,1814.57,1809.98,1810.75,1810.04,1809.7,1810.71,1811.21,1812.69,1812.42,1811.97,1811.33,1809.19,1805.74,1804.13,1802.63,1799.38,1801.54,1801.51,1803.12,1806.06,1805.35,1803.84,1805.41,1805.34,1805.36,1803.33,1799.77,1793.51,1794.35,1794.7,1790.09,1792.89,1792.7,1782.51,1790.82,1796.77,1791.45,1789.58,1788.65,1800.54,1800.54,1790.06,1790.65,1794.19,1797.1,1798.21,1793.03,1788.08,1789.5,1788.96,1787.74,1784.75,1783.18,1780.58,1778.08,1774.69,1775.22,1778.77,1778.84,1777.4,1778.1,1781.74,1783.84,1783.55,1782.36,1781.48,1781.11,1781.07,1782,1782.42,1782.45,1786.41,1788.52,1793.83,1797.91,1796.07,1795.1,1798.13,1799.74,1799.32,1797.96,1799.73,1797.92,1800.72,1799.59,1799.58,1801.18,1801.74,1804.67,1802.2,1803.09,1806.63,1806.63,1805.55,1797.64,1793.84,1794.2,1793.75,1793.78,1788.86,1785.43,1786.13,1785.63,1785.71,1784.96,1783.82,1784.39,1783.53,1781.11,1785.07,1789.61,1789.1,1789.92,1788.6,1789.22,1788.37,1788.55,1788.92,1789.25,1791.07,1790.96,1791.07,1789.81,1788.84,1788.2,1786.16,1787.32,1787.32,1785.62,1786.5,1786.16,1782.9,1785.71,1784.42,1786.77,1787.64,1786.27,1781.17,1777.59,1785.15,1779.71,1776.32,1776.8,1782.12,1782.12,1766.1,1777.36,1778.52,1779.68,1778.55,1783.09,1784.2,1782.25,1778.68,1778.63,1777.05,1774.51,1773.88,1771.95,1768.55,1768.12,1769.79,1768.32,1766.85,1765.11,1762.55,1763.06,1763.86,1762.18,1761.17,1765.96,1766.27,1766.19,1765.97,1765.48,1764.45,1762.58,1760.09,1758.93,1761.3,1764.09,1770.35,1771.38,1779.65,1781.55,1783.66,1785.8,1789.89,1791.15,1797.87,1796.55,1802.64,1791.92,1794.46,1799.87,1804.24,1804.24,1801.34,1801.68,1796.65,1795.08,1795.08,1795.76,1796.48,1795.08,1794.91,1793.57,1791.15,1790.91,1792.86,1793.81,1794,1791.92,1791.47,1791.62,1791.05,1790.22,1791.08,1791.21,1792.14,1793,1794.69,1796.49,1796.61,1796.68,1792.94,1790.77,1793.68,1793.86,1794.07,1794.09,1794.91,1794.05,1794.53,1793.11,1793.64,1792.79,1793.53,1793.4,1791.05,1789.92,1789.67,1790.63,1784.83,1782.12,1787.45,1787.45,1780.32,1781.59,1779.49,1777.02,1778.21,1777.92,1779.99,1779.97,1779.38,1778.66,1777.37,1776.5,1772.19,1770.4,1770.85,1771.46,1771.65,1771.36,1769.84,1767.42,1765.67,1765.43,1760.61,1760.24,1756.45,1754.79,1753.89,1754.37,1754.38,1753.69,1756.32,1754.17,1752.03,1750.34,1748.36,1746.58,1746.55,1747.21,1753.13,1756.24,1753.52,1751.25,1751.18,1746.77,1740.08,1738.18,1743.13,1738.42,1736.47,1738.01,1743.51,1743.51,1730.85,1742.89,1738.32,1742.64,1745.86,1745.97,1748.5,1749.37,1746.3,1744.89,1744.35,1749.09,1748.13,1746.52,1746.25,1745.87,1744.16,1742.5,1742.35,1738.27,1739.6,1738.19,1737.91,1736,1735.08,1734.02,1734.4,1734.61,1734.63,1734.61,1736.66,1738.25,1737.87,1736.2,1735.33,1734.52,1734.56,1735.1,1730.43,1726.4,1731.87,1730.82,1728.15,1727.62,1729.24,1727.05,1729.78,1725.01,1723.01,1731.15,1730.56,1730.56,1722.75,1735.74,1732,1730.74,1732.75,1726.9,1719.04,1717.93,1714.74,1713.35,1703.79,1705.29,1700.73,1703.78,1702.23,1699.01,1697.03,1700.17,1705.61,1703.16,1702.35,1701.8,1700.76,1704.62,1698.65,1695.24,1692.41,1692.45,1692.9,1685.75,1688.04,1685.86,1681.54,1679.66,1682.47,1694.18,1691.82,1688.49,1688.5,1686.75,1690.54,1698.21,1687.65,1689.4,1679.85,1680.92,1672.93,1664.27,1665.29,1664.23,1668.53,1668.53,1654.35,1659.39,1674.5,1680.51,1680.41,1673.75,1675.01,1672.6,1668.02,1663.17,1665.17,1671.67,1675.42,1673.95,1674.04,1681.68,1677.69,1674.47,1669.69,1671.21,1669.53,1666.59,1666.91,1663.4,1660.75,1659.26,1660.7,1660.43,1660.77,1660.7,1670.22,1673.6,1683.68,1680.21,1680.26,1682.94,1688.43,1700.36,1695.39,1694.88,1693.23,1692.16,1695.87,1700.09,1697.35,1696.06,1693.3,1694.75,1694.18,1696.45,1699.33,1699.38,1699.38,1701.88,1679.77,1685.37,1685.11,1682.66,1683.14,1686.53,1685.89,1686.02,1682.32,1680.84,1682.24,1682.49,1681.27,1677.67,1675.6,1675.42,1678.71,1682.94,1684.5,1691.39,1690.02,1690.01,1692.11,1694.3,1695.55,1693.92,1692.68,1693.63,1693.61,1688.44,1689.91,1687.41,1688.56,1689.4,1689.7,1686.64,1686.45,1688.96,1688.49,1688.66,1686.44,1688.37,1688.59,1688.66,1687.44,1685.9,1682.91,1680.34,1682.26,1686.11,1686.11,1684.74,1692.2,1692.72,1696.95,1696.63,1695.25,1700.59,1697.95,1696.88,1693.37,1691.53,1689.76,1689.94,1689.49,1691.92,1689.72,1689.54,1688.8,1687.9,1685.86,1683.49,1682.89,1681.35,1682.31,1683.03,1682.53,1680.97,1682.54,1682.53,1686.15,1688.02,1686.86,1685.08,1682.55,1683.72,1683.42,1683.15,1683.18,1685.51,1684.43,1686.32,1686.14,1685.92,1684.08,1679.8,1679.14,1670.91,1665.14,1663.61,1663.15,1669.01,1669.01,1648.61,1649.61,1651.23,1657,1662.14,1658.8,1663.57,1665.84,1664.64,1662.25,1663.11,1660.99,1658.51,1657.97,1659.94,1660.1,1665.19,1665.93,1666.03,1664.6,1663.98,1669.56,1669.29,1673.68,1675.11,1674.28,1674.18,1672.18,1671.89,1673.42,1673.4,1674.56,1677.09,1681.67,1683.94,1682.12,1679.56,1680.1,1678,1678.07,1680.36,1679.2,1679.76,1679.75,1677.05,1678.73,1677.11,1676.17,1676.58,1677.87,1678.71,1679.88,1680.62,1680.62,1682.93,1682.92,1679.77,1679.98,1684.24,1683.45,1680.91,1681.75,1680.93,1680.72,1680.39,1675.3,1676.75,1678.35,1682.23,1681.92,1682.99,1683.09,1682.97,1683.3,1683.17,1681.25,1682.2,1681.54,1679.31,1680.63,1679.86,1681.22,1683.96,1684.18,1693.57,1702.93,1697.27,1694.25,1696.01,1695.06,1693.08,1692.82,1693.23,1690.61,1697.42,1696.11,1697.89,1695.51,1694.96,1699.38,1697.79,1700.87,1701.57,1703.32,1704.68,1704.68,1706.4,1705.65,1705.52,1709.87,1712.51,1719.15,1719.24,1718.74,1719.39,1719.58,1719.35,1720.11,1720.07,1719.34,1718.75,1718.99,1722.03,1725.3,1727.14,1728.58,1727.19,1726.56,1727.07,1729.51,1731.8,1733,1734.12,1735.26,1735.48,1737.22,1739.92,1740.69,1739.52,1738.84,1738.9,1739.53,1737.41,1733.59,1733.28,1737.68,1739.63,1739.44,1740.82,1742.17,1743.95,1743.81,1743.04,1744.3,1744.15,1745.44,1744.66,1744.66,1765.5,1766.9,1757.89,1751.2,1753.39,1749.06,1754.44,1752.87,1752.49,1749.11,1748.09,1749.21,1757.69,1759.37,1755.25,1755.47,1755.14,1755.93,1755.35,1754.78,1753.12,1751.69,1749.99,1749.19,1749.7,1749.91,1750.03,1750.2,1749.26,1749.18,1745.29,1745.37,1747.59,1747.92,1746.72,1746.83,1743.96,1743.2,1745.25,1744.01,1743.26,1740.13,1735.57,1737.98,1741,1739.18,1738.13,1736.31,1718.7,1723.06,1724.92,1735.78,1735.78,1736.06,1744.68,1745.38,1739.91,1737.43,1742.56,1744.69,1750.52,1751.82,1749.37,1749.38,1748.62,1747.79,1748.25,1748.81,1749.05,1749.47,1752.49,1752.48,1752.45,1751.76,1752.19,1752.12,1753.48,1754.66,1754.35,1755.05,1755.77,1755.95,1756.34,1758.91,1758.82,1760.77,1761.68,1765,1763.54,1762.48,1764.26,1764.22,1765.36,1766.51,1765.67,1763.3,1759.21,1761.43,1761.74,1760.11,1760.65,1760.92,1763.27,1762.84,1762.84,1768.41,1769.08,1762.81,1760.08,1769.67,1765.69,1763.52,1761.63,1763.52,1766.39,1771.53,1771.2,1772.41,1773.13,1773.94,1774.94,1776.27,1773.62,1774.3,1773.51,1772.37,1771.06,1769.09,1769.57,1770.65,1769.97,1770.96,1770.43,1769.48,1769.04,1767.68,1768.63,1767.45,1768.91,1771.78,1772.92,1772.59,1771.01,1771,1771.51,1770.62,1771.68,1772.11,1773.69,1771.48,1771.67,1772.34,1775.19,1770.97,1772.13,1774.04,1777.23,1777.23,1785.34,1786.97,1789.44,1787.39,1788.15,1786.24,1783.53,1783.36,1781.85,1782.72,1785.14,1784.75,1784.96,1786.95,1787,1786.6,1787.89,1787.42,1787.05,1786.68,1786.44,1786.28,1786.15,1785.88,1787.13,1786.39,1785.59,1785,1786.31,1786.27,1783.83,1783.6,1782.9,1781.89,1780.09,1780.5,1781.41,1781.59,1780.08,1778.59,1778.87,1778.15,1775.35,1775.43,1777.32,1774.78,1773.96,1776.84,1769.46,1771.71,1775.11,1776.46,1776.46,1787.99,1781.7,1780.68,1778.69,1774.75,1776.16,1776.63,1776.04,1775.41,1776.31,1779.28,1779.64,1782.84,1783.05,1781.08,1778.64,1780.04,1779.02,1777.36,1775.46,1775.05,1774.33,1773.26,1772.57,1772.16,1772.09,1772.59,1772.1,1772.02,1768.77,1772.87,1774.33,1774.59,1771.95,1771.29,1770.6,1771.17,1771.61,1771.69,1770.89,1770.75,1770.7,1768.09,1766.26,1765.48,1769.83,1771.03,1765.28,1765.29,1764.73,1764.78,1764.78,1763.39,1757.76,1757.96,1757.31,1760.97,1762.29,1759.76,1761.73,1758.54,1759.13,1758.95,1761.68,1764.12,1769.36,1772.23,1769.87,1773.49,1773.32,1772.1,1772.18,1772.93,1772.43,1771.35,1770.44,1769.73,1768.14,1767.83,1767.96,1767.88,1767.71,1768.11,1767.67,1768.7,1771.13,1772.55,1772.9,1773.05,1772.47,1770.94,1771.71,1772.61,1771.07,1771.99,1770.58,1769.96,1770.18,1768.29,1767.99,1767.3,1766.91,1768.02,1768.06,1768.06,1760.86,1769.13,1772.77,1766.07,1760.38,1762.5,1761.6,1764.32,1766.72,1775.11,1771.17,1774.07,1772.36,1770.97,1771.71,1771.36,1770.53,1769.82,1770.42,1772.96,1772.2,1773.22,1773.4,1775.87,1778.6,1778.76,1781.1,1779.66,1780.24,1780.4,1780.03,1778.39,1778.64,1778.31,1778.77,1778.79,1779.95,1779.99,1780.1,1781.75,1784.06,1783.89,1782.33,1781.85,1780.79,1779.08,1778.28,1777.92,1774.77,1775.71,1776.84,1776.77,1776.77,1779.97,1788.2,1783.96,1780.42,1775.59,1772.89,1775.34,1776.54,1776.96,1775.91,1778.24,1779.05,1779.07,1777.78,1777.11,1776.4,1780.14,1779.16,1779.02,1780.25,1779.87,1779.43,1778.76,1779.37,1778.9,1779.74,1779.68,1779.33,1779.58,1776.1,1777.31,1777.98,1778.1,1778.95,1782.39,1780.75,1779.71,1778.02,1777.35,1776.04,1775.1,1775.76,1775.86,1775.9,1775.4,1774.41,1774.08,1770.88,1773.41,1773.41,1777.2,1776.49,1776.19,1775.6,1774.8,1775.31,1773.41,1772.21,1777.84,1784.88,1786.29,1790.61,1790.57,1789.4,1788.3,1787.55,1786.21,1786.5,1789.55,1788.37,1786.34,1786.76,1787.69,1788.18,1787.8,1787.9,1788.69,1789.66,1794.01,1792.88,1792.77,1788.92,1788.15,1788.28,1791.27,1792.16,1791.41,1792.24,1791.65,1789.08,1788.6,1791.13,1790.75,1789.35,1788.79,1787.84,1790.23,1791.24,1791.02,1789.85,1790.35,1792.54,1793.18,1793.18,1796.27,1795.84,1798.4,1795.28,1792.83,1790.85,1792.53,1794.78,1793.88,1793.26,1793.27,1793.83,1792.76,1790.81,1791.95,1792.28,1792.03,1792.62,1792.54,1792.29,1792.17,1792.75,1791.75,1791.64,1794.11,1795.44,1795.15,1795.36,1795.54,1792.91,1792.91,1792.52,1790.61,1787.53,1788.71,1788.73,1785.1,1781.64,1781.43,1783.81,1781.7,1776.48,1773.06,1772.38,1770.73,1767.88,1767.4,1765.15,1764.46,1765.06,1765.63,1765.63,1763.92,1764.1,1758.04,1755.77,1756.8,1758.48,1758.71,1756.11,1750.51,1744.18,1758.21,1756.6,1752.44,1751.69,1751.97,1753.62,1752.5,1752.16,1754.03,1753.53,1753.37,1752.78,1750.65,1749.8,1749.5,1747.9,1744.94,1743.64,1744.5,1744.75,1741.39,1744.53,1742.58,1742.64,1742.99,1741.94,1742.06,1740.53,1738.73,1735.1,1733.12,1738.59,1732.71,1730.22,1731.25,1727.97,1727.36,1729.4,1723.38,1728.4,1728.27,1729.08,1729.08,1726.52,1733.27,1733.36,1727.11,1722.05,1728.46,1730.25,1730.93,1731.08,1732.05,1730.53,1730.68,1729.15,1725.7,1725.97,1726.5,1725.61,1721.78,1721.09,1718.67,1719.27,1718.09,1717.4,1719.71,1721.51,1719.71,1718.9,1719.15,1719.27,1719.76,1719.94,1719.63,1719.63,1720.54,1726.03,1725.31,1725.16,1726.97,1729.59,1728.69,1726.4,1726.48,1728.6,1725.08,1723.68,1725.01,1723.76,1722.93,1723.16,1723.42,1727.46,1727.46,1724.75,1731.92,1734.72,1731.07,1731.66,1734.02,1738.23,1743.72,1741.59,1742.38,1747.41,1748.63,1749.42,1750,1750.69,1746.21,1744.91,1742.13,1738.84,1739.56,1741.64,1740.5,1739.78,1738.83,1737.61,1735.91,1735.51,1734.78,1734.72,1731.58,1731.6,1732.09,1731.67,1732.75,1732.85,1733.31,1732.56,1731.53,1730.18,1729.26,1728.21,1726.77,1724.8,1727.08,1728.77,1726.43,1730.12,1729.41,1730.75,1732.02,1732.02,1734.92,1731.75,1733.82,1733.5,1730.14,1729.3,1727.88,1726.76,1728.98,1729.35,1728.58,1728.32,1728,1728.96,1729.72,1729.86,1728.11,1727.8,1727.93,1726.7,1725.61,1725.07,1723.59,1721.72,1721.91,1721.64,1723.21,1723.01,1724.52,1724.13,1722.95,1722.64,1723.4,1724.17,1726.03,1724.5,1724.48,1722.48,1723.09,1722.31,1720.93,1719.65,1721.72,1722.35,1722.7,1723.76,1724.62,1726.35,1724.62,1724.21,1724.52,1726.69,1726.69,1730.18,1730.06,1739.42,1735.19,1737.35,1739.66,1741.07,1741.89,1739.56,1741.05,1737.85,1736.93,1737.52,1737.31,1735.47,1734.67,1734.62,1735.12,1736.55,1735.21,1734.89,1734.65,1735.06,1735.42,1734.87,1733.39,1732.53,1732.36,1731.91,1731.81,1730.2,1730.62,1731.31,1732.27,1730.64,1732.21,1732.72,1731.5,1732.79,1733.49,1734.83,1737.83,1739.32,1737.97,1737.08,1736.46,1734.9,1735.67,1732.35,1732.01,1733.24,1734.24,1734.24,1735.78,1732.02,1731.91,1725.96,1727.72,1728.79,1730.13,1729.41,1729.14,1729.63,1729.13,1730.67,1730.13,1731.21,1730.65,1730.67,1730.69,1731.43,1732.01,1734.67,1734.38,1734.97,1735.2,1735.81,1737.64,1738.07,1738.57,1738.98,1739.13,1741.62,1745.79,1745.27,1744,1751.56,1754.39,1757.62,1753.63,1757.44,1760.11,1762.83,1763.57,1764.26,1761.06,1761.97,1763.68,1767.42,1766.35,1762.19,1762.54,1767.63,1768.12,1768.12,1779.72,1787.55,1792.33,1785.51,1781.76,1780.63,1783.9,1786.42,1784.22,1784.38,1787.06,1789.46,1791.66,1792.23,1793.74,1793.94,1793.88,1793.3,1792.54,1790.26,1789.8,1788.34,1786.54,1784.53,1785.67,1787.56,1789.18,1788.8,1788.67,1788.75,1789.07,1790.11,1789.81,1789.91,1789.1,1789.79,1788.67,1787.26,1786.69,1788.25,1786.23,1785.45,1787.45,1789.29,1789.79,1787.22,1786.33,1786.94,1786.2,1786.03,1787.95,1788.78,1788.78,1792.14,1792.36,1792.74,1790.58,1798.79,1802.62,1799.9,1801.33,1801.42,1801.04,1797.06,1796.24,1796.87,1798.34,1800.18,1801.63,1804.5,1804.83,1807.74,1806.59,1806.49,1806.06,1807.23,1809.2,1807.13,1806.73,1806.62,1807.5,1806.43,1807.07,1807.11,1802.64,1802.17,1799.76,1795.55,1794.99,1798.81,1799.69,1799.86,1797.58,1795.22,1794.52,1788.3,1790.1,1793.7,1795.25,1791.4,1795.12,1793.53,1789.38,1789.11,1791.48,1791.41,1791.41,1790.88,1796.06,1793.93,1790.75,1796.85,1803.06,1800.24,1801.91,1800.56,1799.62,1801.15,1799.72,1799.25,1799.95,1797.68,1795.34,1797.28,1795.65,1794.83,1793.34,1792.14,1793.33,1793.01,1792.73,1794.91,1795.43,1794.55,1795.75,1795.63,1794.13,1795.33,1795.18,1796.99,1797.48,1797.16,1799.42,1800.1,1802.33,1806.44,1808.91,1809.36,1807.98,1806.34,1806.18,1808.76,1811.05,1812.36,1810.66,1811.41,1818.06,1821.32,1821.32,1826.13,1825.95,1822.24,1827.54,1831.49,1829.43,1837.91,1835.57,1834.47,1829.89,1824.76,1826.5,1825.85,1823.63,1822.49,1822.47,1823.16,1820.82,1819.79,1819.38,1820.66,1822.15,1823.45,1824.14,1823.07,1822.37,1822.74,1821.55,1823.15,1822.69,1822.66,1821.34,1818.69,1820.5,1819.28,1815.67,1819.64,1820.72,1821.69,1822.41,1822.47,1822.13,1821.67,1821.73,1822.47,1820.69,1823.46,1825.61,1828.21,1832.98,1829.66,1830.85,1831.56,1831.56,1830.53,1824.24,1830.29,1829.96,1830.4,1827.17,1823.86,1821.92,1822.66,1823.75,1825.74,1828.34,1826.39,1823.81,1824.94,1824.46,1825.54,1824.5,1824.58,1827.97,1828.56,1830.88,1831.04,1830.72,1829.97,1829.26,1828.92,1828.12,1828.05,1825.97,1827.76,1827.77,1831.55,1834.63,1836.23,1836.06,1836.29,1835.99,1836.53,1836.57,1837.32,1837.38,1837.36,1837.48,1832.16,1832.31,1833.1,1825.83,1828.7,1832.14,1832.12,1832.12,1807.2,1825.07,1815.77,1819.25,1819.27,1815.8,1813.56,1811.07,1809.43,1810.85,1810.53,1810.29,1806.82,1803.88,1803.13,1803.85,1804.52,1805.19,1804.01,1810.04,1813.5,1816.01,1817.46,1821.71,1819.42,1818.27,1821.47,1820.91,1821.47,1821.61,1822.29,1823.73,1823.29,1822.71,1818.7,1819.7,1820.4,1819.23,1818.5,1821.08,1824.1,1825.41,1824.66,1823.31,1822.19,1821.94,1826.86,1829.8,1826.28,1820.45,1827.75,1827.72,1827.72,1828.5,1844.51,1842.96,1855.19,1860.67,1858.81,1859.68,1857.55,1851.38,1850.27,1849.68,1849.62,1850.32,1851.06,1850.74,1849.8,1849.8,1848.87,1848.28,1847.6,1847.2,1848.04,1848.12,1846.32,1846.62,1847.17,1847.82,1847.39,1847.54,1847.74,1849.23,1848.68,1846.35,1845.41,1845.17,1845.48,1845.59,1846.46,1848.17,1849.6,1849.76,1849.22,1849.5,1852.18,1857.49,1858.8,1858.16,1852.39,1853.95,1853.42,1853.08,1853.08,1855.14,1868.63,1869.58,1865.65,1863.71,1865.12,1867.27,1865.78,1862.69,1862.44,1865.6,1866.88,1865.49,1865.2,1863.15,1862.59,1860.69,1858.01,1854.61,1854.34,1851.86,1847.28,1850.59,1848.78,1847.04,1845.29,1843.83,1838.92,1839.16,1840.62,1847.26,1851.17,1851.17,1852.14,1849.25,1850.94,1850.69,1850.24,1849,1846.87,1843.07,1839.95,1840.3,1833.77,1832.26,1833,1831.69,1821.36,1820.38,1821.64,1821.64,1816.45,1817.06,1827.21,1822.08,1818.92,1815.14,1820.21,1824.64,1821.91,1820.92,1821.21,1818.67,1820.19,1818.82,1818.43,1818.93,1818.2,1819.84,1820.2,1820.3,1822.33,1822.92,1821.63,1820.15,1818.78,1817.74,1817.4,1815.86,1816.99,1817,1819.51,1821.63,1822.51,1820.23,1824.53,1823.22,1828.04,1829.58,1829.85,1828.2,1826.26,1828.65,1828.77,1830.02,1827.6,1825.88,1828.89,1828.65,1828.39,1828.38,1829.14,1830.44,1830.44,1835,1836.52,1836.75,1836.56,1838.89,1844.22,1845.04,1847.25,1842.44,1842.72,1844.32,1846.51,1843.99,1844.34,1840.69,1840.71,1839.25,1839,1838.28,1837.54,1838.07,1837.71,1838.58,1838.97,1836.48,1832.41,1836.11,1835.4,1835.59,1835.03,1834.16,1835.16,1834.62,1833.75,1833.01,1834.32,1834.44,1834.16,1832.66,1833.34,1832.86,1830.48,1827.9,1826.28,1825.97,1824.8,1823.59,1822.9,1825.16,1827.74,1827.12,1827.12,1830.48,1827.75,1827.53,1818.6,1821.83,1824.47,1823.62,1824.81,1825.17,1821.51,1823.67,1823.51,1823.44,1822.02,1822.43,1822.56,1821.5,1821.57,1820.58,1818.65,1816.41,1813.62,1814.14,1814.62,1814.64,1815.49,1816.72,1818.55,1819.61,1825.79,1826.31,1827.02,1823.8,1822.97,1823.37,1823.17,1825.08,1827.05,1828.38,1828.24,1829.7,1828.5,1829.58,1832.78,1832.6,1833.13,1832.76,1832.07,1834.41,1830.66,1830.74,1828.6,1829.23,1829.23,1820.54,1820.91,1820.44,1821.22,1820.69,1819.69,1821.03,1822.19,1821.22,1819.69,1816.61,1815.88,1815.13,1812.3,1811.46,1812.39,1812.01,1814.3,1817.2,1815.77,1815.08,1812.85,1813.95,1813.77,1813.49,1814.02,1814.13,1813.85,1812.01,1813.2,1813.28,1810.75,1811.68,1811.17,1812.78,1813.94,1814.14,1813.09,1812.08,1812.69,1814.28,1814.99,1813.53,1811.35,1809.29,1804.91,1805.86,1802.53,1798.47,1795.97,1794.87,1794.22,1795.21,1795.21,1789.38,1785.99,1793.34,1794.34,1796.21,1797.25,1794.2,1791.89,1787.78,1788.26,1787.01,1787.23,1782.68,1782.5,1781.74,1787.53,1790.34,1790.29,1788.82,1792.61,1796.73,1794.83,1793.08,1793.02,1791.73,1792.76,1795.07,1792.82,1790.93,1790.8,1796.17,1795.35,1792.55,1792.72,1795.6,1793.68,1790.7,1787.62,1784.22,1777.68,1782.6,1782.88,1785.8,1781.08,1779.91,1780.87,1786.12,1787.31,1783.6,1784.24,1784.02,1788.23,1788.23,1789.42,1791.09,1799.32,1801.24,1797.48,1799.86,1799.04,1798.54,1798.77,1798.41,1799.15,1798.89,1801.62,1803.87,1805.23,1805.67,1804.76,1804.76,1804.82,1804.58,1802.77,1800.28,1800.14,1800.55,1801.33,1801.46,1801.45,1801.5,1802.32,1802.34,1801.39,1802.82,1802.82,1804.47,1805.82,1804.78,1804.38,1804.58,1804.34,1806.82,1807.62,1807.93,1807.74,1809.4,1810.87,1811.46,1810.73,1811.3,1799.78,1805.96,1810.83,1811.15,1811.15],
      "o": [1710.29,1724.57,1728.89,1732.62,1739.54,1742.32,1736.9,1735.74,1734.91,1734.07,1734.94,1739.4,1741.22,1738.83,1734.46,1733.94,1732.79,1732.09,1732.3,1730.9,1729.39,1730.25,1729.5,1728.72,1727.45,1723.6,1719.17,1713.14,1709.99,1710.07,1716.43,1715.82,1714.68,1717.02,1717.52,1721.33,1724.14,1726.52,1721.98,1720.28,1721.8,1725.11,1723.33,1725.69,1724.6,1728.73,1713.13,1727.55,1713.83,1697.31,1705.77,1703.46,1701.53,1696.21,1700.26,1702.69,1704.31,1703.03,1701.06,1700.4,1697.46,1695.86,1696.06,1696.67,1697.68,1700.41,1697.9,1698.66,1700.35,1701.45,1703.29,1700.12,1698.58,1697.66,1696.22,1698.48,1697.08,1692.99,1691.58,1693.97,1691.79,1690.43,1689.82,1692.49,1690.71,1689.05,1687.03,1686.67,1688.29,1693.34,1697.81,1707.63,1705.73,1705.61,1677.09,1697.96,1699.13,1690.51,1680.17,1683.61,1684.44,1679.79,1678.69,1680.77,1681.67,1681.3,1682.07,1678.1,1676.74,1675.91,1676.77,1677.53,1677.58,1679.89,1679.3,1680.62,1680.67,1678.51,1678.38,1677.24,1676.9,1676.15,1675.85,1676,1675.45,1671.91,1671.67,1670.35,1664.51,1666.29,1669.21,1671.71,1670.97,1669.4,1667.15,1667.49,1664.23,1663.18,1659.62,1661.2,1660.35,1657.81,1642.65,1655.36,1647.81,1635.47,1627.52,1626.37,1627.23,1619.63,1612.75,1616.3,1611.15,1605.37,1597.11,1610.72,1606.71,1604.94,1607.36,1609.1,1615.13,1613.08,1610.25,1608.61,1604.52,1602.52,1599.31,1605.23,1609.07,1615.05,1614.84,1613.57,1612.66,1611.9,1610.37,1608.21,1604.19,1602.22,1603.6,1607.93,1604.39,1599.5,1595.64,1599.59,1595.99,1598.28,1601.08,1599.01,1589.06,1591.11,1592.79,1592.92,1591.17,1621.38,1613.26,1616.26,1615.73,1613.28,1614.62,1614.17,1612.65,1610.59,1612.51,1613.35,1614.54,1618.87,1621.18,1619.08,1619.16,1621.2,1625.35,1629.2,1628.97,1627.23,1625.33,1623.57,1623.36,1622.45,1622.23,1622.69,1621.48,1618.69,1619.84,1621.07,1619.71,1612.7,1615.11,1613.89,1613.09,1609.59,1604.38,1607.7,1609.25,1610.75,1608.72,1609.08,1604.62,1606.39,1606.13,1614.08,1634.15,1643.01,1643.26,1652.38,1649.97,1648.51,1645.67,1642.72,1644.31,1644.96,1644.97,1644.86,1645.44,1646.68,1650.6,1651.67,1651.07,1650.58,1648.41,1647.88,1647.44,1648.85,1648.08,1647.63,1646.84,1645.47,1646.02,1645.76,1645.91,1643.74,1644.74,1647.37,1646.66,1646.66,1647.36,1649.2,1650.8,1650.84,1649.44,1648.22,1647.49,1649.07,1644.98,1646.73,1649.48,1652.71,1654.13,1658.77,1658.19,1653.71,1652.09,1649.62,1643.98,1642.24,1643.08,1642.43,1641.54,1637.76,1637.97,1639.53,1643.64,1648.52,1644.24,1643.91,1646.02,1644.26,1642.8,1643.82,1643.57,1642.74,1642.66,1643.29,1641.52,1641.69,1640.68,1640.38,1639.59,1635.64,1635.22,1636.31,1636.75,1636.46,1638.82,1639.17,1637.24,1637.1,1641.51,1644.95,1643.42,1645.09,1644.48,1643.57,1645.07,1643.46,1641.41,1644.2,1644.63,1641.72,1644.44,1645.56,1642.45,1642.26,1643.09,1643.8,1643.77,1652.58,1656.69,1652.44,1651.28,1652.1,1650.7,1650.44,1650.62,1650.28,1650.8,1650.11,1650,1649.11,1649.74,1650.88,1652.47,1651.76,1651.64,1652.89,1652.09,1652.14,1651.05,1653.45,1654.14,1656.8,1659.18,1657.5,1660.33,1662.23,1663.45,1663.07,1663.64,1665.11,1669.05,1669.21,1670.68,1671.82,1669.84,1673.31,1672.8,1647.01,1644.58,1642.24,1644.91,1646.62,1644.36,1643.61,1643.45,1642.3,1641.07,1637.91,1641.42,1647.24,1647.13,1652.62,1651.26,1649.52,1652.61,1653.09,1652.53,1651.06,1649.96,1649.91,1648.69,1648.9,1649.06,1650.15,1649.67,1648.92,1650.8,1651.55,1654.52,1657.65,1657.28,1658.07,1662.86,1665.1,1664.19,1667.42,1671.52,1663.88,1664.97,1667.12,1666.93,1665.56,1657.68,1662.21,1662.54,1670.4,1667.05,1667.41,1667.36,1667.11,1666.84,1667.01,1669.08,1670.47,1669.6,1673.53,1676.43,1675.58,1676.24,1677.46,1676.58,1676.46,1676.57,1675.94,1675.54,1674.87,1673.21,1673.25,1673.29,1673.72,1673.91,1673.64,1673.54,1675.09,1674.25,1672.6,1669.22,1669.87,1669.79,1668.87,1668.41,1664.87,1665.19,1666.89,1669.25,1668.97,1668.06,1667.94,1667.15,1666.76,1663.05,1669.72,1674.49,1714.3,1710.97,1709.48,1707.29,1706.68,1707.81,1709.79,1710.42,1711.2,1711.91,1709.3,1709.31,1709.78,1708.45,1706.44,1707.67,1705.2,1705.07,1703.46,1703.59,1705.36,1704.59,1704.85,1704.27,1703.92,1703.42,1704.9,1704.33,1704.18,1702.22,1701.46,1700.23,1703.79,1704.4,1705.54,1706.18,1709.29,1712.93,1710.6,1710.48,1710.92,1707.74,1706.93,1706.51,1707.61,1704.73,1705.74,1702.93,1695.18,1702.2,1698.6,1695.72,1696.01,1693.86,1696.28,1696.31,1697.96,1697.25,1695.77,1695.69,1694.95,1692.61,1691.99,1693.31,1695.72,1695.36,1697.68,1698.85,1696.06,1697.45,1697.33,1696.36,1694.82,1696.03,1694.77,1694.69,1691.14,1691.99,1693.38,1693.8,1692.83,1692.46,1689.3,1687.03,1687.95,1688.28,1686.71,1685.61,1689.86,1691.78,1692.04,1692.77,1694.09,1691.17,1695.13,1694.82,1703.52,1705.63,1707.46,1710.65,1706.8,1711.7,1712.01,1708.36,1709.09,1708.68,1708.33,1707.89,1707.08,1705.9,1704.42,1701.31,1699.84,1698.39,1698.21,1698.7,1700.25,1698.91,1699.39,1700.09,1700.92,1700.21,1699.34,1697.88,1695.62,1694.12,1690.47,1691.18,1690.37,1688.47,1683.6,1687.36,1685.97,1684.17,1686.06,1685.33,1684.07,1681.33,1680.35,1683.82,1683.14,1684.62,1684.09,1682.09,1678.98,1679.99,1685.04,1684.25,1691.36,1691.65,1689.09,1688.18,1686.62,1684.63,1683.42,1680.94,1677.48,1674.04,1676.66,1678.19,1676.2,1676.06,1675.67,1675.77,1676.1,1676.54,1678.67,1677.82,1677.66,1676.33,1676.09,1674.69,1676.27,1676.56,1676.85,1679.78,1679.95,1682.21,1682.06,1682.44,1680.23,1678.78,1678.33,1678.31,1677.23,1674.06,1674.93,1674.79,1671.15,1673.71,1672.72,1677.99,1679.5,1677.73,1673.83,1670.4,1673.04,1677.07,1682.12,1678.81,1682.09,1684.5,1689.66,1686.69,1684.47,1684.46,1684.62,1684.3,1683.44,1682.6,1680.49,1678.46,1679.4,1678.68,1675.78,1674.98,1673.53,1671.91,1672.93,1672.09,1671.69,1675.27,1673.96,1673.23,1671.57,1672.36,1672.18,1671.94,1671.64,1668.27,1669.12,1667.56,1666.07,1666.17,1666.09,1674.16,1676.81,1677.2,1677.08,1677.54,1724.25,1723.81,1719.07,1713.82,1713.85,1712.97,1715.46,1714.96,1717.29,1718.46,1720.66,1722.02,1723.75,1731.45,1731.28,1732.24,1734.38,1736.55,1738.7,1735.13,1732.53,1733.93,1733.51,1734.75,1735.84,1737.6,1736.2,1735.83,1736.35,1740.24,1740.3,1741.97,1744.6,1748.51,1748.12,1748.13,1748.98,1750.13,1752.12,1753.89,1754.82,1754.54,1754.37,1754.97,1753.98,1754.2,1755.53,1756.55,1743.65,1753.57,1750.24,1746.82,1747.25,1748.39,1750.52,1754.66,1753.94,1752.71,1749.59,1746.54,1747.09,1746.91,1747.13,1746.78,1746.06,1745.08,1744.63,1743.5,1741.17,1741.65,1742.65,1742.86,1741.64,1740.63,1738.93,1738.28,1739.26,1742.27,1743.65,1745.62,1745.38,1745.35,1746.16,1746.57,1745.33,1744.24,1745.25,1746.67,1748.57,1750.13,1747.59,1746.82,1742.38,1738.81,1740.04,1736.68,1756.22,1756.17,1756.32,1755.05,1757.58,1760.47,1761.1,1758.38,1753.63,1754.34,1756.27,1756.76,1756.76,1756.9,1756.31,1755.02,1754.96,1755.67,1756.34,1755.58,1758.18,1757.61,1756.18,1756.27,1755.09,1754.74,1754.25,1753.15,1754.36,1755.33,1755.45,1754.69,1756.25,1756.98,1758.74,1758.04,1757.54,1756.68,1757,1756.7,1755.6,1755.09,1753.53,1753.68,1752.11,1747.75,1749.73,1750,1733.93,1739.91,1739.61,1737.85,1742.44,1747.64,1744.53,1743.68,1745.87,1746.06,1747.34,1745.57,1745.26,1745.24,1745.35,1745.81,1744.46,1743.13,1741.91,1741.61,1740.63,1740.79,1741.36,1740.87,1739.91,1740.36,1741.94,1741.12,1742.49,1747.07,1750,1747.01,1749.94,1748.88,1747.69,1751.18,1754.16,1753.85,1756.39,1759.97,1758.96,1765.67,1762.25,1762.04,1758.04,1755.93,1758.96,1775.41,1781.73,1779.57,1782.58,1780.5,1781.23,1779.88,1776.49,1778.04,1779.04,1775.56,1776.78,1776.3,1775.7,1774.86,1772.8,1772.43,1772.92,1773.03,1773.44,1773.68,1774.19,1773.14,1770.92,1770.17,1769.39,1770.03,1769.65,1768.77,1768.55,1771.11,1771.3,1770.19,1767.37,1768.03,1768.35,1769.44,1772.04,1770.09,1770.42,1772.22,1771.07,1771.21,1772.41,1769.88,1771.6,1770.89,1774.53,1775.65,1792.73,1788.22,1789.21,1795.66,1789.62,1791.56,1793.46,1791.73,1791.65,1790.12,1789.38,1788.9,1788.07,1788.82,1790.02,1790.85,1793.36,1792.46,1792.29,1791.52,1790.55,1789.74,1789.75,1790.48,1790.63,1791.56,1791.66,1790.86,1788.78,1790.08,1791,1791.96,1792.79,1795.47,1794.04,1792.72,1794.28,1794.49,1794.45,1793.64,1796.96,1798.31,1800.75,1799.39,1799.65,1799.07,1801.12,1806.2,1808.7,1812.84,1813.53,1811.15,1806.26,1807.64,1807.01,1802.43,1803.06,1806.14,1804.93,1804.28,1805.94,1805.21,1806.34,1809.48,1813.67,1818.95,1815.4,1816.49,1819.34,1819.96,1823.37,1820.22,1820.65,1819.14,1818.74,1817.92,1817.52,1819.08,1818.71,1820.45,1820.45,1822.36,1822.13,1822.72,1821.58,1820.45,1814.97,1817.39,1815.85,1816.63,1818.19,1818.78,1818.87,1817.22,1820.06,1832.33,1844.9,1835.63,1837.5,1838.47,1835.59,1822.87,1826.28,1815.36,1826.62,1828.25,1829.77,1831.65,1832.64,1833.53,1832.06,1829.59,1825.77,1823.54,1821.61,1823.85,1825.75,1827.26,1827.84,1827.48,1826.75,1827.25,1825.72,1825.03,1821.54,1822.33,1827.48,1826.08,1826.76,1832.82,1832.96,1831.14,1829.98,1827.35,1829.2,1827.61,1826.69,1825.77,1822.05,1825.03,1824.19,1818.12,1820.04,1817.17,1805.51,1809.26,1814.58,1814.33,1809.94,1807.74,1804.82,1806.05,1807.14,1809.88,1810.02,1810.2,1813.78,1820.65,1829.57,1821.67,1819.69,1821.94,1824.74,1831.63,1829.06,1834.85,1829.72,1829.09,1826.41,1825.42,1826.33,1825.5,1822.6,1826.71,1830.18,1828.02,1826.98,1825.8,1825.02,1827.17,1827.56,1832.64,1830.7,1827.62,1827.15,1826.55,1829.38,1830.89,1833.32,1838.01,1832.81,1837.11,1859.39,1860.02,1852.48,1851.06,1851.56,1852.54,1858.42,1864.01,1864.88,1859.24,1858.76,1860.83,1863.94,1865.05,1864,1863.16,1862.16,1859.73,1857.52,1857.74,1857.89,1856.24,1856.3,1856.84,1856.68,1857.27,1858,1857.61,1852.36,1852.1,1849.62,1844.5,1849.01,1847.17,1846.96,1848.01,1848.42,1847,1847.02,1847.85,1845.92,1844.04,1843.66,1842.43,1840.12,1833.62,1836.32,1834.53,1835.38,1831.05,1833.51,1832.8,1832.47,1838.68,1837.16,1836.22,1835.47,1834.12,1831.77,1831.32,1829.6,1829.64,1828.95,1830.87,1831.54,1828.64,1827.54,1826.49,1825.7,1825.06,1824.61,1824.38,1820.83,1822.42,1825.08,1824.19,1828.23,1828.79,1835.09,1830.59,1829.87,1838.01,1840.63,1847.89,1855.47,1857.15,1857.87,1858.77,1858.48,1858.04,1857.28,1859.28,1859.73,1855.34,1857.27,1857.3,1871.62,1869.22,1872.2,1879.23,1879.01,1873.16,1878.11,1877.8,1880.28,1879.24,1886.8,1886.17,1881.61,1882.21,1884.57,1878.57,1877.94,1876.94,1874.79,1876.62,1876.3,1877.81,1879.48,1878.96,1876.82,1876.39,1874.63,1873.97,1872.92,1870.31,1868.29,1867.91,1861.03,1866.36,1866.05,1861.05,1859.89,1865,1865.55,1862.46,1855.88,1859.2,1864.22,1870.42,1874.53,1868.58,1873.37,1870.36,1866.85,1867.83,1868.4,1869.24,1871.79,1873.94,1874.73,1872.66,1876.86,1880.61,1877.18,1872.8,1870.98,1870.66,1868.75,1867.17,1865.06,1862.84,1863.36,1865.33,1862.66,1859.91,1862.94,1863.81,1863.75,1862.43,1862.41,1861.47,1859.13,1853.39,1857.52,1855.72,1856.21,1854.77,1847.91,1853.71,1856.51,1855.91,1857.19,1857.1,1858.41,1859.05,1853.27,1855.16,1854.73,1848.08,1853.92,1853.29,1858.74,1862.35,1868.55,1866.98,1868.89,1871.59,1867.47,1868.51,1868.82,1868.62,1870.36,1877.87,1879.17,1878.89,1877.18,1875.63,1882.3,1883.63,1883.25,1885.06,1886.73,1887.03,1887.14,1885.85,1886.51,1887.24,1886.05,1884.69,1876.6,1874.22,1874.62,1872.62,1870.98,1869.23,1872.75,1874.61,1878.08,1876.77,1878.43,1879.28,1875.23,1875.2,1877.13,1880.15,1879.62,1875.1,1876.17,1878.96,1877.07,1877.3,1875.75,1873.99,1873.36,1868.18,1868.73,1868.85,1868.09,1864.78,1863.18,1863.42,1860.87,1859.74,1862.2,1861.33,1860.75,1860.13,1861.65,1862.73,1861.64,1859.86,1859.05,1858.61,1858.66,1859.88,1858.98,1857.97,1860.36,1857.92,1857.55,1854.75,1855.86,1856.17,1857.09,1856.03,1857,1859.81,1857.45,1853.74,1853.99,1856.14,1859.07,1857.1,1854.79,1841.3,1854.7,1854.1,1873.86,1872.32,1870.89,1871.39,1875.03,1876.3,1872.58,1870.6,1868.47,1867.18,1865.19,1867.27,1868.92,1859.46,1859.66,1858.09,1856.33,1857.67,1857.31,1855.4,1854.63,1849.5,1852.42,1855.96,1856.23,1856.82,1855.66,1854.41,1848.01,1841.9,1847.55,1846.89,1845.44,1846.66,1854.04,1854.11,1851.42,1848.75,1852.96,1850.6,1854.75,1858.64,1859.08,1859.06,1856.12,1849.7,1853.19,1853.08,1856.48,1850.91,1849.34,1854.43,1860.06,1862.76,1860.33,1855.54,1853.47,1853.21,1854.3,1857.02,1855.18,1855.91,1855.83,1854.38,1858.23,1861.84,1864.54,1872.27,1867.73,1867.47,1871.83,1875.16,1872.94,1868.76,1869.02,1867.65,1863.32,1862.97,1863.21,1864.14,1864.84,1866.7,1864.21,1864.51,1865.77,1866.33,1866.58,1871.05,1874.07,1874.06,1873.64,1874,1872.68,1872.69,1873.31,1874.85,1882.73,1882.86,1882.62,1882.35,1880.43,1875.6,1879.8,1880.22,1878.7,1875.68,1873.21,1870.6,1873.23,1873.08,1873.3,1872.32,1872.19,1869.94,1869.97,1870.86,1872.39,1871.87,1870.82,1871.48,1871.58,1872.05,1872.19,1871.97,1868.97,1873.09,1874.77,1874.7,1877.94,1879.91,1877.93,1878.49,1877.64,1879.76,1883.44,1885.79,1888.22,1888.86,1888.33,1886.76,1887.55,1888.01,1891.24,1891.2,1900.13,1901.82,1897,1901.69,1906.11,1902.04,1904.04,1902.12,1902.15,1904.2,1901.07,1900.57,1901.4,1900.98,1902.29,1902.18,1904.92,1912.35,1908.06,1908.23,1908.96,1906.72,1906.02,1905.47,1905.79,1907.15,1906.4,1906.19,1903.92,1913.3,1917.95,1919.29,1917.18,1917.26,1917.22,1916.18,1919.1,1913.21,1913.56,1914.6,1904.4,1908.02,1907.11,1909.37,1910.46,1907.47,1912.57,1909.01,1904.01,1905.79,1903.94,1904.06,1898.7,1900.67,1900.69,1902.72,1903.15,1903.24,1901.85,1902.12,1903.25,1903.59,1903.66,1903.53,1904.09,1902.78,1901.07,1902.48,1901.49,1898.12,1900.9,1900.17,1901.15,1900.49,1899.74,1898.49,1899.39,1903.41,1908.51,1912.88,1917.12,1912.42,1914.69,1919.47,1921.49,1917.59,1914.67,1913.71,1913.19,1905.39,1905.3,1907.24,1907.35,1907.3,1915.26,1918.93,1924.97,1924.67,1925.16,1923.38,1923.02,1920.35,1917.99,1919.9,1919.5,1919.9,1921.06,1922.39,1920.76,1922.49,1922.94,1921.14,1920.69,1921.26,1922.41,1923.62,1923.51,1921.84,1921.07,1920.92,1921.6,1920.49,1921.29,1920.67,1918.12,1919.55,1919.83,1921.41,1919.96,1917.05,1915.64,1911.39,1911.68,1911.52,1910.61,1910.95,1909.74,1907.67,1907.11,1904.33,1896.14,1895.44,1901.69,1895.5,1892.17,1889.99,1893.29,1896.41,1897.23,1897.03,1894.77,1891.95,1891.94,1891.81,1891.78,1891.97,1893.34,1894.74,1893.38,1893.22,1891.39,1890.59,1889.16,1889.77,1889.84,1888.47,1888.11,1885.31,1883.15,1880.86,1879.82,1878.49,1878.38,1882.68,1880.87,1880.14,1880.78,1882.08,1882.34,1886.04,1889.39,1892.92,1899.48,1899.31,1905,1901.65,1899.8,1902.24,1900.9,1882.58,1902.19,1901.1,1900.57,1898.86,1901.31,1898.24,1895.1,1892.15,1893.49,1891.16,1892.19,1894.84,1894.69,1895.02,1896.68,1897.25,1895.66,1894.43,1894.4,1895.23,1892.89,1893.12,1892.38,1891.53,1891.04,1891.45,1891.11,1891.74,1892.75,1891.75,1889.8,1890.13,1891.24,1891.75,1892.34,1890.27,1882.66,1881.94,1875.95,1873.18,1871.97,1866.58,1869.67,1867.85,1871.33,1884.65,1895.67,1887.34,1897.61,1898.37,1891.05,1887.84,1889.65,1896.78,1902.07,1899.5,1899.05,1898.95,1897.11,1895.88,1894.81,1896.54,1899.89,1901.91,1902.88,1906.83,1907.8,1907.56,1909.35,1913.13,1919.06,1916.83,1915.33,1915.02,1917.01,1916.41,1918.51,1917.11,1916.01,1920.7,1919.97,1920.21,1918.23,1916.67,1916.7,1919.04,1917.25,1919.49,1920.77,1920.33,1920.03,1917.11,1917.12,1918.4,1917.81,1925.05,1925.86,1925.46,1926.4,1929.66,1926.88,1923.89,1922.75,1917.59,1918.18,1916.6,1915.99,1917.83,1917.32,1917.4,1916.74,1915.31,1915.52,1917.4,1916.18,1919.51,1918.25,1918.76,1918.32,1918.11,1919.03,1918.38,1919.54,1920.76,1921.98,1920.58,1913.3,1912.6,1911.97,1911.52,1910.98,1914,1916.22,1914.29,1914.11,1915.94,1915.45,1916.23,1918.74,1919.43,1922.24,1921.05,1918.77,1910.14,1921.89,1921.6,1911.75,1915.13,1915.24,1915.95,1922.32,1917.63,1915.52,1915.24,1915.04,1914.37,1912.29,1910.17,1909.77,1911.76,1913.82,1912.29,1912.62,1912.63,1912.88,1913.14,1913.67,1913.76,1913.61,1914.85,1916.88,1920.71,1920.76,1919.92,1918.36,1916.93,1915.84,1914.59,1915.54,1917.57,1922.03,1920.71,1920.72,1924.03,1925.77,1923.43,1925.28,1924.54,1923.73,1925.93,1926.37,1924.64,1932.04,1927.94,1928.64,1926.48,1926.45,1922.46,1919.96,1925.29,1924.49,1925.75,1924.66,1924.54,1923.83,1924.53,1923.55,1922.01,1922.37,1921.49,1921.02,1920.59,1920.46,1920.26,1924.49,1923.41,1924.65,1924.2,1925.46,1925.47,1922.7,1922.22,1918.69,1919.43,1920.83,1919.65,1916.12,1914.59,1910.75,1909.87,1915.22,1914.83,1917.43,1919.83,1916.82,1916.61,1912.72,1908.46,1911.23,1905.14,1915.45,1907.1,1909.91,1916.14,1914.86,1918.59,1918.6,1919.32,1915.1,1913.64,1913.3,1912.09,1911.5,1914.55,1915.68,1918.27,1915.7,1915.38,1914.61,1910.81,1908.58,1905.57,1904.94,1902.37,1898.65,1896.59,1898.45,1894.53,1881.87,1880.91,1863.24,1879.39,1882.17,1886.15,1892.56,1888.46,1897.55,1901.92,1899.63,1895.75,1897,1899.94,1901.65,1898.45,1901.57,1904.75,1909.04,1903.12,1910.01,1913.23,1915.21,1907.39,1903.41,1903.16,1905.69,1902.84,1902.18,1902.52,1903.21,1906.17,1904.95,1903.84,1901.95,1903.24,1905.26,1905.82,1902.41,1898.27,1897.2,1892.59,1888.33,1888.52,1888.82,1892.04,1894.48,1895.93,1898.51,1896.96,1891.8,1892.07,1890.72,1892.38,1892.37,1891.22,1893.07,1896.9,1898.59,1896.79,1896.21,1898.1,1899.63,1902.7,1904.53,1899.26,1894.9,1894.38,1897.54,1896.89,1882.96,1883.11,1880.49,1873.58,1873.52,1880.8,1881.18,1882.51,1882.97,1886.31,1882.32,1878.69,1877.27,1873.79,1874.35,1874.48,1872.46,1870.79,1869.37,1867.71,1866.85,1864.55,1861.42,1858.28,1856.18,1864.1,1864.97,1864.22,1864.13,1870.41,1870.26,1870.98,1868.97,1868.25,1867.38,1868.81,1872.42,1875.58,1874.38,1873.22,1870.91,1868.04,1869.76,1873.1,1873.52,1872.86,1875.57,1877.13,1885.66,1878,1880.17,1885.21,1886.95,1888.54,1885.82,1884.86,1885.7,1884.56,1883.31,1886.9,1885.37,1884.98,1884.74,1886.07,1887.36,1887.57,1886.94,1884.81,1883.55,1883.01,1882.15,1881.11,1880.17,1879.66,1879.14,1878.82,1880.8,1883.39,1886.6,1887.37,1890.18,1886.97,1887.43,1886.94,1886.11,1885.53,1883.71,1882.27,1883.12,1882.73,1880.04,1879.29,1878.62,1879.11,1886.05,1886.03,1886.42,1885.83,1886.34,1887.09,1884.65,1882.61,1884.01,1885.01,1885.2,1885.62,1887.11,1886.05,1885.34,1884.53,1883.57,1882.19,1881.19,1882.53,1882.77,1883.24,1882.76,1883.41,1882.39,1882.45,1882.18,1881.51,1880.89,1880.4,1877.62,1878.5,1877.29,1877.35,1876.97,1878.55,1880.24,1881.02,1882.05,1879.8,1879.3,1879.7,1880.85,1883.32,1882.97,1883.18,1884.72,1884.57,1884.18,1884.18,1878.59,1879.44,1878.74,1879.21,1879.47,1879.45,1878.16,1875.94,1870.69,1869.94,1866.36,1869.45,1872.07,1877.18,1873.47,1871.91,1871.7,1872.02,1873.45,1874.14,1872.97,1873.33,1872.88,1871.65,1869.73,1868.94,1868.43,1867.83,1865.74,1868.14,1867.63,1865.72,1868.63,1868.34,1867.84,1865.4,1865.32,1874.33,1872.18,1870.17,1872.25,1873.24,1873.63,1871.28,1869.52,1865.83,1870.46,1869.7,1870.42,1874.24,1876.77,1879.14,1878.52,1873.11,1874.83,1874,1871.36,1871.66,1869.33,1867.99,1868.83,1869.82,1870.42,1868.87,1865.08,1862.52,1861.6,1860.89,1858.83,1858.76,1858.01,1858.43,1859.78,1859.57,1859,1858.48,1860.31,1858.81,1859.39,1858.7,1859.66,1861.48,1865.77,1873.84,1867.51,1876.19,1871.03,1871.17,1880.53,1877.96,1879.52,1877.73,1874.75,1867.81,1869.81,1864.42,1864.62,1862.43,1863.33,1862.51,1860.95,1860.5,1862.02,1864.02,1863.9,1864.29,1862.71,1863.01,1862.73,1862.8,1860.77,1859.48,1857.88,1857.52,1858.33,1860.24,1858.48,1858.48,1858.1,1857.14,1856.54,1859.1,1863.23,1862.36,1863.62,1861.68,1862.77,1862.67,1865.1,1870,1867.61,1869.88,1873.08,1870.26,1868.2,1866.12,1866.68,1866.43,1868.05,1869.22,1866.16,1861.38,1863.44,1863.49,1867.97,1867.51,1867.64,1867.24,1867.89,1868.12,1868.99,1867.56,1865.82,1863.46,1862.47,1862.46,1862.3,1860.35,1858.37,1859.02,1858.07,1856.68,1854.5,1853.69,1853.37,1851.74,1853.76,1852.28,1851.59,1854.21,1853.04,1852.29,1850.84,1850.3,1849.91,1849.52,1849.14,1848.77,1847.44,1849.19,1848.88,1847.26,1844.08,1846.85,1848.65,1849.14,1848.57,1846.15,1841.74,1841.32,1844.64,1844.54,1841.62,1843.62,1845.34,1845.68,1850.77,1855.52,1854.27,1850.89,1851.81,1852.42,1850.62,1850.76,1847.65,1844.65,1846,1845.82,1844.08,1842.71,1842.59,1842.57,1840.07,1840.42,1841.38,1838.97,1836.68,1836.9,1836.1,1834.6,1831.82,1833.21,1834.97,1838.32,1835.26,1832.63,1834.63,1834.23,1833.58,1829.81,1827.98,1825.18,1828.49,1830.94,1827.8,1828.45,1824.68,1822.4,1826.27,1824.18,1826.06,1823.28,1819.92,1815.82,1816.53,1810.39,1812.3,1807.32,1810.97,1809.12,1810.04,1812.38,1812.66,1809.43,1804.44,1804.27,1801.83,1800.74,1801.96,1802.07,1803.37,1804.14,1805.7,1810.45,1810.24,1810.33,1809.26,1809.08,1808.59,1809.45,1808.56,1809.26,1814.96,1814.77,1824.38,1828.94,1826.26,1829.3,1828.99,1825.93,1827.86,1825.8,1826.19,1822.74,1821.18,1812.08,1817.98,1822.08,1812.65,1817.82,1820.3,1823.52,1824.92,1822.99,1823.2,1821.72,1819.04,1820.39,1821.76,1820.87,1818.74,1817.34,1818.59,1818.1,1818.21,1821.87,1821.17,1819.09,1818.97,1817.66,1818.33,1817.7,1817.96,1818.52,1818.66,1818.62,1817.88,1821.39,1824.95,1824.19,1821.31,1822.78,1826.12,1828.1,1827.67,1826.98,1826.61,1828.03,1829.59,1827.33,1828.79,1829.43,1830.25,1826.91,1831.55,1831.55,1838.36,1838.1,1839.08,1842.32,1841.66,1842.29,1841.57,1840.62,1841.11,1839.98,1839.39,1838.67,1838.08,1839.57,1840.9,1840.85,1843.78,1843.09,1842.38,1842.04,1841.6,1842.51,1842.2,1844.71,1846.08,1845.65,1843.09,1841.61,1840.42,1839.08,1841.27,1839.77,1838.82,1842.88,1841.3,1840.75,1840.16,1839.38,1841.28,1840.04,1839.62,1839.46,1837.64,1836.68,1841.9,1830.4,1839.68,1838.9,1820.79,1820.41,1815.86,1811.08,1810.17,1810.27,1816.03,1819.79,1820.35,1820.16,1812.72,1810.2,1809.86,1808.98,1809.73,1810.94,1810.77,1810.56,1809.88,1808.7,1808.56,1806.24,1804.5,1803.31,1802.6,1800.87,1799.22,1798.57,1797.98,1798.47,1800.43,1802.88,1800.48,1799.92,1799.59,1800.95,1800.01,1799.51,1799.55,1796.75,1794.99,1790.27,1793.82,1798.37,1793.65,1790.16,1793.66,1790.53,1799.04,1796.88,1796.28,1795.99,1797.57,1798.39,1797.49,1795.77,1793.61,1791.32,1788.88,1787.09,1785.02,1781.92,1783.32,1784.82,1785.81,1787.66,1788.68,1789.16,1795.02,1794.03,1793.83,1793.65,1794.06,1792.58,1792.6,1791.82,1793.05,1789.67,1789.35,1789,1792.1,1790.38,1787.39,1787.3,1786.69,1787.54,1787.77,1790.56,1793.62,1793.72,1792.22,1791.44,1792.67,1790.35,1793.05,1793.05,1789.69,1790.42,1793.38,1794.49,1797.17,1795.58,1794.53,1793.27,1791.38,1791.76,1792.39,1791.09,1790.81,1792.58,1794.99,1797.54,1799.96,1798.11,1797.97,1799.78,1799.93,1801.63,1802.31,1801.12,1802.13,1801.16,1801.26,1801.01,1798.72,1798.05,1798.86,1797.7,1796.99,1797.17,1795.57,1797.17,1796.86,1798.66,1797.81,1797.86,1802.24,1800.43,1801.35,1804.12,1803.86,1799.33,1803.71,1793.15,1790.18,1793.9,1792.5,1791.4,1789.36,1789.95,1790.33,1792.55,1792.82,1792.83,1793.34,1793.77,1793.43,1793.03,1792.43,1792.31,1792.46,1794.85,1794.31,1796.21,1797.26,1798.35,1797.54,1795.54,1795.49,1796.19,1796.99,1796.52,1794.93,1794.39,1796.09,1797.55,1796.72,1800.43,1799.35,1799.58,1798.17,1797.68,1797.99,1795.93,1797.95,1801.03,1800.9,1800.49,1799.52,1795.35,1797.96,1798.61,1810.33,1808.84,1804.44,1805.43,1807.25,1805.33,1804.9,1804.45,1803.17,1803.95,1803.95,1807.59,1807.67,1806.15,1805.21,1804.19,1804.24,1803.26,1802.77,1803.65,1803.15,1802.4,1802.24,1802.63,1802.27,1803.22,1803.19,1802.87,1801.02,1803.46,1802.42,1802.74,1802.76,1803.1,1805.08,1806.21,1805.5,1804.96,1804.34,1803.87,1800.23,1802.32,1797.9,1795.02,1794.29,1788.96,1790.25,1804.24,1806.6,1808.43,1809.07,1806.34,1804.44,1797.77,1797.21,1796.91,1792.99,1794.41,1780.76,1781.77,1781.39,1777.9,1777.92,1779.16,1787.02,1789.83,1792.29,1792.64,1791.89,1795.48,1792.67,1789.86,1794.35,1794.18,1794.58,1794.24,1791.3,1792.83,1796.86,1798.26,1800.86,1800.57,1800.03,1798.28,1795.89,1794.64,1793.28,1795.28,1797.06,1796.29,1795.48,1795.35,1795.21,1796.67,1799.28,1803.87,1806.29,1806.04,1799.31,1808.25,1806.28,1800.85,1804.62,1811.21,1805.61,1806.57,1808.14,1807.33,1806.03,1806.54,1805.78,1806.47,1803.97,1803.81,1805.04,1804.64,1804.74,1803.98,1804.32,1804.27,1803.82,1804.27,1803.14,1803.79,1804.72,1805.96,1805.78,1804.42,1804.42,1804.77,1804.18,1805.95,1807.11,1806.35,1805.55,1806.19,1805.49,1805.39,1806.34,1805.46,1805.47,1804.52,1805.63,1806.07,1808.43,1806.98,1807.94,1807.94,1806.44,1805.58,1797.41,1798.11,1802.55,1801.1,1800.8,1801.28,1803.57,1804.68,1808.38,1806.83,1806.09,1804,1802.71,1800.99,1798.52,1796.11,1796.48,1796.67,1796.25,1794.86,1794.4,1794.29,1793.41,1792.46,1792.51,1791.4,1790.71,1790.11,1789.56,1788.72,1790.06,1795.27,1796.14,1793.68,1797.03,1800.48,1800.68,1800.11,1802.29,1804.78,1804.72,1806.47,1807.64,1807.46,1805.61,1805.36,1805.61,1804.84,1806.13,1806.02,1806.2,1836.95,1806.2,1822.72,1829.09,1825.74,1825.94,1828.25,1832.11,1836.04,1832.86,1832.97,1834.1,1833.34,1834.85,1835.19,1835.61,1835.74,1834.62,1834.17,1834.92,1834.73,1835.47,1834.82,1834.45,1834.55,1834.5,1835.31,1834.71,1835.42,1835.2,1834.43,1834.54,1834.81,1834.5,1834.21,1834.63,1834.11,1834.53,1833.86,1833.33,1832.61,1832.46,1832.18,1832.22,1833,1831.75,1832.16,1832.15,1825.9,1827.2,1832.18,1830.47,1839.29,1830.47,1834.9,1833.43,1827.08,1831.75,1831.41,1831.8,1832.73,1832.99,1831.03,1830.65,1830.08,1827.5,1826.27,1826.51,1825.83,1827.61,1827.33,1826.92,1826.88,1828.13,1829.37,1828.84,1828.63,1827.94,1829.31,1827.55,1827.41,1826.41,1826.1,1824.54,1824.96,1825.3,1827.16,1827.62,1827.2,1827.65,1826.85,1827.8,1826.29,1826.06,1827.11,1826.14,1826.09,1824.64,1823.41,1798.56,1815.22,1824.21,1824.53,1829.39,1829.45,1829.55,1824.53,1823.46,1827.73,1829.16,1834.87,1835.74,1832.84,1829.97,1828.83,1827.77,1828.3,1831.64,1832.33,1831.95,1838.7,1842.48,1842.9,1847.37,1849.51,1850.26,1850.39,1851.45,1851.13,1852.19,1855.32,1855.5,1855.57,1856.81,1856.31,1855.84,1856.03,1857.02,1857.72,1858.28,1859.17,1857.78,1857.14,1857.48,1857.08,1856.33,1856.36,1857.36,1857.14,1858.07,1858.95,1859.48,1856.18,1855.45,1857.77,1857.91,1875.73,1875.81,1857.91,1882.14,1878.91,1878.26,1876.92,1878.58,1880.14,1876.41,1873.98,1872.57,1870.59,1869.9,1869.08,1869.48,1869.65,1868.86,1868.63,1868.57,1868.74,1868.13,1867.58,1871.46,1871.85,1872.24,1872.32,1872.75,1874.87,1878.14,1878.13,1882.69,1882.49,1886.6,1885.38,1885.47,1883.67,1880.51,1880.46,1879.43,1879.44,1876.48,1874.9,1874.02,1873.22,1872.44,1869.8,1866.86,1863.9,1865.23,1869.04,1871.18,1873.01,1869.04,1873.39,1881.78,1880.44,1885.24,1884.06,1886.15,1893.4,1886.84,1882.48,1882.26,1880.08,1878.25,1879.86,1878.76,1879.19,1878.53,1875.58,1873.16,1872.27,1870.75,1869.76,1867.55,1865.72,1862.77,1865.09,1866.33,1865.69,1865.1,1863.7,1868.18,1871.24,1873.58,1873.81,1871.91,1872.24,1873.19,1874.91,1875.58,1875.7,1875.69,1878.43,1880.78,1882.73,1883.75,1882.15,1879.51,1878.54,1879.17,1878.02,1878.02,1886.15,1879.86,1878.71,1872,1871.74,1867.93,1872.28,1870.34,1869.46,1869.2,1869.88,1869.27,1868.74,1867.21,1867.53,1866.09,1865.61,1866.41,1864.23,1864.19,1863.65,1861.99,1860.8,1859.66,1858.79,1858.45,1861.68,1864.58,1861.5,1861.84,1860.42,1860.93,1861.77,1861.65,1869.43,1868.06,1866.08,1865.87,1864.03,1862.25,1862.58,1863.25,1863.13,1862.47,1861.05,1857.54,1858.34,1864,1857.25,1853.1,1853.79,1861.79,1863.07,1851.13,1857.9,1863.07,1860.42,1864.82,1866.22,1873.91,1867.59,1868.76,1866.94,1865.63,1864.98,1863.14,1860.68,1858.51,1860.92,1865.59,1864.78,1861.49,1861.31,1860.6,1860.4,1859.04,1859.21,1858.56,1859.14,1858.08,1857.36,1856.63,1855.99,1855.75,1858.26,1858.77,1859.73,1859.86,1862.13,1861.87,1860.52,1859.95,1861.1,1864.39,1865.74,1866.23,1865.99,1864.08,1862.57,1863.26,1866.71,1869.41,1863.18,1863.67,1867.8,1871.91,1868.86,1868.64,1867.55,1866.35,1862.67,1862.89,1861.66,1862.63,1864.51,1862.21,1861.41,1861.17,1861.55,1861.84,1862.93,1862.48,1861.67,1860.93,1859.31,1858.64,1859.49,1859.13,1860.08,1859.26,1858.46,1857.6,1857.78,1857.29,1856.74,1856.49,1856.55,1856.97,1854.72,1854.7,1857.7,1859.8,1859.69,1860.81,1860.08,1859.87,1857.74,1857.01,1858.8,1857.57,1856.09,1857.07,1853.42,1852.63,1851.55,1850.85,1854.97,1854.97,1853.87,1854.97,1850.2,1854.33,1857.81,1853.65,1852.45,1850.17,1850.01,1848.84,1849.55,1849.26,1850.97,1854.37,1854.96,1854.65,1858.05,1856.79,1855.31,1858.04,1858.02,1857.42,1857.11,1857.81,1857.47,1857.28,1857.52,1857.57,1858.52,1858.12,1859.18,1862.19,1859.55,1859.09,1860.61,1860.57,1860.25,1860.43,1860.06,1860.63,1860.89,1860.8,1860.42,1859.59,1858.34,1858.51,1857.57,1852.03,1853.75,1854.01,1857.95,1860.01,1860.9,1860.94,1859.96,1860.03,1862.49,1865.45,1863.79,1865.26,1865.04,1865.21,1865.65,1864.27,1864.83,1865.83,1865.57,1866.15,1867.57,1867.63,1868.63,1870.84,1870.14,1867.94,1866.87,1866.48,1866.04,1865.18,1864.99,1864.65,1864.66,1869.34,1868.93,1869.94,1869.44,1870.72,1870.59,1870.01,1868.59,1867.72,1866.71,1866.01,1865.38,1865.44,1865.93,1865.96,1867.37,1867,1868.55,1866.94,1863.44,1863.98,1863.9,1867.22,1867.21,1870.02,1868.33,1869.87,1870.23,1873.6,1871.08,1870.91,1867.9,1866.31,1866.39,1866.53,1868.65,1868.29,1867.32,1866.79,1866.21,1866.69,1866.01,1865.15,1864.54,1864.21,1865.99,1868.02,1871.08,1870.06,1870.06,1870.25,1870.67,1869.63,1869.42,1868.55,1868.3,1867.86,1868.28,1867.91,1867.96,1866.94,1867.55,1867.63,1867.75,1868.11,1865.42,1865.42,1864.95,1864.93,1864.1,1866.23,1870.3,1868.85,1863.32,1866.34,1866.35,1868.12,1867.08,1866.35,1868.06,1866.46,1866.51,1867.87,1867.77,1870.65,1870.16,1868.42,1868.61,1865.48,1864.33,1863.75,1864.26,1864.58,1864.75,1863.31,1863.46,1862.72,1861.33,1860.97,1860.02,1860.48,1860.52,1860.15,1860.74,1859.49,1859.09,1859.28,1858.89,1858.58,1858.21,1858.97,1859.8,1859.65,1859.85,1860.52,1862.16,1863.86,1864.7,1863.98,1864.35,1864.15,1863.67,1863.79,1862.84,1862.75,1859.52,1859.6,1862.13,1862.08,1879.13,1862.08,1869.77,1870.74,1868.67,1868.4,1869.29,1869.25,1865.57,1863.26,1860.3,1858.35,1857.78,1861.86,1862.2,1863.02,1861.34,1860.3,1860.58,1860.79,1860.12,1860.1,1860.06,1860.19,1860.21,1861.1,1861.62,1860.63,1860.16,1859.84,1859.37,1859.76,1860.03,1860.05,1860.5,1858.83,1858.63,1857.17,1857.06,1857.67,1856.88,1855.13,1848.72,1847.72,1848.37,1838.11,1839,1838.39,1839.44,1842.24,1843.5,1841.69,1843.5,1843.79,1845,1842.71,1840.73,1843.21,1842.69,1841.73,1840.95,1838.29,1836.72,1833.91,1837.13,1835.77,1835.4,1835.31,1834.05,1834.37,1833.44,1831.87,1831.11,1830,1830.79,1829.95,1828.39,1826.98,1826.76,1827.82,1827.2,1832.74,1833.42,1834.58,1837.52,1838.12,1838.67,1839.15,1837.85,1836.67,1839.67,1840.57,1840.36,1839.52,1840,1841.18,1843.27,1844.78,1845.06,1844.43,1844.57,1848.12,1848.25,1844.23,1848.25,1849.05,1848.39,1849.62,1848.59,1846.96,1846.35,1845.85,1844.74,1843,1844.57,1844.66,1845.33,1848.51,1850.22,1851.5,1851.06,1849.97,1850.73,1854.98,1855.24,1854.7,1852.92,1852.42,1852.33,1852.04,1851.82,1851.68,1851.38,1850.12,1850.35,1850.65,1850.62,1851.15,1851.82,1852.39,1853.25,1853.34,1853.99,1853.47,1853.51,1853,1850.95,1850.76,1852.47,1852.5,1850.57,1853.7,1853.7,1841.84,1853.7,1847.49,1849.09,1848.97,1849.96,1849.11,1848.28,1847.58,1845.72,1845.01,1845.05,1843.82,1841.89,1842.09,1842.99,1844.19,1843.72,1844.04,1844.53,1845.16,1845.79,1847.28,1845.58,1845.65,1845.12,1844.78,1844.59,1844.75,1844.27,1844.17,1843.55,1843.9,1844.82,1844.59,1844.85,1846.34,1845.02,1844.04,1842.85,1842.34,1844.04,1843.85,1842.07,1843.25,1841.7,1841.86,1839.51,1839.1,1839.09,1841.37,1840.7,1840.13,1840.33,1843.78,1844.66,1841.59,1839.45,1838.61,1837.53,1837.76,1838.86,1838.51,1838.14,1838.09,1837.86,1837.49,1837.24,1837.8,1836.59,1836.41,1836.52,1835.57,1834.79,1834.57,1835.35,1834.56,1834.43,1834.06,1833.98,1833.18,1832.67,1832.87,1833.14,1834.58,1833.74,1834.14,1839.7,1839.87,1839.32,1838.68,1838.84,1838.72,1837.06,1835.28,1835.97,1835,1834.69,1831.5,1827.73,1826.15,1825.54,1828.95,1828.34,1831.39,1828.34,1819.26,1822.27,1821.28,1819.77,1818.33,1816.24,1815.73,1815.6,1816.29,1815.7,1814.28,1810.27,1810.81,1810.04,1809.79,1810.57,1811.28,1812.64,1812.52,1811.95,1811.34,1809.15,1805.46,1804.25,1802.62,1799.2,1801.51,1801.17,1803.23,1806.02,1805.18,1803.99,1805.15,1805.5,1805.15,1803.56,1799.57,1793.82,1794.52,1794.59,1789.99,1792.82,1792.71,1782.66,1790.81,1790.34,1790.41,1788.56,1796.97,1800.54,1789.17,1790.65,1800.54,1794.32,1797.2,1798.29,1793.07,1787.98,1789.49,1788.85,1787.93,1784.88,1783.12,1780.57,1777.96,1774.38,1775.66,1778.78,1778.52,1777.43,1778.31,1781.31,1783.61,1783.56,1782.28,1781.41,1781.4,1781.22,1781.86,1782.45,1781.95,1786.84,1788.61,1794.5,1797.59,1795.97,1794.47,1798.13,1800.67,1799.25,1797.5,1799.33,1797.65,1800.72,1799.47,1799.57,1801.12,1801.7,1797.83,1802.82,1806.63,1806.63,1805.55,1805.93,1797.72,1794.11,1794.5,1793.35,1793.77,1788.9,1784.97,1786.39,1785.89,1785.81,1784.9,1783.61,1784.43,1783.85,1781.11,1785.36,1789.48,1789.14,1790.18,1788.37,1789.12,1788.69,1788.76,1788.91,1789.07,1790.82,1791.07,1790.64,1789.91,1789.02,1788.13,1786.44,1787.34,1787.42,1785.85,1786.7,1785.94,1782.89,1785.75,1784.58,1786.57,1787.1,1786.2,1781.06,1777.84,1778.62,1777.7,1775.96,1783.75,1782.12,1765.01,1772.52,1777.3,1778.34,1779.58,1778.64,1782.99,1783.86,1782.09,1778.54,1777.98,1777.01,1774.41,1774.21,1771.79,1768.32,1768.48,1769.73,1768.3,1766.65,1767.42,1762.56,1763.13,1764.25,1762.2,1761.16,1766.25,1766.35,1765.97,1765.32,1765.34,1764.26,1762.63,1759.86,1758.82,1761.46,1764.17,1770.22,1771.41,1779.67,1781.74,1783.64,1785.19,1789.54,1792.18,1797.93,1796.7,1791.87,1794.48,1791.64,1804.3,1804.24,1804.24,1801.4,1801.56,1796.4,1795.05,1795.09,1796,1796.68,1795.11,1795,1793.43,1790.9,1790.83,1793.02,1793.84,1794.05,1791.98,1791.46,1791.82,1791.32,1790.14,1790.98,1791.16,1792.19,1792.82,1794.77,1796.53,1796.68,1796.14,1793.06,1790.95,1793.4,1793.59,1794.26,1794.18,1794.97,1794.36,1794.5,1793.01,1793.94,1792.69,1793.6,1793.18,1790.93,1789.99,1790.02,1781.26,1782.12,1790.13,1787.45,1779.17,1787.45,1781.79,1779,1777.17,1778.35,1777.88,1780.14,1779.6,1779.44,1778.47,1777.32,1776.46,1772.14,1770.63,1770.91,1771.83,1771.58,1771.43,1769.73,1767.53,1766.16,1765.34,1760.64,1759.84,1756.2,1754.23,1753.77,1754.38,1753.9,1753.88,1756.18,1754.48,1751.53,1750.05,1748.17,1746.98,1746.41,1746.97,1754.12,1756.54,1753.36,1751.09,1750.79,1746.18,1740.01,1738.19,1737.26,1737.03,1734.48,1741.81,1743.51,1730.85,1743.51,1742.88,1738.36,1742.83,1746.12,1745.94,1748.93,1749.52,1746.09,1744.41,1744.38,1749.19,1748.28,1746.53,1746.19,1745.93,1744.06,1742.58,1742.23,1738.33,1739.53,1738.02,1737.92,1735.95,1735.88,1734.31,1734,1734.63,1734.22,1734.56,1736.68,1737.99,1737.71,1736.24,1735.39,1734.49,1734.31,1735.24,1730.34,1726.72,1731.97,1730.73,1728.14,1727.71,1729.36,1727.45,1725.01,1723.01,1722.66,1730.17,1730.56,1721.48,1730.56,1735.69,1731.64,1730.79,1732.84,1726.96,1719.26,1717.74,1714.69,1712.98,1703.19,1705.01,1701.5,1703.84,1702.46,1698.89,1696.4,1700.39,1705.6,1703.16,1702.45,1701.82,1700.54,1703.65,1698.79,1694.96,1692.25,1692.9,1693.42,1685.61,1686.55,1686.15,1680.48,1679.96,1682.89,1694.36,1692.29,1688.56,1688.21,1686.66,1691.54,1698.26,1688.08,1689.54,1680.17,1681.04,1666.68,1664.64,1664.33,1671.17,1668.53,1654.18,1656.85,1668.53,1675.29,1680.73,1680.42,1673.66,1674.98,1672.37,1667.62,1663.27,1665.34,1671.8,1675.32,1673.85,1674.1,1681.46,1677.68,1674.38,1669.64,1671.38,1669.65,1667.13,1666.15,1663.7,1660.68,1659.31,1660.88,1659.9,1660.7,1660.09,1670.22,1673.71,1683.68,1679.73,1680.52,1682.51,1688.85,1700.77,1695.21,1694.6,1692.99,1692.14,1696.06,1699.85,1697.49,1695.91,1694.45,1697.3,1694.04,1699.33,1699.38,1699.38,1701.98,1692.67,1699.38,1685.48,1685.05,1682.45,1682.8,1686.56,1685.62,1686.13,1682.22,1680.99,1681.89,1682.38,1680.88,1677.73,1675.72,1675.26,1678.57,1683.05,1684.59,1690.98,1690.29,1690.21,1692.04,1694.43,1695.81,1693.94,1692.59,1693.61,1692.07,1688.44,1689.47,1687.44,1688.31,1689.14,1689.23,1686.97,1686.48,1688.63,1688.84,1688.84,1686.35,1688.62,1689.08,1688.56,1687.81,1685.88,1678.07,1679.85,1683.46,1686.11,1684.88,1686.11,1692.14,1693.47,1696.99,1696.71,1695.33,1700.6,1698.16,1696.58,1693.14,1691.51,1689.75,1689.99,1689.61,1692.08,1689.74,1689.64,1689.14,1687.94,1685.46,1683.35,1682.78,1681.13,1682.09,1683.11,1682.39,1681.02,1682.53,1681.86,1686.25,1688.24,1686.75,1685.47,1682.69,1683.72,1683.68,1683.41,1683.4,1685.56,1684.51,1686.17,1686.3,1685.59,1683.64,1679.77,1678.81,1667.66,1663.64,1663.15,1669.12,1669.01,1647.94,1649.42,1651.23,1669.01,1657.98,1662.09,1658.78,1663.81,1666.07,1664.54,1662.15,1662.95,1660.82,1658.03,1658.03,1659.91,1660.05,1664.74,1665.97,1666.09,1664.51,1663.74,1669.96,1669.33,1673.91,1675.53,1674.27,1674.2,1672.02,1671.79,1673.4,1672.83,1674.59,1677.2,1682.03,1684.47,1681.95,1679.65,1679.96,1677.89,1678.1,1681.26,1678.95,1679.67,1679.54,1677.17,1678.98,1677.24,1676.21,1673.25,1678.2,1678.44,1680.62,1680.62,1682.93,1682.92,1680.62,1679.65,1679.86,1684.88,1683.71,1681.06,1681.58,1681.43,1680.52,1680.08,1675.31,1677.98,1678.3,1681.82,1681.84,1683.57,1683.03,1682.8,1683.33,1682.99,1681.59,1682.67,1681.62,1679.42,1680.62,1680.05,1680.9,1684.18,1683.68,1693.3,1702.92,1697.1,1694.89,1696.1,1695.28,1692.49,1693.33,1693.98,1690.52,1697.36,1695.93,1698.33,1695.67,1695.05,1699.03,1697.8,1693.22,1703.14,1704.68,1704.68,1706.41,1704.68,1705.7,1705.64,1709.77,1712.21,1719.53,1718.96,1718.95,1719.54,1719.43,1719.4,1720.01,1720.09,1719.35,1718.9,1718.86,1721.74,1725.51,1727.1,1729.15,1727.35,1726.54,1727.09,1729.83,1732.09,1732.97,1733.7,1735.48,1735.58,1737.19,1740.28,1740.57,1738.53,1738.98,1739.1,1739.63,1737.76,1733.63,1733.8,1737.59,1739.48,1739.68,1740.87,1741.93,1743.9,1744.01,1741.14,1743.87,1745.09,1744.66,1744.66,1765.5,1768.22,1744.66,1757.18,1751.05,1753.53,1749.31,1754.72,1753.54,1752.24,1748.85,1747.77,1749.27,1758.13,1759.47,1754.62,1755.45,1755.15,1755.8,1755.03,1754.51,1753.19,1751.63,1750.02,1749.21,1749.93,1749.75,1750.13,1750.18,1749.18,1748.48,1745.31,1745.63,1747.28,1748.1,1746.35,1746.34,1743.93,1743.68,1744.96,1744.18,1743.06,1740.24,1735.93,1738.15,1741.4,1738.85,1738.13,1712.12,1722.79,1724.92,1735.36,1735.78,1736.06,1745.06,1744.47,1745.43,1740.2,1737.26,1742.1,1744.58,1750.36,1751.88,1749.25,1749.37,1748.53,1747.7,1748.11,1748.59,1749.22,1749.55,1752.66,1752.7,1752.6,1751.31,1751.47,1752.25,1753.37,1754.6,1754.5,1755,1755.95,1754.8,1756.45,1758.43,1758.94,1760.64,1761.53,1764.63,1763.6,1762.34,1764.07,1764.12,1765.58,1766.01,1766.57,1763.14,1759.26,1761.69,1762.06,1758.46,1760.69,1760.79,1762.84,1762.84,1768.41,1769.08,1762.84,1762.74,1760.02,1769.71,1764.83,1763.44,1761.52,1763.42,1766.12,1770.84,1771.38,1772.68,1773.17,1773.89,1774.81,1775.99,1773.61,1774.29,1773.49,1772.59,1770.88,1768.97,1769.74,1770.98,1769.79,1770.87,1770.37,1769.04,1767.94,1767.81,1768.49,1767.8,1769.16,1771.7,1772.95,1772.07,1770.89,1771.36,1771.55,1770.66,1771.91,1772.65,1773.85,1771.81,1772.12,1772.8,1762.42,1772.13,1774.04,1777.23,1777.23,1785.34,1786.97,1777.23,1789.83,1786.53,1788.47,1786.08,1783.37,1783.31,1781.95,1782.86,1785.26,1784.76,1785.55,1786.81,1786.61,1786.56,1788.01,1787.44,1786.66,1786.19,1786.34,1786.05,1786.24,1785.86,1787.16,1786.28,1785.48,1785.4,1786.27,1785.54,1783.74,1783.83,1782.96,1781.68,1779.9,1780.53,1781.33,1781.69,1780.29,1778.54,1778.61,1778.47,1775.12,1775.44,1777.25,1774.53,1774.46,1769.44,1770.6,1771.7,1776.48,1776.46,1787.2,1776.46,1781.8,1780.82,1778.45,1774.39,1776.16,1776.67,1776.23,1775.41,1776.28,1779.4,1779.74,1783.16,1783.22,1780.99,1778.66,1780.03,1778.82,1777.44,1775.35,1775,1774.15,1773.32,1772.46,1772.01,1772.44,1772.39,1772.02,1770.37,1768.88,1772.92,1774.25,1774.68,1771.78,1771.59,1770.87,1771.26,1771.78,1771.56,1770.92,1770.61,1770.65,1768.19,1765.83,1765.79,1769.87,1762.96,1765.29,1763.04,1764.78,1764.78,1763.39,1757.76,1764.78,1758.98,1757.61,1760.99,1761.78,1759.57,1761.88,1758.57,1759.17,1758.81,1761.77,1764.13,1769.61,1772.02,1771.08,1773,1772.88,1772.12,1772.19,1772.96,1772.52,1771.68,1770.56,1769.64,1768.29,1768.03,1768.09,1767.71,1766.78,1767.99,1767.72,1768.82,1771.04,1772.55,1772.98,1772.99,1772.55,1771.12,1772.42,1772.66,1771.07,1771.94,1770.98,1769.47,1770.19,1768.29,1764.34,1766.91,1768.02,1768.23,1768.06,1760.86,1769.13,1768.06,1772.75,1765.74,1760.32,1762.79,1761.33,1764.23,1767.17,1774.55,1771.32,1774.21,1772.27,1770.94,1771.4,1771.44,1770.35,1769.78,1770.52,1772.9,1772.05,1773.2,1773.42,1775.99,1778.86,1778.69,1780.6,1779.8,1780.4,1779.82,1780.07,1778.33,1778.66,1777.86,1778.99,1779.05,1780.01,1779.77,1780.08,1781.51,1783.86,1783.59,1782.17,1782.21,1780.65,1778.8,1778.63,1775.55,1774.77,1776.84,1776.48,1776.77,1779.97,1776.77,1788.06,1784.3,1780.43,1775.6,1772.89,1775.04,1776.55,1777.22,1775.71,1778.22,1779.48,1778.94,1777.7,1777.43,1776.16,1780.02,1779.3,1779.1,1780.12,1780.41,1779.54,1778.52,1779.35,1779.01,1779.39,1779.6,1779.58,1778.95,1776,1777.4,1777.85,1778.27,1779.43,1782.63,1780.77,1779.55,1778.02,1777.28,1776.03,1775.27,1775.59,1775.81,1775.98,1775.34,1774.34,1766.5,1773.41,1773.41,1777.2,1776.49,1776.19,1773.41,1775.42,1774.77,1775.49,1773.14,1771.97,1778.23,1785.36,1785.95,1790.45,1790.39,1789.45,1788.15,1787.75,1786.18,1786.81,1789.43,1788.47,1786.39,1786.46,1787.6,1788.31,1787.69,1787.57,1788.49,1789.69,1793.78,1792.77,1791.69,1788.93,1788.18,1788.46,1791.17,1792.13,1791.65,1792.52,1791.67,1788.94,1788.76,1791.31,1790.66,1789.43,1788.75,1787.96,1790.29,1791.7,1789.31,1789.21,1790.38,1793.18,1793.18,1796.27,1793.81,1795.99,1798.36,1795,1792.8,1790.71,1792.98,1795.1,1794.16,1793.23,1793.12,1793.77,1792.66,1790.83,1792.35,1792.27,1791.86,1792.65,1792.82,1792.33,1791.89,1792.71,1791.86,1791.6,1794.32,1795.34,1795.1,1795.54,1794.89,1792.49,1792.95,1792.56,1789.92,1787.51,1787.91,1788.9,1785.18,1781.58,1781.76,1783.83,1781.71,1776.31,1772.95,1772.66,1771.88,1767.99,1762.96,1764.46,1765.06,1766.27,1765.63,1763.92,1764.09,1765.63,1757.28,1756.01,1756.85,1758.22,1758.59,1756.02,1750.29,1743.92,1758.54,1756.63,1752.34,1751.71,1751.91,1753.61,1752.35,1751.99,1754.19,1753.36,1753.77,1752.97,1750.39,1749.76,1749.53,1747.68,1744.95,1743.35,1744.75,1744.28,1741.58,1744.37,1742.61,1742.39,1742.79,1741.62,1742.35,1740.34,1738.75,1734.83,1733.56,1738.62,1732.82,1730.13,1730.79,1726.92,1727.41,1722.81,1728.4,1728.27,1729.29,1729.08,1726.39,1729.08,1733.09,1733.28,1726.22,1722.2,1728.89,1730.2,1731,1731.31,1732.07,1730.57,1730.75,1729.07,1726,1726.29,1726.6,1725.3,1721.93,1721.27,1718.64,1719.27,1718.05,1716.85,1719.77,1721.08,1719.29,1719.26,1719.27,1718.79,1719.89,1719.99,1719.52,1719.95,1720.52,1726.3,1725.28,1725.09,1727.13,1729.87,1728.47,1726.14,1726.62,1728.57,1725.03,1723.37,1725.22,1721.79,1722.93,1723.42,1727.46,1727.46,1724.75,1727.46,1732.44,1734.73,1731.25,1731.98,1734.08,1738.17,1743.86,1741.48,1742.4,1747.52,1748.36,1749.22,1750.32,1750.79,1746.02,1745.02,1741.84,1738.67,1739.48,1741.68,1740.6,1740.05,1738.82,1737.51,1735.71,1735.54,1734.72,1734.47,1731.05,1731.48,1732.23,1731.59,1732.48,1733.01,1732.71,1732.58,1732.05,1730.14,1728.67,1728.29,1726.23,1725.14,1727.21,1728.54,1726.06,1729.24,1728.99,1732.02,1732.02,1734.92,1732.19,1732.02,1733.77,1733.51,1730.16,1729.41,1727.72,1726.67,1728.84,1729.56,1728.61,1728.21,1728.15,1729.23,1729.95,1729.99,1727.98,1727.82,1728.79,1726.42,1725.77,1725.02,1723.58,1721.7,1721.89,1721.65,1723.41,1722.87,1724.13,1723.28,1722.91,1722.29,1723.5,1724.12,1725.98,1724.37,1724.16,1722.44,1723.13,1722.19,1720.84,1719.76,1721.83,1722.22,1722.74,1724.1,1724.79,1724.35,1724.06,1723.97,1726.69,1726.69,1730.18,1730.06,1726.69,1739.43,1735.26,1736.8,1739.75,1741.06,1742.12,1739.45,1740.88,1737.86,1737.13,1738.16,1737.32,1735.41,1734.47,1734.53,1735.2,1736.43,1735.06,1734.81,1734.58,1736.09,1735.58,1734.98,1733.36,1732.57,1732.35,1731.81,1731.27,1730.31,1730.84,1731.28,1732.4,1730.66,1732.41,1732.51,1731.5,1733.4,1733.6,1734.66,1738.01,1739.45,1738.05,1738.62,1736.21,1735.16,1729.61,1732.68,1732.65,1734.24,1734.24,1735.78,1734.24,1731.73,1732.11,1726.23,1727.67,1728.68,1730.23,1729.42,1729.15,1729.44,1729.09,1730.55,1730.36,1731.07,1730.25,1730.71,1730.87,1731.4,1732.34,1734.69,1734.17,1734.88,1735.3,1736.11,1737.7,1737.9,1738.49,1739.13,1738.59,1741.44,1746.14,1745.55,1743.76,1751.81,1754.65,1757.05,1753.6,1757.4,1760.2,1762.95,1763.86,1764.33,1761.39,1761.81,1763.64,1767.15,1764.76,1765.16,1763.38,1768.31,1768.12,1779.72,1786.14,1768.12,1791.93,1785.26,1781.68,1780.47,1783.76,1786.49,1784.23,1784.69,1786.83,1789.45,1791.82,1792.43,1793.86,1794.51,1793.75,1793.39,1792.24,1790.43,1790.04,1788.21,1786.62,1784.61,1785.68,1787.46,1789.36,1788.61,1788.75,1788.13,1789.1,1789.94,1789.89,1790.02,1789.02,1789.82,1788.86,1787.31,1786.67,1788,1786.46,1785.94,1787.58,1789.39,1789.85,1786.91,1786.11,1781.98,1786.21,1786.09,1788.94,1788.78,1792.26,1793.05,1792.74,1788.78,1790.37,1798.9,1802.87,1799.85,1801.21,1801.5,1801.17,1796.9,1795.92,1796.93,1798.34,1800.22,1801.44,1804.75,1804.71,1807.56,1806.23,1807.05,1805.86,1807.27,1809.95,1807.31,1806.77,1806.84,1807.08,1806.64,1807.11,1805.45,1802.98,1802,1799.32,1795.15,1795.38,1798.66,1799.61,1800.39,1797.52,1795.14,1794.85,1788.89,1790.55,1793.87,1795.22,1791.41,1794.36,1790.14,1789.39,1789.24,1791.48,1791.41,1790.88,1791.41,1796.01,1793.98,1790.77,1797.16,1803.01,1800.47,1801.89,1800.67,1799.61,1801.12,1799.69,1799.13,1800.2,1797.69,1794.95,1797.32,1795.5,1794.93,1793.51,1792.22,1793.27,1793.01,1793.17,1794.93,1795.1,1794.5,1795.63,1795.6,1794.22,1794.81,1795.22,1796.73,1797.5,1797.18,1799.1,1800.01,1802.73,1806.43,1809.01,1809.36,1807.9,1806.53,1806.28,1808.83,1810.73,1810.27,1811.41,1818.06,1813.76,1821.32,1824.41,1825.94,1825.69,1821.32,1827.71,1831.26,1829.26,1838.25,1835.95,1834.48,1829.73,1824.73,1826.4,1825.54,1823.64,1822.37,1822.52,1823.05,1820.91,1818.95,1819.42,1820.66,1821.99,1823.59,1824.1,1823.07,1821.99,1822.83,1821.69,1823.22,1822.66,1821.82,1821.39,1818.87,1820.86,1819.2,1815.51,1819.41,1820.64,1821.56,1822.53,1821.95,1822.03,1821.97,1822.02,1822.5,1820.65,1823.49,1825.62,1824.21,1828.45,1830.46,1831.78,1831.56,1830.53,1831.56,1824.69,1830.28,1830.1,1830.73,1827.18,1823.76,1821.88,1822.67,1823.93,1825.76,1828.49,1826.16,1823.73,1825.04,1824.48,1825.5,1824.54,1824.67,1827.98,1828.44,1830.89,1830.63,1830.61,1829.72,1828.96,1829.08,1828.05,1827.76,1825.71,1827.9,1828.44,1831.52,1835.35,1836.27,1836.1,1836.35,1836.4,1836.71,1836.17,1837.54,1836.9,1837.46,1837.18,1832.03,1832.77,1826.12,1828.7,1829.01,1833.13,1832.12,1807.2,1825.91,1832.12,1815.5,1819.48,1819.28,1814.99,1813.59,1811.23,1809.1,1811.24,1810.56,1810.66,1806.86,1804.14,1803.19,1803.54,1804.46,1805.05,1804.06,1810.06,1813.96,1816,1817.4,1821.75,1819.47,1818.18,1821.42,1820.62,1821.61,1820.94,1822.22,1823.67,1823.33,1822.36,1818.27,1819.4,1820.49,1818.57,1818.5,1820.93,1824.18,1825.42,1824.77,1823.25,1822.04,1821.73,1826.96,1826.97,1826.41,1827.05,1828.42,1827.72,1827.12,1827.72,1844.46,1843.07,1854.82,1860.7,1858.66,1859.62,1857.41,1851.44,1850.53,1849.85,1849.52,1850.38,1851.08,1850.62,1849.69,1849.58,1849.21,1848.08,1847.69,1847.11,1848.06,1848.08,1846.39,1846.79,1847.24,1847.98,1847.54,1847.02,1847.48,1849.29,1848.59,1846.78,1845.91,1844.8,1845.47,1845.39,1846.37,1848.35,1849.81,1849.67,1849.53,1849.41,1852.16,1857.4,1858.05,1853.68,1851.56,1853.42,1853.52,1853.08,1855.14,1853.08,1868.43,1869.21,1865.91,1863.73,1865.18,1867.27,1865.65,1862.67,1862.84,1865.69,1866.66,1866.19,1865.27,1864.1,1862.03,1860.99,1858.38,1854.47,1854.48,1851.77,1847.74,1850.73,1848.83,1846.7,1845.15,1843.79,1839.16,1839,1841.02,1847.3,1851.05,1851.01,1851.66,1849.57,1850.61,1850.59,1850.23,1849.41,1847.27,1843.1,1840.76,1839.77,1833.66,1832.14,1832.79,1831.93,1822.59,1830.69,1821.64,1816.45,1816.39,1820.75,1827.17,1821.92,1818.69,1815.4,1820.64,1824.57,1821.96,1821.01,1821.25,1818.44,1820.48,1818.69,1818.49,1818.89,1817.92,1819.85,1820.21,1820.28,1822.66,1822.94,1821.72,1820.13,1818.79,1818.09,1817.4,1815.77,1817,1816.16,1819.37,1822.04,1822.27,1820.28,1824.22,1823.37,1828.27,1829.91,1830,1828.43,1826.56,1828.5,1828.87,1830.03,1827.42,1825.85,1828.71,1829.86,1828.29,1828.31,1830.44,1830.44,1835,1830.44,1836.83,1836.69,1836.41,1838.92,1844.16,1844.51,1847.4,1842.43,1844.68,1844.52,1844.62,1843.42,1843.28,1840.75,1840.8,1839.19,1839.07,1837.89,1837.62,1838.14,1837.76,1838.42,1838.93,1835.91,1832.25,1836,1835.59,1834.52,1835.29,1834.01,1835.01,1834.5,1834.11,1832.8,1834.12,1834.37,1834.15,1832.67,1833.44,1832.93,1830.58,1827.56,1826.1,1826.2,1825.68,1814.42,1824.06,1827.38,1827.12,1827.12,1830.48,1827.95,1827.53,1827.12,1818.47,1821.25,1824.4,1823.73,1824.63,1825.03,1821.41,1823.64,1823.53,1823.62,1822.45,1822.15,1822.42,1821.67,1821.45,1820.57,1818.84,1816.04,1813.79,1814.22,1814.95,1814.73,1815.06,1816.68,1818.53,1819.72,1826.31,1825.51,1827.03,1823.63,1823.34,1823.19,1823.14,1825.12,1826.89,1828.05,1828.44,1829.47,1828.06,1829.22,1832.96,1832.17,1833.19,1832.67,1832.24,1830.4,1830.74,1828.6,1829.23,1829.23,1820.54,1820.57,1820.67,1820.11,1821.04,1820.69,1819.77,1820.86,1822.28,1820.86,1819.51,1816.42,1815.95,1814.77,1812.28,1811.95,1812.23,1811.78,1814.32,1817.3,1815.71,1814.6,1813.07,1814.06,1813.89,1813.66,1814.16,1814.15,1813.87,1811.85,1813.28,1813.3,1810.87,1811.57,1811.11,1812.72,1814.18,1814.44,1813.38,1812.25,1812.88,1814.35,1815.13,1813.79,1811.35,1809.13,1804.71,1805.86,1802.31,1796.65,1794.87,1794.22,1797.18,1795.21,1786.52,1787.72,1795.21,1793.5,1793.97,1796.41,1797.22,1793.93,1792.45,1787.59,1789.08,1786.53,1787.04,1782.87,1782.61,1781.59,1788.08,1790.41,1789.87,1788.99,1792.53,1796.96,1794.93,1794.05,1792.4,1791.73,1793.27,1795.05,1792.45,1790.8,1790.37,1796.18,1795.15,1792.82,1793,1795.59,1793.83,1790.9,1787.74,1783.82,1778.53,1782,1783.16,1786.3,1781.02,1780.08,1781.17,1786.68,1783.37,1783.71,1783.73,1785.98,1788.23,1789.91,1791.2,1788.23,1798.91,1801.39,1797.46,1800.04,1798.8,1798.49,1798.77,1797.55,1799.09,1798.62,1801.91,1803.81,1805.15,1805.7,1804.95,1804.96,1804.81,1804.71,1802.78,1800.28,1800.02,1800.42,1801.57,1801.34,1801.29,1801.64,1802.34,1802.01,1801.66,1802.8,1802.78,1804.4,1805.56,1805.2,1804.59,1804.51,1804.23,1806.84,1807.64,1807.68,1808.15,1809.17,1810.32,1811.44,1810.56,1813.94,1799.56,1810.56,1810.67,1811.15],
      "h": [1727.17,1728.58,1733.79,1740.18,1742.87,1742.54,1736.92,1736.05,1735.79,1734.99,1739.5,1742.23,1741.39,1738.83,1735.27,1733.97,1732.79,1732.89,1732.76,1731.13,1731,1730.87,1730.16,1728.97,1727.67,1723.95,1719.19,1713.14,1710.69,1716.3,1716.71,1716.55,1718.2,1717.72,1721.62,1724.63,1726.76,1727.15,1722.18,1722.29,1725.52,1725.23,1725.88,1725.96,1729.43,1731.27,1713.13,1727.55,1713.83,1705.85,1705.95,1703.55,1702.03,1700.4,1702.89,1704.45,1705.2,1703.46,1701.4,1700.57,1697.65,1696.67,1697.17,1697.86,1700.31,1700.84,1699.94,1700.3,1703.3,1704.1,1703.74,1700.22,1698.66,1697.66,1698.25,1698.48,1697.08,1693.38,1695.25,1694.2,1692.2,1691.17,1692.7,1693.55,1690.82,1689.88,1687.45,1688.19,1693.27,1697.66,1708,1709.47,1708.05,1706.05,1677.09,1699.13,1699.13,1690.51,1686.62,1684.64,1684.44,1679.98,1680.88,1681.56,1682.27,1682.51,1682.07,1678.42,1676.89,1676.81,1678.37,1678.95,1679.82,1680.3,1681.24,1681.93,1680.67,1679.34,1678.43,1677.67,1677.56,1676.68,1676.72,1676,1675.45,1672.87,1671.67,1670.35,1666.36,1669.05,1672.22,1672.45,1671.8,1669.4,1667.85,1667.9,1664.67,1664.5,1661.21,1663.64,1660.92,1658.25,1642.65,1655.36,1647.81,1635.47,1627.52,1628.11,1627.43,1619.63,1616.72,1616.49,1612.17,1605.37,1610.42,1612.38,1607,1607.41,1609.12,1615.34,1615.56,1613.9,1610.61,1608.76,1605.73,1602.58,1605.44,1610.39,1615.21,1616.2,1614.98,1613.57,1612.66,1612.09,1610.76,1608.36,1604.71,1603.93,1607.99,1608.36,1604.47,1599.59,1599.36,1599.59,1598.69,1601.36,1601.08,1599.4,1591.03,1596.97,1592.79,1592.92,1626.34,1621.38,1616.36,1618.08,1615.75,1614.93,1614.8,1615.25,1613.19,1612.61,1613.9,1614.56,1619.18,1621.49,1621.33,1620.66,1621.35,1625.58,1629.04,1630.63,1629.12,1627.65,1625.57,1624.11,1623.89,1623.35,1622.94,1622.69,1621.65,1620.01,1621.44,1621.53,1619.75,1615.6,1615.11,1613.99,1613.09,1609.59,1607.84,1609.55,1611.21,1611.86,1610.1,1609.73,1608.56,1608.58,1606.13,1614.77,1643.1,1644.21,1652.48,1653.3,1650.33,1648.53,1645.72,1644.38,1645.42,1645.44,1645.75,1645.86,1646.35,1650.69,1651.68,1652.62,1651.07,1650.64,1648.91,1648.08,1650.32,1649.01,1648.28,1648.31,1646.87,1646.2,1646.14,1645.76,1645.91,1644.85,1647.43,1648.24,1646.77,1647.11,1648.85,1651.36,1652.29,1650.84,1649.98,1648.72,1649.31,1649.07,1646.43,1649.89,1652.81,1655.33,1654.13,1658.77,1661.6,1654.18,1652.4,1649.7,1644.21,1643.19,1643.53,1643.12,1641.54,1637.94,1639.83,1643.83,1648.92,1648.81,1645.09,1646.45,1646.94,1644.51,1644.12,1644.06,1643.67,1643.36,1644.28,1643.3,1642.51,1641.86,1641.23,1640.38,1639.59,1636.1,1636.97,1637.18,1637,1639.14,1639.85,1639.17,1637.55,1641.57,1645.31,1645.63,1645.3,1646.16,1644.65,1645.46,1645.15,1644.59,1641.41,1644.63,1644.63,1644.29,1648.11,1646.18,1642.69,1642.98,1644.01,1644.27,1652.68,1657.87,1656.69,1653.4,1652.9,1652.34,1650.89,1652.46,1651.21,1650.93,1651.74,1650.48,1650,1649.63,1651.54,1652.61,1652.8,1651.96,1653.04,1652.89,1654.71,1652.27,1653.7,1655.58,1657.2,1659.62,1659.18,1660.3,1662.68,1663.45,1663.89,1664.09,1665.55,1668.65,1669.65,1671.07,1672.44,1672.58,1669.84,1673.31,1672.8,1647.01,1644.58,1644.98,1646.92,1646.62,1644.93,1644.12,1643.92,1642.3,1641.37,1641.61,1647.55,1647.45,1652.81,1653.19,1651.26,1652.65,1654,1653.5,1652.78,1651.49,1650.37,1650.17,1649.05,1649.57,1650.21,1650.15,1649.67,1651.65,1651.79,1654.49,1660.4,1657.91,1658.13,1662.57,1665.85,1665.67,1667.64,1671.6,1671.52,1666.93,1668.44,1667.86,1667.34,1665.56,1657.68,1662.54,1673.51,1670.79,1668.09,1668.06,1667.52,1667.69,1667.56,1669.4,1670.81,1670.82,1672.76,1677.25,1676.56,1676.05,1677.51,1677.83,1676.84,1676.88,1676.87,1676.4,1675.54,1674.87,1673.84,1673.98,1674.34,1674.26,1674.14,1673.64,1675.37,1675.17,1674.86,1672.6,1669.85,1670.4,1669.79,1668.92,1668.48,1665.66,1666.89,1669.99,1670.13,1669.45,1668.42,1668.14,1667.15,1670.02,1663.05,1674.49,1713.98,1715.21,1710.97,1710.65,1707.74,1708.88,1709.83,1710.99,1711.37,1712.36,1711.99,1710.22,1710.15,1710.08,1708.45,1707.17,1707.67,1706.14,1705.19,1704.66,1705.49,1705.57,1705.23,1705,1704.76,1704.34,1705.09,1704.9,1704.52,1704.18,1702.87,1701.49,1703.88,1705.08,1705.94,1706.19,1709.19,1712.59,1713,1711.12,1711.03,1711,1707.77,1707.32,1707.78,1707.61,1704.73,1705.74,1706.15,1702.1,1702.88,1698.79,1696.28,1696.11,1696.51,1697.99,1698.02,1698.64,1697.9,1696.29,1696.02,1694.95,1692.98,1693.58,1695.87,1696.95,1697.69,1699.29,1698.98,1698.12,1697.94,1697.33,1696.36,1696.15,1696.27,1694.77,1694.81,1692.37,1693.57,1694.16,1694.32,1693.28,1692.46,1689.3,1689.69,1689.61,1688.28,1686.75,1689.71,1691.99,1692.27,1692.75,1693.96,1694.91,1691.17,1695.13,1706.66,1705.8,1707.21,1711.67,1711.26,1711.66,1713.95,1712.01,1709.31,1709.85,1708.99,1708.57,1708.03,1707.29,1706.42,1704.78,1701.93,1700.28,1698.52,1699.42,1700.98,1700.45,1699.56,1700.81,1701.15,1701.09,1700.4,1699.34,1697.88,1695.62,1694.37,1690.68,1692.38,1690.56,1688.53,1687.7,1687.36,1686.29,1686.65,1686.83,1685.33,1684.31,1682.42,1684.15,1683.92,1684.87,1684.62,1684.09,1683.61,1679.99,1686.41,1685.2,1691.36,1692.14,1693.03,1689.09,1688.58,1687.13,1685.4,1683.62,1680.94,1677.48,1676.78,1678.58,1678.54,1676.55,1678.12,1676.2,1676.1,1676.74,1679.53,1679.06,1678.63,1677.66,1677.07,1676.09,1677.03,1677.6,1677.22,1679.94,1680.67,1682.5,1683.33,1683.43,1682.44,1680.34,1679.25,1678.62,1678.4,1677.23,1675.83,1675.43,1674.82,1671.58,1673.71,1674.99,1680.01,1679.5,1677.73,1673.83,1672.78,1677.25,1682.43,1682.31,1681.66,1684.16,1690.14,1690.31,1687.25,1685.64,1685.44,1684.96,1684.37,1683.8,1682.6,1680.5,1679.95,1679.61,1678.75,1676.18,1675.06,1673.83,1672.71,1672.93,1672.74,1675.18,1675.81,1674.29,1673.23,1672.47,1672.63,1672.68,1671.95,1671.91,1669.46,1669.42,1667.56,1667.02,1666.42,1674.34,1677.39,1679.93,1677.2,1677.54,1725.72,1726.45,1723.95,1719.07,1714.9,1713.87,1716,1715.72,1717.43,1718.71,1720.91,1722.09,1724.24,1731.35,1732.61,1732.44,1734.93,1736.76,1740.44,1739.51,1735.28,1734.72,1734.25,1734.89,1736.28,1738.53,1737.81,1736.2,1737.19,1740.15,1740.73,1741.87,1744.38,1748.07,1748.62,1749.16,1749.32,1750.53,1752.16,1754.02,1754.7,1754.82,1754.67,1755.04,1755.42,1754.23,1754.2,1756.55,1756.55,1754.77,1753.63,1751.07,1747.48,1748.33,1750.47,1754.56,1754.66,1754.37,1752.99,1749.98,1747.23,1747.42,1747.82,1747.89,1747.19,1746.35,1745.54,1744.63,1743.86,1741.65,1742.82,1743.07,1742.89,1741.93,1740.92,1738.93,1740.29,1741.84,1744.1,1745.97,1746.17,1745.38,1746.78,1747.56,1747.12,1745.33,1745.48,1747.25,1748.75,1750.16,1751.12,1748.01,1746.82,1742.39,1738.81,1740.04,1756.32,1758.13,1756.53,1756.39,1757.76,1760.47,1762.84,1761.1,1758.38,1754.77,1756.37,1757.49,1757.81,1757.34,1756.93,1756.31,1755.51,1755.74,1756.5,1756.49,1758.33,1759.08,1757.84,1756.68,1756.49,1755.09,1754.81,1754.25,1754.38,1756.36,1756.48,1755.49,1756.48,1757.23,1759.34,1759.22,1758.44,1757.54,1757.19,1757.33,1756.96,1755.91,1755.38,1754.17,1754.17,1752.22,1747.75,1750,1750,1739.5,1740.62,1739.62,1741.93,1748.05,1747.64,1744.68,1745.92,1747.59,1747.95,1747.98,1745.79,1745.45,1745.73,1746.09,1745.91,1744.46,1743.37,1742.27,1741.79,1741.32,1741.33,1741.36,1740.89,1741,1741.85,1741.94,1742.79,1746.42,1751.06,1750.22,1750.15,1750.14,1749.18,1751.37,1754.4,1754.37,1756.94,1760.38,1760.69,1765.59,1765.67,1762.49,1762.18,1758.04,1755.93,1758.96,1784.43,1782.08,1783.04,1782.7,1781.55,1781.63,1779.92,1778.17,1779.22,1779.54,1778.78,1777.21,1776.88,1776,1774.86,1772.82,1773.1,1773.5,1773.58,1773.82,1774.47,1774.19,1773.22,1771.18,1771.28,1770.27,1770.4,1769.65,1769.17,1771.19,1772.02,1772.09,1770.93,1768.55,1769.87,1769.92,1772.51,1772.68,1770.95,1772.01,1772.99,1771.51,1772.66,1773.93,1772.1,1773.14,1770.89,1775.65,1792.93,1793.01,1789.37,1795.74,1795.88,1792.41,1793.76,1793.67,1791.91,1791.65,1790.34,1789.81,1789.65,1789.09,1790.21,1791.07,1793.48,1793.71,1793.23,1792.29,1791.52,1790.55,1790.12,1790.58,1790.88,1791.28,1791.56,1791.66,1790.86,1790.07,1791.7,1792.75,1793.21,1795.22,1795.47,1794.22,1793.39,1795.09,1795.77,1795.07,1797.22,1800.12,1801.44,1800.98,1800.27,1801.66,1799.07,1801.12,1813.7,1812.64,1816.41,1814.52,1811.15,1807.56,1809,1807.14,1803.55,1806.41,1806.64,1805.38,1806.6,1806.38,1806.65,1809.41,1813.4,1819.04,1819.98,1816.48,1819.43,1819.98,1823.56,1823.37,1821.56,1821.26,1820.94,1818.74,1817.99,1819.16,1819.26,1820.64,1821.34,1822.27,1822.95,1824.03,1822.72,1822.28,1820.45,1817.57,1817.56,1817.07,1818.3,1819.58,1819.69,1820.23,1817.22,1820.06,1846.19,1845.29,1837.94,1840.03,1838.89,1835.82,1828.52,1826.28,1827.65,1828.84,1829.67,1831.35,1832.88,1833.7,1833.71,1832.52,1829.92,1826.76,1824.16,1825.36,1826.29,1827.75,1828.35,1828.99,1829.07,1828.12,1827.52,1825.72,1825.03,1823.54,1828.59,1827.65,1827.1,1832.44,1837.29,1832.98,1831.81,1830.37,1829.94,1829.91,1828.71,1827.92,1826,1824.75,1826.69,1824.95,1818.12,1820.04,1819.03,1809.09,1815.48,1814.58,1815.46,1810.22,1807.81,1805.54,1807.26,1809.32,1810.69,1810.89,1813.39,1821.32,1829.2,1830.6,1822.43,1824.15,1825.81,1831,1831.63,1835.37,1834.97,1832.03,1829.72,1827.67,1827.87,1826.33,1825.5,1827.06,1829.9,1830.38,1828.63,1827.56,1825.81,1827.4,1828.19,1833.02,1833.39,1831.03,1828.85,1827.86,1829.2,1831.04,1834.04,1833.83,1838.01,1837.11,1859.98,1861.48,1860.02,1852.48,1851.32,1853.96,1858.44,1865.35,1865.69,1865.02,1860.04,1860.89,1863.79,1866.1,1865.86,1864.65,1863.77,1862.16,1859.78,1858.55,1858.1,1858.08,1856.63,1857.11,1857.24,1857.51,1857.96,1858,1857.61,1853.68,1852.17,1849.92,1850.47,1849.14,1847.24,1848.15,1849.34,1848.78,1847.09,1848.18,1848.01,1845.92,1844.04,1843.66,1842.82,1840.46,1833.62,1836.32,1837.88,1835.4,1833.97,1834.6,1833.63,1838.51,1841.09,1837.95,1836.99,1836.44,1834.12,1832.23,1831.41,1830.59,1829.76,1830.31,1832.01,1831.55,1829.15,1828.02,1826.99,1827.27,1825.4,1824.89,1824.38,1822.98,1825.11,1825.08,1828.14,1828.58,1836.51,1835.25,1832.2,1837.82,1841.21,1851.82,1855.37,1857.35,1857.4,1860.42,1859.31,1858.59,1858.65,1859.54,1860.39,1861.34,1855.34,1857.3,1873.68,1871.71,1871.95,1878.93,1881.92,1879.5,1878.16,1881.25,1880.75,1880.48,1886.98,1888.99,1886.17,1883.9,1885.62,1885.26,1879.25,1878.74,1877.53,1877.53,1876.84,1877.85,1879.91,1879.56,1879.12,1877.51,1876.54,1874.63,1873.97,1873.14,1870.44,1869.45,1867.91,1866.36,1868.67,1866.29,1861.05,1864.88,1866.51,1865.55,1862.46,1859.29,1864.57,1870.58,1875.33,1875.87,1868.58,1873.37,1875.32,1867.82,1869.03,1869.33,1872.31,1876.46,1875.34,1875.22,1876.96,1881.93,1881.58,1877.25,1873.09,1871.08,1870.73,1869.38,1867.3,1865.7,1863.87,1865.19,1865.56,1862.74,1862.99,1864.72,1864.14,1864.06,1863.21,1862.41,1861.48,1859.13,1859.13,1858.31,1856.94,1856.37,1854.77,1854.01,1857.2,1857.41,1857.22,1858.43,1858.3,1859.62,1859.33,1856.49,1855.93,1855.69,1848.08,1853.92,1858.84,1863.44,1868.76,1870.14,1869.06,1871.75,1872.1,1868.54,1868.89,1868.82,1870.59,1878.09,1879.92,1881.16,1880.8,1877.54,1882.29,1885.25,1884.36,1885.55,1886.72,1887.69,1887.46,1887.42,1886.82,1887.35,1887.24,1886.05,1884.74,1876.79,1875.38,1874.96,1873.42,1871.61,1872.9,1874.79,1878,1878.08,1878.91,1879.85,1879.28,1875.69,1877.28,1880.14,1880.49,1879.74,1875.1,1876.17,1881.18,1879.03,1877.59,1875.99,1875.72,1873.62,1868.96,1870.73,1868.85,1869.29,1865.09,1863.99,1863.5,1861.09,1863.03,1862.43,1861.33,1860.75,1862.19,1863.85,1863.7,1862.22,1860.53,1859.7,1858.83,1859.71,1860.74,1858.98,1861.7,1861.67,1858.4,1857.94,1856.27,1857.02,1857.48,1857.93,1857.21,1860.87,1859.91,1857.47,1854.53,1856.55,1859.25,1859.07,1857.26,1856.18,1841.3,1854.7,1876.8,1874.28,1873.32,1872.38,1874.99,1876.58,1876.3,1874.05,1870.77,1868.67,1867.18,1867.31,1868.75,1868.92,1861.8,1859.84,1858.09,1858.83,1857.95,1857.31,1855.4,1854.63,1852.31,1856.26,1856.5,1857.71,1857.01,1855.66,1854.41,1848.75,1848.29,1847.55,1848.84,1849.3,1854.22,1859.59,1854.11,1851.59,1853.22,1853.96,1856.14,1859.69,1859.11,1859.76,1859.16,1857.16,1849.7,1854.06,1857.41,1856.48,1850.95,1854.33,1862.17,1862.26,1862.92,1860.33,1855.56,1854.2,1854.64,1858.44,1857.02,1856.84,1856.32,1855.83,1858.94,1861.81,1865.08,1871.19,1872.76,1868.15,1871.7,1875.97,1875.16,1873.21,1869.39,1869.02,1867.79,1863.5,1864.26,1865.17,1864.8,1867.15,1866.96,1864.21,1865.93,1866.75,1867.11,1871.63,1874.3,1874.89,1874.69,1874.81,1874,1873.22,1872.69,1874.85,1886.32,1884.13,1883.24,1883.07,1883,1881.84,1879.95,1880.68,1880.57,1878.7,1876.48,1873.7,1873.26,1874.77,1873.94,1873.66,1872.84,1872.43,1870.22,1871.24,1872.79,1873.25,1872.78,1872.14,1872.75,1872.56,1872.67,1872.19,1871.97,1872.97,1876.03,1875.4,1878.25,1880.57,1880.14,1879.07,1878.92,1880.11,1883.29,1885.73,1887.77,1889.25,1889.8,1888.65,1888.29,1892,1888.01,1891.24,1900.09,1904.67,1901.82,1901.67,1908.75,1906.72,1904.68,1904.58,1902.45,1904.24,1904.72,1901.07,1901.4,1901.91,1902.34,1903.12,1904.93,1912.03,1912.4,1908.5,1909.71,1909.13,1906.74,1906.66,1905.96,1907.29,1907.15,1906.4,1906.3,1913.44,1917.05,1924.95,1919.89,1918.71,1917.93,1919.26,1919.97,1919.29,1913.69,1914.79,1914.61,1909.01,1908.46,1910.27,1910.87,1915.38,1907.47,1912.57,1911.15,1906.86,1907.58,1904.78,1904.33,1900.89,1902.48,1902.88,1903.28,1903.79,1903.38,1902.7,1903.26,1903.52,1904.96,1904.25,1904.4,1904.34,1902.78,1902.32,1902.48,1901.91,1900.29,1901.29,1901.24,1901.38,1900.61,1899.74,1899.4,1903.73,1908.35,1915.11,1917.09,1917.14,1914.77,1920.4,1921.81,1921.69,1917.78,1914.77,1914.61,1913.22,1906.06,1907.6,1908.72,1918.95,1907.3,1915.37,1924.69,1927.06,1925.57,1926.19,1923.4,1923.11,1920.71,1920.31,1920.48,1920.56,1921.35,1922.51,1922.75,1922.67,1923.93,1923.02,1921.24,1921.23,1922.9,1923.69,1924.13,1923.75,1922.41,1921.27,1921.62,1921.91,1921.29,1921.29,1920.67,1920.5,1920.26,1921.59,1922.06,1920.15,1918.81,1915.64,1911.95,1912.21,1911.98,1911.93,1912.25,1909.74,1908.98,1907.11,1905.31,1905.13,1895.44,1901.69,1896.08,1893.46,1893.22,1896.37,1898.48,1898.55,1897.83,1894.77,1892.24,1891.94,1891.91,1892.23,1893.37,1894.74,1894.86,1893.88,1893.42,1892.84,1890.78,1890.26,1890.36,1890.01,1889.65,1888.3,1885.82,1883.28,1881.76,1879.82,1878.77,1882.72,1883.5,1880.94,1881.73,1882.39,1883.16,1885.85,1889.14,1892.57,1900,1901.66,1906.64,1906.61,1902.66,1902,1902.25,1901.17,1882.58,1902.19,1908.77,1900.59,1901.99,1901.86,1898.87,1895.58,1893.68,1893.49,1892.9,1894.87,1895.25,1895.41,1897.01,1897.31,1897.25,1896.32,1895.39,1895.99,1895.27,1893.83,1894.01,1892.61,1891.99,1891.88,1892.17,1892.35,1892.76,1892.75,1891.75,1890.22,1891.53,1891.93,1892.31,1894.75,1890.27,1886.84,1883.3,1876.4,1875.01,1872.61,1869.95,1873.88,1876.11,1884.85,1896.53,1895.67,1887.34,1898.37,1898.37,1891.48,1889.27,1896.92,1901.52,1903.41,1899.79,1900.22,1898.95,1897.11,1895.88,1897.5,1900.65,1902.27,1903.09,1906.94,1908.94,1910.32,1909.27,1913.68,1919.66,1921.4,1917.2,1915.78,1917.63,1919.6,1918.89,1918.51,1917.92,1921.09,1927.7,1921.9,1920.59,1919.18,1917.08,1920.18,1919.43,1919.77,1921.19,1921.49,1921.03,1920.06,1917.75,1918.46,1919.1,1925.85,1925.05,1925.86,1930.58,1930.39,1930.2,1927.01,1924.07,1922.96,1918.81,1918.77,1916.77,1918.36,1919.62,1918.52,1918.63,1916.82,1916.25,1917.37,1917.4,1919.38,1919.93,1918.81,1919.11,1918.63,1919.35,1919.74,1919.5,1920.91,1922.47,1921.98,1920.58,1913.62,1914,1912.86,1911.86,1914,1916.7,1916.35,1914.29,1916.25,1916.06,1916.52,1918.81,1919.62,1923.1,1922.32,1921.16,1925.03,1910.14,1921.89,1921.6,1914.86,1916.43,1916.06,1922.28,1922.32,1917.66,1915.87,1915.24,1915.22,1914.69,1912.29,1910.9,1911.68,1913.92,1913.99,1912.83,1913.06,1913.33,1913.36,1914.41,1914.51,1914.36,1915,1917.02,1920.77,1922.64,1920.76,1920.43,1919.21,1918.17,1915.95,1916.23,1917.91,1922.6,1922.03,1920.71,1924.09,1926.78,1925.77,1925.43,1926.22,1924.92,1926.36,1927.33,1932.62,1924.64,1932.04,1933.11,1928.77,1926.79,1926.85,1922.46,1925.05,1926.52,1926.36,1926.25,1924.86,1925.65,1924.91,1924.83,1923.69,1922.87,1922.79,1922.11,1921.49,1921.11,1921.28,1924.4,1924.5,1924.76,1924.9,1925.53,1926.56,1925.97,1922.7,1922.22,1919.53,1921.23,1920.83,1920.02,1916.45,1914.98,1911.07,1915.8,1915.79,1917.11,1920.8,1919.83,1917.41,1916.89,1912.95,1911.47,1917.29,1905.14,1915.45,1910.08,1916.47,1917.42,1918.25,1919.39,1919.35,1919.32,1915.24,1913.84,1913.5,1912.68,1914.84,1915.79,1918.66,1918.27,1915.73,1915.98,1914.61,1911.51,1908.61,1905.87,1906.04,1902.53,1898.82,1899.53,1898.45,1894.53,1881.87,1880.91,1879.22,1882.06,1886,1894.05,1892.56,1897.37,1902.14,1904.58,1899.63,1897.23,1900.51,1903.25,1902.33,1901.5,1904.99,1908.72,1911.07,1903.12,1913.23,1923.21,1915.4,1907.47,1903.45,1906.41,1905.95,1903.04,1902.87,1903.31,1906.55,1906.47,1905.21,1904.17,1903.75,1905.73,1906.57,1906.28,1902.66,1898.61,1897.44,1892.74,1888.67,1889.53,1892.55,1894.75,1896.6,1898.46,1898.51,1896.96,1893.88,1893.21,1892.21,1893.32,1892.58,1892.98,1896.97,1899.13,1898.74,1897.03,1898.35,1899.81,1903.96,1905.42,1904.53,1901.07,1908.37,1894.38,1897.54,1896.89,1885.22,1883.33,1880.49,1873.58,1880.79,1881.65,1882.36,1884.09,1886.01,1886.51,1882.34,1879.12,1877.28,1874.17,1874.92,1874.49,1872.52,1870.79,1869.44,1868.12,1866.92,1864.55,1861.69,1858.92,1864.16,1864.77,1864.97,1864.22,1871.56,1871.38,1870.59,1872.74,1870.38,1868.26,1869.23,1874.19,1875.77,1875.86,1874.61,1874.06,1870.97,1870.84,1873.06,1874.7,1882.14,1872.86,1877.13,1885.85,1885.66,1881.17,1885.53,1887.79,1889.79,1888.72,1885.82,1886.56,1886.87,1884.71,1887.31,1887.58,1886.28,1886.26,1886.56,1887.79,1888.39,1887.98,1886.99,1884.81,1883.74,1883.12,1882.35,1881.53,1880.4,1880.33,1879.14,1880.85,1883.32,1886.72,1887.48,1891.26,1890.24,1887.54,1887.71,1887.17,1887.07,1885.83,1883.8,1884.19,1883.22,1882.73,1880.24,1879.71,1887.18,1879.11,1886.05,1889.15,1886.84,1887.14,1887.73,1887.78,1884.65,1885.14,1885.97,1885.1,1885.55,1887.69,1887.67,1886.05,1885.43,1884.53,1883.66,1882.77,1882.85,1883.34,1883.32,1883.28,1883.5,1883.61,1882.97,1882.56,1882.33,1881.89,1880.89,1880.4,1878.66,1878.9,1877.64,1877.35,1879.02,1880.34,1881.19,1882.49,1882.17,1880.15,1880.6,1880.88,1883.21,1884.17,1883.45,1885.32,1887,1884.57,1884.18,1889.87,1881.03,1879.61,1880.12,1879.95,1880.45,1879.58,1878.16,1876.08,1870.96,1870.09,1869.8,1872.07,1877.17,1877.21,1873.72,1872.27,1872.71,1875.28,1875.15,1874.36,1873.45,1873.42,1873.95,1871.65,1869.79,1869.66,1868.43,1867.83,1868.71,1868.83,1868,1869.21,1869.3,1868.91,1868.1,1865.58,1873.51,1875.41,1872.19,1872.41,1873.22,1873.9,1874.36,1871.48,1872.21,1865.83,1874.43,1870.31,1873.84,1877.06,1879.34,1880.54,1878.52,1875.2,1875.18,1874,1871.94,1871.66,1869.33,1869.56,1870.01,1870.91,1870.49,1869.11,1865.08,1862.63,1863.05,1860.89,1861.07,1859.3,1859.37,1861.16,1860.48,1860.49,1859,1861.79,1860.57,1860.24,1859.57,1859.56,1862.36,1867.56,1873.68,1874.28,1876.23,1877.27,1872.03,1880.16,1882.66,1881.41,1880.02,1877.93,1874.97,1867.81,1869.81,1868.26,1864.71,1863.7,1863.47,1862.77,1860.96,1862.15,1865.07,1864.43,1865.26,1864.62,1863.26,1863.66,1863.21,1863.09,1861.01,1859.59,1858.08,1858.3,1860.63,1860.58,1858.87,1858.48,1858.3,1857.14,1860.22,1863.63,1863.23,1864.99,1863.62,1863.09,1863.64,1865.32,1870.13,1870,1870.08,1873.17,1873.08,1870.5,1868.44,1868.05,1866.68,1868.04,1869.2,1869.32,1866.68,1861.38,1863.49,1871.09,1868.56,1868.43,1867.92,1867.82,1868.82,1869.5,1869.37,1867.56,1866.13,1863.46,1862.85,1862.93,1862.48,1860.46,1859.31,1859.48,1858.16,1856.68,1854.8,1853.78,1853.69,1854.61,1853.89,1852.96,1854.08,1854.8,1853.04,1852.29,1851.05,1850.5,1850.42,1850.22,1849.14,1849.19,1849.35,1849.85,1848.98,1847.26,1847,1848.61,1849.17,1849.45,1848.72,1846.32,1849.26,1841.32,1844.64,1845.62,1844.54,1847.53,1846.59,1851.94,1855.96,1858.76,1854.64,1852.66,1852.74,1852.42,1851.06,1850.82,1847.76,1847.24,1846.23,1846.05,1844.19,1844.19,1843.52,1842.58,1840.86,1841.49,1841.39,1839.08,1837.39,1837.25,1836.1,1835.43,1833.22,1834.94,1838.46,1838.38,1835.57,1834.63,1835.21,1834.87,1833.98,1829.91,1828.04,1828.6,1830.91,1830.94,1829.84,1829,1830.07,1822.4,1826.47,1827.75,1826.06,1823.28,1819.92,1818.25,1816.53,1812.33,1812.47,1811.06,1811.77,1811.19,1812.19,1813.46,1812.66,1809.56,1804.79,1804.61,1802.21,1802.53,1803.86,1803.55,1805.46,1806.67,1810.35,1811.57,1811.58,1810.96,1809.26,1809.5,1810.23,1809.53,1809.53,1814.79,1815.85,1824.34,1828.74,1830,1829.32,1831.65,1828.99,1828.35,1828.3,1827.02,1826.48,1823.51,1821.88,1812.08,1819.01,1822.08,1817.7,1819.88,1824.01,1826.73,1824.94,1823.84,1823.2,1822.67,1821.29,1821.36,1822.08,1821.57,1818.81,1819.27,1818.77,1818.42,1822.05,1824.14,1821.35,1819.62,1818.97,1818.42,1818.5,1818.47,1819.12,1818.95,1818.66,1818.64,1821.32,1824.87,1826.45,1824.19,1823.21,1826.26,1828.17,1828.6,1827.8,1827.8,1827.99,1829.84,1829.73,1829.63,1829.96,1830.58,1830.79,1826.91,1831.55,1838.23,1841.92,1838.92,1842.39,1844.27,1842.27,1842.89,1841.99,1841.31,1841.83,1840.54,1839.69,1838.67,1839.78,1840.99,1841.59,1843.97,1844.07,1843.29,1842.38,1842.52,1842.6,1842.91,1844.89,1846.06,1846.71,1845.7,1843.09,1842.39,1840.46,1841.41,1841.77,1839.77,1842.9,1842.88,1841.58,1841.2,1840.5,1841.77,1841.34,1841.28,1839.8,1839.9,1837.64,1842.08,1843.39,1830.4,1839.68,1838.9,1822.95,1820.41,1816.26,1812.16,1810.61,1815.84,1819.71,1820.47,1821.27,1820.95,1812.83,1810.56,1809.99,1809.65,1811.88,1811.29,1810.94,1810.92,1810.34,1809.01,1808.56,1806.6,1804.5,1803.63,1802.78,1801.36,1799.22,1798.76,1798.88,1800.48,1802.73,1802.91,1800.7,1799.99,1801.68,1801.06,1800.74,1800.15,1799.56,1796.97,1795.16,1793.37,1799.75,1799.42,1794.64,1790.16,1793.66,1800.8,1799.71,1796.88,1796.78,1797.59,1798.61,1800.21,1797.49,1795.77,1793.73,1791.35,1789.07,1787.26,1785.04,1783.46,1784.72,1786.02,1788.17,1788.63,1789.53,1794.88,1795.53,1794.48,1793.83,1794.09,1794.36,1792.58,1792.6,1796.41,1793.81,1790.85,1789.55,1792.17,1792.12,1790.45,1787.77,1787.68,1788.15,1788.35,1790.44,1795.55,1794.3,1793.72,1792.22,1793.25,1793.14,1790.35,1793.05,1793.71,1791.83,1793.59,1794.95,1797.74,1797.58,1796.32,1794.69,1793.51,1791.81,1792.36,1792.39,1791.25,1792.86,1795.06,1797.9,1800.28,1799.96,1798.82,1799.92,1800.29,1802.05,1802.81,1803.19,1802.14,1802.13,1801.22,1801.26,1801.01,1798.93,1798.83,1798.86,1797.7,1797.44,1797.57,1797.12,1797.41,1798.63,1798.66,1798,1802.34,1802.57,1801.52,1804.14,1805.03,1804.43,1799.33,1803.71,1793.15,1794.22,1793.92,1792.76,1791.4,1790.14,1790.69,1792.37,1792.62,1793.18,1793.72,1794.22,1793.97,1793.69,1793.16,1792.52,1792.76,1795.67,1795.15,1796.44,1797.37,1798.82,1798.57,1797.54,1795.68,1796.81,1797.25,1796.99,1796.52,1794.93,1796.13,1797.53,1797.55,1800.43,1800.85,1800.01,1799.77,1798.75,1797.96,1798.14,1798.12,1801.54,1801.62,1801.99,1800.82,1799.77,1795.35,1798.61,1813.57,1810.4,1808.84,1806.45,1807.68,1807.53,1805.33,1805.67,1804.71,1804.16,1804.12,1808.56,1809.32,1807.67,1806.73,1805.45,1804.31,1804.24,1803.42,1803.68,1803.91,1803.69,1802.79,1802.71,1802.8,1803.38,1803.64,1803.19,1803.27,1803.96,1803.67,1803.37,1803.21,1803.82,1805.32,1806.79,1806.43,1805.92,1805.17,1804.34,1804.58,1802.56,1802.36,1797.9,1795.3,1794.54,1788.96,1791.65,1807.44,1808.92,1810.41,1809.07,1806.71,1804.44,1797.77,1798.71,1796.91,1794.19,1794.41,1784.78,1781.98,1781.39,1780.15,1779.04,1787.77,1789.84,1792.27,1794.48,1793.72,1796.07,1795.71,1792.67,1795.17,1794.52,1794.41,1794.58,1794.24,1792.79,1797.72,1798.55,1801.67,1801.53,1802.22,1800.35,1798.39,1796.43,1795.37,1796.36,1797.25,1797.06,1796.39,1795.91,1795.98,1797.45,1796.67,1799.31,1803.87,1806.29,1806.09,1808.7,1808.55,1806.36,1804.26,1811.38,1811.59,1806.83,1808.42,1808.14,1807.94,1806.61,1806.79,1806.87,1806.53,1804.26,1805.71,1805.28,1805.18,1804.74,1805.99,1804.95,1804.5,1804.66,1804.56,1803.68,1805.18,1806.05,1805.96,1805.78,1805.12,1805.01,1805.23,1806.23,1807.51,1807.85,1806.64,1806.69,1807.34,1807.02,1806.54,1806.56,1805.81,1805.59,1806.17,1806.14,1806.87,1808.43,1807.02,1807.94,1807.94,1806.44,1805.58,1802.49,1802.96,1802.75,1801.42,1801.83,1803.49,1804.89,1808.45,1808.38,1807.52,1806.09,1804.07,1802.82,1801.71,1798.78,1796.65,1797,1797.03,1796.49,1795.35,1794.66,1794.54,1793.41,1794.13,1792.97,1791.4,1791.13,1790.11,1789.78,1790.26,1795.04,1796.47,1796.4,1796.89,1800.15,1801.11,1802.56,1802.7,1806.43,1806.33,1806.57,1808.57,1808.29,1808.27,1806.54,1808.26,1805.61,1804.84,1806.35,1806.2,1806.2,1836.95,1823.89,1828.58,1829.74,1825.86,1828.26,1832.1,1836.4,1836.24,1834.14,1834.46,1834.46,1834.84,1835.42,1835.81,1835.92,1836.4,1834.74,1834.82,1835.55,1835.63,1835.91,1835.32,1834.79,1835.24,1835.58,1835.56,1835.62,1835.42,1835.2,1834.57,1834.92,1835.55,1834.64,1834.9,1834.67,1834.73,1834.95,1834.5,1833.71,1833.2,1832.9,1832.52,1833.23,1833,1832.87,1833.85,1832.15,1826.47,1830.36,1832.18,1830.47,1839.29,1838.52,1835,1833.43,1831.81,1832.65,1833.45,1833.44,1833.42,1833.2,1831.58,1830.65,1830.41,1827.69,1826.83,1826.71,1827.71,1827.84,1827.33,1827.39,1828.11,1829.92,1830.01,1829.24,1829.08,1829.6,1829.5,1828.07,1827.41,1826.41,1826.1,1825.05,1825.47,1827.12,1827.86,1828.13,1827.36,1828.04,1827.87,1827.99,1826.96,1828.05,1827.33,1826.96,1826.76,1824.76,1825.96,1815.28,1815.22,1824.53,1824.53,1829.39,1829.45,1829.55,1827.53,1827.68,1829.31,1834.76,1837.4,1835.74,1833.58,1830.09,1828.96,1828.76,1831.63,1832.58,1832.63,1839.02,1842.31,1843.34,1847.8,1851.51,1850.53,1850.44,1851.68,1851.52,1852.67,1855.21,1855.97,1856.06,1856.73,1856.81,1856.31,1857.09,1857.16,1857.63,1858.88,1859.24,1859.17,1857.88,1857.81,1858.06,1857.21,1856.74,1857.64,1857.51,1858,1859.11,1859.67,1859.78,1856.18,1855.49,1857.91,1857.91,1875.73,1875.81,1883.63,1883.87,1880.46,1878.86,1878.59,1881.37,1880.47,1877.13,1874.72,1873.06,1870.77,1870.21,1869.98,1870.04,1869.78,1869.17,1868.98,1869.25,1868.85,1868.28,1871.27,1872.87,1872.3,1873.22,1872.73,1874.95,1878.49,1878.14,1884.1,1884.19,1886.37,1886.6,1885.81,1885.78,1883.77,1881.01,1880.46,1879.78,1879.44,1876.62,1874.9,1874.8,1874.35,1872.56,1869.8,1866.86,1868.1,1869.04,1869.04,1871.18,1873.18,1873.19,1884.2,1881.92,1884.92,1886.66,1886.2,1894.75,1893.4,1886.84,1882.94,1882.26,1880.33,1879.99,1879.93,1879.52,1879.19,1878.62,1876.15,1873.87,1872.64,1871.8,1870.02,1868.25,1867.1,1865.64,1867.22,1866.49,1865.69,1865.43,1868.6,1871.54,1873.23,1875.56,1873.81,1872.3,1873.57,1875.48,1876.04,1875.96,1876.78,1878.44,1881.05,1883.04,1884.19,1884.13,1882.78,1879.73,1879.14,1879.17,1878.02,1878.02,1886.15,1879.88,1880.16,1874.04,1872.47,1872.51,1873.66,1870.49,1869.76,1870.27,1870.38,1869.48,1868.74,1867.74,1867.53,1866.32,1866.65,1866.41,1865.07,1864.61,1864.14,1861.99,1860.85,1860.63,1858.89,1861.71,1864.31,1864.81,1862.37,1861.84,1862.4,1862.47,1862.54,1869.37,1871.47,1868.77,1868.38,1866.34,1864.03,1863,1863.79,1863.27,1863.38,1862.7,1861.05,1858.73,1864.05,1864,1857.25,1853.1,1862.41,1863.07,1863.07,1851.13,1857.9,1863.07,1865.88,1866.41,1873.88,1873.91,1869.56,1868.78,1866.94,1865.87,1865.1,1863.19,1860.68,1861.16,1865.79,1867.01,1864.78,1861.96,1861.9,1860.6,1860.5,1859.46,1859.54,1860.08,1859.85,1858.83,1857.42,1856.79,1855.99,1858.23,1859.22,1859.99,1860.66,1862.23,1862.72,1862.73,1860.93,1861.77,1864.48,1866.01,1866.31,1866.76,1866.21,1864.08,1863.72,1866.48,1872.37,1869.41,1863.69,1865.97,1871.91,1871.91,1870.42,1869.52,1867.91,1866.47,1865.22,1863.04,1864.82,1865.41,1864.75,1862.53,1861.77,1861.84,1862.21,1863.17,1863.29,1862.48,1861.94,1861.47,1859.61,1859.89,1860.04,1861.36,1860.95,1859.82,1858.81,1859.18,1858.72,1857.73,1856.74,1857.56,1857.23,1857.02,1855.99,1857.92,1859.57,1860.21,1860.8,1861.09,1860.27,1859.87,1857.74,1858.86,1859.04,1858.1,1857.03,1857.07,1858.04,1852.65,1851.64,1856.39,1854.97,1854.97,1853.87,1855.67,1854.5,1859.39,1858.09,1853.65,1852.5,1850.68,1850.01,1849.64,1849.93,1851.24,1854.79,1855.35,1855.26,1858.32,1858.72,1856.93,1857.76,1858.29,1858.08,1857.52,1858.3,1858.09,1858.27,1858.03,1857.87,1859.17,1858.52,1860.11,1863.14,1862.19,1859.71,1861.56,1860.94,1860.71,1861.13,1861.06,1860.56,1862.1,1861.33,1861.62,1860.87,1860.16,1858.88,1858.55,1858.63,1853.89,1854.01,1857.78,1860.01,1860.01,1860.9,1860.94,1862.38,1862.74,1865.62,1865.51,1865.29,1865.37,1865.72,1865.99,1865.87,1865.21,1866.27,1866.23,1866.59,1867.92,1867.68,1868.94,1870.92,1871.37,1870.59,1867.94,1867.43,1866.51,1866.71,1865.94,1865.66,1865.07,1869.27,1869.34,1870.36,1870.51,1870.9,1871.68,1870.94,1870.71,1868.73,1867.72,1866.72,1866.2,1865.82,1866.34,1866.4,1867.32,1867.89,1868.55,1868.61,1868.7,1864.5,1863.98,1864.05,1867.22,1867.21,1870.02,1868.33,1870.28,1873.69,1873.87,1871.25,1871.08,1869.47,1866.97,1866.52,1868.59,1868.71,1868.29,1867.84,1867.11,1866.88,1866.81,1866.25,1865.16,1864.86,1866.25,1867.84,1871.72,1871.3,1870.33,1870.1,1870.74,1871.07,1870,1869.42,1868.9,1869.26,1868.62,1868.69,1868.14,1868.41,1867.91,1868.16,1868.51,1868.64,1868.4,1865.88,1865.42,1865.71,1865.6,1866.21,1870.33,1870.68,1868.86,1863.32,1866.35,1866.35,1868.44,1867.08,1868.03,1868.48,1867.63,1868.2,1868.23,1870.48,1872.98,1870.54,1868.42,1868.61,1865.78,1864.78,1864.45,1864.68,1864.89,1864.75,1864.32,1863.77,1862.78,1861.62,1861.23,1861.74,1860.82,1861.24,1861.18,1860.74,1859.65,1859.09,1860.39,1859.11,1859.07,1859.3,1860.09,1860.39,1860.11,1860.46,1862.78,1863.96,1864.96,1864.81,1865.06,1864.35,1864.38,1864.04,1863.79,1863.12,1862.75,1859.52,1859.6,1862.13,1862.08,1879.13,1873.58,1872.91,1870.74,1868.83,1869.58,1869.63,1869.25,1865.64,1864.08,1861.14,1858.6,1861.92,1862.19,1863.15,1863.25,1861.41,1860.94,1861.04,1861.01,1860.35,1860.4,1861.07,1860.58,1861.31,1861.47,1861.62,1860.71,1860.16,1860.46,1860.14,1860.32,1860.99,1861.09,1860.54,1859.58,1858.64,1857.78,1857.9,1858.12,1856.88,1855.23,1849.23,1848.87,1848.38,1839.69,1842.12,1838.39,1839.44,1843.5,1843.5,1841.69,1843.67,1845.33,1845.19,1842.71,1843.26,1843.65,1842.69,1841.82,1841,1838.5,1836.72,1837.02,1837.23,1836.47,1835.5,1835.35,1835.11,1834.7,1833.64,1831.91,1831.27,1832.19,1830.79,1829.95,1828.68,1828.07,1827.9,1827.82,1833.17,1833.34,1834.7,1837.9,1837.99,1838.69,1839.84,1839.35,1837.86,1840.37,1841.23,1841.12,1840.68,1841.19,1842.55,1843.94,1845.67,1847.05,1845.06,1844.68,1848.57,1848.25,1848.25,1844.23,1849.09,1850.6,1850.02,1849.86,1848.77,1847,1846.77,1846.16,1845.19,1844.96,1845.38,1846,1848.39,1850.46,1851.37,1851.78,1851.06,1851.07,1854.8,1855.74,1855.68,1854.7,1853.42,1853.16,1852.51,1852.3,1852.12,1851.68,1851.7,1851.07,1851.05,1851.06,1851.67,1852.13,1852.66,1853.62,1854.13,1854.39,1854.45,1853.77,1854.11,1853.64,1851.68,1852.74,1853.11,1853.75,1850.76,1853.7,1853.7,1842.59,1853.7,1849.25,1850.56,1850.55,1850.11,1849.24,1848.55,1847.58,1845.8,1845.15,1845.48,1844.15,1842.73,1843.26,1844.29,1844.81,1844.45,1844.65,1845.4,1846.17,1846.54,1847.28,1846.04,1845.76,1845.71,1845.4,1844.98,1844.75,1846.22,1844.28,1844.38,1844.76,1845.53,1845.49,1846.48,1846.34,1845.08,1844.64,1843.17,1844.14,1844.41,1843.91,1842.8,1843.25,1842.34,1843.73,1839.51,1839.1,1839.09,1841.37,1840.7,1840.13,1844.13,1845.86,1845.07,1841.59,1839.94,1838.64,1837.7,1838.88,1838.94,1838.51,1838.37,1838.44,1838.02,1837.65,1837.52,1838.04,1836.94,1837.1,1836.85,1835.78,1835.35,1835.5,1835.35,1834.69,1834.97,1834.83,1834.49,1833.18,1833.64,1833.57,1834.89,1834.75,1834.69,1839.65,1842.02,1840.02,1839.32,1839.26,1839.41,1838.95,1837.07,1836.04,1835.97,1835.93,1834.87,1832.1,1827.73,1826.15,1827.39,1828.95,1828.34,1831.39,1829.5,1822.89,1822.46,1821.42,1820.03,1818.78,1817.44,1816.09,1816.61,1816.45,1815.76,1814.48,1811.5,1811.42,1810.25,1810.91,1811.8,1812.71,1812.86,1812.74,1812.18,1811.34,1809.24,1806.07,1804.56,1803.03,1802.26,1801.51,1803.93,1806.73,1806.07,1805.53,1806.45,1805.65,1806.17,1805.69,1803.56,1799.62,1794.7,1795.35,1794.81,1792.89,1794.19,1792.9,1790.82,1797.14,1793.02,1790.41,1788.65,1800.54,1800.54,1790.06,1790.65,1800.54,1797.18,1798.87,1798.29,1793.45,1789.56,1790.26,1789.37,1787.93,1785.13,1784.03,1780.89,1777.99,1776.04,1779.43,1780.22,1779.46,1778.41,1781.74,1784.24,1784.13,1784.16,1782.66,1782.3,1781.7,1782.36,1782.65,1782.45,1787.76,1789.42,1793.84,1798,1797.66,1796.33,1798.26,1800.56,1800.94,1799.82,1800.09,1799.69,1801.73,1801.27,1799.73,1801.43,1803.98,1805.35,1802.2,1803.31,1806.63,1806.63,1805.55,1805.93,1797.94,1795.01,1794.82,1793.99,1793.77,1788.9,1786.25,1787.02,1785.93,1786.07,1785.08,1784.51,1784.43,1783.98,1785.44,1791.41,1789.75,1789.92,1790.3,1790.09,1789.37,1789.34,1789.55,1789.72,1791.51,1792.06,1791.07,1790.67,1790.09,1789.74,1788.55,1787.99,1787.57,1787.42,1786.8,1787.48,1786.07,1785.84,1785.78,1786.95,1787.67,1787.84,1786.29,1781.37,1786.43,1779.92,1777.7,1776.8,1783.75,1782.12,1766.1,1777.36,1779.37,1781.23,1780.37,1783.09,1784.77,1784.84,1782.18,1778.9,1778.54,1777.15,1774.96,1775.49,1772.07,1770.59,1770.93,1770.1,1770.09,1766.73,1767.42,1765.11,1765.15,1764.43,1762.2,1766.11,1766.63,1766.85,1765.97,1766.09,1765.42,1764.43,1762.84,1759.91,1761.41,1764.09,1770.47,1771.9,1779.7,1781.59,1783.71,1786.13,1790.76,1791.89,1797.98,1799.02,1803.42,1794.37,1794.48,1799.87,1804.3,1804.24,1804.24,1802.83,1801.65,1796.4,1797.13,1795.92,1796.99,1796.95,1796.02,1795,1793.43,1791.12,1792.97,1793.89,1794.27,1794.63,1792.21,1791.91,1791.82,1791.41,1791.6,1791.44,1792.14,1793.03,1795.37,1796.57,1796.66,1796.68,1796.14,1793.12,1793.94,1794.54,1794.37,1795.03,1795.03,1796.17,1794.53,1795.6,1793.92,1794.07,1794.09,1794.19,1793.18,1790.93,1790.97,1791.7,1784.83,1782.12,1790.13,1787.45,1780.32,1787.45,1782.46,1779,1778.21,1779,1780.29,1780.42,1779.75,1779.73,1779.09,1777.63,1776.46,1772.21,1771.02,1772.15,1772.06,1772.16,1771.59,1770.35,1768.08,1767.38,1765.51,1761.12,1759.89,1757.44,1755.13,1755.1,1754.38,1754.11,1756.32,1756.21,1754.65,1751.84,1750.95,1748.17,1747.25,1747.32,1753.96,1756.95,1756.86,1753.63,1751.6,1751.03,1746.18,1740.46,1745.8,1738.42,1737.03,1738.01,1743.51,1743.51,1730.85,1743.84,1743.09,1742.66,1745.86,1747.69,1748.5,1750.07,1749.63,1746.11,1744.9,1749.09,1750.3,1748.76,1746.78,1746.66,1745.93,1744.06,1742.74,1742.3,1739.76,1739.85,1738.51,1738.15,1736.25,1736.44,1735.21,1734.61,1734.63,1736.76,1736.88,1738.65,1738.53,1738.43,1736.25,1735.59,1735.36,1736.37,1735.31,1730.75,1734.19,1731.97,1731.06,1728.96,1730.33,1730.42,1730.42,1725.01,1723.01,1731.15,1730.56,1730.56,1722.75,1736.91,1736.46,1732.08,1732.88,1733.02,1726.96,1719.61,1719.18,1714.98,1713.4,1706.75,1705.1,1704.68,1705.92,1702.51,1700.29,1700.55,1705.69,1706.06,1703.89,1702.7,1701.86,1705.12,1703.72,1699.54,1695.96,1693.6,1692.9,1693.42,1688.15,1687.58,1686.96,1681.19,1683.35,1694.18,1697.15,1692.64,1689.06,1688.65,1690.63,1699.83,1698.26,1689.4,1689.54,1681.63,1681.14,1666.68,1665.29,1664.33,1671.17,1668.53,1654.35,1659.39,1675.82,1680.51,1682.98,1680.42,1675.01,1675.27,1672.89,1667.96,1666.14,1671.67,1677.05,1675.45,1674.32,1683.28,1681.46,1678.19,1674.43,1672.34,1671.38,1669.65,1667.53,1667.09,1663.7,1660.92,1662.57,1660.89,1660.96,1660.7,1670.78,1673.6,1683.95,1684.74,1680.34,1683.2,1688.43,1700.57,1702.22,1696.04,1694.64,1693.21,1695.87,1703.48,1700.44,1699.18,1696.57,1694.92,1697.3,1696.45,1699.33,1699.38,1699.38,1702.51,1692.67,1699.38,1687.75,1685.05,1683.38,1686.75,1687.11,1686.43,1686.13,1682.27,1682.58,1682.95,1683.1,1681.9,1677.73,1675.9,1679.32,1683.95,1685.13,1691.86,1690.98,1690.34,1692.25,1695.08,1696.78,1695.81,1694.53,1694.06,1693.61,1692.21,1691.32,1689.47,1688.95,1689.62,1690.52,1689.35,1688.18,1689.19,1689.34,1690.29,1688.87,1688.49,1690.39,1689.08,1688.74,1689.04,1686.28,1680.34,1682.26,1686.11,1686.11,1684.88,1695.3,1693.27,1698.08,1697.23,1697.01,1700.66,1700.69,1698.57,1696.62,1693.14,1691.51,1691.46,1690.27,1692.5,1692.25,1690.8,1690.39,1689.22,1688.04,1685.89,1684.23,1682.85,1682.44,1683.95,1683.42,1682.73,1682.93,1682.53,1686.75,1688.18,1688.39,1686.97,1685.47,1683.98,1684.04,1684.48,1684.02,1685.91,1687.3,1686.54,1687.47,1686.66,1685.98,1683.78,1679.95,1678.81,1667.66,1663.67,1663.15,1669.12,1669.01,1648.61,1649.61,1651.23,1669.01,1665.51,1662.4,1663.57,1666.21,1667.32,1664.54,1663.11,1663,1660.85,1658.4,1660.24,1660.93,1665.19,1666.26,1666.75,1666.72,1664.95,1669.96,1671.91,1674.01,1676.25,1676.13,1675.11,1674.28,1672.73,1673.59,1673.4,1674.71,1677.09,1681.98,1684.38,1684.54,1681.95,1680.8,1680.38,1678.15,1680.62,1681.92,1680.1,1680.35,1679.84,1679.44,1679.52,1677.24,1677.1,1677.87,1678.71,1679.88,1680.62,1680.62,1682.93,1682.92,1682.72,1680.42,1684.54,1686.86,1683.71,1682.14,1682.05,1681.88,1680.66,1680.15,1677.09,1680.45,1682.71,1682.59,1683.56,1683.85,1683.49,1683.63,1683.65,1683.16,1682.28,1682.67,1681.62,1681.15,1680.99,1682.3,1683.96,1684.18,1694.63,1703.61,1703.66,1697.48,1697.54,1696.59,1695.65,1695.28,1695.22,1693.98,1697.5,1697.36,1698.5,1698.49,1695.69,1700.22,1699.59,1701.14,1701.57,1703.32,1704.68,1704.68,1706.41,1705.65,1708.73,1709.96,1712.51,1719.28,1720.47,1719.45,1719.9,1719.82,1719.76,1720.78,1720.96,1720.84,1719.93,1719.96,1722.03,1725.9,1727.15,1728.93,1729.23,1727.35,1727.55,1729.51,1731.8,1733.47,1734.45,1735.8,1735.48,1737.22,1739.95,1740.92,1741.48,1739.79,1739.61,1740.26,1739.81,1737.76,1734.33,1737.91,1739.86,1740.09,1741.33,1742.53,1743.95,1744.8,1744.02,1744.46,1744.15,1745.44,1744.66,1744.66,1765.5,1768.22,1764.45,1757.29,1754.26,1753.53,1755.28,1755.35,1753.54,1752.67,1749.41,1749.62,1757.69,1760.66,1759.73,1755.65,1755.95,1756.13,1756.11,1755.03,1754.64,1753.24,1752.24,1750.02,1750.25,1750.66,1750.43,1750.68,1750.74,1749.18,1748.48,1745.37,1748.41,1748.8,1748.14,1747.29,1746.98,1745.74,1745.85,1745.3,1744.7,1743.44,1741.17,1738.59,1741.98,1741.4,1739.28,1738.75,1718.7,1723.06,1724.92,1735.78,1735.78,1736.06,1745.61,1746.27,1746.02,1740.2,1742.84,1744.97,1750.52,1752.01,1753.5,1749.4,1749.7,1749.13,1748.25,1748.81,1749.05,1749.84,1752.49,1753.23,1753.33,1753.06,1752.57,1752.71,1753.48,1754.66,1755.41,1755.72,1756.08,1755.95,1756.65,1758.91,1759.16,1761.04,1762.14,1765,1764.9,1763.98,1764.26,1764.64,1765.75,1766.62,1767.58,1766.59,1763.3,1761.58,1762.3,1762.47,1760.65,1760.93,1763.27,1762.84,1762.84,1768.41,1769.08,1765.22,1762.75,1771.13,1769.94,1766.21,1763.86,1763.56,1767.26,1771.53,1773.45,1775.1,1773.19,1774.42,1775.05,1776.36,1776.54,1774.47,1774.8,1773.87,1772.81,1771.1,1769.75,1771.28,1771.56,1771.66,1771.27,1770.93,1769.04,1768.47,1768.63,1768.69,1769.23,1771.88,1773.53,1774.54,1772.17,1771.54,1771.94,1772.34,1771.9,1772.25,1774.43,1773.89,1771.99,1772.88,1775.49,1770.97,1772.13,1774.04,1777.23,1777.23,1785.34,1786.97,1790.87,1789.97,1788.15,1788.77,1786.4,1784.08,1783.39,1782.76,1785.74,1785.95,1785.57,1787.65,1788.18,1788.24,1787.97,1788.72,1788.14,1787.3,1786.67,1786.94,1786.79,1787.03,1787.32,1787.33,1786.84,1785.69,1786.64,1786.27,1785.59,1784.29,1784.19,1783.3,1781.91,1780.81,1781.41,1782.14,1781.69,1780.52,1779.64,1778.78,1778.47,1775.97,1777.51,1778.71,1776.53,1776.84,1772.56,1771.71,1775.11,1776.48,1776.46,1788.1,1784.65,1782.75,1781.46,1778.45,1776.16,1777.18,1776.81,1776.23,1776.42,1779.55,1780.12,1782.86,1784.39,1783.63,1780.99,1780.28,1780.24,1779.32,1777.58,1775.76,1775.22,1774.69,1773.62,1772.83,1772.42,1772.94,1772.39,1772.02,1770.73,1772.88,1775.06,1775.21,1774.77,1772.31,1771.8,1771.98,1772.23,1772.7,1772.45,1771.13,1771.49,1770.8,1768.52,1766.48,1770.14,1771.16,1767.02,1765.29,1764.73,1764.78,1764.78,1763.39,1757.76,1764.78,1759.72,1762.65,1762.29,1761.78,1761.91,1762.06,1760.06,1759.79,1761.88,1764.31,1769.36,1773.97,1772.28,1773.57,1774.61,1774.56,1773.45,1773.21,1773.11,1773.2,1772.14,1771.25,1769.8,1768.67,1768.97,1768.19,1767.71,1768.23,1768.69,1769.17,1771.13,1772.55,1773.04,1773.14,1773.36,1772.68,1772.37,1772.77,1772.66,1772.07,1772.14,1771.39,1770.8,1770.41,1768.33,1767.62,1766.91,1768.02,1768.23,1768.06,1760.86,1769.13,1775.79,1773.38,1765.74,1762.6,1764.34,1765.7,1766.87,1775.29,1775.98,1774.98,1774.37,1772.3,1772.11,1771.87,1771.44,1770.47,1770.49,1773.57,1773.19,1773.22,1773.82,1776.04,1778.62,1778.93,1781.11,1780.94,1780.24,1780.4,1782.35,1780.07,1779.46,1779.52,1779.29,1779.48,1780.39,1780.39,1780.52,1782.29,1784.06,1785.38,1783.83,1783.11,1782.21,1781.35,1779.84,1779.41,1777.14,1775.74,1776.84,1776.77,1776.77,1779.97,1788.91,1789.35,1784.35,1780.43,1775.6,1775.34,1776.71,1777.57,1777.29,1778.24,1779.73,1779.49,1779.54,1778.1,1777.47,1780.26,1780.34,1780.51,1780.25,1780.66,1780.68,1779.83,1779.45,1780.05,1780.45,1780.38,1780.07,1779.58,1778.95,1777.62,1778.2,1778.5,1779.16,1783.31,1782.63,1780.84,1779.55,1778.02,1777.78,1776.33,1776.38,1776.22,1776.25,1776.45,1776.09,1775.01,1770.88,1773.41,1773.41,1777.2,1776.49,1776.19,1776.63,1775.62,1775.71,1775.49,1773.19,1777.98,1785.3,1786.66,1790.61,1792.61,1791.82,1789.55,1788.72,1787.79,1787.48,1790.83,1789.49,1788.95,1786.99,1788.91,1788.69,1788.32,1788.46,1788.69,1790.17,1794.01,1793.78,1792.77,1791.72,1789.09,1788.77,1791.27,1792.7,1792.48,1792.56,1792.94,1791.87,1789.19,1791.41,1791.49,1791.15,1789.67,1788.81,1790.63,1791.59,1791.89,1790.1,1790.35,1792.54,1793.18,1793.18,1796.27,1797.08,1798.79,1798.53,1795.36,1793.05,1793.04,1794.84,1796.31,1794.16,1794.33,1794.13,1793.77,1792.66,1792.61,1792.95,1792.34,1793.13,1793.19,1793.12,1792.98,1793.55,1793.43,1792.02,1794.25,1795.51,1795.8,1795.71,1795.54,1794.89,1793.26,1792.95,1792.56,1790.4,1788.71,1789.24,1789.21,1785.39,1782.16,1784.01,1783.93,1781.71,1776.55,1773.15,1773.04,1771.88,1768.17,1765.97,1764.46,1765.06,1766.27,1765.63,1763.92,1764.1,1765.63,1757.28,1757.05,1758.48,1758.88,1758.75,1756.02,1750.29,1758.21,1759.22,1756.63,1752.75,1753.19,1753.75,1753.95,1752.49,1754.03,1754.19,1754.77,1754.1,1752.97,1750.48,1749.87,1749.53,1748.01,1745.6,1744.53,1744.75,1744.28,1745.31,1744.37,1742.99,1743.21,1743.29,1742.42,1742.35,1740.49,1738.75,1734.95,1738.71,1739.14,1733.08,1731.27,1733.12,1727.52,1729.4,1723.38,1728.4,1728.27,1729.29,1729.08,1726.52,1734.72,1735.2,1733.28,1727.18,1728.46,1730.39,1731.55,1731.55,1732.73,1732.61,1731.65,1731.59,1729.34,1726.33,1727.11,1727.08,1725.3,1722.14,1721.27,1721.35,1719.59,1718.05,1720.12,1722.01,1721.62,1721.03,1720.04,1719.27,1722.37,1721.31,1720.39,1719.99,1720.97,1726.43,1726.61,1726.06,1727.44,1729.97,1730.2,1728.77,1727.32,1728.6,1728.89,1725.03,1725.13,1725.88,1722.93,1723.16,1723.42,1727.46,1727.46,1724.75,1731.95,1737.03,1734.77,1732.31,1734.02,1738.39,1744.17,1744.17,1742.38,1747.41,1749.28,1749.69,1750.69,1750.86,1750.79,1746.44,1745.02,1742.17,1739.59,1741.79,1741.88,1741.13,1740.29,1739.09,1737.94,1736.14,1735.87,1734.72,1734.47,1732.43,1732.73,1732.43,1733.01,1733.24,1734.22,1733.09,1732.7,1732.05,1730.78,1729.2,1729.37,1726.49,1727.52,1729.24,1729.21,1730.31,1729.41,1730.75,1732.02,1732.02,1734.92,1732.19,1733.97,1734.39,1734,1730.16,1729.49,1727.96,1728.98,1729.86,1729.76,1728.92,1728.57,1729.26,1730.06,1730.21,1730.08,1728.54,1728.15,1728.79,1726.84,1726.02,1725.03,1723.99,1722.55,1722.37,1723.41,1723.41,1724.52,1724.13,1723.86,1723.35,1723.78,1724.67,1726.03,1726.61,1724.68,1724.97,1723.4,1723.35,1722.22,1720.92,1722.24,1722.75,1723.35,1724.25,1724.99,1726.72,1725.16,1724.27,1724.52,1726.69,1726.69,1730.18,1730.06,1739.98,1739.43,1737.35,1740.01,1741.84,1742.07,1742.38,1741.22,1740.88,1739.46,1738.17,1738.87,1737.32,1735.41,1735.08,1735.58,1736.81,1736.61,1735.14,1735.14,1735.35,1736.17,1736.07,1734.98,1733.91,1732.86,1732.53,1731.81,1731.27,1731.83,1731.42,1732.27,1732.58,1732.21,1732.84,1732.51,1733.23,1733.91,1735.1,1737.97,1739.36,1739.93,1739.01,1738.62,1736.58,1735.85,1732.35,1732.68,1733.27,1734.24,1734.24,1735.78,1734.24,1732.37,1732.11,1727.73,1729.29,1730.63,1730.35,1730.32,1729.84,1729.44,1730.81,1731.55,1731.26,1731.14,1730.79,1731.4,1731.48,1732.05,1734.98,1735.39,1735.29,1735.57,1735.84,1737.73,1738.1,1738.68,1739.59,1739.13,1741.81,1745.81,1747.09,1745.55,1751.86,1754.53,1758.53,1757.24,1758.3,1760.11,1762.94,1763.74,1764.76,1764.6,1762.34,1763.74,1767.52,1767.5,1765.38,1765.16,1767.63,1768.31,1768.12,1779.72,1787.55,1793.21,1791.93,1785.62,1781.7,1784.39,1786.6,1786.51,1784.82,1787.06,1789.98,1791.83,1794.9,1794.21,1795.38,1794.73,1794.1,1793.39,1792.41,1790.58,1790.04,1788.5,1786.73,1785.81,1788.51,1789.33,1789.53,1789.19,1788.75,1789.07,1791.06,1792.79,1790.65,1790.35,1790.41,1789.88,1789.21,1787.78,1788.25,1788.06,1786.79,1787.45,1789.44,1789.93,1789.85,1788.24,1787.72,1786.2,1786.65,1787.95,1788.94,1788.78,1792.26,1793.05,1792.74,1794.13,1799.16,1803.14,1802.87,1801.43,1802.13,1801.81,1801.46,1797.38,1796.87,1798.34,1800.34,1802.13,1804.5,1809.65,1808.7,1808.52,1807.61,1807.83,1807.23,1812.18,1809.95,1808.34,1807.51,1807.8,1807.7,1808.1,1807.11,1806.04,1804.08,1802.08,1799.98,1796.24,1799.2,1800.08,1800.38,1800.39,1797.6,1795.61,1794.97,1790.1,1794.28,1795.53,1795.22,1795.12,1794.88,1790.15,1789.81,1791.48,1791.48,1791.41,1790.88,1796.24,1796.19,1794.31,1796.85,1803.3,1803.05,1802.34,1802.24,1800.76,1801.65,1801.14,1799.77,1800.37,1800.76,1797.69,1797.4,1797.39,1795.61,1795.11,1793.54,1794.72,1793.66,1793.72,1794.91,1795.43,1795.1,1795.95,1795.63,1795.6,1795.46,1795.9,1798.11,1798.03,1797.58,1801.09,1800.1,1802.78,1806.85,1808.91,1809.92,1809.51,1808.12,1806.7,1808.76,1811.6,1813.18,1810.66,1811.41,1818.06,1821.32,1821.32,1826.13,1825.95,1825.8,1827.92,1834.11,1833.24,1837.92,1838.25,1837.15,1834.88,1829.73,1826.88,1826.67,1825.98,1823.64,1823.66,1823.5,1823.42,1821.01,1820.24,1820.9,1823.42,1823.66,1824.44,1824.46,1823.07,1823.07,1822.92,1823.16,1823.23,1822.66,1822.38,1821.67,1820.66,1820.86,1819.64,1820.04,1821.27,1821.97,1822.56,1822.84,1822.89,1823.11,1822.35,1823,1822.5,1823.95,1825.61,1828.4,1833.11,1829.66,1830.85,1831.78,1831.56,1830.53,1833.27,1830.39,1830.83,1830.49,1830.96,1827.29,1823.96,1822.81,1823.82,1826.15,1828.34,1829.33,1826.16,1825.49,1826.11,1825.58,1825.5,1825.24,1827.97,1828.87,1831.17,1831.47,1831.51,1830.92,1830.31,1829.28,1829.18,1828.05,1828,1829.58,1827.9,1831.79,1834.76,1836.23,1837.97,1837.6,1837.02,1837.41,1837.53,1837.81,1838.2,1837.69,1838.08,1837.18,1833.2,1833.83,1826.12,1828.7,1832.14,1833.13,1832.12,1807.2,1825.91,1832.12,1819.33,1823.37,1819.28,1815.05,1813.79,1811.23,1811.11,1811.4,1810.66,1810.77,1807.56,1804.32,1803.91,1804.52,1805.76,1805.12,1810.04,1813.61,1816.5,1818.08,1821.71,1822.16,1819.67,1821.57,1821.8,1821.91,1821.61,1822.47,1824.26,1823.72,1823.89,1822.36,1820.03,1820.87,1820.68,1819.38,1821.11,1824.18,1825.97,1825.55,1825.01,1823.82,1822.74,1826.86,1829.84,1826.97,1826.98,1827.75,1828.42,1827.72,1828.53,1845.99,1844.87,1855.19,1862.63,1860.7,1859.68,1860.08,1858.38,1851.44,1850.75,1850.09,1850.69,1851.06,1851.11,1851.04,1850.53,1849.94,1849.21,1848.75,1847.76,1848.45,1848.81,1848.08,1847.01,1847.31,1848.11,1848.52,1847.54,1848.91,1849.35,1849.51,1848.96,1846.93,1846.85,1845.87,1845.96,1846.93,1848.45,1850.12,1850.5,1850.26,1849.81,1853.99,1857.64,1858.98,1859.11,1854.58,1853.95,1853.42,1853.52,1853.08,1855.14,1874.48,1869.58,1869.21,1865.91,1865.18,1868.69,1867.64,1865.88,1863.29,1866.79,1867.05,1866.83,1866.34,1865.27,1864.1,1862.39,1860.99,1858.38,1855.46,1854.85,1851.77,1851.55,1850.73,1849.05,1847.52,1845.34,1843.79,1839.16,1840.99,1847.26,1852.2,1851.66,1852.82,1851.9,1851.6,1850.87,1851.27,1850.67,1849.9,1847.27,1843.1,1840.89,1840.03,1834.06,1833.41,1833.08,1831.93,1822.59,1830.69,1821.64,1816.45,1817.06,1828.57,1828.62,1822.96,1818.69,1820.81,1825.01,1824.57,1822.14,1822.33,1821.63,1820.78,1820.9,1818.84,1820.09,1818.94,1819.84,1820.52,1821,1822.62,1823.21,1823.09,1821.85,1820.52,1819.69,1818.23,1817.6,1817.59,1817,1819.71,1821.71,1824.83,1822.55,1824.6,1824.63,1828.09,1831.31,1830.55,1830.45,1828.53,1828.65,1828.84,1830.02,1830.07,1827.69,1829.16,1829.88,1829.86,1828.42,1829.14,1830.44,1830.44,1835,1838.72,1836.93,1837.41,1838.89,1846.53,1845.17,1847.72,1848.17,1844.47,1845.9,1846.82,1846.7,1844.5,1843.5,1842.16,1841.58,1839.34,1839.25,1838.86,1838.28,1838.64,1838.83,1839.2,1839.09,1836.14,1836.11,1836.46,1835.59,1835.36,1835.99,1835.48,1836.34,1835.2,1834.66,1834.39,1834.93,1835.14,1834.72,1833.79,1834.39,1832.99,1830.95,1828.19,1827.18,1826.59,1825.69,1822.9,1825.16,1827.74,1827.12,1827.12,1830.48,1827.95,1827.53,1827.12,1822.67,1824.76,1826.6,1825.52,1825.94,1825.05,1824.1,1823.7,1824.13,1823.95,1822.93,1823.16,1822.56,1822.02,1821.71,1820.71,1819,1816.04,1814.14,1814.99,1815.09,1815.49,1817.09,1818.55,1819.73,1825.83,1826.31,1828.11,1827.31,1824.56,1823.8,1823.66,1825.44,1827.21,1828.74,1829.06,1829.84,1830.04,1829.6,1834.09,1832.96,1833.63,1834.13,1833.13,1834.96,1830.66,1830.74,1828.6,1829.23,1829.23,1820.54,1820.91,1820.67,1822.34,1821.45,1821.05,1821.27,1822.44,1822.28,1821.51,1820.22,1817.08,1816.25,1815.13,1812.28,1812.76,1812.23,1814.3,1817.38,1817.72,1815.99,1814.74,1814.51,1814.52,1814.53,1814.42,1814.94,1814.46,1814,1813.49,1813.28,1813.3,1812.29,1812.89,1812.78,1814.15,1815.02,1814.8,1813.51,1813.08,1814.37,1815.49,1815.13,1813.79,1812.02,1809.54,1806.5,1805.86,1802.31,1796.65,1794.87,1794.22,1797.18,1795.21,1789.38,1787.72,1795.21,1794.81,1797.04,1799.1,1797.46,1794.16,1792.45,1789.89,1789.08,1787.99,1787.04,1784.69,1782.63,1787.63,1794.93,1792.96,1790.86,1792.61,1796.91,1796.98,1795.37,1794.05,1793.13,1794.48,1795.82,1795.05,1793.07,1790.8,1796.23,1796.24,1795.43,1794.86,1796,1795.59,1793.91,1790.9,1787.74,1784.08,1782.89,1783.15,1786.76,1786.52,1781.57,1781.91,1786.2,1789.2,1784.17,1784.24,1784.02,1788.23,1788.23,1789.91,1791.2,1799.66,1802.86,1801.56,1800.2,1801.05,1800.11,1799.16,1799.14,1799.34,1799.38,1801.76,1803.87,1805.43,1805.88,1806.02,1805.35,1805.3,1805.14,1804.71,1803.17,1800.98,1800.8,1801.33,1801.64,1801.58,1802.23,1802.39,1802.34,1802.42,1803.39,1803.78,1804.47,1805.82,1805.95,1805.48,1805.2,1805.16,1806.82,1808.17,1808.29,1808.31,1809.59,1810.99,1811.53,1812.07,1811.61,1813.94,1805.96,1810.83,1811.15,1811.15],
      "l": [1710.29,1723.18,1728.89,1732.62,1739.54,1736.07,1735.82,1734.81,1733.85,1733.41,1734.47,1739.4,1738.82,1733.85,1733.53,1732.67,1731.51,1731.4,1730.48,1729.02,1729.39,1729.63,1728.67,1727.49,1723.13,1718.33,1711.29,1713.14,1706.53,1710.07,1715.4,1714.31,1714.68,1716.57,1716.7,1721.31,1724.14,1722.01,1719.04,1720.28,1721.8,1722.78,1723.33,1724,1724.6,1728.73,1713.13,1713.83,1697.34,1696.59,1702.87,1701.87,1695.5,1695.24,1699.59,1702.64,1703.3,1700.19,1700.1,1697.65,1695.64,1695.6,1695.69,1696.33,1697.49,1697.43,1697.9,1698.6,1700.35,1701.45,1700.15,1698.12,1696.93,1696.13,1696.22,1698.48,1692.54,1691.23,1691.58,1691.39,1689.63,1689.21,1689.04,1690.85,1689.2,1687.13,1685.9,1686.42,1687.85,1691.61,1697.81,1698.19,1696.48,1695.5,1677.09,1697.96,1690.92,1679.52,1680.17,1683.21,1679.84,1678.11,1678.28,1680.05,1681.13,1681.27,1678.15,1676.99,1675.2,1674.99,1676.41,1677.33,1677.53,1679.3,1679.22,1680.13,1678.22,1677.75,1677.16,1676.85,1675.95,1675.65,1675.67,1676,1669.43,1671.07,1670.13,1664.28,1663.66,1665.63,1668.48,1670.77,1669.04,1666.79,1666.84,1664.02,1659.06,1660.26,1657.08,1660.2,1657.67,1653.76,1642.65,1647.16,1629.1,1627.47,1624.86,1626.11,1619.07,1612.38,1612.43,1611.65,1605.78,1595.59,1594.38,1606.76,1605.06,1603.39,1606.33,1608.67,1612.79,1610,1608.34,1604.14,1602.43,1599.21,1599.05,1605.23,1608.94,1614.14,1613.14,1613.57,1603.66,1609.98,1607.99,1603.6,1602.28,1600.74,1603.6,1603.89,1599.51,1594.49,1594.43,1595.26,1595.72,1598.28,1598.67,1588.69,1586.44,1591.02,1592.79,1591.17,1591.17,1612.54,1612.18,1615.51,1613.01,1613.1,1612.43,1613.04,1610.66,1610.59,1612.51,1612.32,1614.1,1618.87,1618.86,1618.97,1619.06,1621.2,1625.35,1628.93,1626.21,1625.23,1623.31,1622.99,1622.31,1621.77,1621.54,1622.69,1617.79,1618.54,1619.56,1619.85,1612.22,1611.46,1613.79,1612.51,1609.46,1604.27,1603.36,1606.37,1608.28,1608.2,1608.67,1604.6,1602.92,1606.26,1606.13,1614.08,1629.73,1642.88,1643.26,1649.4,1648.27,1644.74,1642.21,1642.72,1644.02,1644.15,1644.63,1644.55,1644.74,1646.61,1650.29,1650.78,1649.48,1648.05,1647.5,1646.93,1647.44,1646.88,1647.03,1646.42,1645.3,1644.81,1645.4,1645.76,1642.55,1643.74,1644.57,1645.99,1645.56,1645.3,1646.69,1649.02,1650.36,1649.29,1648.36,1646.98,1647.23,1644.6,1643.78,1645.71,1649.48,1652.71,1654.13,1658.19,1652.89,1651.85,1649.37,1644.01,1641.32,1641.89,1642.23,1641.36,1637.57,1636.84,1637.87,1639.08,1642.65,1643.54,1642.93,1643.57,1643,1642.48,1642.24,1642.33,1642.13,1641.96,1641.93,1641.31,1641.38,1640.79,1640.09,1640.38,1635.26,1634.55,1635.08,1635.77,1635.71,1636.23,1638.62,1636.17,1636.54,1637.1,1641.51,1643.1,1642.6,1644.14,1642.89,1643.29,1643,1643.3,1641.41,1644.2,1641.47,1640.31,1644.44,1642.52,1641.19,1641.9,1642.76,1643.52,1643.77,1652.58,1652.47,1651.21,1650.45,1650.37,1649.85,1650.44,1649.68,1648.94,1649.87,1648.97,1648.7,1647.73,1649.09,1650.88,1651.67,1651.1,1650.55,1652.89,1651.93,1650.64,1650.86,1653.22,1653.7,1656.8,1656.95,1657.28,1659.58,1661.67,1662.74,1661.9,1662.69,1664.82,1668.34,1669.21,1670.68,1671.48,1669.84,1672.8,1640.27,1640.29,1640.95,1641.47,1644.44,1643.47,1642.81,1643.14,1641.06,1641,1637.58,1637.91,1641.29,1646.26,1646.69,1650.35,1649.14,1649.2,1652.48,1652.11,1650.87,1649.94,1649.15,1648.82,1648.19,1648.71,1648.8,1650.15,1648.15,1648.89,1650.49,1651.27,1654.52,1656.71,1656.05,1657.93,1662.62,1663.41,1663.75,1667.41,1663.77,1662.84,1664.68,1667.04,1665.23,1657.1,1657.68,1662.21,1662.54,1667.15,1666.93,1667.23,1666.31,1666.78,1666.41,1667.01,1669.08,1669.71,1669.45,1673.43,1675.42,1674.54,1675.89,1676.44,1675.94,1676.09,1675.45,1674.95,1674.38,1672.52,1672.77,1672.49,1672.53,1673.28,1673.34,1673.64,1671.49,1673.63,1672.18,1669.26,1668.8,1669.15,1668.32,1668.03,1664.91,1664.34,1665.03,1666.4,1668.8,1667.86,1667.48,1667.17,1665.36,1666.15,1663.05,1669.72,1674.49,1710.46,1707.78,1707.26,1706.3,1706.62,1707.81,1709.54,1709.47,1711.03,1708.24,1708.93,1708.62,1708.29,1706.24,1705.74,1705.09,1704.56,1703.08,1703.05,1703.59,1704.49,1704.29,1703.62,1703.45,1702.95,1703.13,1704.9,1702.72,1701.9,1701.06,1700.18,1700.23,1703.79,1704.4,1704.83,1706.18,1709.14,1711,1708.2,1709.75,1707.89,1706.34,1705.79,1706.19,1706.3,1704.73,1702.93,1695.17,1694.72,1698.47,1694.9,1694.4,1693.52,1693.35,1695.95,1696.19,1697.2,1695.57,1695.14,1694.19,1692.52,1691.83,1691.99,1693.1,1695.27,1695.36,1697.68,1696.1,1696.05,1696.55,1695.88,1694.87,1694.67,1694.82,1694.77,1691.01,1690.92,1691.37,1692.45,1692.84,1691.31,1688.9,1686.21,1686.45,1687.86,1686.2,1684.47,1684.82,1688.89,1690.87,1690.41,1691.29,1691.7,1691.17,1694.82,1694.82,1702.99,1705.4,1707.46,1706.68,1706.39,1711.43,1708.33,1708.15,1708.81,1708.28,1707.81,1706.82,1705.6,1704.62,1701.69,1699.82,1698.29,1697.11,1697.99,1698.3,1698.81,1698.68,1698.93,1700.09,1699.67,1699.05,1699.34,1694.36,1693.77,1690.55,1688.65,1690.24,1688.2,1684.3,1683.38,1685.53,1683.76,1683.79,1685.29,1682.4,1681.48,1679.79,1680.19,1682.54,1682.49,1684.62,1684.04,1678.76,1676.17,1679.99,1683.1,1684.25,1690.83,1688.9,1686.66,1686.36,1684.65,1683.55,1680.82,1677.45,1673.83,1673.39,1676.21,1676.08,1675.59,1675.73,1675.31,1674.77,1675.54,1676.34,1677.84,1677.66,1676.36,1675.96,1676.09,1672.91,1675.14,1675.14,1676.69,1679.38,1679.44,1681.81,1681.91,1680.11,1678.67,1677.9,1677.78,1677.12,1672.74,1673.39,1674.41,1671.51,1669.31,1673.71,1672.72,1677.76,1677.15,1674.04,1669.96,1669.54,1672.47,1676.84,1678.31,1678.81,1680.12,1684.07,1686.53,1683.96,1683.99,1684.08,1683.48,1682.12,1681.4,1680.02,1678.46,1677.76,1678.35,1675.85,1674.41,1673.35,1671.89,1671.46,1672.93,1670.54,1671.23,1673.83,1673.13,1671.48,1670.96,1671.84,1671.71,1671.13,1668.58,1668.25,1667.42,1665.99,1665.51,1665.36,1665.93,1674.16,1676.81,1677.2,1677.08,1677.54,1723.63,1718.48,1713.51,1713.18,1712.41,1712.96,1714.65,1714.85,1717.27,1717.91,1720.06,1721.87,1723.75,1730.95,1730.74,1732.13,1734.29,1736.55,1734.83,1732.79,1732.53,1733.12,1733.23,1734.66,1735.6,1735.89,1736.2,1734.5,1736.35,1739.48,1740.01,1741.97,1744.22,1747.9,1747.94,1748.13,1748.91,1749.76,1752.12,1753.82,1753.94,1754.04,1754.08,1753.7,1753.66,1754.2,1755.53,1738.36,1743.65,1749.71,1746.98,1745.01,1746.62,1748.18,1750.01,1752.74,1752.25,1749.78,1746.36,1746.03,1746.14,1746.58,1746.92,1745.9,1744.76,1744.38,1743.53,1741.07,1739.67,1741.58,1742.32,1741.32,1740.75,1738.83,1738.93,1736.71,1739.26,1741.56,1743.16,1744.65,1744.51,1745.09,1746.16,1745.6,1744.34,1743.99,1745.21,1746.07,1748.37,1747.64,1746.55,1742.06,1739.85,1738.81,1736.68,1736.68,1756.05,1753.72,1754.81,1754.99,1757.41,1760.47,1758.55,1753.54,1753.13,1754.31,1755.98,1756.4,1756.44,1756.11,1755.22,1754.43,1754.54,1755.65,1755.47,1755.25,1757.34,1756.14,1755.93,1755.06,1754.4,1753.72,1754.25,1751.82,1753.88,1755.28,1754.4,1754.28,1756.12,1756.98,1758.32,1757.24,1756.71,1756.37,1756.47,1755.5,1755.08,1753.28,1752.47,1751.69,1748.96,1747.75,1749.73,1733.18,1733.7,1739.42,1736.75,1737.75,1742.24,1743.48,1743.37,1743.34,1745.54,1746.06,1744.91,1744.58,1744.75,1744.91,1745.3,1743.83,1742.97,1741.78,1741.39,1740.54,1740.34,1740.45,1740.43,1739.76,1739.86,1740.26,1741.94,1739.85,1741.81,1747.07,1746.93,1747.01,1748.37,1747.61,1747.69,1751.18,1752.38,1753.38,1755.88,1758.04,1758.96,1760.87,1761.27,1756.76,1756.57,1755.93,1758.96,1775.08,1779.42,1779.01,1780.53,1779.9,1779.78,1776.03,1776.49,1777.74,1775.25,1774.78,1776.05,1774.94,1773.77,1772.54,1771.99,1770.76,1772.09,1772.71,1772.74,1773.29,1771.69,1769.73,1768.3,1769.09,1768.05,1767.86,1769.65,1766.3,1768.16,1770.8,1768.25,1767.21,1765.52,1768.03,1767.27,1769.32,1769.05,1768.76,1769.19,1770.27,1769.25,1771.04,1770.08,1769.88,1768.94,1770.89,1774.53,1775.65,1787.94,1787.46,1788.81,1789.93,1789.43,1791.56,1791.2,1790.58,1789.9,1789.14,1788.59,1788.04,1787.84,1788.71,1789.76,1790.85,1792.47,1791.96,1791.34,1789.88,1789.32,1789.3,1789.51,1789.82,1790.63,1790.79,1791.66,1788.38,1788.78,1789.78,1790.84,1791.96,1792.79,1793.34,1791.75,1791.24,1793.36,1794.29,1793.4,1793.48,1796.96,1798.27,1799.13,1799.26,1799.5,1799.07,1800.65,1805.82,1807.19,1812.69,1811.2,1806.34,1805.81,1807.26,1802.3,1799.18,1802.91,1804.45,1804.19,1804.28,1805.15,1805.21,1806.22,1809.48,1813.62,1815.89,1815.37,1816.49,1818.83,1819.51,1819.52,1820.22,1818.77,1818.67,1818.74,1815.01,1817.49,1818.33,1818.43,1819.95,1820.45,1821.62,1822.05,1820.87,1819.78,1815,1814.56,1815.21,1815.34,1816.12,1817.73,1818.7,1818.87,1817.22,1819.83,1832.33,1835.51,1835.22,1837.15,1834.43,1822.15,1822.87,1814.47,1814.55,1826.62,1825.1,1829.06,1830.93,1832.03,1831.93,1829.27,1825.19,1823.81,1821.71,1820.7,1822.67,1824.47,1825.37,1826.44,1825.73,1825.08,1824.82,1825.72,1820.91,1821.54,1822.22,1825.11,1824.87,1826.61,1832.6,1831.08,1829.81,1827.27,1827.28,1827.6,1826.77,1825.1,1821.71,1821.48,1824.33,1820.91,1818.12,1817.17,1806.04,1804.22,1809.26,1812.64,1810.1,1807.71,1802.42,1804.36,1805.56,1806.13,1807.98,1808.24,1810.2,1812.74,1820.22,1822.03,1818.47,1818.77,1821.81,1823.23,1826.87,1829.06,1829.3,1828.57,1826,1825.07,1823.83,1826.33,1822.22,1821.28,1826.71,1827.8,1826.58,1825.07,1823.56,1824.76,1826.29,1827.32,1829.45,1827.25,1827.16,1826.24,1826.34,1829.38,1830.76,1830.97,1838.01,1832.81,1837.11,1858.81,1851.3,1850.8,1849.96,1850.83,1851.99,1857.17,1864.01,1857.53,1858.45,1858.76,1860.83,1863.83,1863.93,1863.01,1862.03,1859.56,1857.47,1857.52,1857.33,1856.57,1855.84,1856.16,1856.25,1856.21,1857.02,1858,1852.62,1851.47,1849.28,1843.03,1843.82,1846.97,1846.26,1846.29,1847.58,1847.11,1845.94,1846.42,1845.93,1843.7,1842.77,1842.11,1839.27,1836.13,1833.62,1833.48,1833.93,1829.2,1829.78,1831.65,1831.29,1832.31,1837.08,1835.75,1835.19,1833.57,1831.28,1830.87,1829.1,1828.94,1828.35,1828.05,1830.54,1828.65,1826.92,1826.65,1825.74,1825.09,1824.26,1823.59,1821,1819.21,1822.42,1825.08,1822.38,1826.77,1828.61,1830.12,1829.42,1829.87,1837.12,1840.63,1845.64,1855.27,1855.21,1857.47,1858.33,1856.04,1857.09,1856.67,1859.08,1859.73,1855.34,1857.27,1857.3,1868.09,1868.81,1872.03,1878.44,1872.2,1872.65,1875.73,1876.58,1878.11,1879.15,1885.87,1876.29,1880.9,1882.09,1877.45,1877.55,1877.08,1874.34,1874.69,1875.09,1876.18,1877.81,1878.08,1876.98,1875.71,1874.31,1874.63,1871.89,1870.26,1868.07,1867.64,1861.21,1859.52,1865.54,1860.9,1857.76,1859.09,1864.92,1861.87,1855.58,1855.09,1858.9,1863.99,1869.43,1874.24,1868.58,1870.36,1866.43,1864.67,1867.27,1867.71,1869.01,1871.7,1872.96,1872.54,1872.34,1876.86,1877.01,1872.69,1870.69,1870,1868.4,1867.04,1864.8,1862.89,1862,1863.19,1862.56,1859.76,1859.9,1862.75,1862.61,1862.31,1861.65,1862.41,1858.97,1853.35,1853.2,1855.67,1855.53,1854.2,1843.63,1847.91,1853.63,1855.39,1855.41,1856.96,1857.1,1858.01,1852.76,1852.83,1853.52,1853.69,1848.08,1853.29,1848.98,1858.74,1860.28,1864.78,1866.55,1868.08,1867.64,1865.09,1867.72,1867.52,1867.74,1870.36,1877.87,1878.77,1876.82,1875.31,1875.63,1882.3,1882.34,1883.25,1884.94,1886.66,1885.71,1883.17,1885.39,1886.45,1885.69,1886.05,1876.58,1870.64,1872.8,1872.3,1870.64,1869.3,1869.23,1872.4,1874.13,1875.87,1876.19,1877.96,1874.76,1874.3,1875.01,1876.88,1879.46,1867.75,1875.1,1875.84,1874.99,1876.93,1874.46,1873.18,1872.87,1866.75,1866.01,1866.75,1865.59,1864.69,1854.7,1862.4,1860.43,1858.45,1859.45,1860.8,1859.76,1859.65,1859.82,1861.58,1861.16,1859.82,1858.66,1858.31,1857.83,1858.66,1858.97,1858.98,1857,1857.32,1855.64,1854.36,1853.91,1855.86,1855.57,1856.07,1853.66,1857,1857.41,1854.26,1852.7,1853.34,1855.2,1856.54,1853.82,1852.49,1841.3,1854.1,1854.1,1872.14,1870.12,1870.85,1871.02,1875.03,1871.74,1870.84,1868.33,1867.2,1863.28,1864.04,1866.56,1858.56,1858.9,1858.05,1856.1,1856.05,1856.84,1855.07,1854.57,1849.53,1847.54,1852.42,1854.68,1855.8,1855.28,1855.66,1847.44,1840.43,1841.9,1843.28,1845.59,1844.93,1846.29,1853.88,1850.77,1848.1,1848.75,1850.92,1850.6,1854.46,1856.48,1858.07,1856.61,1852.04,1849.7,1853.19,1850.45,1851.07,1849.41,1849.32,1854.43,1859.8,1859.63,1853.39,1853.09,1852.26,1852.69,1854.24,1854.98,1855.1,1854.68,1854.47,1854.33,1858.23,1861.7,1864.18,1868.07,1866.86,1867.34,1871.83,1872.88,1868.78,1867.8,1869.02,1860.3,1862.01,1862.56,1863.21,1863.26,1864.84,1863.9,1861.79,1864.32,1865.52,1865.7,1866.58,1870.91,1873.39,1873.07,1873.54,1872.79,1872.05,1872.69,1873.31,1874.85,1882.12,1881.77,1881.76,1880.98,1875.71,1875.6,1879.24,1878.66,1875.57,1872.66,1870.14,1870.45,1873.19,1872.72,1872.1,1871.98,1869.71,1869.34,1869.82,1870.61,1871.58,1870.83,1870.75,1871.41,1871.22,1871.79,1872.19,1869.11,1868.92,1871.8,1874.24,1874.43,1877.94,1877.71,1877.62,1877.41,1877.37,1879.74,1883.12,1885.5,1887.66,1887.87,1886.65,1886.3,1887.55,1888.01,1891.2,1891.2,1900.09,1896.55,1896.88,1901.46,1902.21,1901.2,1901.28,1900.8,1902.05,1900.76,1899.09,1899.09,1899.17,1900.26,1902.17,1902.1,1904.92,1907.32,1907.66,1907.87,1906.19,1905.82,1905.13,1905.03,1905.56,1905.52,1906.4,1903,1903.92,1912.37,1917.8,1917.1,1916.93,1916.93,1915.23,1916.08,1913.44,1910.93,1913.51,1904.21,1902.08,1906.4,1907.11,1908.89,1910.41,1907.47,1909.01,1903.18,1904.01,1903.87,1903.22,1898.72,1897.74,1900.61,1900.69,1901.77,1902.31,1901.65,1901.63,1902.12,1902.54,1903.36,1903.13,1903.25,1902.44,1901.28,1901.03,1901.07,1897.74,1897.43,1900.01,1900.05,1900.38,1899.15,1899.74,1897.06,1899.12,1903.41,1908.51,1912.88,1911.8,1912.28,1914.42,1918.87,1917.75,1914.72,1912.96,1912.9,1905.77,1903.18,1904.03,1907.24,1907.35,1907.3,1915.26,1914.04,1922.48,1923.13,1922.94,1921.44,1919.65,1917.3,1917.28,1919.4,1919.38,1919.78,1921.06,1920.55,1920.75,1922.16,1920.91,1919.43,1919.54,1920.64,1922.36,1923.08,1921.29,1920.44,1919.76,1919.46,1920.48,1920.02,1921.29,1917.76,1917.98,1918.48,1919.83,1919.96,1914.47,1915.68,1910.95,1909.62,1910.82,1909.42,1910.6,1909.68,1905.44,1906.44,1903.56,1895.96,1893.75,1895.44,1895.5,1890.9,1889.63,1888.71,1892.92,1896.1,1896.59,1894.85,1891.8,1890.75,1891.27,1891.04,1891.28,1891.6,1893.34,1893.13,1892.71,1891.25,1890.38,1888.94,1888.36,1888.85,1888.45,1887.81,1885.53,1883.14,1880.7,1878.73,1879.82,1875.25,1878.34,1880.73,1878.65,1879.5,1880.78,1881.74,1882.05,1886.04,1888.59,1892.92,1898.8,1898.56,1901.47,1899.77,1899.4,1900.73,1898.71,1882.58,1901.1,1900.2,1898.32,1898.48,1897.73,1895.15,1892.07,1892.15,1891.03,1891.14,1892.02,1894.25,1894.29,1894.82,1896.01,1895.63,1894.28,1894.21,1894.4,1892.84,1892.77,1892.3,1890.97,1890.59,1890.24,1891.33,1890.92,1891.13,1892.75,1888.97,1888.76,1889.69,1890.59,1890.12,1888.97,1879.78,1882.01,1876.84,1871.75,1871.18,1866.52,1865.12,1868.02,1866.96,1871.33,1882.01,1888.15,1887.34,1897.61,1890.27,1887.75,1883.98,1889.65,1896.78,1899.71,1897.55,1898.95,1897.04,1894.22,1894.05,1893.94,1896.47,1899.72,1901.56,1902.88,1906.51,1907.49,1907.13,1909.35,1913.13,1916.77,1915.04,1914.79,1915.02,1916.26,1914.98,1918.51,1914.24,1915.68,1919.54,1916.04,1917.96,1917.27,1915.42,1916.7,1916.45,1916.88,1919.12,1919.87,1919.88,1916.92,1916.52,1914.43,1917.17,1917.81,1925.05,1925.46,1924.23,1926.18,1926.25,1924.27,1920.96,1917.76,1916.85,1916.35,1915.33,1915.44,1917.44,1914.59,1915.79,1915.25,1914.46,1914.4,1915.71,1916.18,1918.07,1917.06,1917.86,1917.17,1917.77,1917.79,1918.05,1918.61,1920.31,1921.98,1913.25,1909.9,1911.91,1911.01,1910.44,1910.96,1913.89,1914.26,1913.07,1913.99,1914.7,1915.04,1916.08,1918.74,1919.29,1920.82,1916.66,1918.77,1910.14,1921.6,1909.8,1911.75,1914.29,1914.26,1915.95,1917.35,1914.88,1914.72,1913.94,1914.18,1911.88,1909.73,1909.48,1908.78,1911.35,1912.04,1911.83,1912.15,1912.4,1912.29,1912.85,1913.36,1913.44,1913.11,1914.18,1916.87,1920.31,1920.76,1918.54,1916.53,1915.66,1912.55,1914.02,1914.9,1916.93,1919.5,1918.78,1919.79,1923.59,1923.17,1922.94,1924.27,1923.26,1923.33,1925.37,1926.37,1924.64,1927.94,1927.02,1926.44,1925.04,1922.25,1917.02,1919.96,1923.35,1923.18,1924.55,1924.02,1923.84,1923.49,1923.21,1921.38,1921.76,1921.1,1920.67,1920.1,1920.1,1920.35,1920.11,1922.51,1923.02,1923.58,1924.06,1925.22,1921.54,1922.7,1917.71,1916.75,1919.43,1919.06,1915.56,1914.07,1910.92,1904.47,1909.87,1914.4,1913.95,1917.43,1916.56,1914.07,1912.53,1908.18,1908.46,1911.23,1905.14,1912.93,1906.43,1909.32,1914.58,1914.86,1917.43,1918.04,1914.97,1913.54,1912.9,1908.91,1911.3,1911.19,1914.4,1914.97,1914.94,1914.71,1914.49,1910.83,1908.44,1905.02,1904.32,1902.31,1898.21,1895.76,1896.59,1894.15,1882.13,1881.87,1859.22,1861.83,1877.01,1881.21,1885.74,1885.85,1888.23,1897.26,1899.93,1895.39,1894.95,1896.95,1899.94,1898.41,1898.33,1901.31,1904.71,1908.95,1903.12,1910.01,1913.23,1907.89,1903.49,1901.52,1902.62,1902.35,1901.73,1901.75,1901.73,1903.03,1904.2,1903.95,1901.49,1901.37,1903.24,1905.1,1902.54,1898.1,1896.72,1892.33,1887.2,1886.62,1888.17,1888.54,1891.46,1893.73,1895.77,1898.51,1890.36,1891.68,1890.75,1890,1892.03,1891.26,1890.92,1892.64,1896.55,1896.34,1895.79,1896.15,1897.04,1899.63,1901.88,1895.37,1894.46,1894.9,1894.38,1896.89,1882.62,1882.78,1880.2,1871.74,1871.45,1873.14,1879.35,1880.86,1882.15,1882.32,1882.36,1878.94,1877.09,1873.35,1873.12,1873.88,1871.99,1870.68,1869.25,1867.82,1866.45,1864.1,1861.29,1858.56,1856.09,1856.08,1863.39,1864.97,1860.17,1863.86,1869.76,1868.92,1868.94,1868.13,1866,1867.38,1868.51,1872.28,1874.39,1873.26,1871.18,1866.22,1868.04,1868.61,1872.43,1873.52,1872.86,1875.57,1876.37,1879.38,1877.6,1880,1885.21,1886.95,1885.57,1884.4,1884.55,1884.66,1882.83,1883.29,1885.33,1884.88,1884.4,1884.41,1885.86,1887.33,1885.97,1884.7,1883.31,1882.57,1882.02,1880.68,1880.23,1879.4,1879.23,1879.14,1877.51,1880.63,1881.9,1885.55,1886.9,1886.82,1886.05,1886.41,1885.66,1885.48,1883.97,1881.47,1881.98,1881.95,1879.48,1878.87,1877.36,1878.62,1879.11,1886.03,1885.69,1885.67,1885.77,1886.15,1884.45,1880.52,1882.1,1884.01,1884.03,1884.28,1885.62,1886.03,1884.82,1884.08,1882.81,1882.3,1881.3,1881.19,1882.42,1882.56,1882.53,1882.6,1882.24,1881.69,1881.57,1881.54,1880.66,1880.89,1877.68,1877.55,1877.18,1876.32,1876.39,1876.59,1878.55,1880.15,1880.88,1879.86,1879.02,1878.98,1879.31,1880.85,1882.79,1882.28,1883.18,1884.63,1884.57,1884.18,1878.47,1877.95,1878.27,1878.74,1878.68,1879.43,1877.87,1875.81,1870.44,1869.83,1866.01,1865.81,1869.21,1872.01,1873.59,1872.16,1871.24,1871.68,1871.94,1873.34,1872.67,1872.67,1872.65,1871.88,1869.35,1868.34,1868.33,1868.43,1865.19,1865.35,1867.58,1865.69,1865.53,1867.48,1867.76,1865.21,1863.18,1865.32,1872.12,1870.2,1868.73,1871.86,1872.33,1870.94,1868.79,1869.52,1865.83,1870.46,1866.89,1870.39,1874.15,1876.07,1878.46,1872.9,1872.79,1873.89,1871.15,1870.53,1869.16,1866.4,1867.78,1868.34,1869.79,1868.59,1864.99,1862.54,1860,1860.6,1857.25,1858.64,1857.93,1857.51,1858.19,1859.17,1858.89,1859,1858.08,1858.32,1858.18,1858.5,1857.6,1859.66,1861.44,1865.54,1866.92,1867.51,1870.78,1870.45,1870.41,1877.71,1877.96,1877.21,1874.55,1871.96,1867.81,1863.67,1862.97,1862.05,1861.15,1862.01,1861,1858.98,1860.5,1862.02,1863.15,1863.9,1862.78,1862.35,1862.38,1862.45,1860.77,1859.15,1857.83,1856.97,1856.51,1858.14,1857.86,1857.92,1856.89,1856.91,1856.13,1855.96,1859.1,1863.23,1862.16,1861.24,1861.26,1861.99,1862.11,1865.1,1867.21,1867.28,1869.65,1870.61,1868.28,1865.97,1865.85,1864.02,1864.67,1866.98,1864.79,1862.19,1861.38,1863.44,1863.49,1866.07,1866.79,1866.63,1867.04,1867.57,1868.12,1867.43,1866.04,1862.92,1862.51,1861.8,1861.96,1860.47,1858.14,1858.23,1858.02,1855.88,1854.44,1853.54,1852.56,1851.12,1851.37,1852.22,1851.17,1851.14,1852.53,1853.04,1849.29,1848.71,1849.49,1849.13,1848.86,1847.68,1847.37,1847.01,1848.3,1847.09,1844.14,1842.56,1845.2,1847.81,1848.29,1846.15,1841.52,1841.39,1841.32,1844.54,1840.31,1841.37,1843.62,1844.02,1845.65,1850.15,1854.09,1850.44,1850.89,1850.96,1849.95,1850.27,1847.78,1844.69,1844.48,1844.73,1843.89,1842.2,1842.51,1841.73,1839.72,1839.51,1839.94,1838.89,1836.66,1836.23,1835.27,1836.1,1832.86,1829.94,1832.9,1834.87,1835.2,1832.44,1832.54,1834.04,1833.49,1829.88,1827.88,1824.93,1824.31,1827.79,1827.64,1827.67,1824.45,1824.08,1822.4,1826.27,1824.12,1823.15,1820.06,1815.84,1815.13,1810.62,1808.34,1807.68,1807.18,1809.29,1809.12,1809.68,1811.34,1809.21,1803.97,1801.16,1801.57,1798.05,1800.12,1801.17,1801.91,1802.74,1804.14,1804.33,1809.7,1809.38,1809.2,1809.26,1807.41,1808.48,1807.91,1808.12,1809.26,1813.96,1814.77,1821.98,1824.72,1826.23,1828.89,1824.78,1825.42,1824.73,1825.67,1822.47,1819.39,1816.21,1812.08,1817.98,1812.73,1812.65,1816.29,1820.3,1823.52,1822.58,1822.91,1821.59,1818.87,1818.09,1819.82,1820.57,1818.65,1817.18,1817.34,1817.5,1817.74,1817.78,1820.84,1818.87,1818.76,1817.65,1817.41,1817.76,1817.33,1817.57,1818.14,1818.66,1817.1,1817.78,1820.96,1824.01,1821.49,1821.22,1822.33,1825.94,1827.51,1826.64,1826.61,1826.59,1827.45,1827.36,1827.13,1828.12,1829.38,1828.98,1826.91,1831.55,1831.55,1837.95,1836.54,1838.64,1841.31,1841.29,1841.35,1840.66,1840.62,1840.17,1839.5,1838.54,1837.15,1838.08,1839.57,1839.95,1840.84,1842.54,1841.67,1841.73,1841.47,1841.48,1841.93,1842.19,1843.74,1845.38,1843.33,1843.09,1839.81,1838.75,1838.54,1839.95,1838.07,1838.77,1840.95,1839.17,1840.03,1839.39,1838.94,1839.71,1839.71,1838.55,1837.33,1835.73,1836,1840.46,1830.4,1838.9,1818.06,1820.1,1815.84,1810.99,1809.53,1809.09,1809.91,1816.03,1818.04,1819.03,1812.8,1808.46,1809.56,1808.91,1808.75,1809.62,1810.21,1809.93,1809.81,1809.09,1807.93,1806.03,1804.6,1803.18,1802.35,1800.86,1798.28,1799.22,1795.23,1795.81,1798.33,1800.43,1800.4,1799.8,1797.34,1799.59,1798.77,1799.76,1799.36,1796.64,1794.87,1790.33,1789.31,1793.82,1793.78,1792.6,1790.16,1790.53,1790.53,1796.75,1794.5,1795.96,1795.71,1797.26,1797.3,1795.41,1793.54,1791.47,1788.42,1786.97,1784.59,1780.71,1781.43,1782.75,1784.56,1785.81,1786.91,1788.38,1789.01,1793.25,1793.14,1792.59,1792.6,1792.46,1790.64,1792.6,1790.42,1789.84,1788.96,1788.45,1789,1789.75,1786.76,1785.6,1785.64,1786.3,1787.06,1787.47,1789.61,1793.09,1791.53,1791.14,1791.07,1790.93,1790.35,1793.05,1789.56,1789.48,1790.42,1792.95,1793.9,1795.5,1794.34,1793.3,1790.7,1790.55,1791.3,1790.64,1790.17,1790.42,1792.58,1794.89,1797.3,1797.05,1797.21,1797.88,1799.14,1799.76,1801.34,1801.15,1801.08,1801.08,1800.56,1801.26,1797.96,1797.83,1797.89,1797.56,1796.55,1796.49,1795.3,1795.2,1795.8,1796.86,1797.51,1797.06,1797.86,1798.47,1799.83,1801.35,1802.75,1803.06,1799.33,1803.71,1789.12,1789.56,1792.45,1791.34,1789.19,1788.64,1789.46,1790.33,1791.4,1792.01,1792.35,1793.2,1793.18,1792.83,1791.96,1791.39,1792.11,1792,1794.21,1794.3,1795.77,1797.26,1797.37,1795.46,1795.27,1795.02,1796.19,1796.99,1794.64,1793.85,1794.15,1796.09,1796.43,1796.62,1799.47,1799.11,1797.91,1797.33,1796.71,1796.05,1795.72,1797.95,1800.29,1800.6,1799.26,1797.11,1795.35,1797.96,1798.61,1808.61,1804.43,1803.9,1805.38,1805.31,1804,1804.33,1803.04,1803.01,1802.83,1803.76,1807.14,1806.18,1805.16,1804.12,1802.71,1802.49,1802.53,1802.63,1803.06,1802.4,1802,1801.84,1801.99,1800.86,1801.71,1803.19,1801.19,1800.87,1801.74,1802.21,1802.11,1802.64,1802.89,1804.71,1805.33,1804.75,1803.76,1803.36,1800.43,1799.54,1797.9,1794.36,1788.8,1789.79,1788.96,1790.25,1803.62,1806.49,1808.43,1806.12,1804.06,1797.61,1796.52,1796.62,1792.37,1792.84,1780.02,1780.7,1775.72,1777.58,1777.72,1775.85,1779.15,1786.58,1788.95,1792.22,1791.65,1790.97,1792.31,1790.01,1789.74,1792.58,1792.28,1794.58,1791.74,1790.61,1792.83,1796.38,1797.66,1800.39,1799.88,1798.41,1794.71,1794.16,1793.35,1792.64,1794.97,1796.26,1795.05,1794.83,1794.73,1794.96,1796.67,1799.28,1803.87,1806.29,1806.04,1799.31,1806.25,1801.17,1799.86,1804.47,1805.6,1805.01,1806.52,1806.4,1806.2,1805.31,1805.49,1805.14,1803.9,1802.98,1803.08,1804.41,1803.73,1803.51,1803.6,1803.96,1803.68,1803.41,1802.9,1802.68,1803.79,1804.6,1805.96,1803.87,1803.8,1803.46,1803.73,1804.01,1805.8,1805.97,1805.43,1805.45,1805.55,1805.1,1805.04,1804.98,1803.94,1804.16,1804.38,1804.66,1805.05,1806.04,1806.75,1807.94,1807.94,1806.44,1805.58,1797.41,1798.11,1801.12,1799.73,1800.32,1800.89,1803.48,1804.68,1806.08,1805.66,1803.92,1802.54,1800.98,1798.81,1795.75,1795.3,1795.72,1796.03,1795.17,1794.18,1793.82,1792.64,1791.92,1792.46,1791.1,1790.17,1789.74,1790.11,1787.89,1788.1,1789.33,1794.66,1793.63,1793.01,1796.92,1799.91,1799.74,1800.11,1802.22,1804.28,1804.19,1806.42,1806.32,1805.73,1804.91,1804.95,1803.97,1804.84,1806.13,1806.02,1806.2,1836.95,1806.2,1822.65,1825.44,1824.17,1825.22,1828.25,1831.5,1832.02,1832.27,1832.58,1833.24,1833.34,1834.36,1834.87,1835.09,1834.39,1833.99,1834.11,1834.67,1834.41,1834.49,1834.13,1833.47,1833.61,1834.5,1834.62,1834.13,1835.42,1833.67,1833.83,1833.85,1834.27,1833.93,1833.63,1834.05,1833.85,1833.75,1833.16,1832.18,1832.36,1831.53,1831.8,1832.22,1831.51,1831.56,1832.02,1825.06,1825.84,1827.19,1830.47,1830.47,1839.29,1830.47,1832.43,1826.02,1826.81,1829.99,1831.1,1831.51,1832.05,1830.71,1830.02,1829.8,1827.51,1826.15,1825.51,1825.73,1825.83,1826.79,1826.12,1826.08,1826.88,1827.73,1828.63,1828.45,1827.95,1827.73,1827.18,1826.95,1827.41,1823.67,1824.23,1824.19,1824.57,1825.11,1826.91,1827.29,1825.9,1826.65,1826.33,1825.85,1825.65,1826.06,1825.93,1825.67,1824.8,1822.47,1823.41,1798.56,1813.02,1824.21,1824.53,1829.39,1829.45,1829.55,1822.58,1823.46,1827.67,1828.89,1834.62,1833.05,1829.95,1828.61,1826.66,1827.07,1828.3,1830.8,1831.25,1831.71,1838.7,1842.2,1842.45,1847.37,1849.51,1849.71,1850.39,1850.32,1850.94,1851.61,1854.69,1855.02,1855.57,1856.81,1855.25,1855.44,1855.64,1856.67,1857.7,1858.28,1857.29,1857.11,1857.08,1856.92,1856.22,1856.2,1856.3,1856.89,1857.11,1857.98,1858.65,1859.07,1855.5,1855.27,1857.77,1857.91,1875.73,1872.73,1857.91,1879.1,1876.86,1876.28,1876.37,1878.22,1876.31,1873.83,1872.42,1870.15,1867.77,1868.21,1868.49,1868.89,1868.42,1868.31,1868.23,1867.98,1867.73,1866.78,1867.24,1870.83,1871.07,1871.4,1871.85,1872.49,1874.29,1878.14,1877.9,1882.12,1882.39,1884.65,1884.84,1883.86,1880.14,1879.52,1878.99,1878.76,1876.51,1874.31,1873.84,1872.93,1872.43,1869.4,1866.73,1863.51,1862.3,1865.23,1869.04,1871.18,1872.85,1867.64,1873.38,1877.16,1880.44,1882.81,1883.71,1885.83,1884.49,1881.12,1880.93,1880.23,1877.57,1877.84,1878.29,1878.72,1878.32,1875.65,1873.05,1872,1870.72,1869.38,1867.38,1865.27,1862.5,1861.72,1863.6,1864.06,1865.69,1862.64,1863.7,1867.95,1871.01,1873.05,1870.8,1869.99,1871.56,1873.11,1874.51,1874.75,1875.16,1875.32,1878.39,1880.4,1882.28,1881.89,1881.71,1876.74,1878.16,1879.07,1878.02,1878.02,1886.15,1879.86,1871.75,1871.11,1867.55,1867.93,1870.5,1869.16,1868.98,1869.2,1869.22,1867.87,1867.17,1866.51,1865.83,1863.21,1865.34,1864.04,1864,1863.44,1861.54,1860.71,1859.55,1858.68,1857.37,1858.45,1861.42,1861.62,1860.39,1861.84,1859.23,1860.59,1861.67,1861.65,1867.84,1865.51,1866.08,1864.29,1862.27,1861.8,1862.42,1862,1862.25,1860.26,1857.23,1856.3,1858.34,1860.75,1857.25,1853.1,1853.79,1861.79,1863.07,1851.12,1857.9,1857.24,1860.4,1864.35,1866.2,1867.32,1867.47,1867,1865.41,1864.9,1862.93,1860.41,1858.27,1858.51,1860.9,1864.6,1861.98,1860.54,1860.28,1860.06,1859.05,1858.57,1858.21,1858.56,1857.95,1857.03,1856.15,1855.9,1855.99,1854.94,1857.78,1858.08,1859.4,1859.56,1861.86,1860.54,1859.36,1858.95,1860.74,1864.13,1865.2,1865.37,1863.4,1862.25,1862.51,1863.03,1866.19,1865.2,1863.18,1863.59,1867.8,1871.91,1868.86,1865.77,1866.21,1860.66,1862.33,1860.37,1861.66,1862.09,1862.12,1860.76,1860.69,1860.69,1861.03,1861.76,1861.78,1861.4,1860.47,1859.37,1858.23,1858.27,1858.39,1859.13,1859,1858.36,1857.32,1857.28,1856.84,1856.61,1856.74,1856.45,1856.04,1854.35,1854.39,1854.66,1857.28,1859.35,1859.32,1859.83,1859,1857.82,1854.69,1855.89,1857.76,1856,1855.18,1852.71,1852.2,1850.86,1849.72,1850.51,1854.97,1854.97,1853.87,1844.66,1850.2,1852.87,1853.56,1851.41,1850.43,1849.16,1848.62,1848.27,1848.64,1847.78,1850.97,1854.04,1854.03,1853.94,1856.32,1854.84,1855.27,1857.34,1857.17,1856.91,1856.48,1856.99,1856.96,1856.42,1856.59,1857.34,1858.52,1858.12,1859.05,1858.85,1858.54,1858.91,1860.02,1858.92,1860.02,1860.04,1859.93,1860.63,1860.15,1860.26,1859.41,1858.26,1856.76,1856.7,1857.21,1852.03,1852.72,1853.38,1857.95,1860.01,1860.9,1860.88,1859.95,1859.68,1862.49,1863.48,1863.44,1864.47,1864.54,1864.58,1864.19,1864.27,1864.57,1865.43,1865.57,1865.66,1866.53,1867.55,1868.52,1869.81,1867.87,1866.84,1866.29,1865.43,1865.22,1864.97,1864.67,1864,1864.27,1869.34,1868.38,1868.98,1869.01,1870.61,1869.5,1868.48,1866.6,1866.31,1865.73,1864.99,1864.71,1865.34,1865.45,1865.74,1866.6,1867,1866.74,1866.6,1863.44,1863.94,1863.9,1867.21,1867.21,1868.85,1868.33,1868.99,1870.23,1870.68,1870.37,1868.33,1865.9,1866.01,1865.73,1866.42,1867.15,1867,1866.68,1865.91,1866.05,1866.02,1864.56,1863.91,1864.12,1864.04,1865.77,1867.77,1869.66,1869.67,1869.23,1869.25,1869.44,1868.79,1869.42,1867.6,1867.59,1867.52,1867.39,1867.23,1867.32,1866.94,1867.03,1867.63,1867.75,1865.51,1865.21,1864.33,1864.38,1863.84,1863.75,1866.23,1869.57,1868.85,1863.32,1866.34,1866.35,1867.92,1867.08,1865.98,1866.53,1866.46,1866.43,1866.2,1867.01,1869.57,1867.92,1866.91,1865.16,1863.74,1863.59,1863.21,1863.28,1863.49,1862.98,1863.24,1862.3,1861.45,1860.28,1859.21,1859.39,1859.67,1859.65,1859.76,1859.06,1858.52,1859.09,1857.77,1857.28,1857.77,1857.73,1858.91,1858.85,1859.01,1859.61,1860.11,1862.16,1863.32,1863.86,1863.98,1863.61,1863.3,1862.88,1862.28,1861.85,1859.91,1859.52,1859.6,1862.08,1862.08,1879.13,1862.08,1869.77,1868.29,1866.99,1868.18,1868.13,1865.62,1863.09,1860.16,1858.61,1856.94,1857.72,1861.44,1861.9,1861.11,1859.76,1860.11,1860.41,1859.69,1859.57,1859.61,1859.76,1859.87,1859.97,1860.77,1860.43,1859.87,1860.16,1858.65,1858.89,1859.26,1859.79,1859.56,1858.7,1858.54,1857.03,1857.01,1856.68,1856.54,1854.16,1848.45,1847.24,1847.72,1837.4,1829.05,1839,1838.39,1839.44,1842.24,1843.5,1840.56,1838.53,1843.69,1842.07,1840.73,1840.52,1842.32,1841.7,1841.12,1838.11,1836.14,1833.54,1833.76,1835.66,1835.18,1834.43,1833.76,1833.99,1833.3,1831.79,1831.03,1828.38,1829.94,1829.58,1828.23,1826.82,1826.46,1826.73,1827.82,1825.79,1831.35,1832.62,1834.33,1836.43,1837.4,1838.51,1837.42,1836.35,1836.67,1839.57,1838.66,1839.01,1839.52,1840,1840.79,1842.93,1844.78,1844.29,1844.23,1844.57,1848.12,1848.25,1844.23,1846.58,1847.93,1848.3,1848.31,1846.97,1845.84,1845.22,1844.86,1842.98,1842.19,1844.35,1844.66,1845.3,1848.29,1850.03,1850.32,1849.59,1849.77,1850.33,1854.62,1854.51,1852.7,1852.44,1852.26,1851.52,1851.15,1851.2,1851.68,1849.93,1849.64,1849.9,1850.14,1849.9,1850.64,1851.82,1852.21,1853.13,1852.9,1853.36,1852.36,1852.72,1851.49,1850.58,1850.76,1852.29,1852.48,1850.38,1853.7,1853.7,1841.84,1841.87,1847.04,1848.69,1848.9,1848.96,1848.34,1847.38,1845.74,1844.15,1844.09,1843.82,1841.77,1841.55,1841.54,1842.99,1843.84,1843.64,1843.41,1844.4,1845.08,1845.5,1845.51,1845.3,1845.12,1844.44,1844.29,1844.3,1844.75,1843.77,1843.26,1843.31,1843.87,1844.49,1844.1,1844.39,1844.7,1843.91,1842.74,1842,1842.25,1843.17,1842.16,1841.84,1841.46,1841.07,1841.28,1839.43,1838.4,1839.09,1840.7,1840.7,1840.13,1840.27,1843.47,1841.58,1839.39,1838.37,1837.27,1836.5,1837.68,1837.91,1837.62,1837.74,1837.67,1837.2,1836.87,1836.78,1836.51,1836.03,1836.15,1835.54,1834.26,1834.29,1834.52,1834.35,1834.05,1834.01,1834,1833.23,1833.18,1831.97,1832.53,1833.14,1833.28,1833.6,1834.04,1839.47,1837.7,1837.54,1838.15,1838.57,1836.62,1834.81,1833.88,1834.03,1834.6,1830.34,1830.06,1825.04,1825.99,1824.71,1828.34,1828.34,1831.39,1817.33,1818.35,1820.98,1819.56,1817.6,1816.04,1815.6,1815.02,1814.92,1815.57,1814.02,1809.98,1809.75,1809.95,1808.96,1809.14,1810.57,1811.28,1812.01,1811.59,1811.25,1808.42,1805.34,1803.72,1802,1797.72,1799.2,1801.51,1799.94,1803.22,1804.83,1803.71,1803.88,1804.5,1804.56,1803.18,1799.32,1793.36,1790.77,1794.12,1788.52,1789.88,1792.29,1782.47,1781.45,1790.81,1790.34,1789.58,1788.56,1796.97,1800.54,1789.17,1790.65,1793.11,1794.11,1796.94,1792.9,1788.01,1787.74,1788.87,1787.66,1784.75,1782.89,1780.18,1778.08,1774.55,1774.22,1775.05,1778.78,1776.87,1776.62,1778.31,1780.59,1783.09,1782.11,1781.44,1780.67,1780.78,1781.22,1781.72,1782.45,1781.95,1786.16,1788.53,1794.5,1795.76,1794.53,1794.26,1797.72,1798.9,1797.47,1796.76,1797.7,1796.9,1798.95,1798.02,1799.57,1801.12,1801.7,1796.07,1802.79,1806.63,1806.63,1805.55,1796.24,1793.84,1793.84,1793.25,1792.81,1788.86,1785.43,1784.64,1785.63,1784.97,1784.83,1783.64,1783.39,1783.51,1781.11,1779.35,1785.06,1787.55,1787.94,1788.26,1788.37,1787.98,1787.88,1788.17,1788.08,1788.8,1790.79,1791.07,1789.29,1788.73,1787.99,1786.16,1785.69,1785.96,1785.08,1785.06,1785.86,1782.56,1782.89,1784.19,1784.43,1786.4,1786.15,1781.17,1776.83,1777.84,1778.25,1776.32,1775.96,1782.12,1782.12,1765.01,1768.2,1776.48,1778.34,1777.88,1778.24,1782.41,1781.85,1778.68,1776.95,1776.89,1774.25,1773.39,1771.81,1768.55,1765.93,1767.75,1768.28,1766.57,1764.65,1762.35,1761.07,1762.95,1761.83,1760.38,1760.67,1765.2,1764.9,1765.97,1764.07,1764.11,1762.39,1759.82,1757.42,1758.79,1760.77,1763.91,1770.22,1771.24,1779.56,1780.88,1783.15,1785.19,1789.4,1792.18,1796.42,1796.51,1790.4,1794.46,1791.64,1804.24,1804.24,1798.01,1801.02,1796.65,1791.93,1794.96,1794.97,1795.66,1795.08,1794.68,1793.53,1791,1790.28,1790.83,1792.72,1792.81,1791.36,1791.27,1791.03,1790.94,1789.83,1789.95,1790.74,1790.76,1792,1792.59,1794.7,1794.72,1796.68,1792.94,1790.22,1790.53,1793.22,1792.49,1793.81,1792.91,1794.05,1793.49,1793.11,1792.84,1792.38,1791.99,1793.01,1790.75,1789.49,1789.52,1790.02,1779.86,1782.12,1787.45,1787.45,1779.17,1781.52,1779.42,1776.17,1776.92,1777.69,1777.84,1779.2,1779.14,1778.65,1777.34,1776.17,1772.1,1770.38,1770.02,1770.66,1771.29,1771.3,1769.82,1767.42,1765.35,1765.01,1760.61,1758.76,1756.35,1753.86,1753.27,1753.25,1754.38,1750.2,1753.84,1754.17,1751.63,1750.34,1748.27,1746.07,1745.9,1745.84,1746.9,1753.83,1753.52,1750.95,1750.76,1746.77,1740.05,1736.43,1738.19,1737.26,1736.47,1733.39,1741.81,1743.51,1730.85,1733.44,1737.64,1737.15,1742.77,1745.38,1745.8,1748.6,1746.3,1744.52,1743.77,1743.77,1748.1,1746.25,1745.44,1745.41,1743.86,1742.19,1742.09,1738.27,1738.11,1738.06,1737.58,1736,1733.95,1734.02,1733.7,1732.48,1734.63,1734.22,1733.46,1736.09,1737.04,1735.78,1734.92,1734.52,1734.24,1734.12,1730.43,1726.4,1726.44,1730.32,1728.15,1725.34,1727.71,1726.89,1727.45,1725.01,1723.01,1722.18,1730.17,1730.56,1721.48,1729.33,1731.78,1730.3,1730.39,1726.9,1718.17,1715.88,1714.63,1711.94,1703.59,1702.68,1697.26,1700.64,1701.94,1697.56,1696.9,1696.14,1699.92,1702.67,1700.85,1701.11,1700.23,1699.06,1698.18,1695.09,1692.3,1690.85,1692.9,1685.75,1683.64,1685.13,1678.28,1678.28,1679.88,1682.08,1691.82,1688.43,1687.09,1686.41,1685.48,1689.97,1687.65,1685.53,1679.66,1678.42,1671.89,1664.27,1664.64,1664.23,1668.53,1668.53,1654.18,1656.85,1664.47,1674.64,1679.88,1673.38,1672,1672.6,1668.02,1662.64,1662.92,1662.97,1671.8,1673.58,1672.41,1674.1,1677.12,1674.46,1669.69,1669.35,1669.21,1665.6,1664.32,1663.34,1660.25,1658.67,1658.35,1659.49,1659.03,1660.7,1660.09,1668.73,1673.67,1680,1678.53,1680.52,1682.03,1688.85,1695.39,1694.3,1693.13,1690.32,1691.38,1695.89,1696.15,1696.06,1693.3,1692.27,1694.18,1693.86,1699.33,1699.38,1699.38,1701.88,1676.17,1680.25,1684.72,1682.66,1682.4,1682.63,1685.44,1685.51,1682.32,1680.55,1680.73,1681.55,1680.61,1677.61,1675.43,1674.64,1675.18,1678.41,1682.67,1684.56,1688.02,1689.04,1690.13,1691.8,1694,1692.98,1692.38,1691.96,1693.61,1687.77,1687.99,1686.24,1687.12,1688.31,1688.85,1685.33,1685.94,1686.19,1688.01,1687.8,1685.14,1686.35,1688.28,1687.23,1687.44,1685.9,1682.91,1678.07,1679.85,1683.46,1686.11,1684.57,1686.11,1691.99,1693.23,1696.36,1695.01,1695.33,1697.95,1696.54,1693.28,1691.34,1688.86,1689.75,1689.41,1689.49,1689.72,1689.47,1688.8,1687.56,1685.44,1683.38,1682.53,1681.11,1680.67,1681.98,1682.52,1680.87,1680.52,1682.53,1680.63,1686.15,1686.14,1684.92,1682.55,1682.17,1682.72,1682.87,1682.73,1682.66,1684.38,1684.28,1684.83,1684.56,1683.96,1679.57,1678.08,1670.54,1665.14,1663.54,1663.15,1669.01,1669.01,1647.4,1649.42,1651.23,1651.2,1657.98,1658.01,1658.78,1663.46,1664.64,1661.85,1659.8,1660.73,1658.09,1654.34,1657.31,1659,1659.09,1664.72,1665.28,1664.3,1663.79,1663.57,1669.27,1668.88,1673.65,1674.2,1674.09,1672.16,1671.74,1671.79,1673.4,1672.83,1673.75,1677.2,1681.67,1681.94,1679.29,1679.41,1678,1677.33,1677.89,1679.2,1678.82,1679.29,1676.76,1676.75,1676.84,1675.47,1675.29,1673.25,1678.2,1678.44,1680.62,1680.62,1682.93,1682.92,1679.66,1678.72,1679.86,1683.3,1680.83,1681.04,1680.87,1680.7,1679.39,1675.19,1675.19,1677.04,1678.3,1680.59,1681.67,1682.66,1681.98,1682.34,1682.88,1681.08,1681.38,1681.42,1678.91,1679.42,1679.61,1679.7,1680.82,1684.18,1683.68,1692.37,1697.27,1694.25,1694.01,1695.06,1692.43,1692.49,1692.86,1690.18,1690.52,1695.55,1695.53,1695.43,1694.53,1695.05,1696.94,1697.02,1693.22,1703.14,1704.68,1704.68,1706.4,1701.14,1704.74,1705.64,1709.35,1712.21,1719.01,1718.39,1718.8,1718.46,1718.62,1719.23,1719.75,1718.9,1718.73,1718.52,1718.79,1721.74,1725.26,1727.1,1726.49,1726.15,1726.54,1727.09,1729.34,1732.09,1732.84,1733.7,1735.48,1735.03,1736.65,1739.59,1739.03,1737.61,1738.44,1738.56,1737.41,1733.4,1732.51,1733.8,1736.89,1739.14,1739.68,1740.87,1740.92,1743.78,1742.11,1741.14,1743.87,1745.09,1744.66,1744.66,1765.5,1766.9,1744.66,1751.03,1750.43,1748.73,1749.17,1752.64,1751.75,1749,1747.65,1747.77,1749.27,1757.7,1754.58,1753.17,1754.13,1754.81,1754.66,1753.67,1752.95,1751.65,1749.64,1748.6,1748.67,1749.9,1749.39,1749.67,1749.11,1749.18,1745.14,1743.77,1745.19,1747.23,1746.15,1746.23,1743.18,1743.2,1743.68,1743.86,1742.84,1740.13,1735.57,1735.36,1738.15,1738.76,1738.13,1736.03,1709.61,1722.53,1724.92,1735.36,1735.78,1736.06,1742.69,1743.8,1739.7,1737.32,1737.26,1741.53,1744.58,1749.56,1749.26,1746.32,1747.82,1747.43,1747.47,1747.21,1747.66,1748.28,1749.55,1752,1752.1,1751.02,1751.16,1751.12,1751.71,1752.21,1753.77,1754.01,1754.59,1755.95,1754.55,1756.24,1757.81,1758.94,1760.64,1761.29,1763.18,1762.33,1762.21,1763.53,1764.12,1765.01,1764.98,1762.55,1758.74,1758.32,1761.47,1759.64,1758.46,1760.69,1760.24,1762.84,1762.84,1768.41,1769.08,1762.65,1759.64,1760.02,1765.39,1763.33,1761.18,1760.46,1763.42,1765.1,1770.49,1771.38,1772.09,1772.79,1773.7,1774.8,1773.62,1773.5,1773.48,1772.37,1770.73,1768.99,1768.58,1769.21,1769.66,1769.79,1770.31,1768.78,1769.04,1767.12,1767.56,1767.45,1767.7,1769.16,1771.46,1772.24,1770.73,1770.57,1770.52,1770.33,1770.65,1770.86,1772.33,1770.86,1771.08,1771.76,1772.59,1762.42,1772.13,1774.04,1777.23,1777.23,1785.34,1786.97,1777.23,1786.23,1786.04,1785.96,1783.11,1782.76,1781.41,1781.52,1782.3,1784.75,1784.17,1784.61,1786.38,1786.59,1786.51,1787.15,1786.59,1785.96,1785.5,1785.63,1785.86,1785.36,1785.74,1786.39,1784.87,1784.7,1785.27,1786.27,1783.15,1783.38,1782.59,1781.13,1780.05,1779.3,1780.05,1781.14,1780.08,1777.75,1778.1,1777.99,1775.14,1774.66,1775.38,1774.62,1773.68,1773.39,1769.44,1770.53,1771.64,1776.46,1776.46,1786.91,1776.46,1780.68,1778.51,1774.24,1774.23,1775.91,1775.91,1774.87,1775.41,1776.28,1779.07,1779.01,1782.94,1780.75,1778.44,1778.42,1778.46,1777.36,1775.25,1774.85,1774.26,1773.18,1772.26,1771.91,1771.31,1771.95,1771.17,1772.02,1768.63,1768.29,1772.81,1773.87,1771.58,1771.04,1770.56,1770.47,1770.87,1771.41,1770.62,1769.92,1770.03,1768.09,1765.94,1764.32,1765.79,1768.96,1762.96,1765.29,1763.04,1764.78,1764.78,1763.39,1757.76,1757.43,1756.07,1757.61,1760.27,1758.56,1758.69,1758.54,1758.34,1758.52,1758.81,1761.71,1764.13,1769.39,1768.4,1771.08,1772.92,1771.91,1772.06,1771.72,1772.43,1770.42,1770.13,1769.73,1768.14,1767.83,1767.62,1767.17,1767.71,1765.28,1767.49,1767.36,1768.73,1770.6,1771.95,1771.9,1772.19,1770.74,1769.97,1771.51,1770.19,1770.58,1770.58,1769.46,1768.82,1767.72,1766.78,1764.34,1766.91,1768.02,1768.06,1768.06,1760.86,1769.13,1768.06,1765.98,1760.26,1759.06,1760.95,1760.19,1764.22,1767.02,1770.86,1770.74,1772.13,1770.77,1770.88,1770.71,1769.98,1769.61,1769.04,1770.52,1771.71,1771.65,1771.96,1773.21,1775.22,1777.9,1778.61,1779.43,1779.52,1780.4,1779.22,1778.25,1777.94,1777.85,1777.39,1778.34,1778.9,1779.35,1779.1,1780.08,1780.99,1783.44,1781.93,1781.39,1780.57,1779.08,1778.18,1776.67,1774.77,1774.77,1776.84,1776.48,1776.77,1779.97,1776.77,1783.96,1779.99,1774.53,1772.89,1772.03,1774.9,1776.07,1775.21,1775.24,1777.74,1778.63,1777.78,1776.81,1775.93,1776.16,1778.93,1778.87,1778.39,1779.28,1778.99,1778.5,1778.06,1778.5,1779.01,1779.34,1779.16,1779.58,1776.1,1775.87,1776.91,1777.36,1777.78,1778.97,1779.48,1778.76,1777.24,1776.8,1775.58,1775.1,1774.83,1775.34,1774.94,1775.35,1774.41,1773.79,1766.5,1773.41,1773.41,1777.2,1776.49,1776.19,1773.41,1774.34,1774.41,1773.2,1770.63,1771.97,1778.23,1783.45,1785.95,1789.2,1789.4,1787.59,1787.33,1786.07,1785.9,1786.74,1788.37,1786.17,1785.08,1786.45,1786.88,1786.97,1786.89,1786.94,1788.34,1789.62,1792.01,1792.77,1788.92,1787.36,1788.15,1786.9,1789.94,1791.24,1791,1791.49,1788.94,1788.43,1788.41,1790.2,1789.28,1787.84,1787.81,1787.57,1790.2,1790.09,1787.19,1787.41,1790.35,1793.18,1793.18,1796.27,1793.81,1795.55,1794.61,1792.56,1790.73,1790.33,1792.98,1793.51,1793.01,1792.55,1792.93,1792.34,1790.41,1790.56,1791.64,1791.34,1791.68,1791.99,1791.86,1791.94,1791.72,1791.63,1790.97,1791.6,1794.29,1794.53,1794.79,1795.54,1792.28,1791.48,1791.52,1790.11,1787.43,1786.44,1787.76,1785.1,1781.12,1781.12,1781.54,1781.7,1776.32,1773.06,1770.19,1770.73,1767.88,1766.85,1762.96,1764.46,1765.06,1765.63,1765.63,1763.92,1764.09,1757.37,1755.64,1755.28,1756.85,1757.73,1756,1750.39,1744.18,1743.82,1756.23,1752.39,1751.58,1751.06,1751.89,1752.48,1750.82,1751.85,1752.93,1752.78,1752.15,1750.61,1748.62,1748.83,1747.64,1744.94,1743.21,1742.7,1744.75,1740.17,1740.55,1742.4,1741.87,1741.9,1741.42,1740.53,1740.3,1738.51,1735.1,1732.09,1733.43,1732.69,1730.22,1729.93,1727.6,1717.64,1725.84,1722.81,1728.4,1728.27,1729.08,1729.08,1726.39,1726.22,1732.7,1727.06,1721.28,1722.2,1728.77,1729.18,1730.49,1731.31,1729.86,1730.06,1729.14,1725.7,1725.37,1726.02,1725.36,1721.74,1720.88,1718.67,1718.07,1717.62,1715.91,1716,1719.77,1719.66,1718.9,1718.2,1719.27,1717.99,1718.87,1718.73,1718.98,1719.31,1720.52,1725.06,1725.04,1724.85,1726.98,1728.58,1726.33,1725.33,1725.94,1724.96,1722.35,1722.76,1723.6,1721.79,1722.93,1723.42,1727.46,1727.46,1724.75,1727.46,1732.44,1730.85,1730.93,1731.65,1733.55,1738.17,1741.47,1741.48,1742.39,1747.52,1748.03,1749.06,1749.66,1746.02,1744.81,1742.12,1738.42,1737.5,1739.48,1740.35,1739.78,1738.83,1737.27,1735.6,1735.21,1734.78,1734.72,1731.27,1730.73,1731.48,1730.53,1731.48,1732.07,1732.99,1731.03,1731.17,1728.19,1728.94,1726.8,1726.15,1724.52,1724.33,1727.13,1726.43,1725.82,1729.24,1728.99,1732.02,1732.02,1734.92,1731.75,1731.21,1733.24,1730.05,1729.04,1727.59,1726.6,1726.67,1728.24,1728.35,1727.93,1727.78,1727.85,1729.14,1729.42,1727.61,1727.63,1727.14,1726.59,1725.61,1724.76,1723.59,1721.54,1721.12,1721.33,1721.45,1722.37,1721.84,1724.13,1721.98,1722.18,1722.02,1723.29,1724.12,1724.17,1723.61,1722.48,1722.44,1722.05,1720.88,1719.16,1719.42,1721.81,1722.09,1722.22,1723.98,1724.48,1724.35,1724.06,1723.77,1726.69,1726.69,1730.18,1730.06,1726.69,1735.19,1733.99,1736.8,1739.28,1740.55,1739.54,1738.78,1737.64,1736.81,1736.81,1736.83,1734.47,1733.71,1733.53,1734.27,1734.87,1734.75,1734.03,1733.83,1734.05,1734.29,1734.54,1733.25,1732.24,1731.63,1730.83,1731.81,1729.48,1730.07,1729.78,1731.06,1730.64,1730.65,1731.43,1731.18,1731.5,1732.48,1733.48,1734.66,1737.33,1737.85,1737.08,1734.5,1734.66,1734.23,1729.61,1732.01,1732.65,1734.24,1734.24,1735.78,1728.99,1731.59,1725.4,1726.23,1727.56,1728.63,1728.55,1728.82,1728.06,1727.7,1728.96,1729.14,1728.54,1729.3,1729.93,1730.35,1730.78,1731.25,1731.83,1734.35,1734.17,1734.3,1735.15,1736.07,1737.32,1737.66,1738.28,1739.13,1738.37,1741.44,1744.75,1743.71,1743.76,1751.46,1754.6,1753.62,1753.6,1756.77,1760.01,1762.43,1763.36,1761.06,1760.86,1760.33,1763.64,1766.35,1762.19,1762.54,1763.38,1768.12,1768.12,1779.72,1786.14,1768.12,1785.23,1781.76,1778.4,1780.47,1783.67,1784.22,1783.66,1784.14,1786.83,1789.03,1791.75,1791.78,1793.51,1793.39,1792.66,1792.03,1790.23,1789.41,1788.26,1786.04,1784.48,1783.82,1785.52,1787.39,1788.24,1787.67,1788.75,1786.55,1788.67,1789.81,1789.47,1788.94,1788.99,1788.42,1787.26,1786.15,1786.47,1786.23,1784.49,1785.55,1787.18,1788.53,1787.19,1786.33,1786.06,1781.98,1786.03,1786.09,1788.78,1788.78,1792.14,1792.36,1792.74,1788.78,1790.37,1798.56,1798.74,1799.35,1800.59,1800.64,1797.06,1795.48,1794.94,1796.16,1798.32,1799.95,1801.07,1804.26,1803.67,1804.51,1805.99,1805.79,1805.33,1807.27,1807.07,1806.34,1805.49,1805.48,1805.76,1806.28,1807.11,1802.64,1802.17,1799.11,1795.55,1791.89,1795.38,1797.88,1798.89,1797.55,1794.94,1793.28,1788.3,1785.22,1790.43,1792.92,1791.18,1791.09,1792.64,1789.21,1788.83,1789.24,1791.41,1791.41,1790.88,1787.8,1793.93,1790.75,1790.77,1797.16,1800.09,1800.45,1800.49,1799.46,1799.38,1799.27,1798.15,1798.75,1797.62,1794.61,1794.61,1794.45,1794.32,1793.34,1791.65,1792.22,1791.73,1792.52,1792.75,1793.37,1793.58,1794.14,1795.63,1793.82,1793.99,1794.22,1795.22,1796.61,1795.72,1797.06,1798.87,1800.01,1802.47,1806.43,1808.83,1807.63,1806.31,1805.91,1805.66,1808.63,1810.73,1808.46,1811.41,1818.06,1813.76,1821.32,1824.41,1825.94,1822.24,1821.32,1827.71,1829.32,1828.71,1833.84,1834.47,1829.77,1824.11,1824.09,1825.48,1823.63,1822.06,1822.15,1822.16,1820.49,1818.86,1818.5,1819.23,1820.44,1821.8,1822.84,1822.7,1821.78,1821.84,1821.43,1821.57,1821.92,1822.66,1820.37,1818.67,1818.81,1818.55,1815.42,1815.51,1819.35,1820.64,1820.88,1821.56,1821.47,1821.45,1821.26,1820.98,1819.89,1819.66,1823.16,1825.42,1824.21,1828.45,1829.99,1831.56,1831.56,1830.53,1822.32,1824.69,1829.2,1829.17,1827.17,1823.63,1821.56,1819.16,1821.69,1822.97,1825.7,1825.77,1823.81,1823.65,1824.43,1823.64,1824.06,1823.85,1824.36,1827.2,1828.44,1829.92,1830.54,1828.68,1828.92,1828.42,1827.65,1828.05,1825.49,1825.71,1826.34,1828.44,1831.52,1834.32,1835.85,1836.1,1834.78,1835.62,1836,1836.03,1836.99,1836.67,1837.17,1831.21,1831.73,1832.27,1822.64,1828.7,1828.97,1832.12,1832.12,1807.2,1825.07,1812.04,1814.77,1819.27,1815.57,1813.52,1811.07,1808.91,1809.02,1810.39,1809.27,1806.46,1803.79,1802.11,1802.65,1803.15,1804.44,1804.01,1803.84,1809.84,1813.96,1816,1816.55,1819.42,1817.82,1817.78,1820.67,1820.62,1821.61,1819.91,1821.76,1822.9,1822.42,1818.39,1818.27,1818.92,1818.6,1818.31,1818.19,1820.88,1824.16,1824.13,1822.52,1822.19,1821.08,1821.56,1826.79,1814.16,1820.45,1826.82,1827.72,1827.72,1827.12,1827.72,1841.15,1843.07,1854.82,1857.09,1858.02,1856.82,1851.2,1846.27,1849.36,1849.17,1848.93,1850.11,1850.28,1849.35,1849.64,1848.66,1847.91,1847.5,1846.3,1846.68,1847.37,1846.15,1846.1,1846.35,1847.06,1847.22,1847.54,1846.48,1847.48,1848.42,1846.15,1845.05,1844.75,1844.8,1844.78,1845.39,1846.34,1848.16,1849.44,1849.22,1848.89,1849.41,1852.16,1857.4,1857.05,1852.39,1851.56,1853.42,1853.08,1853.08,1855.14,1853.08,1866.68,1865.42,1863.71,1863.1,1864.93,1865.25,1861.78,1860.56,1862.65,1865.56,1865.43,1863.61,1862.8,1861.64,1860.69,1857.98,1854.52,1853.83,1851.86,1843.19,1847.71,1847.85,1846.42,1844.84,1842.99,1838.74,1839.16,1837.94,1840.32,1847.3,1850.43,1850.84,1847.25,1849.25,1849.45,1849.71,1848.98,1846.87,1842.91,1839.95,1839.26,1833.77,1831.99,1831.94,1830.7,1821.36,1820.38,1821.64,1821.64,1816.45,1816.38,1820.75,1821.18,1818.66,1814.6,1815.4,1820.59,1821.91,1820.77,1820.71,1818.52,1818.29,1818.15,1817,1818.49,1817.53,1817.62,1819,1819.31,1820.28,1822.06,1821.5,1820.15,1818.53,1817.65,1817.18,1814.75,1815.76,1817,1814.5,1818.68,1821.79,1819.57,1820.17,1823.01,1822.96,1827.92,1828.4,1828.03,1825.31,1826.56,1827.38,1828.33,1827.48,1824.75,1825.67,1826.16,1828.39,1828.29,1828.29,1830.44,1830.44,1835,1830.44,1834.12,1835.96,1835.38,1838.73,1843.21,1844.39,1842.02,1841.88,1843.59,1844.52,1843.54,1841.9,1840.6,1839.18,1837.51,1838.06,1836.65,1836.61,1836.89,1837.39,1837.76,1838.22,1834.76,1831.81,1831.5,1835.09,1835.59,1833.91,1834.16,1834.01,1834.51,1833.7,1832.33,1832.43,1833.58,1834.05,1832.66,1832.44,1832.86,1829.57,1827.54,1825.41,1825.61,1824.8,1822.63,1814.42,1823.87,1827.38,1827.12,1827.12,1830.48,1827.75,1827.53,1818.24,1818.47,1821.25,1822.89,1823.43,1823.35,1820.77,1820.44,1822.71,1823.34,1821.69,1821.99,1822.15,1821.5,1820.99,1820.27,1818.65,1816.34,1813.23,1812.98,1814.02,1813.95,1814.02,1814.92,1816,1818.53,1819.72,1826.31,1824.75,1822.77,1822.97,1822.85,1822.74,1822.85,1824.79,1826.89,1828.04,1826.97,1827.79,1828.06,1829.22,1831.36,1832.17,1832.5,1830.73,1831.9,1828.75,1830.74,1828.6,1829.23,1829.23,1820.54,1820.57,1820.44,1820.11,1820.08,1819.5,1819.16,1820.57,1820.66,1819.11,1815.93,1815.71,1815.13,1811.98,1810.75,1811.54,1810.97,1811.34,1813.54,1815.72,1814.34,1812.82,1812.33,1813.32,1813.36,1813.27,1813.66,1812.96,1812.01,1811.41,1813.28,1810.75,1810.18,1810.95,1810.45,1812.08,1813.85,1812.81,1811.73,1811.02,1812.15,1813.57,1813.35,1811.1,1809.26,1804.91,1804.21,1802.16,1797.89,1795.97,1794.87,1794.22,1795.21,1795.21,1786.52,1785.99,1791.6,1793.42,1793.39,1796.41,1794.11,1791.82,1787.61,1787.01,1786.43,1786.53,1782.09,1782.13,1780.66,1781.29,1788.06,1788.14,1788.82,1788.8,1792.53,1794.66,1792.86,1791.62,1791.48,1791.3,1793.16,1792.59,1790.93,1790.8,1790.07,1795.14,1791.57,1792.25,1792.28,1793.25,1790.46,1787.5,1784.22,1776.85,1777.25,1781.66,1782.8,1780.89,1779.63,1778.67,1781.17,1786.62,1783.35,1783.71,1783.73,1785.98,1788.23,1789.07,1791.09,1788.23,1798.91,1797.04,1797.36,1799.04,1798.15,1797.58,1798.12,1797.55,1798.09,1798.62,1801.58,1803.75,1804.69,1804.76,1803.75,1804.23,1804.13,1802.58,1799.69,1799.36,1800.02,1800.42,1800.68,1800.27,1801.03,1801.36,1802.34,1801.12,1801.42,1802.39,1802.78,1804.31,1804.76,1804.07,1804.11,1804.08,1804.23,1806.7,1807.36,1807.58,1807.71,1809.17,1810.32,1810.25,1810.34,1776.88,1799.56,1810.56,1810.67,1811.15],
      "v": [29004226,18380520,16833175,17847398,15286464,14327839,11724143,12023306,10980053,9757745,7691972,10514853,11193215,17558924,9039621,6042694,6306052,6396645,6442276,6832711,5881377,5305177,6019839,6751446,9071216,13023494,40194306,816988,51565548,20790791,15590062,14411430,19125142,14639711,13272567,15150635,14922383,12151863,15980105,9892489,13132841,14729298,17300819,18471406,20902860,24406519,728989,41341745,43022160,22126236,13933801,13368445,21618504,18002997,15358001,17414497,10581924,9969202,8039779,9763439,10784195,7382936,8308341,13719884,18854935,16150799,11221480,17547748,10372610,8696603,8620555,8828503,9736001,5912219,5746685,183061,26077177,16726375,16512863,13083389,18093531,24755597,14792363,16261985,18780747,21320245,32975679,11812220,14256197,15825860,22167065,42495710,42533727,39347526,242685,48365639,32459098,20271852,15108076,12786719,16798656,12805550,8908252,8872202,10834962,13710590,11342822,8645488,10277366,8906003,8074946,9459121,8709706,8623549,12554995,13891390,11130288,7304662,7436276,8398480,8339965,7337873,7240749,177984,17973192,10497856,11400140,22534046,21936242,20677490,21030129,16943804,16072115,13838601,13352309,23789564,39206426,19466548,26173805,19030101,21248429,34905797,1009815,174957919,36809268,24003347,22450730,16074256,21342723,37553143,22349982,16809036,26640456,47681916,40263288,17280814,11052128,10435774,11845540,17128278,11753428,7135977,6517912,7428167,9963829,10668807,7908428,8680095,7290408,6913028,5157178,85143,19127704,10502807,11383940,16073335,13376138,15444961,11145097,10928411,20414901,51815999,22582808,26205616,23408421,14293620,29174354,44732645,55944031,34529599,643805,85069068,51071019,18397911,16890082,15005452,11565496,11214834,9380531,8020818,8989065,8559521,10821866,25342420,23644294,17935892,12453208,14744939,12554896,22492868,23268565,25461114,9656581,7993003,8750725,6770157,6702239,6314738,6274848,106604,18399385,11259050,10637003,8613688,13232577,13682381,10282296,8533352,15859328,19988666,19194752,15157234,13978884,12794419,11080237,12755030,17932969,15075770,380436,37857103,33317474,23869273,23619921,20676147,15227264,11424890,8470677,7959827,7399481,7206420,7857296,13128688,14882018,30323257,20084346,17043758,10295294,8033719,12394769,16791996,14442277,10454337,7777239,8109762,7063642,5380022,6244206,201700,24161099,17784814,25095922,17077247,21472451,18693591,19147342,21846669,24578294,20778383,20305174,12068963,12322992,23016440,26349482,17970727,24958864,37575452,534572,41547082,31179722,21320397,15580414,15743488,13491667,13985070,14487817,11070408,12349306,10717020,9639339,8770896,11892109,11829695,9492626,7263174,8708909,8801278,7500478,7692665,5849128,5875757,5847785,6375812,5006681,5216183,5369081,179103,25661373,16624338,14083046,13523884,15641020,22072161,17516724,18151643,11056296,19275368,16698621,13322943,15802481,15339445,15998435,15191398,16788808,23262860,663590,43397392,19039380,13659573,13982496,10838212,9965266,9335970,19728065,11131079,17818865,20628003,12574077,9443326,9610837,8454974,10965735,9128823,6611631,6896974,7274348,6933636,6764182,6740393,7973818,7766008,8936972,9497674,11047303,164187,23195657,15101775,22435541,17209927,22653120,26138357,18547998,18308815,22069516,24901886,17992635,21098869,29762581,30989569,36316521,31437856,47514845,44248761,622817,51205128,52835243,26352690,21720784,15169879,15178039,15972628,11835016,8135618,11794641,12635458,20163347,13958638,12015033,13261494,11831671,9281429,6500261,7938802,9607985,6242067,6215839,8421873,5931449,5469123,5427594,5490917,5798716,163007,14668246,12264335,12918089,18819522,26162702,17245554,15640110,18123806,19103962,13865795,19090283,26931726,23688081,17278962,16246223,15951229,15721945,49969309,405185,45750432,27494798,15161417,11099757,12223244,11906264,16248893,24472645,14680163,20781660,15928491,14802787,28138075,18141984,15045659,16576751,11502526,10309369,11074029,8721067,9000492,11359178,8793137,8982593,8874108,8326143,6499636,8656959,127634,23921849,14264456,18446795,20115471,17211837,16440583,20560438,13227609,18229863,19438381,14544160,18321640,15906995,17337773,23743317,19367272,28617458,34759491,424009,58030392,59258705,30064474,27110930,17327994,16358167,21044142,25603309,23155874,20681114,18315807,14166313,11215571,9503570,8566617,9416902,10224123,9948969,7105238,7508543,12028177,11041644,8344085,7121864,5627372,7248929,5047140,7053202,196141,23357520,12991395,20358232,18490210,20198919,16265409,14680049,15056093,17751023,22702731,23687952,15665549,14613620,19699857,28849395,24887411,21356259,27699627,761575,57476792,41038940,17991908,17613182,13628714,10377276,8740526,11077957,10927487,12567296,9244994,9425397,7426687,8112748,10585301,8930336,8110891,7474012,7417477,6408933,7203175,7579718,5480073,7095383,6419258,9834465,9170232,7601097,168801,41659116,18187351,17226006,14946212,17420030,21184110,25339161,32020191,18060221,11632951,16543909,22273305,18827765,24434191,19911613,17154087,23292058,22036868,542155,60118557,18696208,9747251,9933279,9878203,9127217,10350920,10889058,9469881,15104031,10254102,9689751,9574259,17467706,20250774,10288608,11993675,10774322,10001451,8320241,8380026,6119825,6444618,7371960,5941932,6585235,6602208,6552754,96725,19246480,14339294,13706640,20270919,16180203,18905582,14148565,24184137,13121646,17062384,15518966,15842887,18968952,19489658,33199770,25592893,21578576,28464635,930703,70203422,18603029,13943821,16616084,10646352,8373117,11721232,9843387,8316100,6881531,6568299,6841840,6731986,12241512,13600309,12382114,7045100,5436494,5329875,4936751,4759238,6527669,5039639,6492241,6344578,4965973,5601166,4341855,55500,13900069,9692163,9246220,12550714,12581048,10962941,13199380,10446826,11246651,10217123,10769937,8557532,12127572,21795847,13852391,12381976,27209281,48071507,528613,57254733,12767279,8248689,8020607,10534491,8226927,9590457,9156105,7493484,5474585,6880655,10435453,14907736,9875108,7246447,6142131,6106990,11246125,11406858,6850982,8700745,5230379,5591513,6465006,5882597,10069427,7484965,5569943,130693,11330418,11953180,8697770,8603377,9986283,9541884,7912216,8614506,9256011,12303331,12536323,11466104,14693865,14560580,14863498,25708419,22296619,24158051,637827,49922338,119870203,41929429,31407692,23338403,20310794,17066747,13931453,11900705,20855103,16699222,14891851,16614285,16279711,21598003,27656710,36508872,37698065,26697706,22747835,20619361,13885799,9622193,8960210,8896412,9961010,10442336,9583117,60558,18832306,21107964,23971444,26781555,31581818,41635166,23399643,26181941,20845811,21203691,26047983,27233491,24053031,22332508,21657820,21076326,25578556,24585914,391377,43409422,53857613,38079536,21612136,17518516,32371786,20770938,29195140,25564045,20703637,20574829,22428110,14376800,16380574,13141479,9257967,11406507,8477797,8183455,9075009,11510993,8342485,12651644,7951708,8308760,7321771,7007045,10001215,224155,32502345,17120064,21618084,28711855,21811075,21329090,25041126,25603337,19676304,16469124,18650999,19531007,22990551,24981077,23417213,24854080,26213363,31443769,402712,51233332,30718720,23074181,25144525,17068903,24041579,21252147,24820838,14837959,15887451,20100992,18640756,14053989,17837439,11417818,9625047,12157428,10284467,9010873,10468467,16241251,18520850,12860531,10903160,10224468,10743248,8364499,12773997,84307,32509513,18753513,18992943,21270205,20982434,18693956,16150180,18161331,15051261,16032425,16088526,14023304,15493880,16605393,25448844,22346949,21777430,32827239,398917,62757063,39623235,27572108,24003009,16920459,15893141,40098375,18749833,13312059,12153423,17419371,11519753,11826813,10691661,7590779,10671856,8514123,9172626,9194008,35223787,10706906,6424786,5381664,6955593,7684675,5801953,7692691,7303496,297690,23181173,21640576,24981644,14649491,24932040,17550507,13089553,11924702,18125279,12856962,11642861,14197584,20919059,15023231,18707765,13986925,20133693,24952512,322681,46035350,39163230,20743007,19259444,14370731,14636172,11221310,15410848,11611684,12298531,11899411,11015083,9061661,11615442,12417897,12509683,12380910,8400462,9254064,18422502,16562461,8978484,10246115,13016423,9636168,6506647,9202088,10460312,295422,18852310,14625090,16306539,15447067,15991096,19882562,13802661,15104292,27229791,29075474,16452308,14301870,19487230,26225494,18608264,24376778,25102078,34036511,392861,48452433,31727899,22536485,12454891,16373736,21127884,17624206,21336376,19530480,12703729,8779317,8093222,9416817,9071893,17783047,15928139,9317904,9373103,11100296,11061204,6929207,7402256,6415563,7899077,6452507,6827061,12321406,12326028,139230,30164191,21818516,14990162,14933982,14142954,13789173,19456598,16803235,16531925,17236125,16683078,18143854,20044420,21427655,27095269,24919710,23597841,34051750,427632,87202574,22762578,17408744,15316080,17359607,16061661,15865753,17704816,11778374,14648361,9867019,9095684,6704130,7027291,10373170,8904250,11073267,9565821,9077944,17015683,10758337,8033613,7805074,12690247,12842414,7630505,9140768,13229741,100805,21887597,16462734,16247413,14816132,13880181,14591783,14318164,17969480,19684297,19238284,29749517,23571011,16422323,16172810,22234032,34167998,39286153,37867870,1537016,99444146,24226030,15861754,15209420,9283832,9917042,14812401,14282772,17405453,16119858,20021205,14664191,15622289,17006863,12410803,11538694,10974703,9345761,9773554,6958234,5721919,5793383,7966234,6776175,8946054,6978101,5571721,5549453,100142,17340270,9574725,12685181,12915326,11341669,14092767,15592410,12734564,10842367,13044045,11024682,11548867,12177428,12118169,17267933,18289435,22997932,25838147,577997,51507399,29222025,19230399,19260823,14384181,10710089,11815110,9788934,10012242,9112453,12001343,8977879,11804040,10513192,11741998,9424864,10449708,9659434,8560214,12607581,7340490,6680246,6742032,13387633,8954876,12888613,11107363,6955413,42831,14524493,9204845,13941118,12693217,13083306,9983684,9767471,12827049,10751572,9779285,9514729,10732289,9098214,11951570,15308083,15771207,17361412,19933153,293306,41509071,38363596,18365203,13552822,15352453,17007256,10859385,26680923,13253275,16521035,13551652,13652312,20166619,19668626,15049769,11236520,16460824,11917676,9974974,9468692,17421371,12104807,10298993,8229499,7407871,7415111,7361147,6932407,161137,17069001,10819354,12381064,14835176,14054434,12378854,12759070,15198865,11177716,16827203,17571413,12914138,16245308,22066771,17770648,20480611,29430095,30669195,481288,57568333,17305679,9223089,9870858,13901014,7921945,7328958,18829660,8687086,8854520,9926789,9659992,8110492,8230357,8849750,11627391,7275573,5831978,6009633,9188701,6760176,7263563,6409461,7712638,6420713,8634461,8777375,9344510,284343,16119720,10570035,14539015,18571159,12616268,11423557,16516828,12089506,12231868,17936291,12486138,17479575,11475586,12694454,13067724,18677904,19163296,22601693,845954,43034968,18322442,10395528,9707042,10321805,13918165,13614073,15905106,19534298,18713936,17545447,22266822,44457161,28655288,19827133,12920945,15688466,9766915,9344682,11540807,14417072,6171487,8466213,7617215,6701146,7154224,7148952,6501391,353866,33702669,22002163,23213841,27484856,47935350,32060108,17400766,29309801,38870972,20584701,16968094,22054071,49691079,28460502,17963515,18498273,35454581,28586308,911315,55301660,19836353,10934125,11254352,9119686,11290544,11158194,8247315,7157513,8668338,8160753,9140750,9009672,8506846,11148735,7549661,6197008,8362473,8656272,9224020,7140022,5818400,7436252,7862213,5897364,7270100,5262837,5308179,41227,16230251,13074475,12319920,10680184,11905627,10524101,12537165,18642479,15011526,11237703,11601917,16067148,21253338,16151655,18481928,18354318,20642302,24805730,596947,52904281,19555117,12034626,9759967,10105378,7287693,7654820,7279804,6404479,6876455,6855307,5889331,6801620,5863883,6149432,7401285,11413997,10283687,7103193,6978977,6347781,5777167,8958304,6679672,5411142,4790734,5981308,8536744,48358,16111079,12313411,16155704,14734919,10035762,13919669,14683231,12384566,16388789,18373064,14261361,15560148,17639029,16723642,24246799,27339825,19031842,26618168,697107,56459539,31854209,15650620,13937402,12565283,10491784,12778673,12316733,12411683,11797634,15661066,22081786,9077411,9415078,11110007,7396826,7246258,7060302,5287141,6670559,7058961,6682466,6213045,10580292,6992222,5973057,6991564,7444314,63586,19450082,12159138,15933417,11292768,10442462,13202066,15885347,15195946,15871680,15478440,11581043,14453929,17728793,13036404,14312788,17079459,16315320,22164520,642137,61212107,35574151,19345691,18131841,20028105,17591199,25425035,19169883,22997017,20272119,12400334,10279601,9999132,11653778,8927743,7532509,8810959,9523925,7294628,9654338,7113338,5567580,5823500,7578089,8565362,4428896,5088604,4906442,88344,13268624,11005441,11188392,12927202,13336599,11442133,8909887,10250626,11581391,11296095,8926096,9639368,9491525,10608075,13250294,15789974,16128212,26804891,373865,44081513,40348111,14519654,21623948,14059093,12346119,9908417,11765811,12683027,9490820,9323152,15654927,7911510,9403518,11627758,12238164,11327817,9852458,7478887,7822038,7904170,9493013,7614672,11912482,10197806,8522763,7120212,11504386,111733,29386377,20477049,17259509,14792597,13049316,15843511,14841339,17473866,15579404,19900541,21399057,19440151,15151666,14530056,16096673,17588357,20770589,22284751,549526,51782599,53764826,13774217,14213408,9590451,12729974,15669347,10717527,10255504,8609707,7954459,7564607,7827130,6966858,9346807,10065580,10474433,8899397,9351496,7282552,6666054,9112094,7377402,6589320,7304185,9764957,14305560,12153394,89339,18336667,22808654,26537727,17807428,17569955,20992320,20042095,18432121,27962316,26581996,30408030,28261614,32825420,19716865,21278902,19511307,30736190,36102147,480130,43560116,34899911,27197181,20598865,12858544,14733483,22227597,21735941,16162912,13408446,8895311,10937218,10681811,15744456,16388903,11477646,11075505,12655244,17241966,14018382,8811354,10797997,12387651,10395869,13669740,9958526,6968224,9005480,293317,21403063,19233848,23851663,23103217,16005000,19279992,14826099,30982103,23418482,32108030,19552027,17979268,30783016,20681799,19751191,20526738,18356311,32784893,375143,51966404,19152623,14934522,18537166,13106046,11090220,9919735,10864488,17797041,12766507,8682793,8493924,9036854,7764756,10895936,12258734,8821622,9650779,9130511,10992168,9554365,14092645,11156859,9960447,12580908,8845027,7644480,7663966,119060,27649762,20791107,19531378,26251609,31507566,31069124,24012537,45988742,26654302,26200751,23779842,23705077,22684560,31136175,23803196,17795571,21238257,43945295,438428,47295638,25354002,16185242,14191510,13308820,12211930,11171559,9709245,11465366,10383770,9343849,14743040,20101335,14616013,13552074,14947890,19958805,16700646,14429870,17744761,16491514,11832522,17634691,18698333,14014069,7936232,9251085,8181171,376496,21970416,16862611,18898422,26149349,22372971,37873636,22900593,34219903,23603086,20951775,16256221,21739344,16548739,18214848,17976457,18332880,33469644,44734782,243869,52712691,22987566,14038848,18824807,19767329,22540313,12862287,10625529,12436242,12496082,11400687,10496786,11560005,8529725,7753066,10435669,10653925,8888783,5896330,7210534,6310548,5689012,5243365,7158297,8143396,6864830,7374290,8417720,142259,20737212,18779095,21707785,22410518,16071009,15069298,12463002,12704391,13282865,13299460,14545688,14845248,12653585,15711383,22496842,20446212,15192503,21036583,366227,47589122,21578706,10964401,14118149,17474935,14852487,12886029,10212370,9653284,11585580,9376030,9267149,7542253,12229835,12006139,8545326,9587144,10526627,11407036,10240822,9082802,7572329,9592917,8675938,10485489,10383454,8928041,10117766,226134,36007354,26375115,21930518,17362500,20113970,36590620,33184368,23424975,18946471,33481573,17206986,28661906,32619223,20034047,17948818,20281212,27005599,24951051,457989,41242476,21501904,12307829,11706611,16192258,15416864,15644784,15095096,15984330,16137583,12564924,11660061,8926973,5875637,7385951,7008897,7484656,10987468,8905582,8009848,8796629,11637284,11719389,8032272,7232964,9492589,11878237,7075005,71954,15438612,9973723,14603131,14003074,11527186,9283009,10617026,9410479,11140535,11478617,10385948,10138964,9650076,11723857,15137135,19187280,14117979,30756349,607563,36958554,19577460,11559578,11043289,11475229,9279368,12319671,16693041,18698416,10863917,10107388,13223530,18344430,9692672,7462735,8813544,6553265,8045773,9217073,7705626,5401195,7969388,10233532,12137295,9916915,10511695,11105381,8060314,71762,24358253,14356091,12892558,13584647,16137025,14684778,27585511,14949722,18747954,20469691,15443767,21274934,19586599,16843559,23382197,20310319,27752716,33942096,448213,55923396,38174289,19445681,16110859,13385225,13765323,14752691,12029224,10489882,17010495,17778577,9850285,10740774,9659804,12070999,8008094,8828957,9801792,9715014,10488904,8827211,7898222,8171666,7131300,8618444,11781392,19739841,14490188,82665,29173453,17779004,15585055,18958705,16046825,24277344,25170704,24064636,17395030,15169307,22261778,22296029,20197188,19965511,16885679,21188336,20320515,30534061,889669,47540437,31606129,19925816,23841607,17129762,18322407,17265848,16225213,19553940,17290380,13343500,15755899,16587134,11578533,9565414,9208323,8882393,9909932,13281098,8833349,7594484,8140901,8307942,6532493,6368788,6484636,9685365,9693018,271236,22626053,16899004,17381414,20652906,30829798,24411959,26090293,54036530,27414964,16496047,34295841,40846435,26845268,21216249,16779678,34456659,31507402,31039071,288149,49025808,18164377,12768395,14095478,8239609,11612829,10404485,14978168,9898668,11433624,12115290,7783328,11376717,9996210,8799705,8327310,6487531,9199568,18166349,16718586,23248962,16952840,17693276,26616347,26408381,16366519,20874257,63575741,893233,113127194,51348308,51447402,41075726,36457781,35767608,26016094,23871544,27738804,24336595,14464581,15371559,19240984,18291487,17693547,22616888,26718300,28215974,716130,51102825,21442482,9863547,8477456,8272843,13481369,9976569,6940980,7712528,6920976,8810452,5416523,6525661,7534385,8375006,8464679,10143047,7902304,9020955,13119399,10497607,12740100,10786162,7537906,7417803,9189955,7459240,6831227,95460,17113459,10551983,12244307,9026549,12739119,14545282,11511244,15801735,13383559,13875663,11713862,10154882,12383794,15039132,16030487,24861317,24315317,26260702,267779,39978290,16483188,11509780,10842085,11810988,9652526,9376780,9391031,7787837,7836029,7209707,7005330,8494906,7749360,8942881,6731869,6673922,7614902,11637308,9755471,8607779,9094362,13181130,11824645,11855041,12323116,12380673,7009432,208201,21474229,20084946,17035362,23966817,38845962,21709202,15352426,17858969,23896982,18791551,13388360,11159013,10417520,19415816,11198724,11878721,16587649,28695570,521553,45382273,28352789,19156164,10508254,9736244,9111318,11646735,8651474,7801844,8263552,9261453,9535671,15319237,7888540,9627364,8206650,6059738,5120793,5826295,7276565,5912822,5325288,6481330,3746561,4052322,5760167,6896371,3915693,123260,14266621,9724394,12406850,13804660,12074045,12782221,15892111,12742680,10125693,8867516,8538371,14773403,9590757,10150907,10551576,11384626,13246697,16249634,192051,38316118,14841383,9287656,9026266,10231601,10863671,12666890,15384700,9459701,7843890,17799657,14442254,20167268,23381079,16488204,16282866,9589786,6951355,7407372,8042854,5717615,4633827,5701542,5262750,6520854,8050995,4694820,4994588,160709,12748169,8868549,13023920,15280382,11577656,18015737,14173415,15290024,22367261,11876530,10898227,15601389,12786968,18584670,19025169,15282353,16793410,21541489,512473,38692677,22088301,14559605,11918980,10094806,12688657,10652769,10300705,8774417,12654131,9521613,9250698,10863892,12723680,12793405,11864177,10384686,6040470,6191180,5875396,5902352,7514215,9842816,7579554,4991500,7089051,5933401,9285992,66299,15342050,9249049,12720338,12617041,23311721,20454067,22526015,22599576,19151210,21771844,22995087,20084619,14776811,14424369,25773616,26502810,23367762,23625315,497200,48437888,18227421,9288897,12800797,11334056,8505147,9195011,10252503,9888383,10159805,8422265,11846934,8259268,12153355,11387420,9763381,8354632,7481719,10673625,10675644,8200883,9367484,7453564,7418500,6528722,5289549,6265169,8880631,65911,22454356,11161332,12076119,10247872,12782854,14903276,12899098,12684468,13224825,15331953,11171218,9749392,14413461,18672905,16281450,16803693,22504788,32058181,321187,64915423,20428618,10338268,8168848,9087729,13082567,8258818,9249419,8462485,6949920,6867276,5516361,8656290,13249637,8776388,6951495,7228923,9327937,7576850,8517248,5229993,6054074,7323771,5147379,7455574,5931757,6484840,8064501,336345,15289506,7103395,10234840,10726517,9601295,15534043,11842805,9330220,11027511,8862830,9827671,9667718,10430112,12441733,12305899,17713250,21298667,31660944,818791,91577617,19383470,8503869,6509491,6168332,5206054,7642091,5957865,7225198,5378379,4889713,5411101,4500385,3839767,4482072,4139495,7347291,4513633,4467302,3656188,4608507,5866684,4453276,6658281,4197165,3243983,5965696,4574568,245640,10580142,14148307,10680751,20041109,13550725,12069325,8788177,14608332,14398158,14467364,9444304,10040013,7689284,7596954,8926393,14732418,20035653,17661933,352052,42970203,21982157,8778634,9494996,8021829,7946260,7376625,7333547,8703505,8737601,9031823,6572489,7271822,6006396,5826419,5221268,6061812,5152340,7943402,7793253,9778239,10817850,7726624,6842435,9246645,6968050,7395478,9169841,136574,43107631,32012217,23735332,15602675,15075650,15083032,15071439,10966673,15322593,21089477,23127348,24189574,17259687,12130963,12269035,14449530,24150020,31261587,541213,54866122,27168814,9347208,9474849,11192649,17995633,16425413,15094366,11825269,17565469,16408427,17643475,7477896,9613491,10099876,9567362,9194934,8300120,11068814,8925156,6924288,6043919,5846681,7745061,11530858,12084169,8483099,4866335,162343,12208459,9489403,9763807,10956034,13046412,11578937,34095183,18328200,12441362,8591715,9089862,11360221,9976365,9746983,9999720,15993056,15300719,21335870,335284,50006885,15695591,10212145,12959296,10462300,7647362,12077396,11514714,9047939,7080846,9007616,8516299,7308022,8554790,8135330,5829123,4786024,7370242,7574679,6453320,5538585,3027750,4600613,5271145,4383947,4302393,4865772,4091444,65875,11599216,8378124,9555076,8579121,9134316,10270468,11096794,13010134,8621235,8288465,10737615,8801780,13127176,11218434,9513543,13362040,18893101,19485250,438788,40416561,18763381,13671422,17440432,16100752,8822962,5790324,6832026,9759247,7168881,4713298,4970504,6331663,5912988,8346477,6222490,7585698,7279487,5920498,7625023,4856238,4375705,4204360,5342408,4435081,4444490,4772422,3658293,50414,10132445,8563878,10309778,6844906,9761317,8988166,8683626,7408349,9078270,7880707,11930999,9105576,8214434,9060135,12572553,20572841,17113799,20581233,356817,41861594,33324296,15493285,16639597,18865155,17134359,12152158,12378567,14436148,10362211,10176725,11231848,11183278,7167043,6171986,5413213,4942715,4585878,3763334,4325035,4688446,6188808,6067642,6919273,8882123,8740226,12348106,15952242,859723,25400118,12335166,12035021,16387550,11371991,8819663,10730769,9802143,9524157,11130602,12387944,10660100,17864828,22257324,23652270,19904324,15732537,22028301,392983,50605437,17152233,9529319,8925327,7537132,8150879,5498626,7309082,5829372,5708636,6783407,8313923,8099959,6570850,7188350,8245544,7436835,7192243,7237818,5632696,4434368,7798470,6413191,5699314,3310205,4372768,4016505,5154726,96128,15003363,8409246,8243806,7974718,9133967,6720135,6936715,8082098,8705135,8310808,10451224,14971861,24141152,12132309,12981943,9877674,10075184,15875368,528990,35768776,12885299,8489376,11377555,12638856,7418477,6499675,6942597,7216575,7262631,6005937,9729789,13783955,8385196,18238337,18161578,11161658,9370252,7203120,9490707,9103368,10378953,10296298,6470858,5505266,4384608,4835326,3225250,52994,16350815,8877397,8488515,10282887,6891088,5883781,8765850,5593556,7632709,7453482,8100895,10612838,8585734,11840869,13680442,10363897,11765718,14856605,215934,36316675,21246042,12777690,10379326,8896282,6769788,6376256,4733766,5973124,6187650,6281419,5030522,5821985,7622329,4405028,4241132,4845439,5851543,5374646,4179363,4139609,4142358,4551724,5212516,3116022,3425273,3406563,4521714,37725,7274486,6994003,7009702,7127010,6284337,6345731,8041457,10409030,9212796,6884723,13774230,8189421,9023027,14600978,10596551,10065828,10305339,16965678,336576,37840009,20414957,9421005,10607883,15363628,8053917,16789632,12440613,6508403,4706954,9328273,6334338,9517334,8339519,6905392,8096589,8688052,12763468,12454269,13320814,12884097,9009071,12608626,6170994,8608275,9853636,8222873,8486410,247344,15793228,14141583,12292146,9282918,11458708,11259109,11735996,10019334,13405545,13549494,11850242,9721750,12556980,12520185,12064510,22339157,23229991,25507350,909711,47867123,43055866,27424274,15193803,18368285,26587863,20895247,14439285,11853766,10087491,7623834,11071388,14623727,10393495,9022393,9418023,9382563,11882304,9557449,7627084,6732330,6135981,6213024,7116075,6642345,5740608,5156977,5499745,161326,13967669,10294383,13689511,11877423,15021159,27783439,14704140,16106424,11692250,10614262,11138023,11322701,9778130,10469498,9977357,12550841,10802195,18241201,375718,42383381,0,0,0,25881117,11162643,8763872,10524921,11095915,10027504,6318846,8029079,6729143,7060364,8746774,6341043,8604640,6852011,5866016,7858412,11662864,11673323,9557272,7127195,6362803,6250022,3920427,4204603,5812134,6241277,5066273,360103,14486145,21146355,20282762,11868467,13313960,20164955,23899669,14387781,10001217,23854482,19548168,16633113,14973148,20942001,16670452,13854573,14012330,18619381,377308,0,36659857,0,0,0,19460892,15327861,18968400,20180330,12316284,13961052,11788647,10345901,15336097,10357712,7548073,7492667,6659323,7922365,6882799,7693608,5818152,7662004,9486901,6888646,10091379,10058490,8252939,6401245,5883978,6281091,7379800,104350,20873688,12967953,15004370,23884997,14684744,12143832,17981141,16854268,11885900,12077222,13694932,13713744,12903985,20970654,21513322,17559488,19518081,26346873,332245,0,0,44920210,0,0,21712951,10596235,11551295,10252618,8786872,9831384,10019628,12707128,11152119,8342942,7984077,5694121,5636304,6660590,9383282,8657264,8668820,6095650,9309622,8738013,9263779,8519832,7794540,6543527,9646423,9561309,8522028,178897,18889244,10009520,10277359,11816059,9246982,9186472,7987232,8085338,6712242,10297577,11128378,12579453,9224985,8949433,10006344,10123244,18777712,15632332,316967,0,0,54710808,0,0,21823423,17026895,11657339,9041796,8094661,7538156,5976690,5895349,5779979,5780852,4577062,6069155,6840465,6371586,4398047,3970280,3724782,4329257,4434581,9384175,9700947,7167724,5050012,4050716,3933204,4915505,4901310,93660,20272807,10394419,9767562,8738647,11820862,11049602,10786396,9040960,10989380,11730368,13418259,10268284,9178674,11453568,10452479,13780630,21594671,22828234,531115,0,106120506,0,0,0,0,14257781,6689425,6338819,6629018,8513812,7408434,5358978,5970842,8694453,6532027,6475379,5578249,4582587,8281475,5208089,9563381,9434217,7596117,8068542,6487179,5656209,6074665,5441266,6978186,4993716,5199652,6757660,167230,13815241,10740492,9725656,12729432,16656078,11432848,11368762,9645664,13009496,12601243,10168974,9043506,8022961,12565139,9844237,11695699,15839927,14319413,852466,0,40150826,0,0,0,18318483,10142927,8816124,11660267,10214632,11018550,10555150,12193618,9209252,10226973,9993137,7226595,7927022,6671185,9799954,5874582,8735432,11509221,7260914,5705459,6593618,7545616,7169161,10769410,10534341,10264806,20599685,881057,36179425,23427542,30560124,29889023,13973914,15850618,14561800,11981455,11731813,13790099,17769735,16700645,14543327,13194365,19166808,20006444,28044660,40277718,758385,55063136,0,0,0,16294010,9411228,7811915,8564068,8770429,8611151,17890179,15585178,16758271,9858882,6422589,7676429,11104757,6825473,7446112,4885629,6918321,10518425,8235005,7190211,7790206,6515852,6296714,8465163,6967365,4826949,5108530,103417,25687617,17111840,11727964,11325443,10652463,9390383,8304997,9179323,12081769,11191021,7376666,12154158,8891890,11351703,11949316,11394069,12602096,15100528,253794,0,0,33452062,0,0,0,11098277,5949992,5084028,6411617,7543764,5354198,4679654,4886966,5146295,7293395,7578132,7825747,7181635,6849500,5699502,4303929,3813965,4160190,5560492,5246881,5378904,5200294,5322920,4984907,5258569,3677525,4273752,153459,11663437,10258064,9765308,11841101,16485414,9038823,10472861,9835786,10157258,9152709,7447418,9743496,11387060,10464748,13091516,15148847,12382976,16894612,411773,0,0,39255286,0,0,0,14045078,6487340,8707932,6731356,6851152,7280112,5817585,7396067,5957211,6791458,5835401,6381660,8272846,5636669,4771593,6326421,5474853,4456031,4895552,6427194,5035846,5619669,4164820,3619099,3382999,4176489,4657774,85273,14329008,8762145,8638729,10611274,9234037,12511273,12861412,8504027,7780186,9504816,11897837,8923401,8605803,12468129,10230751,11087245,12685029,23368758,309696,0,0,41089195,0,0,17077874,13208739,10314468,9781851,9213788,7913147,6704067,7163637,6423254,8400707,11459716,6641150,11031539,8812546,5522480,5925641,4690884,6680982,6857220,5024002,4523893,3580604,4382951,3647555,5044609,5159635,5056294,119361,10508095,6713897,7029871,7089824,10433862,10786392,8870467,8984806,11628580,12638042,13466711,13294009,11408934,11551866,16334113,16361749,12727132,18182972,571016,0,0,35843619,0,0,11707255,8018582,8250008,19554781,14346912,10100377,5448477,8591842,8733890,10881484,8037791,5731211,8097268,6254113,6391663,7116310,10877704,8301520,5891711,4839817,5513888,5098449,4241601,4306148,6429338,6051017,4532263,278672,11453650,10218344,9487648,7951926,7542867,15576736,11198772,11931274,12591278,12678772,14732355,7158555,13965593,11362852,15252843,17800439,15768278,22650337,628563,0,0,61540971,0,0,0,15255683,12022253,13294310,10117230,8952184,6956702,6744479,7154561,7220169,10580827,6429524,8298826,5986135,9820744,10681088,10834926,15937605,13695532,11728535,7760408,8385237,7070885,8822406,9608799,7726201,5769192,9886172,419144,14013863,9544005,14573776,17669081,15143491,13674964,12167091,10621087,8196339,7591376,7456385,8669769,7758200,7380504,7683536,11359340,11306180,16778670,541104,0,0,32026821,0,0,0,16114404,16893579,12292513,17732536,16059613,12894916,7025306,6672890,6271483,8632288,5786754,7450808,6308423,5485828,6308873,7712075,6980707,6296110,7922862,4374414,5724252,4486870,3054130,4020616,3677554,3156482,3551107,136266,11382000,10896044,14164011,14548390,11471439,8920763,6824348,8289397,7757815,9031729,10873267,10218464,8805100,14039707,12808036,12948654,15872580,15419800,407694,0,35061697,0,0,0,15630124,14121786,13893043,11271131,10492764,9269660,10699442,9324522,7988105,7662758,8310246,5494512,6726678,6019308,5425430,7098802,7523122,6545736,6766543,8314082,7197991,7845045,6722443,5827392,5166284,5207116,6049026,69658,13523519,10231460,9120489,12821319,14342402,11488328,11932364,12538948,16480906,13056412,19587815,31090039,16549238,13295901,15479414,16001768,17080836,20837814,1253547,0,0,38705400,0,0,18454049,11830612,8761027,9618179,10338190,6772461,8792421,11080449,9036692,7555413,9223601,6925704,6267463,7421734,5568799,5236205,5657717,3830108,4641995,4314016,4780309,3863455,4050439,4286710,4404381,7369571,8316126,262061,15424049,8193297,15292440,15680574,10656022,17659345,12172761,12478073,13746154,11832556,12520812,31061793,42640594,31473054,24587592,57875445,83017665,38980280,920024,0,57707386,0,0,15024178,9681026,7977826,8828017,11359850,8295400,8105307,7154875,5022684,7815207,7806416,12030264,5211428,4858687,4818298,4773158,4338167,5635105,6307815,6562602,6041554,5130923,5583345,5719415,8794931,5472920,6562427,287971,15586336,9837596,10353292,12934741,9998022,9682538,10778068,9355405,8725043,9452590,10586892,14818840,12377043,9257817,15690816,23307680,17704144,20703348,856563,0,0,35791420,0,0,28540197,11633962,15685844,14787051,10300472,18760858,14701161,10023854,9498804,6757743,6837650,9775560,11443212,13164549,12867050,9579225,6800716,7774406,13468751,13019990,8382871,5829964,5961117,6367512,5030477,6465649,4809319,195463,14522222,10339817,16204832,9232525,10363426,18002213,16005156,12207926,11640022,11377776,11368562,10451533,10540118,14894068,12375904,15630859,10674433,17060337,347297,28919141,0,0,17683711,10219277,7261556,6260100,4935883,5948505,6276834,11981545,13175555,10879538,9500415,18012952,11184056,7556261,6190680,5943305,6211455,6828748,9564931,11430726,5660332,5803284,6673846,4999905,4121000,4317424,4375061,218205,12251501,6019658,11077710,10781896,10175196,10576606,9474384,9047532,9940465,14458334,9872719,7573731,6599961,9494572,11965706,12128943,19518366,14326691,560414,0,0,40359155,0,0,11878807,7197987,8587951,7173983,8318529,10457650,8059446,8645146,7218274,8208640,6425657,5414137,6312273,4858457,4876899,6087776,5003887,7026715,7776381,12997282,9035154,5764942,5021304,4911226,6006459,4684389,5181954,115113,15875007,9186807,9194896,8787199,10307567,11145091,11818918,8846235,8090281,8954659,8544621,8522376,20310900,18018760,14424341,12738450,28413396,29606662,627790,0,0,56536541,0,0,25291720,17349150,13246665,13040598,12270049,14587423,17156059,10813459,10189620,8892613,9981840,20411904,17113692,11375707,12341013,12291961,8407741,5848204,5644870,6481535,5646983,5897580,14013734,13077201,9437819,11871412,9430078,185380,17870114,9051551,9126243,11573713,11826955,9072428,11464047,12290058,16637525,25399004,19466384,14075747,22195885,16585280,14951685,57107036,44251424,37254313,436157,0,0,45520300,0,0,0,18990636,10137756,9939176,10238522,7507796,6715166,8525099,7123452,8483417,9928678,10212104,9238117,8339815,8824830,5983599,9369593,6218511,8131203,7552402,11147321,8968791,7619910,5770574,5465149,5391324,3956415,5555931,46810,12078620,9176206,21470337,21936561,13209639,12597591,11835598,15504141,11360766,16205205,10650719,8639250,9929251,9371988,8829358,8662906,11775113,18558987,254552,0,31166009,0,0,16060724,7089339,5156563,6650404,4591478,6662303,8796797,8116298,8897935,5480240,4443440,5399636,6842298,4297063,5969844,7218781,5863274,5802575,3990038,3079331,4164828,6504465,4334799,5631896,4406728,5964303,4190571,56085,9393337,8160055,7350657,9380853,10874577,10215684,11902783,11359624,10615481,33055714,12583740,13055629,15707858,18543507,16147754,23935197,40803369,28292757,404832,0,0,50953293,0,0,15597320,7765375,8656893,6554117,10337856,9563048,8977273,9990902,10616196,10901261,12086119,11248069,12373541,13018399,16616713,11852640,8242735,10752388,16042938,24282391,15391477,9613319,8515317,12543883,10477218,12685952,8997411,87181,20678404,12043597,13274332,24224651,30004999,16350931,14267467,28319420,25852665,30352351,22970631,18493366,14147353,15654288,15243415,17826466,17051413,23162645,326171,0,0,42631197,0,15318069,6370673,10869173,7564027,6567092,5705386,8002293,7431394,5823902,5509020,6190432,4452135,5054108,5044368,5244973,5400784,4809078,4680762,3435800,5192494,3996811,5536130,3792951,4081708,5343213,5133607,7047673,95790,10706743,7635500,5406156,6123203,8242282,6317029,8557023,8269165,10359456,9987255,8550828,7433472,11037426,8352105,9761158,14858261,14249045,19002094,718611,0,46550159,0,0,18183341,8681541,9672819,8415809,5514490,4813870,5977500,5539785,4997057,8649921,7926655,11986354,14255553,7919575,6218533,6974928,6296016,6193195,15107923,17692743,18948563,20090706,26370924,21334760,23892256,20772988,13870665,329769,30585371,14804208,13576496,19502267,13732296,18310817,26096191,21115658,15952403,19341713,21133942,13047593,11689003,11941008,18746191,50115944,37442539,30720212,1011190,0,0,73670573,0,0,35573814,15848641,15779060,14352256,14095788,14115066,10541199,8992642,7138566,9396586,15718250,9924365,6052464,4384339,4867385,6172421,5336358,5191196,8126539,6804244,5435390,6780661,7269801,6903978,6993195,5898620,7480890,105438,12528970,11019632,9984473,9787563,9687295,8470121,11688233,13823063,12799352,17590173,17723740,18336021,10326774,15075902,26493872,16427398,17009939,23360183,672756,0,0,45061365,0,0,23481433,17325487,10859978,10933421,11438632,14415755,16412379,12180337,14780914,16467420,19422260,14240191,14753841,15482305,11568734,12878978,11824949,13030448,15997781,15327268,13001776,13791470,12217260,11685973,14177292,17266706,15519126,922011,26518727,25493981,21503772,25695316,21584807,23732955,35066737,27947568,17624856,12961459,16243626,13883985,20391788,19279313,18633744,21758734,22995945,26402450,783430,0,0,57836181,0,0,0,24351138,11374042,10863563,13748533,13697180,9489706,7935188,13898913,12221231,15585512,13819256,7915322,8040661,8985881,5756133,7209168,8956107,8701270,11759875,25396889,12965342,11475703,17834213,15299801,12556105,9810417,13442045,173651,33280609,13731278,37459728,25438131,11846537,15406069,32792863,51444202,29432089,18300831,21580217,16002396,12695080,15108911,11278811,12268821,15257113,17271152,484090,0,0,42857271,0,0,0,23796157,11039095,8752624,6650569,10330937,8927119,5805777,10590787,8167915,6994496,5530120,5958277,6261376,5951414,5632312,4658414,7971363,7181538,11446680,8333366,5824341,5568250,9303225,9608075,6775945,3645241,5013296,122855,12821008,8657350,6439847,6164335,6324851,9545015,10841352,5980116,9600710,9850097,8222659,15426018,11855704,30476800,11712699,15488524,24706174,25214216,655729,0,51970972,0,0,16733320,9534113,8649167,9502220,9117491,8527336,8422998,5822777,6679162,5541713,6672776,3865457,4837217,5945313,4876703,6002521,6157544,5252353,4381875,7059798,5853628,4081811,5072493,4053125,2793739,3390230,5649056,50442,15753274,9378263,8924170,11298145,13527763,10277832,12344296,11441614,9458636,9352496,10332917,10578801,11413802,11475104,17799479,30989823,24187280,55212367,1025931,0,0,83471716,0,0,0,0,37875491,18710930,12465661,18958738,20035826,15227967,9758182,11589364,9054289,11495193,13942758,6957155,6192022,9411973,13326451,7727183,6770110,6578403,16192140,17510472,16090230,23788254,7816962,7182924,5450341,5366729,8141888,115117,15934870,11298845,26038360,21158788,20980085,16513678,12497255,13521905,10803993,8978503,9801044,10563814,7961870,9258385,9426293,17556892,16249568,14253714,552050,0,0,37152258,0,0,0,17923226,7632638,10604038,11137550,8051018,6370680,7101810,7690883,7160549,7565145,7724178,6229242,8266774,5038611,4339726,4571081,4827802,6981789,5408160,6280495,4847671,5009841,7787095,5152147,6529287,4843523,4232551,34949,19276953,14683411,16984363,9001817,10182160,11146023,10426816,9668555,9501594,12132312,19236149,9178891,9269777,12868058,10114849,13724149,13081173,20129524,383903,0,37124844,0,0,18228751,16476528,15564398,10194340,21425539,16086792,10847726,10349602,10592472,15295658,12789048,9895420,8206999,7054042,5477990,6614491,7596489,11534241,10030469,12044793,9610155,10869081,9503771,18541442,16542675,11433654,17133613,1053409,33428622,32003098,29500935,19811331,31121433,14212627,16976949,14940257,18780388,16231735,12594208,16483031,12728945,14710204,13497937,12882752,13272228,17702300,412878,0,0,32096478,0,0,0,42776097,20728299,16391225,15638031,15859269,16961178,12695438,11460654,10005969,10323585,24987471,21658953,13912269,10692217,9620135,7918845,7232877,8977130,5027083,8431095,9863109,6963288,5631697,5085008,5489157,4752859,6573147,174025,15282377,11541139,11514951,8332416,9985049,8909809,9414356,8639010,8007890,8233239,7641263,12975944,17248198,12008496,15837988,11755243,11798184,16166439,292887,0,0,65872529,0,0,17388934,12745848,12949764,9654641,8896890,9788206,12059175,14322558,18067134,9330666,6899906,6401623,5525649,6711600,7382037,8823583,8918199,7562014,10593517,10337844,8760483,7236732,7269112,7993164,7454811,9905987,18327736,280636,20154778,23245482,20409710,16451422,19530250,28233086,22193366,16234635,23739869,15017031,16317892,18521021,20661545,16215530,20494382,19552065,15226982,15123643,274420,0,0,33129330,0,0,0,21654651,15464270,14193381,11011303,9026690,10689492,11345972,8924898,9053422,8990422,8862146,6885466,6113976,7095395,8494906,8930770,6457551,5769618,5945952,8366208,6870185,5981488,4524490,5368605,5803411,5323688,5629287,124763,16939252,10661149,10034112,11358735,10572767,15968262,17806335,12770729,18726159,8614869,10408881,9103757,15152020,17626114,20111057,17433558,17444483,22326557,391432,0,0,37369845,0,0,0,29725226,22116131,19398364,13296632,13801345,10803228,12890204,20643293,16362413,12594780,11201130,11886788,16238433,11182393,10229276,8224791,9070141,8884416,7883816,9066321,6889740,6848074,9015928,6422100,6472504,5457865,5775602,78321,18631856,10923886,19502705,18061319,14058832,14719314,10382945,8907034,12230194,15926304,11376945,9147004,20116242,15426847,13042120,16399384,18075151,20986158,501599,0,0,39803649,0,0,17942722,10915296,12957777,15610807,10714558,9371468,7838854,7381170,9642747,8979264,6665377,7113259,6101054,6381521,5173349,5056244,5192116,5751560,6593431,4756026,5237675,5899277,6183818,5562385,5186783,3803866,4566505,98600,15018273,11336780,9156874,8307496,12895778,8655953,9448610,8778741,7408165,8696984,12311937,9940721,9413972,12675025,22183805,19413998,13913379,22384508,829078,0,0,41428930,0,0,0,11328895,12026408,13180064,11314104,9762488,8643839,11644764,7903981,6599059,13885652,10813952,17986787,24887335,16208748,9753232,7683935,8311353,5730556,7114379,8875536,8219407,6439169,6817837,5002759,6409860,3832273,4438362,149886,12224820,8283693,7695397,11647881,12716475,8955457,9976105,11300916,10210473,10345918,9874340,13316230,9850118,8403962,13859247,18898554,14470788,23045317,511873,0,0,49170483,0,0,0,21366820,10306524,10547227,11352136,12891753,12085506,11296486,10826631,8486663,6290002,6018662,7686954,8560729,6109839,8799961,7969265,6972355,11429928,7573937,5773549,5424128,5040891,6261944,9225861,8481089,7148171,6402223,80946,17959512,12346355,14273823,11901793,18678846,14435229,16473011,13760067,16130749,26246725,32088198,25078498,19969407,15567111,31190818,25806279,16142752,19667530,433565,0,0,34370807,0,0,29514627,18549457,13730068,12574043,11091905,11023530,10568449,12890408,11392152,10679031,9343880,10379897,9861605,8983362,7603613,6864145,5534672,6889207,6628546,6332948,5650638,5293804,6119097,7690519,7828063,5278897,6145074,98817,17088889,11873454,12499003,12522450,11520099,15084415,12439692,14767686,14504289,11853703,12977600,17835074,12107065,11566141,11628523,12683715,21187311,20991329,399971,33844535,0,0,0,0,12324058,14403380,9951811,8806288,8988623,10899101,15371433,12831431,9074061,14314138,7536089,7758332,6827901,6255909,5575573,5817363,3997140,5040915,5174274,5325073,6627856,4813794,5300263,4675245,4583795,5634869,6338302,221026,17408767,12667317,8734595,13102991,9928013,12354038,7414885,8126421,11713835,13370977,9698473,7936773,9290108,9943459,9787167,12192833,12588316,14831793,237837,0,0,36764270,0,0,13787754,9187961,10448866,9765853,6821030,7281536,8131657,8034394,5397911,6316388,7206235,5384047,7681456,8776652,7937466,8442888,7767459,9731431,9242557,6690253,6948238,6197659,7801384,5997004,7685647,6177373,5919637,83842,20576776,11190709,9586198,10469784,13696004,16277944,12000824,18304369,26987408,17850191,13629063,11753050,33534838,45018134,25083433,20390301,28688934,32119644,441121,0,0,61902907,0,0,0,22136721,10556530,11257314,11015846,7678161,8292131,12541253,15798370,22254977,11203730,7861428,6332358,11279810,21098537,10922993,5873262,5507669,5841198,4373160,3962048,6221672,11330789,5369704,5129486,10585192,9352924,7340914,105826,17959819,11893188,8329095,8584581,9703425,9746628,10279204,12695398,16260078,27046443,27329091,22487948,16152159,19966915,17964093,20514006,31422470,26005043,313614,0,0,49925036,0,0,15324764,7573832,7130136,7433360,6962828,4852368,4314599,5387786,5020721,8277097,5961263,5850720,5256415,4142549,4293642,4314750,6599879,6381777,5455235,6768319,5826282,5736473,5695232,10340932,5874148,5450266,4371264,28511,12436457,8090603,6786309,9143285,10240366,17501676,12139248,7715865,5913455,10780834,9368944,18554884,13441822,6469532,11000859,12745815,8648057,11623917,140626,0,0,33403946,0,0,11291676,6778198,8555661,7552613,5941185,7533204,8751232,5669174,7161105,13684729,14091200,11647988,7636978,7711657,6215489,5198827,4373411,4427961,6347595,4431995,3950802,3097781,3285016,3858176,4556194,4956070,4269452,39305,15776542,9778920,8968244,10488676,8361170,7138851,9202043,9766942,9494332,20565575,9462584,13381612,15324188,17971259,22119823,16893591,14852519,14922720,397684,0,32857505,0,0,0,8601803,5336763,6174829,5717067,4334441,7570129,9977597,6495787,5417733,4367597,4285208,4944134,5478839,3859966,5173991,4273681,5609394,3417093,6653138,5644907,6179561,6116243,7635156,5035435,5365924,3708089,5005590,102735,18831632,9588984,7844253,12099150,11323956,9427717,6382983,7971113,7451469,15366400,10036662,13523446,11076279,8002617,9426919,11648880,11917828,20031042,221561,0,0,36172732,0,0,0,14852090,9570806,5642515,8092914,4888866,6698846,4197587,4819991,4655787,3723254,4093066,5061214,5084410,3619809,3798978,3446614,3151731,4393265,3910735,3673147,3418240,4533712,4760114,4790863,3715753,3786191,3367894,106346,7599135,6812655,7719103,5374250,8770684,5836145,8362023,6206276,9286798,9537850,8227067,12846985,10989183,7294186,9707205,17210513,14364029,18432573,190557,0,0,28892827,0,0,15041621,8198919,7294748,5971940,7227787,12139260,7963938,5072000,4802152,3979338,5199897,5579256,6928762,4108112,5091792,4045515,4533787,3566910,4640233,6046671,4626964,3371890,8148185,12865728,6343190,5978399,5810576,47856,22171603,39801937,23141127,20059023,40639421,48122837,29652056,21468307,17995633,14094657,18744329,20152717,23579332,22231356,19758655,19094257,25069338,27500643,1098842,0,0,38781731,0,0,0,51248141,30270336,17507354,16047931,16728568,13468331,11854320,11353387,11259853,12804072,11158963,12199085,12376422,13176673,9039192,10471843,8722628,8840363,7155048,7683998,6510364,7841916,6211864,4635733,5179429,4759134,6258752,133610,14675633,16111774,16184763,20379412,17009954,15125595,13563824,11506894,16541824,13074538,18140499,18987280,13691143,13771229,13541668,17800291,21053868,25494078,599199,0,0,37009242,0,0,0,0,21009140,12150831,9783022,10066263,10601434,11585123,9387068,10537262,12014567,12393214,8938496,8366061,9488122,13067506,18338656,9319831,8983806,9876349,8400678,6768483,10389162,8443663,8487798,5843281,8353727,6558321,6970480,39830,20508992,19536695,19110578,15785948,19933999,17810798,22206245,29174390,20053240,12969797,13484809,14287863,26755926,14919916,11978612,14335643,14415598,17116746,583006,0,0,42334355,0,0,12859090,13118580,8773264,9968590,9687573,6825503,6949000,7002526,4591165,7137609,6283364,7533302,8599401,7968239,7080237,7059844,5203560,4635874,4604589,5594678,4257694,8455767,5186329,5859111,4600396,6152121,5730820,114441,14670010,10242418,11892927,13415905,15574766,14687424,22288155,18883123,22571139,31418460,30667804,26303694,18217093,14563365,15143634,17449216,25618313,26912711,399667,0,0,44664784,0,0,0,0,23608598,22848634,12612156,10193172,11626960,9156200,8543593,8538056,8626556,8112836,5675158,8890524,6006001,4313843,4910610,7116526,4313949,4337975,4322989,4102729,4053886,4478323,5646163,5147687,5086325,6124323,5019471,112151,13642839,10902316,13166936,13020559,13553883,9119295,12324415,13952099,9808227,11303033,12218549,10500699,15560111,11913572,16318066,15524648,12590027,19533553,539411,0,0,35212766,0,0,13663658,8283156,7038593,5977085,8824285,7762723,7566421,10651359,11546034,14084709,8719873,9115896,10698193,4244232,6434961,5848602,5100702,7041436,4601871,5352419,5298448,5325104,5030806,4256249,4333028,5624195,5069252,114053,13913821,8399930,7317009,15258946,14533399,19266615,16224524,14194607,14997120,15680501,19182142,23868923,18344521,13013536,13388719,32613353,21289560,27329646,660274,0,0,55099993,0,0,0,34658074,15222530,13448126,11598173,13833512,9811940,16127909,10824534,7830510,8783304,8682546,10267931,10352825,8975898,7816793,6560552,5737775,6025331,8536674,7309807,6068007,4686764,5559026,4657428,4586005,5057510,4866086,119129,11213011,8735010,8585379,8897512,19518759,12702448,10976199,10378141,11669619,8728528,13370803,9063994,9762367,11580067,12890580,16699545,17526605,17357972,407157,0,0,41947209,0,0,12716457,8867429,9647534,8979587,8235429,7372783,10319677,13009644,9943355,8940431,7011601,7762155,8637487,7728559,5979540,5450475,4474933,6609423,5161753,4199250,4342893,6000603,5447422,5296323,5819785,6336042,4803227,196216,21423142,16485271,10400988,13673398,11329751,12890116,9027244,8435886,13434224,8923912,18532786,14629905,10834729,12536729,11137228,14686471,20846371,25675515,354450,0,0,46440722,0,0,18455875,9824489,12593564,9342058,9416153,10015263,9162268,9205155,6065744,9043483,7503481,6772002,8049197,5750610,4354856,7868169,6842092,8515857,6734670,6302748,11651240,6309132,4456056,5493239,8937635,9278665,7634960,197478,11761868,10978536,15715880,9370833,10959450,11697944,9139500,8656334,9214576,10008714,13448027,15591338,15820848,10462355,12179996,21244168,17854499,17687065,213755,0,40262510,0,0,0,12816825,5268606,9187714,7140829,5742738,6415032,6733046,6391857,5614870,6721578,6163715,4056629,4624105,4459933,8142497,12980267,10045647,7441262,5205680,5661023,4959090,6161079,5594806,4768619,3668685,4444570,3291461,111100,10183735,6531070,9077358,8244283,12419994,8094132,8314281,10619931,9135542,10776664,14062545,10021944,11419785,13379364,10209737,15673242,12783659,14067736,371044,0,0,33871890,0,0,16644137,13637783,7833625,8414885,9970255,7979964,9754806,14123353,13298290,9101613,8338401,13377368,10310817,6398715,6386145,5952757,6138101,5496212,5632764,5351128,6249958,4112866,4838458,4514058,5815733,5670692,3729744,147133,10787026,7377213,6471566,7874884,15032609,12048629,11354592,8657169,8771579,9962062,9918892,14082900,11952357,11200767,17166532,11507219,16882133,17202552,581572,0,0,39276981,0,0,0,0,10047723,6076097,5735321,5259580,4884684,4902002,8675636,8746701,6127945,7362700,6563429,4688421,5808675,5344299,5287357,7237312,7227082,8779089,10002869,6902433,6152054,5735145,4730406,5897890,6331249,3902579,5433635,100542,16026032,6186984,8752118,12729225,8954887,8724842,9882928,12860959,9401540,7391633,7158281,7579074,10758690,7845359,8234545,11646442,12764821,13863089,314800,0,0,28166551,0,0,0,0,15611477,8384261,8633069,8840393,9419497,8872973,8534557,16361219,18892200,14946325,25140759,16657051,14659055,8677953,8686206,8725280,5738688,6477689,7027210,7614002,4885610,5340207,5418133,6021135,5368016,9780468,11076260,177168,12873773,9411557,8418653,11390984,21784000,17768416,12252080,12586250,12414644,9095994,8426127,9769697,12670298,24690435,28305600,20497637,20207572,39316278,675979,0,0,59734274,0,0,0,15249358,7793069,10431794,9122075,10071319,8297023,9705054,11531612,9736896,8616008,13196450,9959445,8448194,7810859,11122522,4983176,5327277,5124411,8785219,6739402,7170980,4664946,4248950,3588786,3685839,3737613,3833018,245380,10193703,6658264,9848252,11822235,11037123,11315524,20915574,13984228,29196011,55807848,47390245,25209956,17083749,21461686,23266786,24919666,30994222,34363961,453273,0,0,44569689,0,0,0,20046523,11091773,11738649,12390739,10960099,10275120,8388108,11714877,9430528,7938346,15239294,12882535,8219918,5502356,6060349,6041065,4661399,4712265,4680390,6103121,4379776,4052393,4870866,3484026,3727255,3472146,6777949,183603,13331821,8801317,12495555,9911601,15802333,19455722,14240343,11046977,11205057,18608287,17708161,13603069,10064504,12712501,16993946,17342631,15156223,16249814,521696,0,0,49541273,0],
      "s": "ok"
    }
  },
  "strategy": {
    "warmup_bars": 150,
    "indicators": {
      "sma20": {
        "type": "SMA",
        "source": "market_data.close",
        "period": 20
      },
      "ema5": {
        "type": "EMA",
        "source": "trade_data.close",
        "period": 5
      },
      "bb": {
        "type": "BB",
        "source": "trade_data.close",
        "period": 20,
        "stddev_multiplier": 2
      },
      "macd": {
        "type": "MACD",
        "source": "trade_data.close",
        "fast_period": 12,
        "slow_period": 26,
        "signal_period": 9,
        "histogram": "line"
      },
      "mfi14": {
        "type": "MFI",
        "source": "trade_data",
        "period": 14
      },
      "trade_sma20": {
        "type": "SMA",
        "source": "trade_data.close",
        "period": 20
      }
    },
    "entry": {
      "require_flat": true,
      "require_no_pending": true,
      "signal_windows": [
        [
          "09:05",
          "11:20"
        ],
        [
          "13:05",
          "14:00"
        ]
      ],
      "conditions": {
        "LONG": {
          "all": [
            {
              "gt": [
                {
                  "ref": "market_data.close"
                },
                {
                  "ref": "sma20"
                }
              ]
            },
            {
              "gt": [
                {
                  "ref": "ema5"
                },
                {
                  "ref": "trade_sma20"
                }
              ]
            },
            {
              "gt": [
                {
                  "sub": [
                    {
                      "ref": "trade_data.close"
                    },
                    {
                      "ref": "bb.upper"
                    }
                  ]
                },
                0
              ]
            },
            {
              "lte": [
                {
                  "sub": [
                    {
                      "ref": "trade_data.close"
                    },
                    {
                      "ref": "bb.upper"
                    }
                  ]
                },
                3
              ]
            },
            {
              "gt": [
                {
                  "ref": "macd.line"
                },
                0
              ]
            },
            {
              "gt": [
                {
                  "ref": "macd.line"
                },
                {
                  "ref": "macd.line",
                  "shift": 1
                }
              ]
            },
            {
              "gte": [
                {
                  "ref": "mfi14"
                },
                55
              ]
            }
          ]
        },
        "SHORT": {
          "all": [
            {
              "lt": [
                {
                  "ref": "market_data.close"
                },
                {
                  "ref": "sma20"
                }
              ]
            },
            {
              "lt": [
                {
                  "ref": "ema5"
                },
                {
                  "ref": "trade_sma20"
                }
              ]
            },
            {
              "gt": [
                {
                  "sub": [
                    {
                      "ref": "bb.lower"
                    },
                    {
                      "ref": "trade_data.close"
                    }
                  ]
                },
                0
              ]
            },
            {
              "lte": [
                {
                  "sub": [
                    {
                      "ref": "bb.lower"
                    },
                    {
                      "ref": "trade_data.close"
                    }
                  ]
                },
                3
              ]
            },
            {
              "lt": [
                {
                  "ref": "macd.line"
                },
                0
              ]
            },
            {
              "lt": [
                {
                  "ref": "macd.line"
                },
                {
                  "ref": "macd.line",
                  "shift": 1
                }
              ]
            },
            {
              "lte": [
                {
                  "ref": "mfi14"
                },
                45
              ]
            }
          ]
        }
      },
      "any": [
        "LONG",
        "SHORT"
      ],
      "on_conflict": "SIGNAL_CONFLICT",
      "reentry": "next_bar_close_after_exit",
      "pending": {
        "max_execution_bars": 1,
        "cross_lunch": false,
        "cross_cutoff": false,
        "cross_session": false
      }
    },
    "exit": {
      "targets": {
        "LONG": {
          "TP1": {
            "add": [
              {
                "ref": "position.entry_price"
              },
              6
            ]
          },
          "TP2": {
            "add": [
              {
                "ref": "position.entry_price"
              },
              12
            ]
          }
        },
        "SHORT": {
          "TP1": {
            "sub": [
              {
                "ref": "position.entry_price"
              },
              6
            ]
          },
          "TP2": {
            "sub": [
              {
                "ref": "position.entry_price"
              },
              12
            ]
          }
        }
      },
      "intrabar": {
        "conditions": {
          "PROTECTIVE_STOP": {
            "type": "protective_stop",
            "distance_points": 6,
            "trailing": {
              "activate_after": "TP1_fill",
              "distance_points": 6,
              "seed": "TP1_price",
              "extrema_from": "bar_after_TP1",
              "update_at": "bar_close",
              "effective_from": "next_bar",
              "combine": "tightest",
              "allow_widening": false
            },
            "quantity": "remaining"
          },
          "TP1": {
            "type": "target_touch",
            "level": "TP1",
            "quantity": {
              "if_initial_quantity_eq": 1,
              "then": "remaining",
              "else": {
                "floor": [
                  {
                    "div": [
                      {
                        "ref": "position.initial_quantity"
                      },
                      2
                    ]
                  }
                ]
              }
            }
          },
          "TP2": {
            "type": "target_touch",
            "level": "TP2",
            "requires": "TP1_filled",
            "quantity": "remaining"
          }
        },
        "any": [
          "PROTECTIVE_STOP",
          "TP1",
          "TP2"
        ],
        "priority": [
          "PROTECTIVE_STOP",
          "TP1",
          "TP2"
        ]
      },
      "bar_close": {
        "conditions": {
          "MARGIN_BREACH": {
            "lt": [
              {
                "ref": "account.equity"
              },
              {
                "ref": "account.required_margin"
              }
            ]
          },
          "FORCED_EXIT": {
            "gte": [
              {
                "ref": "clock.local_time"
              },
              "14:20"
            ]
          },
          "TIME_STOP": {
            "gte": [
              {
                "ref": "position.held_bars"
              },
              18
            ]
          }
        },
        "any": [
          "MARGIN_BREACH",
          "FORCED_EXIT",
          "TIME_STOP"
        ],
        "priority": [
          "MARGIN_BREACH",
          "FORCED_EXIT",
          "TIME_STOP"
        ],
        "quantity": "remaining",
        "fill_policy": "next_open"
      },
      "flat_by": "14:30",
      "allow_overnight": false
    },
    "sizing": {
      "type": "risk_and_margin",
      "risk_fraction": 0.01,
      "stop_points": 6,
      "margin_buffer": 1.1,
      "max_contracts": 5,
      "pyramiding": false
    },
    "daily_limits": {
      "stop_new_entry": {
        "any": [
          {
            "lte": [
              {
                "ref": "day.net_pnl"
              },
              {
                "mul": [
                  {
                    "ref": "day.start_equity"
                  },
                  -0.02
                ]
              }
            ]
          },
          {
            "gte": [
              {
                "ref": "day.entry_fill_count"
              },
              3
            ]
          }
        ]
      }
    }
  },
  "execution": {
    "entry_fill_policy": "next_open",
    "slippage_rate": "0"
  },
  "initial_cash": "100000000",
  "accounting": {
    "model": "contract",
    "contract_multiplier": "100000",
    "margin_rate": "0.17",
    "pit_rate": "0.001",
    "exchange_fee_per_contract": "2700",
    "clearing_fee_per_contract": "2550",
    "broker_fee_per_contract": "0"
  }
}
""")

if os.getenv("BACKTEST_REPORT_START") or os.getenv("BACKTEST_REPORT_END"):
    payload["report"] = payload.get("report") or {}
if os.getenv("BACKTEST_REPORT_START"):
    payload["report"]["start_date"] = os.environ["BACKTEST_REPORT_START"]
if os.getenv("BACKTEST_REPORT_END"):
    payload["report"]["end_date"] = os.environ["BACKTEST_REPORT_END"]

In [4]:
request = Request(
    f"{API_URL}/api/backtests",
    data=json.dumps(payload).encode("utf-8"),
    headers={"Content-Type": "application/json"},
    method="POST",
)
try:
    with urlopen(request, timeout=120) as response:
        result = json.load(response)
except HTTPError as error:
    raise RuntimeError(f"API {error.code}: {error.read().decode('utf-8')}") from error

if result.get("schema_version") != 2:
    raise RuntimeError("Notebook yêu cầu kết quả schema_version=2 của API hiện tại")

required_groups = {"metadata", "summary", "fills", "trades", "open_position", "signals", "orders", "equity_history"}
missing_groups = required_groups - result.keys()
if missing_groups:
    raise RuntimeError(f"Response thiếu nhóm dữ liệu: {sorted(missing_groups)}")
with urlopen(f"{API_URL}/api/backtests/{result['metadata']['run_id']}", timeout=120) as response:
    reloaded_result = json.load(response)
if reloaded_result != result:
    raise RuntimeError("GET result khác POST result của cùng run_id")

## 1. Dữ liệu và cấu hình lần chạy

- `run_id`: định danh để đọc lại kết quả qua API.
- `input_hash`, `policy_hash`: mã băm đầu vào và chính sách đã dùng.
- `accounting_profile`, `money_unit`, `quantity_unit`: mô hình và đơn vị tính thực tế.
- `report_range`: kỳ báo cáo API đã áp dụng; `warmup_bars`: số nến lịch sử trước kỳ báo cáo, khác với yêu cầu `strategy.warmup_bars` trong payload.
- `contract_map`, `data_gaps`, `assumptions`: map hợp đồng, khoảng thiếu dữ liệu và giả định backend đã ghi nhận.

In [5]:
metadata = result["metadata"]
display(Markdown(f"**Đầu vào:** payload khai báo trong notebook · **Phiên bản kết quả:** `{result['schema_version']}`"))
display(pd.DataFrame([{key: metadata.get(key) for key in (
    "run_id", "input_hash", "engine_version", "accounting_profile", "symbol",
    "resolution", "timezone", "price_unit", "money_unit", "quantity_unit", "policy_hash", "input_origin",
)}]))
display(Markdown("**Kỳ báo cáo**"), pd.DataFrame([metadata["report_range"]]))
display(Markdown("**Mô hình tính tiền**"), pd.DataFrame([metadata["accounting"]]))
display(Markdown("**Quy ước thời điểm khớp**"), Markdown(metadata["fill_time_convention"]))
display(Markdown("**Chỉ báo đã khai báo**"), pd.DataFrame(metadata["indicator_specs"]).T.reset_index(names="name"))
display(Markdown("**Nến lịch sử trước kỳ báo cáo**"), pd.DataFrame([metadata["warmup_bars"]]))
display(Markdown("**Map hợp đồng**"), pd.DataFrame(metadata["contract_map"]))
display(Markdown("**Số khoảng thiếu theo nguồn đã kiểm tra**"), pd.DataFrame([
    {key: len(value) for key, value in metadata["data_gaps"].items()}
]))
display(Markdown("**Giả định đã áp dụng**"), pd.DataFrame([metadata["assumptions"]]))
display(Markdown("**Cấu hình chiến lược và khớp lệnh gửi tới API**"), Markdown(
    "```json\n" + json.dumps({key: payload.get(key) for key in (
        "strategy", "execution", "initial_cash", "report",
    )}, ensure_ascii=False, indent=2) + "\n```"
))
display(Markdown("**Trạng thái đánh giá**"), pd.DataFrame([result["evaluation_status"]])
        if "evaluation_status" in result else Markdown("_API không trả bản ghi đánh giá._"))

**Đầu vào:** payload khai báo trong notebook · **Phiên bản kết quả:** `2`

,run_id,input_hash,engine_version,accounting_profile,symbol,resolution,timezone,price_unit,money_unit,quantity_unit,policy_hash,input_origin
0,45531304-06a0-4b61-ad42-043ecf956f9c,b4f1b8d2ae56e1aaae6c8f41587bc857f2af965e860186...,0.2.0,contract_v1,VN30F1M,5,Asia/Ho_Chi_Minh,None,VND,contracts,f89af2e5ff28bcc1e089f68a759e2c874a786d0c6e1fc5...,caller_provided

**Kỳ báo cáo**

        start         end
0  2026-03-16  2026-09-15

**Mô hình tính tiền**

,model,contract_multiplier,margin_rate,pit_rate,exchange_fee_per_contract,clearing_fee_per_contract,broker_fee_per_contract
0,contract,100000,0.17,0.001,2700,2550,0

**Quy ước thời điểm khớp**

Open for market/gap fills; bar Close for intrabar touches

**Chỉ báo đã khai báo**

,name,type,source,period,stddev_multiplier,fast_period,slow_period,signal_period,histogram
0,sma20,SMA,market_data.close,20,NaN,NaN,NaN,NaN,NaN
1,ema5,EMA,trade_data.close,5,NaN,NaN,NaN,NaN,NaN
2,bb,BB,trade_data.close,20,2,NaN,NaN,NaN,NaN
3,macd,MACD,trade_data.close,NaN,NaN,12,26,9,line
4,mfi14,MFI,trade_data,14,NaN,NaN,NaN,NaN,NaN
5,trade_sma20,SMA,trade_data.close,20,NaN,NaN,NaN,NaN,NaN

**Nến lịch sử trước kỳ báo cáo**

   trade_data  market_data
0           0            0

**Map hợp đồng**

   contract_code expiry_date  expiry_unix
0      VN30F2601  2026-01-15   1768410000
1      VN30F2602  2026-02-13   1770915600
2      VN30F2603  2026-03-19   1773853200
3      VN30F2604  2026-04-16   1776272400
4      VN30F2605  2026-05-21   1779296400
5      VN30F2606  2026-06-18   1781715600
6      VN30F2607  2026-07-16   1784134800
7      VN30F2608  2026-08-20   1787158800
8      VN30F2609  2026-09-17   1789578000
9      VN30F2610  2026-10-15   1791997200
10     VN30F2611  2026-11-19   1795021200
11     VN30F2612  2026-12-17   1797440400

**Số khoảng thiếu theo nguồn đã kiểm tra**

   trade_data  market_data
0           0           96

**Giả định đã áp dụng**

,five_minute_default,alignment,missing_data,price_limit_check
0,close=open+300s; available=close,distinct market bars with available_at <= deci...,"reported, never filled",not performed; reference price not supplied

**Cấu hình chiến lược và khớp lệnh gửi tới API**

```json
{
  "strategy": {
    "warmup_bars": 150,
    "indicators": {
      "sma20": {
        "type": "SMA",
        "source": "market_data.close",
        "period": 20
      },
      "ema5": {
        "type": "EMA",
        "source": "trade_data.close",
        "period": 5
      },
      "bb": {
        "type": "BB",
        "source": "trade_data.close",
        "period": 20,
        "stddev_multiplier": 2
      },
      "macd": {
        "type": "MACD",
        "source": "trade_data.close",
        "fast_period": 12,
        "slow_period": 26,
        "signal_period": 9,
        "histogram": "line"
      },
      "mfi14": {
        "type": "MFI",
        "source": "trade_data",
        "period": 14
      },
      "trade_sma20": {
        "type": "SMA",
        "source": "trade_data.close",
        "period": 20
      }
    },
    "entry": {
      "require_flat": true,
      "require_no_pending": true,
      "signal_windows": [
        [
          "09:05",
          "11:20"
        ],
        [
          "13:05",
          "14:00"
        ]
      ],
      "conditions": {
        "LONG": {
          "all": [
            {
              "gt": [
                {
                  "ref": "market_data.close"
                },
                {
                  "ref": "sma20"
                }
              ]
            },
            {
              "gt": [
                {
                  "ref": "ema5"
                },
                {
                  "ref": "trade_sma20"
                }
              ]
            },
            {
              "gt": [
                {
                  "sub": [
                    {
                      "ref": "trade_data.close"
                    },
                    {
                      "ref": "bb.upper"
                    }
                  ]
                },
                0
              ]
            },
            {
              "lte": [
                {
                  "sub": [
                    {
                      "ref": "trade_data.close"
                    },
                    {
                      "ref": "bb.upper"
                    }
                  ]
                },
                3
              ]
            },
            {
              "gt": [
                {
                  "ref": "macd.line"
                },
                0
              ]
            },
            {
              "gt": [
                {
                  "ref": "macd.line"
                },
                {
                  "ref": "macd.line",
                  "shift": 1
                }
              ]
            },
            {
              "gte": [
                {
                  "ref": "mfi14"
                },
                55
              ]
            }
          ]
        },
        "SHORT": {
          "all": [
            {
              "lt": [
                {
                  "ref": "market_data.close"
                },
                {
                  "ref": "sma20"
                }
              ]
            },
            {
              "lt": [
                {
                  "ref": "ema5"
                },
                {
                  "ref": "trade_sma20"
                }
              ]
            },
            {
              "gt": [
                {
                  "sub": [
                    {
                      "ref": "bb.lower"
                    },
                    {
                      "ref": "trade_data.close"
                    }
                  ]
                },
                0
              ]
            },
            {
              "lte": [
                {
                  "sub": [
                    {
                      "ref": "bb.lower"
                    },
                    {
                      "ref": "trade_data.close"
                    }
                  ]
                },
                3
              ]
            },
            {
              "lt": [
                {
                  "ref": "macd.line"
                },
                0
              ]
            },
            {
              "lt": [
                {
                  "ref": "macd.line"
                },
                {
                  "ref": "macd.line",
                  "shift": 1
                }
              ]
            },
            {
              "lte": [
                {
                  "ref": "mfi14"
                },
                45
              ]
            }
          ]
        }
      },
      "any": [
        "LONG",
        "SHORT"
      ],
      "on_conflict": "SIGNAL_CONFLICT",
      "reentry": "next_bar_close_after_exit",
      "pending": {
        "max_execution_bars": 1,
        "cross_lunch": false,
        "cross_cutoff": false,
        "cross_session": false
      }
    },
    "exit": {
      "targets": {
        "LONG": {
          "TP1": {
            "add": [
              {
                "ref": "position.entry_price"
              },
              6
            ]
          },
          "TP2": {
            "add": [
              {
                "ref": "position.entry_price"
              },
              12
            ]
          }
        },
        "SHORT": {
          "TP1": {
            "sub": [
              {
                "ref": "position.entry_price"
              },
              6
            ]
          },
          "TP2": {
            "sub": [
              {
                "ref": "position.entry_price"
              },
              12
            ]
          }
        }
      },
      "intrabar": {
        "conditions": {
          "PROTECTIVE_STOP": {
            "type": "protective_stop",
            "distance_points": 6,
            "trailing": {
              "activate_after": "TP1_fill",
              "distance_points": 6,
              "seed": "TP1_price",
              "extrema_from": "bar_after_TP1",
              "update_at": "bar_close",
              "effective_from": "next_bar",
              "combine": "tightest",
              "allow_widening": false
            },
            "quantity": "remaining"
          },
          "TP1": {
            "type": "target_touch",
            "level": "TP1",
            "quantity": {
              "if_initial_quantity_eq": 1,
              "then": "remaining",
              "else": {
                "floor": [
                  {
                    "div": [
                      {
                        "ref": "position.initial_quantity"
                      },
                      2
                    ]
                  }
                ]
              }
            }
          },
          "TP2": {
            "type": "target_touch",
            "level": "TP2",
            "requires": "TP1_filled",
            "quantity": "remaining"
          }
        },
        "any": [
          "PROTECTIVE_STOP",
          "TP1",
          "TP2"
        ],
        "priority": [
          "PROTECTIVE_STOP",
          "TP1",
          "TP2"
        ]
      },
      "bar_close": {
        "conditions": {
          "MARGIN_BREACH": {
            "lt": [
              {
                "ref": "account.equity"
              },
              {
                "ref": "account.required_margin"
              }
            ]
          },
          "FORCED_EXIT": {
            "gte": [
              {
                "ref": "clock.local_time"
              },
              "14:20"
            ]
          },
          "TIME_STOP": {
            "gte": [
              {
                "ref": "position.held_bars"
              },
              18
            ]
          }
        },
        "any": [
          "MARGIN_BREACH",
          "FORCED_EXIT",
          "TIME_STOP"
        ],
        "priority": [
          "MARGIN_BREACH",
          "FORCED_EXIT",
          "TIME_STOP"
        ],
        "quantity": "remaining",
        "fill_policy": "next_open"
      },
      "flat_by": "14:30",
      "allow_overnight": false
    },
    "sizing": {
      "type": "risk_and_margin",
      "risk_fraction": 0.01,
      "stop_points": 6,
      "margin_buffer": 1.1,
      "max_contracts": 5,
      "pyramiding": false
    },
    "daily_limits": {
      "stop_new_entry": {
        "any": [
          {
            "lte": [
              {
                "ref": "day.net_pnl"
              },
              {
                "mul": [
                  {
                    "ref": "day.start_equity"
                  },
                  -0.02
                ]
              }
            ]
          },
          {
            "gte": [
              {
                "ref": "day.entry_fill_count"
              },
              3
            ]
          }
        ]
      }
    }
  },
  "execution": {
    "entry_fill_policy": "next_open",
    "slippage_rate": "0"
  },
  "initial_cash": "100000000",
  "report": null
}
```

**Trạng thái đánh giá**

                status  unevaluable_bars  evaluated_bars
0  PARTIALLY_EVALUABLE               910            5264

## 2. Kết quả tổng quan

- `initial_cash`, `final_equity`: vốn ban đầu và giá trị tài khoản cuối kỳ, theo đơn vị trong metadata.
- `realized_pnl`: lãi/lỗ ròng của các phần đã đóng, đã gồm chi phí mở được phân bổ và chi phí đóng.
- `unrealized_pnl`: lãi/lỗ chưa chốt. Với mô hình hợp đồng, tính theo chênh lệch giá và chiều LONG/SHORT; chi phí mở đã trừ vào `cash`.
- `total_return`: `(final_equity − initial_cash) / initial_cash`, hiển thị dưới dạng phần trăm.
- `total_fees`: tổng chi phí đã ghi nhận.

In [6]:
summary = result["summary"]
summary_view = {**summary, "total_return": f"{float(summary['total_return']):.2%}"}
display(pd.DataFrame([summary_view]))
display(Markdown(
    "### Kết luận nhanh\n"
    f"- **Giá trị cuối kỳ:** `{summary['final_equity']}` từ vốn `{summary['initial_cash']}` ({metadata['money_unit']}).\n"
    f"- **Tỷ suất sinh lời:** `{summary_view['total_return']}`.\n"
    f"- **Lãi/lỗ:** đã chốt `{summary['realized_pnl']}`, chưa chốt `{summary['unrealized_pnl']}`.\n"
    f"- **Tổng chi phí:** `{summary['total_fees']}`.\n"
    f"- **Hoạt động:** `{len(result['fills'])}` lần khớp, `{len(result['trades'])}` phần giao dịch đã đóng.\n"
    f"- **Cuối kỳ:** {'còn vị thế mở' if result['open_position'] else 'không còn vị thế mở'}."
))

,initial_cash,final_equity,realized_pnl,unrealized_pnl,total_return,total_fees
0,100000000,100924596,924596,0,0.92%,6665404

### Kết luận nhanh
- **Giá trị cuối kỳ:** `100924596` từ vốn `100000000` (VND).
- **Tỷ suất sinh lời:** `0.92%`.
- **Lãi/lỗ:** đã chốt `924596`, chưa chốt `0`.
- **Tổng chi phí:** `6665404`.
- **Hoạt động:** `306` lần khớp, `153` phần giao dịch đã đóng.
- **Cuối kỳ:** không còn vị thế mở.

In [7]:
def show_table(rows):
    frame = pd.DataFrame(rows)
    display(frame if not frame.empty else Markdown("_Không có dữ liệu._"))

## 3. Các lần khớp lệnh (`fills`)

- `side`: LONG/SHORT mở vị thế, CLOSE đóng toàn bộ hoặc một phần; `direction` là chiều vị thế.
- `fill_price`, `quantity`: giá khớp và số hợp đồng khớp.
- `fee`: tổng chi phí lần khớp; `exchange_fee`, `clearing_fee`, `broker_fee`, `pit` là từng khoản phí/thuế.
- `fill_time`: Open cho lệnh thị trường hoặc khi giá mở cửa vượt mức stop/target; chạm mức trong nến được ghi nhận ở Close theo quy ước OHLC.
- `bar_time`: Open của nến chứa lần khớp. `signal_time` của lệnh stop/target gắn với tín hiệu đặt lệnh gốc.
- `fill_id`, `order_id`, `position_id`: liên kết khớp lệnh với lệnh và vị thế.

Tín hiệu chưa khớp không xuất hiện trong bảng này.

In [8]:
show_table(result["fills"])

,fill_id,order_id,position_id,contract_code,direction,side,signal_time,fill_time,fill_price,bar_time,quantity,fee,exchange_fee,clearing_fee,broker_fee,pit
0,61ec03ab-d0f3-5b94-80fb-e96959cd1ece,a8a04063-99b0-5532-ba6d-5a6b8ac6650e,3aabe014-f4f3-5d5b-9cca-3b3efc2458cc,VN30F2604,SHORT,SHORT,2026-03-26T10:05:00+07:00,2026-03-26T10:05:00+07:00,1789.6,2026-03-26T10:05:00+07:00,1,20462,2700,2550,0,15212
1,6ebff0f6-8280-5139-8114-9413ebe8e037,2f266d8c-e020-5b1b-85f0-f2f3de7c93bb,3aabe014-f4f3-5d5b-9cca-3b3efc2458cc,VN30F2604,SHORT,CLOSE,2026-03-26T10:05:00+07:00,2026-03-26T10:20:00+07:00,1795.6,2026-03-26T10:15:00+07:00,1,20513,2700,2550,0,15263
2,febbf665-65f9-5572-ab4a-6f59535acaa8,7a41a5d1-37cf-58ad-b160-cb92af15d24d,1273cfdf-ebec-58ae-a0fa-15242ae64f5f,VN30F2604,SHORT,SHORT,2026-03-26T13:05:00+07:00,2026-03-26T13:05:00+07:00,1785.5,2026-03-26T13:05:00+07:00,1,20427,2700,2550,0,15177
3,dcb984b6-1537-55a7-a37b-d2d86a9e3cef,11f13059-1ccf-5cb6-a12b-f49a11ca7feb,1273cfdf-ebec-58ae-a0fa-15242ae64f5f,VN30F2604,SHORT,CLOSE,2026-03-26T13:05:00+07:00,2026-03-26T13:50:00+07:00,1791.5,2026-03-26T13:45:00+07:00,1,20478,2700,2550,0,15228
4,30cf1e31-fefe-5076-8da4-fb2c8d3475fa,fc80c37f-dec8-5dc6-a43d-07e271d9032a,161073cb-633b-5fb7-b8ff-f21bfe9c205f,VN30F2604,LONG,LONG,2026-03-27T13:15:00+07:00,2026-03-27T13:15:00+07:00,1808.3,2026-03-27T13:15:00+07:00,1,20621,2700,2550,0,15371
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301,5f6f9599-e65a-5927-8524-01125aa74ed4,69802cd0-8aa9-59fa-b1e5-0831c5403121,4f8c3fef-9712-5f52-bb2f-fe28d20b28b8,VN30F2609,SHORT,CLOSE,2026-09-14T13:35:00+07:00,2026-09-14T13:50:00+07:00,1925,2026-09-14T13:45:00+07:00,1,21613,2700,2550,0,16363
302,7fa528c2-b2ab-5c55-b0fd-c1e73dadde28,7c86bb40-505f-5d8c-a529-95f887955e00,a8fba7bb-64ed-5b51-b7b9-400f1a203586,VN30F2609,SHORT,SHORT,2026-09-14T13:55:00+07:00,2026-09-14T13:55:00+07:00,1924.2,2026-09-14T13:55:00+07:00,1,21606,2700,2550,0,16356
303,a3bc842a-0b6d-5b89-b84c-c039b07e3982,c02ba432-7018-5911-bd90-ce0871c56d1c,a8fba7bb-64ed-5b51-b7b9-400f1a203586,VN30F2609,SHORT,CLOSE,2026-09-14T13:55:00+07:00,2026-09-14T14:15:00+07:00,1918.2,2026-09-14T14:10:00+07:00,1,21555,2700,2550,0,16305
304,f5394f25-9d93-53d1-8299-513b3eede55b,d7a7cfc7-7609-5416-8594-141e0a71869c,baf2ad77-eed5-5d7e-9df0-a8f2456d59d9,VN30F2609,LONG,LONG,2026-09-15T13:50:00+07:00,2026-09-15T13:50:00+07:00,1948.2,2026-09-15T13:50:00+07:00,1,21810,2700,2550,0,16560
305,df039171-dca4-5785-9308-87380a798f89,68166d71-119d-5c51-a517-abc2b80bbe7d,baf2ad77-eed5-5d7e-9df0-a8f2456d59d9,VN30F2609,LONG,CLOSE,2026-09-15T14:20:00+07:00,2026-09-15T14:20:00+07:00,1952,2026-09-15T14:20:00+07:00,1,21842,2700,2550,0,16592

## 4. Các phần giao dịch đã đóng (`trades`)

Mỗi dòng là một phần đóng vị thế, liên kết với lần mở/đóng qua `entry_fill_id` và `exit_fill_id`.

- `entry_date`, `exit_date`, `entry_price`, `exit_price`: thời điểm và giá khớp mở/đóng.
- `quantity`: số hợp đồng của phần đóng; `direction`: chiều LONG/SHORT.
- `allocated_entry_cost`: chi phí mở phân bổ cho phần đóng; `fees` gồm khoản này và chi phí đóng.
- `net_pnl`: lãi/lỗ ròng sau chi phí; `close_reason`: lý do thoát do backend ghi nhận (TP1, TP2, STOP_LOSS, TRAILING_STOP, TIME_STOP…).

Ngoài ra, một vị thế có thể có nhiều dòng khi chốt từng phần.

In [9]:
show_table(result["trades"])

,trade_id,position_id,entry_fill_id,exit_fill_id,contract_code,close_reason,entry_date,exit_date,quantity,entry_price,exit_price,fees,net_pnl,direction,allocated_entry_cost
0,0576f1f5-4785-54cd-b5bf-b310705cceab,3aabe014-f4f3-5d5b-9cca-3b3efc2458cc,61ec03ab-d0f3-5b94-80fb-e96959cd1ece,6ebff0f6-8280-5139-8114-9413ebe8e037,VN30F2604,STOP_LOSS,2026-03-26T10:05:00+07:00,2026-03-26T10:20:00+07:00,1,1789.6,1795.6,40975,-640975,SHORT,20462
1,322e814e-6676-56ae-a0b7-fab7fa5c1b7b,1273cfdf-ebec-58ae-a0fa-15242ae64f5f,febbf665-65f9-5572-ab4a-6f59535acaa8,dcb984b6-1537-55a7-a37b-d2d86a9e3cef,VN30F2604,STOP_LOSS,2026-03-26T13:05:00+07:00,2026-03-26T13:50:00+07:00,1,1785.5,1791.5,40905,-640905,SHORT,20427
2,9a3fcb38-a399-5942-9506-d88226b2fa90,161073cb-633b-5fb7-b8ff-f21bfe9c205f,30cf1e31-fefe-5076-8da4-fb2c8d3475fa,f332e865-56ab-5a9d-abb8-c3ffef75b36e,VN30F2604,TP1,2026-03-27T13:15:00+07:00,2026-03-27T13:30:00+07:00,1,1808.3,1814.3,41293,558707,LONG,20621
3,f3079f97-ca0c-548a-b6de-afff19c06e31,2987fa34-7169-5a78-94b7-201b05bd47c0,af64c05e-0321-5541-a0e3-89f5cc594ec5,d03dce39-8c95-50e2-b41c-7984eca924d7,VN30F2604,TP1,2026-03-27T13:35:00+07:00,2026-03-27T13:45:00+07:00,1,1812.6,1818.6,41365,558635,LONG,20657
4,7325c449-9421-5429-a407-8a4201bfb9f8,bf89c7cb-c3e7-5ba4-9399-5dac19b42a18,ae14a874-01db-58ae-9c3f-52a1a21448bd,118728d0-d166-5939-91f8-79cde3d9aa18,VN30F2604,TP1,2026-03-27T13:50:00+07:00,2026-03-27T14:10:00+07:00,1,1818.8,1824.8,41471,558529,LONG,20710
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,39db3205-82e8-55f4-9259-fdc026d4335b,37bcfbe0-025b-5331-9630-6fb8c1d85c8e,ed08761f-1ae3-5746-aa06-c10212d232cc,4f252806-f0ef-5b63-9867-b3ef4780012f,VN30F2609,STOP_LOSS,2026-09-10T10:45:00+07:00,2026-09-10T11:30:00+07:00,1,1960.2,1966.2,43875,-643875,SHORT,21912
149,8cf5c44d-6ec1-5117-aada-5466f9a3f41e,3ff43b58-7081-5340-9143-e2980dbe101f,d15c065d-cd4f-55c0-8b71-5321fcf78621,1f197127-b3a4-56f3-bfcf-6288ea371ed5,VN30F2609,STOP_LOSS,2026-09-14T09:05:00+07:00,2026-09-14T09:35:00+07:00,1,1937.5,1943.5,43489,-643489,SHORT,21719
150,5833cefe-d62a-5fc0-91b2-281a00830841,4f8c3fef-9712-5f52-bb2f-fe28d20b28b8,08c4436e-239b-59c5-95bd-1b8081010723,5f6f9599-e65a-5927-8524-01125aa74ed4,VN30F2609,TP1,2026-09-14T13:35:00+07:00,2026-09-14T13:50:00+07:00,1,1931,1925,43277,556723,SHORT,21664
151,830af3e6-a754-56ca-a479-8fc05db3af18,a8fba7bb-64ed-5b51-b7b9-400f1a203586,7fa528c2-b2ab-5c55-b0fd-c1e73dadde28,a3bc842a-0b6d-5b89-b84c-c039b07e3982,VN30F2609,TP1,2026-09-14T13:55:00+07:00,2026-09-14T14:15:00+07:00,1,1924.2,1918.2,43161,556839,SHORT,21606
152,819cbdd8-10c1-544d-964f-441c31033377,baf2ad77-eed5-5d7e-9df0-a8f2456d59d9,f5394f25-9d93-53d1-8299-513b3eede55b,df039171-dca4-5785-9308-87380a798f89,VN30F2609,FORCED_EXIT,2026-09-15T13:50:00+07:00,2026-09-15T14:20:00+07:00,1,1948.2,1952,43652,336348,LONG,21810

## 5. Vị thế cuối kỳ

- `position_id`, `entry_fill_id`: vị thế và lần khớp mở tương ứng.
- `direction`, `entry_time`, `entry_price`: chiều, thời điểm và giá mở.
- `initial_quantity`, `quantity`: số hợp đồng ban đầu và còn lại.
- `remaining_entry_cost`: chi phí mở chưa phân bổ vào các phần đã đóng.
- `unrealized_pnl`, `strategy_details`: lãi/lỗ chưa chốt và trạng thái chiến lược backend trả về.

`open_position = null` nghĩa là không còn vị thế. Mô phỏng giao dịch đang không hỗ trợ giữ qua đêm; API báo lỗi nếu cuối báo cáo vẫn còn vị thế cần thoát.

In [10]:
position = [result["open_position"]] if result["open_position"] else []
show_table(position)

_Không có dữ liệu._

## 6. Tín hiệu, lệnh và đánh giá chiến lược

- `signals`: ý định giao dịch; `sequence_no` là thứ tự sự kiện, `reason` là lý do phát tín hiệu.
- `orders`: liên kết với `signals` qua `signal_id`; trạng thái `filled`, `rejected`, hoặc `pending` của mô hình hợp đồng. `reason` ghi lý do xử lý. Lệnh mở còn chờ cuối báo cáo bị từ chối với `END_OF_REPORT`.
- Tín hiệu xét tại Close chỉ có thể khớp ở Open hợp lệ kế tiếp. Lệnh stop/target trong nến tuân theo quy tắc thoát trong payload và quy ước thời gian đã nêu.
- `evaluations`: thời điểm xét, trạng thái, lý do, số mẫu thị trường, thời điểm dữ liệu khả dụng và giá trị/thời điểm chỉ báo. Nhóm này và `evaluation_status` chỉ có khi backend ghi nhận đánh giá.

`UNEVALUABLE`: thiếu dữ liệu để đánh giá trên khoảng nến này.

In [11]:
display(Markdown("**Tín hiệu**"))
show_table(result["signals"])
display(Markdown("**Lệnh**"))
show_table(result["orders"])
display(Markdown("**Đánh giá chiến lược**"))
show_table(result.get("evaluations", []))

**Tín hiệu**

,signal_id,sequence_no,signal_time,side,reason
0,450d3728-8fba-53bc-bb0b-08fc1fead60e,1,2026-03-26T10:05:00+07:00,SHORT,ENTRY
1,1ae8961a-ebe9-5da3-ab42-f28fd760b06b,2,2026-03-26T10:05:00+07:00,CLOSE,STOP_LOSS
2,6fb8287e-b451-51ec-9628-7958ab4757ad,3,2026-03-26T13:05:00+07:00,SHORT,ENTRY
3,2668d853-b43d-50c8-b9ad-45ec133bd031,4,2026-03-26T13:05:00+07:00,CLOSE,STOP_LOSS
4,1e7d7315-d316-5a8e-83da-40287f746ae4,5,2026-03-27T13:15:00+07:00,LONG,ENTRY
...,...,...,...,...,...
301,d6c98cee-1115-5ba6-a414-18bc8da5bca4,302,2026-09-14T13:35:00+07:00,CLOSE,TP1
302,31943aaa-c146-5bc4-bac3-fcd9b45533bf,303,2026-09-14T13:55:00+07:00,SHORT,ENTRY
303,e3e6e0d6-b472-54e3-b63b-7cb646e2e321,304,2026-09-14T13:55:00+07:00,CLOSE,TP1
304,fbed4be9-b184-5f7b-ae52-8214db652b1d,305,2026-09-15T13:50:00+07:00,LONG,ENTRY
305,70346b63-d13c-5a00-88b0-00a60ed026e0,306,2026-09-15T14:20:00+07:00,CLOSE,FORCED_EXIT

**Lệnh**

,order_id,signal_id,created_time,side,status,reason,position_id
0,a8a04063-99b0-5532-ba6d-5a6b8ac6650e,450d3728-8fba-53bc-bb0b-08fc1fead60e,2026-03-26T10:05:00+07:00,SHORT,filled,NaN,3aabe014-f4f3-5d5b-9cca-3b3efc2458cc
1,2f266d8c-e020-5b1b-85f0-f2f3de7c93bb,1ae8961a-ebe9-5da3-ab42-f28fd760b06b,2026-03-26T10:05:00+07:00,CLOSE,filled,STOP_LOSS,3aabe014-f4f3-5d5b-9cca-3b3efc2458cc
2,7a41a5d1-37cf-58ad-b160-cb92af15d24d,6fb8287e-b451-51ec-9628-7958ab4757ad,2026-03-26T13:05:00+07:00,SHORT,filled,NaN,1273cfdf-ebec-58ae-a0fa-15242ae64f5f
3,11f13059-1ccf-5cb6-a12b-f49a11ca7feb,2668d853-b43d-50c8-b9ad-45ec133bd031,2026-03-26T13:05:00+07:00,CLOSE,filled,STOP_LOSS,1273cfdf-ebec-58ae-a0fa-15242ae64f5f
4,fc80c37f-dec8-5dc6-a43d-07e271d9032a,1e7d7315-d316-5a8e-83da-40287f746ae4,2026-03-27T13:15:00+07:00,LONG,filled,NaN,161073cb-633b-5fb7-b8ff-f21bfe9c205f
...,...,...,...,...,...,...,...
301,69802cd0-8aa9-59fa-b1e5-0831c5403121,d6c98cee-1115-5ba6-a414-18bc8da5bca4,2026-09-14T13:35:00+07:00,CLOSE,filled,TP1,4f8c3fef-9712-5f52-bb2f-fe28d20b28b8
302,7c86bb40-505f-5d8c-a529-95f887955e00,31943aaa-c146-5bc4-bac3-fcd9b45533bf,2026-09-14T13:55:00+07:00,SHORT,filled,NaN,a8fba7bb-64ed-5b51-b7b9-400f1a203586
303,c02ba432-7018-5911-bd90-ce0871c56d1c,e3e6e0d6-b472-54e3-b63b-7cb646e2e321,2026-09-14T13:55:00+07:00,CLOSE,filled,TP1,a8fba7bb-64ed-5b51-b7b9-400f1a203586
304,d7a7cfc7-7609-5416-8594-141e0a71869c,fbed4be9-b184-5f7b-ae52-8214db652b1d,2026-09-15T13:50:00+07:00,LONG,filled,NaN,baf2ad77-eed5-5d7e-9df0-a8f2456d59d9
305,68166d71-119d-5c51-a517-abc2b80bbe7d,70346b63-d13c-5a00-88b0-00a60ed026e0,2026-09-15T14:20:00+07:00,CLOSE,filled,NaN,baf2ad77-eed5-5d7e-9df0-a8f2456d59d9

**Đánh giá chiến lược**

,time,status,reason,market_sample_count,market_available_at,indicator_times,indicators
0,2026-03-16T09:05:00+07:00,UNEVALUABLE,Missing value for reference: WARMUP:trade_data,0,NaN,"{'ema5': '2026-03-16T09:00:00+07:00', 'bb.midd...","{'sma20': None, 'ema5': None, 'bb.middle': Non..."
1,2026-03-16T09:10:00+07:00,UNEVALUABLE,Missing value for reference: WARMUP:trade_data,0,NaN,"{'ema5': '2026-03-16T09:05:00+07:00', 'bb.midd...","{'sma20': None, 'ema5': None, 'bb.middle': Non..."
2,2026-03-16T09:15:00+07:00,UNEVALUABLE,Missing value for reference: WARMUP:trade_data,0,NaN,"{'ema5': '2026-03-16T09:10:00+07:00', 'bb.midd...","{'sma20': None, 'ema5': None, 'bb.middle': Non..."
3,2026-03-16T09:20:00+07:00,UNEVALUABLE,Missing value for reference: WARMUP:trade_data,0,NaN,"{'ema5': '2026-03-16T09:15:00+07:00', 'bb.midd...","{'sma20': None, 'ema5': None, 'bb.middle': Non..."
4,2026-03-16T09:25:00+07:00,UNEVALUABLE,Missing value for reference: WARMUP:trade_data,0,NaN,"{'ema5': '2026-03-16T09:20:00+07:00', 'bb.midd...","{'sma20': None, 'ema5': '1846.0', 'bb.middle':..."
...,...,...,...,...,...,...,...
6169,2026-09-15T14:15:00+07:00,EVALUABLE,NO_SIGNAL,5680,2026-09-15T14:15:00+07:00,"{'sma20': '2026-09-15T14:10:00+07:00', 'ema5':...","{'sma20': '1804.692', 'ema5': '1948.2146750924..."
6170,2026-09-15T14:20:00+07:00,EVALUABLE,FORCED_EXIT,5681,2026-09-15T14:20:00+07:00,"{'sma20': '2026-09-15T14:15:00+07:00', 'ema5':...","{'sma20': '1805.1985', 'ema5': '1949.476450061..."
6171,2026-09-15T14:25:00+07:00,EVALUABLE,OUTSIDE_ENTRY_WINDOW,5682,2026-09-15T14:25:00+07:00,"{'sma20': '2026-09-15T14:20:00+07:00', 'ema5':...","{'sma20': '1805.662', 'ema5': '1948.4843000411..."
6172,2026-09-15T14:30:00+07:00,EVALUABLE,OUTSIDE_ENTRY_WINDOW,5683,2026-09-15T14:30:00+07:00,"{'sma20': '2026-09-15T14:25:00+07:00', 'ema5':...","{'sma20': '1806.1545', 'ema5': '1948.022866694..."
6173,2026-09-15T14:50:00+07:00,EVALUABLE,OUTSIDE_ENTRY_WINDOW,5683,2026-09-15T14:30:00+07:00,"{'sma20': '2026-09-15T14:25:00+07:00', 'ema5':...","{'sma20': '1806.1545', 'ema5': '1948.022866694..."

## 7. Diễn biến tài khoản (`equity_history`)

Mỗi dòng ghi nhận tài khoản tại Close của nến, sau các lần khớp thuộc nến đó.

- `cash`: tiền tài khoản sau chi phí và lãi/lỗ phát sinh từ các phần đóng.
- `quantity`, `unrealized_pnl`: số hợp đồng còn giữ và lãi/lỗ chưa chốt.
- `equity = cash + unrealized_pnl` với mô hình hợp đồng.
- `required_margin`: ký quỹ yêu cầu theo giá đánh dấu; `available_cash = equity − required_margin`.
- `margin_breach`: giá trị tài khoản thấp hơn ký quỹ yêu cầu.

Mô hình hợp đồng không trả `market_value`. Nếu chọn payload normalized, backend trả trường này và dùng `equity = cash + market_value`.

In [12]:
show_table(result["equity_history"])

,trading_date,cash,quantity,unrealized_pnl,equity,required_margin,available_cash,margin_breach
0,2026-03-16T09:05:00+07:00,100000000,0,0,100000000,0,100000000,False
1,2026-03-16T09:10:00+07:00,100000000,0,0,100000000,0,100000000,False
2,2026-03-16T09:15:00+07:00,100000000,0,0,100000000,0,100000000,False
3,2026-03-16T09:20:00+07:00,100000000,0,0,100000000,0,100000000,False
4,2026-03-16T09:25:00+07:00,100000000,0,0,100000000,0,100000000,False
...,...,...,...,...,...,...,...,...
6169,2026-09-15T14:15:00+07:00,100566438,1,290000,100856438,33168700,67687738,False
6170,2026-09-15T14:20:00+07:00,100566438,1,380000,100946438,33184000,67762438,False
6171,2026-09-15T14:25:00+07:00,100924596,0,0,100924596,0,100924596,False
6172,2026-09-15T14:30:00+07:00,100924596,0,0,100924596,0,100924596,False
6173,2026-09-15T14:50:00+07:00,100924596,0,0,100924596,0,100924596,False